declare namespace Form.quote.Main {
  namespace ProjectInformation {
    namespace Tabs {
      interface ProjectPriceListsTab extends Xrm.SectionCollectionBase {
        get(name: "ProjectPriceListsSection"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface QuoteLinesTab extends Xrm.SectionCollectionBase {
        get(name: "DynamicProperties"): Xrm.PageSection;
        get(name: "ProductLinesSection"): Xrm.PageSection;
        get(name: "ProjectLinesSection"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Summary_tab extends Xrm.SectionCollectionBase {
        get(name: "Summary_tab_section_8"): Xrm.PageSection;
        get(name: "Summary_tab_section_9"): Xrm.PageSection;
        get(name: "addresses"): Xrm.PageSection;
        get(name: "description_section"): Xrm.PageSection;
        get(name: "quote information"): Xrm.PageSection;
        get(name: "shipping information"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface competive_analysis_tab extends Xrm.SectionCollectionBase {
        get(name: "Summary_tab_section_10"): Xrm.PageSection;
        get(name: "analytics_tab_section_5"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface profitability_analytics_tab extends Xrm.SectionCollectionBase {
        get(name: "analyticResultSection"): Xrm.PageSection;
        get(name: "analyticsChartDetailsSection"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface quoteAnaylsis_tab extends Xrm.SectionCollectionBase {
        get(name: "tab_6_section_1"): Xrm.PageSection;
        get(name: "tab_6_section_2"): Xrm.PageSection;
        get(name: "tab_6_section_3"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "billto_composite"): Xrm.Attribute<string>;
      get(name: "billto_contactname"): Xrm.Attribute<string>;
      get(name: "billto_name"): Xrm.Attribute<string>;
      get(name: "customerid"): Xrm.LookupAttribute<"account" | "contact">;
      get(name: "description"): Xrm.Attribute<string>;
      get(name: "effectivefrom"): Xrm.DateAttribute;
      get(name: "effectiveto"): Xrm.DateAttribute;
      get(name: "expireson"): Xrm.DateAttribute;
      get(name: "freighttermscode"): Xrm.OptionSetAttribute<quote_freighttermscode>;
      get(name: "msdyn_accountmanagerid"): Xrm.LookupAttribute<"systemuser">;
      get(name: "msdyn_adjustedgrossmargin"): Xrm.NumberAttribute;
      get(name: "msdyn_competitive"): Xrm.OptionSetAttribute<msdyn_competitive>;
      get(name: "msdyn_contractorganizationalunitid"): Xrm.LookupAttribute<"msdyn_organizationalunit">;
      get(name: "msdyn_customerbudgetrollup"): Xrm.NumberAttribute;
      get(name: "msdyn_estimatedbudget"): Xrm.OptionSetAttribute<msdyn_budgetestimate>;
      get(name: "msdyn_estimatedcompletionrollup"): Xrm.DateAttribute;
      get(name: "msdyn_estimatedschedule"): Xrm.OptionSetAttribute<msdyn_schedule>;
      get(name: "msdyn_grossmargin"): Xrm.NumberAttribute;
      get(name: "msdyn_ordertype"): Xrm.OptionSetAttribute<msdyn_quote_msdyn_ordertype>;
      get(name: "msdyn_profitability"): Xrm.OptionSetAttribute<msdyn_profitability>;
      get(name: "msdyn_totalchargeablecostrollup"): Xrm.NumberAttribute;
      get(name: "msdyn_totalnonchargeablecostrollup"): Xrm.NumberAttribute;
      get(name: "name"): Xrm.Attribute<string>;
      get(name: "opportunityid"): Xrm.LookupAttribute<"opportunity">;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "paymenttermscode"): Xrm.OptionSetAttribute<quote_paymenttermscode>;
      get(name: "pricelevelid"): Xrm.LookupAttribute<"pricelevel">;
      get(name: "quotenumber"): Xrm.Attribute<string>;
      get(name: "requestdeliveryby"): Xrm.DateAttribute;
      get(name: "revisionnumber"): Xrm.NumberAttribute;
      get(name: "shippingmethodcode"): Xrm.OptionSetAttribute<quote_shippingmethodcode>;
      get(name: "shipto_composite"): Xrm.Attribute<string>;
      get(name: "statecode"): Xrm.OptionSetAttribute<quote_statecode>;
      get(name: "statuscode"): Xrm.OptionSetAttribute<quote_statuscode>;
      get(name: "totalamount"): Xrm.NumberAttribute;
      get(name: "totalamount_base"): Xrm.NumberAttribute;
      get(name: "transactioncurrencyid"): Xrm.LookupAttribute<"transactioncurrency">;
      get(name: "willcall"): Xrm.OptionSetAttribute<boolean>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "DynamicPropertiesList_LinkControl"): Xrm.BaseControl;
      get(name: "ProjectPriceListsSubGrid"): Xrm.SubGridControl<"msdyn_quotepricelist">;
      get(name: "ProjectQuoteLines"): Xrm.SubGridControl<"quotedetail">;
      get(name: "billto_composite"): Xrm.StringControl;
      get(name: "billto_contactname"): Xrm.StringControl;
      get(name: "billto_name"): Xrm.StringControl;
      get(name: "costRevenueDistribution"): Xrm.SubGridControl<"msdyn_quotelineanalyticsbreakdown">;
      get(name: "customerid"): Xrm.LookupControl<"account" | "contact">;
      get(name: "description"): Xrm.StringControl;
      get(name: "effectivefrom"): Xrm.DateControl;
      get(name: "effectiveto"): Xrm.DateControl;
      get(name: "expireson"): Xrm.DateControl;
      get(name: "freighttermscode"): Xrm.OptionSetControl<quote_freighttermscode>;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "header_statecode"): Xrm.OptionSetControl<quote_statecode>;
      get(name: "header_statuscode"): Xrm.OptionSetControl<quote_statuscode>;
      get(name: "header_totalamount"): Xrm.NumberControl;
      get(name: "msdyn_accountmanagerid"): Xrm.LookupControl<"systemuser">;
      get(name: "msdyn_adjustedgrossmargin"): Xrm.NumberControl;
      get(name: "msdyn_adjustedgrossmargin1"): Xrm.NumberControl;
      get(name: "msdyn_competitive"): Xrm.OptionSetControl<msdyn_competitive>;
      get(name: "msdyn_competitive1"): Xrm.OptionSetControl<msdyn_competitive>;
      get(name: "msdyn_contractorganizationalunitid"): Xrm.LookupControl<"msdyn_organizationalunit">;
      get(name: "msdyn_customerbudgetrollup"): Xrm.NumberControl;
      get(name: "msdyn_estimatedbudget"): Xrm.OptionSetControl<msdyn_budgetestimate>;
      get(name: "msdyn_estimatedbudget1"): Xrm.OptionSetControl<msdyn_budgetestimate>;
      get(name: "msdyn_estimatedcompletionrollup"): Xrm.DateControl;
      get(name: "msdyn_estimatedschedule"): Xrm.OptionSetControl<msdyn_schedule>;
      get(name: "msdyn_estimatedschedule1"): Xrm.OptionSetControl<msdyn_schedule>;
      get(name: "msdyn_grossmargin"): Xrm.NumberControl;
      get(name: "msdyn_grossmargin1"): Xrm.NumberControl;
      get(name: "msdyn_ordertype"): Xrm.OptionSetControl<msdyn_quote_msdyn_ordertype>;
      get(name: "msdyn_profitability"): Xrm.OptionSetControl<msdyn_profitability>;
      get(name: "msdyn_profitability1"): Xrm.OptionSetControl<msdyn_profitability>;
      get(name: "msdyn_totalchargeablecostrollup"): Xrm.NumberControl;
      get(name: "msdyn_totalnonchargeablecostrollup"): Xrm.NumberControl;
      get(name: "name"): Xrm.StringControl;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: "opportunityid"): Xrm.LookupControl<"opportunity">;
      get(name: "paymenttermscode"): Xrm.OptionSetControl<quote_paymenttermscode>;
      get(name: "pricelevelid"): Xrm.LookupControl<"pricelevel">;
      get(name: "quoteLineComparisonGrid"): Xrm.SubGridControl<"quotedetail">;
      get(name: "quoteLineDetailAnalysis"): Xrm.SubGridControl<"msdyn_quotelineanalyticsbreakdown">;
      get(name: "quotedetailsGrid"): Xrm.SubGridControl<"quotedetail">;
      get(name: "quotenumber"): Xrm.StringControl;
      get(name: "requestdeliveryby"): Xrm.DateControl;
      get(name: "requestdeliveryby1"): Xrm.DateControl;
      get(name: "revisionnumber"): Xrm.NumberControl;
      get(name: "shippingmethodcode"): Xrm.OptionSetControl<quote_shippingmethodcode>;
      get(name: "shipto_composite"): Xrm.StringControl;
      get(name: "statuscode"): Xrm.OptionSetControl<quote_statuscode>;
      get(name: "totalQuoteAmountComparisonGrid"): Xrm.SubGridControl<"quotedetail">;
      get(name: "totalamount"): Xrm.NumberControl;
      get(name: "totalamount1"): Xrm.NumberControl;
      get(name: "totalamount_base"): Xrm.NumberControl;
      get(name: "transactioncurrencyid"): Xrm.LookupControl<"transactioncurrency">;
      get(name: "willcall"): Xrm.OptionSetControl<boolean>;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "ProjectPriceListsTab"): Xrm.PageTab<Tabs.ProjectPriceListsTab>;
      get(name: "QuoteLinesTab"): Xrm.PageTab<Tabs.QuoteLinesTab>;
      get(name: "Summary_tab"): Xrm.PageTab<Tabs.Summary_tab>;
      get(name: "competive_analysis_tab"): Xrm.PageTab<Tabs.competive_analysis_tab>;
      get(name: "profitability_analytics_tab"): Xrm.PageTab<Tabs.profitability_analytics_tab>;
      get(name: "quoteAnaylsis_tab"): Xrm.PageTab<Tabs.quoteAnaylsis_tab>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface ProjectInformation extends Xrm.PageBase<ProjectInformation.Attributes,ProjectInformation.Tabs,ProjectInformation.Controls> {
    getAttribute(attributeName: "billto_composite"): Xrm.Attribute<string>;
    getAttribute(attributeName: "billto_contactname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "billto_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "customerid"): Xrm.LookupAttribute<"account" | "contact">;
    getAttribute(attributeName: "description"): Xrm.Attribute<string>;
    getAttribute(attributeName: "effectivefrom"): Xrm.DateAttribute;
    getAttribute(attributeName: "effectiveto"): Xrm.DateAttribute;
    getAttribute(attributeName: "expireson"): Xrm.DateAttribute;
    getAttribute(attributeName: "freighttermscode"): Xrm.OptionSetAttribute<quote_freighttermscode>;
    getAttribute(attributeName: "msdyn_accountmanagerid"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "msdyn_adjustedgrossmargin"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_competitive"): Xrm.OptionSetAttribute<msdyn_competitive>;
    getAttribute(attributeName: "msdyn_contractorganizationalunitid"): Xrm.LookupAttribute<"msdyn_organizationalunit">;
    getAttribute(attributeName: "msdyn_customerbudgetrollup"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_estimatedbudget"): Xrm.OptionSetAttribute<msdyn_budgetestimate>;
    getAttribute(attributeName: "msdyn_estimatedcompletionrollup"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_estimatedschedule"): Xrm.OptionSetAttribute<msdyn_schedule>;
    getAttribute(attributeName: "msdyn_grossmargin"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_ordertype"): Xrm.OptionSetAttribute<msdyn_quote_msdyn_ordertype>;
    getAttribute(attributeName: "msdyn_profitability"): Xrm.OptionSetAttribute<msdyn_profitability>;
    getAttribute(attributeName: "msdyn_totalchargeablecostrollup"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_totalnonchargeablecostrollup"): Xrm.NumberAttribute;
    getAttribute(attributeName: "name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "opportunityid"): Xrm.LookupAttribute<"opportunity">;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "paymenttermscode"): Xrm.OptionSetAttribute<quote_paymenttermscode>;
    getAttribute(attributeName: "pricelevelid"): Xrm.LookupAttribute<"pricelevel">;
    getAttribute(attributeName: "quotenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "requestdeliveryby"): Xrm.DateAttribute;
    getAttribute(attributeName: "revisionnumber"): Xrm.NumberAttribute;
    getAttribute(attributeName: "shippingmethodcode"): Xrm.OptionSetAttribute<quote_shippingmethodcode>;
    getAttribute(attributeName: "shipto_composite"): Xrm.Attribute<string>;
    getAttribute(attributeName: "statecode"): Xrm.OptionSetAttribute<quote_statecode>;
    getAttribute(attributeName: "statuscode"): Xrm.OptionSetAttribute<quote_statuscode>;
    getAttribute(attributeName: "totalamount"): Xrm.NumberAttribute;
    getAttribute(attributeName: "totalamount_base"): Xrm.NumberAttribute;
    getAttribute(attributeName: "transactioncurrencyid"): Xrm.LookupAttribute<"transactioncurrency">;
    getAttribute(attributeName: "willcall"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: string): undefined;
    getAttribute(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Attribute<any>>): Xrm.Attribute<any>[];
    getControl(controlName: "DynamicPropertiesList_LinkControl"): Xrm.BaseControl;
    getControl(controlName: "ProjectPriceListsSubGrid"): Xrm.SubGridControl<"msdyn_quotepricelist">;
    getControl(controlName: "ProjectQuoteLines"): Xrm.SubGridControl<"quotedetail">;
    getControl(controlName: "billto_composite"): Xrm.StringControl;
    getControl(controlName: "billto_contactname"): Xrm.StringControl;
    getControl(controlName: "billto_name"): Xrm.StringControl;
    getControl(controlName: "costRevenueDistribution"): Xrm.SubGridControl<"msdyn_quotelineanalyticsbreakdown">;
    getControl(controlName: "customerid"): Xrm.LookupControl<"account" | "contact">;
    getControl(controlName: "description"): Xrm.StringControl;
    getControl(controlName: "effectivefrom"): Xrm.DateControl;
    getControl(controlName: "effectiveto"): Xrm.DateControl;
    getControl(controlName: "expireson"): Xrm.DateControl;
    getControl(controlName: "freighttermscode"): Xrm.OptionSetControl<quote_freighttermscode>;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "header_statecode"): Xrm.OptionSetControl<quote_statecode>;
    getControl(controlName: "header_statuscode"): Xrm.OptionSetControl<quote_statuscode>;
    getControl(controlName: "header_totalamount"): Xrm.NumberControl;
    getControl(controlName: "msdyn_accountmanagerid"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "msdyn_adjustedgrossmargin"): Xrm.NumberControl;
    getControl(controlName: "msdyn_adjustedgrossmargin1"): Xrm.NumberControl;
    getControl(controlName: "msdyn_competitive"): Xrm.OptionSetControl<msdyn_competitive>;
    getControl(controlName: "msdyn_competitive1"): Xrm.OptionSetControl<msdyn_competitive>;
    getControl(controlName: "msdyn_contractorganizationalunitid"): Xrm.LookupControl<"msdyn_organizationalunit">;
    getControl(controlName: "msdyn_customerbudgetrollup"): Xrm.NumberControl;
    getControl(controlName: "msdyn_estimatedbudget"): Xrm.OptionSetControl<msdyn_budgetestimate>;
    getControl(controlName: "msdyn_estimatedbudget1"): Xrm.OptionSetControl<msdyn_budgetestimate>;
    getControl(controlName: "msdyn_estimatedcompletionrollup"): Xrm.DateControl;
    getControl(controlName: "msdyn_estimatedschedule"): Xrm.OptionSetControl<msdyn_schedule>;
    getControl(controlName: "msdyn_estimatedschedule1"): Xrm.OptionSetControl<msdyn_schedule>;
    getControl(controlName: "msdyn_grossmargin"): Xrm.NumberControl;
    getControl(controlName: "msdyn_grossmargin1"): Xrm.NumberControl;
    getControl(controlName: "msdyn_ordertype"): Xrm.OptionSetControl<msdyn_quote_msdyn_ordertype>;
    getControl(controlName: "msdyn_profitability"): Xrm.OptionSetControl<msdyn_profitability>;
    getControl(controlName: "msdyn_profitability1"): Xrm.OptionSetControl<msdyn_profitability>;
    getControl(controlName: "msdyn_totalchargeablecostrollup"): Xrm.NumberControl;
    getControl(controlName: "msdyn_totalnonchargeablecostrollup"): Xrm.NumberControl;
    getControl(controlName: "name"): Xrm.StringControl;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: "opportunityid"): Xrm.LookupControl<"opportunity">;
    getControl(controlName: "paymenttermscode"): Xrm.OptionSetControl<quote_paymenttermscode>;
    getControl(controlName: "pricelevelid"): Xrm.LookupControl<"pricelevel">;
    getControl(controlName: "quoteLineComparisonGrid"): Xrm.SubGridControl<"quotedetail">;
    getControl(controlName: "quoteLineDetailAnalysis"): Xrm.SubGridControl<"msdyn_quotelineanalyticsbreakdown">;
    getControl(controlName: "quotedetailsGrid"): Xrm.SubGridControl<"quotedetail">;
    getControl(controlName: "quotenumber"): Xrm.StringControl;
    getControl(controlName: "requestdeliveryby"): Xrm.DateControl;
    getControl(controlName: "requestdeliveryby1"): Xrm.DateControl;
    getControl(controlName: "revisionnumber"): Xrm.NumberControl;
    getControl(controlName: "shippingmethodcode"): Xrm.OptionSetControl<quote_shippingmethodcode>;
    getControl(controlName: "shipto_composite"): Xrm.StringControl;
    getControl(controlName: "statuscode"): Xrm.OptionSetControl<quote_statuscode>;
    getControl(controlName: "totalQuoteAmountComparisonGrid"): Xrm.SubGridControl<"quotedetail">;
    getControl(controlName: "totalamount"): Xrm.NumberControl;
    getControl(controlName: "totalamount1"): Xrm.NumberControl;
    getControl(controlName: "totalamount_base"): Xrm.NumberControl;
    getControl(controlName: "transactioncurrencyid"): Xrm.LookupControl<"transactioncurrency">;
    getControl(controlName: "willcall"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: string): undefined;
    getControl(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Control<any>>): Xrm.Control<any>[];
  }
}
