interface ActivityPointer_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  community?: socialprofile_community | null;
  createdon?: Date | null;
  deliverylastattemptedon?: Date | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  description?: string | null;
  exchangeitemid?: string | null;
  exchangerate?: number | null;
  exchangeweblink?: string | null;
  instancetypecode?: activitypointer_instancetypecode | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  postponeactivityprocessinguntil?: Date | null;
  prioritycode?: activitypointer_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  senton?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: activitypointer_statecode | null;
  statuscode?: activitypointer_statuscode | null;
  subject?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface ActivityPointer_Relationships {
  ActivityPointer_AsyncOperations?: AsyncOperation_Result[] | null;
  ActivityPointer_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  ActivityPointer_CampaignActivityItems?: CampaignActivityItem_Result[] | null;
  ActivityPointer_QueueItem?: QueueItem_Result[] | null;
  CreatedActivity_BulkOperationLogs?: BulkOperationLog_Result[] | null;
  activity_campaignresponse?: CampaignResponse_Result[] | null;
  activity_pointer_BulkOperation?: BulkOperation_Result[] | null;
  activity_pointer_BulkOperation_logs?: BulkOperationLog_Result[] | null;
  activity_pointer_activity_mime_attachment?: ActivityMimeAttachment_Result[] | null;
  activity_pointer_appointment?: Appointment_Result[] | null;
  activity_pointer_campaignactivity?: CampaignActivity_Result[] | null;
  activity_pointer_campaignresponse?: CampaignResponse_Result[] | null;
  activity_pointer_email?: Email_Result[] | null;
  activity_pointer_email_hash?: EmailHash_Result[] | null;
  activity_pointer_fax?: Fax_Result[] | null;
  activity_pointer_incident_resolution?: IncidentResolution_Result[] | null;
  activity_pointer_letter?: Letter_Result[] | null;
  activity_pointer_msdyn_approval?: msdyn_approval_Result[] | null;
  activity_pointer_msdyn_bookingalert?: msdyn_bookingalert_Result[] | null;
  activity_pointer_msdyn_ocliveworkitem?: msdyn_ocliveworkitem_Result[] | null;
  activity_pointer_msdyn_ocoutboundmessage?: msdyn_ocoutboundmessage_Result[] | null;
  activity_pointer_msdyn_ocsession?: msdyn_ocsession_Result[] | null;
  activity_pointer_msfp_alert?: msfp_alert_Result[] | null;
  activity_pointer_msfp_surveyinvite?: msfp_surveyinvite_Result[] | null;
  activity_pointer_msfp_surveyresponse?: msfp_surveyresponse_Result[] | null;
  activity_pointer_opportunity_close?: OpportunityClose_Result[] | null;
  activity_pointer_order_close?: OrderClose_Result[] | null;
  activity_pointer_phonecall?: PhoneCall_Result[] | null;
  activity_pointer_quote_close?: QuoteClose_Result[] | null;
  activity_pointer_recurrencerule?: RecurrenceRule_Result[] | null;
  activity_pointer_recurringappointmentmaster?: RecurringAppointmentMaster_Result[] | null;
  activity_pointer_service_appointment?: ServiceAppointment_Result[] | null;
  activity_pointer_socialactivity?: SocialActivity_Result[] | null;
  activity_pointer_task?: Task_Result[] | null;
  activitypointer_activity_parties?: ActivityParty_Result[] | null;
  activitypointer_connections1?: Connection_Result[] | null;
  activitypointer_connections2?: Connection_Result[] | null;
  regardingobjectid_account?: Account_Result | null;
  regardingobjectid_bookableresourcebooking?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation?: BulkOperation_Result | null;
  regardingobjectid_campaign?: Campaign_Result | null;
  regardingobjectid_campaignactivity?: CampaignActivity_Result | null;
  regardingobjectid_contact?: Contact_Result | null;
  regardingobjectid_contract?: Contract_Result | null;
  regardingobjectid_entitlement?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate?: EntitlementTemplate_Result | null;
  regardingobjectid_incident?: Incident_Result | null;
  regardingobjectid_invoice?: Invoice_Result | null;
  regardingobjectid_knowledgearticle?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead?: Lead_Result | null;
  regardingobjectid_msdyn_agreement?: msdyn_agreement_Result | null;
  regardingobjectid_msdyn_agreementbookingdate?: msdyn_agreementbookingdate_Result | null;
  regardingobjectid_msdyn_agreementbookingincident?: msdyn_agreementbookingincident_Result | null;
  regardingobjectid_msdyn_agreementbookingproduct?: msdyn_agreementbookingproduct_Result | null;
  regardingobjectid_msdyn_agreementbookingservice?: msdyn_agreementbookingservice_Result | null;
  regardingobjectid_msdyn_agreementbookingservicetask?: msdyn_agreementbookingservicetask_Result | null;
  regardingobjectid_msdyn_agreementbookingsetup?: msdyn_agreementbookingsetup_Result | null;
  regardingobjectid_msdyn_agreementinvoicedate?: msdyn_agreementinvoicedate_Result | null;
  regardingobjectid_msdyn_agreementinvoiceproduct?: msdyn_agreementinvoiceproduct_Result | null;
  regardingobjectid_msdyn_agreementinvoicesetup?: msdyn_agreementinvoicesetup_Result | null;
  regardingobjectid_msdyn_bookingalertstatus?: msdyn_bookingalertstatus_Result | null;
  regardingobjectid_msdyn_bookingrule?: msdyn_bookingrule_Result | null;
  regardingobjectid_msdyn_bookingtimestamp?: msdyn_bookingtimestamp_Result | null;
  regardingobjectid_msdyn_customerasset?: msdyn_customerasset_Result | null;
  regardingobjectid_msdyn_fieldservicesetting?: msdyn_fieldservicesetting_Result | null;
  regardingobjectid_msdyn_incidenttypecharacteristic?: msdyn_incidenttypecharacteristic_Result | null;
  regardingobjectid_msdyn_incidenttypeproduct?: msdyn_incidenttypeproduct_Result | null;
  regardingobjectid_msdyn_incidenttypeservice?: msdyn_incidenttypeservice_Result | null;
  regardingobjectid_msdyn_inventoryadjustment?: msdyn_inventoryadjustment_Result | null;
  regardingobjectid_msdyn_inventoryadjustmentproduct?: msdyn_inventoryadjustmentproduct_Result | null;
  regardingobjectid_msdyn_inventoryjournal?: msdyn_inventoryjournal_Result | null;
  regardingobjectid_msdyn_inventorytransfer?: msdyn_inventorytransfer_Result | null;
  regardingobjectid_msdyn_payment?: msdyn_payment_Result | null;
  regardingobjectid_msdyn_paymentdetail?: msdyn_paymentdetail_Result | null;
  regardingobjectid_msdyn_paymentmethod?: msdyn_paymentmethod_Result | null;
  regardingobjectid_msdyn_paymentterm?: msdyn_paymentterm_Result | null;
  regardingobjectid_msdyn_playbookinstance?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum?: msdyn_PostAlbum_Result | null;
  regardingobjectid_msdyn_postalcode?: msdyn_postalcode_Result | null;
  regardingobjectid_msdyn_processnotes?: msdyn_processnotes_Result | null;
  regardingobjectid_msdyn_productinventory?: msdyn_productinventory_Result | null;
  regardingobjectid_msdyn_projectteam?: msdyn_projectteam_Result | null;
  regardingobjectid_msdyn_purchaseorder?: msdyn_purchaseorder_Result | null;
  regardingobjectid_msdyn_purchaseorderbill?: msdyn_purchaseorderbill_Result | null;
  regardingobjectid_msdyn_purchaseorderproduct?: msdyn_purchaseorderproduct_Result | null;
  regardingobjectid_msdyn_purchaseorderreceipt?: msdyn_purchaseorderreceipt_Result | null;
  regardingobjectid_msdyn_purchaseorderreceiptproduct?: msdyn_purchaseorderreceiptproduct_Result | null;
  regardingobjectid_msdyn_purchaseordersubstatus?: msdyn_purchaseordersubstatus_Result | null;
  regardingobjectid_msdyn_quotebookingincident?: msdyn_quotebookingincident_Result | null;
  regardingobjectid_msdyn_quotebookingproduct?: msdyn_quotebookingproduct_Result | null;
  regardingobjectid_msdyn_quotebookingservice?: msdyn_quotebookingservice_Result | null;
  regardingobjectid_msdyn_quotebookingservicetask?: msdyn_quotebookingservicetask_Result | null;
  regardingobjectid_msdyn_resourceterritory?: msdyn_resourceterritory_Result | null;
  regardingobjectid_msdyn_rma?: msdyn_rma_Result | null;
  regardingobjectid_msdyn_rmaproduct?: msdyn_rmaproduct_Result | null;
  regardingobjectid_msdyn_rmareceipt?: msdyn_rmareceipt_Result | null;
  regardingobjectid_msdyn_rmareceiptproduct?: msdyn_rmareceiptproduct_Result | null;
  regardingobjectid_msdyn_rmasubstatus?: msdyn_rmasubstatus_Result | null;
  regardingobjectid_msdyn_rtv?: msdyn_rtv_Result | null;
  regardingobjectid_msdyn_rtvproduct?: msdyn_rtvproduct_Result | null;
  regardingobjectid_msdyn_rtvsubstatus?: msdyn_rtvsubstatus_Result | null;
  regardingobjectid_msdyn_shipvia?: msdyn_shipvia_Result | null;
  regardingobjectid_msdyn_systemuserschedulersetting?: msdyn_systemuserschedulersetting_Result | null;
  regardingobjectid_msdyn_timegroup?: msdyn_timegroup_Result | null;
  regardingobjectid_msdyn_timegroupdetail?: msdyn_timegroupdetail_Result | null;
  regardingobjectid_msdyn_timeoffrequest?: msdyn_timeoffrequest_Result | null;
  regardingobjectid_msdyn_warehouse?: msdyn_warehouse_Result | null;
  regardingobjectid_msdyn_workorder?: msdyn_workorder_Result | null;
  regardingobjectid_msdyn_workordercharacteristic?: msdyn_workordercharacteristic_Result | null;
  regardingobjectid_msdyn_workorderincident?: msdyn_workorderincident_Result | null;
  regardingobjectid_msdyn_workorderproduct?: msdyn_workorderproduct_Result | null;
  regardingobjectid_msdyn_workorderresourcerestriction?: msdyn_workorderresourcerestriction_Result | null;
  regardingobjectid_msdyn_workorderservice?: msdyn_workorderservice_Result | null;
  regardingobjectid_msdyn_workorderservicetask?: msdyn_workorderservicetask_Result | null;
  regardingobjectid_new_interactionforemail?: InteractionForEmail_Result | null;
  regardingobjectid_opportunity?: Opportunity_Result | null;
  regardingobjectid_quote?: Quote_Result | null;
  regardingobjectid_salesorder?: SalesOrder_Result | null;
  regardingobjectid_site?: Site_Result | null;
  regardingobjectid_uii_action?: UII_action_Result | null;
  regardingobjectid_uii_hostedapplication?: UII_hostedapplication_Result | null;
  regardingobjectid_uii_nonhostedapplication?: UII_nonhostedapplication_Result | null;
  regardingobjectid_uii_option?: uii_option_Result | null;
  regardingobjectid_uii_savedsession?: UII_savedsession_Result | null;
  regardingobjectid_uii_workflow?: UII_workflow_Result | null;
  regardingobjectid_uii_workflow_workflowstep_mapping?: UII_workflow_workflowstep_mapping_Result | null;
  regardingobjectid_uii_workflowstep?: UII_workflowstep_Result | null;
  sla_activitypointer_sla?: SLA_Result | null;
  slainvokedid_activitypointer_sla?: SLA_Result | null;
  slakpiinstance_activitypointer?: SLAKPIInstance_Result[] | null;
}
interface ActivityPointer extends ActivityPointer_Base, ActivityPointer_Relationships {
  regardingobjectid_account_bind$accounts?: string | null;
  regardingobjectid_bookableresourcebooking_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_bind$campaignactivities?: string | null;
  regardingobjectid_contact_bind$contacts?: string | null;
  regardingobjectid_contract_bind$contracts?: string | null;
  regardingobjectid_entitlement_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_bind$incidents?: string | null;
  regardingobjectid_invoice_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_bind$leads?: string | null;
  regardingobjectid_msdyn_agreement_bind$msdyn_agreements?: string | null;
  regardingobjectid_msdyn_agreementbookingdate_bind$msdyn_agreementbookingdates?: string | null;
  regardingobjectid_msdyn_agreementbookingincident_bind$msdyn_agreementbookingincidents?: string | null;
  regardingobjectid_msdyn_agreementbookingproduct_bind$msdyn_agreementbookingproducts?: string | null;
  regardingobjectid_msdyn_agreementbookingservice_bind$msdyn_agreementbookingservices?: string | null;
  regardingobjectid_msdyn_agreementbookingservicetask_bind$msdyn_agreementbookingservicetasks?: string | null;
  regardingobjectid_msdyn_agreementbookingsetup_bind$msdyn_agreementbookingsetups?: string | null;
  regardingobjectid_msdyn_agreementinvoicedate_bind$msdyn_agreementinvoicedates?: string | null;
  regardingobjectid_msdyn_agreementinvoiceproduct_bind$msdyn_agreementinvoiceproducts?: string | null;
  regardingobjectid_msdyn_agreementinvoicesetup_bind$msdyn_agreementinvoicesetups?: string | null;
  regardingobjectid_msdyn_bookingalertstatus_bind$msdyn_bookingalertstatuses?: string | null;
  regardingobjectid_msdyn_bookingrule_bind$msdyn_bookingrules?: string | null;
  regardingobjectid_msdyn_bookingtimestamp_bind$msdyn_bookingtimestamps?: string | null;
  regardingobjectid_msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  regardingobjectid_msdyn_fieldservicesetting_bind$msdyn_fieldservicesettings?: string | null;
  regardingobjectid_msdyn_incidenttypecharacteristic_bind$msdyn_incidenttypecharacteristics?: string | null;
  regardingobjectid_msdyn_incidenttypeproduct_bind$msdyn_incidenttypeproducts?: string | null;
  regardingobjectid_msdyn_incidenttypeservice_bind$msdyn_incidenttypeservices?: string | null;
  regardingobjectid_msdyn_inventoryadjustment_bind$msdyn_inventoryadjustments?: string | null;
  regardingobjectid_msdyn_inventoryadjustmentproduct_bind$msdyn_inventoryadjustmentproducts?: string | null;
  regardingobjectid_msdyn_inventoryjournal_bind$msdyn_inventoryjournals?: string | null;
  regardingobjectid_msdyn_inventorytransfer_bind$msdyn_inventorytransfers?: string | null;
  regardingobjectid_msdyn_payment_bind$msdyn_payments?: string | null;
  regardingobjectid_msdyn_paymentdetail_bind$msdyn_paymentdetailes?: string | null;
  regardingobjectid_msdyn_paymentmethod_bind$msdyn_paymentmethods?: string | null;
  regardingobjectid_msdyn_paymentterm_bind$msdyn_paymentterms?: string | null;
  regardingobjectid_msdyn_playbookinstance_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_bind$msdyn_postalbums?: string | null;
  regardingobjectid_msdyn_postalcode_bind$msdyn_postalcodes?: string | null;
  regardingobjectid_msdyn_processnotes_bind$msdyn_processnoteses?: string | null;
  regardingobjectid_msdyn_productinventory_bind$msdyn_productinventories?: string | null;
  regardingobjectid_msdyn_projectteam_bind$msdyn_projectteams?: string | null;
  regardingobjectid_msdyn_purchaseorder_bind$msdyn_purchaseorders?: string | null;
  regardingobjectid_msdyn_purchaseorderbill_bind$msdyn_purchaseorderbills?: string | null;
  regardingobjectid_msdyn_purchaseorderproduct_bind$msdyn_purchaseorderproducts?: string | null;
  regardingobjectid_msdyn_purchaseorderreceipt_bind$msdyn_purchaseorderreceipts?: string | null;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_bind$msdyn_purchaseorderreceiptproducts?: string | null;
  regardingobjectid_msdyn_purchaseordersubstatus_bind$msdyn_purchaseordersubstatuses?: string | null;
  regardingobjectid_msdyn_quotebookingincident_bind$msdyn_quotebookingincidents?: string | null;
  regardingobjectid_msdyn_quotebookingproduct_bind$msdyn_quotebookingproducts?: string | null;
  regardingobjectid_msdyn_quotebookingservice_bind$msdyn_quotebookingservices?: string | null;
  regardingobjectid_msdyn_quotebookingservicetask_bind$msdyn_quotebookingservicetasks?: string | null;
  regardingobjectid_msdyn_resourceterritory_bind$msdyn_resourceterritories?: string | null;
  regardingobjectid_msdyn_rma_bind$msdyn_rmas?: string | null;
  regardingobjectid_msdyn_rmaproduct_bind$msdyn_rmaproducts?: string | null;
  regardingobjectid_msdyn_rmareceipt_bind$msdyn_rmareceipts?: string | null;
  regardingobjectid_msdyn_rmareceiptproduct_bind$msdyn_rmareceiptproducts?: string | null;
  regardingobjectid_msdyn_rmasubstatus_bind$msdyn_rmasubstatuses?: string | null;
  regardingobjectid_msdyn_rtv_bind$msdyn_rtvs?: string | null;
  regardingobjectid_msdyn_rtvproduct_bind$msdyn_rtvproducts?: string | null;
  regardingobjectid_msdyn_rtvsubstatus_bind$msdyn_rtvsubstatuses?: string | null;
  regardingobjectid_msdyn_shipvia_bind$msdyn_shipvias?: string | null;
  regardingobjectid_msdyn_systemuserschedulersetting_bind$msdyn_systemuserschedulersettinges?: string | null;
  regardingobjectid_msdyn_timegroup_bind$msdyn_timegroups?: string | null;
  regardingobjectid_msdyn_timegroupdetail_bind$msdyn_timegroupdetails?: string | null;
  regardingobjectid_msdyn_timeoffrequest_bind$msdyn_timeoffrequests?: string | null;
  regardingobjectid_msdyn_warehouse_bind$msdyn_warehouses?: string | null;
  regardingobjectid_msdyn_workorder_bind$msdyn_workorders?: string | null;
  regardingobjectid_msdyn_workordercharacteristic_bind$msdyn_workordercharacteristics?: string | null;
  regardingobjectid_msdyn_workorderincident_bind$msdyn_workorderincidents?: string | null;
  regardingobjectid_msdyn_workorderproduct_bind$msdyn_workorderproducts?: string | null;
  regardingobjectid_msdyn_workorderresourcerestriction_bind$msdyn_workorderresourcerestrictions?: string | null;
  regardingobjectid_msdyn_workorderservice_bind$msdyn_workorderservices?: string | null;
  regardingobjectid_msdyn_workorderservicetask_bind$msdyn_workorderservicetasks?: string | null;
  regardingobjectid_new_interactionforemail_bind$interactionforemails?: string | null;
  regardingobjectid_opportunity_bind$opportunities?: string | null;
  regardingobjectid_quote_bind$quotes?: string | null;
  regardingobjectid_salesorder_bind$salesorders?: string | null;
  regardingobjectid_site_bind$sites?: string | null;
  regardingobjectid_uii_action_bind$uii_actions?: string | null;
  regardingobjectid_uii_hostedapplication_bind$uii_hostedapplications?: string | null;
  regardingobjectid_uii_nonhostedapplication_bind$uii_nonhostedapplications?: string | null;
  regardingobjectid_uii_option_bind$uii_options?: string | null;
  regardingobjectid_uii_savedsession_bind$uii_savedsessions?: string | null;
  regardingobjectid_uii_workflow_bind$uii_workflows?: string | null;
  regardingobjectid_uii_workflow_workflowstep_mapping_bind$uii_workflow_workflowstep_mappings?: string | null;
  regardingobjectid_uii_workflowstep_bind$uii_workflowsteps?: string | null;
  serviceid_bind$services?: string | null;
  sla_activitypointer_sla_bind$slas?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface ActivityPointer_Create extends ActivityPointer {
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface ActivityPointer_Update extends ActivityPointer {
}
interface ActivityPointer_Select {
  activityadditionalparams: WebAttribute<ActivityPointer_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<ActivityPointer_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<ActivityPointer_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<ActivityPointer_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<ActivityPointer_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<ActivityPointer_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  allparties_guid: WebAttribute<ActivityPointer_Select, { allparties_guid: string | null }, { allparties_formatted?: string }>;
  community: WebAttribute<ActivityPointer_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  createdby_guid: WebAttribute<ActivityPointer_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<ActivityPointer_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<ActivityPointer_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  deliverylastattemptedon: WebAttribute<ActivityPointer_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
  deliveryprioritycode: WebAttribute<ActivityPointer_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  description: WebAttribute<ActivityPointer_Select, { description: string | null }, {  }>;
  exchangeitemid: WebAttribute<ActivityPointer_Select, { exchangeitemid: string | null }, {  }>;
  exchangerate: WebAttribute<ActivityPointer_Select, { exchangerate: number | null }, {  }>;
  exchangeweblink: WebAttribute<ActivityPointer_Select, { exchangeweblink: string | null }, {  }>;
  instancetypecode: WebAttribute<ActivityPointer_Select, { instancetypecode: activitypointer_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isbilled: WebAttribute<ActivityPointer_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<ActivityPointer_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<ActivityPointer_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<ActivityPointer_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<ActivityPointer_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<ActivityPointer_Select, { leftvoicemail: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<ActivityPointer_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<ActivityPointer_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<ActivityPointer_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<ActivityPointer_Select, { onholdtime: number | null }, {  }>;
  ownerid_guid: WebAttribute<ActivityPointer_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<ActivityPointer_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<ActivityPointer_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<ActivityPointer_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  postponeactivityprocessinguntil: WebAttribute<ActivityPointer_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<ActivityPointer_Select, { prioritycode: activitypointer_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<ActivityPointer_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<ActivityPointer_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<ActivityPointer_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<ActivityPointer_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<ActivityPointer_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sendermailboxid_guid: WebAttribute<ActivityPointer_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  senton: WebAttribute<ActivityPointer_Select, { senton: Date | null }, { senton_formatted?: string }>;
  seriesid: WebAttribute<ActivityPointer_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<ActivityPointer_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<ActivityPointer_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<ActivityPointer_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<ActivityPointer_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<ActivityPointer_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<ActivityPointer_Select, { statecode: activitypointer_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<ActivityPointer_Select, { statuscode: activitypointer_statuscode | null }, { statuscode_formatted?: string }>;
  subject: WebAttribute<ActivityPointer_Select, { subject: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<ActivityPointer_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<ActivityPointer_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<ActivityPointer_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<ActivityPointer_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<ActivityPointer_Select, { versionnumber: number | null }, {  }>;
}
interface ActivityPointer_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  allparties_guid: XQW.Guid;
  community: socialprofile_community;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  deliverylastattemptedon: Date;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  description: string;
  exchangeitemid: string;
  exchangerate: any;
  exchangeweblink: string;
  instancetypecode: activitypointer_instancetypecode;
  isbilled: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  postponeactivityprocessinguntil: Date;
  prioritycode: activitypointer_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sendermailboxid_guid: XQW.Guid;
  senton: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: activitypointer_statecode;
  statuscode: activitypointer_statuscode;
  subject: string;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface ActivityPointer_Expand {
  ActivityPointer_AsyncOperations: WebExpand<ActivityPointer_Expand, AsyncOperation_Select, AsyncOperation_Filter, { ActivityPointer_AsyncOperations: AsyncOperation_Result[] }>;
  ActivityPointer_BulkDeleteFailures: WebExpand<ActivityPointer_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { ActivityPointer_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  ActivityPointer_CampaignActivityItems: WebExpand<ActivityPointer_Expand, CampaignActivityItem_Select, CampaignActivityItem_Filter, { ActivityPointer_CampaignActivityItems: CampaignActivityItem_Result[] }>;
  ActivityPointer_QueueItem: WebExpand<ActivityPointer_Expand, QueueItem_Select, QueueItem_Filter, { ActivityPointer_QueueItem: QueueItem_Result[] }>;
  CreatedActivity_BulkOperationLogs: WebExpand<ActivityPointer_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { CreatedActivity_BulkOperationLogs: BulkOperationLog_Result[] }>;
  activity_campaignresponse: WebExpand<ActivityPointer_Expand, CampaignResponse_Select, CampaignResponse_Filter, { activity_campaignresponse: CampaignResponse_Result[] }>;
  activity_pointer_BulkOperation: WebExpand<ActivityPointer_Expand, BulkOperation_Select, BulkOperation_Filter, { activity_pointer_BulkOperation: BulkOperation_Result[] }>;
  activity_pointer_BulkOperation_logs: WebExpand<ActivityPointer_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { activity_pointer_BulkOperation_logs: BulkOperationLog_Result[] }>;
  activity_pointer_activity_mime_attachment: WebExpand<ActivityPointer_Expand, ActivityMimeAttachment_Select, ActivityMimeAttachment_Filter, { activity_pointer_activity_mime_attachment: ActivityMimeAttachment_Result[] }>;
  activity_pointer_appointment: WebExpand<ActivityPointer_Expand, Appointment_Select, Appointment_Filter, { activity_pointer_appointment: Appointment_Result[] }>;
  activity_pointer_campaignactivity: WebExpand<ActivityPointer_Expand, CampaignActivity_Select, CampaignActivity_Filter, { activity_pointer_campaignactivity: CampaignActivity_Result[] }>;
  activity_pointer_campaignresponse: WebExpand<ActivityPointer_Expand, CampaignResponse_Select, CampaignResponse_Filter, { activity_pointer_campaignresponse: CampaignResponse_Result[] }>;
  activity_pointer_email: WebExpand<ActivityPointer_Expand, Email_Select, Email_Filter, { activity_pointer_email: Email_Result[] }>;
  activity_pointer_email_hash: WebExpand<ActivityPointer_Expand, EmailHash_Select, EmailHash_Filter, { activity_pointer_email_hash: EmailHash_Result[] }>;
  activity_pointer_fax: WebExpand<ActivityPointer_Expand, Fax_Select, Fax_Filter, { activity_pointer_fax: Fax_Result[] }>;
  activity_pointer_incident_resolution: WebExpand<ActivityPointer_Expand, IncidentResolution_Select, IncidentResolution_Filter, { activity_pointer_incident_resolution: IncidentResolution_Result[] }>;
  activity_pointer_letter: WebExpand<ActivityPointer_Expand, Letter_Select, Letter_Filter, { activity_pointer_letter: Letter_Result[] }>;
  activity_pointer_msdyn_approval: WebExpand<ActivityPointer_Expand, msdyn_approval_Select, msdyn_approval_Filter, { activity_pointer_msdyn_approval: msdyn_approval_Result[] }>;
  activity_pointer_msdyn_bookingalert: WebExpand<ActivityPointer_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { activity_pointer_msdyn_bookingalert: msdyn_bookingalert_Result[] }>;
  activity_pointer_msdyn_ocliveworkitem: WebExpand<ActivityPointer_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { activity_pointer_msdyn_ocliveworkitem: msdyn_ocliveworkitem_Result[] }>;
  activity_pointer_msdyn_ocoutboundmessage: WebExpand<ActivityPointer_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { activity_pointer_msdyn_ocoutboundmessage: msdyn_ocoutboundmessage_Result[] }>;
  activity_pointer_msdyn_ocsession: WebExpand<ActivityPointer_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { activity_pointer_msdyn_ocsession: msdyn_ocsession_Result[] }>;
  activity_pointer_msfp_alert: WebExpand<ActivityPointer_Expand, msfp_alert_Select, msfp_alert_Filter, { activity_pointer_msfp_alert: msfp_alert_Result[] }>;
  activity_pointer_msfp_surveyinvite: WebExpand<ActivityPointer_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { activity_pointer_msfp_surveyinvite: msfp_surveyinvite_Result[] }>;
  activity_pointer_msfp_surveyresponse: WebExpand<ActivityPointer_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { activity_pointer_msfp_surveyresponse: msfp_surveyresponse_Result[] }>;
  activity_pointer_opportunity_close: WebExpand<ActivityPointer_Expand, OpportunityClose_Select, OpportunityClose_Filter, { activity_pointer_opportunity_close: OpportunityClose_Result[] }>;
  activity_pointer_order_close: WebExpand<ActivityPointer_Expand, OrderClose_Select, OrderClose_Filter, { activity_pointer_order_close: OrderClose_Result[] }>;
  activity_pointer_phonecall: WebExpand<ActivityPointer_Expand, PhoneCall_Select, PhoneCall_Filter, { activity_pointer_phonecall: PhoneCall_Result[] }>;
  activity_pointer_quote_close: WebExpand<ActivityPointer_Expand, QuoteClose_Select, QuoteClose_Filter, { activity_pointer_quote_close: QuoteClose_Result[] }>;
  activity_pointer_recurrencerule: WebExpand<ActivityPointer_Expand, RecurrenceRule_Select, RecurrenceRule_Filter, { activity_pointer_recurrencerule: RecurrenceRule_Result[] }>;
  activity_pointer_recurringappointmentmaster: WebExpand<ActivityPointer_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { activity_pointer_recurringappointmentmaster: RecurringAppointmentMaster_Result[] }>;
  activity_pointer_service_appointment: WebExpand<ActivityPointer_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { activity_pointer_service_appointment: ServiceAppointment_Result[] }>;
  activity_pointer_socialactivity: WebExpand<ActivityPointer_Expand, SocialActivity_Select, SocialActivity_Filter, { activity_pointer_socialactivity: SocialActivity_Result[] }>;
  activity_pointer_task: WebExpand<ActivityPointer_Expand, Task_Select, Task_Filter, { activity_pointer_task: Task_Result[] }>;
  activitypointer_activity_parties: WebExpand<ActivityPointer_Expand, ActivityParty_Select, ActivityParty_Filter, { activitypointer_activity_parties: ActivityParty_Result[] }>;
  activitypointer_connections1: WebExpand<ActivityPointer_Expand, Connection_Select, Connection_Filter, { activitypointer_connections1: Connection_Result[] }>;
  activitypointer_connections2: WebExpand<ActivityPointer_Expand, Connection_Select, Connection_Filter, { activitypointer_connections2: Connection_Result[] }>;
  createdby: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  ownerid: WebExpand<ActivityPointer_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<ActivityPointer_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<ActivityPointer_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  regardingobjectid_account: WebExpand<ActivityPointer_Expand, Account_Select, Account_Filter, { regardingobjectid_account: Account_Result }>;
  regardingobjectid_bookableresourcebooking: WebExpand<ActivityPointer_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader: WebExpand<ActivityPointer_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation: WebExpand<ActivityPointer_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation: BulkOperation_Result }>;
  regardingobjectid_campaign: WebExpand<ActivityPointer_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign: Campaign_Result }>;
  regardingobjectid_campaignactivity: WebExpand<ActivityPointer_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity: CampaignActivity_Result }>;
  regardingobjectid_contact: WebExpand<ActivityPointer_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact: Contact_Result }>;
  regardingobjectid_contract: WebExpand<ActivityPointer_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract: Contract_Result }>;
  regardingobjectid_entitlement: WebExpand<ActivityPointer_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate: WebExpand<ActivityPointer_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate: EntitlementTemplate_Result }>;
  regardingobjectid_incident: WebExpand<ActivityPointer_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident: Incident_Result }>;
  regardingobjectid_invoice: WebExpand<ActivityPointer_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice: Invoice_Result }>;
  regardingobjectid_knowledgearticle: WebExpand<ActivityPointer_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord: WebExpand<ActivityPointer_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead: WebExpand<ActivityPointer_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead: Lead_Result }>;
  regardingobjectid_msdyn_agreement: WebExpand<ActivityPointer_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { regardingobjectid_msdyn_agreement: msdyn_agreement_Result }>;
  regardingobjectid_msdyn_agreementbookingdate: WebExpand<ActivityPointer_Expand, msdyn_agreementbookingdate_Select, msdyn_agreementbookingdate_Filter, { regardingobjectid_msdyn_agreementbookingdate: msdyn_agreementbookingdate_Result }>;
  regardingobjectid_msdyn_agreementbookingincident: WebExpand<ActivityPointer_Expand, msdyn_agreementbookingincident_Select, msdyn_agreementbookingincident_Filter, { regardingobjectid_msdyn_agreementbookingincident: msdyn_agreementbookingincident_Result }>;
  regardingobjectid_msdyn_agreementbookingproduct: WebExpand<ActivityPointer_Expand, msdyn_agreementbookingproduct_Select, msdyn_agreementbookingproduct_Filter, { regardingobjectid_msdyn_agreementbookingproduct: msdyn_agreementbookingproduct_Result }>;
  regardingobjectid_msdyn_agreementbookingservice: WebExpand<ActivityPointer_Expand, msdyn_agreementbookingservice_Select, msdyn_agreementbookingservice_Filter, { regardingobjectid_msdyn_agreementbookingservice: msdyn_agreementbookingservice_Result }>;
  regardingobjectid_msdyn_agreementbookingservicetask: WebExpand<ActivityPointer_Expand, msdyn_agreementbookingservicetask_Select, msdyn_agreementbookingservicetask_Filter, { regardingobjectid_msdyn_agreementbookingservicetask: msdyn_agreementbookingservicetask_Result }>;
  regardingobjectid_msdyn_agreementbookingsetup: WebExpand<ActivityPointer_Expand, msdyn_agreementbookingsetup_Select, msdyn_agreementbookingsetup_Filter, { regardingobjectid_msdyn_agreementbookingsetup: msdyn_agreementbookingsetup_Result }>;
  regardingobjectid_msdyn_agreementinvoicedate: WebExpand<ActivityPointer_Expand, msdyn_agreementinvoicedate_Select, msdyn_agreementinvoicedate_Filter, { regardingobjectid_msdyn_agreementinvoicedate: msdyn_agreementinvoicedate_Result }>;
  regardingobjectid_msdyn_agreementinvoiceproduct: WebExpand<ActivityPointer_Expand, msdyn_agreementinvoiceproduct_Select, msdyn_agreementinvoiceproduct_Filter, { regardingobjectid_msdyn_agreementinvoiceproduct: msdyn_agreementinvoiceproduct_Result }>;
  regardingobjectid_msdyn_agreementinvoicesetup: WebExpand<ActivityPointer_Expand, msdyn_agreementinvoicesetup_Select, msdyn_agreementinvoicesetup_Filter, { regardingobjectid_msdyn_agreementinvoicesetup: msdyn_agreementinvoicesetup_Result }>;
  regardingobjectid_msdyn_bookingalertstatus: WebExpand<ActivityPointer_Expand, msdyn_bookingalertstatus_Select, msdyn_bookingalertstatus_Filter, { regardingobjectid_msdyn_bookingalertstatus: msdyn_bookingalertstatus_Result }>;
  regardingobjectid_msdyn_bookingrule: WebExpand<ActivityPointer_Expand, msdyn_bookingrule_Select, msdyn_bookingrule_Filter, { regardingobjectid_msdyn_bookingrule: msdyn_bookingrule_Result }>;
  regardingobjectid_msdyn_bookingtimestamp: WebExpand<ActivityPointer_Expand, msdyn_bookingtimestamp_Select, msdyn_bookingtimestamp_Filter, { regardingobjectid_msdyn_bookingtimestamp: msdyn_bookingtimestamp_Result }>;
  regardingobjectid_msdyn_customerasset: WebExpand<ActivityPointer_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { regardingobjectid_msdyn_customerasset: msdyn_customerasset_Result }>;
  regardingobjectid_msdyn_fieldservicesetting: WebExpand<ActivityPointer_Expand, msdyn_fieldservicesetting_Select, msdyn_fieldservicesetting_Filter, { regardingobjectid_msdyn_fieldservicesetting: msdyn_fieldservicesetting_Result }>;
  regardingobjectid_msdyn_incidenttypecharacteristic: WebExpand<ActivityPointer_Expand, msdyn_incidenttypecharacteristic_Select, msdyn_incidenttypecharacteristic_Filter, { regardingobjectid_msdyn_incidenttypecharacteristic: msdyn_incidenttypecharacteristic_Result }>;
  regardingobjectid_msdyn_incidenttypeproduct: WebExpand<ActivityPointer_Expand, msdyn_incidenttypeproduct_Select, msdyn_incidenttypeproduct_Filter, { regardingobjectid_msdyn_incidenttypeproduct: msdyn_incidenttypeproduct_Result }>;
  regardingobjectid_msdyn_incidenttypeservice: WebExpand<ActivityPointer_Expand, msdyn_incidenttypeservice_Select, msdyn_incidenttypeservice_Filter, { regardingobjectid_msdyn_incidenttypeservice: msdyn_incidenttypeservice_Result }>;
  regardingobjectid_msdyn_inventoryadjustment: WebExpand<ActivityPointer_Expand, msdyn_inventoryadjustment_Select, msdyn_inventoryadjustment_Filter, { regardingobjectid_msdyn_inventoryadjustment: msdyn_inventoryadjustment_Result }>;
  regardingobjectid_msdyn_inventoryadjustmentproduct: WebExpand<ActivityPointer_Expand, msdyn_inventoryadjustmentproduct_Select, msdyn_inventoryadjustmentproduct_Filter, { regardingobjectid_msdyn_inventoryadjustmentproduct: msdyn_inventoryadjustmentproduct_Result }>;
  regardingobjectid_msdyn_inventoryjournal: WebExpand<ActivityPointer_Expand, msdyn_inventoryjournal_Select, msdyn_inventoryjournal_Filter, { regardingobjectid_msdyn_inventoryjournal: msdyn_inventoryjournal_Result }>;
  regardingobjectid_msdyn_inventorytransfer: WebExpand<ActivityPointer_Expand, msdyn_inventorytransfer_Select, msdyn_inventorytransfer_Filter, { regardingobjectid_msdyn_inventorytransfer: msdyn_inventorytransfer_Result }>;
  regardingobjectid_msdyn_payment: WebExpand<ActivityPointer_Expand, msdyn_payment_Select, msdyn_payment_Filter, { regardingobjectid_msdyn_payment: msdyn_payment_Result }>;
  regardingobjectid_msdyn_paymentdetail: WebExpand<ActivityPointer_Expand, msdyn_paymentdetail_Select, msdyn_paymentdetail_Filter, { regardingobjectid_msdyn_paymentdetail: msdyn_paymentdetail_Result }>;
  regardingobjectid_msdyn_paymentmethod: WebExpand<ActivityPointer_Expand, msdyn_paymentmethod_Select, msdyn_paymentmethod_Filter, { regardingobjectid_msdyn_paymentmethod: msdyn_paymentmethod_Result }>;
  regardingobjectid_msdyn_paymentterm: WebExpand<ActivityPointer_Expand, msdyn_paymentterm_Select, msdyn_paymentterm_Filter, { regardingobjectid_msdyn_paymentterm: msdyn_paymentterm_Result }>;
  regardingobjectid_msdyn_playbookinstance: WebExpand<ActivityPointer_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum: WebExpand<ActivityPointer_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum: msdyn_PostAlbum_Result }>;
  regardingobjectid_msdyn_postalcode: WebExpand<ActivityPointer_Expand, msdyn_postalcode_Select, msdyn_postalcode_Filter, { regardingobjectid_msdyn_postalcode: msdyn_postalcode_Result }>;
  regardingobjectid_msdyn_processnotes: WebExpand<ActivityPointer_Expand, msdyn_processnotes_Select, msdyn_processnotes_Filter, { regardingobjectid_msdyn_processnotes: msdyn_processnotes_Result }>;
  regardingobjectid_msdyn_productinventory: WebExpand<ActivityPointer_Expand, msdyn_productinventory_Select, msdyn_productinventory_Filter, { regardingobjectid_msdyn_productinventory: msdyn_productinventory_Result }>;
  regardingobjectid_msdyn_projectteam: WebExpand<ActivityPointer_Expand, msdyn_projectteam_Select, msdyn_projectteam_Filter, { regardingobjectid_msdyn_projectteam: msdyn_projectteam_Result }>;
  regardingobjectid_msdyn_purchaseorder: WebExpand<ActivityPointer_Expand, msdyn_purchaseorder_Select, msdyn_purchaseorder_Filter, { regardingobjectid_msdyn_purchaseorder: msdyn_purchaseorder_Result }>;
  regardingobjectid_msdyn_purchaseorderbill: WebExpand<ActivityPointer_Expand, msdyn_purchaseorderbill_Select, msdyn_purchaseorderbill_Filter, { regardingobjectid_msdyn_purchaseorderbill: msdyn_purchaseorderbill_Result }>;
  regardingobjectid_msdyn_purchaseorderproduct: WebExpand<ActivityPointer_Expand, msdyn_purchaseorderproduct_Select, msdyn_purchaseorderproduct_Filter, { regardingobjectid_msdyn_purchaseorderproduct: msdyn_purchaseorderproduct_Result }>;
  regardingobjectid_msdyn_purchaseorderreceipt: WebExpand<ActivityPointer_Expand, msdyn_purchaseorderreceipt_Select, msdyn_purchaseorderreceipt_Filter, { regardingobjectid_msdyn_purchaseorderreceipt: msdyn_purchaseorderreceipt_Result }>;
  regardingobjectid_msdyn_purchaseorderreceiptproduct: WebExpand<ActivityPointer_Expand, msdyn_purchaseorderreceiptproduct_Select, msdyn_purchaseorderreceiptproduct_Filter, { regardingobjectid_msdyn_purchaseorderreceiptproduct: msdyn_purchaseorderreceiptproduct_Result }>;
  regardingobjectid_msdyn_purchaseordersubstatus: WebExpand<ActivityPointer_Expand, msdyn_purchaseordersubstatus_Select, msdyn_purchaseordersubstatus_Filter, { regardingobjectid_msdyn_purchaseordersubstatus: msdyn_purchaseordersubstatus_Result }>;
  regardingobjectid_msdyn_quotebookingincident: WebExpand<ActivityPointer_Expand, msdyn_quotebookingincident_Select, msdyn_quotebookingincident_Filter, { regardingobjectid_msdyn_quotebookingincident: msdyn_quotebookingincident_Result }>;
  regardingobjectid_msdyn_quotebookingproduct: WebExpand<ActivityPointer_Expand, msdyn_quotebookingproduct_Select, msdyn_quotebookingproduct_Filter, { regardingobjectid_msdyn_quotebookingproduct: msdyn_quotebookingproduct_Result }>;
  regardingobjectid_msdyn_quotebookingservice: WebExpand<ActivityPointer_Expand, msdyn_quotebookingservice_Select, msdyn_quotebookingservice_Filter, { regardingobjectid_msdyn_quotebookingservice: msdyn_quotebookingservice_Result }>;
  regardingobjectid_msdyn_quotebookingservicetask: WebExpand<ActivityPointer_Expand, msdyn_quotebookingservicetask_Select, msdyn_quotebookingservicetask_Filter, { regardingobjectid_msdyn_quotebookingservicetask: msdyn_quotebookingservicetask_Result }>;
  regardingobjectid_msdyn_resourceterritory: WebExpand<ActivityPointer_Expand, msdyn_resourceterritory_Select, msdyn_resourceterritory_Filter, { regardingobjectid_msdyn_resourceterritory: msdyn_resourceterritory_Result }>;
  regardingobjectid_msdyn_rma: WebExpand<ActivityPointer_Expand, msdyn_rma_Select, msdyn_rma_Filter, { regardingobjectid_msdyn_rma: msdyn_rma_Result }>;
  regardingobjectid_msdyn_rmaproduct: WebExpand<ActivityPointer_Expand, msdyn_rmaproduct_Select, msdyn_rmaproduct_Filter, { regardingobjectid_msdyn_rmaproduct: msdyn_rmaproduct_Result }>;
  regardingobjectid_msdyn_rmareceipt: WebExpand<ActivityPointer_Expand, msdyn_rmareceipt_Select, msdyn_rmareceipt_Filter, { regardingobjectid_msdyn_rmareceipt: msdyn_rmareceipt_Result }>;
  regardingobjectid_msdyn_rmareceiptproduct: WebExpand<ActivityPointer_Expand, msdyn_rmareceiptproduct_Select, msdyn_rmareceiptproduct_Filter, { regardingobjectid_msdyn_rmareceiptproduct: msdyn_rmareceiptproduct_Result }>;
  regardingobjectid_msdyn_rmasubstatus: WebExpand<ActivityPointer_Expand, msdyn_rmasubstatus_Select, msdyn_rmasubstatus_Filter, { regardingobjectid_msdyn_rmasubstatus: msdyn_rmasubstatus_Result }>;
  regardingobjectid_msdyn_rtv: WebExpand<ActivityPointer_Expand, msdyn_rtv_Select, msdyn_rtv_Filter, { regardingobjectid_msdyn_rtv: msdyn_rtv_Result }>;
  regardingobjectid_msdyn_rtvproduct: WebExpand<ActivityPointer_Expand, msdyn_rtvproduct_Select, msdyn_rtvproduct_Filter, { regardingobjectid_msdyn_rtvproduct: msdyn_rtvproduct_Result }>;
  regardingobjectid_msdyn_rtvsubstatus: WebExpand<ActivityPointer_Expand, msdyn_rtvsubstatus_Select, msdyn_rtvsubstatus_Filter, { regardingobjectid_msdyn_rtvsubstatus: msdyn_rtvsubstatus_Result }>;
  regardingobjectid_msdyn_shipvia: WebExpand<ActivityPointer_Expand, msdyn_shipvia_Select, msdyn_shipvia_Filter, { regardingobjectid_msdyn_shipvia: msdyn_shipvia_Result }>;
  regardingobjectid_msdyn_systemuserschedulersetting: WebExpand<ActivityPointer_Expand, msdyn_systemuserschedulersetting_Select, msdyn_systemuserschedulersetting_Filter, { regardingobjectid_msdyn_systemuserschedulersetting: msdyn_systemuserschedulersetting_Result }>;
  regardingobjectid_msdyn_timegroup: WebExpand<ActivityPointer_Expand, msdyn_timegroup_Select, msdyn_timegroup_Filter, { regardingobjectid_msdyn_timegroup: msdyn_timegroup_Result }>;
  regardingobjectid_msdyn_timegroupdetail: WebExpand<ActivityPointer_Expand, msdyn_timegroupdetail_Select, msdyn_timegroupdetail_Filter, { regardingobjectid_msdyn_timegroupdetail: msdyn_timegroupdetail_Result }>;
  regardingobjectid_msdyn_timeoffrequest: WebExpand<ActivityPointer_Expand, msdyn_timeoffrequest_Select, msdyn_timeoffrequest_Filter, { regardingobjectid_msdyn_timeoffrequest: msdyn_timeoffrequest_Result }>;
  regardingobjectid_msdyn_warehouse: WebExpand<ActivityPointer_Expand, msdyn_warehouse_Select, msdyn_warehouse_Filter, { regardingobjectid_msdyn_warehouse: msdyn_warehouse_Result }>;
  regardingobjectid_msdyn_workorder: WebExpand<ActivityPointer_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { regardingobjectid_msdyn_workorder: msdyn_workorder_Result }>;
  regardingobjectid_msdyn_workordercharacteristic: WebExpand<ActivityPointer_Expand, msdyn_workordercharacteristic_Select, msdyn_workordercharacteristic_Filter, { regardingobjectid_msdyn_workordercharacteristic: msdyn_workordercharacteristic_Result }>;
  regardingobjectid_msdyn_workorderincident: WebExpand<ActivityPointer_Expand, msdyn_workorderincident_Select, msdyn_workorderincident_Filter, { regardingobjectid_msdyn_workorderincident: msdyn_workorderincident_Result }>;
  regardingobjectid_msdyn_workorderproduct: WebExpand<ActivityPointer_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { regardingobjectid_msdyn_workorderproduct: msdyn_workorderproduct_Result }>;
  regardingobjectid_msdyn_workorderresourcerestriction: WebExpand<ActivityPointer_Expand, msdyn_workorderresourcerestriction_Select, msdyn_workorderresourcerestriction_Filter, { regardingobjectid_msdyn_workorderresourcerestriction: msdyn_workorderresourcerestriction_Result }>;
  regardingobjectid_msdyn_workorderservice: WebExpand<ActivityPointer_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { regardingobjectid_msdyn_workorderservice: msdyn_workorderservice_Result }>;
  regardingobjectid_msdyn_workorderservicetask: WebExpand<ActivityPointer_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { regardingobjectid_msdyn_workorderservicetask: msdyn_workorderservicetask_Result }>;
  regardingobjectid_new_interactionforemail: WebExpand<ActivityPointer_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { regardingobjectid_new_interactionforemail: InteractionForEmail_Result }>;
  regardingobjectid_opportunity: WebExpand<ActivityPointer_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity: Opportunity_Result }>;
  regardingobjectid_quote: WebExpand<ActivityPointer_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote: Quote_Result }>;
  regardingobjectid_salesorder: WebExpand<ActivityPointer_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder: SalesOrder_Result }>;
  regardingobjectid_site: WebExpand<ActivityPointer_Expand, Site_Select, Site_Filter, { regardingobjectid_site: Site_Result }>;
  regardingobjectid_uii_action: WebExpand<ActivityPointer_Expand, UII_action_Select, UII_action_Filter, { regardingobjectid_uii_action: UII_action_Result }>;
  regardingobjectid_uii_hostedapplication: WebExpand<ActivityPointer_Expand, UII_hostedapplication_Select, UII_hostedapplication_Filter, { regardingobjectid_uii_hostedapplication: UII_hostedapplication_Result }>;
  regardingobjectid_uii_nonhostedapplication: WebExpand<ActivityPointer_Expand, UII_nonhostedapplication_Select, UII_nonhostedapplication_Filter, { regardingobjectid_uii_nonhostedapplication: UII_nonhostedapplication_Result }>;
  regardingobjectid_uii_option: WebExpand<ActivityPointer_Expand, uii_option_Select, uii_option_Filter, { regardingobjectid_uii_option: uii_option_Result }>;
  regardingobjectid_uii_savedsession: WebExpand<ActivityPointer_Expand, UII_savedsession_Select, UII_savedsession_Filter, { regardingobjectid_uii_savedsession: UII_savedsession_Result }>;
  regardingobjectid_uii_workflow: WebExpand<ActivityPointer_Expand, UII_workflow_Select, UII_workflow_Filter, { regardingobjectid_uii_workflow: UII_workflow_Result }>;
  regardingobjectid_uii_workflow_workflowstep_mapping: WebExpand<ActivityPointer_Expand, UII_workflow_workflowstep_mapping_Select, UII_workflow_workflowstep_mapping_Filter, { regardingobjectid_uii_workflow_workflowstep_mapping: UII_workflow_workflowstep_mapping_Result }>;
  regardingobjectid_uii_workflowstep: WebExpand<ActivityPointer_Expand, UII_workflowstep_Select, UII_workflowstep_Filter, { regardingobjectid_uii_workflowstep: UII_workflowstep_Result }>;
  sendermailboxid: WebExpand<ActivityPointer_Expand, Mailbox_Select, Mailbox_Filter, { sendermailboxid: Mailbox_Result }>;
  serviceid: WebExpand<ActivityPointer_Expand, Service_Select, Service_Filter, { serviceid: Service_Result }>;
  sla_activitypointer_sla: WebExpand<ActivityPointer_Expand, SLA_Select, SLA_Filter, { sla_activitypointer_sla: SLA_Result }>;
  slainvokedid_activitypointer_sla: WebExpand<ActivityPointer_Expand, SLA_Select, SLA_Filter, { slainvokedid_activitypointer_sla: SLA_Result }>;
  slakpiinstance_activitypointer: WebExpand<ActivityPointer_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_activitypointer: SLAKPIInstance_Result[] }>;
  transactioncurrencyid: WebExpand<ActivityPointer_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface ActivityPointer_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  allparties_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  deliverylastattemptedon_formatted?: string;
  deliveryprioritycode_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  postponeactivityprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface ActivityPointer_Result extends ActivityPointer_Base, ActivityPointer_Relationships {
  "@odata.etag": string;
  allparties_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  sendermailboxid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface ActivityPointer_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_bookableresourcebooking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_agreement: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingdate: WebMappingRetrieve<msdyn_agreementbookingdate_Select,msdyn_agreementbookingdate_Expand,msdyn_agreementbookingdate_Filter,msdyn_agreementbookingdate_Fixed,msdyn_agreementbookingdate_Result,msdyn_agreementbookingdate_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingincident: WebMappingRetrieve<msdyn_agreementbookingincident_Select,msdyn_agreementbookingincident_Expand,msdyn_agreementbookingincident_Filter,msdyn_agreementbookingincident_Fixed,msdyn_agreementbookingincident_Result,msdyn_agreementbookingincident_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingproduct: WebMappingRetrieve<msdyn_agreementbookingproduct_Select,msdyn_agreementbookingproduct_Expand,msdyn_agreementbookingproduct_Filter,msdyn_agreementbookingproduct_Fixed,msdyn_agreementbookingproduct_Result,msdyn_agreementbookingproduct_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingservice: WebMappingRetrieve<msdyn_agreementbookingservice_Select,msdyn_agreementbookingservice_Expand,msdyn_agreementbookingservice_Filter,msdyn_agreementbookingservice_Fixed,msdyn_agreementbookingservice_Result,msdyn_agreementbookingservice_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingservicetask: WebMappingRetrieve<msdyn_agreementbookingservicetask_Select,msdyn_agreementbookingservicetask_Expand,msdyn_agreementbookingservicetask_Filter,msdyn_agreementbookingservicetask_Fixed,msdyn_agreementbookingservicetask_Result,msdyn_agreementbookingservicetask_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingsetup: WebMappingRetrieve<msdyn_agreementbookingsetup_Select,msdyn_agreementbookingsetup_Expand,msdyn_agreementbookingsetup_Filter,msdyn_agreementbookingsetup_Fixed,msdyn_agreementbookingsetup_Result,msdyn_agreementbookingsetup_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoicedate: WebMappingRetrieve<msdyn_agreementinvoicedate_Select,msdyn_agreementinvoicedate_Expand,msdyn_agreementinvoicedate_Filter,msdyn_agreementinvoicedate_Fixed,msdyn_agreementinvoicedate_Result,msdyn_agreementinvoicedate_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoiceproduct: WebMappingRetrieve<msdyn_agreementinvoiceproduct_Select,msdyn_agreementinvoiceproduct_Expand,msdyn_agreementinvoiceproduct_Filter,msdyn_agreementinvoiceproduct_Fixed,msdyn_agreementinvoiceproduct_Result,msdyn_agreementinvoiceproduct_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoicesetup: WebMappingRetrieve<msdyn_agreementinvoicesetup_Select,msdyn_agreementinvoicesetup_Expand,msdyn_agreementinvoicesetup_Filter,msdyn_agreementinvoicesetup_Fixed,msdyn_agreementinvoicesetup_Result,msdyn_agreementinvoicesetup_FormattedResult>;
  regardingobjectid_msdyn_bookingalertstatus: WebMappingRetrieve<msdyn_bookingalertstatus_Select,msdyn_bookingalertstatus_Expand,msdyn_bookingalertstatus_Filter,msdyn_bookingalertstatus_Fixed,msdyn_bookingalertstatus_Result,msdyn_bookingalertstatus_FormattedResult>;
  regardingobjectid_msdyn_bookingrule: WebMappingRetrieve<msdyn_bookingrule_Select,msdyn_bookingrule_Expand,msdyn_bookingrule_Filter,msdyn_bookingrule_Fixed,msdyn_bookingrule_Result,msdyn_bookingrule_FormattedResult>;
  regardingobjectid_msdyn_bookingtimestamp: WebMappingRetrieve<msdyn_bookingtimestamp_Select,msdyn_bookingtimestamp_Expand,msdyn_bookingtimestamp_Filter,msdyn_bookingtimestamp_Fixed,msdyn_bookingtimestamp_Result,msdyn_bookingtimestamp_FormattedResult>;
  regardingobjectid_msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  regardingobjectid_msdyn_fieldservicesetting: WebMappingRetrieve<msdyn_fieldservicesetting_Select,msdyn_fieldservicesetting_Expand,msdyn_fieldservicesetting_Filter,msdyn_fieldservicesetting_Fixed,msdyn_fieldservicesetting_Result,msdyn_fieldservicesetting_FormattedResult>;
  regardingobjectid_msdyn_incidenttypecharacteristic: WebMappingRetrieve<msdyn_incidenttypecharacteristic_Select,msdyn_incidenttypecharacteristic_Expand,msdyn_incidenttypecharacteristic_Filter,msdyn_incidenttypecharacteristic_Fixed,msdyn_incidenttypecharacteristic_Result,msdyn_incidenttypecharacteristic_FormattedResult>;
  regardingobjectid_msdyn_incidenttypeproduct: WebMappingRetrieve<msdyn_incidenttypeproduct_Select,msdyn_incidenttypeproduct_Expand,msdyn_incidenttypeproduct_Filter,msdyn_incidenttypeproduct_Fixed,msdyn_incidenttypeproduct_Result,msdyn_incidenttypeproduct_FormattedResult>;
  regardingobjectid_msdyn_incidenttypeservice: WebMappingRetrieve<msdyn_incidenttypeservice_Select,msdyn_incidenttypeservice_Expand,msdyn_incidenttypeservice_Filter,msdyn_incidenttypeservice_Fixed,msdyn_incidenttypeservice_Result,msdyn_incidenttypeservice_FormattedResult>;
  regardingobjectid_msdyn_inventoryadjustment: WebMappingRetrieve<msdyn_inventoryadjustment_Select,msdyn_inventoryadjustment_Expand,msdyn_inventoryadjustment_Filter,msdyn_inventoryadjustment_Fixed,msdyn_inventoryadjustment_Result,msdyn_inventoryadjustment_FormattedResult>;
  regardingobjectid_msdyn_inventoryadjustmentproduct: WebMappingRetrieve<msdyn_inventoryadjustmentproduct_Select,msdyn_inventoryadjustmentproduct_Expand,msdyn_inventoryadjustmentproduct_Filter,msdyn_inventoryadjustmentproduct_Fixed,msdyn_inventoryadjustmentproduct_Result,msdyn_inventoryadjustmentproduct_FormattedResult>;
  regardingobjectid_msdyn_inventoryjournal: WebMappingRetrieve<msdyn_inventoryjournal_Select,msdyn_inventoryjournal_Expand,msdyn_inventoryjournal_Filter,msdyn_inventoryjournal_Fixed,msdyn_inventoryjournal_Result,msdyn_inventoryjournal_FormattedResult>;
  regardingobjectid_msdyn_inventorytransfer: WebMappingRetrieve<msdyn_inventorytransfer_Select,msdyn_inventorytransfer_Expand,msdyn_inventorytransfer_Filter,msdyn_inventorytransfer_Fixed,msdyn_inventorytransfer_Result,msdyn_inventorytransfer_FormattedResult>;
  regardingobjectid_msdyn_payment: WebMappingRetrieve<msdyn_payment_Select,msdyn_payment_Expand,msdyn_payment_Filter,msdyn_payment_Fixed,msdyn_payment_Result,msdyn_payment_FormattedResult>;
  regardingobjectid_msdyn_paymentdetail: WebMappingRetrieve<msdyn_paymentdetail_Select,msdyn_paymentdetail_Expand,msdyn_paymentdetail_Filter,msdyn_paymentdetail_Fixed,msdyn_paymentdetail_Result,msdyn_paymentdetail_FormattedResult>;
  regardingobjectid_msdyn_paymentmethod: WebMappingRetrieve<msdyn_paymentmethod_Select,msdyn_paymentmethod_Expand,msdyn_paymentmethod_Filter,msdyn_paymentmethod_Fixed,msdyn_paymentmethod_Result,msdyn_paymentmethod_FormattedResult>;
  regardingobjectid_msdyn_paymentterm: WebMappingRetrieve<msdyn_paymentterm_Select,msdyn_paymentterm_Expand,msdyn_paymentterm_Filter,msdyn_paymentterm_Fixed,msdyn_paymentterm_Result,msdyn_paymentterm_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_msdyn_postalcode: WebMappingRetrieve<msdyn_postalcode_Select,msdyn_postalcode_Expand,msdyn_postalcode_Filter,msdyn_postalcode_Fixed,msdyn_postalcode_Result,msdyn_postalcode_FormattedResult>;
  regardingobjectid_msdyn_processnotes: WebMappingRetrieve<msdyn_processnotes_Select,msdyn_processnotes_Expand,msdyn_processnotes_Filter,msdyn_processnotes_Fixed,msdyn_processnotes_Result,msdyn_processnotes_FormattedResult>;
  regardingobjectid_msdyn_productinventory: WebMappingRetrieve<msdyn_productinventory_Select,msdyn_productinventory_Expand,msdyn_productinventory_Filter,msdyn_productinventory_Fixed,msdyn_productinventory_Result,msdyn_productinventory_FormattedResult>;
  regardingobjectid_msdyn_projectteam: WebMappingRetrieve<msdyn_projectteam_Select,msdyn_projectteam_Expand,msdyn_projectteam_Filter,msdyn_projectteam_Fixed,msdyn_projectteam_Result,msdyn_projectteam_FormattedResult>;
  regardingobjectid_msdyn_purchaseorder: WebMappingRetrieve<msdyn_purchaseorder_Select,msdyn_purchaseorder_Expand,msdyn_purchaseorder_Filter,msdyn_purchaseorder_Fixed,msdyn_purchaseorder_Result,msdyn_purchaseorder_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderbill: WebMappingRetrieve<msdyn_purchaseorderbill_Select,msdyn_purchaseorderbill_Expand,msdyn_purchaseorderbill_Filter,msdyn_purchaseorderbill_Fixed,msdyn_purchaseorderbill_Result,msdyn_purchaseorderbill_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderproduct: WebMappingRetrieve<msdyn_purchaseorderproduct_Select,msdyn_purchaseorderproduct_Expand,msdyn_purchaseorderproduct_Filter,msdyn_purchaseorderproduct_Fixed,msdyn_purchaseorderproduct_Result,msdyn_purchaseorderproduct_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderreceipt: WebMappingRetrieve<msdyn_purchaseorderreceipt_Select,msdyn_purchaseorderreceipt_Expand,msdyn_purchaseorderreceipt_Filter,msdyn_purchaseorderreceipt_Fixed,msdyn_purchaseorderreceipt_Result,msdyn_purchaseorderreceipt_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderreceiptproduct: WebMappingRetrieve<msdyn_purchaseorderreceiptproduct_Select,msdyn_purchaseorderreceiptproduct_Expand,msdyn_purchaseorderreceiptproduct_Filter,msdyn_purchaseorderreceiptproduct_Fixed,msdyn_purchaseorderreceiptproduct_Result,msdyn_purchaseorderreceiptproduct_FormattedResult>;
  regardingobjectid_msdyn_purchaseordersubstatus: WebMappingRetrieve<msdyn_purchaseordersubstatus_Select,msdyn_purchaseordersubstatus_Expand,msdyn_purchaseordersubstatus_Filter,msdyn_purchaseordersubstatus_Fixed,msdyn_purchaseordersubstatus_Result,msdyn_purchaseordersubstatus_FormattedResult>;
  regardingobjectid_msdyn_quotebookingincident: WebMappingRetrieve<msdyn_quotebookingincident_Select,msdyn_quotebookingincident_Expand,msdyn_quotebookingincident_Filter,msdyn_quotebookingincident_Fixed,msdyn_quotebookingincident_Result,msdyn_quotebookingincident_FormattedResult>;
  regardingobjectid_msdyn_quotebookingproduct: WebMappingRetrieve<msdyn_quotebookingproduct_Select,msdyn_quotebookingproduct_Expand,msdyn_quotebookingproduct_Filter,msdyn_quotebookingproduct_Fixed,msdyn_quotebookingproduct_Result,msdyn_quotebookingproduct_FormattedResult>;
  regardingobjectid_msdyn_quotebookingservice: WebMappingRetrieve<msdyn_quotebookingservice_Select,msdyn_quotebookingservice_Expand,msdyn_quotebookingservice_Filter,msdyn_quotebookingservice_Fixed,msdyn_quotebookingservice_Result,msdyn_quotebookingservice_FormattedResult>;
  regardingobjectid_msdyn_quotebookingservicetask: WebMappingRetrieve<msdyn_quotebookingservicetask_Select,msdyn_quotebookingservicetask_Expand,msdyn_quotebookingservicetask_Filter,msdyn_quotebookingservicetask_Fixed,msdyn_quotebookingservicetask_Result,msdyn_quotebookingservicetask_FormattedResult>;
  regardingobjectid_msdyn_resourceterritory: WebMappingRetrieve<msdyn_resourceterritory_Select,msdyn_resourceterritory_Expand,msdyn_resourceterritory_Filter,msdyn_resourceterritory_Fixed,msdyn_resourceterritory_Result,msdyn_resourceterritory_FormattedResult>;
  regardingobjectid_msdyn_rma: WebMappingRetrieve<msdyn_rma_Select,msdyn_rma_Expand,msdyn_rma_Filter,msdyn_rma_Fixed,msdyn_rma_Result,msdyn_rma_FormattedResult>;
  regardingobjectid_msdyn_rmaproduct: WebMappingRetrieve<msdyn_rmaproduct_Select,msdyn_rmaproduct_Expand,msdyn_rmaproduct_Filter,msdyn_rmaproduct_Fixed,msdyn_rmaproduct_Result,msdyn_rmaproduct_FormattedResult>;
  regardingobjectid_msdyn_rmareceipt: WebMappingRetrieve<msdyn_rmareceipt_Select,msdyn_rmareceipt_Expand,msdyn_rmareceipt_Filter,msdyn_rmareceipt_Fixed,msdyn_rmareceipt_Result,msdyn_rmareceipt_FormattedResult>;
  regardingobjectid_msdyn_rmareceiptproduct: WebMappingRetrieve<msdyn_rmareceiptproduct_Select,msdyn_rmareceiptproduct_Expand,msdyn_rmareceiptproduct_Filter,msdyn_rmareceiptproduct_Fixed,msdyn_rmareceiptproduct_Result,msdyn_rmareceiptproduct_FormattedResult>;
  regardingobjectid_msdyn_rmasubstatus: WebMappingRetrieve<msdyn_rmasubstatus_Select,msdyn_rmasubstatus_Expand,msdyn_rmasubstatus_Filter,msdyn_rmasubstatus_Fixed,msdyn_rmasubstatus_Result,msdyn_rmasubstatus_FormattedResult>;
  regardingobjectid_msdyn_rtv: WebMappingRetrieve<msdyn_rtv_Select,msdyn_rtv_Expand,msdyn_rtv_Filter,msdyn_rtv_Fixed,msdyn_rtv_Result,msdyn_rtv_FormattedResult>;
  regardingobjectid_msdyn_rtvproduct: WebMappingRetrieve<msdyn_rtvproduct_Select,msdyn_rtvproduct_Expand,msdyn_rtvproduct_Filter,msdyn_rtvproduct_Fixed,msdyn_rtvproduct_Result,msdyn_rtvproduct_FormattedResult>;
  regardingobjectid_msdyn_rtvsubstatus: WebMappingRetrieve<msdyn_rtvsubstatus_Select,msdyn_rtvsubstatus_Expand,msdyn_rtvsubstatus_Filter,msdyn_rtvsubstatus_Fixed,msdyn_rtvsubstatus_Result,msdyn_rtvsubstatus_FormattedResult>;
  regardingobjectid_msdyn_shipvia: WebMappingRetrieve<msdyn_shipvia_Select,msdyn_shipvia_Expand,msdyn_shipvia_Filter,msdyn_shipvia_Fixed,msdyn_shipvia_Result,msdyn_shipvia_FormattedResult>;
  regardingobjectid_msdyn_systemuserschedulersetting: WebMappingRetrieve<msdyn_systemuserschedulersetting_Select,msdyn_systemuserschedulersetting_Expand,msdyn_systemuserschedulersetting_Filter,msdyn_systemuserschedulersetting_Fixed,msdyn_systemuserschedulersetting_Result,msdyn_systemuserschedulersetting_FormattedResult>;
  regardingobjectid_msdyn_timegroup: WebMappingRetrieve<msdyn_timegroup_Select,msdyn_timegroup_Expand,msdyn_timegroup_Filter,msdyn_timegroup_Fixed,msdyn_timegroup_Result,msdyn_timegroup_FormattedResult>;
  regardingobjectid_msdyn_timegroupdetail: WebMappingRetrieve<msdyn_timegroupdetail_Select,msdyn_timegroupdetail_Expand,msdyn_timegroupdetail_Filter,msdyn_timegroupdetail_Fixed,msdyn_timegroupdetail_Result,msdyn_timegroupdetail_FormattedResult>;
  regardingobjectid_msdyn_timeoffrequest: WebMappingRetrieve<msdyn_timeoffrequest_Select,msdyn_timeoffrequest_Expand,msdyn_timeoffrequest_Filter,msdyn_timeoffrequest_Fixed,msdyn_timeoffrequest_Result,msdyn_timeoffrequest_FormattedResult>;
  regardingobjectid_msdyn_warehouse: WebMappingRetrieve<msdyn_warehouse_Select,msdyn_warehouse_Expand,msdyn_warehouse_Filter,msdyn_warehouse_Fixed,msdyn_warehouse_Result,msdyn_warehouse_FormattedResult>;
  regardingobjectid_msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  regardingobjectid_msdyn_workordercharacteristic: WebMappingRetrieve<msdyn_workordercharacteristic_Select,msdyn_workordercharacteristic_Expand,msdyn_workordercharacteristic_Filter,msdyn_workordercharacteristic_Fixed,msdyn_workordercharacteristic_Result,msdyn_workordercharacteristic_FormattedResult>;
  regardingobjectid_msdyn_workorderincident: WebMappingRetrieve<msdyn_workorderincident_Select,msdyn_workorderincident_Expand,msdyn_workorderincident_Filter,msdyn_workorderincident_Fixed,msdyn_workorderincident_Result,msdyn_workorderincident_FormattedResult>;
  regardingobjectid_msdyn_workorderproduct: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  regardingobjectid_msdyn_workorderresourcerestriction: WebMappingRetrieve<msdyn_workorderresourcerestriction_Select,msdyn_workorderresourcerestriction_Expand,msdyn_workorderresourcerestriction_Filter,msdyn_workorderresourcerestriction_Fixed,msdyn_workorderresourcerestriction_Result,msdyn_workorderresourcerestriction_FormattedResult>;
  regardingobjectid_msdyn_workorderservice: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  regardingobjectid_msdyn_workorderservicetask: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  regardingobjectid_new_interactionforemail: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  regardingobjectid_opportunity: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  regardingobjectid_uii_action: WebMappingRetrieve<UII_action_Select,UII_action_Expand,UII_action_Filter,UII_action_Fixed,UII_action_Result,UII_action_FormattedResult>;
  regardingobjectid_uii_hostedapplication: WebMappingRetrieve<UII_hostedapplication_Select,UII_hostedapplication_Expand,UII_hostedapplication_Filter,UII_hostedapplication_Fixed,UII_hostedapplication_Result,UII_hostedapplication_FormattedResult>;
  regardingobjectid_uii_nonhostedapplication: WebMappingRetrieve<UII_nonhostedapplication_Select,UII_nonhostedapplication_Expand,UII_nonhostedapplication_Filter,UII_nonhostedapplication_Fixed,UII_nonhostedapplication_Result,UII_nonhostedapplication_FormattedResult>;
  regardingobjectid_uii_option: WebMappingRetrieve<uii_option_Select,uii_option_Expand,uii_option_Filter,uii_option_Fixed,uii_option_Result,uii_option_FormattedResult>;
  regardingobjectid_uii_savedsession: WebMappingRetrieve<UII_savedsession_Select,UII_savedsession_Expand,UII_savedsession_Filter,UII_savedsession_Fixed,UII_savedsession_Result,UII_savedsession_FormattedResult>;
  regardingobjectid_uii_workflow: WebMappingRetrieve<UII_workflow_Select,UII_workflow_Expand,UII_workflow_Filter,UII_workflow_Fixed,UII_workflow_Result,UII_workflow_FormattedResult>;
  regardingobjectid_uii_workflow_workflowstep_mapping: WebMappingRetrieve<UII_workflow_workflowstep_mapping_Select,UII_workflow_workflowstep_mapping_Expand,UII_workflow_workflowstep_mapping_Filter,UII_workflow_workflowstep_mapping_Fixed,UII_workflow_workflowstep_mapping_Result,UII_workflow_workflowstep_mapping_FormattedResult>;
  regardingobjectid_uii_workflowstep: WebMappingRetrieve<UII_workflowstep_Select,UII_workflowstep_Expand,UII_workflowstep_Filter,UII_workflowstep_Fixed,UII_workflowstep_Result,UII_workflowstep_FormattedResult>;
  sendermailboxid: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  serviceid: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_activitypointer_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_activitypointer_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface ActivityPointer_RelatedMany {
  ActivityPointer_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  ActivityPointer_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  ActivityPointer_CampaignActivityItems: WebMappingRetrieve<CampaignActivityItem_Select,CampaignActivityItem_Expand,CampaignActivityItem_Filter,CampaignActivityItem_Fixed,CampaignActivityItem_Result,CampaignActivityItem_FormattedResult>;
  ActivityPointer_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  CreatedActivity_BulkOperationLogs: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  activity_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  activity_pointer_BulkOperation: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  activity_pointer_BulkOperation_logs: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  activity_pointer_activity_mime_attachment: WebMappingRetrieve<ActivityMimeAttachment_Select,ActivityMimeAttachment_Expand,ActivityMimeAttachment_Filter,ActivityMimeAttachment_Fixed,ActivityMimeAttachment_Result,ActivityMimeAttachment_FormattedResult>;
  activity_pointer_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  activity_pointer_campaignactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  activity_pointer_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  activity_pointer_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  activity_pointer_email_hash: WebMappingRetrieve<EmailHash_Select,EmailHash_Expand,EmailHash_Filter,EmailHash_Fixed,EmailHash_Result,EmailHash_FormattedResult>;
  activity_pointer_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  activity_pointer_incident_resolution: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  activity_pointer_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  activity_pointer_msdyn_approval: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  activity_pointer_msdyn_bookingalert: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  activity_pointer_msdyn_ocliveworkitem: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  activity_pointer_msdyn_ocoutboundmessage: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  activity_pointer_msdyn_ocsession: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  activity_pointer_msfp_alert: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  activity_pointer_msfp_surveyinvite: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  activity_pointer_msfp_surveyresponse: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  activity_pointer_opportunity_close: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  activity_pointer_order_close: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  activity_pointer_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  activity_pointer_quote_close: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  activity_pointer_recurrencerule: WebMappingRetrieve<RecurrenceRule_Select,RecurrenceRule_Expand,RecurrenceRule_Filter,RecurrenceRule_Fixed,RecurrenceRule_Result,RecurrenceRule_FormattedResult>;
  activity_pointer_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  activity_pointer_service_appointment: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  activity_pointer_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  activity_pointer_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  activitypointer_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  activitypointer_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  activitypointer_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  slakpiinstance_activitypointer: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
}
interface WebEntitiesRetrieve {
  activitypointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
}
interface WebEntitiesRelated {
  activitypointers: WebMappingRelated<ActivityPointer_RelatedOne,ActivityPointer_RelatedMany>;
}
interface WebEntitiesCUDA {
  activitypointers: WebMappingCUDA<ActivityPointer_Create,ActivityPointer_Update,ActivityPointer_Select>;
}
