interface Appointment_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  attachmentcount?: number | null;
  attachmenterrors?: appointment_attachmenterrors | null;
  category?: string | null;
  createdon?: Date | null;
  description?: string | null;
  exchangerate?: number | null;
  globalobjectid?: string | null;
  importsequencenumber?: number | null;
  instancetypecode?: appointment_instancetypecode | null;
  isalldayevent?: boolean | null;
  isbilled?: boolean | null;
  isdraft?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isunsafe?: number | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  location?: string | null;
  modifiedfieldsmask?: string | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  originalstartdate?: Date | null;
  outlookownerapptid?: number | null;
  overriddencreatedon?: Date | null;
  prioritycode?: appointment_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: appointment_statecode | null;
  statuscode?: appointment_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  subscriptionid?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface Appointment_Relationships {
  Appointment_Annotation?: Annotation_Result[] | null;
  Appointment_AsyncOperations?: AsyncOperation_Result[] | null;
  Appointment_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Appointment_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Appointment_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Appointment_ProcessSessions?: ProcessSession_Result[] | null;
  Appointment_QueueItem?: QueueItem_Result[] | null;
  Appointment_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  appointment_PostFollows?: PostFollow_Result[] | null;
  appointment_PostRegardings?: PostRegarding_Result[] | null;
  appointment_PostRoles?: PostRole_Result[] | null;
  appointment_actioncard?: ActionCard_Result[] | null;
  appointment_activity_mime_attachment?: ActivityMimeAttachment_Result[] | null;
  appointment_activity_parties?: ActivityParty_Result[] | null;
  appointment_campaignresponse?: CampaignResponse_Result[] | null;
  appointment_connections1?: Connection_Result[] | null;
  appointment_connections2?: Connection_Result[] | null;
  appointment_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  createdby_appointment?: SystemUser_Result | null;
  createdonbehalfby_appointment?: SystemUser_Result | null;
  modifiedby_appointment?: SystemUser_Result | null;
  modifiedonbehalfby_appointment?: SystemUser_Result | null;
  msdyn_appointment_bookableresourcebooking?: BookableResourceBooking_Result[] | null;
  msdyn_appointment_msdyn_resourcerequirement?: msdyn_resourcerequirement_Result[] | null;
  ownerid_appointment?: Team_Result | null;
  ownerid_appointment1?: SystemUser_Result | null;
  owningbusinessunit_appointment?: BusinessUnit_Result | null;
  owningteam_appointment?: Team_Result | null;
  owninguser_appointment?: SystemUser_Result | null;
  regardingobjectid_account_appointment?: Account_Result | null;
  regardingobjectid_bookableresourcebooking_appointment?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_appointment?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_appointment?: BulkOperation_Result | null;
  regardingobjectid_campaign_appointment?: Campaign_Result | null;
  regardingobjectid_campaignactivity_appointment?: CampaignActivity_Result | null;
  regardingobjectid_contact_appointment?: Contact_Result | null;
  regardingobjectid_contract_appointment?: Contract_Result | null;
  regardingobjectid_entitlement_appointment?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_appointment?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_appointment?: Incident_Result | null;
  regardingobjectid_invoice_appointment?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_appointment?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_appointment?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_appointment?: Lead_Result | null;
  regardingobjectid_msdyn_agreement_appointment?: msdyn_agreement_Result | null;
  regardingobjectid_msdyn_agreementbookingdate_appointment?: msdyn_agreementbookingdate_Result | null;
  regardingobjectid_msdyn_agreementbookingincident_appointment?: msdyn_agreementbookingincident_Result | null;
  regardingobjectid_msdyn_agreementbookingproduct_appointment?: msdyn_agreementbookingproduct_Result | null;
  regardingobjectid_msdyn_agreementbookingservice_appointment?: msdyn_agreementbookingservice_Result | null;
  regardingobjectid_msdyn_agreementbookingservicetask_appointment?: msdyn_agreementbookingservicetask_Result | null;
  regardingobjectid_msdyn_agreementbookingsetup_appointment?: msdyn_agreementbookingsetup_Result | null;
  regardingobjectid_msdyn_agreementinvoicedate_appointment?: msdyn_agreementinvoicedate_Result | null;
  regardingobjectid_msdyn_agreementinvoiceproduct_appointment?: msdyn_agreementinvoiceproduct_Result | null;
  regardingobjectid_msdyn_agreementinvoicesetup_appointment?: msdyn_agreementinvoicesetup_Result | null;
  regardingobjectid_msdyn_bookingalertstatus_appointment?: msdyn_bookingalertstatus_Result | null;
  regardingobjectid_msdyn_bookingrule_appointment?: msdyn_bookingrule_Result | null;
  regardingobjectid_msdyn_bookingtimestamp_appointment?: msdyn_bookingtimestamp_Result | null;
  regardingobjectid_msdyn_customerasset_appointment?: msdyn_customerasset_Result | null;
  regardingobjectid_msdyn_fieldservicesetting_appointment?: msdyn_fieldservicesetting_Result | null;
  regardingobjectid_msdyn_incidenttypecharacteristic_appointment?: msdyn_incidenttypecharacteristic_Result | null;
  regardingobjectid_msdyn_incidenttypeproduct_appointment?: msdyn_incidenttypeproduct_Result | null;
  regardingobjectid_msdyn_incidenttypeservice_appointment?: msdyn_incidenttypeservice_Result | null;
  regardingobjectid_msdyn_inventoryadjustment_appointment?: msdyn_inventoryadjustment_Result | null;
  regardingobjectid_msdyn_inventoryadjustmentproduct_appointment?: msdyn_inventoryadjustmentproduct_Result | null;
  regardingobjectid_msdyn_inventoryjournal_appointment?: msdyn_inventoryjournal_Result | null;
  regardingobjectid_msdyn_inventorytransfer_appointment?: msdyn_inventorytransfer_Result | null;
  regardingobjectid_msdyn_payment_appointment?: msdyn_payment_Result | null;
  regardingobjectid_msdyn_paymentdetail_appointment?: msdyn_paymentdetail_Result | null;
  regardingobjectid_msdyn_paymentmethod_appointment?: msdyn_paymentmethod_Result | null;
  regardingobjectid_msdyn_paymentterm_appointment?: msdyn_paymentterm_Result | null;
  regardingobjectid_msdyn_playbookinstance_appointment?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_appointment?: msdyn_PostAlbum_Result | null;
  regardingobjectid_msdyn_postalcode_appointment?: msdyn_postalcode_Result | null;
  regardingobjectid_msdyn_processnotes_appointment?: msdyn_processnotes_Result | null;
  regardingobjectid_msdyn_productinventory_appointment?: msdyn_productinventory_Result | null;
  regardingobjectid_msdyn_projectteam_appointment?: msdyn_projectteam_Result | null;
  regardingobjectid_msdyn_purchaseorder_appointment?: msdyn_purchaseorder_Result | null;
  regardingobjectid_msdyn_purchaseorderbill_appointment?: msdyn_purchaseorderbill_Result | null;
  regardingobjectid_msdyn_purchaseorderproduct_appointment?: msdyn_purchaseorderproduct_Result | null;
  regardingobjectid_msdyn_purchaseorderreceipt_appointment?: msdyn_purchaseorderreceipt_Result | null;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_appointment?: msdyn_purchaseorderreceiptproduct_Result | null;
  regardingobjectid_msdyn_purchaseordersubstatus_appointment?: msdyn_purchaseordersubstatus_Result | null;
  regardingobjectid_msdyn_quotebookingincident_appointment?: msdyn_quotebookingincident_Result | null;
  regardingobjectid_msdyn_quotebookingproduct_appointment?: msdyn_quotebookingproduct_Result | null;
  regardingobjectid_msdyn_quotebookingservice_appointment?: msdyn_quotebookingservice_Result | null;
  regardingobjectid_msdyn_quotebookingservicetask_appointment?: msdyn_quotebookingservicetask_Result | null;
  regardingobjectid_msdyn_resourceterritory_appointment?: msdyn_resourceterritory_Result | null;
  regardingobjectid_msdyn_rma_appointment?: msdyn_rma_Result | null;
  regardingobjectid_msdyn_rmaproduct_appointment?: msdyn_rmaproduct_Result | null;
  regardingobjectid_msdyn_rmareceipt_appointment?: msdyn_rmareceipt_Result | null;
  regardingobjectid_msdyn_rmareceiptproduct_appointment?: msdyn_rmareceiptproduct_Result | null;
  regardingobjectid_msdyn_rmasubstatus_appointment?: msdyn_rmasubstatus_Result | null;
  regardingobjectid_msdyn_rtv_appointment?: msdyn_rtv_Result | null;
  regardingobjectid_msdyn_rtvproduct_appointment?: msdyn_rtvproduct_Result | null;
  regardingobjectid_msdyn_rtvsubstatus_appointment?: msdyn_rtvsubstatus_Result | null;
  regardingobjectid_msdyn_shipvia_appointment?: msdyn_shipvia_Result | null;
  regardingobjectid_msdyn_systemuserschedulersetting_appointment?: msdyn_systemuserschedulersetting_Result | null;
  regardingobjectid_msdyn_timegroup_appointment?: msdyn_timegroup_Result | null;
  regardingobjectid_msdyn_timegroupdetail_appointment?: msdyn_timegroupdetail_Result | null;
  regardingobjectid_msdyn_timeoffrequest_appointment?: msdyn_timeoffrequest_Result | null;
  regardingobjectid_msdyn_warehouse_appointment?: msdyn_warehouse_Result | null;
  regardingobjectid_msdyn_workorder_appointment?: msdyn_workorder_Result | null;
  regardingobjectid_msdyn_workordercharacteristic_appointment?: msdyn_workordercharacteristic_Result | null;
  regardingobjectid_msdyn_workorderincident_appointment?: msdyn_workorderincident_Result | null;
  regardingobjectid_msdyn_workorderproduct_appointment?: msdyn_workorderproduct_Result | null;
  regardingobjectid_msdyn_workorderresourcerestriction_appointment?: msdyn_workorderresourcerestriction_Result | null;
  regardingobjectid_msdyn_workorderservice_appointment?: msdyn_workorderservice_Result | null;
  regardingobjectid_msdyn_workorderservicetask_appointment?: msdyn_workorderservicetask_Result | null;
  regardingobjectid_opportunity_appointment?: Opportunity_Result | null;
  regardingobjectid_quote_appointment?: Quote_Result | null;
  regardingobjectid_salesorder_appointment?: SalesOrder_Result | null;
  regardingobjectid_site_appointment?: Site_Result | null;
  regardingobjectid_uii_action_appointment?: UII_action_Result | null;
  regardingobjectid_uii_hostedapplication_appointment?: UII_hostedapplication_Result | null;
  regardingobjectid_uii_nonhostedapplication_appointment?: UII_nonhostedapplication_Result | null;
  regardingobjectid_uii_option_appointment?: uii_option_Result | null;
  regardingobjectid_uii_savedsession_appointment?: UII_savedsession_Result | null;
  regardingobjectid_uii_workflow_appointment?: UII_workflow_Result | null;
  regardingobjectid_uii_workflow_workflowstep_mapping_appointment?: UII_workflow_workflowstep_mapping_Result | null;
  regardingobjectid_uii_workflowstep_appointment?: UII_workflowstep_Result | null;
  seriesid_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  serviceid_appointment?: Service_Result | null;
  sla_appointment_sla?: SLA_Result | null;
  slainvokedid_appointment_sla?: SLA_Result | null;
  slakpiinstance_appointment?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  transactioncurrencyid_appointment?: TransactionCurrency_Result | null;
  userentityinstancedata_appointment?: UserEntityInstanceData_Result[] | null;
}
interface Appointment extends Appointment_Base, Appointment_Relationships {
  ownerid_appointment_bind$systemusers?: string | null;
  ownerid_appointment_bind$teams?: string | null;
  regardingobjectid_account_appointment_bind$accounts?: string | null;
  regardingobjectid_bookableresourcebooking_appointment_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_appointment_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_appointment_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_appointment_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_appointment_bind$campaignactivities?: string | null;
  regardingobjectid_contact_appointment_bind$contacts?: string | null;
  regardingobjectid_contract_appointment_bind$contracts?: string | null;
  regardingobjectid_entitlement_appointment_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_appointment_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_appointment_bind$incidents?: string | null;
  regardingobjectid_invoice_appointment_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_appointment_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_appointment_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_appointment_bind$leads?: string | null;
  regardingobjectid_msdyn_agreement_appointment_bind$msdyn_agreements?: string | null;
  regardingobjectid_msdyn_agreementbookingdate_appointment_bind$msdyn_agreementbookingdates?: string | null;
  regardingobjectid_msdyn_agreementbookingincident_appointment_bind$msdyn_agreementbookingincidents?: string | null;
  regardingobjectid_msdyn_agreementbookingproduct_appointment_bind$msdyn_agreementbookingproducts?: string | null;
  regardingobjectid_msdyn_agreementbookingservice_appointment_bind$msdyn_agreementbookingservices?: string | null;
  regardingobjectid_msdyn_agreementbookingservicetask_appointment_bind$msdyn_agreementbookingservicetasks?: string | null;
  regardingobjectid_msdyn_agreementbookingsetup_appointment_bind$msdyn_agreementbookingsetups?: string | null;
  regardingobjectid_msdyn_agreementinvoicedate_appointment_bind$msdyn_agreementinvoicedates?: string | null;
  regardingobjectid_msdyn_agreementinvoiceproduct_appointment_bind$msdyn_agreementinvoiceproducts?: string | null;
  regardingobjectid_msdyn_agreementinvoicesetup_appointment_bind$msdyn_agreementinvoicesetups?: string | null;
  regardingobjectid_msdyn_bookingalertstatus_appointment_bind$msdyn_bookingalertstatuses?: string | null;
  regardingobjectid_msdyn_bookingrule_appointment_bind$msdyn_bookingrules?: string | null;
  regardingobjectid_msdyn_bookingtimestamp_appointment_bind$msdyn_bookingtimestamps?: string | null;
  regardingobjectid_msdyn_customerasset_appointment_bind$msdyn_customerassets?: string | null;
  regardingobjectid_msdyn_fieldservicesetting_appointment_bind$msdyn_fieldservicesettings?: string | null;
  regardingobjectid_msdyn_incidenttypecharacteristic_appointment_bind$msdyn_incidenttypecharacteristics?: string | null;
  regardingobjectid_msdyn_incidenttypeproduct_appointment_bind$msdyn_incidenttypeproducts?: string | null;
  regardingobjectid_msdyn_incidenttypeservice_appointment_bind$msdyn_incidenttypeservices?: string | null;
  regardingobjectid_msdyn_inventoryadjustment_appointment_bind$msdyn_inventoryadjustments?: string | null;
  regardingobjectid_msdyn_inventoryadjustmentproduct_appointment_bind$msdyn_inventoryadjustmentproducts?: string | null;
  regardingobjectid_msdyn_inventoryjournal_appointment_bind$msdyn_inventoryjournals?: string | null;
  regardingobjectid_msdyn_inventorytransfer_appointment_bind$msdyn_inventorytransfers?: string | null;
  regardingobjectid_msdyn_payment_appointment_bind$msdyn_payments?: string | null;
  regardingobjectid_msdyn_paymentdetail_appointment_bind$msdyn_paymentdetailes?: string | null;
  regardingobjectid_msdyn_paymentmethod_appointment_bind$msdyn_paymentmethods?: string | null;
  regardingobjectid_msdyn_paymentterm_appointment_bind$msdyn_paymentterms?: string | null;
  regardingobjectid_msdyn_playbookinstance_appointment_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_appointment_bind$msdyn_postalbums?: string | null;
  regardingobjectid_msdyn_postalcode_appointment_bind$msdyn_postalcodes?: string | null;
  regardingobjectid_msdyn_processnotes_appointment_bind$msdyn_processnoteses?: string | null;
  regardingobjectid_msdyn_productinventory_appointment_bind$msdyn_productinventories?: string | null;
  regardingobjectid_msdyn_projectteam_appointment_bind$msdyn_projectteams?: string | null;
  regardingobjectid_msdyn_purchaseorder_appointment_bind$msdyn_purchaseorders?: string | null;
  regardingobjectid_msdyn_purchaseorderbill_appointment_bind$msdyn_purchaseorderbills?: string | null;
  regardingobjectid_msdyn_purchaseorderproduct_appointment_bind$msdyn_purchaseorderproducts?: string | null;
  regardingobjectid_msdyn_purchaseorderreceipt_appointment_bind$msdyn_purchaseorderreceipts?: string | null;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_appointment_bind$msdyn_purchaseorderreceiptproducts?: string | null;
  regardingobjectid_msdyn_purchaseordersubstatus_appointment_bind$msdyn_purchaseordersubstatuses?: string | null;
  regardingobjectid_msdyn_quotebookingincident_appointment_bind$msdyn_quotebookingincidents?: string | null;
  regardingobjectid_msdyn_quotebookingproduct_appointment_bind$msdyn_quotebookingproducts?: string | null;
  regardingobjectid_msdyn_quotebookingservice_appointment_bind$msdyn_quotebookingservices?: string | null;
  regardingobjectid_msdyn_quotebookingservicetask_appointment_bind$msdyn_quotebookingservicetasks?: string | null;
  regardingobjectid_msdyn_resourceterritory_appointment_bind$msdyn_resourceterritories?: string | null;
  regardingobjectid_msdyn_rma_appointment_bind$msdyn_rmas?: string | null;
  regardingobjectid_msdyn_rmaproduct_appointment_bind$msdyn_rmaproducts?: string | null;
  regardingobjectid_msdyn_rmareceipt_appointment_bind$msdyn_rmareceipts?: string | null;
  regardingobjectid_msdyn_rmareceiptproduct_appointment_bind$msdyn_rmareceiptproducts?: string | null;
  regardingobjectid_msdyn_rmasubstatus_appointment_bind$msdyn_rmasubstatuses?: string | null;
  regardingobjectid_msdyn_rtv_appointment_bind$msdyn_rtvs?: string | null;
  regardingobjectid_msdyn_rtvproduct_appointment_bind$msdyn_rtvproducts?: string | null;
  regardingobjectid_msdyn_rtvsubstatus_appointment_bind$msdyn_rtvsubstatuses?: string | null;
  regardingobjectid_msdyn_shipvia_appointment_bind$msdyn_shipvias?: string | null;
  regardingobjectid_msdyn_systemuserschedulersetting_appointment_bind$msdyn_systemuserschedulersettinges?: string | null;
  regardingobjectid_msdyn_timegroup_appointment_bind$msdyn_timegroups?: string | null;
  regardingobjectid_msdyn_timegroupdetail_appointment_bind$msdyn_timegroupdetails?: string | null;
  regardingobjectid_msdyn_timeoffrequest_appointment_bind$msdyn_timeoffrequests?: string | null;
  regardingobjectid_msdyn_warehouse_appointment_bind$msdyn_warehouses?: string | null;
  regardingobjectid_msdyn_workorder_appointment_bind$msdyn_workorders?: string | null;
  regardingobjectid_msdyn_workordercharacteristic_appointment_bind$msdyn_workordercharacteristics?: string | null;
  regardingobjectid_msdyn_workorderincident_appointment_bind$msdyn_workorderincidents?: string | null;
  regardingobjectid_msdyn_workorderproduct_appointment_bind$msdyn_workorderproducts?: string | null;
  regardingobjectid_msdyn_workorderresourcerestriction_appointment_bind$msdyn_workorderresourcerestrictions?: string | null;
  regardingobjectid_msdyn_workorderservice_appointment_bind$msdyn_workorderservices?: string | null;
  regardingobjectid_msdyn_workorderservicetask_appointment_bind$msdyn_workorderservicetasks?: string | null;
  regardingobjectid_opportunity_appointment_bind$opportunities?: string | null;
  regardingobjectid_quote_appointment_bind$quotes?: string | null;
  regardingobjectid_salesorder_appointment_bind$salesorders?: string | null;
  regardingobjectid_site_appointment_bind$sites?: string | null;
  regardingobjectid_uii_action_appointment_bind$uii_actions?: string | null;
  regardingobjectid_uii_hostedapplication_appointment_bind$uii_hostedapplications?: string | null;
  regardingobjectid_uii_nonhostedapplication_appointment_bind$uii_nonhostedapplications?: string | null;
  regardingobjectid_uii_option_appointment_bind$uii_options?: string | null;
  regardingobjectid_uii_savedsession_appointment_bind$uii_savedsessions?: string | null;
  regardingobjectid_uii_workflow_appointment_bind$uii_workflows?: string | null;
  regardingobjectid_uii_workflow_workflowstep_mapping_appointment_bind$uii_workflow_workflowstep_mappings?: string | null;
  regardingobjectid_uii_workflowstep_appointment_bind$uii_workflowsteps?: string | null;
  serviceid_appointment_bind$services?: string | null;
  sla_appointment_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_appointment_bind$transactioncurrencies?: string | null;
}
interface Appointment_Create extends Appointment {
  activityid_activitypointer_bind$activitypointers?: string | null;
}
interface Appointment_Update extends Appointment {
}
interface Appointment_Select {
  activityadditionalparams: WebAttribute<Appointment_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<Appointment_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<Appointment_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<Appointment_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<Appointment_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<Appointment_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  attachmentcount: WebAttribute<Appointment_Select, { attachmentcount: number | null }, {  }>;
  attachmenterrors: WebAttribute<Appointment_Select, { attachmenterrors: appointment_attachmenterrors | null }, { attachmenterrors_formatted?: string }>;
  category: WebAttribute<Appointment_Select, { category: string | null }, {  }>;
  createdby_guid: WebAttribute<Appointment_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Appointment_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Appointment_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<Appointment_Select, { description: string | null }, {  }>;
  exchangerate: WebAttribute<Appointment_Select, { exchangerate: number | null }, {  }>;
  globalobjectid: WebAttribute<Appointment_Select, { globalobjectid: string | null }, {  }>;
  importsequencenumber: WebAttribute<Appointment_Select, { importsequencenumber: number | null }, {  }>;
  instancetypecode: WebAttribute<Appointment_Select, { instancetypecode: appointment_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isalldayevent: WebAttribute<Appointment_Select, { isalldayevent: boolean | null }, {  }>;
  isbilled: WebAttribute<Appointment_Select, { isbilled: boolean | null }, {  }>;
  isdraft: WebAttribute<Appointment_Select, { isdraft: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<Appointment_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<Appointment_Select, { isregularactivity: boolean | null }, {  }>;
  isunsafe: WebAttribute<Appointment_Select, { isunsafe: number | null }, {  }>;
  isworkflowcreated: WebAttribute<Appointment_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<Appointment_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  location: WebAttribute<Appointment_Select, { location: string | null }, {  }>;
  modifiedby_guid: WebAttribute<Appointment_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedfieldsmask: WebAttribute<Appointment_Select, { modifiedfieldsmask: string | null }, {  }>;
  modifiedon: WebAttribute<Appointment_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Appointment_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<Appointment_Select, { onholdtime: number | null }, {  }>;
  optionalattendees_guid: WebAttribute<Appointment_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<Appointment_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  originalstartdate: WebAttribute<Appointment_Select, { originalstartdate: Date | null }, { originalstartdate_formatted?: string }>;
  outlookownerapptid: WebAttribute<Appointment_Select, { outlookownerapptid: number | null }, {  }>;
  overriddencreatedon: WebAttribute<Appointment_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Appointment_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Appointment_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Appointment_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Appointment_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  prioritycode: WebAttribute<Appointment_Select, { prioritycode: appointment_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<Appointment_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<Appointment_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<Appointment_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<Appointment_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<Appointment_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<Appointment_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  seriesid: WebAttribute<Appointment_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<Appointment_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<Appointment_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<Appointment_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<Appointment_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<Appointment_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Appointment_Select, { statecode: appointment_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Appointment_Select, { statuscode: appointment_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<Appointment_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<Appointment_Select, { subject: string | null }, {  }>;
  subscriptionid: WebAttribute<Appointment_Select, { subscriptionid: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<Appointment_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<Appointment_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Appointment_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Appointment_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Appointment_Select, { versionnumber: number | null }, {  }>;
}
interface Appointment_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  attachmentcount: number;
  attachmenterrors: appointment_attachmenterrors;
  category: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  exchangerate: any;
  globalobjectid: string;
  importsequencenumber: number;
  instancetypecode: appointment_instancetypecode;
  isalldayevent: boolean;
  isbilled: boolean;
  isdraft: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isunsafe: number;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  location: string;
  modifiedby_guid: XQW.Guid;
  modifiedfieldsmask: string;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  originalstartdate: Date;
  outlookownerapptid: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  prioritycode: appointment_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: appointment_statecode;
  statuscode: appointment_statuscode;
  subcategory: string;
  subject: string;
  subscriptionid: XQW.Guid;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface Appointment_Expand {
  Appointment_Annotation: WebExpand<Appointment_Expand, Annotation_Select, Annotation_Filter, { Appointment_Annotation: Annotation_Result[] }>;
  Appointment_AsyncOperations: WebExpand<Appointment_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Appointment_AsyncOperations: AsyncOperation_Result[] }>;
  Appointment_BulkDeleteFailures: WebExpand<Appointment_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Appointment_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Appointment_DuplicateBaseRecord: WebExpand<Appointment_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Appointment_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Appointment_DuplicateMatchingRecord: WebExpand<Appointment_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Appointment_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Appointment_ProcessSessions: WebExpand<Appointment_Expand, ProcessSession_Select, ProcessSession_Filter, { Appointment_ProcessSessions: ProcessSession_Result[] }>;
  Appointment_QueueItem: WebExpand<Appointment_Expand, QueueItem_Select, QueueItem_Filter, { Appointment_QueueItem: QueueItem_Result[] }>;
  Appointment_SyncErrors: WebExpand<Appointment_Expand, SyncError_Select, SyncError_Filter, { Appointment_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<Appointment_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  appointment_PostFollows: WebExpand<Appointment_Expand, PostFollow_Select, PostFollow_Filter, { appointment_PostFollows: PostFollow_Result[] }>;
  appointment_PostRegardings: WebExpand<Appointment_Expand, PostRegarding_Select, PostRegarding_Filter, { appointment_PostRegardings: PostRegarding_Result[] }>;
  appointment_PostRoles: WebExpand<Appointment_Expand, PostRole_Select, PostRole_Filter, { appointment_PostRoles: PostRole_Result[] }>;
  appointment_actioncard: WebExpand<Appointment_Expand, ActionCard_Select, ActionCard_Filter, { appointment_actioncard: ActionCard_Result[] }>;
  appointment_activity_mime_attachment: WebExpand<Appointment_Expand, ActivityMimeAttachment_Select, ActivityMimeAttachment_Filter, { appointment_activity_mime_attachment: ActivityMimeAttachment_Result[] }>;
  appointment_activity_parties: WebExpand<Appointment_Expand, ActivityParty_Select, ActivityParty_Filter, { appointment_activity_parties: ActivityParty_Result[] }>;
  appointment_campaignresponse: WebExpand<Appointment_Expand, CampaignResponse_Select, CampaignResponse_Filter, { appointment_campaignresponse: CampaignResponse_Result[] }>;
  appointment_connections1: WebExpand<Appointment_Expand, Connection_Select, Connection_Filter, { appointment_connections1: Connection_Result[] }>;
  appointment_connections2: WebExpand<Appointment_Expand, Connection_Select, Connection_Filter, { appointment_connections2: Connection_Result[] }>;
  appointment_principalobjectattributeaccess: WebExpand<Appointment_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { appointment_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  createdby_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { createdby_appointment: SystemUser_Result }>;
  createdonbehalfby_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_appointment: SystemUser_Result }>;
  modifiedby_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_appointment: SystemUser_Result }>;
  modifiedonbehalfby_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_appointment: SystemUser_Result }>;
  msdyn_appointment_bookableresourcebooking: WebExpand<Appointment_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { msdyn_appointment_bookableresourcebooking: BookableResourceBooking_Result[] }>;
  msdyn_appointment_msdyn_resourcerequirement: WebExpand<Appointment_Expand, msdyn_resourcerequirement_Select, msdyn_resourcerequirement_Filter, { msdyn_appointment_msdyn_resourcerequirement: msdyn_resourcerequirement_Result[] }>;
  ownerid_appointment: WebExpand<Appointment_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_appointment: SystemUser_Result } & { ownerid_appointment: Team_Result }>;
  owningbusinessunit_appointment: WebExpand<Appointment_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_appointment: BusinessUnit_Result }>;
  owningteam_appointment: WebExpand<Appointment_Expand, Team_Select, Team_Filter, { owningteam_appointment: Team_Result }>;
  owninguser_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_appointment: SystemUser_Result }>;
  regardingobjectid_account_appointment: WebExpand<Appointment_Expand, Account_Select, Account_Filter, { regardingobjectid_account_appointment: Account_Result }>;
  regardingobjectid_bookableresourcebooking_appointment: WebExpand<Appointment_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_appointment: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_appointment: WebExpand<Appointment_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_appointment: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_appointment: WebExpand<Appointment_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_appointment: BulkOperation_Result }>;
  regardingobjectid_campaign_appointment: WebExpand<Appointment_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_appointment: Campaign_Result }>;
  regardingobjectid_campaignactivity_appointment: WebExpand<Appointment_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_appointment: CampaignActivity_Result }>;
  regardingobjectid_contact_appointment: WebExpand<Appointment_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_appointment: Contact_Result }>;
  regardingobjectid_contract_appointment: WebExpand<Appointment_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_appointment: Contract_Result }>;
  regardingobjectid_entitlement_appointment: WebExpand<Appointment_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_appointment: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_appointment: WebExpand<Appointment_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_appointment: EntitlementTemplate_Result }>;
  regardingobjectid_incident_appointment: WebExpand<Appointment_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_appointment: Incident_Result }>;
  regardingobjectid_invoice_appointment: WebExpand<Appointment_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_appointment: Invoice_Result }>;
  regardingobjectid_knowledgearticle_appointment: WebExpand<Appointment_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_appointment: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_appointment: WebExpand<Appointment_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_appointment: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_appointment: WebExpand<Appointment_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_appointment: Lead_Result }>;
  regardingobjectid_msdyn_agreement_appointment: WebExpand<Appointment_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { regardingobjectid_msdyn_agreement_appointment: msdyn_agreement_Result }>;
  regardingobjectid_msdyn_agreementbookingdate_appointment: WebExpand<Appointment_Expand, msdyn_agreementbookingdate_Select, msdyn_agreementbookingdate_Filter, { regardingobjectid_msdyn_agreementbookingdate_appointment: msdyn_agreementbookingdate_Result }>;
  regardingobjectid_msdyn_agreementbookingincident_appointment: WebExpand<Appointment_Expand, msdyn_agreementbookingincident_Select, msdyn_agreementbookingincident_Filter, { regardingobjectid_msdyn_agreementbookingincident_appointment: msdyn_agreementbookingincident_Result }>;
  regardingobjectid_msdyn_agreementbookingproduct_appointment: WebExpand<Appointment_Expand, msdyn_agreementbookingproduct_Select, msdyn_agreementbookingproduct_Filter, { regardingobjectid_msdyn_agreementbookingproduct_appointment: msdyn_agreementbookingproduct_Result }>;
  regardingobjectid_msdyn_agreementbookingservice_appointment: WebExpand<Appointment_Expand, msdyn_agreementbookingservice_Select, msdyn_agreementbookingservice_Filter, { regardingobjectid_msdyn_agreementbookingservice_appointment: msdyn_agreementbookingservice_Result }>;
  regardingobjectid_msdyn_agreementbookingservicetask_appointment: WebExpand<Appointment_Expand, msdyn_agreementbookingservicetask_Select, msdyn_agreementbookingservicetask_Filter, { regardingobjectid_msdyn_agreementbookingservicetask_appointment: msdyn_agreementbookingservicetask_Result }>;
  regardingobjectid_msdyn_agreementbookingsetup_appointment: WebExpand<Appointment_Expand, msdyn_agreementbookingsetup_Select, msdyn_agreementbookingsetup_Filter, { regardingobjectid_msdyn_agreementbookingsetup_appointment: msdyn_agreementbookingsetup_Result }>;
  regardingobjectid_msdyn_agreementinvoicedate_appointment: WebExpand<Appointment_Expand, msdyn_agreementinvoicedate_Select, msdyn_agreementinvoicedate_Filter, { regardingobjectid_msdyn_agreementinvoicedate_appointment: msdyn_agreementinvoicedate_Result }>;
  regardingobjectid_msdyn_agreementinvoiceproduct_appointment: WebExpand<Appointment_Expand, msdyn_agreementinvoiceproduct_Select, msdyn_agreementinvoiceproduct_Filter, { regardingobjectid_msdyn_agreementinvoiceproduct_appointment: msdyn_agreementinvoiceproduct_Result }>;
  regardingobjectid_msdyn_agreementinvoicesetup_appointment: WebExpand<Appointment_Expand, msdyn_agreementinvoicesetup_Select, msdyn_agreementinvoicesetup_Filter, { regardingobjectid_msdyn_agreementinvoicesetup_appointment: msdyn_agreementinvoicesetup_Result }>;
  regardingobjectid_msdyn_bookingalertstatus_appointment: WebExpand<Appointment_Expand, msdyn_bookingalertstatus_Select, msdyn_bookingalertstatus_Filter, { regardingobjectid_msdyn_bookingalertstatus_appointment: msdyn_bookingalertstatus_Result }>;
  regardingobjectid_msdyn_bookingrule_appointment: WebExpand<Appointment_Expand, msdyn_bookingrule_Select, msdyn_bookingrule_Filter, { regardingobjectid_msdyn_bookingrule_appointment: msdyn_bookingrule_Result }>;
  regardingobjectid_msdyn_bookingtimestamp_appointment: WebExpand<Appointment_Expand, msdyn_bookingtimestamp_Select, msdyn_bookingtimestamp_Filter, { regardingobjectid_msdyn_bookingtimestamp_appointment: msdyn_bookingtimestamp_Result }>;
  regardingobjectid_msdyn_customerasset_appointment: WebExpand<Appointment_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { regardingobjectid_msdyn_customerasset_appointment: msdyn_customerasset_Result }>;
  regardingobjectid_msdyn_fieldservicesetting_appointment: WebExpand<Appointment_Expand, msdyn_fieldservicesetting_Select, msdyn_fieldservicesetting_Filter, { regardingobjectid_msdyn_fieldservicesetting_appointment: msdyn_fieldservicesetting_Result }>;
  regardingobjectid_msdyn_incidenttypecharacteristic_appointment: WebExpand<Appointment_Expand, msdyn_incidenttypecharacteristic_Select, msdyn_incidenttypecharacteristic_Filter, { regardingobjectid_msdyn_incidenttypecharacteristic_appointment: msdyn_incidenttypecharacteristic_Result }>;
  regardingobjectid_msdyn_incidenttypeproduct_appointment: WebExpand<Appointment_Expand, msdyn_incidenttypeproduct_Select, msdyn_incidenttypeproduct_Filter, { regardingobjectid_msdyn_incidenttypeproduct_appointment: msdyn_incidenttypeproduct_Result }>;
  regardingobjectid_msdyn_incidenttypeservice_appointment: WebExpand<Appointment_Expand, msdyn_incidenttypeservice_Select, msdyn_incidenttypeservice_Filter, { regardingobjectid_msdyn_incidenttypeservice_appointment: msdyn_incidenttypeservice_Result }>;
  regardingobjectid_msdyn_inventoryadjustment_appointment: WebExpand<Appointment_Expand, msdyn_inventoryadjustment_Select, msdyn_inventoryadjustment_Filter, { regardingobjectid_msdyn_inventoryadjustment_appointment: msdyn_inventoryadjustment_Result }>;
  regardingobjectid_msdyn_inventoryadjustmentproduct_appointment: WebExpand<Appointment_Expand, msdyn_inventoryadjustmentproduct_Select, msdyn_inventoryadjustmentproduct_Filter, { regardingobjectid_msdyn_inventoryadjustmentproduct_appointment: msdyn_inventoryadjustmentproduct_Result }>;
  regardingobjectid_msdyn_inventoryjournal_appointment: WebExpand<Appointment_Expand, msdyn_inventoryjournal_Select, msdyn_inventoryjournal_Filter, { regardingobjectid_msdyn_inventoryjournal_appointment: msdyn_inventoryjournal_Result }>;
  regardingobjectid_msdyn_inventorytransfer_appointment: WebExpand<Appointment_Expand, msdyn_inventorytransfer_Select, msdyn_inventorytransfer_Filter, { regardingobjectid_msdyn_inventorytransfer_appointment: msdyn_inventorytransfer_Result }>;
  regardingobjectid_msdyn_payment_appointment: WebExpand<Appointment_Expand, msdyn_payment_Select, msdyn_payment_Filter, { regardingobjectid_msdyn_payment_appointment: msdyn_payment_Result }>;
  regardingobjectid_msdyn_paymentdetail_appointment: WebExpand<Appointment_Expand, msdyn_paymentdetail_Select, msdyn_paymentdetail_Filter, { regardingobjectid_msdyn_paymentdetail_appointment: msdyn_paymentdetail_Result }>;
  regardingobjectid_msdyn_paymentmethod_appointment: WebExpand<Appointment_Expand, msdyn_paymentmethod_Select, msdyn_paymentmethod_Filter, { regardingobjectid_msdyn_paymentmethod_appointment: msdyn_paymentmethod_Result }>;
  regardingobjectid_msdyn_paymentterm_appointment: WebExpand<Appointment_Expand, msdyn_paymentterm_Select, msdyn_paymentterm_Filter, { regardingobjectid_msdyn_paymentterm_appointment: msdyn_paymentterm_Result }>;
  regardingobjectid_msdyn_playbookinstance_appointment: WebExpand<Appointment_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_appointment: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_appointment: WebExpand<Appointment_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_appointment: msdyn_PostAlbum_Result }>;
  regardingobjectid_msdyn_postalcode_appointment: WebExpand<Appointment_Expand, msdyn_postalcode_Select, msdyn_postalcode_Filter, { regardingobjectid_msdyn_postalcode_appointment: msdyn_postalcode_Result }>;
  regardingobjectid_msdyn_processnotes_appointment: WebExpand<Appointment_Expand, msdyn_processnotes_Select, msdyn_processnotes_Filter, { regardingobjectid_msdyn_processnotes_appointment: msdyn_processnotes_Result }>;
  regardingobjectid_msdyn_productinventory_appointment: WebExpand<Appointment_Expand, msdyn_productinventory_Select, msdyn_productinventory_Filter, { regardingobjectid_msdyn_productinventory_appointment: msdyn_productinventory_Result }>;
  regardingobjectid_msdyn_projectteam_appointment: WebExpand<Appointment_Expand, msdyn_projectteam_Select, msdyn_projectteam_Filter, { regardingobjectid_msdyn_projectteam_appointment: msdyn_projectteam_Result }>;
  regardingobjectid_msdyn_purchaseorder_appointment: WebExpand<Appointment_Expand, msdyn_purchaseorder_Select, msdyn_purchaseorder_Filter, { regardingobjectid_msdyn_purchaseorder_appointment: msdyn_purchaseorder_Result }>;
  regardingobjectid_msdyn_purchaseorderbill_appointment: WebExpand<Appointment_Expand, msdyn_purchaseorderbill_Select, msdyn_purchaseorderbill_Filter, { regardingobjectid_msdyn_purchaseorderbill_appointment: msdyn_purchaseorderbill_Result }>;
  regardingobjectid_msdyn_purchaseorderproduct_appointment: WebExpand<Appointment_Expand, msdyn_purchaseorderproduct_Select, msdyn_purchaseorderproduct_Filter, { regardingobjectid_msdyn_purchaseorderproduct_appointment: msdyn_purchaseorderproduct_Result }>;
  regardingobjectid_msdyn_purchaseorderreceipt_appointment: WebExpand<Appointment_Expand, msdyn_purchaseorderreceipt_Select, msdyn_purchaseorderreceipt_Filter, { regardingobjectid_msdyn_purchaseorderreceipt_appointment: msdyn_purchaseorderreceipt_Result }>;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_appointment: WebExpand<Appointment_Expand, msdyn_purchaseorderreceiptproduct_Select, msdyn_purchaseorderreceiptproduct_Filter, { regardingobjectid_msdyn_purchaseorderreceiptproduct_appointment: msdyn_purchaseorderreceiptproduct_Result }>;
  regardingobjectid_msdyn_purchaseordersubstatus_appointment: WebExpand<Appointment_Expand, msdyn_purchaseordersubstatus_Select, msdyn_purchaseordersubstatus_Filter, { regardingobjectid_msdyn_purchaseordersubstatus_appointment: msdyn_purchaseordersubstatus_Result }>;
  regardingobjectid_msdyn_quotebookingincident_appointment: WebExpand<Appointment_Expand, msdyn_quotebookingincident_Select, msdyn_quotebookingincident_Filter, { regardingobjectid_msdyn_quotebookingincident_appointment: msdyn_quotebookingincident_Result }>;
  regardingobjectid_msdyn_quotebookingproduct_appointment: WebExpand<Appointment_Expand, msdyn_quotebookingproduct_Select, msdyn_quotebookingproduct_Filter, { regardingobjectid_msdyn_quotebookingproduct_appointment: msdyn_quotebookingproduct_Result }>;
  regardingobjectid_msdyn_quotebookingservice_appointment: WebExpand<Appointment_Expand, msdyn_quotebookingservice_Select, msdyn_quotebookingservice_Filter, { regardingobjectid_msdyn_quotebookingservice_appointment: msdyn_quotebookingservice_Result }>;
  regardingobjectid_msdyn_quotebookingservicetask_appointment: WebExpand<Appointment_Expand, msdyn_quotebookingservicetask_Select, msdyn_quotebookingservicetask_Filter, { regardingobjectid_msdyn_quotebookingservicetask_appointment: msdyn_quotebookingservicetask_Result }>;
  regardingobjectid_msdyn_resourceterritory_appointment: WebExpand<Appointment_Expand, msdyn_resourceterritory_Select, msdyn_resourceterritory_Filter, { regardingobjectid_msdyn_resourceterritory_appointment: msdyn_resourceterritory_Result }>;
  regardingobjectid_msdyn_rma_appointment: WebExpand<Appointment_Expand, msdyn_rma_Select, msdyn_rma_Filter, { regardingobjectid_msdyn_rma_appointment: msdyn_rma_Result }>;
  regardingobjectid_msdyn_rmaproduct_appointment: WebExpand<Appointment_Expand, msdyn_rmaproduct_Select, msdyn_rmaproduct_Filter, { regardingobjectid_msdyn_rmaproduct_appointment: msdyn_rmaproduct_Result }>;
  regardingobjectid_msdyn_rmareceipt_appointment: WebExpand<Appointment_Expand, msdyn_rmareceipt_Select, msdyn_rmareceipt_Filter, { regardingobjectid_msdyn_rmareceipt_appointment: msdyn_rmareceipt_Result }>;
  regardingobjectid_msdyn_rmareceiptproduct_appointment: WebExpand<Appointment_Expand, msdyn_rmareceiptproduct_Select, msdyn_rmareceiptproduct_Filter, { regardingobjectid_msdyn_rmareceiptproduct_appointment: msdyn_rmareceiptproduct_Result }>;
  regardingobjectid_msdyn_rmasubstatus_appointment: WebExpand<Appointment_Expand, msdyn_rmasubstatus_Select, msdyn_rmasubstatus_Filter, { regardingobjectid_msdyn_rmasubstatus_appointment: msdyn_rmasubstatus_Result }>;
  regardingobjectid_msdyn_rtv_appointment: WebExpand<Appointment_Expand, msdyn_rtv_Select, msdyn_rtv_Filter, { regardingobjectid_msdyn_rtv_appointment: msdyn_rtv_Result }>;
  regardingobjectid_msdyn_rtvproduct_appointment: WebExpand<Appointment_Expand, msdyn_rtvproduct_Select, msdyn_rtvproduct_Filter, { regardingobjectid_msdyn_rtvproduct_appointment: msdyn_rtvproduct_Result }>;
  regardingobjectid_msdyn_rtvsubstatus_appointment: WebExpand<Appointment_Expand, msdyn_rtvsubstatus_Select, msdyn_rtvsubstatus_Filter, { regardingobjectid_msdyn_rtvsubstatus_appointment: msdyn_rtvsubstatus_Result }>;
  regardingobjectid_msdyn_shipvia_appointment: WebExpand<Appointment_Expand, msdyn_shipvia_Select, msdyn_shipvia_Filter, { regardingobjectid_msdyn_shipvia_appointment: msdyn_shipvia_Result }>;
  regardingobjectid_msdyn_systemuserschedulersetting_appointment: WebExpand<Appointment_Expand, msdyn_systemuserschedulersetting_Select, msdyn_systemuserschedulersetting_Filter, { regardingobjectid_msdyn_systemuserschedulersetting_appointment: msdyn_systemuserschedulersetting_Result }>;
  regardingobjectid_msdyn_timegroup_appointment: WebExpand<Appointment_Expand, msdyn_timegroup_Select, msdyn_timegroup_Filter, { regardingobjectid_msdyn_timegroup_appointment: msdyn_timegroup_Result }>;
  regardingobjectid_msdyn_timegroupdetail_appointment: WebExpand<Appointment_Expand, msdyn_timegroupdetail_Select, msdyn_timegroupdetail_Filter, { regardingobjectid_msdyn_timegroupdetail_appointment: msdyn_timegroupdetail_Result }>;
  regardingobjectid_msdyn_timeoffrequest_appointment: WebExpand<Appointment_Expand, msdyn_timeoffrequest_Select, msdyn_timeoffrequest_Filter, { regardingobjectid_msdyn_timeoffrequest_appointment: msdyn_timeoffrequest_Result }>;
  regardingobjectid_msdyn_warehouse_appointment: WebExpand<Appointment_Expand, msdyn_warehouse_Select, msdyn_warehouse_Filter, { regardingobjectid_msdyn_warehouse_appointment: msdyn_warehouse_Result }>;
  regardingobjectid_msdyn_workorder_appointment: WebExpand<Appointment_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { regardingobjectid_msdyn_workorder_appointment: msdyn_workorder_Result }>;
  regardingobjectid_msdyn_workordercharacteristic_appointment: WebExpand<Appointment_Expand, msdyn_workordercharacteristic_Select, msdyn_workordercharacteristic_Filter, { regardingobjectid_msdyn_workordercharacteristic_appointment: msdyn_workordercharacteristic_Result }>;
  regardingobjectid_msdyn_workorderincident_appointment: WebExpand<Appointment_Expand, msdyn_workorderincident_Select, msdyn_workorderincident_Filter, { regardingobjectid_msdyn_workorderincident_appointment: msdyn_workorderincident_Result }>;
  regardingobjectid_msdyn_workorderproduct_appointment: WebExpand<Appointment_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { regardingobjectid_msdyn_workorderproduct_appointment: msdyn_workorderproduct_Result }>;
  regardingobjectid_msdyn_workorderresourcerestriction_appointment: WebExpand<Appointment_Expand, msdyn_workorderresourcerestriction_Select, msdyn_workorderresourcerestriction_Filter, { regardingobjectid_msdyn_workorderresourcerestriction_appointment: msdyn_workorderresourcerestriction_Result }>;
  regardingobjectid_msdyn_workorderservice_appointment: WebExpand<Appointment_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { regardingobjectid_msdyn_workorderservice_appointment: msdyn_workorderservice_Result }>;
  regardingobjectid_msdyn_workorderservicetask_appointment: WebExpand<Appointment_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { regardingobjectid_msdyn_workorderservicetask_appointment: msdyn_workorderservicetask_Result }>;
  regardingobjectid_opportunity_appointment: WebExpand<Appointment_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_appointment: Opportunity_Result }>;
  regardingobjectid_quote_appointment: WebExpand<Appointment_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_appointment: Quote_Result }>;
  regardingobjectid_salesorder_appointment: WebExpand<Appointment_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_appointment: SalesOrder_Result }>;
  regardingobjectid_site_appointment: WebExpand<Appointment_Expand, Site_Select, Site_Filter, { regardingobjectid_site_appointment: Site_Result }>;
  regardingobjectid_uii_action_appointment: WebExpand<Appointment_Expand, UII_action_Select, UII_action_Filter, { regardingobjectid_uii_action_appointment: UII_action_Result }>;
  regardingobjectid_uii_hostedapplication_appointment: WebExpand<Appointment_Expand, UII_hostedapplication_Select, UII_hostedapplication_Filter, { regardingobjectid_uii_hostedapplication_appointment: UII_hostedapplication_Result }>;
  regardingobjectid_uii_nonhostedapplication_appointment: WebExpand<Appointment_Expand, UII_nonhostedapplication_Select, UII_nonhostedapplication_Filter, { regardingobjectid_uii_nonhostedapplication_appointment: UII_nonhostedapplication_Result }>;
  regardingobjectid_uii_option_appointment: WebExpand<Appointment_Expand, uii_option_Select, uii_option_Filter, { regardingobjectid_uii_option_appointment: uii_option_Result }>;
  regardingobjectid_uii_savedsession_appointment: WebExpand<Appointment_Expand, UII_savedsession_Select, UII_savedsession_Filter, { regardingobjectid_uii_savedsession_appointment: UII_savedsession_Result }>;
  regardingobjectid_uii_workflow_appointment: WebExpand<Appointment_Expand, UII_workflow_Select, UII_workflow_Filter, { regardingobjectid_uii_workflow_appointment: UII_workflow_Result }>;
  regardingobjectid_uii_workflow_workflowstep_mapping_appointment: WebExpand<Appointment_Expand, UII_workflow_workflowstep_mapping_Select, UII_workflow_workflowstep_mapping_Filter, { regardingobjectid_uii_workflow_workflowstep_mapping_appointment: UII_workflow_workflowstep_mapping_Result }>;
  regardingobjectid_uii_workflowstep_appointment: WebExpand<Appointment_Expand, UII_workflowstep_Select, UII_workflowstep_Filter, { regardingobjectid_uii_workflowstep_appointment: UII_workflowstep_Result }>;
  seriesid_recurringappointmentmaster: WebExpand<Appointment_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { seriesid_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  serviceid_appointment: WebExpand<Appointment_Expand, Service_Select, Service_Filter, { serviceid_appointment: Service_Result }>;
  sla_appointment_sla: WebExpand<Appointment_Expand, SLA_Select, SLA_Filter, { sla_appointment_sla: SLA_Result }>;
  slainvokedid_appointment_sla: WebExpand<Appointment_Expand, SLA_Select, SLA_Filter, { slainvokedid_appointment_sla: SLA_Result }>;
  slakpiinstance_appointment: WebExpand<Appointment_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_appointment: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<Appointment_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid_appointment: WebExpand<Appointment_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_appointment: TransactionCurrency_Result }>;
  userentityinstancedata_appointment: WebExpand<Appointment_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_appointment: UserEntityInstanceData_Result[] }>;
}
interface Appointment_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  attachmenterrors_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  originalstartdate_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Appointment_Result extends Appointment_Base, Appointment_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Appointment_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_appointment: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_appointment1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_appointment: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_appointment: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_appointment: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_bookableresourcebooking_appointment: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_appointment: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_appointment: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_appointment: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_appointment: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_appointment: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_appointment: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_appointment: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_appointment: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_appointment: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_appointment: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_appointment: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_appointment: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_appointment: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_agreement_appointment: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingdate_appointment: WebMappingRetrieve<msdyn_agreementbookingdate_Select,msdyn_agreementbookingdate_Expand,msdyn_agreementbookingdate_Filter,msdyn_agreementbookingdate_Fixed,msdyn_agreementbookingdate_Result,msdyn_agreementbookingdate_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingincident_appointment: WebMappingRetrieve<msdyn_agreementbookingincident_Select,msdyn_agreementbookingincident_Expand,msdyn_agreementbookingincident_Filter,msdyn_agreementbookingincident_Fixed,msdyn_agreementbookingincident_Result,msdyn_agreementbookingincident_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingproduct_appointment: WebMappingRetrieve<msdyn_agreementbookingproduct_Select,msdyn_agreementbookingproduct_Expand,msdyn_agreementbookingproduct_Filter,msdyn_agreementbookingproduct_Fixed,msdyn_agreementbookingproduct_Result,msdyn_agreementbookingproduct_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingservice_appointment: WebMappingRetrieve<msdyn_agreementbookingservice_Select,msdyn_agreementbookingservice_Expand,msdyn_agreementbookingservice_Filter,msdyn_agreementbookingservice_Fixed,msdyn_agreementbookingservice_Result,msdyn_agreementbookingservice_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingservicetask_appointment: WebMappingRetrieve<msdyn_agreementbookingservicetask_Select,msdyn_agreementbookingservicetask_Expand,msdyn_agreementbookingservicetask_Filter,msdyn_agreementbookingservicetask_Fixed,msdyn_agreementbookingservicetask_Result,msdyn_agreementbookingservicetask_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingsetup_appointment: WebMappingRetrieve<msdyn_agreementbookingsetup_Select,msdyn_agreementbookingsetup_Expand,msdyn_agreementbookingsetup_Filter,msdyn_agreementbookingsetup_Fixed,msdyn_agreementbookingsetup_Result,msdyn_agreementbookingsetup_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoicedate_appointment: WebMappingRetrieve<msdyn_agreementinvoicedate_Select,msdyn_agreementinvoicedate_Expand,msdyn_agreementinvoicedate_Filter,msdyn_agreementinvoicedate_Fixed,msdyn_agreementinvoicedate_Result,msdyn_agreementinvoicedate_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoiceproduct_appointment: WebMappingRetrieve<msdyn_agreementinvoiceproduct_Select,msdyn_agreementinvoiceproduct_Expand,msdyn_agreementinvoiceproduct_Filter,msdyn_agreementinvoiceproduct_Fixed,msdyn_agreementinvoiceproduct_Result,msdyn_agreementinvoiceproduct_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoicesetup_appointment: WebMappingRetrieve<msdyn_agreementinvoicesetup_Select,msdyn_agreementinvoicesetup_Expand,msdyn_agreementinvoicesetup_Filter,msdyn_agreementinvoicesetup_Fixed,msdyn_agreementinvoicesetup_Result,msdyn_agreementinvoicesetup_FormattedResult>;
  regardingobjectid_msdyn_bookingalertstatus_appointment: WebMappingRetrieve<msdyn_bookingalertstatus_Select,msdyn_bookingalertstatus_Expand,msdyn_bookingalertstatus_Filter,msdyn_bookingalertstatus_Fixed,msdyn_bookingalertstatus_Result,msdyn_bookingalertstatus_FormattedResult>;
  regardingobjectid_msdyn_bookingrule_appointment: WebMappingRetrieve<msdyn_bookingrule_Select,msdyn_bookingrule_Expand,msdyn_bookingrule_Filter,msdyn_bookingrule_Fixed,msdyn_bookingrule_Result,msdyn_bookingrule_FormattedResult>;
  regardingobjectid_msdyn_bookingtimestamp_appointment: WebMappingRetrieve<msdyn_bookingtimestamp_Select,msdyn_bookingtimestamp_Expand,msdyn_bookingtimestamp_Filter,msdyn_bookingtimestamp_Fixed,msdyn_bookingtimestamp_Result,msdyn_bookingtimestamp_FormattedResult>;
  regardingobjectid_msdyn_customerasset_appointment: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  regardingobjectid_msdyn_fieldservicesetting_appointment: WebMappingRetrieve<msdyn_fieldservicesetting_Select,msdyn_fieldservicesetting_Expand,msdyn_fieldservicesetting_Filter,msdyn_fieldservicesetting_Fixed,msdyn_fieldservicesetting_Result,msdyn_fieldservicesetting_FormattedResult>;
  regardingobjectid_msdyn_incidenttypecharacteristic_appointment: WebMappingRetrieve<msdyn_incidenttypecharacteristic_Select,msdyn_incidenttypecharacteristic_Expand,msdyn_incidenttypecharacteristic_Filter,msdyn_incidenttypecharacteristic_Fixed,msdyn_incidenttypecharacteristic_Result,msdyn_incidenttypecharacteristic_FormattedResult>;
  regardingobjectid_msdyn_incidenttypeproduct_appointment: WebMappingRetrieve<msdyn_incidenttypeproduct_Select,msdyn_incidenttypeproduct_Expand,msdyn_incidenttypeproduct_Filter,msdyn_incidenttypeproduct_Fixed,msdyn_incidenttypeproduct_Result,msdyn_incidenttypeproduct_FormattedResult>;
  regardingobjectid_msdyn_incidenttypeservice_appointment: WebMappingRetrieve<msdyn_incidenttypeservice_Select,msdyn_incidenttypeservice_Expand,msdyn_incidenttypeservice_Filter,msdyn_incidenttypeservice_Fixed,msdyn_incidenttypeservice_Result,msdyn_incidenttypeservice_FormattedResult>;
  regardingobjectid_msdyn_inventoryadjustment_appointment: WebMappingRetrieve<msdyn_inventoryadjustment_Select,msdyn_inventoryadjustment_Expand,msdyn_inventoryadjustment_Filter,msdyn_inventoryadjustment_Fixed,msdyn_inventoryadjustment_Result,msdyn_inventoryadjustment_FormattedResult>;
  regardingobjectid_msdyn_inventoryadjustmentproduct_appointment: WebMappingRetrieve<msdyn_inventoryadjustmentproduct_Select,msdyn_inventoryadjustmentproduct_Expand,msdyn_inventoryadjustmentproduct_Filter,msdyn_inventoryadjustmentproduct_Fixed,msdyn_inventoryadjustmentproduct_Result,msdyn_inventoryadjustmentproduct_FormattedResult>;
  regardingobjectid_msdyn_inventoryjournal_appointment: WebMappingRetrieve<msdyn_inventoryjournal_Select,msdyn_inventoryjournal_Expand,msdyn_inventoryjournal_Filter,msdyn_inventoryjournal_Fixed,msdyn_inventoryjournal_Result,msdyn_inventoryjournal_FormattedResult>;
  regardingobjectid_msdyn_inventorytransfer_appointment: WebMappingRetrieve<msdyn_inventorytransfer_Select,msdyn_inventorytransfer_Expand,msdyn_inventorytransfer_Filter,msdyn_inventorytransfer_Fixed,msdyn_inventorytransfer_Result,msdyn_inventorytransfer_FormattedResult>;
  regardingobjectid_msdyn_payment_appointment: WebMappingRetrieve<msdyn_payment_Select,msdyn_payment_Expand,msdyn_payment_Filter,msdyn_payment_Fixed,msdyn_payment_Result,msdyn_payment_FormattedResult>;
  regardingobjectid_msdyn_paymentdetail_appointment: WebMappingRetrieve<msdyn_paymentdetail_Select,msdyn_paymentdetail_Expand,msdyn_paymentdetail_Filter,msdyn_paymentdetail_Fixed,msdyn_paymentdetail_Result,msdyn_paymentdetail_FormattedResult>;
  regardingobjectid_msdyn_paymentmethod_appointment: WebMappingRetrieve<msdyn_paymentmethod_Select,msdyn_paymentmethod_Expand,msdyn_paymentmethod_Filter,msdyn_paymentmethod_Fixed,msdyn_paymentmethod_Result,msdyn_paymentmethod_FormattedResult>;
  regardingobjectid_msdyn_paymentterm_appointment: WebMappingRetrieve<msdyn_paymentterm_Select,msdyn_paymentterm_Expand,msdyn_paymentterm_Filter,msdyn_paymentterm_Fixed,msdyn_paymentterm_Result,msdyn_paymentterm_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_appointment: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_appointment: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_msdyn_postalcode_appointment: WebMappingRetrieve<msdyn_postalcode_Select,msdyn_postalcode_Expand,msdyn_postalcode_Filter,msdyn_postalcode_Fixed,msdyn_postalcode_Result,msdyn_postalcode_FormattedResult>;
  regardingobjectid_msdyn_processnotes_appointment: WebMappingRetrieve<msdyn_processnotes_Select,msdyn_processnotes_Expand,msdyn_processnotes_Filter,msdyn_processnotes_Fixed,msdyn_processnotes_Result,msdyn_processnotes_FormattedResult>;
  regardingobjectid_msdyn_productinventory_appointment: WebMappingRetrieve<msdyn_productinventory_Select,msdyn_productinventory_Expand,msdyn_productinventory_Filter,msdyn_productinventory_Fixed,msdyn_productinventory_Result,msdyn_productinventory_FormattedResult>;
  regardingobjectid_msdyn_projectteam_appointment: WebMappingRetrieve<msdyn_projectteam_Select,msdyn_projectteam_Expand,msdyn_projectteam_Filter,msdyn_projectteam_Fixed,msdyn_projectteam_Result,msdyn_projectteam_FormattedResult>;
  regardingobjectid_msdyn_purchaseorder_appointment: WebMappingRetrieve<msdyn_purchaseorder_Select,msdyn_purchaseorder_Expand,msdyn_purchaseorder_Filter,msdyn_purchaseorder_Fixed,msdyn_purchaseorder_Result,msdyn_purchaseorder_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderbill_appointment: WebMappingRetrieve<msdyn_purchaseorderbill_Select,msdyn_purchaseorderbill_Expand,msdyn_purchaseorderbill_Filter,msdyn_purchaseorderbill_Fixed,msdyn_purchaseorderbill_Result,msdyn_purchaseorderbill_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderproduct_appointment: WebMappingRetrieve<msdyn_purchaseorderproduct_Select,msdyn_purchaseorderproduct_Expand,msdyn_purchaseorderproduct_Filter,msdyn_purchaseorderproduct_Fixed,msdyn_purchaseorderproduct_Result,msdyn_purchaseorderproduct_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderreceipt_appointment: WebMappingRetrieve<msdyn_purchaseorderreceipt_Select,msdyn_purchaseorderreceipt_Expand,msdyn_purchaseorderreceipt_Filter,msdyn_purchaseorderreceipt_Fixed,msdyn_purchaseorderreceipt_Result,msdyn_purchaseorderreceipt_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_appointment: WebMappingRetrieve<msdyn_purchaseorderreceiptproduct_Select,msdyn_purchaseorderreceiptproduct_Expand,msdyn_purchaseorderreceiptproduct_Filter,msdyn_purchaseorderreceiptproduct_Fixed,msdyn_purchaseorderreceiptproduct_Result,msdyn_purchaseorderreceiptproduct_FormattedResult>;
  regardingobjectid_msdyn_purchaseordersubstatus_appointment: WebMappingRetrieve<msdyn_purchaseordersubstatus_Select,msdyn_purchaseordersubstatus_Expand,msdyn_purchaseordersubstatus_Filter,msdyn_purchaseordersubstatus_Fixed,msdyn_purchaseordersubstatus_Result,msdyn_purchaseordersubstatus_FormattedResult>;
  regardingobjectid_msdyn_quotebookingincident_appointment: WebMappingRetrieve<msdyn_quotebookingincident_Select,msdyn_quotebookingincident_Expand,msdyn_quotebookingincident_Filter,msdyn_quotebookingincident_Fixed,msdyn_quotebookingincident_Result,msdyn_quotebookingincident_FormattedResult>;
  regardingobjectid_msdyn_quotebookingproduct_appointment: WebMappingRetrieve<msdyn_quotebookingproduct_Select,msdyn_quotebookingproduct_Expand,msdyn_quotebookingproduct_Filter,msdyn_quotebookingproduct_Fixed,msdyn_quotebookingproduct_Result,msdyn_quotebookingproduct_FormattedResult>;
  regardingobjectid_msdyn_quotebookingservice_appointment: WebMappingRetrieve<msdyn_quotebookingservice_Select,msdyn_quotebookingservice_Expand,msdyn_quotebookingservice_Filter,msdyn_quotebookingservice_Fixed,msdyn_quotebookingservice_Result,msdyn_quotebookingservice_FormattedResult>;
  regardingobjectid_msdyn_quotebookingservicetask_appointment: WebMappingRetrieve<msdyn_quotebookingservicetask_Select,msdyn_quotebookingservicetask_Expand,msdyn_quotebookingservicetask_Filter,msdyn_quotebookingservicetask_Fixed,msdyn_quotebookingservicetask_Result,msdyn_quotebookingservicetask_FormattedResult>;
  regardingobjectid_msdyn_resourceterritory_appointment: WebMappingRetrieve<msdyn_resourceterritory_Select,msdyn_resourceterritory_Expand,msdyn_resourceterritory_Filter,msdyn_resourceterritory_Fixed,msdyn_resourceterritory_Result,msdyn_resourceterritory_FormattedResult>;
  regardingobjectid_msdyn_rma_appointment: WebMappingRetrieve<msdyn_rma_Select,msdyn_rma_Expand,msdyn_rma_Filter,msdyn_rma_Fixed,msdyn_rma_Result,msdyn_rma_FormattedResult>;
  regardingobjectid_msdyn_rmaproduct_appointment: WebMappingRetrieve<msdyn_rmaproduct_Select,msdyn_rmaproduct_Expand,msdyn_rmaproduct_Filter,msdyn_rmaproduct_Fixed,msdyn_rmaproduct_Result,msdyn_rmaproduct_FormattedResult>;
  regardingobjectid_msdyn_rmareceipt_appointment: WebMappingRetrieve<msdyn_rmareceipt_Select,msdyn_rmareceipt_Expand,msdyn_rmareceipt_Filter,msdyn_rmareceipt_Fixed,msdyn_rmareceipt_Result,msdyn_rmareceipt_FormattedResult>;
  regardingobjectid_msdyn_rmareceiptproduct_appointment: WebMappingRetrieve<msdyn_rmareceiptproduct_Select,msdyn_rmareceiptproduct_Expand,msdyn_rmareceiptproduct_Filter,msdyn_rmareceiptproduct_Fixed,msdyn_rmareceiptproduct_Result,msdyn_rmareceiptproduct_FormattedResult>;
  regardingobjectid_msdyn_rmasubstatus_appointment: WebMappingRetrieve<msdyn_rmasubstatus_Select,msdyn_rmasubstatus_Expand,msdyn_rmasubstatus_Filter,msdyn_rmasubstatus_Fixed,msdyn_rmasubstatus_Result,msdyn_rmasubstatus_FormattedResult>;
  regardingobjectid_msdyn_rtv_appointment: WebMappingRetrieve<msdyn_rtv_Select,msdyn_rtv_Expand,msdyn_rtv_Filter,msdyn_rtv_Fixed,msdyn_rtv_Result,msdyn_rtv_FormattedResult>;
  regardingobjectid_msdyn_rtvproduct_appointment: WebMappingRetrieve<msdyn_rtvproduct_Select,msdyn_rtvproduct_Expand,msdyn_rtvproduct_Filter,msdyn_rtvproduct_Fixed,msdyn_rtvproduct_Result,msdyn_rtvproduct_FormattedResult>;
  regardingobjectid_msdyn_rtvsubstatus_appointment: WebMappingRetrieve<msdyn_rtvsubstatus_Select,msdyn_rtvsubstatus_Expand,msdyn_rtvsubstatus_Filter,msdyn_rtvsubstatus_Fixed,msdyn_rtvsubstatus_Result,msdyn_rtvsubstatus_FormattedResult>;
  regardingobjectid_msdyn_shipvia_appointment: WebMappingRetrieve<msdyn_shipvia_Select,msdyn_shipvia_Expand,msdyn_shipvia_Filter,msdyn_shipvia_Fixed,msdyn_shipvia_Result,msdyn_shipvia_FormattedResult>;
  regardingobjectid_msdyn_systemuserschedulersetting_appointment: WebMappingRetrieve<msdyn_systemuserschedulersetting_Select,msdyn_systemuserschedulersetting_Expand,msdyn_systemuserschedulersetting_Filter,msdyn_systemuserschedulersetting_Fixed,msdyn_systemuserschedulersetting_Result,msdyn_systemuserschedulersetting_FormattedResult>;
  regardingobjectid_msdyn_timegroup_appointment: WebMappingRetrieve<msdyn_timegroup_Select,msdyn_timegroup_Expand,msdyn_timegroup_Filter,msdyn_timegroup_Fixed,msdyn_timegroup_Result,msdyn_timegroup_FormattedResult>;
  regardingobjectid_msdyn_timegroupdetail_appointment: WebMappingRetrieve<msdyn_timegroupdetail_Select,msdyn_timegroupdetail_Expand,msdyn_timegroupdetail_Filter,msdyn_timegroupdetail_Fixed,msdyn_timegroupdetail_Result,msdyn_timegroupdetail_FormattedResult>;
  regardingobjectid_msdyn_timeoffrequest_appointment: WebMappingRetrieve<msdyn_timeoffrequest_Select,msdyn_timeoffrequest_Expand,msdyn_timeoffrequest_Filter,msdyn_timeoffrequest_Fixed,msdyn_timeoffrequest_Result,msdyn_timeoffrequest_FormattedResult>;
  regardingobjectid_msdyn_warehouse_appointment: WebMappingRetrieve<msdyn_warehouse_Select,msdyn_warehouse_Expand,msdyn_warehouse_Filter,msdyn_warehouse_Fixed,msdyn_warehouse_Result,msdyn_warehouse_FormattedResult>;
  regardingobjectid_msdyn_workorder_appointment: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  regardingobjectid_msdyn_workordercharacteristic_appointment: WebMappingRetrieve<msdyn_workordercharacteristic_Select,msdyn_workordercharacteristic_Expand,msdyn_workordercharacteristic_Filter,msdyn_workordercharacteristic_Fixed,msdyn_workordercharacteristic_Result,msdyn_workordercharacteristic_FormattedResult>;
  regardingobjectid_msdyn_workorderincident_appointment: WebMappingRetrieve<msdyn_workorderincident_Select,msdyn_workorderincident_Expand,msdyn_workorderincident_Filter,msdyn_workorderincident_Fixed,msdyn_workorderincident_Result,msdyn_workorderincident_FormattedResult>;
  regardingobjectid_msdyn_workorderproduct_appointment: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  regardingobjectid_msdyn_workorderresourcerestriction_appointment: WebMappingRetrieve<msdyn_workorderresourcerestriction_Select,msdyn_workorderresourcerestriction_Expand,msdyn_workorderresourcerestriction_Filter,msdyn_workorderresourcerestriction_Fixed,msdyn_workorderresourcerestriction_Result,msdyn_workorderresourcerestriction_FormattedResult>;
  regardingobjectid_msdyn_workorderservice_appointment: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  regardingobjectid_msdyn_workorderservicetask_appointment: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  regardingobjectid_opportunity_appointment: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_appointment: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_appointment: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_appointment: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  regardingobjectid_uii_action_appointment: WebMappingRetrieve<UII_action_Select,UII_action_Expand,UII_action_Filter,UII_action_Fixed,UII_action_Result,UII_action_FormattedResult>;
  regardingobjectid_uii_hostedapplication_appointment: WebMappingRetrieve<UII_hostedapplication_Select,UII_hostedapplication_Expand,UII_hostedapplication_Filter,UII_hostedapplication_Fixed,UII_hostedapplication_Result,UII_hostedapplication_FormattedResult>;
  regardingobjectid_uii_nonhostedapplication_appointment: WebMappingRetrieve<UII_nonhostedapplication_Select,UII_nonhostedapplication_Expand,UII_nonhostedapplication_Filter,UII_nonhostedapplication_Fixed,UII_nonhostedapplication_Result,UII_nonhostedapplication_FormattedResult>;
  regardingobjectid_uii_option_appointment: WebMappingRetrieve<uii_option_Select,uii_option_Expand,uii_option_Filter,uii_option_Fixed,uii_option_Result,uii_option_FormattedResult>;
  regardingobjectid_uii_savedsession_appointment: WebMappingRetrieve<UII_savedsession_Select,UII_savedsession_Expand,UII_savedsession_Filter,UII_savedsession_Fixed,UII_savedsession_Result,UII_savedsession_FormattedResult>;
  regardingobjectid_uii_workflow_appointment: WebMappingRetrieve<UII_workflow_Select,UII_workflow_Expand,UII_workflow_Filter,UII_workflow_Fixed,UII_workflow_Result,UII_workflow_FormattedResult>;
  regardingobjectid_uii_workflow_workflowstep_mapping_appointment: WebMappingRetrieve<UII_workflow_workflowstep_mapping_Select,UII_workflow_workflowstep_mapping_Expand,UII_workflow_workflowstep_mapping_Filter,UII_workflow_workflowstep_mapping_Fixed,UII_workflow_workflowstep_mapping_Result,UII_workflow_workflowstep_mapping_FormattedResult>;
  regardingobjectid_uii_workflowstep_appointment: WebMappingRetrieve<UII_workflowstep_Select,UII_workflowstep_Expand,UII_workflowstep_Filter,UII_workflowstep_Fixed,UII_workflowstep_Result,UII_workflowstep_FormattedResult>;
  seriesid_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  serviceid_appointment: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_appointment_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_appointment_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_appointment: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Appointment_RelatedMany {
  Appointment_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Appointment_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Appointment_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Appointment_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Appointment_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Appointment_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Appointment_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  Appointment_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  appointment_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  appointment_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  appointment_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  appointment_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  appointment_activity_mime_attachment: WebMappingRetrieve<ActivityMimeAttachment_Select,ActivityMimeAttachment_Expand,ActivityMimeAttachment_Filter,ActivityMimeAttachment_Fixed,ActivityMimeAttachment_Result,ActivityMimeAttachment_FormattedResult>;
  appointment_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  appointment_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  appointment_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  appointment_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  appointment_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_appointment_bookableresourcebooking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  msdyn_appointment_msdyn_resourcerequirement: WebMappingRetrieve<msdyn_resourcerequirement_Select,msdyn_resourcerequirement_Expand,msdyn_resourcerequirement_Filter,msdyn_resourcerequirement_Fixed,msdyn_resourcerequirement_Result,msdyn_resourcerequirement_FormattedResult>;
  slakpiinstance_appointment: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_appointment: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
}
interface WebEntitiesRelated {
  appointments: WebMappingRelated<Appointment_RelatedOne,Appointment_RelatedMany>;
}
interface WebEntitiesCUDA {
  appointments: WebMappingCUDA<Appointment_Create,Appointment_Update,Appointment_Select>;
}
