interface BookableResourceBooking_Base extends WebEntity {
  bookableresourcebookingid?: string | null;
  bookingtype?: bookableresourcebooking_bookingtype | null;
  createdon?: Date | null;
  duration?: number | null;
  endtime?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_acceptcascadecrewchanges?: boolean | null;
  msdyn_actualarrivaltime?: Date | null;
  msdyn_actualtravelduration?: number | null;
  msdyn_allowoverlapping?: boolean | null;
  msdyn_basetravelduration?: number | null;
  msdyn_bookingmethod?: msdyn_resourceschedulesource | null;
  msdyn_cascadecrewchanges?: boolean | null;
  msdyn_crewmembertype?: msdyn_crewmembertype | null;
  msdyn_effort?: number | null;
  msdyn_estimatedarrivaltime?: Date | null;
  msdyn_estimatedtravelduration?: number | null;
  msdyn_internalflags?: string | null;
  msdyn_latitude?: number | null;
  msdyn_longitude?: number | null;
  msdyn_milestraveled?: number | null;
  msdyn_offlinetimestamp?: Date | null;
  msdyn_preventtimestampcreation?: boolean | null;
  msdyn_quickNoteAction?: msdyn_quicknote_type | null;
  msdyn_requirementgroupset?: string | null;
  msdyn_signature?: string | null;
  msdyn_slottext?: string | null;
  msdyn_totalbillableduration?: number | null;
  msdyn_totalbreakduration?: number | null;
  msdyn_totalcost?: number | null;
  msdyn_totalcost_base?: number | null;
  msdyn_totaldurationinprogress?: number | null;
  msdyn_traveltimecalculationtype?: msdyn_traveltimetype | null;
  msdyn_traveltimerescheduling?: boolean | null;
  msdyn_ursinternalflags?: string | null;
  msdyn_worklocation?: msdyn_worklocation | null;
  name?: string | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  stageid?: string | null;
  starttime?: Date | null;
  statecode?: bookableresourcebooking_statecode | null;
  statuscode?: bookableresourcebooking_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface BookableResourceBooking_Relationships {
  BookableResourceBooking_SyncErrors?: SyncError_Result[] | null;
  BookingStatus?: BookingStatus_Result | null;
  Header?: BookableResourceBookingHeader_Result | null;
  Resource?: BookableResource_Result | null;
  bookableresourcebooking_ActivityPointers?: ActivityPointer_Result[] | null;
  bookableresourcebooking_Annotations?: Annotation_Result[] | null;
  bookableresourcebooking_Appointments?: Appointment_Result[] | null;
  bookableresourcebooking_AsyncOperations?: AsyncOperation_Result[] | null;
  bookableresourcebooking_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  bookableresourcebooking_BulkOperations?: BulkOperation_Result[] | null;
  bookableresourcebooking_CampaignActivities?: CampaignActivity_Result[] | null;
  bookableresourcebooking_CampaignResponses?: CampaignResponse_Result[] | null;
  bookableresourcebooking_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  bookableresourcebooking_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  bookableresourcebooking_Emails?: Email_Result[] | null;
  bookableresourcebooking_Faxes?: Fax_Result[] | null;
  bookableresourcebooking_IncidentResolutions?: IncidentResolution_Result[] | null;
  bookableresourcebooking_Letters?: Letter_Result[] | null;
  bookableresourcebooking_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  bookableresourcebooking_OpportunityCloses?: OpportunityClose_Result[] | null;
  bookableresourcebooking_OrderCloses?: OrderClose_Result[] | null;
  bookableresourcebooking_PhoneCalls?: PhoneCall_Result[] | null;
  bookableresourcebooking_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  bookableresourcebooking_ProcessSession?: ProcessSession_Result[] | null;
  bookableresourcebooking_QuoteCloses?: QuoteClose_Result[] | null;
  bookableresourcebooking_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  bookableresourcebooking_ServiceAppointments?: ServiceAppointment_Result[] | null;
  bookableresourcebooking_SocialActivities?: SocialActivity_Result[] | null;
  bookableresourcebooking_Tasks?: Task_Result[] | null;
  bookableresourcebooking_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  bookableresourcebooking_msdyn_approvals?: msdyn_approval_Result[] | null;
  bookableresourcebooking_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  bookableresourcebooking_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  bookableresourcebooking_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  bookableresourcebooking_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  bookableresourcebooking_msfp_alerts?: msfp_alert_Result[] | null;
  bookableresourcebooking_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  bookableresourcebooking_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  createdbyname?: SystemUser_Result | null;
  createdonbehalfbyname?: SystemUser_Result | null;
  modifiedbyname?: SystemUser_Result | null;
  modifiedonbehalfbyname?: SystemUser_Result | null;
  msdyn_AppointmentBookingId?: Appointment_Result | null;
  msdyn_BookingSetupMetadataId?: msdyn_bookingsetupmetadata_Result | null;
  msdyn_Crew?: BookableResource_Result | null;
  msdyn_ResourceRequirement?: msdyn_resourcerequirement_Result | null;
  msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking?: msdyn_bookingjournal_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking?: msdyn_bookingtimestamp_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_geofence_bookableresourcebookingid?: msdyn_geofence_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking?: msdyn_purchaseorder_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking?: msdyn_purchaseorderproduct_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBooking?: msdyn_purchaseorderreceiptproduct_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_rtv_Booking?: msdyn_rtv_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_timeentry_BookableResourceBooking?: msdyn_timeentry_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking?: msdyn_workorderproduct_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_workorderservice_Booking?: msdyn_workorderservice_Result[] | null;
  msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking?: msdyn_workorderservicetask_Result[] | null;
  msdyn_bookableresourcebookingquicknote_bookableresourcebooking?: msdyn_bookableresourcebookingquicknote_Result[] | null;
}
interface BookableResourceBooking extends BookableResourceBooking_Base, BookableResourceBooking_Relationships {
  BookingStatus_bind$bookingstatuses?: string | null;
  Header_bind$bookableresourcebookingheaders?: string | null;
  Resource_bind$bookableresources?: string | null;
  msdyn_AppointmentBookingId_bind$appointments?: string | null;
  msdyn_BookingSetupMetadataId_bind$msdyn_bookingsetupmetadatas?: string | null;
  msdyn_Crew_bind$bookableresources?: string | null;
  msdyn_ResourceRequirement_bind$msdyn_resourcerequirements?: string | null;
  msdyn_agreementbookingdate_bind$msdyn_agreementbookingdates?: string | null;
  msdyn_projectid_bind$msdyn_projects?: string | null;
  msdyn_projectteamid_bind$msdyn_projectteams?: string | null;
  msdyn_requirementgroupid_bind$msdyn_requirementgroups?: string | null;
  msdyn_resourcecategoryid_bind$bookableresourcecategories?: string | null;
  msdyn_resourcegroup_bind$bookableresources?: string | null;
  msdyn_serviceappointment_bind$serviceappointments?: string | null;
  msdyn_timegroupdetailselected_bind$msdyn_timegroupdetails?: string | null;
  msdyn_workorder_bind$msdyn_workorders?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  stageid_bind$processstages?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface BookableResourceBooking_Create extends BookableResourceBooking {
}
interface BookableResourceBooking_Update extends BookableResourceBooking {
}
interface BookableResourceBooking_Select {
  bookableresourcebookingid: WebAttribute<BookableResourceBooking_Select, { bookableresourcebookingid: string | null }, {  }>;
  bookingstatus_guid: WebAttribute<BookableResourceBooking_Select, { bookingstatus_guid: string | null }, { bookingstatus_formatted?: string }>;
  bookingtype: WebAttribute<BookableResourceBooking_Select, { bookingtype: bookableresourcebooking_bookingtype | null }, { bookingtype_formatted?: string }>;
  createdby_guid: WebAttribute<BookableResourceBooking_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<BookableResourceBooking_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<BookableResourceBooking_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  duration: WebAttribute<BookableResourceBooking_Select, { duration: number | null }, {  }>;
  endtime: WebAttribute<BookableResourceBooking_Select, { endtime: Date | null }, { endtime_formatted?: string }>;
  exchangerate: WebAttribute<BookableResourceBooking_Select, { exchangerate: number | null }, {  }>;
  header_guid: WebAttribute<BookableResourceBooking_Select, { header_guid: string | null }, { header_formatted?: string }>;
  importsequencenumber: WebAttribute<BookableResourceBooking_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<BookableResourceBooking_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<BookableResourceBooking_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<BookableResourceBooking_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_acceptcascadecrewchanges: WebAttribute<BookableResourceBooking_Select, { msdyn_acceptcascadecrewchanges: boolean | null }, {  }>;
  msdyn_actualarrivaltime: WebAttribute<BookableResourceBooking_Select, { msdyn_actualarrivaltime: Date | null }, { msdyn_actualarrivaltime_formatted?: string }>;
  msdyn_actualtravelduration: WebAttribute<BookableResourceBooking_Select, { msdyn_actualtravelduration: number | null }, {  }>;
  msdyn_agreementbookingdate_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_agreementbookingdate_guid: string | null }, { msdyn_agreementbookingdate_formatted?: string }>;
  msdyn_allowoverlapping: WebAttribute<BookableResourceBooking_Select, { msdyn_allowoverlapping: boolean | null }, {  }>;
  msdyn_appointmentbookingid_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_appointmentbookingid_guid: string | null }, { msdyn_appointmentbookingid_formatted?: string }>;
  msdyn_basetravelduration: WebAttribute<BookableResourceBooking_Select, { msdyn_basetravelduration: number | null }, {  }>;
  msdyn_bookingmethod: WebAttribute<BookableResourceBooking_Select, { msdyn_bookingmethod: msdyn_resourceschedulesource | null }, { msdyn_bookingmethod_formatted?: string }>;
  msdyn_bookingsetupmetadataid_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_bookingsetupmetadataid_guid: string | null }, { msdyn_bookingsetupmetadataid_formatted?: string }>;
  msdyn_cascadecrewchanges: WebAttribute<BookableResourceBooking_Select, { msdyn_cascadecrewchanges: boolean | null }, {  }>;
  msdyn_crew_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_crew_guid: string | null }, { msdyn_crew_formatted?: string }>;
  msdyn_crewmembertype: WebAttribute<BookableResourceBooking_Select, { msdyn_crewmembertype: msdyn_crewmembertype | null }, { msdyn_crewmembertype_formatted?: string }>;
  msdyn_effort: WebAttribute<BookableResourceBooking_Select, { msdyn_effort: number | null }, {  }>;
  msdyn_estimatedarrivaltime: WebAttribute<BookableResourceBooking_Select, { msdyn_estimatedarrivaltime: Date | null }, { msdyn_estimatedarrivaltime_formatted?: string }>;
  msdyn_estimatedtravelduration: WebAttribute<BookableResourceBooking_Select, { msdyn_estimatedtravelduration: number | null }, {  }>;
  msdyn_internalflags: WebAttribute<BookableResourceBooking_Select, { msdyn_internalflags: string | null }, {  }>;
  msdyn_latitude: WebAttribute<BookableResourceBooking_Select, { msdyn_latitude: number | null }, {  }>;
  msdyn_longitude: WebAttribute<BookableResourceBooking_Select, { msdyn_longitude: number | null }, {  }>;
  msdyn_milestraveled: WebAttribute<BookableResourceBooking_Select, { msdyn_milestraveled: number | null }, {  }>;
  msdyn_offlinetimestamp: WebAttribute<BookableResourceBooking_Select, { msdyn_offlinetimestamp: Date | null }, { msdyn_offlinetimestamp_formatted?: string }>;
  msdyn_preventtimestampcreation: WebAttribute<BookableResourceBooking_Select, { msdyn_preventtimestampcreation: boolean | null }, {  }>;
  msdyn_projectid_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_projectid_guid: string | null }, { msdyn_projectid_formatted?: string }>;
  msdyn_projectteamid_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_projectteamid_guid: string | null }, { msdyn_projectteamid_formatted?: string }>;
  msdyn_quickNoteAction: WebAttribute<BookableResourceBooking_Select, { msdyn_quickNoteAction: msdyn_quicknote_type | null }, { msdyn_quickNoteAction_formatted?: string }>;
  msdyn_requirementgroupid_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_requirementgroupid_guid: string | null }, { msdyn_requirementgroupid_formatted?: string }>;
  msdyn_requirementgroupset: WebAttribute<BookableResourceBooking_Select, { msdyn_requirementgroupset: string | null }, {  }>;
  msdyn_resourcecategoryid_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_resourcecategoryid_guid: string | null }, { msdyn_resourcecategoryid_formatted?: string }>;
  msdyn_resourcegroup_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_resourcegroup_guid: string | null }, { msdyn_resourcegroup_formatted?: string }>;
  msdyn_resourcerequirement_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_resourcerequirement_guid: string | null }, { msdyn_resourcerequirement_formatted?: string }>;
  msdyn_serviceappointment_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_serviceappointment_guid: string | null }, { msdyn_serviceappointment_formatted?: string }>;
  msdyn_signature: WebAttribute<BookableResourceBooking_Select, { msdyn_signature: string | null }, {  }>;
  msdyn_slottext: WebAttribute<BookableResourceBooking_Select, { msdyn_slottext: string | null }, {  }>;
  msdyn_timegroupdetailselected_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_timegroupdetailselected_guid: string | null }, { msdyn_timegroupdetailselected_formatted?: string }>;
  msdyn_totalbillableduration: WebAttribute<BookableResourceBooking_Select, { msdyn_totalbillableduration: number | null }, {  }>;
  msdyn_totalbreakduration: WebAttribute<BookableResourceBooking_Select, { msdyn_totalbreakduration: number | null }, {  }>;
  msdyn_totalcost: WebAttribute<BookableResourceBooking_Select, { msdyn_totalcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalcost_base: WebAttribute<BookableResourceBooking_Select, { msdyn_totalcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totaldurationinprogress: WebAttribute<BookableResourceBooking_Select, { msdyn_totaldurationinprogress: number | null }, {  }>;
  msdyn_traveltimecalculationtype: WebAttribute<BookableResourceBooking_Select, { msdyn_traveltimecalculationtype: msdyn_traveltimetype | null }, { msdyn_traveltimecalculationtype_formatted?: string }>;
  msdyn_traveltimerescheduling: WebAttribute<BookableResourceBooking_Select, { msdyn_traveltimerescheduling: boolean | null }, {  }>;
  msdyn_ursinternalflags: WebAttribute<BookableResourceBooking_Select, { msdyn_ursinternalflags: string | null }, {  }>;
  msdyn_worklocation: WebAttribute<BookableResourceBooking_Select, { msdyn_worklocation: msdyn_worklocation | null }, { msdyn_worklocation_formatted?: string }>;
  msdyn_workorder_guid: WebAttribute<BookableResourceBooking_Select, { msdyn_workorder_guid: string | null }, { msdyn_workorder_formatted?: string }>;
  name: WebAttribute<BookableResourceBooking_Select, { name: string | null }, {  }>;
  overriddencreatedon: WebAttribute<BookableResourceBooking_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<BookableResourceBooking_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<BookableResourceBooking_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<BookableResourceBooking_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<BookableResourceBooking_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  processid: WebAttribute<BookableResourceBooking_Select, { processid: string | null }, {  }>;
  resource_guid: WebAttribute<BookableResourceBooking_Select, { resource_guid: string | null }, { resource_formatted?: string }>;
  stageid: WebAttribute<BookableResourceBooking_Select, { stageid: string | null }, {  }>;
  starttime: WebAttribute<BookableResourceBooking_Select, { starttime: Date | null }, { starttime_formatted?: string }>;
  statecode: WebAttribute<BookableResourceBooking_Select, { statecode: bookableresourcebooking_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<BookableResourceBooking_Select, { statuscode: bookableresourcebooking_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<BookableResourceBooking_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<BookableResourceBooking_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<BookableResourceBooking_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<BookableResourceBooking_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<BookableResourceBooking_Select, { versionnumber: number | null }, {  }>;
}
interface BookableResourceBooking_Filter {
  bookableresourcebookingid: XQW.Guid;
  bookingstatus_guid: XQW.Guid;
  bookingtype: bookableresourcebooking_bookingtype;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  duration: number;
  endtime: Date;
  exchangerate: any;
  header_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_acceptcascadecrewchanges: boolean;
  msdyn_actualarrivaltime: Date;
  msdyn_actualtravelduration: number;
  msdyn_agreementbookingdate_guid: XQW.Guid;
  msdyn_allowoverlapping: boolean;
  msdyn_appointmentbookingid_guid: XQW.Guid;
  msdyn_basetravelduration: number;
  msdyn_bookingmethod: msdyn_resourceschedulesource;
  msdyn_bookingsetupmetadataid_guid: XQW.Guid;
  msdyn_cascadecrewchanges: boolean;
  msdyn_crew_guid: XQW.Guid;
  msdyn_crewmembertype: msdyn_crewmembertype;
  msdyn_effort: any;
  msdyn_estimatedarrivaltime: Date;
  msdyn_estimatedtravelduration: number;
  msdyn_internalflags: string;
  msdyn_latitude: number;
  msdyn_longitude: number;
  msdyn_milestraveled: number;
  msdyn_offlinetimestamp: Date;
  msdyn_preventtimestampcreation: boolean;
  msdyn_projectid_guid: XQW.Guid;
  msdyn_projectteamid_guid: XQW.Guid;
  msdyn_quickNoteAction: msdyn_quicknote_type;
  msdyn_requirementgroupid_guid: XQW.Guid;
  msdyn_requirementgroupset: string;
  msdyn_resourcecategoryid_guid: XQW.Guid;
  msdyn_resourcegroup_guid: XQW.Guid;
  msdyn_resourcerequirement_guid: XQW.Guid;
  msdyn_serviceappointment_guid: XQW.Guid;
  msdyn_signature: string;
  msdyn_slottext: string;
  msdyn_timegroupdetailselected_guid: XQW.Guid;
  msdyn_totalbillableduration: number;
  msdyn_totalbreakduration: number;
  msdyn_totalcost: number;
  msdyn_totalcost_base: number;
  msdyn_totaldurationinprogress: number;
  msdyn_traveltimecalculationtype: msdyn_traveltimetype;
  msdyn_traveltimerescheduling: boolean;
  msdyn_ursinternalflags: string;
  msdyn_worklocation: msdyn_worklocation;
  msdyn_workorder_guid: XQW.Guid;
  name: string;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  processid: XQW.Guid;
  resource_guid: XQW.Guid;
  stageid: XQW.Guid;
  starttime: Date;
  statecode: bookableresourcebooking_statecode;
  statuscode: bookableresourcebooking_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface BookableResourceBooking_Expand {
  BookableResourceBooking_SyncErrors: WebExpand<BookableResourceBooking_Expand, SyncError_Select, SyncError_Filter, { BookableResourceBooking_SyncErrors: SyncError_Result[] }>;
  BookingStatus: WebExpand<BookableResourceBooking_Expand, BookingStatus_Select, BookingStatus_Filter, { BookingStatus: BookingStatus_Result }>;
  Header: WebExpand<BookableResourceBooking_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { Header: BookableResourceBookingHeader_Result }>;
  Resource: WebExpand<BookableResourceBooking_Expand, BookableResource_Select, BookableResource_Filter, { Resource: BookableResource_Result }>;
  bookableresourcebooking_ActivityPointers: WebExpand<BookableResourceBooking_Expand, ActivityPointer_Select, ActivityPointer_Filter, { bookableresourcebooking_ActivityPointers: ActivityPointer_Result[] }>;
  bookableresourcebooking_Annotations: WebExpand<BookableResourceBooking_Expand, Annotation_Select, Annotation_Filter, { bookableresourcebooking_Annotations: Annotation_Result[] }>;
  bookableresourcebooking_Appointments: WebExpand<BookableResourceBooking_Expand, Appointment_Select, Appointment_Filter, { bookableresourcebooking_Appointments: Appointment_Result[] }>;
  bookableresourcebooking_AsyncOperations: WebExpand<BookableResourceBooking_Expand, AsyncOperation_Select, AsyncOperation_Filter, { bookableresourcebooking_AsyncOperations: AsyncOperation_Result[] }>;
  bookableresourcebooking_BulkDeleteFailures: WebExpand<BookableResourceBooking_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { bookableresourcebooking_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  bookableresourcebooking_BulkOperations: WebExpand<BookableResourceBooking_Expand, BulkOperation_Select, BulkOperation_Filter, { bookableresourcebooking_BulkOperations: BulkOperation_Result[] }>;
  bookableresourcebooking_CampaignActivities: WebExpand<BookableResourceBooking_Expand, CampaignActivity_Select, CampaignActivity_Filter, { bookableresourcebooking_CampaignActivities: CampaignActivity_Result[] }>;
  bookableresourcebooking_CampaignResponses: WebExpand<BookableResourceBooking_Expand, CampaignResponse_Select, CampaignResponse_Filter, { bookableresourcebooking_CampaignResponses: CampaignResponse_Result[] }>;
  bookableresourcebooking_DuplicateBaseRecord: WebExpand<BookableResourceBooking_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { bookableresourcebooking_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  bookableresourcebooking_DuplicateMatchingRecord: WebExpand<BookableResourceBooking_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { bookableresourcebooking_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  bookableresourcebooking_Emails: WebExpand<BookableResourceBooking_Expand, Email_Select, Email_Filter, { bookableresourcebooking_Emails: Email_Result[] }>;
  bookableresourcebooking_Faxes: WebExpand<BookableResourceBooking_Expand, Fax_Select, Fax_Filter, { bookableresourcebooking_Faxes: Fax_Result[] }>;
  bookableresourcebooking_IncidentResolutions: WebExpand<BookableResourceBooking_Expand, IncidentResolution_Select, IncidentResolution_Filter, { bookableresourcebooking_IncidentResolutions: IncidentResolution_Result[] }>;
  bookableresourcebooking_Letters: WebExpand<BookableResourceBooking_Expand, Letter_Select, Letter_Filter, { bookableresourcebooking_Letters: Letter_Result[] }>;
  bookableresourcebooking_MailboxTrackingFolders: WebExpand<BookableResourceBooking_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { bookableresourcebooking_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  bookableresourcebooking_OpportunityCloses: WebExpand<BookableResourceBooking_Expand, OpportunityClose_Select, OpportunityClose_Filter, { bookableresourcebooking_OpportunityCloses: OpportunityClose_Result[] }>;
  bookableresourcebooking_OrderCloses: WebExpand<BookableResourceBooking_Expand, OrderClose_Select, OrderClose_Filter, { bookableresourcebooking_OrderCloses: OrderClose_Result[] }>;
  bookableresourcebooking_PhoneCalls: WebExpand<BookableResourceBooking_Expand, PhoneCall_Select, PhoneCall_Filter, { bookableresourcebooking_PhoneCalls: PhoneCall_Result[] }>;
  bookableresourcebooking_PrincipalObjectAttributeAccesses: WebExpand<BookableResourceBooking_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { bookableresourcebooking_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  bookableresourcebooking_ProcessSession: WebExpand<BookableResourceBooking_Expand, ProcessSession_Select, ProcessSession_Filter, { bookableresourcebooking_ProcessSession: ProcessSession_Result[] }>;
  bookableresourcebooking_QuoteCloses: WebExpand<BookableResourceBooking_Expand, QuoteClose_Select, QuoteClose_Filter, { bookableresourcebooking_QuoteCloses: QuoteClose_Result[] }>;
  bookableresourcebooking_RecurringAppointmentMasters: WebExpand<BookableResourceBooking_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { bookableresourcebooking_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  bookableresourcebooking_ServiceAppointments: WebExpand<BookableResourceBooking_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { bookableresourcebooking_ServiceAppointments: ServiceAppointment_Result[] }>;
  bookableresourcebooking_SocialActivities: WebExpand<BookableResourceBooking_Expand, SocialActivity_Select, SocialActivity_Filter, { bookableresourcebooking_SocialActivities: SocialActivity_Result[] }>;
  bookableresourcebooking_Tasks: WebExpand<BookableResourceBooking_Expand, Task_Select, Task_Filter, { bookableresourcebooking_Tasks: Task_Result[] }>;
  bookableresourcebooking_UserEntityInstanceDatas: WebExpand<BookableResourceBooking_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { bookableresourcebooking_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  bookableresourcebooking_msdyn_approvals: WebExpand<BookableResourceBooking_Expand, msdyn_approval_Select, msdyn_approval_Filter, { bookableresourcebooking_msdyn_approvals: msdyn_approval_Result[] }>;
  bookableresourcebooking_msdyn_bookingalerts: WebExpand<BookableResourceBooking_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { bookableresourcebooking_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  bookableresourcebooking_msdyn_ocliveworkitems: WebExpand<BookableResourceBooking_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { bookableresourcebooking_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  bookableresourcebooking_msdyn_ocoutboundmessages: WebExpand<BookableResourceBooking_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { bookableresourcebooking_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  bookableresourcebooking_msdyn_ocsessions: WebExpand<BookableResourceBooking_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { bookableresourcebooking_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  bookableresourcebooking_msfp_alerts: WebExpand<BookableResourceBooking_Expand, msfp_alert_Select, msfp_alert_Filter, { bookableresourcebooking_msfp_alerts: msfp_alert_Result[] }>;
  bookableresourcebooking_msfp_surveyinvites: WebExpand<BookableResourceBooking_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { bookableresourcebooking_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  bookableresourcebooking_msfp_surveyresponses: WebExpand<BookableResourceBooking_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { bookableresourcebooking_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  createdbyname: WebExpand<BookableResourceBooking_Expand, SystemUser_Select, SystemUser_Filter, { createdbyname: SystemUser_Result }>;
  createdonbehalfbyname: WebExpand<BookableResourceBooking_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfbyname: SystemUser_Result }>;
  modifiedbyname: WebExpand<BookableResourceBooking_Expand, SystemUser_Select, SystemUser_Filter, { modifiedbyname: SystemUser_Result }>;
  modifiedonbehalfbyname: WebExpand<BookableResourceBooking_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfbyname: SystemUser_Result }>;
  msdyn_AppointmentBookingId: WebExpand<BookableResourceBooking_Expand, Appointment_Select, Appointment_Filter, { msdyn_AppointmentBookingId: Appointment_Result }>;
  msdyn_BookingSetupMetadataId: WebExpand<BookableResourceBooking_Expand, msdyn_bookingsetupmetadata_Select, msdyn_bookingsetupmetadata_Filter, { msdyn_BookingSetupMetadataId: msdyn_bookingsetupmetadata_Result }>;
  msdyn_Crew: WebExpand<BookableResourceBooking_Expand, BookableResource_Select, BookableResource_Filter, { msdyn_Crew: BookableResource_Result }>;
  msdyn_ResourceRequirement: WebExpand<BookableResourceBooking_Expand, msdyn_resourcerequirement_Select, msdyn_resourcerequirement_Filter, { msdyn_ResourceRequirement: msdyn_resourcerequirement_Result }>;
  msdyn_agreementbookingdate: WebExpand<BookableResourceBooking_Expand, msdyn_agreementbookingdate_Select, msdyn_agreementbookingdate_Filter, { msdyn_agreementbookingdate: msdyn_agreementbookingdate_Result }>;
  msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking: WebExpand<BookableResourceBooking_Expand, msdyn_bookingjournal_Select, msdyn_bookingjournal_Filter, { msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking: msdyn_bookingjournal_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking: WebExpand<BookableResourceBooking_Expand, msdyn_bookingtimestamp_Select, msdyn_bookingtimestamp_Filter, { msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking: msdyn_bookingtimestamp_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_geofence_bookableresourcebookingid: WebExpand<BookableResourceBooking_Expand, msdyn_geofence_Select, msdyn_geofence_Filter, { msdyn_bookableresourcebooking_msdyn_geofence_bookableresourcebookingid: msdyn_geofence_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking: WebExpand<BookableResourceBooking_Expand, msdyn_purchaseorder_Select, msdyn_purchaseorder_Filter, { msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking: msdyn_purchaseorder_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking: WebExpand<BookableResourceBooking_Expand, msdyn_purchaseorderproduct_Select, msdyn_purchaseorderproduct_Filter, { msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking: msdyn_purchaseorderproduct_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBooking: WebExpand<BookableResourceBooking_Expand, msdyn_purchaseorderreceiptproduct_Select, msdyn_purchaseorderreceiptproduct_Filter, { msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBooking: msdyn_purchaseorderreceiptproduct_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_rtv_Booking: WebExpand<BookableResourceBooking_Expand, msdyn_rtv_Select, msdyn_rtv_Filter, { msdyn_bookableresourcebooking_msdyn_rtv_Booking: msdyn_rtv_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_timeentry_BookableResourceBooking: WebExpand<BookableResourceBooking_Expand, msdyn_timeentry_Select, msdyn_timeentry_Filter, { msdyn_bookableresourcebooking_msdyn_timeentry_BookableResourceBooking: msdyn_timeentry_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking: WebExpand<BookableResourceBooking_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking: msdyn_workorderproduct_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_workorderservice_Booking: WebExpand<BookableResourceBooking_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { msdyn_bookableresourcebooking_msdyn_workorderservice_Booking: msdyn_workorderservice_Result[] }>;
  msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking: WebExpand<BookableResourceBooking_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking: msdyn_workorderservicetask_Result[] }>;
  msdyn_bookableresourcebookingquicknote_bookableresourcebooking: WebExpand<BookableResourceBooking_Expand, msdyn_bookableresourcebookingquicknote_Select, msdyn_bookableresourcebookingquicknote_Filter, { msdyn_bookableresourcebookingquicknote_bookableresourcebooking: msdyn_bookableresourcebookingquicknote_Result[] }>;
  msdyn_projectid: WebExpand<BookableResourceBooking_Expand, msdyn_project_Select, msdyn_project_Filter, { msdyn_projectid: msdyn_project_Result }>;
  msdyn_projectteamid: WebExpand<BookableResourceBooking_Expand, msdyn_projectteam_Select, msdyn_projectteam_Filter, { msdyn_projectteamid: msdyn_projectteam_Result }>;
  msdyn_requirementgroupid: WebExpand<BookableResourceBooking_Expand, msdyn_requirementgroup_Select, msdyn_requirementgroup_Filter, { msdyn_requirementgroupid: msdyn_requirementgroup_Result }>;
  msdyn_resourcecategoryid: WebExpand<BookableResourceBooking_Expand, BookableResourceCategory_Select, BookableResourceCategory_Filter, { msdyn_resourcecategoryid: BookableResourceCategory_Result }>;
  msdyn_resourcegroup: WebExpand<BookableResourceBooking_Expand, BookableResource_Select, BookableResource_Filter, { msdyn_resourcegroup: BookableResource_Result }>;
  msdyn_serviceappointment: WebExpand<BookableResourceBooking_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_serviceappointment: ServiceAppointment_Result }>;
  msdyn_timegroupdetailselected: WebExpand<BookableResourceBooking_Expand, msdyn_timegroupdetail_Select, msdyn_timegroupdetail_Filter, { msdyn_timegroupdetailselected: msdyn_timegroupdetail_Result }>;
  msdyn_workorder: WebExpand<BookableResourceBooking_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_workorder: msdyn_workorder_Result }>;
  ownerid: WebExpand<BookableResourceBooking_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<BookableResourceBooking_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<BookableResourceBooking_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<BookableResourceBooking_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  stageid: WebExpand<BookableResourceBooking_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid: ProcessStage_Result }>;
  transactioncurrencyid: WebExpand<BookableResourceBooking_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface BookableResourceBooking_FormattedResult {
  bookingstatus_formatted?: string;
  bookingtype_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  endtime_formatted?: string;
  header_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_actualarrivaltime_formatted?: string;
  msdyn_agreementbookingdate_formatted?: string;
  msdyn_appointmentbookingid_formatted?: string;
  msdyn_bookingmethod_formatted?: string;
  msdyn_bookingsetupmetadataid_formatted?: string;
  msdyn_crew_formatted?: string;
  msdyn_crewmembertype_formatted?: string;
  msdyn_estimatedarrivaltime_formatted?: string;
  msdyn_offlinetimestamp_formatted?: string;
  msdyn_projectid_formatted?: string;
  msdyn_projectteamid_formatted?: string;
  msdyn_quickNoteAction_formatted?: string;
  msdyn_requirementgroupid_formatted?: string;
  msdyn_resourcecategoryid_formatted?: string;
  msdyn_resourcegroup_formatted?: string;
  msdyn_resourcerequirement_formatted?: string;
  msdyn_serviceappointment_formatted?: string;
  msdyn_timegroupdetailselected_formatted?: string;
  msdyn_totalcost_base_formatted?: string;
  msdyn_totalcost_formatted?: string;
  msdyn_traveltimecalculationtype_formatted?: string;
  msdyn_worklocation_formatted?: string;
  msdyn_workorder_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  resource_formatted?: string;
  starttime_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface BookableResourceBooking_Result extends BookableResourceBooking_Base, BookableResourceBooking_Relationships {
  "@odata.etag": string;
  bookingstatus_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  header_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_agreementbookingdate_guid: string | null;
  msdyn_appointmentbookingid_guid: string | null;
  msdyn_bookingsetupmetadataid_guid: string | null;
  msdyn_crew_guid: string | null;
  msdyn_projectid_guid: string | null;
  msdyn_projectteamid_guid: string | null;
  msdyn_requirementgroupid_guid: string | null;
  msdyn_resourcecategoryid_guid: string | null;
  msdyn_resourcegroup_guid: string | null;
  msdyn_resourcerequirement_guid: string | null;
  msdyn_serviceappointment_guid: string | null;
  msdyn_timegroupdetailselected_guid: string | null;
  msdyn_workorder_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  resource_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface BookableResourceBooking_RelatedOne {
  BookingStatus: WebMappingRetrieve<BookingStatus_Select,BookingStatus_Expand,BookingStatus_Filter,BookingStatus_Fixed,BookingStatus_Result,BookingStatus_FormattedResult>;
  Header: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  Resource: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  createdbyname: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfbyname: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedbyname: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfbyname: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_AppointmentBookingId: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_BookingSetupMetadataId: WebMappingRetrieve<msdyn_bookingsetupmetadata_Select,msdyn_bookingsetupmetadata_Expand,msdyn_bookingsetupmetadata_Filter,msdyn_bookingsetupmetadata_Fixed,msdyn_bookingsetupmetadata_Result,msdyn_bookingsetupmetadata_FormattedResult>;
  msdyn_Crew: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  msdyn_ResourceRequirement: WebMappingRetrieve<msdyn_resourcerequirement_Select,msdyn_resourcerequirement_Expand,msdyn_resourcerequirement_Filter,msdyn_resourcerequirement_Fixed,msdyn_resourcerequirement_Result,msdyn_resourcerequirement_FormattedResult>;
  msdyn_agreementbookingdate: WebMappingRetrieve<msdyn_agreementbookingdate_Select,msdyn_agreementbookingdate_Expand,msdyn_agreementbookingdate_Filter,msdyn_agreementbookingdate_Fixed,msdyn_agreementbookingdate_Result,msdyn_agreementbookingdate_FormattedResult>;
  msdyn_projectid: WebMappingRetrieve<msdyn_project_Select,msdyn_project_Expand,msdyn_project_Filter,msdyn_project_Fixed,msdyn_project_Result,msdyn_project_FormattedResult>;
  msdyn_projectteamid: WebMappingRetrieve<msdyn_projectteam_Select,msdyn_projectteam_Expand,msdyn_projectteam_Filter,msdyn_projectteam_Fixed,msdyn_projectteam_Result,msdyn_projectteam_FormattedResult>;
  msdyn_requirementgroupid: WebMappingRetrieve<msdyn_requirementgroup_Select,msdyn_requirementgroup_Expand,msdyn_requirementgroup_Filter,msdyn_requirementgroup_Fixed,msdyn_requirementgroup_Result,msdyn_requirementgroup_FormattedResult>;
  msdyn_resourcecategoryid: WebMappingRetrieve<BookableResourceCategory_Select,BookableResourceCategory_Expand,BookableResourceCategory_Filter,BookableResourceCategory_Fixed,BookableResourceCategory_Result,BookableResourceCategory_FormattedResult>;
  msdyn_resourcegroup: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  msdyn_serviceappointment: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_timegroupdetailselected: WebMappingRetrieve<msdyn_timegroupdetail_Select,msdyn_timegroupdetail_Expand,msdyn_timegroupdetail_Filter,msdyn_timegroupdetail_Fixed,msdyn_timegroupdetail_Result,msdyn_timegroupdetail_FormattedResult>;
  msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  stageid: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface BookableResourceBooking_RelatedMany {
  BookableResourceBooking_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  bookableresourcebooking_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  bookableresourcebooking_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  bookableresourcebooking_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  bookableresourcebooking_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  bookableresourcebooking_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  bookableresourcebooking_BulkOperations: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  bookableresourcebooking_CampaignActivities: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  bookableresourcebooking_CampaignResponses: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  bookableresourcebooking_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  bookableresourcebooking_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  bookableresourcebooking_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  bookableresourcebooking_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  bookableresourcebooking_IncidentResolutions: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  bookableresourcebooking_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  bookableresourcebooking_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  bookableresourcebooking_OpportunityCloses: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  bookableresourcebooking_OrderCloses: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  bookableresourcebooking_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  bookableresourcebooking_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  bookableresourcebooking_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  bookableresourcebooking_QuoteCloses: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  bookableresourcebooking_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  bookableresourcebooking_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  bookableresourcebooking_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  bookableresourcebooking_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  bookableresourcebooking_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  bookableresourcebooking_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  bookableresourcebooking_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  bookableresourcebooking_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  bookableresourcebooking_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  bookableresourcebooking_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  bookableresourcebooking_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  bookableresourcebooking_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  bookableresourcebooking_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking: WebMappingRetrieve<msdyn_bookingjournal_Select,msdyn_bookingjournal_Expand,msdyn_bookingjournal_Filter,msdyn_bookingjournal_Fixed,msdyn_bookingjournal_Result,msdyn_bookingjournal_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking: WebMappingRetrieve<msdyn_bookingtimestamp_Select,msdyn_bookingtimestamp_Expand,msdyn_bookingtimestamp_Filter,msdyn_bookingtimestamp_Fixed,msdyn_bookingtimestamp_Result,msdyn_bookingtimestamp_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_geofence_bookableresourcebookingid: WebMappingRetrieve<msdyn_geofence_Select,msdyn_geofence_Expand,msdyn_geofence_Filter,msdyn_geofence_Fixed,msdyn_geofence_Result,msdyn_geofence_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking: WebMappingRetrieve<msdyn_purchaseorder_Select,msdyn_purchaseorder_Expand,msdyn_purchaseorder_Filter,msdyn_purchaseorder_Fixed,msdyn_purchaseorder_Result,msdyn_purchaseorder_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking: WebMappingRetrieve<msdyn_purchaseorderproduct_Select,msdyn_purchaseorderproduct_Expand,msdyn_purchaseorderproduct_Filter,msdyn_purchaseorderproduct_Fixed,msdyn_purchaseorderproduct_Result,msdyn_purchaseorderproduct_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBooking: WebMappingRetrieve<msdyn_purchaseorderreceiptproduct_Select,msdyn_purchaseorderreceiptproduct_Expand,msdyn_purchaseorderreceiptproduct_Filter,msdyn_purchaseorderreceiptproduct_Fixed,msdyn_purchaseorderreceiptproduct_Result,msdyn_purchaseorderreceiptproduct_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_rtv_Booking: WebMappingRetrieve<msdyn_rtv_Select,msdyn_rtv_Expand,msdyn_rtv_Filter,msdyn_rtv_Fixed,msdyn_rtv_Result,msdyn_rtv_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_timeentry_BookableResourceBooking: WebMappingRetrieve<msdyn_timeentry_Select,msdyn_timeentry_Expand,msdyn_timeentry_Filter,msdyn_timeentry_Fixed,msdyn_timeentry_Result,msdyn_timeentry_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_workorderservice_Booking: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  msdyn_bookableresourcebookingquicknote_bookableresourcebooking: WebMappingRetrieve<msdyn_bookableresourcebookingquicknote_Select,msdyn_bookableresourcebookingquicknote_Expand,msdyn_bookableresourcebookingquicknote_Filter,msdyn_bookableresourcebookingquicknote_Fixed,msdyn_bookableresourcebookingquicknote_Result,msdyn_bookableresourcebookingquicknote_FormattedResult>;
}
interface WebEntitiesRetrieve {
  bookableresourcebookings: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
}
interface WebEntitiesRelated {
  bookableresourcebookings: WebMappingRelated<BookableResourceBooking_RelatedOne,BookableResourceBooking_RelatedMany>;
}
interface WebEntitiesCUDA {
  bookableresourcebookings: WebMappingCUDA<BookableResourceBooking_Create,BookableResourceBooking_Update,BookableResourceBooking_Select>;
}
