interface BulkOperation_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  bulkoperationnumber?: string | null;
  community?: socialprofile_community | null;
  createdon?: Date | null;
  createdrecordtypecode?: bulkoperation_createdrecordtypecode | null;
  deliverylastattemptedon?: Date | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  description?: string | null;
  errornumber?: number | null;
  exchangeitemid?: string | null;
  exchangerate?: number | null;
  exchangeweblink?: string | null;
  failurecount?: number | null;
  importsequencenumber?: number | null;
  instancetypecode?: _bulkoperation_instancetypecode | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  operationtypecode?: bulkoperation_operationtypecode | null;
  overriddencreatedon?: Date | null;
  parameters?: string | null;
  postponeactivityprocessinguntil?: Date | null;
  prioritycode?: _bulkoperation_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  senton?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: bulkoperation_statecode | null;
  statuscode?: bulkoperation_statuscode | null;
  subject?: string | null;
  successcount?: number | null;
  targetedrecordtypecode?: bulkoperation_targetedrecordtypecode | null;
  targetmemberscount?: number | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
  workflowinfo?: string | null;
}
interface BulkOperation_Relationships {
  BulkOperation_ActivityPointers?: ActivityPointer_Result[] | null;
  BulkOperation_Appointment?: Appointment_Result[] | null;
  BulkOperation_AsyncOperations?: AsyncOperation_Result[] | null;
  BulkOperation_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  BulkOperation_CampaignResponse?: CampaignResponse_Result[] | null;
  BulkOperation_Email?: Email_Result[] | null;
  BulkOperation_Faxes?: Fax_Result[] | null;
  BulkOperation_Letter?: Letter_Result[] | null;
  BulkOperation_Logs_Accounts?: Account_Result[] | null;
  BulkOperation_Logs_Contacts?: Contact_Result[] | null;
  BulkOperation_Logs_Leads?: Lead_Result[] | null;
  BulkOperation_MailboxTrackingFolder?: MailboxTrackingFolder_Result[] | null;
  BulkOperation_Phonecall?: PhoneCall_Result[] | null;
  BulkOperation_QueueItem?: QueueItem_Result[] | null;
  BulkOperation_RecurringAppointmentMaster?: RecurringAppointmentMaster_Result[] | null;
  BulkOperation_SocialActivity?: SocialActivity_Result[] | null;
  BulkOperation_SyncErrors?: SyncError_Result[] | null;
  BulkOperation_logs?: BulkOperationLog_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  bulkoperation_Annotations?: Annotation_Result[] | null;
  bulkoperation_IncidentResolutions?: IncidentResolution_Result[] | null;
  bulkoperation_OpportunityCloses?: OpportunityClose_Result[] | null;
  bulkoperation_OrderCloses?: OrderClose_Result[] | null;
  bulkoperation_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  bulkoperation_QuoteCloses?: QuoteClose_Result[] | null;
  bulkoperation_ServiceAppointments?: ServiceAppointment_Result[] | null;
  bulkoperation_Tasks?: Task_Result[] | null;
  bulkoperation_activity_parties?: ActivityParty_Result[] | null;
  bulkoperation_msdyn_approvals?: msdyn_approval_Result[] | null;
  bulkoperation_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  bulkoperation_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  bulkoperation_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  bulkoperation_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  bulkoperation_msfp_alerts?: msfp_alert_Result[] | null;
  bulkoperation_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  bulkoperation_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  createdby_bulkoperation?: SystemUser_Result | null;
  createdonbehalfby_bulkoperation?: SystemUser_Result | null;
  modifiedby_bulkoperation?: SystemUser_Result | null;
  modifiedonbehalfby_bulkoperation?: SystemUser_Result | null;
  ownerid_bulkoperation?: Team_Result | null;
  ownerid_bulkoperation1?: SystemUser_Result | null;
  owningbusinessunit_bulkoperation?: BusinessUnit_Result | null;
  owningteam_bulkoperation?: Team_Result | null;
  owninguser_bulkoperation?: SystemUser_Result | null;
  regardingobjectid_account_bulkoperation?: Account_Result | null;
  regardingobjectid_bookableresourcebooking_bulkoperation?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_bulkoperation?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_campaignactivity_bulkoperation?: CampaignActivity_Result | null;
  regardingobjectid_contact_bulkoperation?: Contact_Result | null;
  regardingobjectid_knowledgearticle_bulkoperation?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_bulkoperation?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_bulkoperation?: Lead_Result | null;
  regardingobjectid_list?: List_Result | null;
  regardingobjectid_new_interactionforemail_bulkoperation?: InteractionForEmail_Result | null;
  sendermailboxid_bulkoperation?: Mailbox_Result | null;
  sla_activitypointer_sla_bulkoperation?: SLA_Result | null;
  slainvokedid_activitypointer_sla_bulkoperation?: SLA_Result | null;
  transactioncurrencyid_bulkoperation?: TransactionCurrency_Result | null;
  userentityinstancedata_bulkoperation?: UserEntityInstanceData_Result[] | null;
}
interface BulkOperation extends BulkOperation_Base, BulkOperation_Relationships {
  sla_activitypointer_sla_bulkoperation_bind$slas?: string | null;
  transactioncurrencyid_bulkoperation_bind$transactioncurrencies?: string | null;
}
interface BulkOperation_Create extends BulkOperation {
  activityid_activitypointer_bind$activitypointers?: string | null;
  ownerid_bulkoperation_bind$systemusers?: string | null;
  ownerid_bulkoperation_bind$teams?: string | null;
  regardingobjectid_account_bulkoperation_bind$accounts?: string | null;
  regardingobjectid_bookableresourcebooking_bulkoperation_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_bulkoperation_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_campaignactivity_bulkoperation_bind$campaignactivities?: string | null;
  regardingobjectid_contact_bulkoperation_bind$contacts?: string | null;
  regardingobjectid_knowledgearticle_bulkoperation_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_bulkoperation_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_bulkoperation_bind$leads?: string | null;
  regardingobjectid_list_bind$lists?: string | null;
  regardingobjectid_new_interactionforemail_bulkoperation_bind$interactionforemails?: string | null;
}
interface BulkOperation_Update extends BulkOperation {
}
interface BulkOperation_Select {
  activityadditionalparams: WebAttribute<BulkOperation_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<BulkOperation_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<BulkOperation_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<BulkOperation_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<BulkOperation_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<BulkOperation_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  bcc_guid: WebAttribute<BulkOperation_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
  bulkoperationnumber: WebAttribute<BulkOperation_Select, { bulkoperationnumber: string | null }, {  }>;
  cc_guid: WebAttribute<BulkOperation_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
  community: WebAttribute<BulkOperation_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  createdby_guid: WebAttribute<BulkOperation_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<BulkOperation_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<BulkOperation_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  createdrecordtypecode: WebAttribute<BulkOperation_Select, { createdrecordtypecode: bulkoperation_createdrecordtypecode | null }, { createdrecordtypecode_formatted?: string }>;
  customers_guid: WebAttribute<BulkOperation_Select, { customers_guid: string | null }, { customers_formatted?: string }>;
  deliverylastattemptedon: WebAttribute<BulkOperation_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
  deliveryprioritycode: WebAttribute<BulkOperation_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  description: WebAttribute<BulkOperation_Select, { description: string | null }, {  }>;
  errornumber: WebAttribute<BulkOperation_Select, { errornumber: number | null }, {  }>;
  exchangeitemid: WebAttribute<BulkOperation_Select, { exchangeitemid: string | null }, {  }>;
  exchangerate: WebAttribute<BulkOperation_Select, { exchangerate: number | null }, {  }>;
  exchangeweblink: WebAttribute<BulkOperation_Select, { exchangeweblink: string | null }, {  }>;
  failurecount: WebAttribute<BulkOperation_Select, { failurecount: number | null }, {  }>;
  from_guid: WebAttribute<BulkOperation_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<BulkOperation_Select, { importsequencenumber: number | null }, {  }>;
  instancetypecode: WebAttribute<BulkOperation_Select, { instancetypecode: _bulkoperation_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isbilled: WebAttribute<BulkOperation_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<BulkOperation_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<BulkOperation_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<BulkOperation_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<BulkOperation_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<BulkOperation_Select, { leftvoicemail: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<BulkOperation_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<BulkOperation_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<BulkOperation_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<BulkOperation_Select, { onholdtime: number | null }, {  }>;
  operationtypecode: WebAttribute<BulkOperation_Select, { operationtypecode: bulkoperation_operationtypecode | null }, { operationtypecode_formatted?: string }>;
  optionalattendees_guid: WebAttribute<BulkOperation_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<BulkOperation_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  overriddencreatedon: WebAttribute<BulkOperation_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<BulkOperation_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<BulkOperation_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<BulkOperation_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<BulkOperation_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  parameters: WebAttribute<BulkOperation_Select, { parameters: string | null }, {  }>;
  partners_guid: WebAttribute<BulkOperation_Select, { partners_guid: string | null }, { partners_formatted?: string }>;
  postponeactivityprocessinguntil: WebAttribute<BulkOperation_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<BulkOperation_Select, { prioritycode: _bulkoperation_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<BulkOperation_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<BulkOperation_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<BulkOperation_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  resources_guid: WebAttribute<BulkOperation_Select, { resources_guid: string | null }, { resources_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<BulkOperation_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<BulkOperation_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<BulkOperation_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sendermailboxid_guid: WebAttribute<BulkOperation_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  senton: WebAttribute<BulkOperation_Select, { senton: Date | null }, { senton_formatted?: string }>;
  seriesid: WebAttribute<BulkOperation_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<BulkOperation_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<BulkOperation_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<BulkOperation_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<BulkOperation_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<BulkOperation_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<BulkOperation_Select, { statecode: bulkoperation_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<BulkOperation_Select, { statuscode: bulkoperation_statuscode | null }, { statuscode_formatted?: string }>;
  subject: WebAttribute<BulkOperation_Select, { subject: string | null }, {  }>;
  successcount: WebAttribute<BulkOperation_Select, { successcount: number | null }, {  }>;
  targetedrecordtypecode: WebAttribute<BulkOperation_Select, { targetedrecordtypecode: bulkoperation_targetedrecordtypecode | null }, { targetedrecordtypecode_formatted?: string }>;
  targetmemberscount: WebAttribute<BulkOperation_Select, { targetmemberscount: number | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<BulkOperation_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<BulkOperation_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<BulkOperation_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<BulkOperation_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<BulkOperation_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<BulkOperation_Select, { versionnumber: number | null }, {  }>;
  workflowinfo: WebAttribute<BulkOperation_Select, { workflowinfo: string | null }, {  }>;
}
interface BulkOperation_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  bcc_guid: XQW.Guid;
  bulkoperationnumber: string;
  cc_guid: XQW.Guid;
  community: socialprofile_community;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  createdrecordtypecode: bulkoperation_createdrecordtypecode;
  customers_guid: XQW.Guid;
  deliverylastattemptedon: Date;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  description: string;
  errornumber: number;
  exchangeitemid: string;
  exchangerate: any;
  exchangeweblink: string;
  failurecount: number;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  instancetypecode: _bulkoperation_instancetypecode;
  isbilled: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  operationtypecode: bulkoperation_operationtypecode;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  parameters: string;
  partners_guid: XQW.Guid;
  postponeactivityprocessinguntil: Date;
  prioritycode: _bulkoperation_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  resources_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sendermailboxid_guid: XQW.Guid;
  senton: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: bulkoperation_statecode;
  statuscode: bulkoperation_statuscode;
  subject: string;
  successcount: number;
  targetedrecordtypecode: bulkoperation_targetedrecordtypecode;
  targetmemberscount: number;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
  workflowinfo: string;
}
interface BulkOperation_Expand {
  BulkOperation_ActivityPointers: WebExpand<BulkOperation_Expand, ActivityPointer_Select, ActivityPointer_Filter, { BulkOperation_ActivityPointers: ActivityPointer_Result[] }>;
  BulkOperation_Appointment: WebExpand<BulkOperation_Expand, Appointment_Select, Appointment_Filter, { BulkOperation_Appointment: Appointment_Result[] }>;
  BulkOperation_AsyncOperations: WebExpand<BulkOperation_Expand, AsyncOperation_Select, AsyncOperation_Filter, { BulkOperation_AsyncOperations: AsyncOperation_Result[] }>;
  BulkOperation_BulkDeleteFailures: WebExpand<BulkOperation_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { BulkOperation_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  BulkOperation_CampaignResponse: WebExpand<BulkOperation_Expand, CampaignResponse_Select, CampaignResponse_Filter, { BulkOperation_CampaignResponse: CampaignResponse_Result[] }>;
  BulkOperation_Email: WebExpand<BulkOperation_Expand, Email_Select, Email_Filter, { BulkOperation_Email: Email_Result[] }>;
  BulkOperation_Faxes: WebExpand<BulkOperation_Expand, Fax_Select, Fax_Filter, { BulkOperation_Faxes: Fax_Result[] }>;
  BulkOperation_Letter: WebExpand<BulkOperation_Expand, Letter_Select, Letter_Filter, { BulkOperation_Letter: Letter_Result[] }>;
  BulkOperation_Logs_Accounts: WebExpand<BulkOperation_Expand, Account_Select, Account_Filter, { BulkOperation_Logs_Accounts: Account_Result[] }>;
  BulkOperation_Logs_Contacts: WebExpand<BulkOperation_Expand, Contact_Select, Contact_Filter, { BulkOperation_Logs_Contacts: Contact_Result[] }>;
  BulkOperation_Logs_Leads: WebExpand<BulkOperation_Expand, Lead_Select, Lead_Filter, { BulkOperation_Logs_Leads: Lead_Result[] }>;
  BulkOperation_MailboxTrackingFolder: WebExpand<BulkOperation_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { BulkOperation_MailboxTrackingFolder: MailboxTrackingFolder_Result[] }>;
  BulkOperation_Phonecall: WebExpand<BulkOperation_Expand, PhoneCall_Select, PhoneCall_Filter, { BulkOperation_Phonecall: PhoneCall_Result[] }>;
  BulkOperation_QueueItem: WebExpand<BulkOperation_Expand, QueueItem_Select, QueueItem_Filter, { BulkOperation_QueueItem: QueueItem_Result[] }>;
  BulkOperation_RecurringAppointmentMaster: WebExpand<BulkOperation_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { BulkOperation_RecurringAppointmentMaster: RecurringAppointmentMaster_Result[] }>;
  BulkOperation_SocialActivity: WebExpand<BulkOperation_Expand, SocialActivity_Select, SocialActivity_Filter, { BulkOperation_SocialActivity: SocialActivity_Result[] }>;
  BulkOperation_SyncErrors: WebExpand<BulkOperation_Expand, SyncError_Select, SyncError_Filter, { BulkOperation_SyncErrors: SyncError_Result[] }>;
  BulkOperation_logs: WebExpand<BulkOperation_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { BulkOperation_logs: BulkOperationLog_Result[] }>;
  activityid_activitypointer: WebExpand<BulkOperation_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  bulkoperation_Annotations: WebExpand<BulkOperation_Expand, Annotation_Select, Annotation_Filter, { bulkoperation_Annotations: Annotation_Result[] }>;
  bulkoperation_IncidentResolutions: WebExpand<BulkOperation_Expand, IncidentResolution_Select, IncidentResolution_Filter, { bulkoperation_IncidentResolutions: IncidentResolution_Result[] }>;
  bulkoperation_OpportunityCloses: WebExpand<BulkOperation_Expand, OpportunityClose_Select, OpportunityClose_Filter, { bulkoperation_OpportunityCloses: OpportunityClose_Result[] }>;
  bulkoperation_OrderCloses: WebExpand<BulkOperation_Expand, OrderClose_Select, OrderClose_Filter, { bulkoperation_OrderCloses: OrderClose_Result[] }>;
  bulkoperation_PrincipalObjectAttributeAccesses: WebExpand<BulkOperation_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { bulkoperation_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  bulkoperation_QuoteCloses: WebExpand<BulkOperation_Expand, QuoteClose_Select, QuoteClose_Filter, { bulkoperation_QuoteCloses: QuoteClose_Result[] }>;
  bulkoperation_ServiceAppointments: WebExpand<BulkOperation_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { bulkoperation_ServiceAppointments: ServiceAppointment_Result[] }>;
  bulkoperation_Tasks: WebExpand<BulkOperation_Expand, Task_Select, Task_Filter, { bulkoperation_Tasks: Task_Result[] }>;
  bulkoperation_activity_parties: WebExpand<BulkOperation_Expand, ActivityParty_Select, ActivityParty_Filter, { bulkoperation_activity_parties: ActivityParty_Result[] }>;
  bulkoperation_msdyn_approvals: WebExpand<BulkOperation_Expand, msdyn_approval_Select, msdyn_approval_Filter, { bulkoperation_msdyn_approvals: msdyn_approval_Result[] }>;
  bulkoperation_msdyn_bookingalerts: WebExpand<BulkOperation_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { bulkoperation_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  bulkoperation_msdyn_ocliveworkitems: WebExpand<BulkOperation_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { bulkoperation_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  bulkoperation_msdyn_ocoutboundmessages: WebExpand<BulkOperation_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { bulkoperation_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  bulkoperation_msdyn_ocsessions: WebExpand<BulkOperation_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { bulkoperation_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  bulkoperation_msfp_alerts: WebExpand<BulkOperation_Expand, msfp_alert_Select, msfp_alert_Filter, { bulkoperation_msfp_alerts: msfp_alert_Result[] }>;
  bulkoperation_msfp_surveyinvites: WebExpand<BulkOperation_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { bulkoperation_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  bulkoperation_msfp_surveyresponses: WebExpand<BulkOperation_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { bulkoperation_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  createdby_bulkoperation: WebExpand<BulkOperation_Expand, SystemUser_Select, SystemUser_Filter, { createdby_bulkoperation: SystemUser_Result }>;
  createdonbehalfby_bulkoperation: WebExpand<BulkOperation_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_bulkoperation: SystemUser_Result }>;
  modifiedby_bulkoperation: WebExpand<BulkOperation_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_bulkoperation: SystemUser_Result }>;
  modifiedonbehalfby_bulkoperation: WebExpand<BulkOperation_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_bulkoperation: SystemUser_Result }>;
  ownerid_bulkoperation: WebExpand<BulkOperation_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_bulkoperation: SystemUser_Result } & { ownerid_bulkoperation: Team_Result }>;
  owningbusinessunit_bulkoperation: WebExpand<BulkOperation_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_bulkoperation: BusinessUnit_Result }>;
  owningteam_bulkoperation: WebExpand<BulkOperation_Expand, Team_Select, Team_Filter, { owningteam_bulkoperation: Team_Result }>;
  owninguser_bulkoperation: WebExpand<BulkOperation_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_bulkoperation: SystemUser_Result }>;
  regardingobjectid_account_bulkoperation: WebExpand<BulkOperation_Expand, Account_Select, Account_Filter, { regardingobjectid_account_bulkoperation: Account_Result }>;
  regardingobjectid_bookableresourcebooking_bulkoperation: WebExpand<BulkOperation_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_bulkoperation: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_bulkoperation: WebExpand<BulkOperation_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_bulkoperation: BookableResourceBookingHeader_Result }>;
  regardingobjectid_campaignactivity_bulkoperation: WebExpand<BulkOperation_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_bulkoperation: CampaignActivity_Result }>;
  regardingobjectid_contact_bulkoperation: WebExpand<BulkOperation_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_bulkoperation: Contact_Result }>;
  regardingobjectid_knowledgearticle_bulkoperation: WebExpand<BulkOperation_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_bulkoperation: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_bulkoperation: WebExpand<BulkOperation_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_bulkoperation: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_bulkoperation: WebExpand<BulkOperation_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_bulkoperation: Lead_Result }>;
  regardingobjectid_list: WebExpand<BulkOperation_Expand, List_Select, List_Filter, { regardingobjectid_list: List_Result }>;
  regardingobjectid_new_interactionforemail_bulkoperation: WebExpand<BulkOperation_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { regardingobjectid_new_interactionforemail_bulkoperation: InteractionForEmail_Result }>;
  sendermailboxid_bulkoperation: WebExpand<BulkOperation_Expand, Mailbox_Select, Mailbox_Filter, { sendermailboxid_bulkoperation: Mailbox_Result }>;
  sla_activitypointer_sla_bulkoperation: WebExpand<BulkOperation_Expand, SLA_Select, SLA_Filter, { sla_activitypointer_sla_bulkoperation: SLA_Result }>;
  slainvokedid_activitypointer_sla_bulkoperation: WebExpand<BulkOperation_Expand, SLA_Select, SLA_Filter, { slainvokedid_activitypointer_sla_bulkoperation: SLA_Result }>;
  transactioncurrencyid_bulkoperation: WebExpand<BulkOperation_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_bulkoperation: TransactionCurrency_Result }>;
  userentityinstancedata_bulkoperation: WebExpand<BulkOperation_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_bulkoperation: UserEntityInstanceData_Result[] }>;
}
interface BulkOperation_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  bcc_formatted?: string;
  cc_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  createdrecordtypecode_formatted?: string;
  customers_formatted?: string;
  deliverylastattemptedon_formatted?: string;
  deliveryprioritycode_formatted?: string;
  from_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  operationtypecode_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  partners_formatted?: string;
  postponeactivityprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  resources_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  targetedrecordtypecode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface BulkOperation_Result extends BulkOperation_Base, BulkOperation_Relationships {
  "@odata.etag": string;
  bcc_guid: string | null;
  cc_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  customers_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  partners_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  resources_guid: string | null;
  sendermailboxid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface BulkOperation_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_bulkoperation: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_bulkoperation: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_bulkoperation: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_bulkoperation: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_bulkoperation: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_bulkoperation1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_bulkoperation: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_bulkoperation: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_bulkoperation: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_bulkoperation: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_bookableresourcebooking_bulkoperation: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_bulkoperation: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_campaignactivity_bulkoperation: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_bulkoperation: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_knowledgearticle_bulkoperation: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_bulkoperation: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_bulkoperation: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_list: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  regardingobjectid_new_interactionforemail_bulkoperation: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  sendermailboxid_bulkoperation: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  sla_activitypointer_sla_bulkoperation: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_activitypointer_sla_bulkoperation: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  transactioncurrencyid_bulkoperation: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface BulkOperation_RelatedMany {
  BulkOperation_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  BulkOperation_Appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  BulkOperation_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  BulkOperation_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  BulkOperation_CampaignResponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  BulkOperation_Email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  BulkOperation_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  BulkOperation_Letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  BulkOperation_Logs_Accounts: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  BulkOperation_Logs_Contacts: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  BulkOperation_Logs_Leads: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  BulkOperation_MailboxTrackingFolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  BulkOperation_Phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  BulkOperation_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  BulkOperation_RecurringAppointmentMaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  BulkOperation_SocialActivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  BulkOperation_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  BulkOperation_logs: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  bulkoperation_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  bulkoperation_IncidentResolutions: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  bulkoperation_OpportunityCloses: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  bulkoperation_OrderCloses: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  bulkoperation_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  bulkoperation_QuoteCloses: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  bulkoperation_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  bulkoperation_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  bulkoperation_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  bulkoperation_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  bulkoperation_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  bulkoperation_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  bulkoperation_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  bulkoperation_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  bulkoperation_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  bulkoperation_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  bulkoperation_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  userentityinstancedata_bulkoperation: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  bulkoperations: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
}
interface WebEntitiesRelated {
  bulkoperations: WebMappingRelated<BulkOperation_RelatedOne,BulkOperation_RelatedMany>;
}
interface WebEntitiesCUDA {
  bulkoperations: WebMappingCUDA<BulkOperation_Create,BulkOperation_Update,BulkOperation_Select>;
}
