interface Campaign_Base extends WebEntity {
  actualend?: Date | null;
  actualstart?: Date | null;
  budgetedcost?: number | null;
  budgetedcost_base?: number | null;
  campaignid?: string | null;
  codename?: string | null;
  createdon?: Date | null;
  description?: string | null;
  emailaddress?: string | null;
  entityimageid?: string | null;
  exchangerate?: number | null;
  expectedresponse?: number | null;
  expectedrevenue?: number | null;
  expectedrevenue_base?: number | null;
  importsequencenumber?: number | null;
  istemplate?: boolean | null;
  message?: string | null;
  modifiedon?: Date | null;
  name?: string | null;
  objective?: string | null;
  othercost?: number | null;
  othercost_base?: number | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  promotioncodename?: string | null;
  proposedend?: Date | null;
  proposedstart?: Date | null;
  stageid?: string | null;
  statecode?: campaign_statecode | null;
  statuscode?: campaign_statuscode | null;
  timezoneruleversionnumber?: number | null;
  tmpregardingobjectid?: string | null;
  totalactualcost?: number | null;
  totalactualcost_base?: number | null;
  totalcampaignactivityactualcost?: number | null;
  totalcampaignactivityactualcost_base?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  typecode?: campaign_typecode | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface Campaign_Relationships {
  Campaign_ActivityPointers?: ActivityPointer_Result[] | null;
  Campaign_Annotation?: Annotation_Result[] | null;
  Campaign_Appointments?: Appointment_Result[] | null;
  Campaign_AsyncOperations?: AsyncOperation_Result[] | null;
  Campaign_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Campaign_CampaignActivities?: CampaignActivity_Result[] | null;
  Campaign_CampaignResponses?: CampaignResponse_Result[] | null;
  Campaign_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Campaign_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Campaign_Emails?: Email_Result[] | null;
  Campaign_Faxes?: Fax_Result[] | null;
  Campaign_Letters?: Letter_Result[] | null;
  Campaign_MailboxTrackingFolder?: MailboxTrackingFolder_Result[] | null;
  Campaign_Phonecalls?: PhoneCall_Result[] | null;
  Campaign_ProcessSessions?: ProcessSession_Result[] | null;
  Campaign_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  Campaign_ServiceAppointments?: ServiceAppointment_Result[] | null;
  Campaign_SyncErrors?: SyncError_Result[] | null;
  Campaign_Tasks?: Task_Result[] | null;
  campaign_IncidentResolutions?: IncidentResolution_Result[] | null;
  campaign_OpportunityCloses?: OpportunityClose_Result[] | null;
  campaign_OrderCloses?: OrderClose_Result[] | null;
  campaign_QuoteCloses?: QuoteClose_Result[] | null;
  campaign_SocialActivities?: SocialActivity_Result[] | null;
  campaign_activity_parties?: ActivityParty_Result[] | null;
  campaign_connections1?: Connection_Result[] | null;
  campaign_connections2?: Connection_Result[] | null;
  campaign_leads?: Lead_Result[] | null;
  campaign_msdyn_approvals?: msdyn_approval_Result[] | null;
  campaign_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  campaign_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  campaign_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  campaign_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  campaign_msfp_alerts?: msfp_alert_Result[] | null;
  campaign_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  campaign_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  campaign_opportunities?: Opportunity_Result[] | null;
  campaign_orders?: SalesOrder_Result[] | null;
  campaign_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  campaign_quotes?: Quote_Result[] | null;
  campaigncampaign_association?: Campaign_Result[] | null;
  campaignlist_association?: List_Result[] | null;
  campaignproduct_association?: Product_Result[] | null;
  campaignsalesliterature_association?: SalesLiterature_Result[] | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  stageid_processstage?: ProcessStage_Result | null;
  userentityinstancedata_campaign?: UserEntityInstanceData_Result[] | null;
}
interface Campaign extends Campaign_Base, Campaign_Relationships {
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  pricelistid_bind$pricelevels?: string | null;
  stageid_processstage_bind$processstages?: string | null;
}
interface Campaign_Create extends Campaign {
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface Campaign_Update extends Campaign {
}
interface Campaign_Select {
  actualend: WebAttribute<Campaign_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<Campaign_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  budgetedcost: WebAttribute<Campaign_Select, { budgetedcost: number | null; transactioncurrencyid_guid: string | null }, { budgetedcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  budgetedcost_base: WebAttribute<Campaign_Select, { budgetedcost_base: number | null; transactioncurrencyid_guid: string | null }, { budgetedcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  campaignid: WebAttribute<Campaign_Select, { campaignid: string | null }, {  }>;
  codename: WebAttribute<Campaign_Select, { codename: string | null }, {  }>;
  createdby_guid: WebAttribute<Campaign_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Campaign_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Campaign_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<Campaign_Select, { description: string | null }, {  }>;
  emailaddress: WebAttribute<Campaign_Select, { emailaddress: string | null }, {  }>;
  entityimageid: WebAttribute<Campaign_Select, { entityimageid: string | null }, {  }>;
  exchangerate: WebAttribute<Campaign_Select, { exchangerate: number | null }, {  }>;
  expectedresponse: WebAttribute<Campaign_Select, { expectedresponse: number | null }, {  }>;
  expectedrevenue: WebAttribute<Campaign_Select, { expectedrevenue: number | null; transactioncurrencyid_guid: string | null }, { expectedrevenue_formatted?: string; transactioncurrencyid_formatted?: string }>;
  expectedrevenue_base: WebAttribute<Campaign_Select, { expectedrevenue_base: number | null; transactioncurrencyid_guid: string | null }, { expectedrevenue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  importsequencenumber: WebAttribute<Campaign_Select, { importsequencenumber: number | null }, {  }>;
  istemplate: WebAttribute<Campaign_Select, { istemplate: boolean | null }, {  }>;
  message: WebAttribute<Campaign_Select, { message: string | null }, {  }>;
  modifiedby_guid: WebAttribute<Campaign_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Campaign_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Campaign_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  name: WebAttribute<Campaign_Select, { name: string | null }, {  }>;
  objective: WebAttribute<Campaign_Select, { objective: string | null }, {  }>;
  othercost: WebAttribute<Campaign_Select, { othercost: number | null; transactioncurrencyid_guid: string | null }, { othercost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  othercost_base: WebAttribute<Campaign_Select, { othercost_base: number | null; transactioncurrencyid_guid: string | null }, { othercost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  overriddencreatedon: WebAttribute<Campaign_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Campaign_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Campaign_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Campaign_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Campaign_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  pricelistid_guid: WebAttribute<Campaign_Select, { pricelistid_guid: string | null }, { pricelistid_formatted?: string }>;
  processid: WebAttribute<Campaign_Select, { processid: string | null }, {  }>;
  promotioncodename: WebAttribute<Campaign_Select, { promotioncodename: string | null }, {  }>;
  proposedend: WebAttribute<Campaign_Select, { proposedend: Date | null }, { proposedend_formatted?: string }>;
  proposedstart: WebAttribute<Campaign_Select, { proposedstart: Date | null }, { proposedstart_formatted?: string }>;
  stageid: WebAttribute<Campaign_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Campaign_Select, { statecode: campaign_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Campaign_Select, { statuscode: campaign_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<Campaign_Select, { timezoneruleversionnumber: number | null }, {  }>;
  tmpregardingobjectid: WebAttribute<Campaign_Select, { tmpregardingobjectid: string | null }, {  }>;
  totalactualcost: WebAttribute<Campaign_Select, { totalactualcost: number | null; transactioncurrencyid_guid: string | null }, { totalactualcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totalactualcost_base: WebAttribute<Campaign_Select, { totalactualcost_base: number | null; transactioncurrencyid_guid: string | null }, { totalactualcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totalcampaignactivityactualcost: WebAttribute<Campaign_Select, { totalcampaignactivityactualcost: number | null; transactioncurrencyid_guid: string | null }, { totalcampaignactivityactualcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totalcampaignactivityactualcost_base: WebAttribute<Campaign_Select, { totalcampaignactivityactualcost_base: number | null; transactioncurrencyid_guid: string | null }, { totalcampaignactivityactualcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<Campaign_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Campaign_Select, { traversedpath: string | null }, {  }>;
  typecode: WebAttribute<Campaign_Select, { typecode: campaign_typecode | null }, { typecode_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<Campaign_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Campaign_Select, { versionnumber: number | null }, {  }>;
}
interface Campaign_Filter {
  actualend: Date;
  actualstart: Date;
  budgetedcost: number;
  budgetedcost_base: number;
  campaignid: XQW.Guid;
  codename: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  emailaddress: string;
  entityimageid: XQW.Guid;
  exchangerate: any;
  expectedresponse: number;
  expectedrevenue: number;
  expectedrevenue_base: number;
  importsequencenumber: number;
  istemplate: boolean;
  message: string;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  name: string;
  objective: string;
  othercost: number;
  othercost_base: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  pricelistid_guid: XQW.Guid;
  processid: XQW.Guid;
  promotioncodename: string;
  proposedend: Date;
  proposedstart: Date;
  stageid: XQW.Guid;
  statecode: campaign_statecode;
  statuscode: campaign_statuscode;
  timezoneruleversionnumber: number;
  tmpregardingobjectid: string;
  totalactualcost: number;
  totalactualcost_base: number;
  totalcampaignactivityactualcost: number;
  totalcampaignactivityactualcost_base: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  typecode: campaign_typecode;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface Campaign_Expand {
  Campaign_ActivityPointers: WebExpand<Campaign_Expand, ActivityPointer_Select, ActivityPointer_Filter, { Campaign_ActivityPointers: ActivityPointer_Result[] }>;
  Campaign_Annotation: WebExpand<Campaign_Expand, Annotation_Select, Annotation_Filter, { Campaign_Annotation: Annotation_Result[] }>;
  Campaign_Appointments: WebExpand<Campaign_Expand, Appointment_Select, Appointment_Filter, { Campaign_Appointments: Appointment_Result[] }>;
  Campaign_AsyncOperations: WebExpand<Campaign_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Campaign_AsyncOperations: AsyncOperation_Result[] }>;
  Campaign_BulkDeleteFailures: WebExpand<Campaign_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Campaign_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Campaign_CampaignActivities: WebExpand<Campaign_Expand, CampaignActivity_Select, CampaignActivity_Filter, { Campaign_CampaignActivities: CampaignActivity_Result[] }>;
  Campaign_CampaignResponses: WebExpand<Campaign_Expand, CampaignResponse_Select, CampaignResponse_Filter, { Campaign_CampaignResponses: CampaignResponse_Result[] }>;
  Campaign_DuplicateBaseRecord: WebExpand<Campaign_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Campaign_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Campaign_DuplicateMatchingRecord: WebExpand<Campaign_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Campaign_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Campaign_Emails: WebExpand<Campaign_Expand, Email_Select, Email_Filter, { Campaign_Emails: Email_Result[] }>;
  Campaign_Faxes: WebExpand<Campaign_Expand, Fax_Select, Fax_Filter, { Campaign_Faxes: Fax_Result[] }>;
  Campaign_Letters: WebExpand<Campaign_Expand, Letter_Select, Letter_Filter, { Campaign_Letters: Letter_Result[] }>;
  Campaign_MailboxTrackingFolder: WebExpand<Campaign_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { Campaign_MailboxTrackingFolder: MailboxTrackingFolder_Result[] }>;
  Campaign_Phonecalls: WebExpand<Campaign_Expand, PhoneCall_Select, PhoneCall_Filter, { Campaign_Phonecalls: PhoneCall_Result[] }>;
  Campaign_ProcessSessions: WebExpand<Campaign_Expand, ProcessSession_Select, ProcessSession_Filter, { Campaign_ProcessSessions: ProcessSession_Result[] }>;
  Campaign_RecurringAppointmentMasters: WebExpand<Campaign_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { Campaign_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  Campaign_ServiceAppointments: WebExpand<Campaign_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { Campaign_ServiceAppointments: ServiceAppointment_Result[] }>;
  Campaign_SyncErrors: WebExpand<Campaign_Expand, SyncError_Select, SyncError_Filter, { Campaign_SyncErrors: SyncError_Result[] }>;
  Campaign_Tasks: WebExpand<Campaign_Expand, Task_Select, Task_Filter, { Campaign_Tasks: Task_Result[] }>;
  campaign_IncidentResolutions: WebExpand<Campaign_Expand, IncidentResolution_Select, IncidentResolution_Filter, { campaign_IncidentResolutions: IncidentResolution_Result[] }>;
  campaign_OpportunityCloses: WebExpand<Campaign_Expand, OpportunityClose_Select, OpportunityClose_Filter, { campaign_OpportunityCloses: OpportunityClose_Result[] }>;
  campaign_OrderCloses: WebExpand<Campaign_Expand, OrderClose_Select, OrderClose_Filter, { campaign_OrderCloses: OrderClose_Result[] }>;
  campaign_QuoteCloses: WebExpand<Campaign_Expand, QuoteClose_Select, QuoteClose_Filter, { campaign_QuoteCloses: QuoteClose_Result[] }>;
  campaign_SocialActivities: WebExpand<Campaign_Expand, SocialActivity_Select, SocialActivity_Filter, { campaign_SocialActivities: SocialActivity_Result[] }>;
  campaign_activity_parties: WebExpand<Campaign_Expand, ActivityParty_Select, ActivityParty_Filter, { campaign_activity_parties: ActivityParty_Result[] }>;
  campaign_connections1: WebExpand<Campaign_Expand, Connection_Select, Connection_Filter, { campaign_connections1: Connection_Result[] }>;
  campaign_connections2: WebExpand<Campaign_Expand, Connection_Select, Connection_Filter, { campaign_connections2: Connection_Result[] }>;
  campaign_leads: WebExpand<Campaign_Expand, Lead_Select, Lead_Filter, { campaign_leads: Lead_Result[] }>;
  campaign_msdyn_approvals: WebExpand<Campaign_Expand, msdyn_approval_Select, msdyn_approval_Filter, { campaign_msdyn_approvals: msdyn_approval_Result[] }>;
  campaign_msdyn_bookingalerts: WebExpand<Campaign_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { campaign_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  campaign_msdyn_ocliveworkitems: WebExpand<Campaign_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { campaign_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  campaign_msdyn_ocoutboundmessages: WebExpand<Campaign_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { campaign_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  campaign_msdyn_ocsessions: WebExpand<Campaign_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { campaign_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  campaign_msfp_alerts: WebExpand<Campaign_Expand, msfp_alert_Select, msfp_alert_Filter, { campaign_msfp_alerts: msfp_alert_Result[] }>;
  campaign_msfp_surveyinvites: WebExpand<Campaign_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { campaign_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  campaign_msfp_surveyresponses: WebExpand<Campaign_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { campaign_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  campaign_opportunities: WebExpand<Campaign_Expand, Opportunity_Select, Opportunity_Filter, { campaign_opportunities: Opportunity_Result[] }>;
  campaign_orders: WebExpand<Campaign_Expand, SalesOrder_Select, SalesOrder_Filter, { campaign_orders: SalesOrder_Result[] }>;
  campaign_principalobjectattributeaccess: WebExpand<Campaign_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { campaign_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  campaign_quotes: WebExpand<Campaign_Expand, Quote_Select, Quote_Filter, { campaign_quotes: Quote_Result[] }>;
  campaigncampaign_association: WebExpand<Campaign_Expand, Campaign_Select, Campaign_Filter, { campaigncampaign_association: Campaign_Result[] }>;
  campaignlist_association: WebExpand<Campaign_Expand, List_Select, List_Filter, { campaignlist_association: List_Result[] }>;
  campaignproduct_association: WebExpand<Campaign_Expand, Product_Select, Product_Filter, { campaignproduct_association: Product_Result[] }>;
  campaignsalesliterature_association: WebExpand<Campaign_Expand, SalesLiterature_Select, SalesLiterature_Filter, { campaignsalesliterature_association: SalesLiterature_Result[] }>;
  createdby: WebExpand<Campaign_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Campaign_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  entityimageid_imagedescriptor: WebExpand<Campaign_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  modifiedby: WebExpand<Campaign_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Campaign_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  ownerid: WebExpand<Campaign_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<Campaign_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<Campaign_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<Campaign_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  pricelistid: WebExpand<Campaign_Expand, PriceLevel_Select, PriceLevel_Filter, { pricelistid: PriceLevel_Result }>;
  stageid_processstage: WebExpand<Campaign_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid: WebExpand<Campaign_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_campaign: WebExpand<Campaign_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_campaign: UserEntityInstanceData_Result[] }>;
}
interface Campaign_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  budgetedcost_base_formatted?: string;
  budgetedcost_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  expectedrevenue_base_formatted?: string;
  expectedrevenue_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  othercost_base_formatted?: string;
  othercost_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  pricelistid_formatted?: string;
  proposedend_formatted?: string;
  proposedstart_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  totalactualcost_base_formatted?: string;
  totalactualcost_formatted?: string;
  totalcampaignactivityactualcost_base_formatted?: string;
  totalcampaignactivityactualcost_formatted?: string;
  transactioncurrencyid_formatted?: string;
  typecode_formatted?: string;
}
interface Campaign_Result extends Campaign_Base, Campaign_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  pricelistid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Campaign_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  pricelistid: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Campaign_RelatedMany {
  Campaign_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  Campaign_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Campaign_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  Campaign_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Campaign_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Campaign_CampaignActivities: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  Campaign_CampaignResponses: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  Campaign_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Campaign_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Campaign_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  Campaign_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  Campaign_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  Campaign_MailboxTrackingFolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  Campaign_Phonecalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  Campaign_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Campaign_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  Campaign_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  Campaign_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  Campaign_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  campaign_IncidentResolutions: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  campaign_OpportunityCloses: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  campaign_OrderCloses: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  campaign_QuoteCloses: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  campaign_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  campaign_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  campaign_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  campaign_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  campaign_leads: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  campaign_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  campaign_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  campaign_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  campaign_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  campaign_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  campaign_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  campaign_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  campaign_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  campaign_opportunities: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  campaign_orders: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  campaign_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  campaign_quotes: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  campaigncampaign_association: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  campaignlist_association: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  campaignproduct_association: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  campaignsalesliterature_association: WebMappingRetrieve<SalesLiterature_Select,SalesLiterature_Expand,SalesLiterature_Filter,SalesLiterature_Fixed,SalesLiterature_Result,SalesLiterature_FormattedResult>;
  userentityinstancedata_campaign: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  campaigns: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
}
interface WebEntitiesRelated {
  campaigns: WebMappingRelated<Campaign_RelatedOne,Campaign_RelatedMany>;
}
interface WebEntitiesCUDA {
  campaigns: WebMappingCUDA<Campaign_Create,Campaign_Update,Campaign_Select>;
}
