interface CampaignActivity_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualcost?: number | null;
  actualcost_base?: number | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  budgetedcost?: number | null;
  budgetedcost_base?: number | null;
  category?: string | null;
  channeltypecode?: campaignactivity_channeltypecode | null;
  community?: socialprofile_community | null;
  createdon?: Date | null;
  deliverylastattemptedon?: Date | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  description?: string | null;
  donotsendonoptout?: boolean | null;
  exchangeitemid?: string | null;
  exchangerate?: number | null;
  exchangeweblink?: string | null;
  excludeifcontactedinxdays?: number | null;
  ignoreinactivelistmembers?: boolean | null;
  importsequencenumber?: number | null;
  instancetypecode?: _campaignactivity_instancetypecode | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  postponeactivityprocessinguntil?: Date | null;
  prioritycode?: campaignactivity_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  senton?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: campaignactivity_statecode | null;
  statuscode?: campaignactivity_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  typecode?: campaignactivity_typecode | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface CampaignActivity_Relationships {
  CampaignActivity_ActivityPointers?: ActivityPointer_Result[] | null;
  CampaignActivity_Annotation?: Annotation_Result[] | null;
  CampaignActivity_Appointments?: Appointment_Result[] | null;
  CampaignActivity_AsyncOperations?: AsyncOperation_Result[] | null;
  CampaignActivity_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  CampaignActivity_BulkOperations?: BulkOperation_Result[] | null;
  CampaignActivity_Emails?: Email_Result[] | null;
  CampaignActivity_Faxes?: Fax_Result[] | null;
  CampaignActivity_Letters?: Letter_Result[] | null;
  CampaignActivity_Logs_Accounts?: Account_Result[] | null;
  CampaignActivity_Logs_Contacts?: Contact_Result[] | null;
  CampaignActivity_Logs_Leads?: Lead_Result[] | null;
  CampaignActivity_MailboxTrackingFolder?: MailboxTrackingFolder_Result[] | null;
  CampaignActivity_Phonecalls?: PhoneCall_Result[] | null;
  CampaignActivity_ProcessSessions?: ProcessSession_Result[] | null;
  CampaignActivity_QueueItem?: QueueItem_Result[] | null;
  CampaignActivity_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  CampaignActivity_SyncErrors?: SyncError_Result[] | null;
  CampaignActivity_Tasks?: Task_Result[] | null;
  CampaignActivity_logs?: BulkOperationLog_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  campaignactivity_CampaignResponses?: CampaignResponse_Result[] | null;
  campaignactivity_IncidentResolutions?: IncidentResolution_Result[] | null;
  campaignactivity_OpportunityCloses?: OpportunityClose_Result[] | null;
  campaignactivity_OrderCloses?: OrderClose_Result[] | null;
  campaignactivity_QuoteCloses?: QuoteClose_Result[] | null;
  campaignactivity_ServiceAppointments?: ServiceAppointment_Result[] | null;
  campaignactivity_SocialActivities?: SocialActivity_Result[] | null;
  campaignactivity_activity_parties?: ActivityParty_Result[] | null;
  campaignactivity_activityparties?: ActivityParty_Result[] | null;
  campaignactivity_connections1?: Connection_Result[] | null;
  campaignactivity_connections2?: Connection_Result[] | null;
  campaignactivity_msdyn_approvals?: msdyn_approval_Result[] | null;
  campaignactivity_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  campaignactivity_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  campaignactivity_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  campaignactivity_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  campaignactivity_msfp_alerts?: msfp_alert_Result[] | null;
  campaignactivity_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  campaignactivity_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  campaignactivity_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  campaignactivitylist_association?: List_Result[] | null;
  campaignactivitysalesliterature_association?: SalesLiterature_Result[] | null;
  createdby_campaignactivity?: SystemUser_Result | null;
  createdonbehalfby_campaignactivity?: SystemUser_Result | null;
  modifiedby_campaignactivity?: SystemUser_Result | null;
  modifiedonbehalfby_campaignactivity?: SystemUser_Result | null;
  ownerid_campaignactivity?: Team_Result | null;
  ownerid_campaignactivity1?: SystemUser_Result | null;
  owningbusinessunit_campaignactivity?: BusinessUnit_Result | null;
  owningteam_campaignactivity?: Team_Result | null;
  owninguser_campaignactivity?: SystemUser_Result | null;
  regardingobjectid_bookableresourcebooking_campaignactivity?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_campaignactivity?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_campaign_campaignactivity?: Campaign_Result | null;
  sendermailboxid_campaignactivity?: Mailbox_Result | null;
  sla_activitypointer_sla_campaignactivity?: SLA_Result | null;
  slainvokedid_activitypointer_sla_campaignactivity?: SLA_Result | null;
  stageid_processstage?: ProcessStage_Result | null;
  transactioncurrencyid_campaignactivity?: TransactionCurrency_Result | null;
  userentityinstancedata_campaignactivity?: UserEntityInstanceData_Result[] | null;
}
interface CampaignActivity extends CampaignActivity_Base, CampaignActivity_Relationships {
  ownerid_campaignactivity_bind$systemusers?: string | null;
  ownerid_campaignactivity_bind$teams?: string | null;
  sla_activitypointer_sla_campaignactivity_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
}
interface CampaignActivity_Create extends CampaignActivity {
  activityid_activitypointer_bind$activitypointers?: string | null;
  regardingobjectid_bookableresourcebooking_campaignactivity_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_campaignactivity_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_campaign_campaignactivity_bind$campaigns?: string | null;
}
interface CampaignActivity_Update extends CampaignActivity {
}
interface CampaignActivity_Select {
  activityadditionalparams: WebAttribute<CampaignActivity_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<CampaignActivity_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<CampaignActivity_Select, { activitytypecode: string | null }, {  }>;
  actualcost: WebAttribute<CampaignActivity_Select, { actualcost: number | null; transactioncurrencyid_guid: string | null }, { actualcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  actualcost_base: WebAttribute<CampaignActivity_Select, { actualcost_base: number | null; transactioncurrencyid_guid: string | null }, { actualcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  actualdurationminutes: WebAttribute<CampaignActivity_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<CampaignActivity_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<CampaignActivity_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  bcc_guid: WebAttribute<CampaignActivity_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
  budgetedcost: WebAttribute<CampaignActivity_Select, { budgetedcost: number | null; transactioncurrencyid_guid: string | null }, { budgetedcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  budgetedcost_base: WebAttribute<CampaignActivity_Select, { budgetedcost_base: number | null; transactioncurrencyid_guid: string | null }, { budgetedcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  category: WebAttribute<CampaignActivity_Select, { category: string | null }, {  }>;
  cc_guid: WebAttribute<CampaignActivity_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
  channeltypecode: WebAttribute<CampaignActivity_Select, { channeltypecode: campaignactivity_channeltypecode | null }, { channeltypecode_formatted?: string }>;
  community: WebAttribute<CampaignActivity_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  createdby_guid: WebAttribute<CampaignActivity_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<CampaignActivity_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<CampaignActivity_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  customers_guid: WebAttribute<CampaignActivity_Select, { customers_guid: string | null }, { customers_formatted?: string }>;
  deliverylastattemptedon: WebAttribute<CampaignActivity_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
  deliveryprioritycode: WebAttribute<CampaignActivity_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  description: WebAttribute<CampaignActivity_Select, { description: string | null }, {  }>;
  donotsendonoptout: WebAttribute<CampaignActivity_Select, { donotsendonoptout: boolean | null }, {  }>;
  exchangeitemid: WebAttribute<CampaignActivity_Select, { exchangeitemid: string | null }, {  }>;
  exchangerate: WebAttribute<CampaignActivity_Select, { exchangerate: number | null }, {  }>;
  exchangeweblink: WebAttribute<CampaignActivity_Select, { exchangeweblink: string | null }, {  }>;
  excludeifcontactedinxdays: WebAttribute<CampaignActivity_Select, { excludeifcontactedinxdays: number | null }, {  }>;
  from_guid: WebAttribute<CampaignActivity_Select, { from_guid: string | null }, { from_formatted?: string }>;
  ignoreinactivelistmembers: WebAttribute<CampaignActivity_Select, { ignoreinactivelistmembers: boolean | null }, {  }>;
  importsequencenumber: WebAttribute<CampaignActivity_Select, { importsequencenumber: number | null }, {  }>;
  instancetypecode: WebAttribute<CampaignActivity_Select, { instancetypecode: _campaignactivity_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isbilled: WebAttribute<CampaignActivity_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<CampaignActivity_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<CampaignActivity_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<CampaignActivity_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<CampaignActivity_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<CampaignActivity_Select, { leftvoicemail: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<CampaignActivity_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<CampaignActivity_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<CampaignActivity_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<CampaignActivity_Select, { onholdtime: number | null }, {  }>;
  optionalattendees_guid: WebAttribute<CampaignActivity_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<CampaignActivity_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  overriddencreatedon: WebAttribute<CampaignActivity_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<CampaignActivity_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<CampaignActivity_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<CampaignActivity_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<CampaignActivity_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  partners_guid: WebAttribute<CampaignActivity_Select, { partners_guid: string | null }, { partners_formatted?: string }>;
  postponeactivityprocessinguntil: WebAttribute<CampaignActivity_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<CampaignActivity_Select, { prioritycode: campaignactivity_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<CampaignActivity_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<CampaignActivity_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<CampaignActivity_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  resources_guid: WebAttribute<CampaignActivity_Select, { resources_guid: string | null }, { resources_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<CampaignActivity_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<CampaignActivity_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<CampaignActivity_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sendermailboxid_guid: WebAttribute<CampaignActivity_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  senton: WebAttribute<CampaignActivity_Select, { senton: Date | null }, { senton_formatted?: string }>;
  seriesid: WebAttribute<CampaignActivity_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<CampaignActivity_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<CampaignActivity_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<CampaignActivity_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<CampaignActivity_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<CampaignActivity_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<CampaignActivity_Select, { statecode: campaignactivity_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<CampaignActivity_Select, { statuscode: campaignactivity_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<CampaignActivity_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<CampaignActivity_Select, { subject: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<CampaignActivity_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<CampaignActivity_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<CampaignActivity_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<CampaignActivity_Select, { traversedpath: string | null }, {  }>;
  typecode: WebAttribute<CampaignActivity_Select, { typecode: campaignactivity_typecode | null }, { typecode_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<CampaignActivity_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<CampaignActivity_Select, { versionnumber: number | null }, {  }>;
}
interface CampaignActivity_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualcost: number;
  actualcost_base: number;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  bcc_guid: XQW.Guid;
  budgetedcost: number;
  budgetedcost_base: number;
  category: string;
  cc_guid: XQW.Guid;
  channeltypecode: campaignactivity_channeltypecode;
  community: socialprofile_community;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  customers_guid: XQW.Guid;
  deliverylastattemptedon: Date;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  description: string;
  donotsendonoptout: boolean;
  exchangeitemid: string;
  exchangerate: any;
  exchangeweblink: string;
  excludeifcontactedinxdays: number;
  from_guid: XQW.Guid;
  ignoreinactivelistmembers: boolean;
  importsequencenumber: number;
  instancetypecode: _campaignactivity_instancetypecode;
  isbilled: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  partners_guid: XQW.Guid;
  postponeactivityprocessinguntil: Date;
  prioritycode: campaignactivity_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  resources_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sendermailboxid_guid: XQW.Guid;
  senton: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: campaignactivity_statecode;
  statuscode: campaignactivity_statuscode;
  subcategory: string;
  subject: string;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  typecode: campaignactivity_typecode;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface CampaignActivity_Expand {
  CampaignActivity_ActivityPointers: WebExpand<CampaignActivity_Expand, ActivityPointer_Select, ActivityPointer_Filter, { CampaignActivity_ActivityPointers: ActivityPointer_Result[] }>;
  CampaignActivity_Annotation: WebExpand<CampaignActivity_Expand, Annotation_Select, Annotation_Filter, { CampaignActivity_Annotation: Annotation_Result[] }>;
  CampaignActivity_Appointments: WebExpand<CampaignActivity_Expand, Appointment_Select, Appointment_Filter, { CampaignActivity_Appointments: Appointment_Result[] }>;
  CampaignActivity_AsyncOperations: WebExpand<CampaignActivity_Expand, AsyncOperation_Select, AsyncOperation_Filter, { CampaignActivity_AsyncOperations: AsyncOperation_Result[] }>;
  CampaignActivity_BulkDeleteFailures: WebExpand<CampaignActivity_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { CampaignActivity_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  CampaignActivity_BulkOperations: WebExpand<CampaignActivity_Expand, BulkOperation_Select, BulkOperation_Filter, { CampaignActivity_BulkOperations: BulkOperation_Result[] }>;
  CampaignActivity_Emails: WebExpand<CampaignActivity_Expand, Email_Select, Email_Filter, { CampaignActivity_Emails: Email_Result[] }>;
  CampaignActivity_Faxes: WebExpand<CampaignActivity_Expand, Fax_Select, Fax_Filter, { CampaignActivity_Faxes: Fax_Result[] }>;
  CampaignActivity_Letters: WebExpand<CampaignActivity_Expand, Letter_Select, Letter_Filter, { CampaignActivity_Letters: Letter_Result[] }>;
  CampaignActivity_Logs_Accounts: WebExpand<CampaignActivity_Expand, Account_Select, Account_Filter, { CampaignActivity_Logs_Accounts: Account_Result[] }>;
  CampaignActivity_Logs_Contacts: WebExpand<CampaignActivity_Expand, Contact_Select, Contact_Filter, { CampaignActivity_Logs_Contacts: Contact_Result[] }>;
  CampaignActivity_Logs_Leads: WebExpand<CampaignActivity_Expand, Lead_Select, Lead_Filter, { CampaignActivity_Logs_Leads: Lead_Result[] }>;
  CampaignActivity_MailboxTrackingFolder: WebExpand<CampaignActivity_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { CampaignActivity_MailboxTrackingFolder: MailboxTrackingFolder_Result[] }>;
  CampaignActivity_Phonecalls: WebExpand<CampaignActivity_Expand, PhoneCall_Select, PhoneCall_Filter, { CampaignActivity_Phonecalls: PhoneCall_Result[] }>;
  CampaignActivity_ProcessSessions: WebExpand<CampaignActivity_Expand, ProcessSession_Select, ProcessSession_Filter, { CampaignActivity_ProcessSessions: ProcessSession_Result[] }>;
  CampaignActivity_QueueItem: WebExpand<CampaignActivity_Expand, QueueItem_Select, QueueItem_Filter, { CampaignActivity_QueueItem: QueueItem_Result[] }>;
  CampaignActivity_RecurringAppointmentMasters: WebExpand<CampaignActivity_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { CampaignActivity_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  CampaignActivity_SyncErrors: WebExpand<CampaignActivity_Expand, SyncError_Select, SyncError_Filter, { CampaignActivity_SyncErrors: SyncError_Result[] }>;
  CampaignActivity_Tasks: WebExpand<CampaignActivity_Expand, Task_Select, Task_Filter, { CampaignActivity_Tasks: Task_Result[] }>;
  CampaignActivity_logs: WebExpand<CampaignActivity_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { CampaignActivity_logs: BulkOperationLog_Result[] }>;
  activityid_activitypointer: WebExpand<CampaignActivity_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  campaignactivity_CampaignResponses: WebExpand<CampaignActivity_Expand, CampaignResponse_Select, CampaignResponse_Filter, { campaignactivity_CampaignResponses: CampaignResponse_Result[] }>;
  campaignactivity_IncidentResolutions: WebExpand<CampaignActivity_Expand, IncidentResolution_Select, IncidentResolution_Filter, { campaignactivity_IncidentResolutions: IncidentResolution_Result[] }>;
  campaignactivity_OpportunityCloses: WebExpand<CampaignActivity_Expand, OpportunityClose_Select, OpportunityClose_Filter, { campaignactivity_OpportunityCloses: OpportunityClose_Result[] }>;
  campaignactivity_OrderCloses: WebExpand<CampaignActivity_Expand, OrderClose_Select, OrderClose_Filter, { campaignactivity_OrderCloses: OrderClose_Result[] }>;
  campaignactivity_QuoteCloses: WebExpand<CampaignActivity_Expand, QuoteClose_Select, QuoteClose_Filter, { campaignactivity_QuoteCloses: QuoteClose_Result[] }>;
  campaignactivity_ServiceAppointments: WebExpand<CampaignActivity_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { campaignactivity_ServiceAppointments: ServiceAppointment_Result[] }>;
  campaignactivity_SocialActivities: WebExpand<CampaignActivity_Expand, SocialActivity_Select, SocialActivity_Filter, { campaignactivity_SocialActivities: SocialActivity_Result[] }>;
  campaignactivity_activity_parties: WebExpand<CampaignActivity_Expand, ActivityParty_Select, ActivityParty_Filter, { campaignactivity_activity_parties: ActivityParty_Result[] }>;
  campaignactivity_activityparties: WebExpand<CampaignActivity_Expand, ActivityParty_Select, ActivityParty_Filter, { campaignactivity_activityparties: ActivityParty_Result[] }>;
  campaignactivity_connections1: WebExpand<CampaignActivity_Expand, Connection_Select, Connection_Filter, { campaignactivity_connections1: Connection_Result[] }>;
  campaignactivity_connections2: WebExpand<CampaignActivity_Expand, Connection_Select, Connection_Filter, { campaignactivity_connections2: Connection_Result[] }>;
  campaignactivity_msdyn_approvals: WebExpand<CampaignActivity_Expand, msdyn_approval_Select, msdyn_approval_Filter, { campaignactivity_msdyn_approvals: msdyn_approval_Result[] }>;
  campaignactivity_msdyn_bookingalerts: WebExpand<CampaignActivity_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { campaignactivity_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  campaignactivity_msdyn_ocliveworkitems: WebExpand<CampaignActivity_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { campaignactivity_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  campaignactivity_msdyn_ocoutboundmessages: WebExpand<CampaignActivity_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { campaignactivity_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  campaignactivity_msdyn_ocsessions: WebExpand<CampaignActivity_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { campaignactivity_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  campaignactivity_msfp_alerts: WebExpand<CampaignActivity_Expand, msfp_alert_Select, msfp_alert_Filter, { campaignactivity_msfp_alerts: msfp_alert_Result[] }>;
  campaignactivity_msfp_surveyinvites: WebExpand<CampaignActivity_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { campaignactivity_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  campaignactivity_msfp_surveyresponses: WebExpand<CampaignActivity_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { campaignactivity_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  campaignactivity_principalobjectattributeaccess: WebExpand<CampaignActivity_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { campaignactivity_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  campaignactivitylist_association: WebExpand<CampaignActivity_Expand, List_Select, List_Filter, { campaignactivitylist_association: List_Result[] }>;
  campaignactivitysalesliterature_association: WebExpand<CampaignActivity_Expand, SalesLiterature_Select, SalesLiterature_Filter, { campaignactivitysalesliterature_association: SalesLiterature_Result[] }>;
  createdby_campaignactivity: WebExpand<CampaignActivity_Expand, SystemUser_Select, SystemUser_Filter, { createdby_campaignactivity: SystemUser_Result }>;
  createdonbehalfby_campaignactivity: WebExpand<CampaignActivity_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_campaignactivity: SystemUser_Result }>;
  modifiedby_campaignactivity: WebExpand<CampaignActivity_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_campaignactivity: SystemUser_Result }>;
  modifiedonbehalfby_campaignactivity: WebExpand<CampaignActivity_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_campaignactivity: SystemUser_Result }>;
  ownerid_campaignactivity: WebExpand<CampaignActivity_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_campaignactivity: SystemUser_Result } & { ownerid_campaignactivity: Team_Result }>;
  owningbusinessunit_campaignactivity: WebExpand<CampaignActivity_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_campaignactivity: BusinessUnit_Result }>;
  owningteam_campaignactivity: WebExpand<CampaignActivity_Expand, Team_Select, Team_Filter, { owningteam_campaignactivity: Team_Result }>;
  owninguser_campaignactivity: WebExpand<CampaignActivity_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_campaignactivity: SystemUser_Result }>;
  regardingobjectid_bookableresourcebooking_campaignactivity: WebExpand<CampaignActivity_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_campaignactivity: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_campaignactivity: WebExpand<CampaignActivity_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_campaignactivity: BookableResourceBookingHeader_Result }>;
  regardingobjectid_campaign_campaignactivity: WebExpand<CampaignActivity_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_campaignactivity: Campaign_Result }>;
  sendermailboxid_campaignactivity: WebExpand<CampaignActivity_Expand, Mailbox_Select, Mailbox_Filter, { sendermailboxid_campaignactivity: Mailbox_Result }>;
  sla_activitypointer_sla_campaignactivity: WebExpand<CampaignActivity_Expand, SLA_Select, SLA_Filter, { sla_activitypointer_sla_campaignactivity: SLA_Result }>;
  slainvokedid_activitypointer_sla_campaignactivity: WebExpand<CampaignActivity_Expand, SLA_Select, SLA_Filter, { slainvokedid_activitypointer_sla_campaignactivity: SLA_Result }>;
  stageid_processstage: WebExpand<CampaignActivity_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid_campaignactivity: WebExpand<CampaignActivity_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_campaignactivity: TransactionCurrency_Result }>;
  userentityinstancedata_campaignactivity: WebExpand<CampaignActivity_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_campaignactivity: UserEntityInstanceData_Result[] }>;
}
interface CampaignActivity_FormattedResult {
  actualcost_base_formatted?: string;
  actualcost_formatted?: string;
  actualend_formatted?: string;
  actualstart_formatted?: string;
  bcc_formatted?: string;
  budgetedcost_base_formatted?: string;
  budgetedcost_formatted?: string;
  cc_formatted?: string;
  channeltypecode_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  customers_formatted?: string;
  deliverylastattemptedon_formatted?: string;
  deliveryprioritycode_formatted?: string;
  from_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  partners_formatted?: string;
  postponeactivityprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  resources_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
  typecode_formatted?: string;
}
interface CampaignActivity_Result extends CampaignActivity_Base, CampaignActivity_Relationships {
  "@odata.etag": string;
  bcc_guid: string | null;
  cc_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  customers_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  partners_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  resources_guid: string | null;
  sendermailboxid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface CampaignActivity_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_campaignactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_campaignactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_campaignactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_campaignactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_campaignactivity: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_campaignactivity1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_campaignactivity: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_campaignactivity: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_campaignactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_bookableresourcebooking_campaignactivity: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_campaignactivity: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_campaign_campaignactivity: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  sendermailboxid_campaignactivity: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  sla_activitypointer_sla_campaignactivity: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_activitypointer_sla_campaignactivity: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_campaignactivity: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface CampaignActivity_RelatedMany {
  CampaignActivity_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  CampaignActivity_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  CampaignActivity_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  CampaignActivity_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  CampaignActivity_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  CampaignActivity_BulkOperations: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  CampaignActivity_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  CampaignActivity_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  CampaignActivity_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  CampaignActivity_Logs_Accounts: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  CampaignActivity_Logs_Contacts: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  CampaignActivity_Logs_Leads: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  CampaignActivity_MailboxTrackingFolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  CampaignActivity_Phonecalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  CampaignActivity_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  CampaignActivity_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  CampaignActivity_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  CampaignActivity_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  CampaignActivity_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  CampaignActivity_logs: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  campaignactivity_CampaignResponses: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  campaignactivity_IncidentResolutions: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  campaignactivity_OpportunityCloses: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  campaignactivity_OrderCloses: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  campaignactivity_QuoteCloses: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  campaignactivity_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  campaignactivity_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  campaignactivity_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  campaignactivity_activityparties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  campaignactivity_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  campaignactivity_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  campaignactivity_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  campaignactivity_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  campaignactivity_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  campaignactivity_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  campaignactivity_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  campaignactivity_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  campaignactivity_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  campaignactivity_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  campaignactivity_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  campaignactivitylist_association: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  campaignactivitysalesliterature_association: WebMappingRetrieve<SalesLiterature_Select,SalesLiterature_Expand,SalesLiterature_Filter,SalesLiterature_Fixed,SalesLiterature_Result,SalesLiterature_FormattedResult>;
  userentityinstancedata_campaignactivity: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  campaignactivities: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
}
interface WebEntitiesRelated {
  campaignactivities: WebMappingRelated<CampaignActivity_RelatedOne,CampaignActivity_RelatedMany>;
}
interface WebEntitiesCUDA {
  campaignactivities: WebMappingCUDA<CampaignActivity_Create,CampaignActivity_Update,CampaignActivity_Select>;
}
