interface CampaignResponse_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  category?: string | null;
  channeltypecode?: campaignresponse_channeltypecode | null;
  community?: socialprofile_community | null;
  companyname?: string | null;
  createdon?: Date | null;
  deliverylastattemptedon?: Date | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  description?: string | null;
  emailaddress?: string | null;
  exchangeitemid?: string | null;
  exchangerate?: number | null;
  exchangeweblink?: string | null;
  fax?: string | null;
  firstname?: string | null;
  importsequencenumber?: number | null;
  instancetypecode?: _campaignresponse_instancetypecode | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastname?: string | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  postponeactivityprocessinguntil?: Date | null;
  prioritycode?: campaignresponse_prioritycode | null;
  processid?: string | null;
  promotioncodename?: string | null;
  receivedon?: Date | null;
  responsecode?: campaignresponse_responsecode | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  senton?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: campaignresponse_statecode | null;
  statuscode?: campaignresponse_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  telephone?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface CampaignResponse_Relationships {
  CampaignResponse_Annotation?: Annotation_Result[] | null;
  CampaignResponse_AsyncOperations?: AsyncOperation_Result[] | null;
  CampaignResponse_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  CampaignResponse_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  CampaignResponse_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  CampaignResponse_Lead?: Lead_Result[] | null;
  CampaignResponse_ProcessSessions?: ProcessSession_Result[] | null;
  CampaignResponse_QueueItem?: QueueItem_Result[] | null;
  CampaignResponse_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  campaignresponse_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  campaignresponse_activity_parties?: ActivityParty_Result[] | null;
  campaignresponse_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  createdby_campaignresponse?: SystemUser_Result | null;
  createdonbehalfby_campaignresponse?: SystemUser_Result | null;
  modifiedby_campaignresponse?: SystemUser_Result | null;
  modifiedonbehalfby_campaignresponse?: SystemUser_Result | null;
  originatingactivityid_activitypointer?: ActivityPointer_Result | null;
  originatingactivityid_appointment?: Appointment_Result | null;
  originatingactivityid_email?: Email_Result | null;
  originatingactivityid_fax?: Fax_Result | null;
  originatingactivityid_incidentresolution_campaignresponse?: IncidentResolution_Result | null;
  originatingactivityid_letter?: Letter_Result | null;
  originatingactivityid_msdyn_approval_campaignresponse?: msdyn_approval_Result | null;
  originatingactivityid_msdyn_bookingalert_campaignresponse?: msdyn_bookingalert_Result | null;
  originatingactivityid_msdyn_ocliveworkitem_campaignresponse?: msdyn_ocliveworkitem_Result | null;
  originatingactivityid_msdyn_ocoutboundmessage_campaignresponse?: msdyn_ocoutboundmessage_Result | null;
  originatingactivityid_msdyn_ocsession_campaignresponse?: msdyn_ocsession_Result | null;
  originatingactivityid_msfp_alert_campaignresponse?: msfp_alert_Result | null;
  originatingactivityid_msfp_surveyinvite_campaignresponse?: msfp_surveyinvite_Result | null;
  originatingactivityid_msfp_surveyresponse_campaignresponse?: msfp_surveyresponse_Result | null;
  originatingactivityid_opportunityclose_campaignresponse?: OpportunityClose_Result | null;
  originatingactivityid_orderclose_campaignresponse?: OrderClose_Result | null;
  originatingactivityid_phonecall?: PhoneCall_Result | null;
  originatingactivityid_quoteclose_campaignresponse?: QuoteClose_Result | null;
  originatingactivityid_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  originatingactivityid_serviceappointment_campaignresponse?: ServiceAppointment_Result | null;
  ownerid_campaignresponse?: Team_Result | null;
  ownerid_campaignresponse1?: SystemUser_Result | null;
  owningbusinessunit_campaignresponse?: BusinessUnit_Result | null;
  owningteam_campaignresponse?: Team_Result | null;
  owninguser_campaignresponse?: SystemUser_Result | null;
  regardingobjectid_account_campaignresponse?: Account_Result | null;
  regardingobjectid_bookableresourcebooking_campaignresponse?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_campaignresponse?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_campaignresponse?: BulkOperation_Result | null;
  regardingobjectid_campaign_campaignresponse?: Campaign_Result | null;
  regardingobjectid_campaignactivity_campaignresponse?: CampaignActivity_Result | null;
  regardingobjectid_contact_campaignresponse?: Contact_Result | null;
  regardingobjectid_knowledgearticle_campaignresponse?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_campaignresponse?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_campaignresponse?: Lead_Result | null;
  regardingobjectid_new_interactionforemail_campaignresponse?: InteractionForEmail_Result | null;
  sendermailboxid_campaignresponse?: Mailbox_Result | null;
  sla_activitypointer_sla_campaignresponse?: SLA_Result | null;
  slainvokedid_activitypointer_sla_campaignresponse?: SLA_Result | null;
  stageid_processstage?: ProcessStage_Result | null;
  transactioncurrencyid_campaignresponse?: TransactionCurrency_Result | null;
  userentityinstancedata_campaignresponse?: UserEntityInstanceData_Result[] | null;
}
interface CampaignResponse extends CampaignResponse_Base, CampaignResponse_Relationships {
  originatingactivityid_activitypointer_bind$activitypointers?: string | null;
  originatingactivityid_appointment_bind$appointments?: string | null;
  originatingactivityid_email_bind$emails?: string | null;
  originatingactivityid_fax_bind$faxes?: string | null;
  originatingactivityid_incidentresolution_campaignresponse_bind$incidentresolutions?: string | null;
  originatingactivityid_letter_bind$letters?: string | null;
  originatingactivityid_msdyn_approval_campaignresponse_bind$msdyn_approvals?: string | null;
  originatingactivityid_msdyn_bookingalert_campaignresponse_bind$msdyn_bookingalerts?: string | null;
  originatingactivityid_msdyn_ocliveworkitem_campaignresponse_bind$msdyn_ocliveworkitems?: string | null;
  originatingactivityid_msdyn_ocoutboundmessage_campaignresponse_bind$msdyn_ocoutboundmessages?: string | null;
  originatingactivityid_msdyn_ocsession_campaignresponse_bind$msdyn_ocsessions?: string | null;
  originatingactivityid_msfp_alert_campaignresponse_bind$msfp_alerts?: string | null;
  originatingactivityid_msfp_surveyinvite_campaignresponse_bind$msfp_surveyinvites?: string | null;
  originatingactivityid_msfp_surveyresponse_campaignresponse_bind$msfp_surveyresponses?: string | null;
  originatingactivityid_opportunityclose_campaignresponse_bind$opportunitycloses?: string | null;
  originatingactivityid_orderclose_campaignresponse_bind$ordercloses?: string | null;
  originatingactivityid_phonecall_bind$phonecalls?: string | null;
  originatingactivityid_quoteclose_campaignresponse_bind$quotecloses?: string | null;
  originatingactivityid_recurringappointmentmaster_bind$recurringappointmentmasters?: string | null;
  originatingactivityid_serviceappointment_campaignresponse_bind$serviceappointments?: string | null;
  ownerid_campaignresponse_bind$systemusers?: string | null;
  ownerid_campaignresponse_bind$teams?: string | null;
  sla_activitypointer_sla_campaignresponse_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_campaignresponse_bind$transactioncurrencies?: string | null;
}
interface CampaignResponse_Create extends CampaignResponse {
  activityid_activitypointer_bind$activitypointers?: string | null;
  regardingobjectid_account_campaignresponse_bind$accounts?: string | null;
  regardingobjectid_bookableresourcebooking_campaignresponse_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_campaignresponse_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_campaignresponse_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_campaignresponse_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_campaignresponse_bind$campaignactivities?: string | null;
  regardingobjectid_contact_campaignresponse_bind$contacts?: string | null;
  regardingobjectid_knowledgearticle_campaignresponse_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_campaignresponse_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_campaignresponse_bind$leads?: string | null;
  regardingobjectid_new_interactionforemail_campaignresponse_bind$interactionforemails?: string | null;
}
interface CampaignResponse_Update extends CampaignResponse {
}
interface CampaignResponse_Select {
  activityadditionalparams: WebAttribute<CampaignResponse_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<CampaignResponse_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<CampaignResponse_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<CampaignResponse_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<CampaignResponse_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<CampaignResponse_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  bcc_guid: WebAttribute<CampaignResponse_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
  category: WebAttribute<CampaignResponse_Select, { category: string | null }, {  }>;
  cc_guid: WebAttribute<CampaignResponse_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
  channeltypecode: WebAttribute<CampaignResponse_Select, { channeltypecode: campaignresponse_channeltypecode | null }, { channeltypecode_formatted?: string }>;
  community: WebAttribute<CampaignResponse_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  companyname: WebAttribute<CampaignResponse_Select, { companyname: string | null }, {  }>;
  createdby_guid: WebAttribute<CampaignResponse_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<CampaignResponse_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<CampaignResponse_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  customer_guid: WebAttribute<CampaignResponse_Select, { customer_guid: string | null }, { customer_formatted?: string }>;
  customers_guid: WebAttribute<CampaignResponse_Select, { customers_guid: string | null }, { customers_formatted?: string }>;
  deliverylastattemptedon: WebAttribute<CampaignResponse_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
  deliveryprioritycode: WebAttribute<CampaignResponse_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  description: WebAttribute<CampaignResponse_Select, { description: string | null }, {  }>;
  emailaddress: WebAttribute<CampaignResponse_Select, { emailaddress: string | null }, {  }>;
  exchangeitemid: WebAttribute<CampaignResponse_Select, { exchangeitemid: string | null }, {  }>;
  exchangerate: WebAttribute<CampaignResponse_Select, { exchangerate: number | null }, {  }>;
  exchangeweblink: WebAttribute<CampaignResponse_Select, { exchangeweblink: string | null }, {  }>;
  fax: WebAttribute<CampaignResponse_Select, { fax: string | null }, {  }>;
  firstname: WebAttribute<CampaignResponse_Select, { firstname: string | null }, {  }>;
  from_guid: WebAttribute<CampaignResponse_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<CampaignResponse_Select, { importsequencenumber: number | null }, {  }>;
  instancetypecode: WebAttribute<CampaignResponse_Select, { instancetypecode: _campaignresponse_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isbilled: WebAttribute<CampaignResponse_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<CampaignResponse_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<CampaignResponse_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<CampaignResponse_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastname: WebAttribute<CampaignResponse_Select, { lastname: string | null }, {  }>;
  lastonholdtime: WebAttribute<CampaignResponse_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<CampaignResponse_Select, { leftvoicemail: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<CampaignResponse_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<CampaignResponse_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<CampaignResponse_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<CampaignResponse_Select, { onholdtime: number | null }, {  }>;
  optionalattendees_guid: WebAttribute<CampaignResponse_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<CampaignResponse_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  originatingactivityid_guid: WebAttribute<CampaignResponse_Select, { originatingactivityid_guid: string | null }, { originatingactivityid_formatted?: string }>;
  overriddencreatedon: WebAttribute<CampaignResponse_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<CampaignResponse_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<CampaignResponse_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<CampaignResponse_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<CampaignResponse_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  partner_guid: WebAttribute<CampaignResponse_Select, { partner_guid: string | null }, { partner_formatted?: string }>;
  partners_guid: WebAttribute<CampaignResponse_Select, { partners_guid: string | null }, { partners_formatted?: string }>;
  postponeactivityprocessinguntil: WebAttribute<CampaignResponse_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<CampaignResponse_Select, { prioritycode: campaignresponse_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<CampaignResponse_Select, { processid: string | null }, {  }>;
  promotioncodename: WebAttribute<CampaignResponse_Select, { promotioncodename: string | null }, {  }>;
  receivedon: WebAttribute<CampaignResponse_Select, { receivedon: Date | null }, { receivedon_formatted?: string }>;
  regardingobjectid_guid: WebAttribute<CampaignResponse_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<CampaignResponse_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  resources_guid: WebAttribute<CampaignResponse_Select, { resources_guid: string | null }, { resources_formatted?: string }>;
  responsecode: WebAttribute<CampaignResponse_Select, { responsecode: campaignresponse_responsecode | null }, { responsecode_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<CampaignResponse_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<CampaignResponse_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<CampaignResponse_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sendermailboxid_guid: WebAttribute<CampaignResponse_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  senton: WebAttribute<CampaignResponse_Select, { senton: Date | null }, { senton_formatted?: string }>;
  seriesid: WebAttribute<CampaignResponse_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<CampaignResponse_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<CampaignResponse_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<CampaignResponse_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<CampaignResponse_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<CampaignResponse_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<CampaignResponse_Select, { statecode: campaignresponse_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<CampaignResponse_Select, { statuscode: campaignresponse_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<CampaignResponse_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<CampaignResponse_Select, { subject: string | null }, {  }>;
  telephone: WebAttribute<CampaignResponse_Select, { telephone: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<CampaignResponse_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<CampaignResponse_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<CampaignResponse_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<CampaignResponse_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<CampaignResponse_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<CampaignResponse_Select, { versionnumber: number | null }, {  }>;
}
interface CampaignResponse_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  bcc_guid: XQW.Guid;
  category: string;
  cc_guid: XQW.Guid;
  channeltypecode: campaignresponse_channeltypecode;
  community: socialprofile_community;
  companyname: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  customer_guid: XQW.Guid;
  customers_guid: XQW.Guid;
  deliverylastattemptedon: Date;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  description: string;
  emailaddress: string;
  exchangeitemid: string;
  exchangerate: any;
  exchangeweblink: string;
  fax: string;
  firstname: string;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  instancetypecode: _campaignresponse_instancetypecode;
  isbilled: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastname: string;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  originatingactivityid_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  partner_guid: XQW.Guid;
  partners_guid: XQW.Guid;
  postponeactivityprocessinguntil: Date;
  prioritycode: campaignresponse_prioritycode;
  processid: XQW.Guid;
  promotioncodename: string;
  receivedon: Date;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  resources_guid: XQW.Guid;
  responsecode: campaignresponse_responsecode;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sendermailboxid_guid: XQW.Guid;
  senton: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: campaignresponse_statecode;
  statuscode: campaignresponse_statuscode;
  subcategory: string;
  subject: string;
  telephone: string;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface CampaignResponse_Expand {
  CampaignResponse_Annotation: WebExpand<CampaignResponse_Expand, Annotation_Select, Annotation_Filter, { CampaignResponse_Annotation: Annotation_Result[] }>;
  CampaignResponse_AsyncOperations: WebExpand<CampaignResponse_Expand, AsyncOperation_Select, AsyncOperation_Filter, { CampaignResponse_AsyncOperations: AsyncOperation_Result[] }>;
  CampaignResponse_BulkDeleteFailures: WebExpand<CampaignResponse_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { CampaignResponse_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  CampaignResponse_DuplicateBaseRecord: WebExpand<CampaignResponse_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { CampaignResponse_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  CampaignResponse_DuplicateMatchingRecord: WebExpand<CampaignResponse_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { CampaignResponse_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  CampaignResponse_Lead: WebExpand<CampaignResponse_Expand, Lead_Select, Lead_Filter, { CampaignResponse_Lead: Lead_Result[] }>;
  CampaignResponse_ProcessSessions: WebExpand<CampaignResponse_Expand, ProcessSession_Select, ProcessSession_Filter, { CampaignResponse_ProcessSessions: ProcessSession_Result[] }>;
  CampaignResponse_QueueItem: WebExpand<CampaignResponse_Expand, QueueItem_Select, QueueItem_Filter, { CampaignResponse_QueueItem: QueueItem_Result[] }>;
  CampaignResponse_SyncErrors: WebExpand<CampaignResponse_Expand, SyncError_Select, SyncError_Filter, { CampaignResponse_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<CampaignResponse_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  campaignresponse_MailboxTrackingFolders: WebExpand<CampaignResponse_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { campaignresponse_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  campaignresponse_activity_parties: WebExpand<CampaignResponse_Expand, ActivityParty_Select, ActivityParty_Filter, { campaignresponse_activity_parties: ActivityParty_Result[] }>;
  campaignresponse_principalobjectattributeaccess: WebExpand<CampaignResponse_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { campaignresponse_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  createdby_campaignresponse: WebExpand<CampaignResponse_Expand, SystemUser_Select, SystemUser_Filter, { createdby_campaignresponse: SystemUser_Result }>;
  createdonbehalfby_campaignresponse: WebExpand<CampaignResponse_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_campaignresponse: SystemUser_Result }>;
  modifiedby_campaignresponse: WebExpand<CampaignResponse_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_campaignresponse: SystemUser_Result }>;
  modifiedonbehalfby_campaignresponse: WebExpand<CampaignResponse_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_campaignresponse: SystemUser_Result }>;
  originatingactivityid_activitypointer: WebExpand<CampaignResponse_Expand, ActivityPointer_Select, ActivityPointer_Filter, { originatingactivityid_activitypointer: ActivityPointer_Result }>;
  originatingactivityid_appointment: WebExpand<CampaignResponse_Expand, Appointment_Select, Appointment_Filter, { originatingactivityid_appointment: Appointment_Result }>;
  originatingactivityid_email: WebExpand<CampaignResponse_Expand, Email_Select, Email_Filter, { originatingactivityid_email: Email_Result }>;
  originatingactivityid_fax: WebExpand<CampaignResponse_Expand, Fax_Select, Fax_Filter, { originatingactivityid_fax: Fax_Result }>;
  originatingactivityid_incidentresolution_campaignresponse: WebExpand<CampaignResponse_Expand, IncidentResolution_Select, IncidentResolution_Filter, { originatingactivityid_incidentresolution_campaignresponse: IncidentResolution_Result }>;
  originatingactivityid_letter: WebExpand<CampaignResponse_Expand, Letter_Select, Letter_Filter, { originatingactivityid_letter: Letter_Result }>;
  originatingactivityid_msdyn_approval_campaignresponse: WebExpand<CampaignResponse_Expand, msdyn_approval_Select, msdyn_approval_Filter, { originatingactivityid_msdyn_approval_campaignresponse: msdyn_approval_Result }>;
  originatingactivityid_msdyn_bookingalert_campaignresponse: WebExpand<CampaignResponse_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { originatingactivityid_msdyn_bookingalert_campaignresponse: msdyn_bookingalert_Result }>;
  originatingactivityid_msdyn_ocliveworkitem_campaignresponse: WebExpand<CampaignResponse_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { originatingactivityid_msdyn_ocliveworkitem_campaignresponse: msdyn_ocliveworkitem_Result }>;
  originatingactivityid_msdyn_ocoutboundmessage_campaignresponse: WebExpand<CampaignResponse_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { originatingactivityid_msdyn_ocoutboundmessage_campaignresponse: msdyn_ocoutboundmessage_Result }>;
  originatingactivityid_msdyn_ocsession_campaignresponse: WebExpand<CampaignResponse_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { originatingactivityid_msdyn_ocsession_campaignresponse: msdyn_ocsession_Result }>;
  originatingactivityid_msfp_alert_campaignresponse: WebExpand<CampaignResponse_Expand, msfp_alert_Select, msfp_alert_Filter, { originatingactivityid_msfp_alert_campaignresponse: msfp_alert_Result }>;
  originatingactivityid_msfp_surveyinvite_campaignresponse: WebExpand<CampaignResponse_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { originatingactivityid_msfp_surveyinvite_campaignresponse: msfp_surveyinvite_Result }>;
  originatingactivityid_msfp_surveyresponse_campaignresponse: WebExpand<CampaignResponse_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { originatingactivityid_msfp_surveyresponse_campaignresponse: msfp_surveyresponse_Result }>;
  originatingactivityid_opportunityclose_campaignresponse: WebExpand<CampaignResponse_Expand, OpportunityClose_Select, OpportunityClose_Filter, { originatingactivityid_opportunityclose_campaignresponse: OpportunityClose_Result }>;
  originatingactivityid_orderclose_campaignresponse: WebExpand<CampaignResponse_Expand, OrderClose_Select, OrderClose_Filter, { originatingactivityid_orderclose_campaignresponse: OrderClose_Result }>;
  originatingactivityid_phonecall: WebExpand<CampaignResponse_Expand, PhoneCall_Select, PhoneCall_Filter, { originatingactivityid_phonecall: PhoneCall_Result }>;
  originatingactivityid_quoteclose_campaignresponse: WebExpand<CampaignResponse_Expand, QuoteClose_Select, QuoteClose_Filter, { originatingactivityid_quoteclose_campaignresponse: QuoteClose_Result }>;
  originatingactivityid_recurringappointmentmaster: WebExpand<CampaignResponse_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { originatingactivityid_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  originatingactivityid_serviceappointment_campaignresponse: WebExpand<CampaignResponse_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { originatingactivityid_serviceappointment_campaignresponse: ServiceAppointment_Result }>;
  ownerid_campaignresponse: WebExpand<CampaignResponse_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_campaignresponse: SystemUser_Result } & { ownerid_campaignresponse: Team_Result }>;
  owningbusinessunit_campaignresponse: WebExpand<CampaignResponse_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_campaignresponse: BusinessUnit_Result }>;
  owningteam_campaignresponse: WebExpand<CampaignResponse_Expand, Team_Select, Team_Filter, { owningteam_campaignresponse: Team_Result }>;
  owninguser_campaignresponse: WebExpand<CampaignResponse_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_campaignresponse: SystemUser_Result }>;
  regardingobjectid_account_campaignresponse: WebExpand<CampaignResponse_Expand, Account_Select, Account_Filter, { regardingobjectid_account_campaignresponse: Account_Result }>;
  regardingobjectid_bookableresourcebooking_campaignresponse: WebExpand<CampaignResponse_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_campaignresponse: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_campaignresponse: WebExpand<CampaignResponse_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_campaignresponse: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_campaignresponse: WebExpand<CampaignResponse_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_campaignresponse: BulkOperation_Result }>;
  regardingobjectid_campaign_campaignresponse: WebExpand<CampaignResponse_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_campaignresponse: Campaign_Result }>;
  regardingobjectid_campaignactivity_campaignresponse: WebExpand<CampaignResponse_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_campaignresponse: CampaignActivity_Result }>;
  regardingobjectid_contact_campaignresponse: WebExpand<CampaignResponse_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_campaignresponse: Contact_Result }>;
  regardingobjectid_knowledgearticle_campaignresponse: WebExpand<CampaignResponse_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_campaignresponse: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_campaignresponse: WebExpand<CampaignResponse_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_campaignresponse: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_campaignresponse: WebExpand<CampaignResponse_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_campaignresponse: Lead_Result }>;
  regardingobjectid_new_interactionforemail_campaignresponse: WebExpand<CampaignResponse_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { regardingobjectid_new_interactionforemail_campaignresponse: InteractionForEmail_Result }>;
  sendermailboxid_campaignresponse: WebExpand<CampaignResponse_Expand, Mailbox_Select, Mailbox_Filter, { sendermailboxid_campaignresponse: Mailbox_Result }>;
  sla_activitypointer_sla_campaignresponse: WebExpand<CampaignResponse_Expand, SLA_Select, SLA_Filter, { sla_activitypointer_sla_campaignresponse: SLA_Result }>;
  slainvokedid_activitypointer_sla_campaignresponse: WebExpand<CampaignResponse_Expand, SLA_Select, SLA_Filter, { slainvokedid_activitypointer_sla_campaignresponse: SLA_Result }>;
  stageid_processstage: WebExpand<CampaignResponse_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid_campaignresponse: WebExpand<CampaignResponse_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_campaignresponse: TransactionCurrency_Result }>;
  userentityinstancedata_campaignresponse: WebExpand<CampaignResponse_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_campaignresponse: UserEntityInstanceData_Result[] }>;
}
interface CampaignResponse_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  bcc_formatted?: string;
  cc_formatted?: string;
  channeltypecode_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  customer_formatted?: string;
  customers_formatted?: string;
  deliverylastattemptedon_formatted?: string;
  deliveryprioritycode_formatted?: string;
  from_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  originatingactivityid_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  partner_formatted?: string;
  partners_formatted?: string;
  postponeactivityprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  receivedon_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  resources_formatted?: string;
  responsecode_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface CampaignResponse_Result extends CampaignResponse_Base, CampaignResponse_Relationships {
  "@odata.etag": string;
  bcc_guid: string | null;
  cc_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  customer_guid: string | null;
  customers_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  originatingactivityid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  partner_guid: string | null;
  partners_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  resources_guid: string | null;
  sendermailboxid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface CampaignResponse_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_campaignresponse: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_campaignresponse: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_campaignresponse: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_campaignresponse: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  originatingactivityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  originatingactivityid_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  originatingactivityid_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  originatingactivityid_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  originatingactivityid_incidentresolution_campaignresponse: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  originatingactivityid_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  originatingactivityid_msdyn_approval_campaignresponse: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  originatingactivityid_msdyn_bookingalert_campaignresponse: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  originatingactivityid_msdyn_ocliveworkitem_campaignresponse: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  originatingactivityid_msdyn_ocoutboundmessage_campaignresponse: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  originatingactivityid_msdyn_ocsession_campaignresponse: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  originatingactivityid_msfp_alert_campaignresponse: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  originatingactivityid_msfp_surveyinvite_campaignresponse: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  originatingactivityid_msfp_surveyresponse_campaignresponse: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  originatingactivityid_opportunityclose_campaignresponse: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  originatingactivityid_orderclose_campaignresponse: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  originatingactivityid_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  originatingactivityid_quoteclose_campaignresponse: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  originatingactivityid_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  originatingactivityid_serviceappointment_campaignresponse: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  ownerid_campaignresponse: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_campaignresponse1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_campaignresponse: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_campaignresponse: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_campaignresponse: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_campaignresponse: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_bookableresourcebooking_campaignresponse: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_campaignresponse: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_campaignresponse: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_campaignresponse: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_campaignresponse: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_campaignresponse: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_knowledgearticle_campaignresponse: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_campaignresponse: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_campaignresponse: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_new_interactionforemail_campaignresponse: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  sendermailboxid_campaignresponse: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  sla_activitypointer_sla_campaignresponse: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_activitypointer_sla_campaignresponse: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_campaignresponse: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface CampaignResponse_RelatedMany {
  CampaignResponse_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  CampaignResponse_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  CampaignResponse_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  CampaignResponse_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  CampaignResponse_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  CampaignResponse_Lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  CampaignResponse_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  CampaignResponse_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  CampaignResponse_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  campaignresponse_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  campaignresponse_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  campaignresponse_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  userentityinstancedata_campaignresponse: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  campaignresponses: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
}
interface WebEntitiesRelated {
  campaignresponses: WebMappingRelated<CampaignResponse_RelatedOne,CampaignResponse_RelatedMany>;
}
interface WebEntitiesCUDA {
  campaignresponses: WebMappingCUDA<CampaignResponse_Create,CampaignResponse_Update,CampaignResponse_Select>;
}
