interface EmailServerProfile_Base extends WebEntity {
  aadresourceid?: string | null;
  createdon?: Date | null;
  defaultserverlocation?: string | null;
  description?: string | null;
  emailserverprofileid?: string | null;
  emailservertypename?: string | null;
  encodingcodepage?: string | null;
  entityimageid?: string | null;
  exchangeonlinetenantid?: string | null;
  exchangeversion?: emailserverprofile_exchangeversion | null;
  incomingauthenticationprotocol?: emailserverprofile_authenticationprotocol | null;
  incomingcredentialretrieval?: emailserverprofile_incomingcredentialretrieval | null;
  incomingpassword?: string | null;
  incomingportnumber?: number | null;
  incomingserverlocation?: string | null;
  incominguseimpersonation?: boolean | null;
  incomingusername?: string | null;
  incomingusessl?: boolean | null;
  isincomingpasswordset?: boolean | null;
  isoauthclientsecretset?: boolean | null;
  isoutgoingpasswordset?: boolean | null;
  lastauthorizationstatus?: emailserverprofile_lastauthorizationstatus | null;
  lastcrmmessage?: string | null;
  lasttestexecutionstatus?: emailserverprofile_lasttestexecutionstatus | null;
  lasttestrequest?: string | null;
  lasttestresponse?: string | null;
  lastteststarttime?: Date | null;
  lasttesttotalexecutiontime?: number | null;
  lasttestvalidationstatus?: emailserverprofile_lasttestvalidationstatus | null;
  maxconcurrentconnections?: number | null;
  minpollingintervalinminutes?: number | null;
  modifiedon?: Date | null;
  moveundeliveredemails?: boolean | null;
  name?: string | null;
  oauthclientid?: string | null;
  oauthclientsecret?: string | null;
  outgoingauthenticationprotocol?: emailserverprofile_authenticationprotocol | null;
  outgoingautograntdelegateaccess?: boolean | null;
  outgoingcredentialretrieval?: emailserverprofile_outgoingcredentialretrieval | null;
  outgoingpassword?: string | null;
  outgoingportnumber?: number | null;
  outgoingserverlocation?: string | null;
  outgoinguseimpersonation?: boolean | null;
  outgoingusername?: string | null;
  outgoingusessl?: boolean | null;
  owneremailaddress?: string | null;
  processemailsreceivedafter?: Date | null;
  sendemailalert?: boolean | null;
  servertype?: emailserverprofile_servertype | null;
  statecode?: emailserverprofile_statecode | null;
  statuscode?: emailserverprofile_statuscode | null;
  timeoutmailboxconnection?: boolean | null;
  timeoutmailboxconnectionafteramount?: number | null;
  timezoneruleversionnumber?: number | null;
  useautodiscover?: boolean | null;
  usedefaulttenantid?: boolean | null;
  usesamesettingsforoutgoingconnections?: boolean | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface EmailServerProfile_Relationships {
  EmailServerProfile_Annotation?: Annotation_Result[] | null;
  EmailServerProfile_Organization?: Organization_Result[] | null;
  EmailServerProfile_SyncErrors?: SyncError_Result[] | null;
  emailServerProfile_TraceRegardings?: TraceRegarding_Result[] | null;
  emailserverprofile_asyncoperations?: AsyncOperation_Result[] | null;
  emailserverprofile_bulkdeletefailures?: BulkDeleteFailure_Result[] | null;
  emailserverprofile_duplicatebaserecord?: DuplicateRecord_Result[] | null;
  emailserverprofile_duplicatematchingrecord?: DuplicateRecord_Result[] | null;
  emailserverprofile_mailbox?: Mailbox_Result[] | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  tracelog_EmailServerProfile?: TraceLog_Result[] | null;
}
interface EmailServerProfile extends EmailServerProfile_Base, EmailServerProfile_Relationships {
  keyvaultreferenceid_bind$keyvaultreferences?: string | null;
  managedidentityid_bind$managedidentities?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface EmailServerProfile_Create extends EmailServerProfile {
}
interface EmailServerProfile_Update extends EmailServerProfile {
}
interface EmailServerProfile_Select {
  aadresourceid: WebAttribute<EmailServerProfile_Select, { aadresourceid: string | null }, {  }>;
  createdby_guid: WebAttribute<EmailServerProfile_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<EmailServerProfile_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<EmailServerProfile_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  defaultserverlocation: WebAttribute<EmailServerProfile_Select, { defaultserverlocation: string | null }, {  }>;
  description: WebAttribute<EmailServerProfile_Select, { description: string | null }, {  }>;
  emailserverprofileid: WebAttribute<EmailServerProfile_Select, { emailserverprofileid: string | null }, {  }>;
  emailservertypename: WebAttribute<EmailServerProfile_Select, { emailservertypename: string | null }, {  }>;
  encodingcodepage: WebAttribute<EmailServerProfile_Select, { encodingcodepage: string | null }, {  }>;
  entityimageid: WebAttribute<EmailServerProfile_Select, { entityimageid: string | null }, {  }>;
  exchangeonlinetenantid: WebAttribute<EmailServerProfile_Select, { exchangeonlinetenantid: string | null }, {  }>;
  exchangeversion: WebAttribute<EmailServerProfile_Select, { exchangeversion: emailserverprofile_exchangeversion | null }, { exchangeversion_formatted?: string }>;
  incomingauthenticationprotocol: WebAttribute<EmailServerProfile_Select, { incomingauthenticationprotocol: emailserverprofile_authenticationprotocol | null }, { incomingauthenticationprotocol_formatted?: string }>;
  incomingcredentialretrieval: WebAttribute<EmailServerProfile_Select, { incomingcredentialretrieval: emailserverprofile_incomingcredentialretrieval | null }, { incomingcredentialretrieval_formatted?: string }>;
  incomingpartnerapplication_guid: WebAttribute<EmailServerProfile_Select, { incomingpartnerapplication_guid: string | null }, { incomingpartnerapplication_formatted?: string }>;
  incomingpassword: WebAttribute<EmailServerProfile_Select, { incomingpassword: string | null }, {  }>;
  incomingportnumber: WebAttribute<EmailServerProfile_Select, { incomingportnumber: number | null }, {  }>;
  incomingserverlocation: WebAttribute<EmailServerProfile_Select, { incomingserverlocation: string | null }, {  }>;
  incominguseimpersonation: WebAttribute<EmailServerProfile_Select, { incominguseimpersonation: boolean | null }, {  }>;
  incomingusername: WebAttribute<EmailServerProfile_Select, { incomingusername: string | null }, {  }>;
  incomingusessl: WebAttribute<EmailServerProfile_Select, { incomingusessl: boolean | null }, {  }>;
  isincomingpasswordset: WebAttribute<EmailServerProfile_Select, { isincomingpasswordset: boolean | null }, {  }>;
  isoauthclientsecretset: WebAttribute<EmailServerProfile_Select, { isoauthclientsecretset: boolean | null }, {  }>;
  isoutgoingpasswordset: WebAttribute<EmailServerProfile_Select, { isoutgoingpasswordset: boolean | null }, {  }>;
  keyvaultreferenceid_guid: WebAttribute<EmailServerProfile_Select, { keyvaultreferenceid_guid: string | null }, { keyvaultreferenceid_formatted?: string }>;
  lastauthorizationstatus: WebAttribute<EmailServerProfile_Select, { lastauthorizationstatus: emailserverprofile_lastauthorizationstatus | null }, { lastauthorizationstatus_formatted?: string }>;
  lastcrmmessage: WebAttribute<EmailServerProfile_Select, { lastcrmmessage: string | null }, {  }>;
  lasttestexecutionstatus: WebAttribute<EmailServerProfile_Select, { lasttestexecutionstatus: emailserverprofile_lasttestexecutionstatus | null }, { lasttestexecutionstatus_formatted?: string }>;
  lasttestrequest: WebAttribute<EmailServerProfile_Select, { lasttestrequest: string | null }, {  }>;
  lasttestresponse: WebAttribute<EmailServerProfile_Select, { lasttestresponse: string | null }, {  }>;
  lastteststarttime: WebAttribute<EmailServerProfile_Select, { lastteststarttime: Date | null }, { lastteststarttime_formatted?: string }>;
  lasttesttotalexecutiontime: WebAttribute<EmailServerProfile_Select, { lasttesttotalexecutiontime: number | null }, {  }>;
  lasttestvalidationstatus: WebAttribute<EmailServerProfile_Select, { lasttestvalidationstatus: emailserverprofile_lasttestvalidationstatus | null }, { lasttestvalidationstatus_formatted?: string }>;
  managedidentityid_guid: WebAttribute<EmailServerProfile_Select, { managedidentityid_guid: string | null }, { managedidentityid_formatted?: string }>;
  maxconcurrentconnections: WebAttribute<EmailServerProfile_Select, { maxconcurrentconnections: number | null }, {  }>;
  minpollingintervalinminutes: WebAttribute<EmailServerProfile_Select, { minpollingintervalinminutes: number | null }, {  }>;
  modifiedby_guid: WebAttribute<EmailServerProfile_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<EmailServerProfile_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<EmailServerProfile_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  moveundeliveredemails: WebAttribute<EmailServerProfile_Select, { moveundeliveredemails: boolean | null }, {  }>;
  name: WebAttribute<EmailServerProfile_Select, { name: string | null }, {  }>;
  oauthclientid: WebAttribute<EmailServerProfile_Select, { oauthclientid: string | null }, {  }>;
  oauthclientsecret: WebAttribute<EmailServerProfile_Select, { oauthclientsecret: string | null }, {  }>;
  organizationid_guid: WebAttribute<EmailServerProfile_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  outgoingauthenticationprotocol: WebAttribute<EmailServerProfile_Select, { outgoingauthenticationprotocol: emailserverprofile_authenticationprotocol | null }, { outgoingauthenticationprotocol_formatted?: string }>;
  outgoingautograntdelegateaccess: WebAttribute<EmailServerProfile_Select, { outgoingautograntdelegateaccess: boolean | null }, {  }>;
  outgoingcredentialretrieval: WebAttribute<EmailServerProfile_Select, { outgoingcredentialretrieval: emailserverprofile_outgoingcredentialretrieval | null }, { outgoingcredentialretrieval_formatted?: string }>;
  outgoingpartnerapplication_guid: WebAttribute<EmailServerProfile_Select, { outgoingpartnerapplication_guid: string | null }, { outgoingpartnerapplication_formatted?: string }>;
  outgoingpassword: WebAttribute<EmailServerProfile_Select, { outgoingpassword: string | null }, {  }>;
  outgoingportnumber: WebAttribute<EmailServerProfile_Select, { outgoingportnumber: number | null }, {  }>;
  outgoingserverlocation: WebAttribute<EmailServerProfile_Select, { outgoingserverlocation: string | null }, {  }>;
  outgoinguseimpersonation: WebAttribute<EmailServerProfile_Select, { outgoinguseimpersonation: boolean | null }, {  }>;
  outgoingusername: WebAttribute<EmailServerProfile_Select, { outgoingusername: string | null }, {  }>;
  outgoingusessl: WebAttribute<EmailServerProfile_Select, { outgoingusessl: boolean | null }, {  }>;
  owneremailaddress: WebAttribute<EmailServerProfile_Select, { owneremailaddress: string | null }, {  }>;
  ownerid_guid: WebAttribute<EmailServerProfile_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<EmailServerProfile_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<EmailServerProfile_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<EmailServerProfile_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  processemailsreceivedafter: WebAttribute<EmailServerProfile_Select, { processemailsreceivedafter: Date | null }, { processemailsreceivedafter_formatted?: string }>;
  sendemailalert: WebAttribute<EmailServerProfile_Select, { sendemailalert: boolean | null }, {  }>;
  servertype: WebAttribute<EmailServerProfile_Select, { servertype: emailserverprofile_servertype | null }, { servertype_formatted?: string }>;
  statecode: WebAttribute<EmailServerProfile_Select, { statecode: emailserverprofile_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<EmailServerProfile_Select, { statuscode: emailserverprofile_statuscode | null }, { statuscode_formatted?: string }>;
  timeoutmailboxconnection: WebAttribute<EmailServerProfile_Select, { timeoutmailboxconnection: boolean | null }, {  }>;
  timeoutmailboxconnectionafteramount: WebAttribute<EmailServerProfile_Select, { timeoutmailboxconnectionafteramount: number | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<EmailServerProfile_Select, { timezoneruleversionnumber: number | null }, {  }>;
  useautodiscover: WebAttribute<EmailServerProfile_Select, { useautodiscover: boolean | null }, {  }>;
  usedefaulttenantid: WebAttribute<EmailServerProfile_Select, { usedefaulttenantid: boolean | null }, {  }>;
  usesamesettingsforoutgoingconnections: WebAttribute<EmailServerProfile_Select, { usesamesettingsforoutgoingconnections: boolean | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<EmailServerProfile_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<EmailServerProfile_Select, { versionnumber: number | null }, {  }>;
}
interface EmailServerProfile_Filter {
  aadresourceid: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  defaultserverlocation: string;
  description: string;
  emailserverprofileid: XQW.Guid;
  emailservertypename: string;
  encodingcodepage: string;
  entityimageid: XQW.Guid;
  exchangeonlinetenantid: string;
  exchangeversion: emailserverprofile_exchangeversion;
  incomingauthenticationprotocol: emailserverprofile_authenticationprotocol;
  incomingcredentialretrieval: emailserverprofile_incomingcredentialretrieval;
  incomingpartnerapplication_guid: XQW.Guid;
  incomingpassword: string;
  incomingportnumber: number;
  incomingserverlocation: string;
  incominguseimpersonation: boolean;
  incomingusername: string;
  incomingusessl: boolean;
  isincomingpasswordset: boolean;
  isoauthclientsecretset: boolean;
  isoutgoingpasswordset: boolean;
  keyvaultreferenceid_guid: XQW.Guid;
  lastauthorizationstatus: emailserverprofile_lastauthorizationstatus;
  lastcrmmessage: string;
  lasttestexecutionstatus: emailserverprofile_lasttestexecutionstatus;
  lasttestrequest: string;
  lasttestresponse: string;
  lastteststarttime: Date;
  lasttesttotalexecutiontime: number;
  lasttestvalidationstatus: emailserverprofile_lasttestvalidationstatus;
  managedidentityid_guid: XQW.Guid;
  maxconcurrentconnections: number;
  minpollingintervalinminutes: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  moveundeliveredemails: boolean;
  name: string;
  oauthclientid: string;
  oauthclientsecret: string;
  organizationid_guid: XQW.Guid;
  outgoingauthenticationprotocol: emailserverprofile_authenticationprotocol;
  outgoingautograntdelegateaccess: boolean;
  outgoingcredentialretrieval: emailserverprofile_outgoingcredentialretrieval;
  outgoingpartnerapplication_guid: XQW.Guid;
  outgoingpassword: string;
  outgoingportnumber: number;
  outgoingserverlocation: string;
  outgoinguseimpersonation: boolean;
  outgoingusername: string;
  outgoingusessl: boolean;
  owneremailaddress: string;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  processemailsreceivedafter: Date;
  sendemailalert: boolean;
  servertype: emailserverprofile_servertype;
  statecode: emailserverprofile_statecode;
  statuscode: emailserverprofile_statuscode;
  timeoutmailboxconnection: boolean;
  timeoutmailboxconnectionafteramount: number;
  timezoneruleversionnumber: number;
  useautodiscover: boolean;
  usedefaulttenantid: boolean;
  usesamesettingsforoutgoingconnections: boolean;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface EmailServerProfile_Expand {
  EmailServerProfile_Annotation: WebExpand<EmailServerProfile_Expand, Annotation_Select, Annotation_Filter, { EmailServerProfile_Annotation: Annotation_Result[] }>;
  EmailServerProfile_Organization: WebExpand<EmailServerProfile_Expand, Organization_Select, Organization_Filter, { EmailServerProfile_Organization: Organization_Result[] }>;
  EmailServerProfile_SyncErrors: WebExpand<EmailServerProfile_Expand, SyncError_Select, SyncError_Filter, { EmailServerProfile_SyncErrors: SyncError_Result[] }>;
  createdby: WebExpand<EmailServerProfile_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<EmailServerProfile_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  emailServerProfile_TraceRegardings: WebExpand<EmailServerProfile_Expand, TraceRegarding_Select, TraceRegarding_Filter, { emailServerProfile_TraceRegardings: TraceRegarding_Result[] }>;
  emailserverprofile_asyncoperations: WebExpand<EmailServerProfile_Expand, AsyncOperation_Select, AsyncOperation_Filter, { emailserverprofile_asyncoperations: AsyncOperation_Result[] }>;
  emailserverprofile_bulkdeletefailures: WebExpand<EmailServerProfile_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { emailserverprofile_bulkdeletefailures: BulkDeleteFailure_Result[] }>;
  emailserverprofile_duplicatebaserecord: WebExpand<EmailServerProfile_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { emailserverprofile_duplicatebaserecord: DuplicateRecord_Result[] }>;
  emailserverprofile_duplicatematchingrecord: WebExpand<EmailServerProfile_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { emailserverprofile_duplicatematchingrecord: DuplicateRecord_Result[] }>;
  emailserverprofile_mailbox: WebExpand<EmailServerProfile_Expand, Mailbox_Select, Mailbox_Filter, { emailserverprofile_mailbox: Mailbox_Result[] }>;
  entityimageid_imagedescriptor: WebExpand<EmailServerProfile_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  incomingpartnerapplication: WebExpand<EmailServerProfile_Expand, PartnerApplication_Select, PartnerApplication_Filter, { incomingpartnerapplication: PartnerApplication_Result }>;
  keyvaultreferenceid: WebExpand<EmailServerProfile_Expand, KeyVaultReference_Select, KeyVaultReference_Filter, { keyvaultreferenceid: KeyVaultReference_Result }>;
  managedidentityid: WebExpand<EmailServerProfile_Expand, ManagedIdentity_Select, ManagedIdentity_Filter, { managedidentityid: ManagedIdentity_Result }>;
  modifiedby: WebExpand<EmailServerProfile_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<EmailServerProfile_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  organizationid: WebExpand<EmailServerProfile_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  outgoingpartnerapplication: WebExpand<EmailServerProfile_Expand, PartnerApplication_Select, PartnerApplication_Filter, { outgoingpartnerapplication: PartnerApplication_Result }>;
  ownerid: WebExpand<EmailServerProfile_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<EmailServerProfile_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<EmailServerProfile_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  tracelog_EmailServerProfile: WebExpand<EmailServerProfile_Expand, TraceLog_Select, TraceLog_Filter, { tracelog_EmailServerProfile: TraceLog_Result[] }>;
}
interface EmailServerProfile_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  exchangeversion_formatted?: string;
  incomingauthenticationprotocol_formatted?: string;
  incomingcredentialretrieval_formatted?: string;
  incomingpartnerapplication_formatted?: string;
  keyvaultreferenceid_formatted?: string;
  lastauthorizationstatus_formatted?: string;
  lasttestexecutionstatus_formatted?: string;
  lastteststarttime_formatted?: string;
  lasttestvalidationstatus_formatted?: string;
  managedidentityid_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  organizationid_formatted?: string;
  outgoingauthenticationprotocol_formatted?: string;
  outgoingcredentialretrieval_formatted?: string;
  outgoingpartnerapplication_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  processemailsreceivedafter_formatted?: string;
  servertype_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface EmailServerProfile_Result extends EmailServerProfile_Base, EmailServerProfile_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  incomingpartnerapplication_guid: string | null;
  keyvaultreferenceid_guid: string | null;
  managedidentityid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  organizationid_guid: string | null;
  outgoingpartnerapplication_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface EmailServerProfile_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  incomingpartnerapplication: WebMappingRetrieve<PartnerApplication_Select,PartnerApplication_Expand,PartnerApplication_Filter,PartnerApplication_Fixed,PartnerApplication_Result,PartnerApplication_FormattedResult>;
  keyvaultreferenceid: WebMappingRetrieve<KeyVaultReference_Select,KeyVaultReference_Expand,KeyVaultReference_Filter,KeyVaultReference_Fixed,KeyVaultReference_Result,KeyVaultReference_FormattedResult>;
  managedidentityid: WebMappingRetrieve<ManagedIdentity_Select,ManagedIdentity_Expand,ManagedIdentity_Filter,ManagedIdentity_Fixed,ManagedIdentity_Result,ManagedIdentity_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  outgoingpartnerapplication: WebMappingRetrieve<PartnerApplication_Select,PartnerApplication_Expand,PartnerApplication_Filter,PartnerApplication_Fixed,PartnerApplication_Result,PartnerApplication_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
}
interface EmailServerProfile_RelatedMany {
  EmailServerProfile_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  EmailServerProfile_Organization: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  EmailServerProfile_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  emailServerProfile_TraceRegardings: WebMappingRetrieve<TraceRegarding_Select,TraceRegarding_Expand,TraceRegarding_Filter,TraceRegarding_Fixed,TraceRegarding_Result,TraceRegarding_FormattedResult>;
  emailserverprofile_asyncoperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  emailserverprofile_bulkdeletefailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  emailserverprofile_duplicatebaserecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  emailserverprofile_duplicatematchingrecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  emailserverprofile_mailbox: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  tracelog_EmailServerProfile: WebMappingRetrieve<TraceLog_Select,TraceLog_Expand,TraceLog_Filter,TraceLog_Fixed,TraceLog_Result,TraceLog_FormattedResult>;
}
interface WebEntitiesRetrieve {
  emailserverprofiles: WebMappingRetrieve<EmailServerProfile_Select,EmailServerProfile_Expand,EmailServerProfile_Filter,EmailServerProfile_Fixed,EmailServerProfile_Result,EmailServerProfile_FormattedResult>;
}
interface WebEntitiesRelated {
  emailserverprofiles: WebMappingRelated<EmailServerProfile_RelatedOne,EmailServerProfile_RelatedMany>;
}
interface WebEntitiesCUDA {
  emailserverprofiles: WebMappingCUDA<EmailServerProfile_Create,EmailServerProfile_Update,EmailServerProfile_Select>;
}
