interface Fax_Base extends WebEntity {
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  billingcode?: string | null;
  category?: string | null;
  coverpagename?: string | null;
  createdon?: Date | null;
  description?: string | null;
  directioncode?: boolean | null;
  exchangerate?: number | null;
  faxnumber?: string | null;
  importsequencenumber?: number | null;
  isbilled?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  modifiedon?: Date | null;
  numberofpages?: number | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  prioritycode?: fax_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: fax_statecode | null;
  statuscode?: fax_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  subscriptionid?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  tsid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface Fax_Relationships {
  Fax_Annotation?: Annotation_Result[] | null;
  Fax_AsyncOperations?: AsyncOperation_Result[] | null;
  Fax_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Fax_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Fax_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Fax_ProcessSessions?: ProcessSession_Result[] | null;
  Fax_QueueItem?: QueueItem_Result[] | null;
  Fax_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  createdby_fax?: SystemUser_Result | null;
  createdonbehalfby_fax?: SystemUser_Result | null;
  fax_actioncard?: ActionCard_Result[] | null;
  fax_activity_parties?: ActivityParty_Result[] | null;
  fax_campaignresponse?: CampaignResponse_Result[] | null;
  fax_connections1?: Connection_Result[] | null;
  fax_connections2?: Connection_Result[] | null;
  fax_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  modifiedby_fax?: SystemUser_Result | null;
  modifiedonbehalfby_fax?: SystemUser_Result | null;
  ownerid_fax?: Team_Result | null;
  ownerid_fax1?: SystemUser_Result | null;
  owningbusinessunit_fax?: BusinessUnit_Result | null;
  owningteam_fax?: Team_Result | null;
  owninguser_fax?: SystemUser_Result | null;
  regardingobjectid_account_fax?: Account_Result | null;
  regardingobjectid_bookableresourcebooking_fax?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_fax?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_fax?: BulkOperation_Result | null;
  regardingobjectid_campaign_fax?: Campaign_Result | null;
  regardingobjectid_campaignactivity_fax?: CampaignActivity_Result | null;
  regardingobjectid_contact_fax?: Contact_Result | null;
  regardingobjectid_contract_fax?: Contract_Result | null;
  regardingobjectid_entitlement_fax?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_fax?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_fax?: Incident_Result | null;
  regardingobjectid_invoice_fax?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_fax?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_fax?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_fax?: Lead_Result | null;
  regardingobjectid_msdyn_agreement_fax?: msdyn_agreement_Result | null;
  regardingobjectid_msdyn_agreementbookingdate_fax?: msdyn_agreementbookingdate_Result | null;
  regardingobjectid_msdyn_agreementbookingincident_fax?: msdyn_agreementbookingincident_Result | null;
  regardingobjectid_msdyn_agreementbookingproduct_fax?: msdyn_agreementbookingproduct_Result | null;
  regardingobjectid_msdyn_agreementbookingservice_fax?: msdyn_agreementbookingservice_Result | null;
  regardingobjectid_msdyn_agreementbookingservicetask_fax?: msdyn_agreementbookingservicetask_Result | null;
  regardingobjectid_msdyn_agreementbookingsetup_fax?: msdyn_agreementbookingsetup_Result | null;
  regardingobjectid_msdyn_agreementinvoicedate_fax?: msdyn_agreementinvoicedate_Result | null;
  regardingobjectid_msdyn_agreementinvoiceproduct_fax?: msdyn_agreementinvoiceproduct_Result | null;
  regardingobjectid_msdyn_agreementinvoicesetup_fax?: msdyn_agreementinvoicesetup_Result | null;
  regardingobjectid_msdyn_bookingalertstatus_fax?: msdyn_bookingalertstatus_Result | null;
  regardingobjectid_msdyn_bookingrule_fax?: msdyn_bookingrule_Result | null;
  regardingobjectid_msdyn_bookingtimestamp_fax?: msdyn_bookingtimestamp_Result | null;
  regardingobjectid_msdyn_customerasset_fax?: msdyn_customerasset_Result | null;
  regardingobjectid_msdyn_fieldservicesetting_fax?: msdyn_fieldservicesetting_Result | null;
  regardingobjectid_msdyn_incidenttypecharacteristic_fax?: msdyn_incidenttypecharacteristic_Result | null;
  regardingobjectid_msdyn_incidenttypeproduct_fax?: msdyn_incidenttypeproduct_Result | null;
  regardingobjectid_msdyn_incidenttypeservice_fax?: msdyn_incidenttypeservice_Result | null;
  regardingobjectid_msdyn_inventoryadjustment_fax?: msdyn_inventoryadjustment_Result | null;
  regardingobjectid_msdyn_inventoryadjustmentproduct_fax?: msdyn_inventoryadjustmentproduct_Result | null;
  regardingobjectid_msdyn_inventoryjournal_fax?: msdyn_inventoryjournal_Result | null;
  regardingobjectid_msdyn_inventorytransfer_fax?: msdyn_inventorytransfer_Result | null;
  regardingobjectid_msdyn_payment_fax?: msdyn_payment_Result | null;
  regardingobjectid_msdyn_paymentdetail_fax?: msdyn_paymentdetail_Result | null;
  regardingobjectid_msdyn_paymentmethod_fax?: msdyn_paymentmethod_Result | null;
  regardingobjectid_msdyn_paymentterm_fax?: msdyn_paymentterm_Result | null;
  regardingobjectid_msdyn_playbookinstance_fax?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_fax?: msdyn_PostAlbum_Result | null;
  regardingobjectid_msdyn_postalcode_fax?: msdyn_postalcode_Result | null;
  regardingobjectid_msdyn_processnotes_fax?: msdyn_processnotes_Result | null;
  regardingobjectid_msdyn_productinventory_fax?: msdyn_productinventory_Result | null;
  regardingobjectid_msdyn_projectteam_fax?: msdyn_projectteam_Result | null;
  regardingobjectid_msdyn_purchaseorder_fax?: msdyn_purchaseorder_Result | null;
  regardingobjectid_msdyn_purchaseorderbill_fax?: msdyn_purchaseorderbill_Result | null;
  regardingobjectid_msdyn_purchaseorderproduct_fax?: msdyn_purchaseorderproduct_Result | null;
  regardingobjectid_msdyn_purchaseorderreceipt_fax?: msdyn_purchaseorderreceipt_Result | null;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_fax?: msdyn_purchaseorderreceiptproduct_Result | null;
  regardingobjectid_msdyn_purchaseordersubstatus_fax?: msdyn_purchaseordersubstatus_Result | null;
  regardingobjectid_msdyn_quotebookingincident_fax?: msdyn_quotebookingincident_Result | null;
  regardingobjectid_msdyn_quotebookingproduct_fax?: msdyn_quotebookingproduct_Result | null;
  regardingobjectid_msdyn_quotebookingservice_fax?: msdyn_quotebookingservice_Result | null;
  regardingobjectid_msdyn_quotebookingservicetask_fax?: msdyn_quotebookingservicetask_Result | null;
  regardingobjectid_msdyn_resourceterritory_fax?: msdyn_resourceterritory_Result | null;
  regardingobjectid_msdyn_rma_fax?: msdyn_rma_Result | null;
  regardingobjectid_msdyn_rmaproduct_fax?: msdyn_rmaproduct_Result | null;
  regardingobjectid_msdyn_rmareceipt_fax?: msdyn_rmareceipt_Result | null;
  regardingobjectid_msdyn_rmareceiptproduct_fax?: msdyn_rmareceiptproduct_Result | null;
  regardingobjectid_msdyn_rmasubstatus_fax?: msdyn_rmasubstatus_Result | null;
  regardingobjectid_msdyn_rtv_fax?: msdyn_rtv_Result | null;
  regardingobjectid_msdyn_rtvproduct_fax?: msdyn_rtvproduct_Result | null;
  regardingobjectid_msdyn_rtvsubstatus_fax?: msdyn_rtvsubstatus_Result | null;
  regardingobjectid_msdyn_shipvia_fax?: msdyn_shipvia_Result | null;
  regardingobjectid_msdyn_systemuserschedulersetting_fax?: msdyn_systemuserschedulersetting_Result | null;
  regardingobjectid_msdyn_timegroup_fax?: msdyn_timegroup_Result | null;
  regardingobjectid_msdyn_timegroupdetail_fax?: msdyn_timegroupdetail_Result | null;
  regardingobjectid_msdyn_timeoffrequest_fax?: msdyn_timeoffrequest_Result | null;
  regardingobjectid_msdyn_warehouse_fax?: msdyn_warehouse_Result | null;
  regardingobjectid_msdyn_workorder_fax?: msdyn_workorder_Result | null;
  regardingobjectid_msdyn_workordercharacteristic_fax?: msdyn_workordercharacteristic_Result | null;
  regardingobjectid_msdyn_workorderincident_fax?: msdyn_workorderincident_Result | null;
  regardingobjectid_msdyn_workorderproduct_fax?: msdyn_workorderproduct_Result | null;
  regardingobjectid_msdyn_workorderresourcerestriction_fax?: msdyn_workorderresourcerestriction_Result | null;
  regardingobjectid_msdyn_workorderservice_fax?: msdyn_workorderservice_Result | null;
  regardingobjectid_msdyn_workorderservicetask_fax?: msdyn_workorderservicetask_Result | null;
  regardingobjectid_opportunity_fax?: Opportunity_Result | null;
  regardingobjectid_quote_fax?: Quote_Result | null;
  regardingobjectid_salesorder_fax?: SalesOrder_Result | null;
  regardingobjectid_site_fax?: Site_Result | null;
  regardingobjectid_uii_action_fax?: UII_action_Result | null;
  regardingobjectid_uii_hostedapplication_fax?: UII_hostedapplication_Result | null;
  regardingobjectid_uii_nonhostedapplication_fax?: UII_nonhostedapplication_Result | null;
  regardingobjectid_uii_option_fax?: uii_option_Result | null;
  regardingobjectid_uii_savedsession_fax?: UII_savedsession_Result | null;
  regardingobjectid_uii_workflow_fax?: UII_workflow_Result | null;
  regardingobjectid_uii_workflow_workflowstep_mapping_fax?: UII_workflow_workflowstep_mapping_Result | null;
  regardingobjectid_uii_workflowstep_fax?: UII_workflowstep_Result | null;
  serviceid_fax?: Service_Result | null;
  sla_fax_sla?: SLA_Result | null;
  slainvokedid_fax_sla?: SLA_Result | null;
  slakpiinstance_fax?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  transactioncurrencyid_fax?: TransactionCurrency_Result | null;
  userentityinstancedata_fax?: UserEntityInstanceData_Result[] | null;
}
interface Fax extends Fax_Base, Fax_Relationships {
  ownerid_fax_bind$systemusers?: string | null;
  ownerid_fax_bind$teams?: string | null;
  regardingobjectid_account_fax_bind$accounts?: string | null;
  regardingobjectid_bookableresourcebooking_fax_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_fax_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_fax_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_fax_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_fax_bind$campaignactivities?: string | null;
  regardingobjectid_contact_fax_bind$contacts?: string | null;
  regardingobjectid_contract_fax_bind$contracts?: string | null;
  regardingobjectid_entitlement_fax_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_fax_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_fax_bind$incidents?: string | null;
  regardingobjectid_invoice_fax_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_fax_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_fax_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_fax_bind$leads?: string | null;
  regardingobjectid_msdyn_agreement_fax_bind$msdyn_agreements?: string | null;
  regardingobjectid_msdyn_agreementbookingdate_fax_bind$msdyn_agreementbookingdates?: string | null;
  regardingobjectid_msdyn_agreementbookingincident_fax_bind$msdyn_agreementbookingincidents?: string | null;
  regardingobjectid_msdyn_agreementbookingproduct_fax_bind$msdyn_agreementbookingproducts?: string | null;
  regardingobjectid_msdyn_agreementbookingservice_fax_bind$msdyn_agreementbookingservices?: string | null;
  regardingobjectid_msdyn_agreementbookingservicetask_fax_bind$msdyn_agreementbookingservicetasks?: string | null;
  regardingobjectid_msdyn_agreementbookingsetup_fax_bind$msdyn_agreementbookingsetups?: string | null;
  regardingobjectid_msdyn_agreementinvoicedate_fax_bind$msdyn_agreementinvoicedates?: string | null;
  regardingobjectid_msdyn_agreementinvoiceproduct_fax_bind$msdyn_agreementinvoiceproducts?: string | null;
  regardingobjectid_msdyn_agreementinvoicesetup_fax_bind$msdyn_agreementinvoicesetups?: string | null;
  regardingobjectid_msdyn_bookingalertstatus_fax_bind$msdyn_bookingalertstatuses?: string | null;
  regardingobjectid_msdyn_bookingrule_fax_bind$msdyn_bookingrules?: string | null;
  regardingobjectid_msdyn_bookingtimestamp_fax_bind$msdyn_bookingtimestamps?: string | null;
  regardingobjectid_msdyn_customerasset_fax_bind$msdyn_customerassets?: string | null;
  regardingobjectid_msdyn_fieldservicesetting_fax_bind$msdyn_fieldservicesettings?: string | null;
  regardingobjectid_msdyn_incidenttypecharacteristic_fax_bind$msdyn_incidenttypecharacteristics?: string | null;
  regardingobjectid_msdyn_incidenttypeproduct_fax_bind$msdyn_incidenttypeproducts?: string | null;
  regardingobjectid_msdyn_incidenttypeservice_fax_bind$msdyn_incidenttypeservices?: string | null;
  regardingobjectid_msdyn_inventoryadjustment_fax_bind$msdyn_inventoryadjustments?: string | null;
  regardingobjectid_msdyn_inventoryadjustmentproduct_fax_bind$msdyn_inventoryadjustmentproducts?: string | null;
  regardingobjectid_msdyn_inventoryjournal_fax_bind$msdyn_inventoryjournals?: string | null;
  regardingobjectid_msdyn_inventorytransfer_fax_bind$msdyn_inventorytransfers?: string | null;
  regardingobjectid_msdyn_payment_fax_bind$msdyn_payments?: string | null;
  regardingobjectid_msdyn_paymentdetail_fax_bind$msdyn_paymentdetailes?: string | null;
  regardingobjectid_msdyn_paymentmethod_fax_bind$msdyn_paymentmethods?: string | null;
  regardingobjectid_msdyn_paymentterm_fax_bind$msdyn_paymentterms?: string | null;
  regardingobjectid_msdyn_playbookinstance_fax_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_fax_bind$msdyn_postalbums?: string | null;
  regardingobjectid_msdyn_postalcode_fax_bind$msdyn_postalcodes?: string | null;
  regardingobjectid_msdyn_processnotes_fax_bind$msdyn_processnoteses?: string | null;
  regardingobjectid_msdyn_productinventory_fax_bind$msdyn_productinventories?: string | null;
  regardingobjectid_msdyn_projectteam_fax_bind$msdyn_projectteams?: string | null;
  regardingobjectid_msdyn_purchaseorder_fax_bind$msdyn_purchaseorders?: string | null;
  regardingobjectid_msdyn_purchaseorderbill_fax_bind$msdyn_purchaseorderbills?: string | null;
  regardingobjectid_msdyn_purchaseorderproduct_fax_bind$msdyn_purchaseorderproducts?: string | null;
  regardingobjectid_msdyn_purchaseorderreceipt_fax_bind$msdyn_purchaseorderreceipts?: string | null;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_fax_bind$msdyn_purchaseorderreceiptproducts?: string | null;
  regardingobjectid_msdyn_purchaseordersubstatus_fax_bind$msdyn_purchaseordersubstatuses?: string | null;
  regardingobjectid_msdyn_quotebookingincident_fax_bind$msdyn_quotebookingincidents?: string | null;
  regardingobjectid_msdyn_quotebookingproduct_fax_bind$msdyn_quotebookingproducts?: string | null;
  regardingobjectid_msdyn_quotebookingservice_fax_bind$msdyn_quotebookingservices?: string | null;
  regardingobjectid_msdyn_quotebookingservicetask_fax_bind$msdyn_quotebookingservicetasks?: string | null;
  regardingobjectid_msdyn_resourceterritory_fax_bind$msdyn_resourceterritories?: string | null;
  regardingobjectid_msdyn_rma_fax_bind$msdyn_rmas?: string | null;
  regardingobjectid_msdyn_rmaproduct_fax_bind$msdyn_rmaproducts?: string | null;
  regardingobjectid_msdyn_rmareceipt_fax_bind$msdyn_rmareceipts?: string | null;
  regardingobjectid_msdyn_rmareceiptproduct_fax_bind$msdyn_rmareceiptproducts?: string | null;
  regardingobjectid_msdyn_rmasubstatus_fax_bind$msdyn_rmasubstatuses?: string | null;
  regardingobjectid_msdyn_rtv_fax_bind$msdyn_rtvs?: string | null;
  regardingobjectid_msdyn_rtvproduct_fax_bind$msdyn_rtvproducts?: string | null;
  regardingobjectid_msdyn_rtvsubstatus_fax_bind$msdyn_rtvsubstatuses?: string | null;
  regardingobjectid_msdyn_shipvia_fax_bind$msdyn_shipvias?: string | null;
  regardingobjectid_msdyn_systemuserschedulersetting_fax_bind$msdyn_systemuserschedulersettinges?: string | null;
  regardingobjectid_msdyn_timegroup_fax_bind$msdyn_timegroups?: string | null;
  regardingobjectid_msdyn_timegroupdetail_fax_bind$msdyn_timegroupdetails?: string | null;
  regardingobjectid_msdyn_timeoffrequest_fax_bind$msdyn_timeoffrequests?: string | null;
  regardingobjectid_msdyn_warehouse_fax_bind$msdyn_warehouses?: string | null;
  regardingobjectid_msdyn_workorder_fax_bind$msdyn_workorders?: string | null;
  regardingobjectid_msdyn_workordercharacteristic_fax_bind$msdyn_workordercharacteristics?: string | null;
  regardingobjectid_msdyn_workorderincident_fax_bind$msdyn_workorderincidents?: string | null;
  regardingobjectid_msdyn_workorderproduct_fax_bind$msdyn_workorderproducts?: string | null;
  regardingobjectid_msdyn_workorderresourcerestriction_fax_bind$msdyn_workorderresourcerestrictions?: string | null;
  regardingobjectid_msdyn_workorderservice_fax_bind$msdyn_workorderservices?: string | null;
  regardingobjectid_msdyn_workorderservicetask_fax_bind$msdyn_workorderservicetasks?: string | null;
  regardingobjectid_opportunity_fax_bind$opportunities?: string | null;
  regardingobjectid_quote_fax_bind$quotes?: string | null;
  regardingobjectid_salesorder_fax_bind$salesorders?: string | null;
  regardingobjectid_site_fax_bind$sites?: string | null;
  regardingobjectid_uii_action_fax_bind$uii_actions?: string | null;
  regardingobjectid_uii_hostedapplication_fax_bind$uii_hostedapplications?: string | null;
  regardingobjectid_uii_nonhostedapplication_fax_bind$uii_nonhostedapplications?: string | null;
  regardingobjectid_uii_option_fax_bind$uii_options?: string | null;
  regardingobjectid_uii_savedsession_fax_bind$uii_savedsessions?: string | null;
  regardingobjectid_uii_workflow_fax_bind$uii_workflows?: string | null;
  regardingobjectid_uii_workflow_workflowstep_mapping_fax_bind$uii_workflow_workflowstep_mappings?: string | null;
  regardingobjectid_uii_workflowstep_fax_bind$uii_workflowsteps?: string | null;
  serviceid_fax_bind$services?: string | null;
  sla_fax_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_fax_bind$transactioncurrencies?: string | null;
}
interface Fax_Create extends Fax {
  activityid_activitypointer_bind$activitypointers?: string | null;
}
interface Fax_Update extends Fax {
}
interface Fax_Select {
  activityid: WebAttribute<Fax_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<Fax_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<Fax_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<Fax_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<Fax_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  billingcode: WebAttribute<Fax_Select, { billingcode: string | null }, {  }>;
  category: WebAttribute<Fax_Select, { category: string | null }, {  }>;
  coverpagename: WebAttribute<Fax_Select, { coverpagename: string | null }, {  }>;
  createdby_guid: WebAttribute<Fax_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Fax_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Fax_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<Fax_Select, { description: string | null }, {  }>;
  directioncode: WebAttribute<Fax_Select, { directioncode: boolean | null }, {  }>;
  exchangerate: WebAttribute<Fax_Select, { exchangerate: number | null }, {  }>;
  faxnumber: WebAttribute<Fax_Select, { faxnumber: string | null }, {  }>;
  from_guid: WebAttribute<Fax_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<Fax_Select, { importsequencenumber: number | null }, {  }>;
  isbilled: WebAttribute<Fax_Select, { isbilled: boolean | null }, {  }>;
  isregularactivity: WebAttribute<Fax_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<Fax_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<Fax_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  modifiedby_guid: WebAttribute<Fax_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Fax_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Fax_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  numberofpages: WebAttribute<Fax_Select, { numberofpages: number | null }, {  }>;
  onholdtime: WebAttribute<Fax_Select, { onholdtime: number | null }, {  }>;
  overriddencreatedon: WebAttribute<Fax_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Fax_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Fax_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Fax_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Fax_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  prioritycode: WebAttribute<Fax_Select, { prioritycode: fax_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<Fax_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<Fax_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<Fax_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<Fax_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<Fax_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  serviceid_guid: WebAttribute<Fax_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<Fax_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<Fax_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<Fax_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<Fax_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Fax_Select, { statecode: fax_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Fax_Select, { statuscode: fax_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<Fax_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<Fax_Select, { subject: string | null }, {  }>;
  subscriptionid: WebAttribute<Fax_Select, { subscriptionid: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<Fax_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<Fax_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<Fax_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Fax_Select, { traversedpath: string | null }, {  }>;
  tsid: WebAttribute<Fax_Select, { tsid: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Fax_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Fax_Select, { versionnumber: number | null }, {  }>;
}
interface Fax_Filter {
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  billingcode: string;
  category: string;
  coverpagename: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  directioncode: boolean;
  exchangerate: any;
  faxnumber: string;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  isbilled: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  numberofpages: number;
  onholdtime: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  prioritycode: fax_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: fax_statecode;
  statuscode: fax_statuscode;
  subcategory: string;
  subject: string;
  subscriptionid: XQW.Guid;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  tsid: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface Fax_Expand {
  Fax_Annotation: WebExpand<Fax_Expand, Annotation_Select, Annotation_Filter, { Fax_Annotation: Annotation_Result[] }>;
  Fax_AsyncOperations: WebExpand<Fax_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Fax_AsyncOperations: AsyncOperation_Result[] }>;
  Fax_BulkDeleteFailures: WebExpand<Fax_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Fax_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Fax_DuplicateBaseRecord: WebExpand<Fax_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Fax_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Fax_DuplicateMatchingRecord: WebExpand<Fax_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Fax_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Fax_ProcessSessions: WebExpand<Fax_Expand, ProcessSession_Select, ProcessSession_Filter, { Fax_ProcessSessions: ProcessSession_Result[] }>;
  Fax_QueueItem: WebExpand<Fax_Expand, QueueItem_Select, QueueItem_Filter, { Fax_QueueItem: QueueItem_Result[] }>;
  Fax_SyncErrors: WebExpand<Fax_Expand, SyncError_Select, SyncError_Filter, { Fax_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<Fax_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  createdby_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { createdby_fax: SystemUser_Result }>;
  createdonbehalfby_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_fax: SystemUser_Result }>;
  fax_actioncard: WebExpand<Fax_Expand, ActionCard_Select, ActionCard_Filter, { fax_actioncard: ActionCard_Result[] }>;
  fax_activity_parties: WebExpand<Fax_Expand, ActivityParty_Select, ActivityParty_Filter, { fax_activity_parties: ActivityParty_Result[] }>;
  fax_campaignresponse: WebExpand<Fax_Expand, CampaignResponse_Select, CampaignResponse_Filter, { fax_campaignresponse: CampaignResponse_Result[] }>;
  fax_connections1: WebExpand<Fax_Expand, Connection_Select, Connection_Filter, { fax_connections1: Connection_Result[] }>;
  fax_connections2: WebExpand<Fax_Expand, Connection_Select, Connection_Filter, { fax_connections2: Connection_Result[] }>;
  fax_principalobjectattributeaccess: WebExpand<Fax_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { fax_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  modifiedby_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_fax: SystemUser_Result }>;
  modifiedonbehalfby_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_fax: SystemUser_Result }>;
  ownerid_fax: WebExpand<Fax_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_fax: SystemUser_Result } & { ownerid_fax: Team_Result }>;
  owningbusinessunit_fax: WebExpand<Fax_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_fax: BusinessUnit_Result }>;
  owningteam_fax: WebExpand<Fax_Expand, Team_Select, Team_Filter, { owningteam_fax: Team_Result }>;
  owninguser_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_fax: SystemUser_Result }>;
  regardingobjectid_account_fax: WebExpand<Fax_Expand, Account_Select, Account_Filter, { regardingobjectid_account_fax: Account_Result }>;
  regardingobjectid_bookableresourcebooking_fax: WebExpand<Fax_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_fax: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_fax: WebExpand<Fax_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_fax: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_fax: WebExpand<Fax_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_fax: BulkOperation_Result }>;
  regardingobjectid_campaign_fax: WebExpand<Fax_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_fax: Campaign_Result }>;
  regardingobjectid_campaignactivity_fax: WebExpand<Fax_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_fax: CampaignActivity_Result }>;
  regardingobjectid_contact_fax: WebExpand<Fax_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_fax: Contact_Result }>;
  regardingobjectid_contract_fax: WebExpand<Fax_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_fax: Contract_Result }>;
  regardingobjectid_entitlement_fax: WebExpand<Fax_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_fax: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_fax: WebExpand<Fax_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_fax: EntitlementTemplate_Result }>;
  regardingobjectid_incident_fax: WebExpand<Fax_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_fax: Incident_Result }>;
  regardingobjectid_invoice_fax: WebExpand<Fax_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_fax: Invoice_Result }>;
  regardingobjectid_knowledgearticle_fax: WebExpand<Fax_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_fax: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_fax: WebExpand<Fax_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_fax: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_fax: WebExpand<Fax_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_fax: Lead_Result }>;
  regardingobjectid_msdyn_agreement_fax: WebExpand<Fax_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { regardingobjectid_msdyn_agreement_fax: msdyn_agreement_Result }>;
  regardingobjectid_msdyn_agreementbookingdate_fax: WebExpand<Fax_Expand, msdyn_agreementbookingdate_Select, msdyn_agreementbookingdate_Filter, { regardingobjectid_msdyn_agreementbookingdate_fax: msdyn_agreementbookingdate_Result }>;
  regardingobjectid_msdyn_agreementbookingincident_fax: WebExpand<Fax_Expand, msdyn_agreementbookingincident_Select, msdyn_agreementbookingincident_Filter, { regardingobjectid_msdyn_agreementbookingincident_fax: msdyn_agreementbookingincident_Result }>;
  regardingobjectid_msdyn_agreementbookingproduct_fax: WebExpand<Fax_Expand, msdyn_agreementbookingproduct_Select, msdyn_agreementbookingproduct_Filter, { regardingobjectid_msdyn_agreementbookingproduct_fax: msdyn_agreementbookingproduct_Result }>;
  regardingobjectid_msdyn_agreementbookingservice_fax: WebExpand<Fax_Expand, msdyn_agreementbookingservice_Select, msdyn_agreementbookingservice_Filter, { regardingobjectid_msdyn_agreementbookingservice_fax: msdyn_agreementbookingservice_Result }>;
  regardingobjectid_msdyn_agreementbookingservicetask_fax: WebExpand<Fax_Expand, msdyn_agreementbookingservicetask_Select, msdyn_agreementbookingservicetask_Filter, { regardingobjectid_msdyn_agreementbookingservicetask_fax: msdyn_agreementbookingservicetask_Result }>;
  regardingobjectid_msdyn_agreementbookingsetup_fax: WebExpand<Fax_Expand, msdyn_agreementbookingsetup_Select, msdyn_agreementbookingsetup_Filter, { regardingobjectid_msdyn_agreementbookingsetup_fax: msdyn_agreementbookingsetup_Result }>;
  regardingobjectid_msdyn_agreementinvoicedate_fax: WebExpand<Fax_Expand, msdyn_agreementinvoicedate_Select, msdyn_agreementinvoicedate_Filter, { regardingobjectid_msdyn_agreementinvoicedate_fax: msdyn_agreementinvoicedate_Result }>;
  regardingobjectid_msdyn_agreementinvoiceproduct_fax: WebExpand<Fax_Expand, msdyn_agreementinvoiceproduct_Select, msdyn_agreementinvoiceproduct_Filter, { regardingobjectid_msdyn_agreementinvoiceproduct_fax: msdyn_agreementinvoiceproduct_Result }>;
  regardingobjectid_msdyn_agreementinvoicesetup_fax: WebExpand<Fax_Expand, msdyn_agreementinvoicesetup_Select, msdyn_agreementinvoicesetup_Filter, { regardingobjectid_msdyn_agreementinvoicesetup_fax: msdyn_agreementinvoicesetup_Result }>;
  regardingobjectid_msdyn_bookingalertstatus_fax: WebExpand<Fax_Expand, msdyn_bookingalertstatus_Select, msdyn_bookingalertstatus_Filter, { regardingobjectid_msdyn_bookingalertstatus_fax: msdyn_bookingalertstatus_Result }>;
  regardingobjectid_msdyn_bookingrule_fax: WebExpand<Fax_Expand, msdyn_bookingrule_Select, msdyn_bookingrule_Filter, { regardingobjectid_msdyn_bookingrule_fax: msdyn_bookingrule_Result }>;
  regardingobjectid_msdyn_bookingtimestamp_fax: WebExpand<Fax_Expand, msdyn_bookingtimestamp_Select, msdyn_bookingtimestamp_Filter, { regardingobjectid_msdyn_bookingtimestamp_fax: msdyn_bookingtimestamp_Result }>;
  regardingobjectid_msdyn_customerasset_fax: WebExpand<Fax_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { regardingobjectid_msdyn_customerasset_fax: msdyn_customerasset_Result }>;
  regardingobjectid_msdyn_fieldservicesetting_fax: WebExpand<Fax_Expand, msdyn_fieldservicesetting_Select, msdyn_fieldservicesetting_Filter, { regardingobjectid_msdyn_fieldservicesetting_fax: msdyn_fieldservicesetting_Result }>;
  regardingobjectid_msdyn_incidenttypecharacteristic_fax: WebExpand<Fax_Expand, msdyn_incidenttypecharacteristic_Select, msdyn_incidenttypecharacteristic_Filter, { regardingobjectid_msdyn_incidenttypecharacteristic_fax: msdyn_incidenttypecharacteristic_Result }>;
  regardingobjectid_msdyn_incidenttypeproduct_fax: WebExpand<Fax_Expand, msdyn_incidenttypeproduct_Select, msdyn_incidenttypeproduct_Filter, { regardingobjectid_msdyn_incidenttypeproduct_fax: msdyn_incidenttypeproduct_Result }>;
  regardingobjectid_msdyn_incidenttypeservice_fax: WebExpand<Fax_Expand, msdyn_incidenttypeservice_Select, msdyn_incidenttypeservice_Filter, { regardingobjectid_msdyn_incidenttypeservice_fax: msdyn_incidenttypeservice_Result }>;
  regardingobjectid_msdyn_inventoryadjustment_fax: WebExpand<Fax_Expand, msdyn_inventoryadjustment_Select, msdyn_inventoryadjustment_Filter, { regardingobjectid_msdyn_inventoryadjustment_fax: msdyn_inventoryadjustment_Result }>;
  regardingobjectid_msdyn_inventoryadjustmentproduct_fax: WebExpand<Fax_Expand, msdyn_inventoryadjustmentproduct_Select, msdyn_inventoryadjustmentproduct_Filter, { regardingobjectid_msdyn_inventoryadjustmentproduct_fax: msdyn_inventoryadjustmentproduct_Result }>;
  regardingobjectid_msdyn_inventoryjournal_fax: WebExpand<Fax_Expand, msdyn_inventoryjournal_Select, msdyn_inventoryjournal_Filter, { regardingobjectid_msdyn_inventoryjournal_fax: msdyn_inventoryjournal_Result }>;
  regardingobjectid_msdyn_inventorytransfer_fax: WebExpand<Fax_Expand, msdyn_inventorytransfer_Select, msdyn_inventorytransfer_Filter, { regardingobjectid_msdyn_inventorytransfer_fax: msdyn_inventorytransfer_Result }>;
  regardingobjectid_msdyn_payment_fax: WebExpand<Fax_Expand, msdyn_payment_Select, msdyn_payment_Filter, { regardingobjectid_msdyn_payment_fax: msdyn_payment_Result }>;
  regardingobjectid_msdyn_paymentdetail_fax: WebExpand<Fax_Expand, msdyn_paymentdetail_Select, msdyn_paymentdetail_Filter, { regardingobjectid_msdyn_paymentdetail_fax: msdyn_paymentdetail_Result }>;
  regardingobjectid_msdyn_paymentmethod_fax: WebExpand<Fax_Expand, msdyn_paymentmethod_Select, msdyn_paymentmethod_Filter, { regardingobjectid_msdyn_paymentmethod_fax: msdyn_paymentmethod_Result }>;
  regardingobjectid_msdyn_paymentterm_fax: WebExpand<Fax_Expand, msdyn_paymentterm_Select, msdyn_paymentterm_Filter, { regardingobjectid_msdyn_paymentterm_fax: msdyn_paymentterm_Result }>;
  regardingobjectid_msdyn_playbookinstance_fax: WebExpand<Fax_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_fax: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_fax: WebExpand<Fax_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_fax: msdyn_PostAlbum_Result }>;
  regardingobjectid_msdyn_postalcode_fax: WebExpand<Fax_Expand, msdyn_postalcode_Select, msdyn_postalcode_Filter, { regardingobjectid_msdyn_postalcode_fax: msdyn_postalcode_Result }>;
  regardingobjectid_msdyn_processnotes_fax: WebExpand<Fax_Expand, msdyn_processnotes_Select, msdyn_processnotes_Filter, { regardingobjectid_msdyn_processnotes_fax: msdyn_processnotes_Result }>;
  regardingobjectid_msdyn_productinventory_fax: WebExpand<Fax_Expand, msdyn_productinventory_Select, msdyn_productinventory_Filter, { regardingobjectid_msdyn_productinventory_fax: msdyn_productinventory_Result }>;
  regardingobjectid_msdyn_projectteam_fax: WebExpand<Fax_Expand, msdyn_projectteam_Select, msdyn_projectteam_Filter, { regardingobjectid_msdyn_projectteam_fax: msdyn_projectteam_Result }>;
  regardingobjectid_msdyn_purchaseorder_fax: WebExpand<Fax_Expand, msdyn_purchaseorder_Select, msdyn_purchaseorder_Filter, { regardingobjectid_msdyn_purchaseorder_fax: msdyn_purchaseorder_Result }>;
  regardingobjectid_msdyn_purchaseorderbill_fax: WebExpand<Fax_Expand, msdyn_purchaseorderbill_Select, msdyn_purchaseorderbill_Filter, { regardingobjectid_msdyn_purchaseorderbill_fax: msdyn_purchaseorderbill_Result }>;
  regardingobjectid_msdyn_purchaseorderproduct_fax: WebExpand<Fax_Expand, msdyn_purchaseorderproduct_Select, msdyn_purchaseorderproduct_Filter, { regardingobjectid_msdyn_purchaseorderproduct_fax: msdyn_purchaseorderproduct_Result }>;
  regardingobjectid_msdyn_purchaseorderreceipt_fax: WebExpand<Fax_Expand, msdyn_purchaseorderreceipt_Select, msdyn_purchaseorderreceipt_Filter, { regardingobjectid_msdyn_purchaseorderreceipt_fax: msdyn_purchaseorderreceipt_Result }>;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_fax: WebExpand<Fax_Expand, msdyn_purchaseorderreceiptproduct_Select, msdyn_purchaseorderreceiptproduct_Filter, { regardingobjectid_msdyn_purchaseorderreceiptproduct_fax: msdyn_purchaseorderreceiptproduct_Result }>;
  regardingobjectid_msdyn_purchaseordersubstatus_fax: WebExpand<Fax_Expand, msdyn_purchaseordersubstatus_Select, msdyn_purchaseordersubstatus_Filter, { regardingobjectid_msdyn_purchaseordersubstatus_fax: msdyn_purchaseordersubstatus_Result }>;
  regardingobjectid_msdyn_quotebookingincident_fax: WebExpand<Fax_Expand, msdyn_quotebookingincident_Select, msdyn_quotebookingincident_Filter, { regardingobjectid_msdyn_quotebookingincident_fax: msdyn_quotebookingincident_Result }>;
  regardingobjectid_msdyn_quotebookingproduct_fax: WebExpand<Fax_Expand, msdyn_quotebookingproduct_Select, msdyn_quotebookingproduct_Filter, { regardingobjectid_msdyn_quotebookingproduct_fax: msdyn_quotebookingproduct_Result }>;
  regardingobjectid_msdyn_quotebookingservice_fax: WebExpand<Fax_Expand, msdyn_quotebookingservice_Select, msdyn_quotebookingservice_Filter, { regardingobjectid_msdyn_quotebookingservice_fax: msdyn_quotebookingservice_Result }>;
  regardingobjectid_msdyn_quotebookingservicetask_fax: WebExpand<Fax_Expand, msdyn_quotebookingservicetask_Select, msdyn_quotebookingservicetask_Filter, { regardingobjectid_msdyn_quotebookingservicetask_fax: msdyn_quotebookingservicetask_Result }>;
  regardingobjectid_msdyn_resourceterritory_fax: WebExpand<Fax_Expand, msdyn_resourceterritory_Select, msdyn_resourceterritory_Filter, { regardingobjectid_msdyn_resourceterritory_fax: msdyn_resourceterritory_Result }>;
  regardingobjectid_msdyn_rma_fax: WebExpand<Fax_Expand, msdyn_rma_Select, msdyn_rma_Filter, { regardingobjectid_msdyn_rma_fax: msdyn_rma_Result }>;
  regardingobjectid_msdyn_rmaproduct_fax: WebExpand<Fax_Expand, msdyn_rmaproduct_Select, msdyn_rmaproduct_Filter, { regardingobjectid_msdyn_rmaproduct_fax: msdyn_rmaproduct_Result }>;
  regardingobjectid_msdyn_rmareceipt_fax: WebExpand<Fax_Expand, msdyn_rmareceipt_Select, msdyn_rmareceipt_Filter, { regardingobjectid_msdyn_rmareceipt_fax: msdyn_rmareceipt_Result }>;
  regardingobjectid_msdyn_rmareceiptproduct_fax: WebExpand<Fax_Expand, msdyn_rmareceiptproduct_Select, msdyn_rmareceiptproduct_Filter, { regardingobjectid_msdyn_rmareceiptproduct_fax: msdyn_rmareceiptproduct_Result }>;
  regardingobjectid_msdyn_rmasubstatus_fax: WebExpand<Fax_Expand, msdyn_rmasubstatus_Select, msdyn_rmasubstatus_Filter, { regardingobjectid_msdyn_rmasubstatus_fax: msdyn_rmasubstatus_Result }>;
  regardingobjectid_msdyn_rtv_fax: WebExpand<Fax_Expand, msdyn_rtv_Select, msdyn_rtv_Filter, { regardingobjectid_msdyn_rtv_fax: msdyn_rtv_Result }>;
  regardingobjectid_msdyn_rtvproduct_fax: WebExpand<Fax_Expand, msdyn_rtvproduct_Select, msdyn_rtvproduct_Filter, { regardingobjectid_msdyn_rtvproduct_fax: msdyn_rtvproduct_Result }>;
  regardingobjectid_msdyn_rtvsubstatus_fax: WebExpand<Fax_Expand, msdyn_rtvsubstatus_Select, msdyn_rtvsubstatus_Filter, { regardingobjectid_msdyn_rtvsubstatus_fax: msdyn_rtvsubstatus_Result }>;
  regardingobjectid_msdyn_shipvia_fax: WebExpand<Fax_Expand, msdyn_shipvia_Select, msdyn_shipvia_Filter, { regardingobjectid_msdyn_shipvia_fax: msdyn_shipvia_Result }>;
  regardingobjectid_msdyn_systemuserschedulersetting_fax: WebExpand<Fax_Expand, msdyn_systemuserschedulersetting_Select, msdyn_systemuserschedulersetting_Filter, { regardingobjectid_msdyn_systemuserschedulersetting_fax: msdyn_systemuserschedulersetting_Result }>;
  regardingobjectid_msdyn_timegroup_fax: WebExpand<Fax_Expand, msdyn_timegroup_Select, msdyn_timegroup_Filter, { regardingobjectid_msdyn_timegroup_fax: msdyn_timegroup_Result }>;
  regardingobjectid_msdyn_timegroupdetail_fax: WebExpand<Fax_Expand, msdyn_timegroupdetail_Select, msdyn_timegroupdetail_Filter, { regardingobjectid_msdyn_timegroupdetail_fax: msdyn_timegroupdetail_Result }>;
  regardingobjectid_msdyn_timeoffrequest_fax: WebExpand<Fax_Expand, msdyn_timeoffrequest_Select, msdyn_timeoffrequest_Filter, { regardingobjectid_msdyn_timeoffrequest_fax: msdyn_timeoffrequest_Result }>;
  regardingobjectid_msdyn_warehouse_fax: WebExpand<Fax_Expand, msdyn_warehouse_Select, msdyn_warehouse_Filter, { regardingobjectid_msdyn_warehouse_fax: msdyn_warehouse_Result }>;
  regardingobjectid_msdyn_workorder_fax: WebExpand<Fax_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { regardingobjectid_msdyn_workorder_fax: msdyn_workorder_Result }>;
  regardingobjectid_msdyn_workordercharacteristic_fax: WebExpand<Fax_Expand, msdyn_workordercharacteristic_Select, msdyn_workordercharacteristic_Filter, { regardingobjectid_msdyn_workordercharacteristic_fax: msdyn_workordercharacteristic_Result }>;
  regardingobjectid_msdyn_workorderincident_fax: WebExpand<Fax_Expand, msdyn_workorderincident_Select, msdyn_workorderincident_Filter, { regardingobjectid_msdyn_workorderincident_fax: msdyn_workorderincident_Result }>;
  regardingobjectid_msdyn_workorderproduct_fax: WebExpand<Fax_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { regardingobjectid_msdyn_workorderproduct_fax: msdyn_workorderproduct_Result }>;
  regardingobjectid_msdyn_workorderresourcerestriction_fax: WebExpand<Fax_Expand, msdyn_workorderresourcerestriction_Select, msdyn_workorderresourcerestriction_Filter, { regardingobjectid_msdyn_workorderresourcerestriction_fax: msdyn_workorderresourcerestriction_Result }>;
  regardingobjectid_msdyn_workorderservice_fax: WebExpand<Fax_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { regardingobjectid_msdyn_workorderservice_fax: msdyn_workorderservice_Result }>;
  regardingobjectid_msdyn_workorderservicetask_fax: WebExpand<Fax_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { regardingobjectid_msdyn_workorderservicetask_fax: msdyn_workorderservicetask_Result }>;
  regardingobjectid_opportunity_fax: WebExpand<Fax_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_fax: Opportunity_Result }>;
  regardingobjectid_quote_fax: WebExpand<Fax_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_fax: Quote_Result }>;
  regardingobjectid_salesorder_fax: WebExpand<Fax_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_fax: SalesOrder_Result }>;
  regardingobjectid_site_fax: WebExpand<Fax_Expand, Site_Select, Site_Filter, { regardingobjectid_site_fax: Site_Result }>;
  regardingobjectid_uii_action_fax: WebExpand<Fax_Expand, UII_action_Select, UII_action_Filter, { regardingobjectid_uii_action_fax: UII_action_Result }>;
  regardingobjectid_uii_hostedapplication_fax: WebExpand<Fax_Expand, UII_hostedapplication_Select, UII_hostedapplication_Filter, { regardingobjectid_uii_hostedapplication_fax: UII_hostedapplication_Result }>;
  regardingobjectid_uii_nonhostedapplication_fax: WebExpand<Fax_Expand, UII_nonhostedapplication_Select, UII_nonhostedapplication_Filter, { regardingobjectid_uii_nonhostedapplication_fax: UII_nonhostedapplication_Result }>;
  regardingobjectid_uii_option_fax: WebExpand<Fax_Expand, uii_option_Select, uii_option_Filter, { regardingobjectid_uii_option_fax: uii_option_Result }>;
  regardingobjectid_uii_savedsession_fax: WebExpand<Fax_Expand, UII_savedsession_Select, UII_savedsession_Filter, { regardingobjectid_uii_savedsession_fax: UII_savedsession_Result }>;
  regardingobjectid_uii_workflow_fax: WebExpand<Fax_Expand, UII_workflow_Select, UII_workflow_Filter, { regardingobjectid_uii_workflow_fax: UII_workflow_Result }>;
  regardingobjectid_uii_workflow_workflowstep_mapping_fax: WebExpand<Fax_Expand, UII_workflow_workflowstep_mapping_Select, UII_workflow_workflowstep_mapping_Filter, { regardingobjectid_uii_workflow_workflowstep_mapping_fax: UII_workflow_workflowstep_mapping_Result }>;
  regardingobjectid_uii_workflowstep_fax: WebExpand<Fax_Expand, UII_workflowstep_Select, UII_workflowstep_Filter, { regardingobjectid_uii_workflowstep_fax: UII_workflowstep_Result }>;
  serviceid_fax: WebExpand<Fax_Expand, Service_Select, Service_Filter, { serviceid_fax: Service_Result }>;
  sla_fax_sla: WebExpand<Fax_Expand, SLA_Select, SLA_Filter, { sla_fax_sla: SLA_Result }>;
  slainvokedid_fax_sla: WebExpand<Fax_Expand, SLA_Select, SLA_Filter, { slainvokedid_fax_sla: SLA_Result }>;
  slakpiinstance_fax: WebExpand<Fax_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_fax: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<Fax_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid_fax: WebExpand<Fax_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_fax: TransactionCurrency_Result }>;
  userentityinstancedata_fax: WebExpand<Fax_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_fax: UserEntityInstanceData_Result[] }>;
}
interface Fax_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  from_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Fax_Result extends Fax_Base, Fax_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Fax_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_fax: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_fax1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_fax: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_fax: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_fax: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_bookableresourcebooking_fax: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_fax: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_fax: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_fax: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_fax: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_fax: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_fax: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_fax: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_fax: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_fax: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_fax: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_fax: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_fax: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_fax: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_agreement_fax: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingdate_fax: WebMappingRetrieve<msdyn_agreementbookingdate_Select,msdyn_agreementbookingdate_Expand,msdyn_agreementbookingdate_Filter,msdyn_agreementbookingdate_Fixed,msdyn_agreementbookingdate_Result,msdyn_agreementbookingdate_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingincident_fax: WebMappingRetrieve<msdyn_agreementbookingincident_Select,msdyn_agreementbookingincident_Expand,msdyn_agreementbookingincident_Filter,msdyn_agreementbookingincident_Fixed,msdyn_agreementbookingincident_Result,msdyn_agreementbookingincident_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingproduct_fax: WebMappingRetrieve<msdyn_agreementbookingproduct_Select,msdyn_agreementbookingproduct_Expand,msdyn_agreementbookingproduct_Filter,msdyn_agreementbookingproduct_Fixed,msdyn_agreementbookingproduct_Result,msdyn_agreementbookingproduct_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingservice_fax: WebMappingRetrieve<msdyn_agreementbookingservice_Select,msdyn_agreementbookingservice_Expand,msdyn_agreementbookingservice_Filter,msdyn_agreementbookingservice_Fixed,msdyn_agreementbookingservice_Result,msdyn_agreementbookingservice_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingservicetask_fax: WebMappingRetrieve<msdyn_agreementbookingservicetask_Select,msdyn_agreementbookingservicetask_Expand,msdyn_agreementbookingservicetask_Filter,msdyn_agreementbookingservicetask_Fixed,msdyn_agreementbookingservicetask_Result,msdyn_agreementbookingservicetask_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingsetup_fax: WebMappingRetrieve<msdyn_agreementbookingsetup_Select,msdyn_agreementbookingsetup_Expand,msdyn_agreementbookingsetup_Filter,msdyn_agreementbookingsetup_Fixed,msdyn_agreementbookingsetup_Result,msdyn_agreementbookingsetup_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoicedate_fax: WebMappingRetrieve<msdyn_agreementinvoicedate_Select,msdyn_agreementinvoicedate_Expand,msdyn_agreementinvoicedate_Filter,msdyn_agreementinvoicedate_Fixed,msdyn_agreementinvoicedate_Result,msdyn_agreementinvoicedate_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoiceproduct_fax: WebMappingRetrieve<msdyn_agreementinvoiceproduct_Select,msdyn_agreementinvoiceproduct_Expand,msdyn_agreementinvoiceproduct_Filter,msdyn_agreementinvoiceproduct_Fixed,msdyn_agreementinvoiceproduct_Result,msdyn_agreementinvoiceproduct_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoicesetup_fax: WebMappingRetrieve<msdyn_agreementinvoicesetup_Select,msdyn_agreementinvoicesetup_Expand,msdyn_agreementinvoicesetup_Filter,msdyn_agreementinvoicesetup_Fixed,msdyn_agreementinvoicesetup_Result,msdyn_agreementinvoicesetup_FormattedResult>;
  regardingobjectid_msdyn_bookingalertstatus_fax: WebMappingRetrieve<msdyn_bookingalertstatus_Select,msdyn_bookingalertstatus_Expand,msdyn_bookingalertstatus_Filter,msdyn_bookingalertstatus_Fixed,msdyn_bookingalertstatus_Result,msdyn_bookingalertstatus_FormattedResult>;
  regardingobjectid_msdyn_bookingrule_fax: WebMappingRetrieve<msdyn_bookingrule_Select,msdyn_bookingrule_Expand,msdyn_bookingrule_Filter,msdyn_bookingrule_Fixed,msdyn_bookingrule_Result,msdyn_bookingrule_FormattedResult>;
  regardingobjectid_msdyn_bookingtimestamp_fax: WebMappingRetrieve<msdyn_bookingtimestamp_Select,msdyn_bookingtimestamp_Expand,msdyn_bookingtimestamp_Filter,msdyn_bookingtimestamp_Fixed,msdyn_bookingtimestamp_Result,msdyn_bookingtimestamp_FormattedResult>;
  regardingobjectid_msdyn_customerasset_fax: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  regardingobjectid_msdyn_fieldservicesetting_fax: WebMappingRetrieve<msdyn_fieldservicesetting_Select,msdyn_fieldservicesetting_Expand,msdyn_fieldservicesetting_Filter,msdyn_fieldservicesetting_Fixed,msdyn_fieldservicesetting_Result,msdyn_fieldservicesetting_FormattedResult>;
  regardingobjectid_msdyn_incidenttypecharacteristic_fax: WebMappingRetrieve<msdyn_incidenttypecharacteristic_Select,msdyn_incidenttypecharacteristic_Expand,msdyn_incidenttypecharacteristic_Filter,msdyn_incidenttypecharacteristic_Fixed,msdyn_incidenttypecharacteristic_Result,msdyn_incidenttypecharacteristic_FormattedResult>;
  regardingobjectid_msdyn_incidenttypeproduct_fax: WebMappingRetrieve<msdyn_incidenttypeproduct_Select,msdyn_incidenttypeproduct_Expand,msdyn_incidenttypeproduct_Filter,msdyn_incidenttypeproduct_Fixed,msdyn_incidenttypeproduct_Result,msdyn_incidenttypeproduct_FormattedResult>;
  regardingobjectid_msdyn_incidenttypeservice_fax: WebMappingRetrieve<msdyn_incidenttypeservice_Select,msdyn_incidenttypeservice_Expand,msdyn_incidenttypeservice_Filter,msdyn_incidenttypeservice_Fixed,msdyn_incidenttypeservice_Result,msdyn_incidenttypeservice_FormattedResult>;
  regardingobjectid_msdyn_inventoryadjustment_fax: WebMappingRetrieve<msdyn_inventoryadjustment_Select,msdyn_inventoryadjustment_Expand,msdyn_inventoryadjustment_Filter,msdyn_inventoryadjustment_Fixed,msdyn_inventoryadjustment_Result,msdyn_inventoryadjustment_FormattedResult>;
  regardingobjectid_msdyn_inventoryadjustmentproduct_fax: WebMappingRetrieve<msdyn_inventoryadjustmentproduct_Select,msdyn_inventoryadjustmentproduct_Expand,msdyn_inventoryadjustmentproduct_Filter,msdyn_inventoryadjustmentproduct_Fixed,msdyn_inventoryadjustmentproduct_Result,msdyn_inventoryadjustmentproduct_FormattedResult>;
  regardingobjectid_msdyn_inventoryjournal_fax: WebMappingRetrieve<msdyn_inventoryjournal_Select,msdyn_inventoryjournal_Expand,msdyn_inventoryjournal_Filter,msdyn_inventoryjournal_Fixed,msdyn_inventoryjournal_Result,msdyn_inventoryjournal_FormattedResult>;
  regardingobjectid_msdyn_inventorytransfer_fax: WebMappingRetrieve<msdyn_inventorytransfer_Select,msdyn_inventorytransfer_Expand,msdyn_inventorytransfer_Filter,msdyn_inventorytransfer_Fixed,msdyn_inventorytransfer_Result,msdyn_inventorytransfer_FormattedResult>;
  regardingobjectid_msdyn_payment_fax: WebMappingRetrieve<msdyn_payment_Select,msdyn_payment_Expand,msdyn_payment_Filter,msdyn_payment_Fixed,msdyn_payment_Result,msdyn_payment_FormattedResult>;
  regardingobjectid_msdyn_paymentdetail_fax: WebMappingRetrieve<msdyn_paymentdetail_Select,msdyn_paymentdetail_Expand,msdyn_paymentdetail_Filter,msdyn_paymentdetail_Fixed,msdyn_paymentdetail_Result,msdyn_paymentdetail_FormattedResult>;
  regardingobjectid_msdyn_paymentmethod_fax: WebMappingRetrieve<msdyn_paymentmethod_Select,msdyn_paymentmethod_Expand,msdyn_paymentmethod_Filter,msdyn_paymentmethod_Fixed,msdyn_paymentmethod_Result,msdyn_paymentmethod_FormattedResult>;
  regardingobjectid_msdyn_paymentterm_fax: WebMappingRetrieve<msdyn_paymentterm_Select,msdyn_paymentterm_Expand,msdyn_paymentterm_Filter,msdyn_paymentterm_Fixed,msdyn_paymentterm_Result,msdyn_paymentterm_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_fax: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_fax: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_msdyn_postalcode_fax: WebMappingRetrieve<msdyn_postalcode_Select,msdyn_postalcode_Expand,msdyn_postalcode_Filter,msdyn_postalcode_Fixed,msdyn_postalcode_Result,msdyn_postalcode_FormattedResult>;
  regardingobjectid_msdyn_processnotes_fax: WebMappingRetrieve<msdyn_processnotes_Select,msdyn_processnotes_Expand,msdyn_processnotes_Filter,msdyn_processnotes_Fixed,msdyn_processnotes_Result,msdyn_processnotes_FormattedResult>;
  regardingobjectid_msdyn_productinventory_fax: WebMappingRetrieve<msdyn_productinventory_Select,msdyn_productinventory_Expand,msdyn_productinventory_Filter,msdyn_productinventory_Fixed,msdyn_productinventory_Result,msdyn_productinventory_FormattedResult>;
  regardingobjectid_msdyn_projectteam_fax: WebMappingRetrieve<msdyn_projectteam_Select,msdyn_projectteam_Expand,msdyn_projectteam_Filter,msdyn_projectteam_Fixed,msdyn_projectteam_Result,msdyn_projectteam_FormattedResult>;
  regardingobjectid_msdyn_purchaseorder_fax: WebMappingRetrieve<msdyn_purchaseorder_Select,msdyn_purchaseorder_Expand,msdyn_purchaseorder_Filter,msdyn_purchaseorder_Fixed,msdyn_purchaseorder_Result,msdyn_purchaseorder_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderbill_fax: WebMappingRetrieve<msdyn_purchaseorderbill_Select,msdyn_purchaseorderbill_Expand,msdyn_purchaseorderbill_Filter,msdyn_purchaseorderbill_Fixed,msdyn_purchaseorderbill_Result,msdyn_purchaseorderbill_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderproduct_fax: WebMappingRetrieve<msdyn_purchaseorderproduct_Select,msdyn_purchaseorderproduct_Expand,msdyn_purchaseorderproduct_Filter,msdyn_purchaseorderproduct_Fixed,msdyn_purchaseorderproduct_Result,msdyn_purchaseorderproduct_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderreceipt_fax: WebMappingRetrieve<msdyn_purchaseorderreceipt_Select,msdyn_purchaseorderreceipt_Expand,msdyn_purchaseorderreceipt_Filter,msdyn_purchaseorderreceipt_Fixed,msdyn_purchaseorderreceipt_Result,msdyn_purchaseorderreceipt_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderreceiptproduct_fax: WebMappingRetrieve<msdyn_purchaseorderreceiptproduct_Select,msdyn_purchaseorderreceiptproduct_Expand,msdyn_purchaseorderreceiptproduct_Filter,msdyn_purchaseorderreceiptproduct_Fixed,msdyn_purchaseorderreceiptproduct_Result,msdyn_purchaseorderreceiptproduct_FormattedResult>;
  regardingobjectid_msdyn_purchaseordersubstatus_fax: WebMappingRetrieve<msdyn_purchaseordersubstatus_Select,msdyn_purchaseordersubstatus_Expand,msdyn_purchaseordersubstatus_Filter,msdyn_purchaseordersubstatus_Fixed,msdyn_purchaseordersubstatus_Result,msdyn_purchaseordersubstatus_FormattedResult>;
  regardingobjectid_msdyn_quotebookingincident_fax: WebMappingRetrieve<msdyn_quotebookingincident_Select,msdyn_quotebookingincident_Expand,msdyn_quotebookingincident_Filter,msdyn_quotebookingincident_Fixed,msdyn_quotebookingincident_Result,msdyn_quotebookingincident_FormattedResult>;
  regardingobjectid_msdyn_quotebookingproduct_fax: WebMappingRetrieve<msdyn_quotebookingproduct_Select,msdyn_quotebookingproduct_Expand,msdyn_quotebookingproduct_Filter,msdyn_quotebookingproduct_Fixed,msdyn_quotebookingproduct_Result,msdyn_quotebookingproduct_FormattedResult>;
  regardingobjectid_msdyn_quotebookingservice_fax: WebMappingRetrieve<msdyn_quotebookingservice_Select,msdyn_quotebookingservice_Expand,msdyn_quotebookingservice_Filter,msdyn_quotebookingservice_Fixed,msdyn_quotebookingservice_Result,msdyn_quotebookingservice_FormattedResult>;
  regardingobjectid_msdyn_quotebookingservicetask_fax: WebMappingRetrieve<msdyn_quotebookingservicetask_Select,msdyn_quotebookingservicetask_Expand,msdyn_quotebookingservicetask_Filter,msdyn_quotebookingservicetask_Fixed,msdyn_quotebookingservicetask_Result,msdyn_quotebookingservicetask_FormattedResult>;
  regardingobjectid_msdyn_resourceterritory_fax: WebMappingRetrieve<msdyn_resourceterritory_Select,msdyn_resourceterritory_Expand,msdyn_resourceterritory_Filter,msdyn_resourceterritory_Fixed,msdyn_resourceterritory_Result,msdyn_resourceterritory_FormattedResult>;
  regardingobjectid_msdyn_rma_fax: WebMappingRetrieve<msdyn_rma_Select,msdyn_rma_Expand,msdyn_rma_Filter,msdyn_rma_Fixed,msdyn_rma_Result,msdyn_rma_FormattedResult>;
  regardingobjectid_msdyn_rmaproduct_fax: WebMappingRetrieve<msdyn_rmaproduct_Select,msdyn_rmaproduct_Expand,msdyn_rmaproduct_Filter,msdyn_rmaproduct_Fixed,msdyn_rmaproduct_Result,msdyn_rmaproduct_FormattedResult>;
  regardingobjectid_msdyn_rmareceipt_fax: WebMappingRetrieve<msdyn_rmareceipt_Select,msdyn_rmareceipt_Expand,msdyn_rmareceipt_Filter,msdyn_rmareceipt_Fixed,msdyn_rmareceipt_Result,msdyn_rmareceipt_FormattedResult>;
  regardingobjectid_msdyn_rmareceiptproduct_fax: WebMappingRetrieve<msdyn_rmareceiptproduct_Select,msdyn_rmareceiptproduct_Expand,msdyn_rmareceiptproduct_Filter,msdyn_rmareceiptproduct_Fixed,msdyn_rmareceiptproduct_Result,msdyn_rmareceiptproduct_FormattedResult>;
  regardingobjectid_msdyn_rmasubstatus_fax: WebMappingRetrieve<msdyn_rmasubstatus_Select,msdyn_rmasubstatus_Expand,msdyn_rmasubstatus_Filter,msdyn_rmasubstatus_Fixed,msdyn_rmasubstatus_Result,msdyn_rmasubstatus_FormattedResult>;
  regardingobjectid_msdyn_rtv_fax: WebMappingRetrieve<msdyn_rtv_Select,msdyn_rtv_Expand,msdyn_rtv_Filter,msdyn_rtv_Fixed,msdyn_rtv_Result,msdyn_rtv_FormattedResult>;
  regardingobjectid_msdyn_rtvproduct_fax: WebMappingRetrieve<msdyn_rtvproduct_Select,msdyn_rtvproduct_Expand,msdyn_rtvproduct_Filter,msdyn_rtvproduct_Fixed,msdyn_rtvproduct_Result,msdyn_rtvproduct_FormattedResult>;
  regardingobjectid_msdyn_rtvsubstatus_fax: WebMappingRetrieve<msdyn_rtvsubstatus_Select,msdyn_rtvsubstatus_Expand,msdyn_rtvsubstatus_Filter,msdyn_rtvsubstatus_Fixed,msdyn_rtvsubstatus_Result,msdyn_rtvsubstatus_FormattedResult>;
  regardingobjectid_msdyn_shipvia_fax: WebMappingRetrieve<msdyn_shipvia_Select,msdyn_shipvia_Expand,msdyn_shipvia_Filter,msdyn_shipvia_Fixed,msdyn_shipvia_Result,msdyn_shipvia_FormattedResult>;
  regardingobjectid_msdyn_systemuserschedulersetting_fax: WebMappingRetrieve<msdyn_systemuserschedulersetting_Select,msdyn_systemuserschedulersetting_Expand,msdyn_systemuserschedulersetting_Filter,msdyn_systemuserschedulersetting_Fixed,msdyn_systemuserschedulersetting_Result,msdyn_systemuserschedulersetting_FormattedResult>;
  regardingobjectid_msdyn_timegroup_fax: WebMappingRetrieve<msdyn_timegroup_Select,msdyn_timegroup_Expand,msdyn_timegroup_Filter,msdyn_timegroup_Fixed,msdyn_timegroup_Result,msdyn_timegroup_FormattedResult>;
  regardingobjectid_msdyn_timegroupdetail_fax: WebMappingRetrieve<msdyn_timegroupdetail_Select,msdyn_timegroupdetail_Expand,msdyn_timegroupdetail_Filter,msdyn_timegroupdetail_Fixed,msdyn_timegroupdetail_Result,msdyn_timegroupdetail_FormattedResult>;
  regardingobjectid_msdyn_timeoffrequest_fax: WebMappingRetrieve<msdyn_timeoffrequest_Select,msdyn_timeoffrequest_Expand,msdyn_timeoffrequest_Filter,msdyn_timeoffrequest_Fixed,msdyn_timeoffrequest_Result,msdyn_timeoffrequest_FormattedResult>;
  regardingobjectid_msdyn_warehouse_fax: WebMappingRetrieve<msdyn_warehouse_Select,msdyn_warehouse_Expand,msdyn_warehouse_Filter,msdyn_warehouse_Fixed,msdyn_warehouse_Result,msdyn_warehouse_FormattedResult>;
  regardingobjectid_msdyn_workorder_fax: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  regardingobjectid_msdyn_workordercharacteristic_fax: WebMappingRetrieve<msdyn_workordercharacteristic_Select,msdyn_workordercharacteristic_Expand,msdyn_workordercharacteristic_Filter,msdyn_workordercharacteristic_Fixed,msdyn_workordercharacteristic_Result,msdyn_workordercharacteristic_FormattedResult>;
  regardingobjectid_msdyn_workorderincident_fax: WebMappingRetrieve<msdyn_workorderincident_Select,msdyn_workorderincident_Expand,msdyn_workorderincident_Filter,msdyn_workorderincident_Fixed,msdyn_workorderincident_Result,msdyn_workorderincident_FormattedResult>;
  regardingobjectid_msdyn_workorderproduct_fax: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  regardingobjectid_msdyn_workorderresourcerestriction_fax: WebMappingRetrieve<msdyn_workorderresourcerestriction_Select,msdyn_workorderresourcerestriction_Expand,msdyn_workorderresourcerestriction_Filter,msdyn_workorderresourcerestriction_Fixed,msdyn_workorderresourcerestriction_Result,msdyn_workorderresourcerestriction_FormattedResult>;
  regardingobjectid_msdyn_workorderservice_fax: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  regardingobjectid_msdyn_workorderservicetask_fax: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  regardingobjectid_opportunity_fax: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_fax: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_fax: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_fax: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  regardingobjectid_uii_action_fax: WebMappingRetrieve<UII_action_Select,UII_action_Expand,UII_action_Filter,UII_action_Fixed,UII_action_Result,UII_action_FormattedResult>;
  regardingobjectid_uii_hostedapplication_fax: WebMappingRetrieve<UII_hostedapplication_Select,UII_hostedapplication_Expand,UII_hostedapplication_Filter,UII_hostedapplication_Fixed,UII_hostedapplication_Result,UII_hostedapplication_FormattedResult>;
  regardingobjectid_uii_nonhostedapplication_fax: WebMappingRetrieve<UII_nonhostedapplication_Select,UII_nonhostedapplication_Expand,UII_nonhostedapplication_Filter,UII_nonhostedapplication_Fixed,UII_nonhostedapplication_Result,UII_nonhostedapplication_FormattedResult>;
  regardingobjectid_uii_option_fax: WebMappingRetrieve<uii_option_Select,uii_option_Expand,uii_option_Filter,uii_option_Fixed,uii_option_Result,uii_option_FormattedResult>;
  regardingobjectid_uii_savedsession_fax: WebMappingRetrieve<UII_savedsession_Select,UII_savedsession_Expand,UII_savedsession_Filter,UII_savedsession_Fixed,UII_savedsession_Result,UII_savedsession_FormattedResult>;
  regardingobjectid_uii_workflow_fax: WebMappingRetrieve<UII_workflow_Select,UII_workflow_Expand,UII_workflow_Filter,UII_workflow_Fixed,UII_workflow_Result,UII_workflow_FormattedResult>;
  regardingobjectid_uii_workflow_workflowstep_mapping_fax: WebMappingRetrieve<UII_workflow_workflowstep_mapping_Select,UII_workflow_workflowstep_mapping_Expand,UII_workflow_workflowstep_mapping_Filter,UII_workflow_workflowstep_mapping_Fixed,UII_workflow_workflowstep_mapping_Result,UII_workflow_workflowstep_mapping_FormattedResult>;
  regardingobjectid_uii_workflowstep_fax: WebMappingRetrieve<UII_workflowstep_Select,UII_workflowstep_Expand,UII_workflowstep_Filter,UII_workflowstep_Fixed,UII_workflowstep_Result,UII_workflowstep_FormattedResult>;
  serviceid_fax: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_fax_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_fax_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_fax: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Fax_RelatedMany {
  Fax_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Fax_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Fax_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Fax_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Fax_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Fax_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Fax_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  Fax_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  fax_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  fax_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  fax_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  fax_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  fax_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  fax_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  slakpiinstance_fax: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_fax: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
}
interface WebEntitiesRelated {
  faxes: WebMappingRelated<Fax_RelatedOne,Fax_RelatedMany>;
}
interface WebEntitiesCUDA {
  faxes: WebMappingCUDA<Fax_Create,Fax_Update,Fax_Select>;
}
