interface KnowledgeArticle_Base extends WebEntity {
  articlepublicnumber?: string | null;
  content?: string | null;
  createdon?: Date | null;
  description?: string | null;
  exchangerate?: number | null;
  expirationdate?: Date | null;
  expirationstateid?: number | null;
  expirationstatusid?: number | null;
  expiredreviewoptions?: knowledgearticle_expiredreviewoptions | null;
  importsequencenumber?: number | null;
  isinternal?: boolean | null;
  islatestversion?: boolean | null;
  isprimary?: boolean | null;
  isrootarticle?: boolean | null;
  keywords?: string | null;
  knowledgearticleid?: string | null;
  knowledgearticleviews?: number | null;
  knowledgearticleviews_date?: Date | null;
  knowledgearticleviews_state?: number | null;
  majorversionnumber?: number | null;
  minorversionnumber?: number | null;
  modifiedon?: Date | null;
  msdyn_ingestedarticleurl?: string | null;
  msdyn_isingestedarticle?: boolean | null;
  msdyn_keywordsdescsuggestioncontrol?: boolean | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  publishon?: Date | null;
  publishstatusid?: number | null;
  rating?: number | null;
  rating_count?: number | null;
  rating_date?: Date | null;
  rating_state?: number | null;
  rating_sum?: number | null;
  readyforreview?: boolean | null;
  review?: knowledgearticle_review | null;
  scheduledstatusid?: number | null;
  setcategoryassociations?: boolean | null;
  setproductassociations?: boolean | null;
  stageid?: string | null;
  statecode?: knowledgearticle_statecode | null;
  statuscode?: knowledgearticle_statuscode | null;
  timezoneruleversionnumber?: number | null;
  title?: string | null;
  traversedpath?: string | null;
  updatecontent?: boolean | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface KnowledgeArticle_Relationships {
  KnowledgeArticle_ActivityPointers?: ActivityPointer_Result[] | null;
  KnowledgeArticle_Appointments?: Appointment_Result[] | null;
  KnowledgeArticle_Emails?: Email_Result[] | null;
  KnowledgeArticle_Faxes?: Fax_Result[] | null;
  KnowledgeArticle_Feedback?: Feedback_Result[] | null;
  KnowledgeArticle_Letters?: Letter_Result[] | null;
  KnowledgeArticle_Phonecalls?: PhoneCall_Result[] | null;
  KnowledgeArticle_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  KnowledgeArticle_ServiceAppointments?: ServiceAppointment_Result[] | null;
  KnowledgeArticle_SocialActivities?: SocialActivity_Result[] | null;
  KnowledgeArticle_SyncErrors?: SyncError_Result[] | null;
  KnowledgeArticle_Tasks?: Task_Result[] | null;
  ParentArticleContentId?: KnowledgeArticle_Result | null;
  PreviousArticleContentId?: KnowledgeArticle_Result | null;
  RootArticleId?: KnowledgeArticle_Result | null;
  incident_knowledgearticles?: KnowledgeArticleIncident_Result[] | null;
  knowledgearticle_Annotations?: Annotation_Result[] | null;
  knowledgearticle_AsyncOperations?: AsyncOperation_Result[] | null;
  knowledgearticle_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  knowledgearticle_BulkOperations?: BulkOperation_Result[] | null;
  knowledgearticle_CampaignResponses?: CampaignResponse_Result[] | null;
  knowledgearticle_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  knowledgearticle_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  knowledgearticle_IncidentResolutions?: IncidentResolution_Result[] | null;
  knowledgearticle_OpportunityCloses?: OpportunityClose_Result[] | null;
  knowledgearticle_OrderCloses?: OrderClose_Result[] | null;
  knowledgearticle_PostFollows?: PostFollow_Result[] | null;
  knowledgearticle_PostRegardings?: PostRegarding_Result[] | null;
  knowledgearticle_PostRoles?: PostRole_Result[] | null;
  knowledgearticle_Posts?: Post_Result[] | null;
  knowledgearticle_PrincipalObjectAttributeAccess?: PrincipalObjectAttributeAccess_Result[] | null;
  knowledgearticle_ProcessSession?: ProcessSession_Result[] | null;
  knowledgearticle_QueueItems?: QueueItem_Result[] | null;
  knowledgearticle_QuoteCloses?: QuoteClose_Result[] | null;
  knowledgearticle_SharePointDocumentLocations?: SharePointDocumentLocation_Result[] | null;
  knowledgearticle_SharePointDocuments?: SharePointDocument_Result[] | null;
  knowledgearticle_Teams?: Team_Result[] | null;
  knowledgearticle_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  knowledgearticle_activity_parties?: ActivityParty_Result[] | null;
  knowledgearticle_category?: Category_Result[] | null;
  knowledgearticle_connections1?: Connection_Result[] | null;
  knowledgearticle_connections2?: Connection_Result[] | null;
  knowledgearticle_documentindex?: DocumentIndex_Result[] | null;
  knowledgearticle_expiredprocess?: ExpiredProcess_Result[] | null;
  knowledgearticle_msdyn_approvals?: msdyn_approval_Result[] | null;
  knowledgearticle_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  knowledgearticle_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  knowledgearticle_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  knowledgearticle_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  knowledgearticle_msfp_alerts?: msfp_alert_Result[] | null;
  knowledgearticle_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  knowledgearticle_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  knowledgearticle_newprocess?: NewProcess_Result[] | null;
  knowledgearticle_parentarticle_contentid?: KnowledgeArticle_Result[] | null;
  knowledgearticle_previousarticle_contentid?: KnowledgeArticle_Result[] | null;
  knowledgearticle_rootarticle_id?: KnowledgeArticle_Result[] | null;
  knowledgearticle_translationprocess?: TranslationProcess_Result[] | null;
  knowledgearticle_views?: KnowledgeArticleViews_Result[] | null;
  msdyn_knowledgearticle_feedback_context?: Feedback_Result[] | null;
  msdyn_knowledgearticle_msdyn_kbenrichment_kbid?: msdyn_kbenrichment_Result[] | null;
  msdyn_knowledgearticle_msdyn_knowledgearticlesuggestion_suggestedentity?: msdyn_knowledgearticlesuggestion_Result[] | null;
  msdyn_knowledgearticle_msdyn_suggestioninteraction_msdyn_suggestedentity?: msdyn_suggestioninteraction_Result[] | null;
  msdyn_knowledgearticleimage_parentknowledgearticleid?: msdyn_knowledgearticleimage_Result[] | null;
  msdyn_msdyn_kbattachment_knowledgearticle?: msdyn_kbattachment_Result[] | null;
  navigationPropertyNameNotDefined?: msdyn_customerasset_Result[] | null;
  navigationPropertyNameNotDefined1?: Product_Result[] | null;
  navigationPropertyNameNotDefined2?: msdyn_incidenttype_Result[] | null;
  navigationPropertyNameNotDefined3?: msdyn_workorder_Result[] | null;
  navigationPropertyNameNotDefined4?: msdyn_ocliveworkitem_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
}
interface KnowledgeArticle extends KnowledgeArticle_Base, KnowledgeArticle_Relationships {
  ParentArticleContentId_bind$knowledgearticles?: string | null;
  PreviousArticleContentId_bind$knowledgearticles?: string | null;
  RootArticleId_bind$knowledgearticles?: string | null;
  languagelocaleid_bind$languagelocale?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  primaryauthorid_bind$systemusers?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  subjectid_bind$subjects?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface KnowledgeArticle_Create extends KnowledgeArticle {
}
interface KnowledgeArticle_Update extends KnowledgeArticle {
}
interface KnowledgeArticle_Select {
  articlepublicnumber: WebAttribute<KnowledgeArticle_Select, { articlepublicnumber: string | null }, {  }>;
  content: WebAttribute<KnowledgeArticle_Select, { content: string | null }, {  }>;
  createdby_guid: WebAttribute<KnowledgeArticle_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<KnowledgeArticle_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<KnowledgeArticle_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<KnowledgeArticle_Select, { description: string | null }, {  }>;
  exchangerate: WebAttribute<KnowledgeArticle_Select, { exchangerate: number | null }, {  }>;
  expirationdate: WebAttribute<KnowledgeArticle_Select, { expirationdate: Date | null }, { expirationdate_formatted?: string }>;
  expirationstateid: WebAttribute<KnowledgeArticle_Select, { expirationstateid: number | null }, {  }>;
  expirationstatusid: WebAttribute<KnowledgeArticle_Select, { expirationstatusid: number | null }, {  }>;
  expiredreviewoptions: WebAttribute<KnowledgeArticle_Select, { expiredreviewoptions: knowledgearticle_expiredreviewoptions | null }, { expiredreviewoptions_formatted?: string }>;
  importsequencenumber: WebAttribute<KnowledgeArticle_Select, { importsequencenumber: number | null }, {  }>;
  isinternal: WebAttribute<KnowledgeArticle_Select, { isinternal: boolean | null }, {  }>;
  islatestversion: WebAttribute<KnowledgeArticle_Select, { islatestversion: boolean | null }, {  }>;
  isprimary: WebAttribute<KnowledgeArticle_Select, { isprimary: boolean | null }, {  }>;
  isrootarticle: WebAttribute<KnowledgeArticle_Select, { isrootarticle: boolean | null }, {  }>;
  keywords: WebAttribute<KnowledgeArticle_Select, { keywords: string | null }, {  }>;
  knowledgearticleid: WebAttribute<KnowledgeArticle_Select, { knowledgearticleid: string | null }, {  }>;
  knowledgearticleviews: WebAttribute<KnowledgeArticle_Select, { knowledgearticleviews: number | null }, {  }>;
  knowledgearticleviews_date: WebAttribute<KnowledgeArticle_Select, { knowledgearticleviews_date: Date | null }, { knowledgearticleviews_date_formatted?: string }>;
  knowledgearticleviews_state: WebAttribute<KnowledgeArticle_Select, { knowledgearticleviews_state: number | null }, {  }>;
  languagelocaleid_guid: WebAttribute<KnowledgeArticle_Select, { languagelocaleid_guid: string | null }, { languagelocaleid_formatted?: string }>;
  majorversionnumber: WebAttribute<KnowledgeArticle_Select, { majorversionnumber: number | null }, {  }>;
  minorversionnumber: WebAttribute<KnowledgeArticle_Select, { minorversionnumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<KnowledgeArticle_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<KnowledgeArticle_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<KnowledgeArticle_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_ingestedarticleurl: WebAttribute<KnowledgeArticle_Select, { msdyn_ingestedarticleurl: string | null }, {  }>;
  msdyn_isingestedarticle: WebAttribute<KnowledgeArticle_Select, { msdyn_isingestedarticle: boolean | null }, {  }>;
  msdyn_keywordsdescsuggestioncontrol: WebAttribute<KnowledgeArticle_Select, { msdyn_keywordsdescsuggestioncontrol: boolean | null }, {  }>;
  overriddencreatedon: WebAttribute<KnowledgeArticle_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<KnowledgeArticle_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<KnowledgeArticle_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<KnowledgeArticle_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<KnowledgeArticle_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  parentarticlecontentid_guid: WebAttribute<KnowledgeArticle_Select, { parentarticlecontentid_guid: string | null }, { parentarticlecontentid_formatted?: string }>;
  previousarticlecontentid_guid: WebAttribute<KnowledgeArticle_Select, { previousarticlecontentid_guid: string | null }, { previousarticlecontentid_formatted?: string }>;
  primaryauthorid_guid: WebAttribute<KnowledgeArticle_Select, { primaryauthorid_guid: string | null }, { primaryauthorid_formatted?: string }>;
  processid: WebAttribute<KnowledgeArticle_Select, { processid: string | null }, {  }>;
  publishon: WebAttribute<KnowledgeArticle_Select, { publishon: Date | null }, { publishon_formatted?: string }>;
  publishstatusid: WebAttribute<KnowledgeArticle_Select, { publishstatusid: number | null }, {  }>;
  rating: WebAttribute<KnowledgeArticle_Select, { rating: number | null }, {  }>;
  rating_count: WebAttribute<KnowledgeArticle_Select, { rating_count: number | null }, {  }>;
  rating_date: WebAttribute<KnowledgeArticle_Select, { rating_date: Date | null }, { rating_date_formatted?: string }>;
  rating_state: WebAttribute<KnowledgeArticle_Select, { rating_state: number | null }, {  }>;
  rating_sum: WebAttribute<KnowledgeArticle_Select, { rating_sum: number | null }, {  }>;
  readyforreview: WebAttribute<KnowledgeArticle_Select, { readyforreview: boolean | null }, {  }>;
  review: WebAttribute<KnowledgeArticle_Select, { review: knowledgearticle_review | null }, { review_formatted?: string }>;
  rootarticleid_guid: WebAttribute<KnowledgeArticle_Select, { rootarticleid_guid: string | null }, { rootarticleid_formatted?: string }>;
  scheduledstatusid: WebAttribute<KnowledgeArticle_Select, { scheduledstatusid: number | null }, {  }>;
  setcategoryassociations: WebAttribute<KnowledgeArticle_Select, { setcategoryassociations: boolean | null }, {  }>;
  setproductassociations: WebAttribute<KnowledgeArticle_Select, { setproductassociations: boolean | null }, {  }>;
  stageid: WebAttribute<KnowledgeArticle_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<KnowledgeArticle_Select, { statecode: knowledgearticle_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<KnowledgeArticle_Select, { statuscode: knowledgearticle_statuscode | null }, { statuscode_formatted?: string }>;
  subjectid_guid: WebAttribute<KnowledgeArticle_Select, { subjectid_guid: string | null }, { subjectid_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<KnowledgeArticle_Select, { timezoneruleversionnumber: number | null }, {  }>;
  title: WebAttribute<KnowledgeArticle_Select, { title: string | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<KnowledgeArticle_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<KnowledgeArticle_Select, { traversedpath: string | null }, {  }>;
  updatecontent: WebAttribute<KnowledgeArticle_Select, { updatecontent: boolean | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<KnowledgeArticle_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<KnowledgeArticle_Select, { versionnumber: number | null }, {  }>;
}
interface KnowledgeArticle_Filter {
  articlepublicnumber: string;
  content: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  exchangerate: any;
  expirationdate: Date;
  expirationstateid: number;
  expirationstatusid: number;
  expiredreviewoptions: knowledgearticle_expiredreviewoptions;
  importsequencenumber: number;
  isinternal: boolean;
  islatestversion: boolean;
  isprimary: boolean;
  isrootarticle: boolean;
  keywords: string;
  knowledgearticleid: XQW.Guid;
  knowledgearticleviews: number;
  knowledgearticleviews_date: Date;
  knowledgearticleviews_state: number;
  languagelocaleid_guid: XQW.Guid;
  majorversionnumber: number;
  minorversionnumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_ingestedarticleurl: string;
  msdyn_isingestedarticle: boolean;
  msdyn_keywordsdescsuggestioncontrol: boolean;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  parentarticlecontentid_guid: XQW.Guid;
  previousarticlecontentid_guid: XQW.Guid;
  primaryauthorid_guid: XQW.Guid;
  processid: XQW.Guid;
  publishon: Date;
  publishstatusid: number;
  rating: any;
  rating_count: number;
  rating_date: Date;
  rating_state: number;
  rating_sum: any;
  readyforreview: boolean;
  review: knowledgearticle_review;
  rootarticleid_guid: XQW.Guid;
  scheduledstatusid: number;
  setcategoryassociations: boolean;
  setproductassociations: boolean;
  stageid: XQW.Guid;
  statecode: knowledgearticle_statecode;
  statuscode: knowledgearticle_statuscode;
  subjectid_guid: XQW.Guid;
  timezoneruleversionnumber: number;
  title: string;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  updatecontent: boolean;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface KnowledgeArticle_Expand {
  KnowledgeArticle_ActivityPointers: WebExpand<KnowledgeArticle_Expand, ActivityPointer_Select, ActivityPointer_Filter, { KnowledgeArticle_ActivityPointers: ActivityPointer_Result[] }>;
  KnowledgeArticle_Appointments: WebExpand<KnowledgeArticle_Expand, Appointment_Select, Appointment_Filter, { KnowledgeArticle_Appointments: Appointment_Result[] }>;
  KnowledgeArticle_Emails: WebExpand<KnowledgeArticle_Expand, Email_Select, Email_Filter, { KnowledgeArticle_Emails: Email_Result[] }>;
  KnowledgeArticle_Faxes: WebExpand<KnowledgeArticle_Expand, Fax_Select, Fax_Filter, { KnowledgeArticle_Faxes: Fax_Result[] }>;
  KnowledgeArticle_Feedback: WebExpand<KnowledgeArticle_Expand, Feedback_Select, Feedback_Filter, { KnowledgeArticle_Feedback: Feedback_Result[] }>;
  KnowledgeArticle_Letters: WebExpand<KnowledgeArticle_Expand, Letter_Select, Letter_Filter, { KnowledgeArticle_Letters: Letter_Result[] }>;
  KnowledgeArticle_Phonecalls: WebExpand<KnowledgeArticle_Expand, PhoneCall_Select, PhoneCall_Filter, { KnowledgeArticle_Phonecalls: PhoneCall_Result[] }>;
  KnowledgeArticle_RecurringAppointmentMasters: WebExpand<KnowledgeArticle_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { KnowledgeArticle_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  KnowledgeArticle_ServiceAppointments: WebExpand<KnowledgeArticle_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { KnowledgeArticle_ServiceAppointments: ServiceAppointment_Result[] }>;
  KnowledgeArticle_SocialActivities: WebExpand<KnowledgeArticle_Expand, SocialActivity_Select, SocialActivity_Filter, { KnowledgeArticle_SocialActivities: SocialActivity_Result[] }>;
  KnowledgeArticle_SyncErrors: WebExpand<KnowledgeArticle_Expand, SyncError_Select, SyncError_Filter, { KnowledgeArticle_SyncErrors: SyncError_Result[] }>;
  KnowledgeArticle_Tasks: WebExpand<KnowledgeArticle_Expand, Task_Select, Task_Filter, { KnowledgeArticle_Tasks: Task_Result[] }>;
  ParentArticleContentId: WebExpand<KnowledgeArticle_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { ParentArticleContentId: KnowledgeArticle_Result }>;
  PreviousArticleContentId: WebExpand<KnowledgeArticle_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { PreviousArticleContentId: KnowledgeArticle_Result }>;
  RootArticleId: WebExpand<KnowledgeArticle_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { RootArticleId: KnowledgeArticle_Result }>;
  createdby: WebExpand<KnowledgeArticle_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<KnowledgeArticle_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  incident_knowledgearticles: WebExpand<KnowledgeArticle_Expand, KnowledgeArticleIncident_Select, KnowledgeArticleIncident_Filter, { incident_knowledgearticles: KnowledgeArticleIncident_Result[] }>;
  knowledgearticle_Annotations: WebExpand<KnowledgeArticle_Expand, Annotation_Select, Annotation_Filter, { knowledgearticle_Annotations: Annotation_Result[] }>;
  knowledgearticle_AsyncOperations: WebExpand<KnowledgeArticle_Expand, AsyncOperation_Select, AsyncOperation_Filter, { knowledgearticle_AsyncOperations: AsyncOperation_Result[] }>;
  knowledgearticle_BulkDeleteFailures: WebExpand<KnowledgeArticle_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { knowledgearticle_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  knowledgearticle_BulkOperations: WebExpand<KnowledgeArticle_Expand, BulkOperation_Select, BulkOperation_Filter, { knowledgearticle_BulkOperations: BulkOperation_Result[] }>;
  knowledgearticle_CampaignResponses: WebExpand<KnowledgeArticle_Expand, CampaignResponse_Select, CampaignResponse_Filter, { knowledgearticle_CampaignResponses: CampaignResponse_Result[] }>;
  knowledgearticle_DuplicateBaseRecord: WebExpand<KnowledgeArticle_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { knowledgearticle_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  knowledgearticle_DuplicateMatchingRecord: WebExpand<KnowledgeArticle_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { knowledgearticle_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  knowledgearticle_IncidentResolutions: WebExpand<KnowledgeArticle_Expand, IncidentResolution_Select, IncidentResolution_Filter, { knowledgearticle_IncidentResolutions: IncidentResolution_Result[] }>;
  knowledgearticle_OpportunityCloses: WebExpand<KnowledgeArticle_Expand, OpportunityClose_Select, OpportunityClose_Filter, { knowledgearticle_OpportunityCloses: OpportunityClose_Result[] }>;
  knowledgearticle_OrderCloses: WebExpand<KnowledgeArticle_Expand, OrderClose_Select, OrderClose_Filter, { knowledgearticle_OrderCloses: OrderClose_Result[] }>;
  knowledgearticle_PostFollows: WebExpand<KnowledgeArticle_Expand, PostFollow_Select, PostFollow_Filter, { knowledgearticle_PostFollows: PostFollow_Result[] }>;
  knowledgearticle_PostRegardings: WebExpand<KnowledgeArticle_Expand, PostRegarding_Select, PostRegarding_Filter, { knowledgearticle_PostRegardings: PostRegarding_Result[] }>;
  knowledgearticle_PostRoles: WebExpand<KnowledgeArticle_Expand, PostRole_Select, PostRole_Filter, { knowledgearticle_PostRoles: PostRole_Result[] }>;
  knowledgearticle_Posts: WebExpand<KnowledgeArticle_Expand, Post_Select, Post_Filter, { knowledgearticle_Posts: Post_Result[] }>;
  knowledgearticle_PrincipalObjectAttributeAccess: WebExpand<KnowledgeArticle_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { knowledgearticle_PrincipalObjectAttributeAccess: PrincipalObjectAttributeAccess_Result[] }>;
  knowledgearticle_ProcessSession: WebExpand<KnowledgeArticle_Expand, ProcessSession_Select, ProcessSession_Filter, { knowledgearticle_ProcessSession: ProcessSession_Result[] }>;
  knowledgearticle_QueueItems: WebExpand<KnowledgeArticle_Expand, QueueItem_Select, QueueItem_Filter, { knowledgearticle_QueueItems: QueueItem_Result[] }>;
  knowledgearticle_QuoteCloses: WebExpand<KnowledgeArticle_Expand, QuoteClose_Select, QuoteClose_Filter, { knowledgearticle_QuoteCloses: QuoteClose_Result[] }>;
  knowledgearticle_SharePointDocumentLocations: WebExpand<KnowledgeArticle_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { knowledgearticle_SharePointDocumentLocations: SharePointDocumentLocation_Result[] }>;
  knowledgearticle_SharePointDocuments: WebExpand<KnowledgeArticle_Expand, SharePointDocument_Select, SharePointDocument_Filter, { knowledgearticle_SharePointDocuments: SharePointDocument_Result[] }>;
  knowledgearticle_Teams: WebExpand<KnowledgeArticle_Expand, Team_Select, Team_Filter, { knowledgearticle_Teams: Team_Result[] }>;
  knowledgearticle_UserEntityInstanceDatas: WebExpand<KnowledgeArticle_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { knowledgearticle_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  knowledgearticle_activity_parties: WebExpand<KnowledgeArticle_Expand, ActivityParty_Select, ActivityParty_Filter, { knowledgearticle_activity_parties: ActivityParty_Result[] }>;
  knowledgearticle_category: WebExpand<KnowledgeArticle_Expand, Category_Select, Category_Filter, { knowledgearticle_category: Category_Result[] }>;
  knowledgearticle_connections1: WebExpand<KnowledgeArticle_Expand, Connection_Select, Connection_Filter, { knowledgearticle_connections1: Connection_Result[] }>;
  knowledgearticle_connections2: WebExpand<KnowledgeArticle_Expand, Connection_Select, Connection_Filter, { knowledgearticle_connections2: Connection_Result[] }>;
  knowledgearticle_documentindex: WebExpand<KnowledgeArticle_Expand, DocumentIndex_Select, DocumentIndex_Filter, { knowledgearticle_documentindex: DocumentIndex_Result[] }>;
  knowledgearticle_expiredprocess: WebExpand<KnowledgeArticle_Expand, ExpiredProcess_Select, ExpiredProcess_Filter, { knowledgearticle_expiredprocess: ExpiredProcess_Result[] }>;
  knowledgearticle_msdyn_approvals: WebExpand<KnowledgeArticle_Expand, msdyn_approval_Select, msdyn_approval_Filter, { knowledgearticle_msdyn_approvals: msdyn_approval_Result[] }>;
  knowledgearticle_msdyn_bookingalerts: WebExpand<KnowledgeArticle_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { knowledgearticle_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  knowledgearticle_msdyn_ocliveworkitems: WebExpand<KnowledgeArticle_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { knowledgearticle_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  knowledgearticle_msdyn_ocoutboundmessages: WebExpand<KnowledgeArticle_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { knowledgearticle_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  knowledgearticle_msdyn_ocsessions: WebExpand<KnowledgeArticle_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { knowledgearticle_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  knowledgearticle_msfp_alerts: WebExpand<KnowledgeArticle_Expand, msfp_alert_Select, msfp_alert_Filter, { knowledgearticle_msfp_alerts: msfp_alert_Result[] }>;
  knowledgearticle_msfp_surveyinvites: WebExpand<KnowledgeArticle_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { knowledgearticle_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  knowledgearticle_msfp_surveyresponses: WebExpand<KnowledgeArticle_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { knowledgearticle_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  knowledgearticle_newprocess: WebExpand<KnowledgeArticle_Expand, NewProcess_Select, NewProcess_Filter, { knowledgearticle_newprocess: NewProcess_Result[] }>;
  knowledgearticle_parentarticle_contentid: WebExpand<KnowledgeArticle_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { knowledgearticle_parentarticle_contentid: KnowledgeArticle_Result[] }>;
  knowledgearticle_previousarticle_contentid: WebExpand<KnowledgeArticle_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { knowledgearticle_previousarticle_contentid: KnowledgeArticle_Result[] }>;
  knowledgearticle_rootarticle_id: WebExpand<KnowledgeArticle_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { knowledgearticle_rootarticle_id: KnowledgeArticle_Result[] }>;
  knowledgearticle_translationprocess: WebExpand<KnowledgeArticle_Expand, TranslationProcess_Select, TranslationProcess_Filter, { knowledgearticle_translationprocess: TranslationProcess_Result[] }>;
  knowledgearticle_views: WebExpand<KnowledgeArticle_Expand, KnowledgeArticleViews_Select, KnowledgeArticleViews_Filter, { knowledgearticle_views: KnowledgeArticleViews_Result[] }>;
  languagelocaleid: WebExpand<KnowledgeArticle_Expand, LanguageLocale_Select, LanguageLocale_Filter, { languagelocaleid: LanguageLocale_Result }>;
  modifiedby: WebExpand<KnowledgeArticle_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<KnowledgeArticle_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_knowledgearticle_feedback_context: WebExpand<KnowledgeArticle_Expand, Feedback_Select, Feedback_Filter, { msdyn_knowledgearticle_feedback_context: Feedback_Result[] }>;
  msdyn_knowledgearticle_msdyn_kbenrichment_kbid: WebExpand<KnowledgeArticle_Expand, msdyn_kbenrichment_Select, msdyn_kbenrichment_Filter, { msdyn_knowledgearticle_msdyn_kbenrichment_kbid: msdyn_kbenrichment_Result[] }>;
  msdyn_knowledgearticle_msdyn_knowledgearticlesuggestion_suggestedentity: WebExpand<KnowledgeArticle_Expand, msdyn_knowledgearticlesuggestion_Select, msdyn_knowledgearticlesuggestion_Filter, { msdyn_knowledgearticle_msdyn_knowledgearticlesuggestion_suggestedentity: msdyn_knowledgearticlesuggestion_Result[] }>;
  msdyn_knowledgearticle_msdyn_suggestioninteraction_msdyn_suggestedentity: WebExpand<KnowledgeArticle_Expand, msdyn_suggestioninteraction_Select, msdyn_suggestioninteraction_Filter, { msdyn_knowledgearticle_msdyn_suggestioninteraction_msdyn_suggestedentity: msdyn_suggestioninteraction_Result[] }>;
  msdyn_knowledgearticleimage_parentknowledgearticleid: WebExpand<KnowledgeArticle_Expand, msdyn_knowledgearticleimage_Select, msdyn_knowledgearticleimage_Filter, { msdyn_knowledgearticleimage_parentknowledgearticleid: msdyn_knowledgearticleimage_Result[] }>;
  msdyn_msdyn_kbattachment_knowledgearticle: WebExpand<KnowledgeArticle_Expand, msdyn_kbattachment_Select, msdyn_kbattachment_Filter, { msdyn_msdyn_kbattachment_knowledgearticle: msdyn_kbattachment_Result[] }>;
  navigationPropertyNameNotDefined: WebExpand<KnowledgeArticle_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { navigationPropertyNameNotDefined: msdyn_customerasset_Result[] }>;
  navigationPropertyNameNotDefined1: WebExpand<KnowledgeArticle_Expand, Product_Select, Product_Filter, { navigationPropertyNameNotDefined: Product_Result[] }>;
  navigationPropertyNameNotDefined2: WebExpand<KnowledgeArticle_Expand, msdyn_incidenttype_Select, msdyn_incidenttype_Filter, { navigationPropertyNameNotDefined: msdyn_incidenttype_Result[] }>;
  navigationPropertyNameNotDefined3: WebExpand<KnowledgeArticle_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { navigationPropertyNameNotDefined: msdyn_workorder_Result[] }>;
  navigationPropertyNameNotDefined4: WebExpand<KnowledgeArticle_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { navigationPropertyNameNotDefined: msdyn_ocliveworkitem_Result[] }>;
  ownerid: WebExpand<KnowledgeArticle_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<KnowledgeArticle_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<KnowledgeArticle_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<KnowledgeArticle_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  primaryauthorid: WebExpand<KnowledgeArticle_Expand, SystemUser_Select, SystemUser_Filter, { primaryauthorid: SystemUser_Result }>;
  stageid_processstage: WebExpand<KnowledgeArticle_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  subjectid: WebExpand<KnowledgeArticle_Expand, Subject_Select, Subject_Filter, { subjectid: Subject_Result }>;
  transactioncurrencyid: WebExpand<KnowledgeArticle_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface KnowledgeArticle_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  expirationdate_formatted?: string;
  expiredreviewoptions_formatted?: string;
  knowledgearticleviews_date_formatted?: string;
  languagelocaleid_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  parentarticlecontentid_formatted?: string;
  previousarticlecontentid_formatted?: string;
  primaryauthorid_formatted?: string;
  publishon_formatted?: string;
  rating_date_formatted?: string;
  review_formatted?: string;
  rootarticleid_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  subjectid_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface KnowledgeArticle_Result extends KnowledgeArticle_Base, KnowledgeArticle_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  languagelocaleid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  parentarticlecontentid_guid: string | null;
  previousarticlecontentid_guid: string | null;
  primaryauthorid_guid: string | null;
  rootarticleid_guid: string | null;
  subjectid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface KnowledgeArticle_RelatedOne {
  ParentArticleContentId: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  PreviousArticleContentId: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  RootArticleId: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  languagelocaleid: WebMappingRetrieve<LanguageLocale_Select,LanguageLocale_Expand,LanguageLocale_Filter,LanguageLocale_Fixed,LanguageLocale_Result,LanguageLocale_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  primaryauthorid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  subjectid: WebMappingRetrieve<Subject_Select,Subject_Expand,Subject_Filter,Subject_Fixed,Subject_Result,Subject_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface KnowledgeArticle_RelatedMany {
  KnowledgeArticle_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  KnowledgeArticle_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  KnowledgeArticle_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  KnowledgeArticle_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  KnowledgeArticle_Feedback: WebMappingRetrieve<Feedback_Select,Feedback_Expand,Feedback_Filter,Feedback_Fixed,Feedback_Result,Feedback_FormattedResult>;
  KnowledgeArticle_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  KnowledgeArticle_Phonecalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  KnowledgeArticle_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  KnowledgeArticle_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  KnowledgeArticle_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  KnowledgeArticle_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  KnowledgeArticle_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  incident_knowledgearticles: WebMappingRetrieve<KnowledgeArticleIncident_Select,KnowledgeArticleIncident_Expand,KnowledgeArticleIncident_Filter,KnowledgeArticleIncident_Fixed,KnowledgeArticleIncident_Result,KnowledgeArticleIncident_FormattedResult>;
  knowledgearticle_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  knowledgearticle_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  knowledgearticle_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  knowledgearticle_BulkOperations: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  knowledgearticle_CampaignResponses: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  knowledgearticle_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  knowledgearticle_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  knowledgearticle_IncidentResolutions: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  knowledgearticle_OpportunityCloses: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  knowledgearticle_OrderCloses: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  knowledgearticle_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  knowledgearticle_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  knowledgearticle_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  knowledgearticle_Posts: WebMappingRetrieve<Post_Select,Post_Expand,Post_Filter,Post_Fixed,Post_Result,Post_FormattedResult>;
  knowledgearticle_PrincipalObjectAttributeAccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  knowledgearticle_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  knowledgearticle_QueueItems: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  knowledgearticle_QuoteCloses: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  knowledgearticle_SharePointDocumentLocations: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  knowledgearticle_SharePointDocuments: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  knowledgearticle_Teams: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  knowledgearticle_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  knowledgearticle_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  knowledgearticle_category: WebMappingRetrieve<Category_Select,Category_Expand,Category_Filter,Category_Fixed,Category_Result,Category_FormattedResult>;
  knowledgearticle_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  knowledgearticle_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  knowledgearticle_documentindex: WebMappingRetrieve<DocumentIndex_Select,DocumentIndex_Expand,DocumentIndex_Filter,DocumentIndex_Fixed,DocumentIndex_Result,DocumentIndex_FormattedResult>;
  knowledgearticle_expiredprocess: WebMappingRetrieve<ExpiredProcess_Select,ExpiredProcess_Expand,ExpiredProcess_Filter,ExpiredProcess_Fixed,ExpiredProcess_Result,ExpiredProcess_FormattedResult>;
  knowledgearticle_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  knowledgearticle_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  knowledgearticle_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  knowledgearticle_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  knowledgearticle_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  knowledgearticle_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  knowledgearticle_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  knowledgearticle_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  knowledgearticle_newprocess: WebMappingRetrieve<NewProcess_Select,NewProcess_Expand,NewProcess_Filter,NewProcess_Fixed,NewProcess_Result,NewProcess_FormattedResult>;
  knowledgearticle_parentarticle_contentid: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  knowledgearticle_previousarticle_contentid: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  knowledgearticle_rootarticle_id: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  knowledgearticle_translationprocess: WebMappingRetrieve<TranslationProcess_Select,TranslationProcess_Expand,TranslationProcess_Filter,TranslationProcess_Fixed,TranslationProcess_Result,TranslationProcess_FormattedResult>;
  knowledgearticle_views: WebMappingRetrieve<KnowledgeArticleViews_Select,KnowledgeArticleViews_Expand,KnowledgeArticleViews_Filter,KnowledgeArticleViews_Fixed,KnowledgeArticleViews_Result,KnowledgeArticleViews_FormattedResult>;
  msdyn_knowledgearticle_feedback_context: WebMappingRetrieve<Feedback_Select,Feedback_Expand,Feedback_Filter,Feedback_Fixed,Feedback_Result,Feedback_FormattedResult>;
  msdyn_knowledgearticle_msdyn_kbenrichment_kbid: WebMappingRetrieve<msdyn_kbenrichment_Select,msdyn_kbenrichment_Expand,msdyn_kbenrichment_Filter,msdyn_kbenrichment_Fixed,msdyn_kbenrichment_Result,msdyn_kbenrichment_FormattedResult>;
  msdyn_knowledgearticle_msdyn_knowledgearticlesuggestion_suggestedentity: WebMappingRetrieve<msdyn_knowledgearticlesuggestion_Select,msdyn_knowledgearticlesuggestion_Expand,msdyn_knowledgearticlesuggestion_Filter,msdyn_knowledgearticlesuggestion_Fixed,msdyn_knowledgearticlesuggestion_Result,msdyn_knowledgearticlesuggestion_FormattedResult>;
  msdyn_knowledgearticle_msdyn_suggestioninteraction_msdyn_suggestedentity: WebMappingRetrieve<msdyn_suggestioninteraction_Select,msdyn_suggestioninteraction_Expand,msdyn_suggestioninteraction_Filter,msdyn_suggestioninteraction_Fixed,msdyn_suggestioninteraction_Result,msdyn_suggestioninteraction_FormattedResult>;
  msdyn_knowledgearticleimage_parentknowledgearticleid: WebMappingRetrieve<msdyn_knowledgearticleimage_Select,msdyn_knowledgearticleimage_Expand,msdyn_knowledgearticleimage_Filter,msdyn_knowledgearticleimage_Fixed,msdyn_knowledgearticleimage_Result,msdyn_knowledgearticleimage_FormattedResult>;
  msdyn_msdyn_kbattachment_knowledgearticle: WebMappingRetrieve<msdyn_kbattachment_Select,msdyn_kbattachment_Expand,msdyn_kbattachment_Filter,msdyn_kbattachment_Fixed,msdyn_kbattachment_Result,msdyn_kbattachment_FormattedResult>;
  navigationPropertyNameNotDefined: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  navigationPropertyNameNotDefined1: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  navigationPropertyNameNotDefined2: WebMappingRetrieve<msdyn_incidenttype_Select,msdyn_incidenttype_Expand,msdyn_incidenttype_Filter,msdyn_incidenttype_Fixed,msdyn_incidenttype_Result,msdyn_incidenttype_FormattedResult>;
  navigationPropertyNameNotDefined3: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  navigationPropertyNameNotDefined4: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
}
interface WebEntitiesRetrieve {
  knowledgearticles: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
}
interface WebEntitiesRelated {
  knowledgearticles: WebMappingRelated<KnowledgeArticle_RelatedOne,KnowledgeArticle_RelatedMany>;
}
interface WebEntitiesCUDA {
  knowledgearticles: WebMappingCUDA<KnowledgeArticle_Create,KnowledgeArticle_Update,KnowledgeArticle_Select>;
}
