interface Lead_Base extends WebEntity {
  address1_addressid?: string | null;
  address1_addresstypecode?: lead_address1_addresstypecode | null;
  address1_city?: string | null;
  address1_composite?: string | null;
  address1_country?: string | null;
  address1_county?: string | null;
  address1_fax?: string | null;
  address1_latitude?: number | null;
  address1_line1?: string | null;
  address1_line2?: string | null;
  address1_line3?: string | null;
  address1_longitude?: number | null;
  address1_name?: string | null;
  address1_postalcode?: string | null;
  address1_postofficebox?: string | null;
  address1_shippingmethodcode?: lead_address1_shippingmethodcode | null;
  address1_stateorprovince?: string | null;
  address1_telephone1?: string | null;
  address1_telephone2?: string | null;
  address1_telephone3?: string | null;
  address1_upszone?: string | null;
  address1_utcoffset?: number | null;
  address2_addressid?: string | null;
  address2_addresstypecode?: lead_address2_addresstypecode | null;
  address2_city?: string | null;
  address2_composite?: string | null;
  address2_country?: string | null;
  address2_county?: string | null;
  address2_fax?: string | null;
  address2_latitude?: number | null;
  address2_line1?: string | null;
  address2_line2?: string | null;
  address2_line3?: string | null;
  address2_longitude?: number | null;
  address2_name?: string | null;
  address2_postalcode?: string | null;
  address2_postofficebox?: string | null;
  address2_shippingmethodcode?: lead_address2_shippingmethodcode | null;
  address2_stateorprovince?: string | null;
  address2_telephone1?: string | null;
  address2_telephone2?: string | null;
  address2_telephone3?: string | null;
  address2_upszone?: string | null;
  address2_utcoffset?: number | null;
  budgetamount?: number | null;
  budgetamount_base?: number | null;
  budgetstatus?: budgetstatus | null;
  businesscard?: string | null;
  businesscardattributes?: string | null;
  companyname?: string | null;
  confirminterest?: boolean | null;
  createdon?: Date | null;
  decisionmaker?: boolean | null;
  description?: string | null;
  donotbulkemail?: boolean | null;
  donotemail?: boolean | null;
  donotfax?: boolean | null;
  donotphone?: boolean | null;
  donotpostalmail?: boolean | null;
  donotsendmm?: boolean | null;
  emailaddress1?: string | null;
  emailaddress2?: string | null;
  emailaddress3?: string | null;
  entityimageid?: string | null;
  estimatedamount?: number | null;
  estimatedamount_base?: number | null;
  estimatedclosedate?: Date | null;
  estimatedvalue?: number | null;
  evaluatefit?: boolean | null;
  exchangerate?: number | null;
  fax?: string | null;
  firstname?: string | null;
  followemail?: boolean | null;
  fullname?: string | null;
  importsequencenumber?: number | null;
  industrycode?: lead_industrycode | null;
  initialcommunication?: initialcommunication | null;
  isautocreate?: boolean | null;
  isprivate?: boolean | null;
  jobtitle?: string | null;
  lastname?: string | null;
  lastonholdtime?: Date | null;
  lastusedincampaign?: Date | null;
  leadid?: string | null;
  leadqualitycode?: lead_leadqualitycode | null;
  leadsourcecode?: lead_leadsourcecode | null;
  merged?: boolean | null;
  middlename?: string | null;
  mobilephone?: string | null;
  modifiedon?: Date | null;
  msdyn_gdproptout?: boolean | null;
  msdyn_ordertype?: msdyn_lead_msdyn_ordertype | null;
  msdyn_salesassignmentresult?: msdyn_lead_msdyn_salesassignmentresult | null;
  need?: need | null;
  numberofemployees?: number | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  pager?: string | null;
  participatesinworkflow?: boolean | null;
  preferredcontactmethodcode?: lead_preferredcontactmethodcode | null;
  prioritycode?: lead_prioritycode | null;
  processid?: string | null;
  purchaseprocess?: purchaseprocess | null;
  purchasetimeframe?: purchasetimeframe | null;
  qualificationcomments?: string | null;
  revenue?: number | null;
  revenue_base?: number | null;
  salesstage?: lead_salesstage | null;
  salesstagecode?: lead_salesstagecode | null;
  salutation?: string | null;
  schedulefollowup_prospect?: Date | null;
  schedulefollowup_qualify?: Date | null;
  sic?: string | null;
  stageid?: string | null;
  statecode?: lead_statecode | null;
  statuscode?: lead_statuscode | null;
  subject?: string | null;
  teamsfollowed?: number | null;
  telephone1?: string | null;
  telephone2?: string | null;
  telephone3?: string | null;
  timespentbymeonemailandmeetings?: string | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
  websiteurl?: string | null;
}
interface Lead_Relationships {
  BulkOperation_Leads?: BulkOperation_Result[] | null;
  CampaignActivity_Leads?: CampaignActivity_Result[] | null;
  CreatedLead_BulkOperationLogs?: BulkOperationLog_Result[] | null;
  Lead_ActivityPointers?: ActivityPointer_Result[] | null;
  Lead_Annotation?: Annotation_Result[] | null;
  Lead_Appointments?: Appointment_Result[] | null;
  Lead_AsyncOperations?: AsyncOperation_Result[] | null;
  Lead_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Lead_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Lead_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Lead_Email_EmailSender?: Email_Result[] | null;
  Lead_Emails?: Email_Result[] | null;
  Lead_Faxes?: Fax_Result[] | null;
  Lead_Letters?: Letter_Result[] | null;
  Lead_MailboxTrackingFolder?: MailboxTrackingFolder_Result[] | null;
  Lead_Phonecalls?: PhoneCall_Result[] | null;
  Lead_ProcessSessions?: ProcessSession_Result[] | null;
  Lead_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  Lead_ServiceAppointments?: ServiceAppointment_Result[] | null;
  Lead_SharepointDocument?: SharePointDocument_Result[] | null;
  Lead_SharepointDocumentLocation?: SharePointDocumentLocation_Result[] | null;
  Lead_SocialActivities?: SocialActivity_Result[] | null;
  Lead_SyncErrors?: SyncError_Result[] | null;
  Lead_Tasks?: Task_Result[] | null;
  Lead_actioncard?: ActionCard_Result[] | null;
  SourceLead_BulkOperationLogs?: BulkOperationLog_Result[] | null;
  account_originating_lead?: Account_Result[] | null;
  accountleads_association?: Account_Result[] | null;
  contact_originating_lead?: Contact_Result[] | null;
  contactleads_association?: Contact_Result[] | null;
  customerid_account?: Account_Result | null;
  customerid_contact?: Contact_Result | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  lead_BulkOperations?: BulkOperation_Result[] | null;
  lead_CampaignResponses?: CampaignResponse_Result[] | null;
  lead_IncidentResolutions?: IncidentResolution_Result[] | null;
  lead_OpportunityCloses?: OpportunityClose_Result[] | null;
  lead_OrderCloses?: OrderClose_Result[] | null;
  lead_PostFollows?: PostFollow_Result[] | null;
  lead_PostRegardings?: PostRegarding_Result[] | null;
  lead_PostRoles?: PostRole_Result[] | null;
  lead_Posts?: Post_Result[] | null;
  lead_QuoteCloses?: QuoteClose_Result[] | null;
  lead_activity_parties?: ActivityParty_Result[] | null;
  lead_addresses?: LeadAddress_Result[] | null;
  lead_connections1?: Connection_Result[] | null;
  lead_connections2?: Connection_Result[] | null;
  lead_leadtoopportunitysalesprocess?: LeadToOpportunitySalesProcess_Result[] | null;
  lead_master_lead?: Lead_Result[] | null;
  lead_msdyn_approvals?: msdyn_approval_Result[] | null;
  lead_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  lead_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  lead_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  lead_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  lead_msfp_alerts?: msfp_alert_Result[] | null;
  lead_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  lead_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  lead_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  leadcompetitors_association?: Competitor_Result[] | null;
  leadproduct_association?: Product_Result[] | null;
  listlead_association?: List_Result[] | null;
  msdyn_lead_msdyn_salesroutingrun_targetobject?: msdyn_salesroutingrun_Result[] | null;
  msdyn_playbookinstance_lead?: msdyn_playbookinstance_Result[] | null;
  msdyn_sequencetarget_lead_msdyn_target?: msdyn_sequencetarget_Result[] | null;
  opportunity_originating_lead?: Opportunity_Result[] | null;
  sla_lead_sla?: SLA_Result | null;
  slainvokedid_lead_sla?: SLA_Result | null;
  slakpiinstance_lead?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  userentityinstancedata_lead?: UserEntityInstanceData_Result[] | null;
}
interface Lead extends Lead_Base, Lead_Relationships {
  campaignid_bind$campaigns?: string | null;
  customerid_account_bind$accounts?: string | null;
  customerid_contact_bind$contacts?: string | null;
  msdyn_segmentid_bind$msdyn_segments?: string | null;
  originatingcaseid_bind$incidents?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  parentaccountid_bind$accounts?: string | null;
  parentcontactid_bind$contacts?: string | null;
  qualifyingopportunityid_bind$opportunities?: string | null;
  sla_lead_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface Lead_Create extends Lead {
  relatedobjectid_bind$campaignresponses?: string | null;
}
interface Lead_Update extends Lead {
}
interface Lead_Select {
  accountid_guid: WebAttribute<Lead_Select, { accountid_guid: string | null }, { accountid_formatted?: string }>;
  address1_addressid: WebAttribute<Lead_Select, { address1_addressid: string | null }, {  }>;
  address1_addresstypecode: WebAttribute<Lead_Select, { address1_addresstypecode: lead_address1_addresstypecode | null }, { address1_addresstypecode_formatted?: string }>;
  address1_city: WebAttribute<Lead_Select, { address1_city: string | null }, {  }>;
  address1_composite: WebAttribute<Lead_Select, { address1_composite: string | null }, {  }>;
  address1_country: WebAttribute<Lead_Select, { address1_country: string | null }, {  }>;
  address1_county: WebAttribute<Lead_Select, { address1_county: string | null }, {  }>;
  address1_fax: WebAttribute<Lead_Select, { address1_fax: string | null }, {  }>;
  address1_latitude: WebAttribute<Lead_Select, { address1_latitude: number | null }, {  }>;
  address1_line1: WebAttribute<Lead_Select, { address1_line1: string | null }, {  }>;
  address1_line2: WebAttribute<Lead_Select, { address1_line2: string | null }, {  }>;
  address1_line3: WebAttribute<Lead_Select, { address1_line3: string | null }, {  }>;
  address1_longitude: WebAttribute<Lead_Select, { address1_longitude: number | null }, {  }>;
  address1_name: WebAttribute<Lead_Select, { address1_name: string | null }, {  }>;
  address1_postalcode: WebAttribute<Lead_Select, { address1_postalcode: string | null }, {  }>;
  address1_postofficebox: WebAttribute<Lead_Select, { address1_postofficebox: string | null }, {  }>;
  address1_shippingmethodcode: WebAttribute<Lead_Select, { address1_shippingmethodcode: lead_address1_shippingmethodcode | null }, { address1_shippingmethodcode_formatted?: string }>;
  address1_stateorprovince: WebAttribute<Lead_Select, { address1_stateorprovince: string | null }, {  }>;
  address1_telephone1: WebAttribute<Lead_Select, { address1_telephone1: string | null }, {  }>;
  address1_telephone2: WebAttribute<Lead_Select, { address1_telephone2: string | null }, {  }>;
  address1_telephone3: WebAttribute<Lead_Select, { address1_telephone3: string | null }, {  }>;
  address1_upszone: WebAttribute<Lead_Select, { address1_upszone: string | null }, {  }>;
  address1_utcoffset: WebAttribute<Lead_Select, { address1_utcoffset: number | null }, {  }>;
  address2_addressid: WebAttribute<Lead_Select, { address2_addressid: string | null }, {  }>;
  address2_addresstypecode: WebAttribute<Lead_Select, { address2_addresstypecode: lead_address2_addresstypecode | null }, { address2_addresstypecode_formatted?: string }>;
  address2_city: WebAttribute<Lead_Select, { address2_city: string | null }, {  }>;
  address2_composite: WebAttribute<Lead_Select, { address2_composite: string | null }, {  }>;
  address2_country: WebAttribute<Lead_Select, { address2_country: string | null }, {  }>;
  address2_county: WebAttribute<Lead_Select, { address2_county: string | null }, {  }>;
  address2_fax: WebAttribute<Lead_Select, { address2_fax: string | null }, {  }>;
  address2_latitude: WebAttribute<Lead_Select, { address2_latitude: number | null }, {  }>;
  address2_line1: WebAttribute<Lead_Select, { address2_line1: string | null }, {  }>;
  address2_line2: WebAttribute<Lead_Select, { address2_line2: string | null }, {  }>;
  address2_line3: WebAttribute<Lead_Select, { address2_line3: string | null }, {  }>;
  address2_longitude: WebAttribute<Lead_Select, { address2_longitude: number | null }, {  }>;
  address2_name: WebAttribute<Lead_Select, { address2_name: string | null }, {  }>;
  address2_postalcode: WebAttribute<Lead_Select, { address2_postalcode: string | null }, {  }>;
  address2_postofficebox: WebAttribute<Lead_Select, { address2_postofficebox: string | null }, {  }>;
  address2_shippingmethodcode: WebAttribute<Lead_Select, { address2_shippingmethodcode: lead_address2_shippingmethodcode | null }, { address2_shippingmethodcode_formatted?: string }>;
  address2_stateorprovince: WebAttribute<Lead_Select, { address2_stateorprovince: string | null }, {  }>;
  address2_telephone1: WebAttribute<Lead_Select, { address2_telephone1: string | null }, {  }>;
  address2_telephone2: WebAttribute<Lead_Select, { address2_telephone2: string | null }, {  }>;
  address2_telephone3: WebAttribute<Lead_Select, { address2_telephone3: string | null }, {  }>;
  address2_upszone: WebAttribute<Lead_Select, { address2_upszone: string | null }, {  }>;
  address2_utcoffset: WebAttribute<Lead_Select, { address2_utcoffset: number | null }, {  }>;
  budgetamount: WebAttribute<Lead_Select, { budgetamount: number | null; transactioncurrencyid_guid: string | null }, { budgetamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  budgetamount_base: WebAttribute<Lead_Select, { budgetamount_base: number | null; transactioncurrencyid_guid: string | null }, { budgetamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  budgetstatus: WebAttribute<Lead_Select, { budgetstatus: budgetstatus | null }, { budgetstatus_formatted?: string }>;
  businesscard: WebAttribute<Lead_Select, { businesscard: string | null }, {  }>;
  businesscardattributes: WebAttribute<Lead_Select, { businesscardattributes: string | null }, {  }>;
  campaignid_guid: WebAttribute<Lead_Select, { campaignid_guid: string | null }, { campaignid_formatted?: string }>;
  companyname: WebAttribute<Lead_Select, { companyname: string | null }, {  }>;
  confirminterest: WebAttribute<Lead_Select, { confirminterest: boolean | null }, {  }>;
  contactid_guid: WebAttribute<Lead_Select, { contactid_guid: string | null }, { contactid_formatted?: string }>;
  createdby_guid: WebAttribute<Lead_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Lead_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Lead_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  customerid_guid: WebAttribute<Lead_Select, { customerid_guid: string | null }, { customerid_formatted?: string }>;
  decisionmaker: WebAttribute<Lead_Select, { decisionmaker: boolean | null }, {  }>;
  description: WebAttribute<Lead_Select, { description: string | null }, {  }>;
  donotbulkemail: WebAttribute<Lead_Select, { donotbulkemail: boolean | null }, {  }>;
  donotemail: WebAttribute<Lead_Select, { donotemail: boolean | null }, {  }>;
  donotfax: WebAttribute<Lead_Select, { donotfax: boolean | null }, {  }>;
  donotphone: WebAttribute<Lead_Select, { donotphone: boolean | null }, {  }>;
  donotpostalmail: WebAttribute<Lead_Select, { donotpostalmail: boolean | null }, {  }>;
  donotsendmm: WebAttribute<Lead_Select, { donotsendmm: boolean | null }, {  }>;
  emailaddress1: WebAttribute<Lead_Select, { emailaddress1: string | null }, {  }>;
  emailaddress2: WebAttribute<Lead_Select, { emailaddress2: string | null }, {  }>;
  emailaddress3: WebAttribute<Lead_Select, { emailaddress3: string | null }, {  }>;
  entityimageid: WebAttribute<Lead_Select, { entityimageid: string | null }, {  }>;
  estimatedamount: WebAttribute<Lead_Select, { estimatedamount: number | null; transactioncurrencyid_guid: string | null }, { estimatedamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  estimatedamount_base: WebAttribute<Lead_Select, { estimatedamount_base: number | null; transactioncurrencyid_guid: string | null }, { estimatedamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  estimatedclosedate: WebAttribute<Lead_Select, { estimatedclosedate: Date | null }, { estimatedclosedate_formatted?: string }>;
  estimatedvalue: WebAttribute<Lead_Select, { estimatedvalue: number | null }, {  }>;
  evaluatefit: WebAttribute<Lead_Select, { evaluatefit: boolean | null }, {  }>;
  exchangerate: WebAttribute<Lead_Select, { exchangerate: number | null }, {  }>;
  fax: WebAttribute<Lead_Select, { fax: string | null }, {  }>;
  firstname: WebAttribute<Lead_Select, { firstname: string | null }, {  }>;
  followemail: WebAttribute<Lead_Select, { followemail: boolean | null }, {  }>;
  fullname: WebAttribute<Lead_Select, { fullname: string | null }, {  }>;
  importsequencenumber: WebAttribute<Lead_Select, { importsequencenumber: number | null }, {  }>;
  industrycode: WebAttribute<Lead_Select, { industrycode: lead_industrycode | null }, { industrycode_formatted?: string }>;
  initialcommunication: WebAttribute<Lead_Select, { initialcommunication: initialcommunication | null }, { initialcommunication_formatted?: string }>;
  isautocreate: WebAttribute<Lead_Select, { isautocreate: boolean | null }, {  }>;
  isprivate: WebAttribute<Lead_Select, { isprivate: boolean | null }, {  }>;
  jobtitle: WebAttribute<Lead_Select, { jobtitle: string | null }, {  }>;
  lastname: WebAttribute<Lead_Select, { lastname: string | null }, {  }>;
  lastonholdtime: WebAttribute<Lead_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  lastusedincampaign: WebAttribute<Lead_Select, { lastusedincampaign: Date | null }, { lastusedincampaign_formatted?: string }>;
  leadid: WebAttribute<Lead_Select, { leadid: string | null }, {  }>;
  leadqualitycode: WebAttribute<Lead_Select, { leadqualitycode: lead_leadqualitycode | null }, { leadqualitycode_formatted?: string }>;
  leadsourcecode: WebAttribute<Lead_Select, { leadsourcecode: lead_leadsourcecode | null }, { leadsourcecode_formatted?: string }>;
  masterid_guid: WebAttribute<Lead_Select, { masterid_guid: string | null }, { masterid_formatted?: string }>;
  merged: WebAttribute<Lead_Select, { merged: boolean | null }, {  }>;
  middlename: WebAttribute<Lead_Select, { middlename: string | null }, {  }>;
  mobilephone: WebAttribute<Lead_Select, { mobilephone: string | null }, {  }>;
  modifiedby_guid: WebAttribute<Lead_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Lead_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Lead_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_gdproptout: WebAttribute<Lead_Select, { msdyn_gdproptout: boolean | null }, {  }>;
  msdyn_ordertype: WebAttribute<Lead_Select, { msdyn_ordertype: msdyn_lead_msdyn_ordertype | null }, { msdyn_ordertype_formatted?: string }>;
  msdyn_salesassignmentresult: WebAttribute<Lead_Select, { msdyn_salesassignmentresult: msdyn_lead_msdyn_salesassignmentresult | null }, { msdyn_salesassignmentresult_formatted?: string }>;
  msdyn_segmentid_guid: WebAttribute<Lead_Select, { msdyn_segmentid_guid: string | null }, { msdyn_segmentid_formatted?: string }>;
  need: WebAttribute<Lead_Select, { need: need | null }, { need_formatted?: string }>;
  numberofemployees: WebAttribute<Lead_Select, { numberofemployees: number | null }, {  }>;
  onholdtime: WebAttribute<Lead_Select, { onholdtime: number | null }, {  }>;
  originatingcaseid_guid: WebAttribute<Lead_Select, { originatingcaseid_guid: string | null }, { originatingcaseid_formatted?: string }>;
  overriddencreatedon: WebAttribute<Lead_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Lead_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Lead_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Lead_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Lead_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  pager: WebAttribute<Lead_Select, { pager: string | null }, {  }>;
  parentaccountid_guid: WebAttribute<Lead_Select, { parentaccountid_guid: string | null }, { parentaccountid_formatted?: string }>;
  parentcontactid_guid: WebAttribute<Lead_Select, { parentcontactid_guid: string | null }, { parentcontactid_formatted?: string }>;
  participatesinworkflow: WebAttribute<Lead_Select, { participatesinworkflow: boolean | null }, {  }>;
  preferredcontactmethodcode: WebAttribute<Lead_Select, { preferredcontactmethodcode: lead_preferredcontactmethodcode | null }, { preferredcontactmethodcode_formatted?: string }>;
  prioritycode: WebAttribute<Lead_Select, { prioritycode: lead_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<Lead_Select, { processid: string | null }, {  }>;
  purchaseprocess: WebAttribute<Lead_Select, { purchaseprocess: purchaseprocess | null }, { purchaseprocess_formatted?: string }>;
  purchasetimeframe: WebAttribute<Lead_Select, { purchasetimeframe: purchasetimeframe | null }, { purchasetimeframe_formatted?: string }>;
  qualificationcomments: WebAttribute<Lead_Select, { qualificationcomments: string | null }, {  }>;
  qualifyingopportunityid_guid: WebAttribute<Lead_Select, { qualifyingopportunityid_guid: string | null }, { qualifyingopportunityid_formatted?: string }>;
  relatedobjectid_guid: WebAttribute<Lead_Select, { relatedobjectid_guid: string | null }, { relatedobjectid_formatted?: string }>;
  revenue: WebAttribute<Lead_Select, { revenue: number | null; transactioncurrencyid_guid: string | null }, { revenue_formatted?: string; transactioncurrencyid_formatted?: string }>;
  revenue_base: WebAttribute<Lead_Select, { revenue_base: number | null; transactioncurrencyid_guid: string | null }, { revenue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  salesstage: WebAttribute<Lead_Select, { salesstage: lead_salesstage | null }, { salesstage_formatted?: string }>;
  salesstagecode: WebAttribute<Lead_Select, { salesstagecode: lead_salesstagecode | null }, { salesstagecode_formatted?: string }>;
  salutation: WebAttribute<Lead_Select, { salutation: string | null }, {  }>;
  schedulefollowup_prospect: WebAttribute<Lead_Select, { schedulefollowup_prospect: Date | null }, { schedulefollowup_prospect_formatted?: string }>;
  schedulefollowup_qualify: WebAttribute<Lead_Select, { schedulefollowup_qualify: Date | null }, { schedulefollowup_qualify_formatted?: string }>;
  sic: WebAttribute<Lead_Select, { sic: string | null }, {  }>;
  slaid_guid: WebAttribute<Lead_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<Lead_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  stageid: WebAttribute<Lead_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Lead_Select, { statecode: lead_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Lead_Select, { statuscode: lead_statuscode | null }, { statuscode_formatted?: string }>;
  subject: WebAttribute<Lead_Select, { subject: string | null }, {  }>;
  teamsfollowed: WebAttribute<Lead_Select, { teamsfollowed: number | null }, {  }>;
  telephone1: WebAttribute<Lead_Select, { telephone1: string | null }, {  }>;
  telephone2: WebAttribute<Lead_Select, { telephone2: string | null }, {  }>;
  telephone3: WebAttribute<Lead_Select, { telephone3: string | null }, {  }>;
  timespentbymeonemailandmeetings: WebAttribute<Lead_Select, { timespentbymeonemailandmeetings: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<Lead_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<Lead_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Lead_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Lead_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Lead_Select, { versionnumber: number | null }, {  }>;
  websiteurl: WebAttribute<Lead_Select, { websiteurl: string | null }, {  }>;
}
interface Lead_Filter {
  accountid_guid: XQW.Guid;
  address1_addressid: XQW.Guid;
  address1_addresstypecode: lead_address1_addresstypecode;
  address1_city: string;
  address1_composite: string;
  address1_country: string;
  address1_county: string;
  address1_fax: string;
  address1_latitude: number;
  address1_line1: string;
  address1_line2: string;
  address1_line3: string;
  address1_longitude: number;
  address1_name: string;
  address1_postalcode: string;
  address1_postofficebox: string;
  address1_shippingmethodcode: lead_address1_shippingmethodcode;
  address1_stateorprovince: string;
  address1_telephone1: string;
  address1_telephone2: string;
  address1_telephone3: string;
  address1_upszone: string;
  address1_utcoffset: number;
  address2_addressid: XQW.Guid;
  address2_addresstypecode: lead_address2_addresstypecode;
  address2_city: string;
  address2_composite: string;
  address2_country: string;
  address2_county: string;
  address2_fax: string;
  address2_latitude: number;
  address2_line1: string;
  address2_line2: string;
  address2_line3: string;
  address2_longitude: number;
  address2_name: string;
  address2_postalcode: string;
  address2_postofficebox: string;
  address2_shippingmethodcode: lead_address2_shippingmethodcode;
  address2_stateorprovince: string;
  address2_telephone1: string;
  address2_telephone2: string;
  address2_telephone3: string;
  address2_upszone: string;
  address2_utcoffset: number;
  budgetamount: number;
  budgetamount_base: number;
  budgetstatus: budgetstatus;
  businesscard: string;
  businesscardattributes: string;
  campaignid_guid: XQW.Guid;
  companyname: string;
  confirminterest: boolean;
  contactid_guid: XQW.Guid;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  customerid_guid: XQW.Guid;
  decisionmaker: boolean;
  description: string;
  donotbulkemail: boolean;
  donotemail: boolean;
  donotfax: boolean;
  donotphone: boolean;
  donotpostalmail: boolean;
  donotsendmm: boolean;
  emailaddress1: string;
  emailaddress2: string;
  emailaddress3: string;
  entityimageid: XQW.Guid;
  estimatedamount: number;
  estimatedamount_base: number;
  estimatedclosedate: Date;
  estimatedvalue: number;
  evaluatefit: boolean;
  exchangerate: any;
  fax: string;
  firstname: string;
  followemail: boolean;
  fullname: string;
  importsequencenumber: number;
  industrycode: lead_industrycode;
  initialcommunication: initialcommunication;
  isautocreate: boolean;
  isprivate: boolean;
  jobtitle: string;
  lastname: string;
  lastonholdtime: Date;
  lastusedincampaign: Date;
  leadid: XQW.Guid;
  leadqualitycode: lead_leadqualitycode;
  leadsourcecode: lead_leadsourcecode;
  masterid_guid: XQW.Guid;
  merged: boolean;
  middlename: string;
  mobilephone: string;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_gdproptout: boolean;
  msdyn_ordertype: msdyn_lead_msdyn_ordertype;
  msdyn_salesassignmentresult: msdyn_lead_msdyn_salesassignmentresult;
  msdyn_segmentid_guid: XQW.Guid;
  need: need;
  numberofemployees: number;
  onholdtime: number;
  originatingcaseid_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  pager: string;
  parentaccountid_guid: XQW.Guid;
  parentcontactid_guid: XQW.Guid;
  participatesinworkflow: boolean;
  preferredcontactmethodcode: lead_preferredcontactmethodcode;
  prioritycode: lead_prioritycode;
  processid: XQW.Guid;
  purchaseprocess: purchaseprocess;
  purchasetimeframe: purchasetimeframe;
  qualificationcomments: string;
  qualifyingopportunityid_guid: XQW.Guid;
  relatedobjectid_guid: XQW.Guid;
  revenue: number;
  revenue_base: number;
  salesstage: lead_salesstage;
  salesstagecode: lead_salesstagecode;
  salutation: string;
  schedulefollowup_prospect: Date;
  schedulefollowup_qualify: Date;
  sic: string;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: lead_statecode;
  statuscode: lead_statuscode;
  subject: string;
  teamsfollowed: number;
  telephone1: string;
  telephone2: string;
  telephone3: string;
  timespentbymeonemailandmeetings: string;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
  websiteurl: string;
}
interface Lead_Expand {
  BulkOperation_Leads: WebExpand<Lead_Expand, BulkOperation_Select, BulkOperation_Filter, { BulkOperation_Leads: BulkOperation_Result[] }>;
  CampaignActivity_Leads: WebExpand<Lead_Expand, CampaignActivity_Select, CampaignActivity_Filter, { CampaignActivity_Leads: CampaignActivity_Result[] }>;
  CreatedLead_BulkOperationLogs: WebExpand<Lead_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { CreatedLead_BulkOperationLogs: BulkOperationLog_Result[] }>;
  Lead_ActivityPointers: WebExpand<Lead_Expand, ActivityPointer_Select, ActivityPointer_Filter, { Lead_ActivityPointers: ActivityPointer_Result[] }>;
  Lead_Annotation: WebExpand<Lead_Expand, Annotation_Select, Annotation_Filter, { Lead_Annotation: Annotation_Result[] }>;
  Lead_Appointments: WebExpand<Lead_Expand, Appointment_Select, Appointment_Filter, { Lead_Appointments: Appointment_Result[] }>;
  Lead_AsyncOperations: WebExpand<Lead_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Lead_AsyncOperations: AsyncOperation_Result[] }>;
  Lead_BulkDeleteFailures: WebExpand<Lead_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Lead_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Lead_DuplicateBaseRecord: WebExpand<Lead_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Lead_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Lead_DuplicateMatchingRecord: WebExpand<Lead_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Lead_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Lead_Email_EmailSender: WebExpand<Lead_Expand, Email_Select, Email_Filter, { Lead_Email_EmailSender: Email_Result[] }>;
  Lead_Emails: WebExpand<Lead_Expand, Email_Select, Email_Filter, { Lead_Emails: Email_Result[] }>;
  Lead_Faxes: WebExpand<Lead_Expand, Fax_Select, Fax_Filter, { Lead_Faxes: Fax_Result[] }>;
  Lead_Letters: WebExpand<Lead_Expand, Letter_Select, Letter_Filter, { Lead_Letters: Letter_Result[] }>;
  Lead_MailboxTrackingFolder: WebExpand<Lead_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { Lead_MailboxTrackingFolder: MailboxTrackingFolder_Result[] }>;
  Lead_Phonecalls: WebExpand<Lead_Expand, PhoneCall_Select, PhoneCall_Filter, { Lead_Phonecalls: PhoneCall_Result[] }>;
  Lead_ProcessSessions: WebExpand<Lead_Expand, ProcessSession_Select, ProcessSession_Filter, { Lead_ProcessSessions: ProcessSession_Result[] }>;
  Lead_RecurringAppointmentMasters: WebExpand<Lead_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { Lead_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  Lead_ServiceAppointments: WebExpand<Lead_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { Lead_ServiceAppointments: ServiceAppointment_Result[] }>;
  Lead_SharepointDocument: WebExpand<Lead_Expand, SharePointDocument_Select, SharePointDocument_Filter, { Lead_SharepointDocument: SharePointDocument_Result[] }>;
  Lead_SharepointDocumentLocation: WebExpand<Lead_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { Lead_SharepointDocumentLocation: SharePointDocumentLocation_Result[] }>;
  Lead_SocialActivities: WebExpand<Lead_Expand, SocialActivity_Select, SocialActivity_Filter, { Lead_SocialActivities: SocialActivity_Result[] }>;
  Lead_SyncErrors: WebExpand<Lead_Expand, SyncError_Select, SyncError_Filter, { Lead_SyncErrors: SyncError_Result[] }>;
  Lead_Tasks: WebExpand<Lead_Expand, Task_Select, Task_Filter, { Lead_Tasks: Task_Result[] }>;
  Lead_actioncard: WebExpand<Lead_Expand, ActionCard_Select, ActionCard_Filter, { Lead_actioncard: ActionCard_Result[] }>;
  SourceLead_BulkOperationLogs: WebExpand<Lead_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { SourceLead_BulkOperationLogs: BulkOperationLog_Result[] }>;
  account_originating_lead: WebExpand<Lead_Expand, Account_Select, Account_Filter, { account_originating_lead: Account_Result[] }>;
  accountleads_association: WebExpand<Lead_Expand, Account_Select, Account_Filter, { accountleads_association: Account_Result[] }>;
  campaignid: WebExpand<Lead_Expand, Campaign_Select, Campaign_Filter, { campaignid: Campaign_Result }>;
  contact_originating_lead: WebExpand<Lead_Expand, Contact_Select, Contact_Filter, { contact_originating_lead: Contact_Result[] }>;
  contactleads_association: WebExpand<Lead_Expand, Contact_Select, Contact_Filter, { contactleads_association: Contact_Result[] }>;
  createdby: WebExpand<Lead_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Lead_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  customerid_account: WebExpand<Lead_Expand, Account_Select, Account_Filter, { customerid_account: Account_Result }>;
  customerid_contact: WebExpand<Lead_Expand, Contact_Select, Contact_Filter, { customerid_contact: Contact_Result }>;
  entityimageid_imagedescriptor: WebExpand<Lead_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  lead_BulkOperations: WebExpand<Lead_Expand, BulkOperation_Select, BulkOperation_Filter, { lead_BulkOperations: BulkOperation_Result[] }>;
  lead_CampaignResponses: WebExpand<Lead_Expand, CampaignResponse_Select, CampaignResponse_Filter, { lead_CampaignResponses: CampaignResponse_Result[] }>;
  lead_IncidentResolutions: WebExpand<Lead_Expand, IncidentResolution_Select, IncidentResolution_Filter, { lead_IncidentResolutions: IncidentResolution_Result[] }>;
  lead_OpportunityCloses: WebExpand<Lead_Expand, OpportunityClose_Select, OpportunityClose_Filter, { lead_OpportunityCloses: OpportunityClose_Result[] }>;
  lead_OrderCloses: WebExpand<Lead_Expand, OrderClose_Select, OrderClose_Filter, { lead_OrderCloses: OrderClose_Result[] }>;
  lead_PostFollows: WebExpand<Lead_Expand, PostFollow_Select, PostFollow_Filter, { lead_PostFollows: PostFollow_Result[] }>;
  lead_PostRegardings: WebExpand<Lead_Expand, PostRegarding_Select, PostRegarding_Filter, { lead_PostRegardings: PostRegarding_Result[] }>;
  lead_PostRoles: WebExpand<Lead_Expand, PostRole_Select, PostRole_Filter, { lead_PostRoles: PostRole_Result[] }>;
  lead_Posts: WebExpand<Lead_Expand, Post_Select, Post_Filter, { lead_Posts: Post_Result[] }>;
  lead_QuoteCloses: WebExpand<Lead_Expand, QuoteClose_Select, QuoteClose_Filter, { lead_QuoteCloses: QuoteClose_Result[] }>;
  lead_activity_parties: WebExpand<Lead_Expand, ActivityParty_Select, ActivityParty_Filter, { lead_activity_parties: ActivityParty_Result[] }>;
  lead_addresses: WebExpand<Lead_Expand, LeadAddress_Select, LeadAddress_Filter, { lead_addresses: LeadAddress_Result[] }>;
  lead_connections1: WebExpand<Lead_Expand, Connection_Select, Connection_Filter, { lead_connections1: Connection_Result[] }>;
  lead_connections2: WebExpand<Lead_Expand, Connection_Select, Connection_Filter, { lead_connections2: Connection_Result[] }>;
  lead_leadtoopportunitysalesprocess: WebExpand<Lead_Expand, LeadToOpportunitySalesProcess_Select, LeadToOpportunitySalesProcess_Filter, { lead_leadtoopportunitysalesprocess: LeadToOpportunitySalesProcess_Result[] }>;
  lead_master_lead: WebExpand<Lead_Expand, Lead_Select, Lead_Filter, { lead_master_lead: Lead_Result[] }>;
  lead_msdyn_approvals: WebExpand<Lead_Expand, msdyn_approval_Select, msdyn_approval_Filter, { lead_msdyn_approvals: msdyn_approval_Result[] }>;
  lead_msdyn_bookingalerts: WebExpand<Lead_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { lead_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  lead_msdyn_ocliveworkitems: WebExpand<Lead_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { lead_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  lead_msdyn_ocoutboundmessages: WebExpand<Lead_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { lead_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  lead_msdyn_ocsessions: WebExpand<Lead_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { lead_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  lead_msfp_alerts: WebExpand<Lead_Expand, msfp_alert_Select, msfp_alert_Filter, { lead_msfp_alerts: msfp_alert_Result[] }>;
  lead_msfp_surveyinvites: WebExpand<Lead_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { lead_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  lead_msfp_surveyresponses: WebExpand<Lead_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { lead_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  lead_principalobjectattributeaccess: WebExpand<Lead_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { lead_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  leadcompetitors_association: WebExpand<Lead_Expand, Competitor_Select, Competitor_Filter, { leadcompetitors_association: Competitor_Result[] }>;
  leadproduct_association: WebExpand<Lead_Expand, Product_Select, Product_Filter, { leadproduct_association: Product_Result[] }>;
  listlead_association: WebExpand<Lead_Expand, List_Select, List_Filter, { listlead_association: List_Result[] }>;
  masterid: WebExpand<Lead_Expand, Lead_Select, Lead_Filter, { masterid: Lead_Result }>;
  modifiedby: WebExpand<Lead_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Lead_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_lead_msdyn_salesroutingrun_targetobject: WebExpand<Lead_Expand, msdyn_salesroutingrun_Select, msdyn_salesroutingrun_Filter, { msdyn_lead_msdyn_salesroutingrun_targetobject: msdyn_salesroutingrun_Result[] }>;
  msdyn_playbookinstance_lead: WebExpand<Lead_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { msdyn_playbookinstance_lead: msdyn_playbookinstance_Result[] }>;
  msdyn_segmentid: WebExpand<Lead_Expand, msdyn_segment_Select, msdyn_segment_Filter, { msdyn_segmentid: msdyn_segment_Result }>;
  msdyn_sequencetarget_lead_msdyn_target: WebExpand<Lead_Expand, msdyn_sequencetarget_Select, msdyn_sequencetarget_Filter, { msdyn_sequencetarget_lead_msdyn_target: msdyn_sequencetarget_Result[] }>;
  opportunity_originating_lead: WebExpand<Lead_Expand, Opportunity_Select, Opportunity_Filter, { opportunity_originating_lead: Opportunity_Result[] }>;
  originatingcaseid: WebExpand<Lead_Expand, Incident_Select, Incident_Filter, { originatingcaseid: Incident_Result }>;
  ownerid: WebExpand<Lead_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<Lead_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<Lead_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<Lead_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  parentaccountid: WebExpand<Lead_Expand, Account_Select, Account_Filter, { parentaccountid: Account_Result }>;
  parentcontactid: WebExpand<Lead_Expand, Contact_Select, Contact_Filter, { parentcontactid: Contact_Result }>;
  qualifyingopportunityid: WebExpand<Lead_Expand, Opportunity_Select, Opportunity_Filter, { qualifyingopportunityid: Opportunity_Result }>;
  relatedobjectid: WebExpand<Lead_Expand, CampaignResponse_Select, CampaignResponse_Filter, { relatedobjectid: CampaignResponse_Result }>;
  sla_lead_sla: WebExpand<Lead_Expand, SLA_Select, SLA_Filter, { sla_lead_sla: SLA_Result }>;
  slainvokedid_lead_sla: WebExpand<Lead_Expand, SLA_Select, SLA_Filter, { slainvokedid_lead_sla: SLA_Result }>;
  slakpiinstance_lead: WebExpand<Lead_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_lead: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<Lead_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid: WebExpand<Lead_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_lead: WebExpand<Lead_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_lead: UserEntityInstanceData_Result[] }>;
}
interface Lead_FormattedResult {
  accountid_formatted?: string;
  address1_addresstypecode_formatted?: string;
  address1_shippingmethodcode_formatted?: string;
  address2_addresstypecode_formatted?: string;
  address2_shippingmethodcode_formatted?: string;
  budgetamount_base_formatted?: string;
  budgetamount_formatted?: string;
  budgetstatus_formatted?: string;
  campaignid_formatted?: string;
  contactid_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  customerid_formatted?: string;
  estimatedamount_base_formatted?: string;
  estimatedamount_formatted?: string;
  estimatedclosedate_formatted?: string;
  industrycode_formatted?: string;
  initialcommunication_formatted?: string;
  lastonholdtime_formatted?: string;
  lastusedincampaign_formatted?: string;
  leadqualitycode_formatted?: string;
  leadsourcecode_formatted?: string;
  masterid_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_ordertype_formatted?: string;
  msdyn_salesassignmentresult_formatted?: string;
  msdyn_segmentid_formatted?: string;
  need_formatted?: string;
  originatingcaseid_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  parentaccountid_formatted?: string;
  parentcontactid_formatted?: string;
  preferredcontactmethodcode_formatted?: string;
  prioritycode_formatted?: string;
  purchaseprocess_formatted?: string;
  purchasetimeframe_formatted?: string;
  qualifyingopportunityid_formatted?: string;
  relatedobjectid_formatted?: string;
  revenue_base_formatted?: string;
  revenue_formatted?: string;
  salesstage_formatted?: string;
  salesstagecode_formatted?: string;
  schedulefollowup_prospect_formatted?: string;
  schedulefollowup_qualify_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Lead_Result extends Lead_Base, Lead_Relationships {
  "@odata.etag": string;
  accountid_guid: string | null;
  campaignid_guid: string | null;
  contactid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  customerid_guid: string | null;
  masterid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_segmentid_guid: string | null;
  originatingcaseid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  parentaccountid_guid: string | null;
  parentcontactid_guid: string | null;
  qualifyingopportunityid_guid: string | null;
  relatedobjectid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Lead_RelatedOne {
  campaignid: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  customerid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  customerid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  masterid: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_segmentid: WebMappingRetrieve<msdyn_segment_Select,msdyn_segment_Expand,msdyn_segment_Filter,msdyn_segment_Fixed,msdyn_segment_Result,msdyn_segment_FormattedResult>;
  originatingcaseid: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  parentaccountid: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  parentcontactid: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  qualifyingopportunityid: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  relatedobjectid: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  sla_lead_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_lead_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Lead_RelatedMany {
  BulkOperation_Leads: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  CampaignActivity_Leads: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  CreatedLead_BulkOperationLogs: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  Lead_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  Lead_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Lead_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  Lead_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Lead_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Lead_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Lead_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Lead_Email_EmailSender: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  Lead_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  Lead_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  Lead_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  Lead_MailboxTrackingFolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  Lead_Phonecalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  Lead_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Lead_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  Lead_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  Lead_SharepointDocument: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  Lead_SharepointDocumentLocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  Lead_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  Lead_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  Lead_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  Lead_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  SourceLead_BulkOperationLogs: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  account_originating_lead: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  accountleads_association: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  contact_originating_lead: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  contactleads_association: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  lead_BulkOperations: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  lead_CampaignResponses: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  lead_IncidentResolutions: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  lead_OpportunityCloses: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  lead_OrderCloses: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  lead_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  lead_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  lead_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  lead_Posts: WebMappingRetrieve<Post_Select,Post_Expand,Post_Filter,Post_Fixed,Post_Result,Post_FormattedResult>;
  lead_QuoteCloses: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  lead_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  lead_addresses: WebMappingRetrieve<LeadAddress_Select,LeadAddress_Expand,LeadAddress_Filter,LeadAddress_Fixed,LeadAddress_Result,LeadAddress_FormattedResult>;
  lead_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  lead_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  lead_leadtoopportunitysalesprocess: WebMappingRetrieve<LeadToOpportunitySalesProcess_Select,LeadToOpportunitySalesProcess_Expand,LeadToOpportunitySalesProcess_Filter,LeadToOpportunitySalesProcess_Fixed,LeadToOpportunitySalesProcess_Result,LeadToOpportunitySalesProcess_FormattedResult>;
  lead_master_lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  lead_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  lead_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  lead_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  lead_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  lead_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  lead_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  lead_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  lead_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  lead_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  leadcompetitors_association: WebMappingRetrieve<Competitor_Select,Competitor_Expand,Competitor_Filter,Competitor_Fixed,Competitor_Result,Competitor_FormattedResult>;
  leadproduct_association: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  listlead_association: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  msdyn_lead_msdyn_salesroutingrun_targetobject: WebMappingRetrieve<msdyn_salesroutingrun_Select,msdyn_salesroutingrun_Expand,msdyn_salesroutingrun_Filter,msdyn_salesroutingrun_Fixed,msdyn_salesroutingrun_Result,msdyn_salesroutingrun_FormattedResult>;
  msdyn_playbookinstance_lead: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  msdyn_sequencetarget_lead_msdyn_target: WebMappingRetrieve<msdyn_sequencetarget_Select,msdyn_sequencetarget_Expand,msdyn_sequencetarget_Filter,msdyn_sequencetarget_Fixed,msdyn_sequencetarget_Result,msdyn_sequencetarget_FormattedResult>;
  opportunity_originating_lead: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  slakpiinstance_lead: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_lead: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  leads: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
}
interface WebEntitiesRelated {
  leads: WebMappingRelated<Lead_RelatedOne,Lead_RelatedMany>;
}
interface WebEntitiesCUDA {
  leads: WebMappingCUDA<Lead_Create,Lead_Update,Lead_Select>;
}
