interface Mailbox_Base extends WebEntity {
  actdeliverymethod?: mailbox_actdeliverymethod | null;
  actstatus?: mailbox_actstatus | null;
  allowemailconnectortousecredentials?: boolean | null;
  averagetotalduration?: number | null;
  createdon?: Date | null;
  emailaddress?: string | null;
  emailrouteraccessapproval?: mailbox_emailrouteraccessapproval | null;
  enabledforact?: boolean | null;
  enabledforincomingemail?: boolean | null;
  enabledforoutgoingemail?: boolean | null;
  entityimageid?: string | null;
  ewsurl?: string | null;
  exchangecontactsimportcompletedon?: Date | null;
  exchangecontactsimportstatus?: mailbox_exchangecontactsimportstatus | null;
  exchangesyncstatexml?: string | null;
  folderhierarchy?: string | null;
  forcedunlockcount?: number | null;
  hostid?: string | null;
  incomingemaildeliverymethod?: mailbox_incomingemaildeliverymethod | null;
  incomingemailstatus?: mailbox_incomingemailstatus | null;
  isactsyncorgflagset?: boolean | null;
  isemailaddressapprovedbyo365admin?: boolean | null;
  isexchangecontactsimportscheduled?: boolean | null;
  isforwardmailbox?: boolean | null;
  isoauthaccesstokenset?: boolean | null;
  isoauthrefreshtokenset?: boolean | null;
  ispasswordset?: boolean | null;
  isserviceaccount?: boolean | null;
  itemsfailedforlastsync?: number | null;
  itemsprocessedforlastsync?: number | null;
  lastactiveon?: Date | null;
  lastautodiscoveredon?: Date | null;
  lastduration?: number | null;
  lastmailboxforcedunlockoccurredon?: Date | null;
  lastmessageid?: string | null;
  lastsuccessfulsynccompletedon?: Date | null;
  lastsyncerror?: string | null;
  lastsyncerrorcode?: number | null;
  lastsyncerrorcount?: number | null;
  lastsyncerrormachinename?: string | null;
  lastsyncerroroccurredon?: Date | null;
  lastsyncstartedon?: Date | null;
  lasttaggedmessageid?: string | null;
  mailboxid?: string | null;
  mailboxprocessingcontext?: number | null;
  mailboxstatus?: mailbox_status | null;
  modifiedon?: Date | null;
  name?: string | null;
  nextscheduledactsyncinseconds?: number | null;
  noactcount?: number | null;
  noemailcount?: number | null;
  oauthaccesstoken?: string | null;
  oauthrefreshtoken?: string | null;
  oauthtokenexpireson?: Date | null;
  officeappsdeploymentcompleteon?: Date | null;
  officeappsdeploymenterror?: string | null;
  officeappsdeploymentscheduled?: boolean | null;
  officeappsdeploymentstatus?: mailbox_officeappsdeploymentstatus | null;
  orgmarkedasprimaryforexchangesync?: boolean | null;
  outgoingemaildeliverymethod?: mailbox_outgoingemaildeliverymethod | null;
  outgoingemailstatus?: mailbox_outgoingemailstatus | null;
  password?: string | null;
  postponemailboxprocessinguntil?: Date | null;
  postponeofficeappsdeploymentuntil?: Date | null;
  postponesendinguntil?: Date | null;
  postponetestemailconfigurationuntil?: Date | null;
  processanddeleteemails?: boolean | null;
  processedtimes?: number | null;
  processemailreceivedafter?: Date | null;
  processinglastattemptedon?: Date | null;
  processingstatecode?: number | null;
  receivingpostponeduntil?: Date | null;
  receivingpostponeduntilforact?: Date | null;
  statecode?: mailbox_statecode | null;
  statuscode?: mailbox_statuscode | null;
  tagemailsafter?: Date | null;
  testemailconfigurationretrycount?: number | null;
  testemailconfigurationscheduled?: boolean | null;
  testmailboxaccesscompletedon?: Date | null;
  timezoneruleversionnumber?: number | null;
  transientfailurecount?: number | null;
  undeliverablefolder?: string | null;
  username?: string | null;
  utcconversiontimezonecode?: number | null;
  verboseloggingenabled?: number | null;
  versionnumber?: number | null;
}
interface Mailbox_Relationships {
  Mailbox_Annotation?: Annotation_Result[] | null;
  Mailbox_MailboxTrackingFolder?: MailboxTrackingFolder_Result[] | null;
  Mailbox_SyncErrors?: SyncError_Result[] | null;
  Mailbox_mailboxtrackingcategory?: MailboxTrackingCategory_Result[] | null;
  activitypointer_sendermailboxid_mailbox?: ActivityPointer_Result[] | null;
  bulkoperation_mailbox_sendermailboxid?: BulkOperation_Result[] | null;
  campaignactivity_mailbox_sendermailboxid?: CampaignActivity_Result[] | null;
  campaignresponse_mailbox_sendermailboxid?: CampaignResponse_Result[] | null;
  email_sendermailboxid_mailbox?: Email_Result[] | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  exchangesyncstatexmlfileref?: FileAttachment_Result | null;
  incidentresolution_mailbox_sendermailboxid?: IncidentResolution_Result[] | null;
  mailbox_FileAttachments?: FileAttachment_Result[] | null;
  mailbox_TraceRegardings?: TraceRegarding_Result[] | null;
  mailbox_asyncoperations?: AsyncOperation_Result[] | null;
  mailbox_email_ReceivingMailboxId?: Email_Result[] | null;
  mailbox_mailboxstatistics?: MailboxStatistics_Result[] | null;
  mailbox_processsessions?: ProcessSession_Result[] | null;
  mailbox_userentityinstancedatas?: UserEntityInstanceData_Result[] | null;
  msdyn_approval_mailbox_sendermailboxid?: msdyn_approval_Result[] | null;
  msdyn_bookingalert_mailbox_sendermailboxid?: msdyn_bookingalert_Result[] | null;
  msdyn_ocliveworkitem_mailbox_sendermailboxid?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_ocoutboundmessage_mailbox_sendermailboxid?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_ocsession_mailbox_sendermailboxid?: msdyn_ocsession_Result[] | null;
  msfp_alert_mailbox_sendermailboxid?: msfp_alert_Result[] | null;
  msfp_surveyinvite_mailbox_sendermailboxid?: msfp_surveyinvite_Result[] | null;
  msfp_surveyresponse_mailbox_sendermailboxid?: msfp_surveyresponse_Result[] | null;
  opportunityclose_mailbox_sendermailboxid?: OpportunityClose_Result[] | null;
  orderclose_mailbox_sendermailboxid?: OrderClose_Result[] | null;
  queue_defaultmailbox_mailbox?: Queue_Result[] | null;
  quoteclose_mailbox_sendermailboxid?: QuoteClose_Result[] | null;
  regardingobjectid_queue?: Queue_Result | null;
  serviceappointment_mailbox_sendermailboxid?: ServiceAppointment_Result[] | null;
  systemuser_defaultmailbox_mailbox?: SystemUser_Result[] | null;
  tracelog_Mailbox?: TraceLog_Result[] | null;
}
interface Mailbox extends Mailbox_Base, Mailbox_Relationships {
  emailserverprofile_bind$emailserverprofiles?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface Mailbox_Create extends Mailbox {
}
interface Mailbox_Update extends Mailbox {
}
interface Mailbox_Select {
  actdeliverymethod: WebAttribute<Mailbox_Select, { actdeliverymethod: mailbox_actdeliverymethod | null }, { actdeliverymethod_formatted?: string }>;
  actstatus: WebAttribute<Mailbox_Select, { actstatus: mailbox_actstatus | null }, { actstatus_formatted?: string }>;
  allowemailconnectortousecredentials: WebAttribute<Mailbox_Select, { allowemailconnectortousecredentials: boolean | null }, {  }>;
  averagetotalduration: WebAttribute<Mailbox_Select, { averagetotalduration: number | null }, {  }>;
  createdby_guid: WebAttribute<Mailbox_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Mailbox_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Mailbox_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  emailaddress: WebAttribute<Mailbox_Select, { emailaddress: string | null }, {  }>;
  emailrouteraccessapproval: WebAttribute<Mailbox_Select, { emailrouteraccessapproval: mailbox_emailrouteraccessapproval | null }, { emailrouteraccessapproval_formatted?: string }>;
  emailserverprofile_guid: WebAttribute<Mailbox_Select, { emailserverprofile_guid: string | null }, { emailserverprofile_formatted?: string }>;
  enabledforact: WebAttribute<Mailbox_Select, { enabledforact: boolean | null }, {  }>;
  enabledforincomingemail: WebAttribute<Mailbox_Select, { enabledforincomingemail: boolean | null }, {  }>;
  enabledforoutgoingemail: WebAttribute<Mailbox_Select, { enabledforoutgoingemail: boolean | null }, {  }>;
  entityimageid: WebAttribute<Mailbox_Select, { entityimageid: string | null }, {  }>;
  ewsurl: WebAttribute<Mailbox_Select, { ewsurl: string | null }, {  }>;
  exchangecontactsimportcompletedon: WebAttribute<Mailbox_Select, { exchangecontactsimportcompletedon: Date | null }, { exchangecontactsimportcompletedon_formatted?: string }>;
  exchangecontactsimportstatus: WebAttribute<Mailbox_Select, { exchangecontactsimportstatus: mailbox_exchangecontactsimportstatus | null }, { exchangecontactsimportstatus_formatted?: string }>;
  exchangesyncstatexml: WebAttribute<Mailbox_Select, { exchangesyncstatexml: string | null }, {  }>;
  folderhierarchy: WebAttribute<Mailbox_Select, { folderhierarchy: string | null }, {  }>;
  forcedunlockcount: WebAttribute<Mailbox_Select, { forcedunlockcount: number | null }, {  }>;
  hostid: WebAttribute<Mailbox_Select, { hostid: string | null }, {  }>;
  incomingemaildeliverymethod: WebAttribute<Mailbox_Select, { incomingemaildeliverymethod: mailbox_incomingemaildeliverymethod | null }, { incomingemaildeliverymethod_formatted?: string }>;
  incomingemailstatus: WebAttribute<Mailbox_Select, { incomingemailstatus: mailbox_incomingemailstatus | null }, { incomingemailstatus_formatted?: string }>;
  isactsyncorgflagset: WebAttribute<Mailbox_Select, { isactsyncorgflagset: boolean | null }, {  }>;
  isemailaddressapprovedbyo365admin: WebAttribute<Mailbox_Select, { isemailaddressapprovedbyo365admin: boolean | null }, {  }>;
  isexchangecontactsimportscheduled: WebAttribute<Mailbox_Select, { isexchangecontactsimportscheduled: boolean | null }, {  }>;
  isforwardmailbox: WebAttribute<Mailbox_Select, { isforwardmailbox: boolean | null }, {  }>;
  isoauthaccesstokenset: WebAttribute<Mailbox_Select, { isoauthaccesstokenset: boolean | null }, {  }>;
  isoauthrefreshtokenset: WebAttribute<Mailbox_Select, { isoauthrefreshtokenset: boolean | null }, {  }>;
  ispasswordset: WebAttribute<Mailbox_Select, { ispasswordset: boolean | null }, {  }>;
  isserviceaccount: WebAttribute<Mailbox_Select, { isserviceaccount: boolean | null }, {  }>;
  itemsfailedforlastsync: WebAttribute<Mailbox_Select, { itemsfailedforlastsync: number | null }, {  }>;
  itemsprocessedforlastsync: WebAttribute<Mailbox_Select, { itemsprocessedforlastsync: number | null }, {  }>;
  lastactiveon: WebAttribute<Mailbox_Select, { lastactiveon: Date | null }, { lastactiveon_formatted?: string }>;
  lastautodiscoveredon: WebAttribute<Mailbox_Select, { lastautodiscoveredon: Date | null }, { lastautodiscoveredon_formatted?: string }>;
  lastduration: WebAttribute<Mailbox_Select, { lastduration: number | null }, {  }>;
  lastmailboxforcedunlockoccurredon: WebAttribute<Mailbox_Select, { lastmailboxforcedunlockoccurredon: Date | null }, { lastmailboxforcedunlockoccurredon_formatted?: string }>;
  lastmessageid: WebAttribute<Mailbox_Select, { lastmessageid: string | null }, {  }>;
  lastsuccessfulsynccompletedon: WebAttribute<Mailbox_Select, { lastsuccessfulsynccompletedon: Date | null }, { lastsuccessfulsynccompletedon_formatted?: string }>;
  lastsyncerror: WebAttribute<Mailbox_Select, { lastsyncerror: string | null }, {  }>;
  lastsyncerrorcode: WebAttribute<Mailbox_Select, { lastsyncerrorcode: number | null }, {  }>;
  lastsyncerrorcount: WebAttribute<Mailbox_Select, { lastsyncerrorcount: number | null }, {  }>;
  lastsyncerrormachinename: WebAttribute<Mailbox_Select, { lastsyncerrormachinename: string | null }, {  }>;
  lastsyncerroroccurredon: WebAttribute<Mailbox_Select, { lastsyncerroroccurredon: Date | null }, { lastsyncerroroccurredon_formatted?: string }>;
  lastsyncstartedon: WebAttribute<Mailbox_Select, { lastsyncstartedon: Date | null }, { lastsyncstartedon_formatted?: string }>;
  lasttaggedmessageid: WebAttribute<Mailbox_Select, { lasttaggedmessageid: string | null }, {  }>;
  mailboxid: WebAttribute<Mailbox_Select, { mailboxid: string | null }, {  }>;
  mailboxprocessingcontext: WebAttribute<Mailbox_Select, { mailboxprocessingcontext: number | null }, {  }>;
  mailboxstatus: WebAttribute<Mailbox_Select, { mailboxstatus: mailbox_status | null }, { mailboxstatus_formatted?: string }>;
  modifiedby_guid: WebAttribute<Mailbox_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Mailbox_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Mailbox_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  name: WebAttribute<Mailbox_Select, { name: string | null }, {  }>;
  nextscheduledactsyncinseconds: WebAttribute<Mailbox_Select, { nextscheduledactsyncinseconds: number | null }, {  }>;
  noactcount: WebAttribute<Mailbox_Select, { noactcount: number | null }, {  }>;
  noemailcount: WebAttribute<Mailbox_Select, { noemailcount: number | null }, {  }>;
  oauthaccesstoken: WebAttribute<Mailbox_Select, { oauthaccesstoken: string | null }, {  }>;
  oauthrefreshtoken: WebAttribute<Mailbox_Select, { oauthrefreshtoken: string | null }, {  }>;
  oauthtokenexpireson: WebAttribute<Mailbox_Select, { oauthtokenexpireson: Date | null }, { oauthtokenexpireson_formatted?: string }>;
  officeappsdeploymentcompleteon: WebAttribute<Mailbox_Select, { officeappsdeploymentcompleteon: Date | null }, { officeappsdeploymentcompleteon_formatted?: string }>;
  officeappsdeploymenterror: WebAttribute<Mailbox_Select, { officeappsdeploymenterror: string | null }, {  }>;
  officeappsdeploymentscheduled: WebAttribute<Mailbox_Select, { officeappsdeploymentscheduled: boolean | null }, {  }>;
  officeappsdeploymentstatus: WebAttribute<Mailbox_Select, { officeappsdeploymentstatus: mailbox_officeappsdeploymentstatus | null }, { officeappsdeploymentstatus_formatted?: string }>;
  organizationid_guid: WebAttribute<Mailbox_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  orgmarkedasprimaryforexchangesync: WebAttribute<Mailbox_Select, { orgmarkedasprimaryforexchangesync: boolean | null }, {  }>;
  outgoingemaildeliverymethod: WebAttribute<Mailbox_Select, { outgoingemaildeliverymethod: mailbox_outgoingemaildeliverymethod | null }, { outgoingemaildeliverymethod_formatted?: string }>;
  outgoingemailstatus: WebAttribute<Mailbox_Select, { outgoingemailstatus: mailbox_outgoingemailstatus | null }, { outgoingemailstatus_formatted?: string }>;
  ownerid_guid: WebAttribute<Mailbox_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Mailbox_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Mailbox_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Mailbox_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  password: WebAttribute<Mailbox_Select, { password: string | null }, {  }>;
  postponemailboxprocessinguntil: WebAttribute<Mailbox_Select, { postponemailboxprocessinguntil: Date | null }, { postponemailboxprocessinguntil_formatted?: string }>;
  postponeofficeappsdeploymentuntil: WebAttribute<Mailbox_Select, { postponeofficeappsdeploymentuntil: Date | null }, { postponeofficeappsdeploymentuntil_formatted?: string }>;
  postponesendinguntil: WebAttribute<Mailbox_Select, { postponesendinguntil: Date | null }, { postponesendinguntil_formatted?: string }>;
  postponetestemailconfigurationuntil: WebAttribute<Mailbox_Select, { postponetestemailconfigurationuntil: Date | null }, { postponetestemailconfigurationuntil_formatted?: string }>;
  processanddeleteemails: WebAttribute<Mailbox_Select, { processanddeleteemails: boolean | null }, {  }>;
  processedtimes: WebAttribute<Mailbox_Select, { processedtimes: number | null }, {  }>;
  processemailreceivedafter: WebAttribute<Mailbox_Select, { processemailreceivedafter: Date | null }, { processemailreceivedafter_formatted?: string }>;
  processinglastattemptedon: WebAttribute<Mailbox_Select, { processinglastattemptedon: Date | null }, { processinglastattemptedon_formatted?: string }>;
  processingstatecode: WebAttribute<Mailbox_Select, { processingstatecode: number | null }, {  }>;
  receivingpostponeduntil: WebAttribute<Mailbox_Select, { receivingpostponeduntil: Date | null }, { receivingpostponeduntil_formatted?: string }>;
  receivingpostponeduntilforact: WebAttribute<Mailbox_Select, { receivingpostponeduntilforact: Date | null }, { receivingpostponeduntilforact_formatted?: string }>;
  regardingobjectid_guid: WebAttribute<Mailbox_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  statecode: WebAttribute<Mailbox_Select, { statecode: mailbox_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Mailbox_Select, { statuscode: mailbox_statuscode | null }, { statuscode_formatted?: string }>;
  tagemailsafter: WebAttribute<Mailbox_Select, { tagemailsafter: Date | null }, { tagemailsafter_formatted?: string }>;
  testemailconfigurationretrycount: WebAttribute<Mailbox_Select, { testemailconfigurationretrycount: number | null }, {  }>;
  testemailconfigurationscheduled: WebAttribute<Mailbox_Select, { testemailconfigurationscheduled: boolean | null }, {  }>;
  testmailboxaccesscompletedon: WebAttribute<Mailbox_Select, { testmailboxaccesscompletedon: Date | null }, { testmailboxaccesscompletedon_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<Mailbox_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transientfailurecount: WebAttribute<Mailbox_Select, { transientfailurecount: number | null }, {  }>;
  undeliverablefolder: WebAttribute<Mailbox_Select, { undeliverablefolder: string | null }, {  }>;
  username: WebAttribute<Mailbox_Select, { username: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Mailbox_Select, { utcconversiontimezonecode: number | null }, {  }>;
  verboseloggingenabled: WebAttribute<Mailbox_Select, { verboseloggingenabled: number | null }, {  }>;
  versionnumber: WebAttribute<Mailbox_Select, { versionnumber: number | null }, {  }>;
}
interface Mailbox_Filter {
  actdeliverymethod: mailbox_actdeliverymethod;
  actstatus: mailbox_actstatus;
  allowemailconnectortousecredentials: boolean;
  averagetotalduration: number;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  emailaddress: string;
  emailrouteraccessapproval: mailbox_emailrouteraccessapproval;
  emailserverprofile_guid: XQW.Guid;
  enabledforact: boolean;
  enabledforincomingemail: boolean;
  enabledforoutgoingemail: boolean;
  entityimageid: XQW.Guid;
  ewsurl: string;
  exchangecontactsimportcompletedon: Date;
  exchangecontactsimportstatus: mailbox_exchangecontactsimportstatus;
  exchangesyncstatexml: string;
  folderhierarchy: string;
  forcedunlockcount: number;
  hostid: string;
  incomingemaildeliverymethod: mailbox_incomingemaildeliverymethod;
  incomingemailstatus: mailbox_incomingemailstatus;
  isactsyncorgflagset: boolean;
  isemailaddressapprovedbyo365admin: boolean;
  isexchangecontactsimportscheduled: boolean;
  isforwardmailbox: boolean;
  isoauthaccesstokenset: boolean;
  isoauthrefreshtokenset: boolean;
  ispasswordset: boolean;
  isserviceaccount: boolean;
  itemsfailedforlastsync: number;
  itemsprocessedforlastsync: number;
  lastactiveon: Date;
  lastautodiscoveredon: Date;
  lastduration: number;
  lastmailboxforcedunlockoccurredon: Date;
  lastmessageid: string;
  lastsuccessfulsynccompletedon: Date;
  lastsyncerror: string;
  lastsyncerrorcode: number;
  lastsyncerrorcount: number;
  lastsyncerrormachinename: string;
  lastsyncerroroccurredon: Date;
  lastsyncstartedon: Date;
  lasttaggedmessageid: string;
  mailboxid: XQW.Guid;
  mailboxprocessingcontext: number;
  mailboxstatus: mailbox_status;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  name: string;
  nextscheduledactsyncinseconds: number;
  noactcount: number;
  noemailcount: number;
  oauthaccesstoken: string;
  oauthrefreshtoken: string;
  oauthtokenexpireson: Date;
  officeappsdeploymentcompleteon: Date;
  officeappsdeploymenterror: string;
  officeappsdeploymentscheduled: boolean;
  officeappsdeploymentstatus: mailbox_officeappsdeploymentstatus;
  organizationid_guid: XQW.Guid;
  orgmarkedasprimaryforexchangesync: boolean;
  outgoingemaildeliverymethod: mailbox_outgoingemaildeliverymethod;
  outgoingemailstatus: mailbox_outgoingemailstatus;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  password: string;
  postponemailboxprocessinguntil: Date;
  postponeofficeappsdeploymentuntil: Date;
  postponesendinguntil: Date;
  postponetestemailconfigurationuntil: Date;
  processanddeleteemails: boolean;
  processedtimes: number;
  processemailreceivedafter: Date;
  processinglastattemptedon: Date;
  processingstatecode: number;
  receivingpostponeduntil: Date;
  receivingpostponeduntilforact: Date;
  regardingobjectid_guid: XQW.Guid;
  statecode: mailbox_statecode;
  statuscode: mailbox_statuscode;
  tagemailsafter: Date;
  testemailconfigurationretrycount: number;
  testemailconfigurationscheduled: boolean;
  testmailboxaccesscompletedon: Date;
  timezoneruleversionnumber: number;
  transientfailurecount: number;
  undeliverablefolder: string;
  username: string;
  utcconversiontimezonecode: number;
  verboseloggingenabled: number;
  versionnumber: number;
}
interface Mailbox_Expand {
  Mailbox_Annotation: WebExpand<Mailbox_Expand, Annotation_Select, Annotation_Filter, { Mailbox_Annotation: Annotation_Result[] }>;
  Mailbox_MailboxTrackingFolder: WebExpand<Mailbox_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { Mailbox_MailboxTrackingFolder: MailboxTrackingFolder_Result[] }>;
  Mailbox_SyncErrors: WebExpand<Mailbox_Expand, SyncError_Select, SyncError_Filter, { Mailbox_SyncErrors: SyncError_Result[] }>;
  Mailbox_mailboxtrackingcategory: WebExpand<Mailbox_Expand, MailboxTrackingCategory_Select, MailboxTrackingCategory_Filter, { Mailbox_mailboxtrackingcategory: MailboxTrackingCategory_Result[] }>;
  activitypointer_sendermailboxid_mailbox: WebExpand<Mailbox_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activitypointer_sendermailboxid_mailbox: ActivityPointer_Result[] }>;
  bulkoperation_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, BulkOperation_Select, BulkOperation_Filter, { bulkoperation_mailbox_sendermailboxid: BulkOperation_Result[] }>;
  campaignactivity_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, CampaignActivity_Select, CampaignActivity_Filter, { campaignactivity_mailbox_sendermailboxid: CampaignActivity_Result[] }>;
  campaignresponse_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, CampaignResponse_Select, CampaignResponse_Filter, { campaignresponse_mailbox_sendermailboxid: CampaignResponse_Result[] }>;
  createdby: WebExpand<Mailbox_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Mailbox_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  email_sendermailboxid_mailbox: WebExpand<Mailbox_Expand, Email_Select, Email_Filter, { email_sendermailboxid_mailbox: Email_Result[] }>;
  emailserverprofile: WebExpand<Mailbox_Expand, EmailServerProfile_Select, EmailServerProfile_Filter, { emailserverprofile: EmailServerProfile_Result }>;
  entityimageid_imagedescriptor: WebExpand<Mailbox_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  exchangesyncstatexmlfileref: WebExpand<Mailbox_Expand, FileAttachment_Select, FileAttachment_Filter, { exchangesyncstatexmlfileref: FileAttachment_Result }>;
  incidentresolution_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, IncidentResolution_Select, IncidentResolution_Filter, { incidentresolution_mailbox_sendermailboxid: IncidentResolution_Result[] }>;
  mailbox_FileAttachments: WebExpand<Mailbox_Expand, FileAttachment_Select, FileAttachment_Filter, { mailbox_FileAttachments: FileAttachment_Result[] }>;
  mailbox_TraceRegardings: WebExpand<Mailbox_Expand, TraceRegarding_Select, TraceRegarding_Filter, { mailbox_TraceRegardings: TraceRegarding_Result[] }>;
  mailbox_asyncoperations: WebExpand<Mailbox_Expand, AsyncOperation_Select, AsyncOperation_Filter, { mailbox_asyncoperations: AsyncOperation_Result[] }>;
  mailbox_email_ReceivingMailboxId: WebExpand<Mailbox_Expand, Email_Select, Email_Filter, { mailbox_email_ReceivingMailboxId: Email_Result[] }>;
  mailbox_mailboxstatistics: WebExpand<Mailbox_Expand, MailboxStatistics_Select, MailboxStatistics_Filter, { mailbox_mailboxstatistics: MailboxStatistics_Result[] }>;
  mailbox_processsessions: WebExpand<Mailbox_Expand, ProcessSession_Select, ProcessSession_Filter, { mailbox_processsessions: ProcessSession_Result[] }>;
  mailbox_userentityinstancedatas: WebExpand<Mailbox_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { mailbox_userentityinstancedatas: UserEntityInstanceData_Result[] }>;
  modifiedby: WebExpand<Mailbox_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Mailbox_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_approval_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_approval_mailbox_sendermailboxid: msdyn_approval_Result[] }>;
  msdyn_bookingalert_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_bookingalert_mailbox_sendermailboxid: msdyn_bookingalert_Result[] }>;
  msdyn_ocliveworkitem_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_ocliveworkitem_mailbox_sendermailboxid: msdyn_ocliveworkitem_Result[] }>;
  msdyn_ocoutboundmessage_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_ocoutboundmessage_mailbox_sendermailboxid: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_ocsession_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_ocsession_mailbox_sendermailboxid: msdyn_ocsession_Result[] }>;
  msfp_alert_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, msfp_alert_Select, msfp_alert_Filter, { msfp_alert_mailbox_sendermailboxid: msfp_alert_Result[] }>;
  msfp_surveyinvite_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msfp_surveyinvite_mailbox_sendermailboxid: msfp_surveyinvite_Result[] }>;
  msfp_surveyresponse_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msfp_surveyresponse_mailbox_sendermailboxid: msfp_surveyresponse_Result[] }>;
  opportunityclose_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, OpportunityClose_Select, OpportunityClose_Filter, { opportunityclose_mailbox_sendermailboxid: OpportunityClose_Result[] }>;
  orderclose_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, OrderClose_Select, OrderClose_Filter, { orderclose_mailbox_sendermailboxid: OrderClose_Result[] }>;
  organizationid: WebExpand<Mailbox_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  ownerid: WebExpand<Mailbox_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<Mailbox_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<Mailbox_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<Mailbox_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  queue_defaultmailbox_mailbox: WebExpand<Mailbox_Expand, Queue_Select, Queue_Filter, { queue_defaultmailbox_mailbox: Queue_Result[] }>;
  quoteclose_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, QuoteClose_Select, QuoteClose_Filter, { quoteclose_mailbox_sendermailboxid: QuoteClose_Result[] }>;
  regardingobjectid: WebExpand<Mailbox_Expand, SystemUser_Select, SystemUser_Filter, { regardingobjectid: SystemUser_Result }>;
  regardingobjectid_queue: WebExpand<Mailbox_Expand, Queue_Select, Queue_Filter, { regardingobjectid_queue: Queue_Result }>;
  serviceappointment_mailbox_sendermailboxid: WebExpand<Mailbox_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { serviceappointment_mailbox_sendermailboxid: ServiceAppointment_Result[] }>;
  systemuser_defaultmailbox_mailbox: WebExpand<Mailbox_Expand, SystemUser_Select, SystemUser_Filter, { systemuser_defaultmailbox_mailbox: SystemUser_Result[] }>;
  tracelog_Mailbox: WebExpand<Mailbox_Expand, TraceLog_Select, TraceLog_Filter, { tracelog_Mailbox: TraceLog_Result[] }>;
}
interface Mailbox_FormattedResult {
  actdeliverymethod_formatted?: string;
  actstatus_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  emailrouteraccessapproval_formatted?: string;
  emailserverprofile_formatted?: string;
  exchangecontactsimportcompletedon_formatted?: string;
  exchangecontactsimportstatus_formatted?: string;
  incomingemaildeliverymethod_formatted?: string;
  incomingemailstatus_formatted?: string;
  lastactiveon_formatted?: string;
  lastautodiscoveredon_formatted?: string;
  lastmailboxforcedunlockoccurredon_formatted?: string;
  lastsuccessfulsynccompletedon_formatted?: string;
  lastsyncerroroccurredon_formatted?: string;
  lastsyncstartedon_formatted?: string;
  mailboxstatus_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  oauthtokenexpireson_formatted?: string;
  officeappsdeploymentcompleteon_formatted?: string;
  officeappsdeploymentstatus_formatted?: string;
  organizationid_formatted?: string;
  outgoingemaildeliverymethod_formatted?: string;
  outgoingemailstatus_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  postponemailboxprocessinguntil_formatted?: string;
  postponeofficeappsdeploymentuntil_formatted?: string;
  postponesendinguntil_formatted?: string;
  postponetestemailconfigurationuntil_formatted?: string;
  processemailreceivedafter_formatted?: string;
  processinglastattemptedon_formatted?: string;
  receivingpostponeduntil_formatted?: string;
  receivingpostponeduntilforact_formatted?: string;
  regardingobjectid_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  tagemailsafter_formatted?: string;
  testmailboxaccesscompletedon_formatted?: string;
}
interface Mailbox_Result extends Mailbox_Base, Mailbox_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  emailserverprofile_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  organizationid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
}
interface Mailbox_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  emailserverprofile: WebMappingRetrieve<EmailServerProfile_Select,EmailServerProfile_Expand,EmailServerProfile_Filter,EmailServerProfile_Fixed,EmailServerProfile_Result,EmailServerProfile_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  exchangesyncstatexmlfileref: WebMappingRetrieve<FileAttachment_Select,FileAttachment_Expand,FileAttachment_Filter,FileAttachment_Fixed,FileAttachment_Result,FileAttachment_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_queue: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
}
interface Mailbox_RelatedMany {
  Mailbox_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Mailbox_MailboxTrackingFolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  Mailbox_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  Mailbox_mailboxtrackingcategory: WebMappingRetrieve<MailboxTrackingCategory_Select,MailboxTrackingCategory_Expand,MailboxTrackingCategory_Filter,MailboxTrackingCategory_Fixed,MailboxTrackingCategory_Result,MailboxTrackingCategory_FormattedResult>;
  activitypointer_sendermailboxid_mailbox: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  bulkoperation_mailbox_sendermailboxid: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  campaignactivity_mailbox_sendermailboxid: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  campaignresponse_mailbox_sendermailboxid: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  email_sendermailboxid_mailbox: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  incidentresolution_mailbox_sendermailboxid: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  mailbox_FileAttachments: WebMappingRetrieve<FileAttachment_Select,FileAttachment_Expand,FileAttachment_Filter,FileAttachment_Fixed,FileAttachment_Result,FileAttachment_FormattedResult>;
  mailbox_TraceRegardings: WebMappingRetrieve<TraceRegarding_Select,TraceRegarding_Expand,TraceRegarding_Filter,TraceRegarding_Fixed,TraceRegarding_Result,TraceRegarding_FormattedResult>;
  mailbox_asyncoperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  mailbox_email_ReceivingMailboxId: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  mailbox_mailboxstatistics: WebMappingRetrieve<MailboxStatistics_Select,MailboxStatistics_Expand,MailboxStatistics_Filter,MailboxStatistics_Fixed,MailboxStatistics_Result,MailboxStatistics_FormattedResult>;
  mailbox_processsessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  mailbox_userentityinstancedatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_approval_mailbox_sendermailboxid: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_bookingalert_mailbox_sendermailboxid: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_ocliveworkitem_mailbox_sendermailboxid: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_ocoutboundmessage_mailbox_sendermailboxid: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_ocsession_mailbox_sendermailboxid: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msfp_alert_mailbox_sendermailboxid: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msfp_surveyinvite_mailbox_sendermailboxid: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msfp_surveyresponse_mailbox_sendermailboxid: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  opportunityclose_mailbox_sendermailboxid: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  orderclose_mailbox_sendermailboxid: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  queue_defaultmailbox_mailbox: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  quoteclose_mailbox_sendermailboxid: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  serviceappointment_mailbox_sendermailboxid: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  systemuser_defaultmailbox_mailbox: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  tracelog_Mailbox: WebMappingRetrieve<TraceLog_Select,TraceLog_Expand,TraceLog_Filter,TraceLog_Fixed,TraceLog_Result,TraceLog_FormattedResult>;
}
interface WebEntitiesRetrieve {
  mailboxes: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
}
interface WebEntitiesRelated {
  mailboxes: WebMappingRelated<Mailbox_RelatedOne,Mailbox_RelatedMany>;
}
interface WebEntitiesCUDA {
  mailboxes: WebMappingCUDA<Mailbox_Create,Mailbox_Update,Mailbox_Select>;
}
