interface msdyn_workorderservice_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_additionalcost?: number | null;
  msdyn_additionalcost_base?: number | null;
  msdyn_calculatedunitamount?: number | null;
  msdyn_calculatedunitamount_base?: number | null;
  msdyn_commissioncosts?: number | null;
  msdyn_commissioncosts_base?: number | null;
  msdyn_description?: string | null;
  msdyn_disableentitlement?: boolean | null;
  msdyn_discountamount?: number | null;
  msdyn_discountamount_base?: number | null;
  msdyn_discountpercent?: number | null;
  msdyn_duration?: number | null;
  msdyn_durationtobill?: number | null;
  msdyn_estimatecalculatedunitamount?: number | null;
  msdyn_estimatecalculatedunitamount_base?: number | null;
  msdyn_estimatediscountamount?: number | null;
  msdyn_estimatediscountamount_base?: number | null;
  msdyn_estimatediscountpercent?: number | null;
  msdyn_estimateduration?: number | null;
  msdyn_estimatesubtotal?: number | null;
  msdyn_estimatesubtotal_base?: number | null;
  msdyn_estimatetotalamount?: number | null;
  msdyn_estimatetotalamount_base?: number | null;
  msdyn_estimatetotalcost?: number | null;
  msdyn_estimatetotalcost_base?: number | null;
  msdyn_estimateunitamount?: number | null;
  msdyn_estimateunitamount_base?: number | null;
  msdyn_estimateunitcost?: number | null;
  msdyn_estimateunitcost_base?: number | null;
  msdyn_internaldescription?: string | null;
  msdyn_internalflags?: string | null;
  msdyn_lineorder?: number | null;
  msdyn_linestatus?: msdyn_productservicestatus | null;
  msdyn_minimumchargeamount?: number | null;
  msdyn_minimumchargeamount_base?: number | null;
  msdyn_minimumchargeduration?: number | null;
  msdyn_name?: string | null;
  msdyn_subtotal?: number | null;
  msdyn_subtotal_base?: number | null;
  msdyn_taxable?: boolean | null;
  msdyn_totalamount?: number | null;
  msdyn_totalamount_base?: number | null;
  msdyn_totalcost?: number | null;
  msdyn_totalcost_base?: number | null;
  msdyn_unitamount?: number | null;
  msdyn_unitamount_base?: number | null;
  msdyn_unitcost?: number | null;
  msdyn_unitcost_base?: number | null;
  msdyn_workorderserviceid?: string | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_workorderservice_statecode | null;
  statuscode?: msdyn_workorderservice_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_workorderservice_Relationships {
  msdyn_msdyn_workorderservice_invoicedetail?: InvoiceDetail_Result[] | null;
  msdyn_workorderservice_ActivityPointers?: ActivityPointer_Result[] | null;
  msdyn_workorderservice_Annotations?: Annotation_Result[] | null;
  msdyn_workorderservice_Appointments?: Appointment_Result[] | null;
  msdyn_workorderservice_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_workorderservice_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_workorderservice_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_workorderservice_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_workorderservice_Emails?: Email_Result[] | null;
  msdyn_workorderservice_Faxes?: Fax_Result[] | null;
  msdyn_workorderservice_Letters?: Letter_Result[] | null;
  msdyn_workorderservice_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_workorderservice_PhoneCalls?: PhoneCall_Result[] | null;
  msdyn_workorderservice_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_workorderservice_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_workorderservice_QueueItems?: QueueItem_Result[] | null;
  msdyn_workorderservice_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  msdyn_workorderservice_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_workorderservice_SharePointDocumentLocations?: SharePointDocumentLocation_Result[] | null;
  msdyn_workorderservice_SharePointDocuments?: SharePointDocument_Result[] | null;
  msdyn_workorderservice_SocialActivities?: SocialActivity_Result[] | null;
  msdyn_workorderservice_SyncErrors?: SyncError_Result[] | null;
  msdyn_workorderservice_Tasks?: Task_Result[] | null;
  msdyn_workorderservice_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_workorderservice_connections1?: Connection_Result[] | null;
  msdyn_workorderservice_connections2?: Connection_Result[] | null;
  msdyn_workorderservice_msdyn_approvals?: msdyn_approval_Result[] | null;
  msdyn_workorderservice_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  msdyn_workorderservice_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_workorderservice_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_workorderservice_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  msdyn_workorderservice_msfp_alerts?: msfp_alert_Result[] | null;
  msdyn_workorderservice_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  msdyn_workorderservice_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
}
interface msdyn_workorderservice extends msdyn_workorderservice_Base, msdyn_workorderservice_Relationships {
  msdyn_agreementbookingservice_bind$msdyn_agreementbookingservices?: string | null;
  msdyn_booking_bind$bookableresourcebookings?: string | null;
  msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  msdyn_entitlement_bind$entitlements?: string | null;
  msdyn_pricelist_bind$pricelevels?: string | null;
  msdyn_service_bind$products?: string | null;
  msdyn_unit_bind$uoms?: string | null;
  msdyn_workorder_bind$msdyn_workorders?: string | null;
  msdyn_workorderincident_bind$msdyn_workorderincidents?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface msdyn_workorderservice_Create extends msdyn_workorderservice {
}
interface msdyn_workorderservice_Update extends msdyn_workorderservice {
}
interface msdyn_workorderservice_Select {
  createdby_guid: WebAttribute<msdyn_workorderservice_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_workorderservice_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_workorderservice_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_workorderservice_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_workorderservice_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_workorderservice_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_workorderservice_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_workorderservice_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_additionalcost: WebAttribute<msdyn_workorderservice_Select, { msdyn_additionalcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_additionalcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_additionalcost_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_additionalcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_additionalcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_agreementbookingservice_guid: WebAttribute<msdyn_workorderservice_Select, { msdyn_agreementbookingservice_guid: string | null }, { msdyn_agreementbookingservice_formatted?: string }>;
  msdyn_booking_guid: WebAttribute<msdyn_workorderservice_Select, { msdyn_booking_guid: string | null }, { msdyn_booking_formatted?: string }>;
  msdyn_calculatedunitamount: WebAttribute<msdyn_workorderservice_Select, { msdyn_calculatedunitamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_calculatedunitamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_calculatedunitamount_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_calculatedunitamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_calculatedunitamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_commissioncosts: WebAttribute<msdyn_workorderservice_Select, { msdyn_commissioncosts: number | null; transactioncurrencyid_guid: string | null }, { msdyn_commissioncosts_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_commissioncosts_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_commissioncosts_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_commissioncosts_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_customerasset_guid: WebAttribute<msdyn_workorderservice_Select, { msdyn_customerasset_guid: string | null }, { msdyn_customerasset_formatted?: string }>;
  msdyn_description: WebAttribute<msdyn_workorderservice_Select, { msdyn_description: string | null }, {  }>;
  msdyn_disableentitlement: WebAttribute<msdyn_workorderservice_Select, { msdyn_disableentitlement: boolean | null }, {  }>;
  msdyn_discountamount: WebAttribute<msdyn_workorderservice_Select, { msdyn_discountamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_discountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_discountamount_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_discountamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_discountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_discountpercent: WebAttribute<msdyn_workorderservice_Select, { msdyn_discountpercent: number | null }, {  }>;
  msdyn_duration: WebAttribute<msdyn_workorderservice_Select, { msdyn_duration: number | null }, {  }>;
  msdyn_durationtobill: WebAttribute<msdyn_workorderservice_Select, { msdyn_durationtobill: number | null }, {  }>;
  msdyn_entitlement_guid: WebAttribute<msdyn_workorderservice_Select, { msdyn_entitlement_guid: string | null }, { msdyn_entitlement_formatted?: string }>;
  msdyn_estimatecalculatedunitamount: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatecalculatedunitamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatecalculatedunitamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatecalculatedunitamount_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatecalculatedunitamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatecalculatedunitamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatediscountamount: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatediscountamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatediscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatediscountamount_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatediscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatediscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatediscountpercent: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatediscountpercent: number | null }, {  }>;
  msdyn_estimateduration: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimateduration: number | null }, {  }>;
  msdyn_estimatesubtotal: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatesubtotal: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatesubtotal_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatesubtotal_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatesubtotal_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatesubtotal_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatetotalamount: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatetotalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatetotalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatetotalamount_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatetotalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatetotalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatetotalcost: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatetotalcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatetotalcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatetotalcost_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimatetotalcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatetotalcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimateunitamount: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimateunitamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimateunitamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimateunitamount_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimateunitamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimateunitamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimateunitcost: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimateunitcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimateunitcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimateunitcost_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_estimateunitcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimateunitcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_internaldescription: WebAttribute<msdyn_workorderservice_Select, { msdyn_internaldescription: string | null }, {  }>;
  msdyn_internalflags: WebAttribute<msdyn_workorderservice_Select, { msdyn_internalflags: string | null }, {  }>;
  msdyn_lineorder: WebAttribute<msdyn_workorderservice_Select, { msdyn_lineorder: number | null }, {  }>;
  msdyn_linestatus: WebAttribute<msdyn_workorderservice_Select, { msdyn_linestatus: msdyn_productservicestatus | null }, { msdyn_linestatus_formatted?: string }>;
  msdyn_minimumchargeamount: WebAttribute<msdyn_workorderservice_Select, { msdyn_minimumchargeamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_minimumchargeamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_minimumchargeamount_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_minimumchargeamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_minimumchargeamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_minimumchargeduration: WebAttribute<msdyn_workorderservice_Select, { msdyn_minimumchargeduration: number | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_workorderservice_Select, { msdyn_name: string | null }, {  }>;
  msdyn_pricelist_guid: WebAttribute<msdyn_workorderservice_Select, { msdyn_pricelist_guid: string | null }, { msdyn_pricelist_formatted?: string }>;
  msdyn_service_guid: WebAttribute<msdyn_workorderservice_Select, { msdyn_service_guid: string | null }, { msdyn_service_formatted?: string }>;
  msdyn_subtotal: WebAttribute<msdyn_workorderservice_Select, { msdyn_subtotal: number | null; transactioncurrencyid_guid: string | null }, { msdyn_subtotal_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_subtotal_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_subtotal_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_subtotal_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_taxable: WebAttribute<msdyn_workorderservice_Select, { msdyn_taxable: boolean | null }, {  }>;
  msdyn_totalamount: WebAttribute<msdyn_workorderservice_Select, { msdyn_totalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalamount_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_totalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalcost: WebAttribute<msdyn_workorderservice_Select, { msdyn_totalcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalcost_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_totalcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unit_guid: WebAttribute<msdyn_workorderservice_Select, { msdyn_unit_guid: string | null }, { msdyn_unit_formatted?: string }>;
  msdyn_unitamount: WebAttribute<msdyn_workorderservice_Select, { msdyn_unitamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unitamount_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_unitamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unitcost: WebAttribute<msdyn_workorderservice_Select, { msdyn_unitcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unitcost_base: WebAttribute<msdyn_workorderservice_Select, { msdyn_unitcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_workorder_guid: WebAttribute<msdyn_workorderservice_Select, { msdyn_workorder_guid: string | null }, { msdyn_workorder_formatted?: string }>;
  msdyn_workorderincident_guid: WebAttribute<msdyn_workorderservice_Select, { msdyn_workorderincident_guid: string | null }, { msdyn_workorderincident_formatted?: string }>;
  msdyn_workorderserviceid: WebAttribute<msdyn_workorderservice_Select, { msdyn_workorderserviceid: string | null }, {  }>;
  overriddencreatedon: WebAttribute<msdyn_workorderservice_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_workorderservice_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_workorderservice_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_workorderservice_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_workorderservice_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_workorderservice_Select, { statecode: msdyn_workorderservice_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_workorderservice_Select, { statuscode: msdyn_workorderservice_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_workorderservice_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_workorderservice_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<msdyn_workorderservice_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_workorderservice_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_workorderservice_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_additionalcost: number;
  msdyn_additionalcost_base: number;
  msdyn_agreementbookingservice_guid: XQW.Guid;
  msdyn_booking_guid: XQW.Guid;
  msdyn_calculatedunitamount: number;
  msdyn_calculatedunitamount_base: number;
  msdyn_commissioncosts: number;
  msdyn_commissioncosts_base: number;
  msdyn_customerasset_guid: XQW.Guid;
  msdyn_description: string;
  msdyn_disableentitlement: boolean;
  msdyn_discountamount: number;
  msdyn_discountamount_base: number;
  msdyn_discountpercent: number;
  msdyn_duration: number;
  msdyn_durationtobill: number;
  msdyn_entitlement_guid: XQW.Guid;
  msdyn_estimatecalculatedunitamount: number;
  msdyn_estimatecalculatedunitamount_base: number;
  msdyn_estimatediscountamount: number;
  msdyn_estimatediscountamount_base: number;
  msdyn_estimatediscountpercent: number;
  msdyn_estimateduration: number;
  msdyn_estimatesubtotal: number;
  msdyn_estimatesubtotal_base: number;
  msdyn_estimatetotalamount: number;
  msdyn_estimatetotalamount_base: number;
  msdyn_estimatetotalcost: number;
  msdyn_estimatetotalcost_base: number;
  msdyn_estimateunitamount: number;
  msdyn_estimateunitamount_base: number;
  msdyn_estimateunitcost: number;
  msdyn_estimateunitcost_base: number;
  msdyn_internaldescription: string;
  msdyn_internalflags: string;
  msdyn_lineorder: number;
  msdyn_linestatus: msdyn_productservicestatus;
  msdyn_minimumchargeamount: number;
  msdyn_minimumchargeamount_base: number;
  msdyn_minimumchargeduration: number;
  msdyn_name: string;
  msdyn_pricelist_guid: XQW.Guid;
  msdyn_service_guid: XQW.Guid;
  msdyn_subtotal: number;
  msdyn_subtotal_base: number;
  msdyn_taxable: boolean;
  msdyn_totalamount: number;
  msdyn_totalamount_base: number;
  msdyn_totalcost: number;
  msdyn_totalcost_base: number;
  msdyn_unit_guid: XQW.Guid;
  msdyn_unitamount: number;
  msdyn_unitamount_base: number;
  msdyn_unitcost: number;
  msdyn_unitcost_base: number;
  msdyn_workorder_guid: XQW.Guid;
  msdyn_workorderincident_guid: XQW.Guid;
  msdyn_workorderserviceid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_workorderservice_statecode;
  statuscode: msdyn_workorderservice_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_workorderservice_Expand {
  createdby: WebExpand<msdyn_workorderservice_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_workorderservice_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_workorderservice_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_workorderservice_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_agreementbookingservice: WebExpand<msdyn_workorderservice_Expand, msdyn_agreementbookingservice_Select, msdyn_agreementbookingservice_Filter, { msdyn_agreementbookingservice: msdyn_agreementbookingservice_Result }>;
  msdyn_booking: WebExpand<msdyn_workorderservice_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { msdyn_booking: BookableResourceBooking_Result }>;
  msdyn_customerasset: WebExpand<msdyn_workorderservice_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_customerasset: msdyn_customerasset_Result }>;
  msdyn_entitlement: WebExpand<msdyn_workorderservice_Expand, Entitlement_Select, Entitlement_Filter, { msdyn_entitlement: Entitlement_Result }>;
  msdyn_msdyn_workorderservice_invoicedetail: WebExpand<msdyn_workorderservice_Expand, InvoiceDetail_Select, InvoiceDetail_Filter, { msdyn_msdyn_workorderservice_invoicedetail: InvoiceDetail_Result[] }>;
  msdyn_pricelist: WebExpand<msdyn_workorderservice_Expand, PriceLevel_Select, PriceLevel_Filter, { msdyn_pricelist: PriceLevel_Result }>;
  msdyn_service: WebExpand<msdyn_workorderservice_Expand, Product_Select, Product_Filter, { msdyn_service: Product_Result }>;
  msdyn_unit: WebExpand<msdyn_workorderservice_Expand, UoM_Select, UoM_Filter, { msdyn_unit: UoM_Result }>;
  msdyn_workorder: WebExpand<msdyn_workorderservice_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_workorder: msdyn_workorder_Result }>;
  msdyn_workorderincident: WebExpand<msdyn_workorderservice_Expand, msdyn_workorderincident_Select, msdyn_workorderincident_Filter, { msdyn_workorderincident: msdyn_workorderincident_Result }>;
  msdyn_workorderservice_ActivityPointers: WebExpand<msdyn_workorderservice_Expand, ActivityPointer_Select, ActivityPointer_Filter, { msdyn_workorderservice_ActivityPointers: ActivityPointer_Result[] }>;
  msdyn_workorderservice_Annotations: WebExpand<msdyn_workorderservice_Expand, Annotation_Select, Annotation_Filter, { msdyn_workorderservice_Annotations: Annotation_Result[] }>;
  msdyn_workorderservice_Appointments: WebExpand<msdyn_workorderservice_Expand, Appointment_Select, Appointment_Filter, { msdyn_workorderservice_Appointments: Appointment_Result[] }>;
  msdyn_workorderservice_AsyncOperations: WebExpand<msdyn_workorderservice_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_workorderservice_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_workorderservice_BulkDeleteFailures: WebExpand<msdyn_workorderservice_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_workorderservice_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_workorderservice_DuplicateBaseRecord: WebExpand<msdyn_workorderservice_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_workorderservice_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_workorderservice_DuplicateMatchingRecord: WebExpand<msdyn_workorderservice_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_workorderservice_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_workorderservice_Emails: WebExpand<msdyn_workorderservice_Expand, Email_Select, Email_Filter, { msdyn_workorderservice_Emails: Email_Result[] }>;
  msdyn_workorderservice_Faxes: WebExpand<msdyn_workorderservice_Expand, Fax_Select, Fax_Filter, { msdyn_workorderservice_Faxes: Fax_Result[] }>;
  msdyn_workorderservice_Letters: WebExpand<msdyn_workorderservice_Expand, Letter_Select, Letter_Filter, { msdyn_workorderservice_Letters: Letter_Result[] }>;
  msdyn_workorderservice_MailboxTrackingFolders: WebExpand<msdyn_workorderservice_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_workorderservice_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_workorderservice_PhoneCalls: WebExpand<msdyn_workorderservice_Expand, PhoneCall_Select, PhoneCall_Filter, { msdyn_workorderservice_PhoneCalls: PhoneCall_Result[] }>;
  msdyn_workorderservice_PrincipalObjectAttributeAccesses: WebExpand<msdyn_workorderservice_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_workorderservice_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_workorderservice_ProcessSession: WebExpand<msdyn_workorderservice_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_workorderservice_ProcessSession: ProcessSession_Result[] }>;
  msdyn_workorderservice_QueueItems: WebExpand<msdyn_workorderservice_Expand, QueueItem_Select, QueueItem_Filter, { msdyn_workorderservice_QueueItems: QueueItem_Result[] }>;
  msdyn_workorderservice_RecurringAppointmentMasters: WebExpand<msdyn_workorderservice_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { msdyn_workorderservice_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  msdyn_workorderservice_ServiceAppointments: WebExpand<msdyn_workorderservice_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_workorderservice_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_workorderservice_SharePointDocumentLocations: WebExpand<msdyn_workorderservice_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { msdyn_workorderservice_SharePointDocumentLocations: SharePointDocumentLocation_Result[] }>;
  msdyn_workorderservice_SharePointDocuments: WebExpand<msdyn_workorderservice_Expand, SharePointDocument_Select, SharePointDocument_Filter, { msdyn_workorderservice_SharePointDocuments: SharePointDocument_Result[] }>;
  msdyn_workorderservice_SocialActivities: WebExpand<msdyn_workorderservice_Expand, SocialActivity_Select, SocialActivity_Filter, { msdyn_workorderservice_SocialActivities: SocialActivity_Result[] }>;
  msdyn_workorderservice_SyncErrors: WebExpand<msdyn_workorderservice_Expand, SyncError_Select, SyncError_Filter, { msdyn_workorderservice_SyncErrors: SyncError_Result[] }>;
  msdyn_workorderservice_Tasks: WebExpand<msdyn_workorderservice_Expand, Task_Select, Task_Filter, { msdyn_workorderservice_Tasks: Task_Result[] }>;
  msdyn_workorderservice_UserEntityInstanceDatas: WebExpand<msdyn_workorderservice_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_workorderservice_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_workorderservice_connections1: WebExpand<msdyn_workorderservice_Expand, Connection_Select, Connection_Filter, { msdyn_workorderservice_connections1: Connection_Result[] }>;
  msdyn_workorderservice_connections2: WebExpand<msdyn_workorderservice_Expand, Connection_Select, Connection_Filter, { msdyn_workorderservice_connections2: Connection_Result[] }>;
  msdyn_workorderservice_msdyn_approvals: WebExpand<msdyn_workorderservice_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_workorderservice_msdyn_approvals: msdyn_approval_Result[] }>;
  msdyn_workorderservice_msdyn_bookingalerts: WebExpand<msdyn_workorderservice_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_workorderservice_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  msdyn_workorderservice_msdyn_ocliveworkitems: WebExpand<msdyn_workorderservice_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_workorderservice_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  msdyn_workorderservice_msdyn_ocoutboundmessages: WebExpand<msdyn_workorderservice_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_workorderservice_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_workorderservice_msdyn_ocsessions: WebExpand<msdyn_workorderservice_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_workorderservice_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  msdyn_workorderservice_msfp_alerts: WebExpand<msdyn_workorderservice_Expand, msfp_alert_Select, msfp_alert_Filter, { msdyn_workorderservice_msfp_alerts: msfp_alert_Result[] }>;
  msdyn_workorderservice_msfp_surveyinvites: WebExpand<msdyn_workorderservice_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msdyn_workorderservice_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  msdyn_workorderservice_msfp_surveyresponses: WebExpand<msdyn_workorderservice_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msdyn_workorderservice_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  ownerid: WebExpand<msdyn_workorderservice_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_workorderservice_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_workorderservice_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_workorderservice_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  transactioncurrencyid: WebExpand<msdyn_workorderservice_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface msdyn_workorderservice_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_additionalcost_base_formatted?: string;
  msdyn_additionalcost_formatted?: string;
  msdyn_agreementbookingservice_formatted?: string;
  msdyn_booking_formatted?: string;
  msdyn_calculatedunitamount_base_formatted?: string;
  msdyn_calculatedunitamount_formatted?: string;
  msdyn_commissioncosts_base_formatted?: string;
  msdyn_commissioncosts_formatted?: string;
  msdyn_customerasset_formatted?: string;
  msdyn_discountamount_base_formatted?: string;
  msdyn_discountamount_formatted?: string;
  msdyn_entitlement_formatted?: string;
  msdyn_estimatecalculatedunitamount_base_formatted?: string;
  msdyn_estimatecalculatedunitamount_formatted?: string;
  msdyn_estimatediscountamount_base_formatted?: string;
  msdyn_estimatediscountamount_formatted?: string;
  msdyn_estimatesubtotal_base_formatted?: string;
  msdyn_estimatesubtotal_formatted?: string;
  msdyn_estimatetotalamount_base_formatted?: string;
  msdyn_estimatetotalamount_formatted?: string;
  msdyn_estimatetotalcost_base_formatted?: string;
  msdyn_estimatetotalcost_formatted?: string;
  msdyn_estimateunitamount_base_formatted?: string;
  msdyn_estimateunitamount_formatted?: string;
  msdyn_estimateunitcost_base_formatted?: string;
  msdyn_estimateunitcost_formatted?: string;
  msdyn_linestatus_formatted?: string;
  msdyn_minimumchargeamount_base_formatted?: string;
  msdyn_minimumchargeamount_formatted?: string;
  msdyn_pricelist_formatted?: string;
  msdyn_service_formatted?: string;
  msdyn_subtotal_base_formatted?: string;
  msdyn_subtotal_formatted?: string;
  msdyn_totalamount_base_formatted?: string;
  msdyn_totalamount_formatted?: string;
  msdyn_totalcost_base_formatted?: string;
  msdyn_totalcost_formatted?: string;
  msdyn_unit_formatted?: string;
  msdyn_unitamount_base_formatted?: string;
  msdyn_unitamount_formatted?: string;
  msdyn_unitcost_base_formatted?: string;
  msdyn_unitcost_formatted?: string;
  msdyn_workorder_formatted?: string;
  msdyn_workorderincident_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface msdyn_workorderservice_Result extends msdyn_workorderservice_Base, msdyn_workorderservice_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_agreementbookingservice_guid: string | null;
  msdyn_booking_guid: string | null;
  msdyn_customerasset_guid: string | null;
  msdyn_entitlement_guid: string | null;
  msdyn_pricelist_guid: string | null;
  msdyn_service_guid: string | null;
  msdyn_unit_guid: string | null;
  msdyn_workorder_guid: string | null;
  msdyn_workorderincident_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface msdyn_workorderservice_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_agreementbookingservice: WebMappingRetrieve<msdyn_agreementbookingservice_Select,msdyn_agreementbookingservice_Expand,msdyn_agreementbookingservice_Filter,msdyn_agreementbookingservice_Fixed,msdyn_agreementbookingservice_Result,msdyn_agreementbookingservice_FormattedResult>;
  msdyn_booking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_entitlement: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  msdyn_pricelist: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  msdyn_service: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  msdyn_unit: WebMappingRetrieve<UoM_Select,UoM_Expand,UoM_Filter,UoM_Fixed,UoM_Result,UoM_FormattedResult>;
  msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  msdyn_workorderincident: WebMappingRetrieve<msdyn_workorderincident_Select,msdyn_workorderincident_Expand,msdyn_workorderincident_Filter,msdyn_workorderincident_Fixed,msdyn_workorderincident_Result,msdyn_workorderincident_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface msdyn_workorderservice_RelatedMany {
  msdyn_msdyn_workorderservice_invoicedetail: WebMappingRetrieve<InvoiceDetail_Select,InvoiceDetail_Expand,InvoiceDetail_Filter,InvoiceDetail_Fixed,InvoiceDetail_Result,InvoiceDetail_FormattedResult>;
  msdyn_workorderservice_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  msdyn_workorderservice_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_workorderservice_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_workorderservice_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_workorderservice_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_workorderservice_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_workorderservice_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_workorderservice_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_workorderservice_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  msdyn_workorderservice_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  msdyn_workorderservice_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_workorderservice_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  msdyn_workorderservice_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_workorderservice_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_workorderservice_QueueItems: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  msdyn_workorderservice_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  msdyn_workorderservice_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_workorderservice_SharePointDocumentLocations: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  msdyn_workorderservice_SharePointDocuments: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  msdyn_workorderservice_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  msdyn_workorderservice_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_workorderservice_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  msdyn_workorderservice_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_workorderservice_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorderservice_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorderservice_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_workorderservice_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_workorderservice_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_workorderservice_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_workorderservice_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msdyn_workorderservice_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msdyn_workorderservice_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msdyn_workorderservice_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_workorderservices: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_workorderservices: WebMappingRelated<msdyn_workorderservice_RelatedOne,msdyn_workorderservice_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_workorderservices: WebMappingCUDA<msdyn_workorderservice_Create,msdyn_workorderservice_Update,msdyn_workorderservice_Select>;
}
