interface msdyn_customerasset_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_alert?: boolean | null;
  msdyn_alertcount?: number | null;
  msdyn_alertcount_date?: Date | null;
  msdyn_alertcount_state?: number | null;
  msdyn_customerassetid?: string | null;
  msdyn_deviceid?: string | null;
  msdyn_lastalerttime?: Date | null;
  msdyn_lastalerttime_date?: Date | null;
  msdyn_lastalerttime_state?: number | null;
  msdyn_lastcommandsenttime?: Date | null;
  msdyn_latitude?: number | null;
  msdyn_longitude?: number | null;
  msdyn_name?: string | null;
  msdyn_registrationstatus?: msdyn_customerasset_msdyn_registrationstatus | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_customerasset_statecode | null;
  statuscode?: msdyn_customerasset_statuscode | null;
  timezoneruleversionnumber?: number | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_customerasset_Relationships {
  msdyn_CustomerAssetCategory?: msdyn_customerassetcategory_Result | null;
  msdyn_FunctionalLocation?: msdyn_FunctionalLocation_Result | null;
  msdyn_LastCommandSent?: msdyn_iotdevicecommand_Result | null;
  msdyn_customerasset_ActivityPointers?: ActivityPointer_Result[] | null;
  msdyn_customerasset_Annotations?: Annotation_Result[] | null;
  msdyn_customerasset_Appointments?: Appointment_Result[] | null;
  msdyn_customerasset_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_customerasset_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_customerasset_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_customerasset_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_customerasset_Emails?: Email_Result[] | null;
  msdyn_customerasset_Faxes?: Fax_Result[] | null;
  msdyn_customerasset_Letters?: Letter_Result[] | null;
  msdyn_customerasset_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_customerasset_OpportunityCloses?: OpportunityClose_Result[] | null;
  msdyn_customerasset_OrderCloses?: OrderClose_Result[] | null;
  msdyn_customerasset_PhoneCalls?: PhoneCall_Result[] | null;
  msdyn_customerasset_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_customerasset_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_customerasset_QuoteCloses?: QuoteClose_Result[] | null;
  msdyn_customerasset_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  msdyn_customerasset_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_customerasset_SocialActivities?: SocialActivity_Result[] | null;
  msdyn_customerasset_SyncErrors?: SyncError_Result[] | null;
  msdyn_customerasset_Tasks?: Task_Result[] | null;
  msdyn_customerasset_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_customerasset_connections1?: Connection_Result[] | null;
  msdyn_customerasset_connections2?: Connection_Result[] | null;
  msdyn_customerasset_msdyn_approvals?: msdyn_approval_Result[] | null;
  msdyn_customerasset_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  msdyn_customerasset_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_customerasset_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_customerasset_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  msdyn_customerasset_msfp_alerts?: msfp_alert_Result[] | null;
  msdyn_customerasset_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  msdyn_customerasset_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  msdyn_incident_msdyn_customerasset?: Incident_Result[] | null;
  msdyn_masterasset_msdyn_customerasset?: msdyn_customerasset_Result | null;
  msdyn_msdyn_customerasset_msdyn_3dmodel?: msdyn_3dmodel_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_agreementbookingincident_CustomerAsset?: msdyn_agreementbookingincident_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_agreementbookingproduct_CustomerAsset?: msdyn_agreementbookingproduct_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_agreementbookingservice_CustomerAsset?: msdyn_agreementbookingservice_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_agreementbookingservicetask_CustomerAsset?: msdyn_agreementbookingservicetask_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_assettemplateassociation_customerasset?: msdyn_assettemplateassociation_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_customerasset_MasterAsset?: msdyn_customerasset_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_customerasset_ParentAsset?: msdyn_customerasset_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_customerassetattachment_CustomerAsset?: msdyn_customerassetattachment_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_entitlementapplication_customerasset?: msdyn_entitlementapplication_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_inspectioninstance_customerassetid?: msdyn_inspectioninstance_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_iotalert_CustomerAsset?: msdyn_iotalert_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_iotdevicecommand_CustomerAsset?: msdyn_iotdevicecommand_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_problematicasset_asset?: msdyn_problematicasset_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_propertyassetassociation_customerasset?: msdyn_propertyassetassociation_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_propertylog_customerasset?: msdyn_propertylog_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_quotebookingincident_CustomerAsset?: msdyn_quotebookingincident_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_quotebookingproduct_CustomerAsset?: msdyn_quotebookingproduct_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_quotebookingservice_CustomerAsset?: msdyn_quotebookingservice_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_quotebookingservicetask_CustomerAsset?: msdyn_quotebookingservicetask_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_rmaproduct_CustomerAsset?: msdyn_rmaproduct_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_workorder_CustomerAsset?: msdyn_workorder_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_workorderincident_CustomerAsset?: msdyn_workorderincident_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_workorderproduct_CustomerAsset?: msdyn_workorderproduct_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_workorderresolution_CustomerAsset?: msdyn_workorderresolution_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_workorderservice_CustomerAsset?: msdyn_workorderservice_Result[] | null;
  msdyn_msdyn_customerasset_msdyn_workorderservicetask_CustomerAsset?: msdyn_workorderservicetask_Result[] | null;
  msdyn_parentasset_msdyn_customerasset?: msdyn_customerasset_Result | null;
  navigationPropertyNameNotDefined?: KnowledgeBaseRecord_Result[] | null;
  navigationPropertyNameNotDefined1?: KnowledgeArticle_Result[] | null;
}
interface msdyn_customerasset extends msdyn_customerasset_Base, msdyn_customerasset_Relationships {
  msdyn_CustomerAssetCategory_bind$msdyn_customerassetcategories?: string | null;
  msdyn_FunctionalLocation_bind$msdyn_functionallocations?: string | null;
  msdyn_LastCommandSent_bind$msdyn_iotdevicecommands?: string | null;
  msdyn_account_bind$accounts?: string | null;
  msdyn_masterasset_msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  msdyn_parentasset_msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  msdyn_product_bind$products?: string | null;
  msdyn_workorderproduct_bind$msdyn_workorderproducts?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface msdyn_customerasset_Create extends msdyn_customerasset {
}
interface msdyn_customerasset_Update extends msdyn_customerasset {
}
interface msdyn_customerasset_Select {
  createdby_guid: WebAttribute<msdyn_customerasset_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_customerasset_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_customerasset_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<msdyn_customerasset_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_customerasset_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_customerasset_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_customerasset_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_account_guid: WebAttribute<msdyn_customerasset_Select, { msdyn_account_guid: string | null }, { msdyn_account_formatted?: string }>;
  msdyn_alert: WebAttribute<msdyn_customerasset_Select, { msdyn_alert: boolean | null }, {  }>;
  msdyn_alertcount: WebAttribute<msdyn_customerasset_Select, { msdyn_alertcount: number | null }, {  }>;
  msdyn_alertcount_date: WebAttribute<msdyn_customerasset_Select, { msdyn_alertcount_date: Date | null }, { msdyn_alertcount_date_formatted?: string }>;
  msdyn_alertcount_state: WebAttribute<msdyn_customerasset_Select, { msdyn_alertcount_state: number | null }, {  }>;
  msdyn_customerassetcategory_guid: WebAttribute<msdyn_customerasset_Select, { msdyn_customerassetcategory_guid: string | null }, { msdyn_customerassetcategory_formatted?: string }>;
  msdyn_customerassetid: WebAttribute<msdyn_customerasset_Select, { msdyn_customerassetid: string | null }, {  }>;
  msdyn_deviceid: WebAttribute<msdyn_customerasset_Select, { msdyn_deviceid: string | null }, {  }>;
  msdyn_functionallocation_guid: WebAttribute<msdyn_customerasset_Select, { msdyn_functionallocation_guid: string | null }, { msdyn_functionallocation_formatted?: string }>;
  msdyn_lastalerttime: WebAttribute<msdyn_customerasset_Select, { msdyn_lastalerttime: Date | null }, { msdyn_lastalerttime_formatted?: string }>;
  msdyn_lastalerttime_date: WebAttribute<msdyn_customerasset_Select, { msdyn_lastalerttime_date: Date | null }, { msdyn_lastalerttime_date_formatted?: string }>;
  msdyn_lastalerttime_state: WebAttribute<msdyn_customerasset_Select, { msdyn_lastalerttime_state: number | null }, {  }>;
  msdyn_lastcommandsent_guid: WebAttribute<msdyn_customerasset_Select, { msdyn_lastcommandsent_guid: string | null }, { msdyn_lastcommandsent_formatted?: string }>;
  msdyn_lastcommandsenttime: WebAttribute<msdyn_customerasset_Select, { msdyn_lastcommandsenttime: Date | null }, { msdyn_lastcommandsenttime_formatted?: string }>;
  msdyn_latitude: WebAttribute<msdyn_customerasset_Select, { msdyn_latitude: number | null }, {  }>;
  msdyn_longitude: WebAttribute<msdyn_customerasset_Select, { msdyn_longitude: number | null }, {  }>;
  msdyn_masterasset_guid: WebAttribute<msdyn_customerasset_Select, { msdyn_masterasset_guid: string | null }, { msdyn_masterasset_formatted?: string }>;
  msdyn_name: WebAttribute<msdyn_customerasset_Select, { msdyn_name: string | null }, {  }>;
  msdyn_parentasset_guid: WebAttribute<msdyn_customerasset_Select, { msdyn_parentasset_guid: string | null }, { msdyn_parentasset_formatted?: string }>;
  msdyn_product_guid: WebAttribute<msdyn_customerasset_Select, { msdyn_product_guid: string | null }, { msdyn_product_formatted?: string }>;
  msdyn_registrationstatus: WebAttribute<msdyn_customerasset_Select, { msdyn_registrationstatus: msdyn_customerasset_msdyn_registrationstatus | null }, { msdyn_registrationstatus_formatted?: string }>;
  msdyn_workorderproduct_guid: WebAttribute<msdyn_customerasset_Select, { msdyn_workorderproduct_guid: string | null }, { msdyn_workorderproduct_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_customerasset_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_customerasset_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_customerasset_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_customerasset_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_customerasset_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_customerasset_Select, { statecode: msdyn_customerasset_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_customerasset_Select, { statuscode: msdyn_customerasset_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_customerasset_Select, { timezoneruleversionnumber: number | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_customerasset_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_customerasset_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_customerasset_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_account_guid: XQW.Guid;
  msdyn_alert: boolean;
  msdyn_alertcount: number;
  msdyn_alertcount_date: Date;
  msdyn_alertcount_state: number;
  msdyn_customerassetcategory_guid: XQW.Guid;
  msdyn_customerassetid: XQW.Guid;
  msdyn_deviceid: string;
  msdyn_functionallocation_guid: XQW.Guid;
  msdyn_lastalerttime: Date;
  msdyn_lastalerttime_date: Date;
  msdyn_lastalerttime_state: number;
  msdyn_lastcommandsent_guid: XQW.Guid;
  msdyn_lastcommandsenttime: Date;
  msdyn_latitude: number;
  msdyn_longitude: number;
  msdyn_masterasset_guid: XQW.Guid;
  msdyn_name: string;
  msdyn_parentasset_guid: XQW.Guid;
  msdyn_product_guid: XQW.Guid;
  msdyn_registrationstatus: msdyn_customerasset_msdyn_registrationstatus;
  msdyn_workorderproduct_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_customerasset_statecode;
  statuscode: msdyn_customerasset_statuscode;
  timezoneruleversionnumber: number;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_customerasset_Expand {
  createdby: WebExpand<msdyn_customerasset_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_customerasset_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_customerasset_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_customerasset_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_CustomerAssetCategory: WebExpand<msdyn_customerasset_Expand, msdyn_customerassetcategory_Select, msdyn_customerassetcategory_Filter, { msdyn_CustomerAssetCategory: msdyn_customerassetcategory_Result }>;
  msdyn_FunctionalLocation: WebExpand<msdyn_customerasset_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { msdyn_FunctionalLocation: msdyn_FunctionalLocation_Result }>;
  msdyn_LastCommandSent: WebExpand<msdyn_customerasset_Expand, msdyn_iotdevicecommand_Select, msdyn_iotdevicecommand_Filter, { msdyn_LastCommandSent: msdyn_iotdevicecommand_Result }>;
  msdyn_account: WebExpand<msdyn_customerasset_Expand, Account_Select, Account_Filter, { msdyn_account: Account_Result }>;
  msdyn_customerasset_ActivityPointers: WebExpand<msdyn_customerasset_Expand, ActivityPointer_Select, ActivityPointer_Filter, { msdyn_customerasset_ActivityPointers: ActivityPointer_Result[] }>;
  msdyn_customerasset_Annotations: WebExpand<msdyn_customerasset_Expand, Annotation_Select, Annotation_Filter, { msdyn_customerasset_Annotations: Annotation_Result[] }>;
  msdyn_customerasset_Appointments: WebExpand<msdyn_customerasset_Expand, Appointment_Select, Appointment_Filter, { msdyn_customerasset_Appointments: Appointment_Result[] }>;
  msdyn_customerasset_AsyncOperations: WebExpand<msdyn_customerasset_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_customerasset_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_customerasset_BulkDeleteFailures: WebExpand<msdyn_customerasset_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_customerasset_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_customerasset_DuplicateBaseRecord: WebExpand<msdyn_customerasset_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_customerasset_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_customerasset_DuplicateMatchingRecord: WebExpand<msdyn_customerasset_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_customerasset_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_customerasset_Emails: WebExpand<msdyn_customerasset_Expand, Email_Select, Email_Filter, { msdyn_customerasset_Emails: Email_Result[] }>;
  msdyn_customerasset_Faxes: WebExpand<msdyn_customerasset_Expand, Fax_Select, Fax_Filter, { msdyn_customerasset_Faxes: Fax_Result[] }>;
  msdyn_customerasset_Letters: WebExpand<msdyn_customerasset_Expand, Letter_Select, Letter_Filter, { msdyn_customerasset_Letters: Letter_Result[] }>;
  msdyn_customerasset_MailboxTrackingFolders: WebExpand<msdyn_customerasset_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_customerasset_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_customerasset_OpportunityCloses: WebExpand<msdyn_customerasset_Expand, OpportunityClose_Select, OpportunityClose_Filter, { msdyn_customerasset_OpportunityCloses: OpportunityClose_Result[] }>;
  msdyn_customerasset_OrderCloses: WebExpand<msdyn_customerasset_Expand, OrderClose_Select, OrderClose_Filter, { msdyn_customerasset_OrderCloses: OrderClose_Result[] }>;
  msdyn_customerasset_PhoneCalls: WebExpand<msdyn_customerasset_Expand, PhoneCall_Select, PhoneCall_Filter, { msdyn_customerasset_PhoneCalls: PhoneCall_Result[] }>;
  msdyn_customerasset_PrincipalObjectAttributeAccesses: WebExpand<msdyn_customerasset_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_customerasset_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_customerasset_ProcessSession: WebExpand<msdyn_customerasset_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_customerasset_ProcessSession: ProcessSession_Result[] }>;
  msdyn_customerasset_QuoteCloses: WebExpand<msdyn_customerasset_Expand, QuoteClose_Select, QuoteClose_Filter, { msdyn_customerasset_QuoteCloses: QuoteClose_Result[] }>;
  msdyn_customerasset_RecurringAppointmentMasters: WebExpand<msdyn_customerasset_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { msdyn_customerasset_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  msdyn_customerasset_ServiceAppointments: WebExpand<msdyn_customerasset_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_customerasset_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_customerasset_SocialActivities: WebExpand<msdyn_customerasset_Expand, SocialActivity_Select, SocialActivity_Filter, { msdyn_customerasset_SocialActivities: SocialActivity_Result[] }>;
  msdyn_customerasset_SyncErrors: WebExpand<msdyn_customerasset_Expand, SyncError_Select, SyncError_Filter, { msdyn_customerasset_SyncErrors: SyncError_Result[] }>;
  msdyn_customerasset_Tasks: WebExpand<msdyn_customerasset_Expand, Task_Select, Task_Filter, { msdyn_customerasset_Tasks: Task_Result[] }>;
  msdyn_customerasset_UserEntityInstanceDatas: WebExpand<msdyn_customerasset_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_customerasset_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_customerasset_connections1: WebExpand<msdyn_customerasset_Expand, Connection_Select, Connection_Filter, { msdyn_customerasset_connections1: Connection_Result[] }>;
  msdyn_customerasset_connections2: WebExpand<msdyn_customerasset_Expand, Connection_Select, Connection_Filter, { msdyn_customerasset_connections2: Connection_Result[] }>;
  msdyn_customerasset_msdyn_approvals: WebExpand<msdyn_customerasset_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_customerasset_msdyn_approvals: msdyn_approval_Result[] }>;
  msdyn_customerasset_msdyn_bookingalerts: WebExpand<msdyn_customerasset_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_customerasset_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  msdyn_customerasset_msdyn_ocliveworkitems: WebExpand<msdyn_customerasset_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_customerasset_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  msdyn_customerasset_msdyn_ocoutboundmessages: WebExpand<msdyn_customerasset_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_customerasset_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_customerasset_msdyn_ocsessions: WebExpand<msdyn_customerasset_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_customerasset_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  msdyn_customerasset_msfp_alerts: WebExpand<msdyn_customerasset_Expand, msfp_alert_Select, msfp_alert_Filter, { msdyn_customerasset_msfp_alerts: msfp_alert_Result[] }>;
  msdyn_customerasset_msfp_surveyinvites: WebExpand<msdyn_customerasset_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msdyn_customerasset_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  msdyn_customerasset_msfp_surveyresponses: WebExpand<msdyn_customerasset_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msdyn_customerasset_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  msdyn_incident_msdyn_customerasset: WebExpand<msdyn_customerasset_Expand, Incident_Select, Incident_Filter, { msdyn_incident_msdyn_customerasset: Incident_Result[] }>;
  msdyn_masterasset_msdyn_customerasset: WebExpand<msdyn_customerasset_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_masterasset_msdyn_customerasset: msdyn_customerasset_Result }>;
  msdyn_msdyn_customerasset_msdyn_3dmodel: WebExpand<msdyn_customerasset_Expand, msdyn_3dmodel_Select, msdyn_3dmodel_Filter, { msdyn_msdyn_customerasset_msdyn_3dmodel: msdyn_3dmodel_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_agreementbookingincident_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_agreementbookingincident_Select, msdyn_agreementbookingincident_Filter, { msdyn_msdyn_customerasset_msdyn_agreementbookingincident_CustomerAsset: msdyn_agreementbookingincident_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_agreementbookingproduct_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_agreementbookingproduct_Select, msdyn_agreementbookingproduct_Filter, { msdyn_msdyn_customerasset_msdyn_agreementbookingproduct_CustomerAsset: msdyn_agreementbookingproduct_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_agreementbookingservice_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_agreementbookingservice_Select, msdyn_agreementbookingservice_Filter, { msdyn_msdyn_customerasset_msdyn_agreementbookingservice_CustomerAsset: msdyn_agreementbookingservice_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_agreementbookingservicetask_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_agreementbookingservicetask_Select, msdyn_agreementbookingservicetask_Filter, { msdyn_msdyn_customerasset_msdyn_agreementbookingservicetask_CustomerAsset: msdyn_agreementbookingservicetask_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_assettemplateassociation_customerasset: WebExpand<msdyn_customerasset_Expand, msdyn_assettemplateassociation_Select, msdyn_assettemplateassociation_Filter, { msdyn_msdyn_customerasset_msdyn_assettemplateassociation_customerasset: msdyn_assettemplateassociation_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_customerasset_MasterAsset: WebExpand<msdyn_customerasset_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_msdyn_customerasset_msdyn_customerasset_MasterAsset: msdyn_customerasset_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_customerasset_ParentAsset: WebExpand<msdyn_customerasset_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_msdyn_customerasset_msdyn_customerasset_ParentAsset: msdyn_customerasset_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_customerassetattachment_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_customerassetattachment_Select, msdyn_customerassetattachment_Filter, { msdyn_msdyn_customerasset_msdyn_customerassetattachment_CustomerAsset: msdyn_customerassetattachment_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_entitlementapplication_customerasset: WebExpand<msdyn_customerasset_Expand, msdyn_entitlementapplication_Select, msdyn_entitlementapplication_Filter, { msdyn_msdyn_customerasset_msdyn_entitlementapplication_customerasset: msdyn_entitlementapplication_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_inspectioninstance_customerassetid: WebExpand<msdyn_customerasset_Expand, msdyn_inspectioninstance_Select, msdyn_inspectioninstance_Filter, { msdyn_msdyn_customerasset_msdyn_inspectioninstance_customerassetid: msdyn_inspectioninstance_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_iotalert_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_iotalert_Select, msdyn_iotalert_Filter, { msdyn_msdyn_customerasset_msdyn_iotalert_CustomerAsset: msdyn_iotalert_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_iotdevicecommand_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_iotdevicecommand_Select, msdyn_iotdevicecommand_Filter, { msdyn_msdyn_customerasset_msdyn_iotdevicecommand_CustomerAsset: msdyn_iotdevicecommand_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_problematicasset_asset: WebExpand<msdyn_customerasset_Expand, msdyn_problematicasset_Select, msdyn_problematicasset_Filter, { msdyn_msdyn_customerasset_msdyn_problematicasset_asset: msdyn_problematicasset_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_propertyassetassociation_customerasset: WebExpand<msdyn_customerasset_Expand, msdyn_propertyassetassociation_Select, msdyn_propertyassetassociation_Filter, { msdyn_msdyn_customerasset_msdyn_propertyassetassociation_customerasset: msdyn_propertyassetassociation_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_propertylog_customerasset: WebExpand<msdyn_customerasset_Expand, msdyn_propertylog_Select, msdyn_propertylog_Filter, { msdyn_msdyn_customerasset_msdyn_propertylog_customerasset: msdyn_propertylog_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_quotebookingincident_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_quotebookingincident_Select, msdyn_quotebookingincident_Filter, { msdyn_msdyn_customerasset_msdyn_quotebookingincident_CustomerAsset: msdyn_quotebookingincident_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_quotebookingproduct_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_quotebookingproduct_Select, msdyn_quotebookingproduct_Filter, { msdyn_msdyn_customerasset_msdyn_quotebookingproduct_CustomerAsset: msdyn_quotebookingproduct_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_quotebookingservice_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_quotebookingservice_Select, msdyn_quotebookingservice_Filter, { msdyn_msdyn_customerasset_msdyn_quotebookingservice_CustomerAsset: msdyn_quotebookingservice_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_quotebookingservicetask_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_quotebookingservicetask_Select, msdyn_quotebookingservicetask_Filter, { msdyn_msdyn_customerasset_msdyn_quotebookingservicetask_CustomerAsset: msdyn_quotebookingservicetask_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_rmaproduct_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_rmaproduct_Select, msdyn_rmaproduct_Filter, { msdyn_msdyn_customerasset_msdyn_rmaproduct_CustomerAsset: msdyn_rmaproduct_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_workorder_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_msdyn_customerasset_msdyn_workorder_CustomerAsset: msdyn_workorder_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_workorderincident_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_workorderincident_Select, msdyn_workorderincident_Filter, { msdyn_msdyn_customerasset_msdyn_workorderincident_CustomerAsset: msdyn_workorderincident_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_workorderproduct_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { msdyn_msdyn_customerasset_msdyn_workorderproduct_CustomerAsset: msdyn_workorderproduct_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_workorderresolution_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_workorderresolution_Select, msdyn_workorderresolution_Filter, { msdyn_msdyn_customerasset_msdyn_workorderresolution_CustomerAsset: msdyn_workorderresolution_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_workorderservice_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { msdyn_msdyn_customerasset_msdyn_workorderservice_CustomerAsset: msdyn_workorderservice_Result[] }>;
  msdyn_msdyn_customerasset_msdyn_workorderservicetask_CustomerAsset: WebExpand<msdyn_customerasset_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { msdyn_msdyn_customerasset_msdyn_workorderservicetask_CustomerAsset: msdyn_workorderservicetask_Result[] }>;
  msdyn_parentasset_msdyn_customerasset: WebExpand<msdyn_customerasset_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_parentasset_msdyn_customerasset: msdyn_customerasset_Result }>;
  msdyn_product: WebExpand<msdyn_customerasset_Expand, Product_Select, Product_Filter, { msdyn_product: Product_Result }>;
  msdyn_workorderproduct: WebExpand<msdyn_customerasset_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { msdyn_workorderproduct: msdyn_workorderproduct_Result }>;
  navigationPropertyNameNotDefined: WebExpand<msdyn_customerasset_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { navigationPropertyNameNotDefined: KnowledgeBaseRecord_Result[] }>;
  navigationPropertyNameNotDefined1: WebExpand<msdyn_customerasset_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { navigationPropertyNameNotDefined: KnowledgeArticle_Result[] }>;
  ownerid: WebExpand<msdyn_customerasset_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_customerasset_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_customerasset_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_customerasset_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
}
interface msdyn_customerasset_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_account_formatted?: string;
  msdyn_alertcount_date_formatted?: string;
  msdyn_customerassetcategory_formatted?: string;
  msdyn_functionallocation_formatted?: string;
  msdyn_lastalerttime_date_formatted?: string;
  msdyn_lastalerttime_formatted?: string;
  msdyn_lastcommandsent_formatted?: string;
  msdyn_lastcommandsenttime_formatted?: string;
  msdyn_masterasset_formatted?: string;
  msdyn_parentasset_formatted?: string;
  msdyn_product_formatted?: string;
  msdyn_registrationstatus_formatted?: string;
  msdyn_workorderproduct_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface msdyn_customerasset_Result extends msdyn_customerasset_Base, msdyn_customerasset_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_account_guid: string | null;
  msdyn_customerassetcategory_guid: string | null;
  msdyn_functionallocation_guid: string | null;
  msdyn_lastcommandsent_guid: string | null;
  msdyn_masterasset_guid: string | null;
  msdyn_parentasset_guid: string | null;
  msdyn_product_guid: string | null;
  msdyn_workorderproduct_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface msdyn_customerasset_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_CustomerAssetCategory: WebMappingRetrieve<msdyn_customerassetcategory_Select,msdyn_customerassetcategory_Expand,msdyn_customerassetcategory_Filter,msdyn_customerassetcategory_Fixed,msdyn_customerassetcategory_Result,msdyn_customerassetcategory_FormattedResult>;
  msdyn_FunctionalLocation: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  msdyn_LastCommandSent: WebMappingRetrieve<msdyn_iotdevicecommand_Select,msdyn_iotdevicecommand_Expand,msdyn_iotdevicecommand_Filter,msdyn_iotdevicecommand_Fixed,msdyn_iotdevicecommand_Result,msdyn_iotdevicecommand_FormattedResult>;
  msdyn_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_masterasset_msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_parentasset_msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_product: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  msdyn_workorderproduct: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface msdyn_customerasset_RelatedMany {
  msdyn_customerasset_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  msdyn_customerasset_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_customerasset_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_customerasset_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_customerasset_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_customerasset_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_customerasset_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_customerasset_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_customerasset_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  msdyn_customerasset_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  msdyn_customerasset_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_customerasset_OpportunityCloses: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  msdyn_customerasset_OrderCloses: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  msdyn_customerasset_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  msdyn_customerasset_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_customerasset_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_customerasset_QuoteCloses: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  msdyn_customerasset_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  msdyn_customerasset_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_customerasset_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  msdyn_customerasset_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_customerasset_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  msdyn_customerasset_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_customerasset_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_customerasset_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_customerasset_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_customerasset_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_customerasset_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_customerasset_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_customerasset_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msdyn_customerasset_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msdyn_customerasset_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msdyn_customerasset_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  msdyn_incident_msdyn_customerasset: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_3dmodel: WebMappingRetrieve<msdyn_3dmodel_Select,msdyn_3dmodel_Expand,msdyn_3dmodel_Filter,msdyn_3dmodel_Fixed,msdyn_3dmodel_Result,msdyn_3dmodel_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_agreementbookingincident_CustomerAsset: WebMappingRetrieve<msdyn_agreementbookingincident_Select,msdyn_agreementbookingincident_Expand,msdyn_agreementbookingincident_Filter,msdyn_agreementbookingincident_Fixed,msdyn_agreementbookingincident_Result,msdyn_agreementbookingincident_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_agreementbookingproduct_CustomerAsset: WebMappingRetrieve<msdyn_agreementbookingproduct_Select,msdyn_agreementbookingproduct_Expand,msdyn_agreementbookingproduct_Filter,msdyn_agreementbookingproduct_Fixed,msdyn_agreementbookingproduct_Result,msdyn_agreementbookingproduct_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_agreementbookingservice_CustomerAsset: WebMappingRetrieve<msdyn_agreementbookingservice_Select,msdyn_agreementbookingservice_Expand,msdyn_agreementbookingservice_Filter,msdyn_agreementbookingservice_Fixed,msdyn_agreementbookingservice_Result,msdyn_agreementbookingservice_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_agreementbookingservicetask_CustomerAsset: WebMappingRetrieve<msdyn_agreementbookingservicetask_Select,msdyn_agreementbookingservicetask_Expand,msdyn_agreementbookingservicetask_Filter,msdyn_agreementbookingservicetask_Fixed,msdyn_agreementbookingservicetask_Result,msdyn_agreementbookingservicetask_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_assettemplateassociation_customerasset: WebMappingRetrieve<msdyn_assettemplateassociation_Select,msdyn_assettemplateassociation_Expand,msdyn_assettemplateassociation_Filter,msdyn_assettemplateassociation_Fixed,msdyn_assettemplateassociation_Result,msdyn_assettemplateassociation_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_customerasset_MasterAsset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_customerasset_ParentAsset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_customerassetattachment_CustomerAsset: WebMappingRetrieve<msdyn_customerassetattachment_Select,msdyn_customerassetattachment_Expand,msdyn_customerassetattachment_Filter,msdyn_customerassetattachment_Fixed,msdyn_customerassetattachment_Result,msdyn_customerassetattachment_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_entitlementapplication_customerasset: WebMappingRetrieve<msdyn_entitlementapplication_Select,msdyn_entitlementapplication_Expand,msdyn_entitlementapplication_Filter,msdyn_entitlementapplication_Fixed,msdyn_entitlementapplication_Result,msdyn_entitlementapplication_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_inspectioninstance_customerassetid: WebMappingRetrieve<msdyn_inspectioninstance_Select,msdyn_inspectioninstance_Expand,msdyn_inspectioninstance_Filter,msdyn_inspectioninstance_Fixed,msdyn_inspectioninstance_Result,msdyn_inspectioninstance_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_iotalert_CustomerAsset: WebMappingRetrieve<msdyn_iotalert_Select,msdyn_iotalert_Expand,msdyn_iotalert_Filter,msdyn_iotalert_Fixed,msdyn_iotalert_Result,msdyn_iotalert_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_iotdevicecommand_CustomerAsset: WebMappingRetrieve<msdyn_iotdevicecommand_Select,msdyn_iotdevicecommand_Expand,msdyn_iotdevicecommand_Filter,msdyn_iotdevicecommand_Fixed,msdyn_iotdevicecommand_Result,msdyn_iotdevicecommand_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_problematicasset_asset: WebMappingRetrieve<msdyn_problematicasset_Select,msdyn_problematicasset_Expand,msdyn_problematicasset_Filter,msdyn_problematicasset_Fixed,msdyn_problematicasset_Result,msdyn_problematicasset_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_propertyassetassociation_customerasset: WebMappingRetrieve<msdyn_propertyassetassociation_Select,msdyn_propertyassetassociation_Expand,msdyn_propertyassetassociation_Filter,msdyn_propertyassetassociation_Fixed,msdyn_propertyassetassociation_Result,msdyn_propertyassetassociation_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_propertylog_customerasset: WebMappingRetrieve<msdyn_propertylog_Select,msdyn_propertylog_Expand,msdyn_propertylog_Filter,msdyn_propertylog_Fixed,msdyn_propertylog_Result,msdyn_propertylog_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_quotebookingincident_CustomerAsset: WebMappingRetrieve<msdyn_quotebookingincident_Select,msdyn_quotebookingincident_Expand,msdyn_quotebookingincident_Filter,msdyn_quotebookingincident_Fixed,msdyn_quotebookingincident_Result,msdyn_quotebookingincident_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_quotebookingproduct_CustomerAsset: WebMappingRetrieve<msdyn_quotebookingproduct_Select,msdyn_quotebookingproduct_Expand,msdyn_quotebookingproduct_Filter,msdyn_quotebookingproduct_Fixed,msdyn_quotebookingproduct_Result,msdyn_quotebookingproduct_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_quotebookingservice_CustomerAsset: WebMappingRetrieve<msdyn_quotebookingservice_Select,msdyn_quotebookingservice_Expand,msdyn_quotebookingservice_Filter,msdyn_quotebookingservice_Fixed,msdyn_quotebookingservice_Result,msdyn_quotebookingservice_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_quotebookingservicetask_CustomerAsset: WebMappingRetrieve<msdyn_quotebookingservicetask_Select,msdyn_quotebookingservicetask_Expand,msdyn_quotebookingservicetask_Filter,msdyn_quotebookingservicetask_Fixed,msdyn_quotebookingservicetask_Result,msdyn_quotebookingservicetask_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_rmaproduct_CustomerAsset: WebMappingRetrieve<msdyn_rmaproduct_Select,msdyn_rmaproduct_Expand,msdyn_rmaproduct_Filter,msdyn_rmaproduct_Fixed,msdyn_rmaproduct_Result,msdyn_rmaproduct_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_workorder_CustomerAsset: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_workorderincident_CustomerAsset: WebMappingRetrieve<msdyn_workorderincident_Select,msdyn_workorderincident_Expand,msdyn_workorderincident_Filter,msdyn_workorderincident_Fixed,msdyn_workorderincident_Result,msdyn_workorderincident_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_workorderproduct_CustomerAsset: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_workorderresolution_CustomerAsset: WebMappingRetrieve<msdyn_workorderresolution_Select,msdyn_workorderresolution_Expand,msdyn_workorderresolution_Filter,msdyn_workorderresolution_Fixed,msdyn_workorderresolution_Result,msdyn_workorderresolution_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_workorderservice_CustomerAsset: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  msdyn_msdyn_customerasset_msdyn_workorderservicetask_CustomerAsset: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  navigationPropertyNameNotDefined: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  navigationPropertyNameNotDefined1: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_customerassets: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_customerassets: WebMappingRelated<msdyn_customerasset_RelatedOne,msdyn_customerasset_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_customerassets: WebMappingCUDA<msdyn_customerasset_Create,msdyn_customerasset_Update,msdyn_customerasset_Select>;
}
