interface msdyn_project_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_actualdurationminutes?: number | null;
  msdyn_actualend?: Date | null;
  msdyn_actualexpensecost?: number | null;
  msdyn_actualexpensecost_base?: number | null;
  msdyn_actualexpensesales?: number | null;
  msdyn_actualexpensesales_base?: number | null;
  msdyn_actualhours?: number | null;
  msdyn_actuallaborcost?: number | null;
  msdyn_actuallaborcost_base?: number | null;
  msdyn_actualsales?: number | null;
  msdyn_actualsales_base?: number | null;
  msdyn_actualstart?: Date | null;
  msdyn_bulkgenerationstatus?: msdyn_asyncoperationstatus | null;
  msdyn_calendarid?: string | null;
  msdyn_comments?: string | null;
  msdyn_costconsumption?: number | null;
  msdyn_costestimateatcomplete?: number | null;
  msdyn_costestimateatcomplete_base?: number | null;
  msdyn_costperformence?: msdyn_project_msdyn_costperformence | null;
  msdyn_costvariance?: number | null;
  msdyn_costvariance_base?: number | null;
  msdyn_description?: string | null;
  msdyn_disablecreateofteammemberformanager?: boolean | null;
  msdyn_effortestimateatcompleteeac?: number | null;
  msdyn_exchangerate?: number | null;
  msdyn_islinkedtomsprojectclient?: boolean | null;
  msdyn_istemplate?: boolean | null;
  msdyn_linkeddocumenturl?: string | null;
  msdyn_overallprojectstatus?: msdyn_project_msdyn_overallprojectstatus | null;
  msdyn_plannedexpensecost?: number | null;
  msdyn_plannedexpensecost_base?: number | null;
  msdyn_plannedexpensesales?: number | null;
  msdyn_plannedexpensesales_base?: number | null;
  msdyn_plannedhours?: number | null;
  msdyn_plannedlaborcost?: number | null;
  msdyn_plannedlaborcost_base?: number | null;
  msdyn_plannedsales?: number | null;
  msdyn_plannedsales_base?: number | null;
  msdyn_progress?: number | null;
  msdyn_projectid?: string | null;
  msdyn_projectresourcerequirementsvisibletore?: boolean | null;
  msdyn_remainingcost?: number | null;
  msdyn_remainingcost_base?: number | null;
  msdyn_remaininghours?: number | null;
  msdyn_remainingsales?: number | null;
  msdyn_remainingsales_base?: number | null;
  msdyn_salesconsumption?: number | null;
  msdyn_salesestimateatcompleteeac?: number | null;
  msdyn_salesestimateatcompleteeac_base?: number | null;
  msdyn_salesvariance?: number | null;
  msdyn_salesvariance_base?: number | null;
  msdyn_scheduleddurationminutes?: number | null;
  msdyn_scheduledend?: Date | null;
  msdyn_scheduledstart?: Date | null;
  msdyn_scheduleperformance?: msdyn_project_msdyn_scheduleperformance | null;
  msdyn_schedulevariance?: number | null;
  msdyn_stagename?: string | null;
  msdyn_statusupdatedon?: Date | null;
  msdyn_subject?: string | null;
  msdyn_teamsize?: number | null;
  msdyn_teamsize_date?: Date | null;
  msdyn_teamsize_state?: number | null;
  msdyn_totalactualcost?: number | null;
  msdyn_totalactualcost_base?: number | null;
  msdyn_totalactualsales?: number | null;
  msdyn_totalactualsales_base?: number | null;
  msdyn_totalplannedcost?: number | null;
  msdyn_totalplannedcost_base?: number | null;
  msdyn_totalplannedsales?: number | null;
  msdyn_totalplannedsales_base?: number | null;
  msdyn_wbsduration?: number | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  stageid?: string | null;
  statecode?: msdyn_project_statecode | null;
  statuscode?: msdyn_project_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_project_Relationships {
  bpf_msdyn_project_msdyn_bpf_665e73aa18c247d886bfc50499c73b82?: msdyn_bpf_665e73aa18c247d886bfc50499c73b82_Result[] | null;
  msdyn_ContractOrganizationalUnitId?: msdyn_organizationalunit_Result | null;
  msdyn_ProjectTemplate?: msdyn_project_Result | null;
  msdyn_msdyn_project_bookableresourcebooking_projectid?: BookableResourceBooking_Result[] | null;
  msdyn_msdyn_project_bookableresourcebookingheader_projectid?: BookableResourceBookingHeader_Result[] | null;
  msdyn_msdyn_project_invoicedetail_Project?: InvoiceDetail_Result[] | null;
  msdyn_msdyn_project_msdyn_actual_Project?: msdyn_actual_Result[] | null;
  msdyn_msdyn_project_msdyn_approvalset_Project?: msdyn_approvalset_Result[] | null;
  msdyn_msdyn_project_msdyn_contractlinescheduleofvalue_project?: msdyn_contractlinescheduleofvalue_Result[] | null;
  msdyn_msdyn_project_msdyn_estimate_Project?: msdyn_estimate_Result[] | null;
  msdyn_msdyn_project_msdyn_estimateline_Project?: msdyn_estimateline_Result[] | null;
  msdyn_msdyn_project_msdyn_expense_Project?: msdyn_expense_Result[] | null;
  msdyn_msdyn_project_msdyn_fact_Project?: msdyn_fact_Result[] | null;
  msdyn_msdyn_project_msdyn_invoicelinetransaction_Project?: msdyn_invoicelinetransaction_Result[] | null;
  msdyn_msdyn_project_msdyn_journal_DefaultProject?: msdyn_journal_Result[] | null;
  msdyn_msdyn_project_msdyn_journal_Project?: msdyn_journal_Result[] | null;
  msdyn_msdyn_project_msdyn_journalline_Project?: msdyn_journalline_Result[] | null;
  msdyn_msdyn_project_msdyn_opportunitylinetransaction_Project?: msdyn_opportunitylinetransaction_Result[] | null;
  msdyn_msdyn_project_msdyn_orderlinetransaction_Project?: msdyn_orderlinetransaction_Result[] | null;
  msdyn_msdyn_project_msdyn_project_ProjectTemplate?: msdyn_project_Result[] | null;
  msdyn_msdyn_project_msdyn_projectapproval_Project?: msdyn_projectapproval_Result[] | null;
  msdyn_msdyn_project_msdyn_projectpricelist_Project?: msdyn_projectpricelist_Result[] | null;
  msdyn_msdyn_project_msdyn_projecttask_project?: msdyn_projecttask_Result[] | null;
  msdyn_msdyn_project_msdyn_projecttaskdependency_Project?: msdyn_projecttaskdependency_Result[] | null;
  msdyn_msdyn_project_msdyn_projectteam_project?: msdyn_projectteam_Result[] | null;
  msdyn_msdyn_project_msdyn_projecttransactioncategory_Project?: msdyn_projecttransactioncategory_Result[] | null;
  msdyn_msdyn_project_msdyn_quotelinetransaction_Project?: msdyn_quotelinetransaction_Result[] | null;
  msdyn_msdyn_project_msdyn_resourceassignment_projectid?: msdyn_resourceassignment_Result[] | null;
  msdyn_msdyn_project_msdyn_timeentry_project?: msdyn_timeentry_Result[] | null;
  msdyn_msdyn_project_opportunityproduct_Project?: OpportunityProduct_Result[] | null;
  msdyn_msdyn_project_quotedetail_Project?: QuoteDetail_Result[] | null;
  msdyn_msdyn_project_salesorderdetail_Project?: SalesOrderDetail_Result[] | null;
  msdyn_project_Annotations?: Annotation_Result[] | null;
  msdyn_project_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_project_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_project_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_project_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_project_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_project_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_project_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_project_QueueItems?: QueueItem_Result[] | null;
  msdyn_project_SharePointDocumentLocations?: SharePointDocumentLocation_Result[] | null;
  msdyn_project_SharePointDocuments?: SharePointDocument_Result[] | null;
  msdyn_project_SyncErrors?: SyncError_Result[] | null;
  msdyn_project_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_project_connections1?: Connection_Result[] | null;
  msdyn_project_connections2?: Connection_Result[] | null;
  msdyn_project_resourcerequirement?: msdyn_resourcerequirement_Result[] | null;
}
interface msdyn_project extends msdyn_project_Base, msdyn_project_Relationships {
  msdyn_ContractOrganizationalUnitId_bind$msdyn_organizationalunits?: string | null;
  msdyn_ProjectTemplate_bind$msdyn_projects?: string | null;
  msdyn_customer_bind$accounts?: string | null;
  msdyn_projectmanager_bind$systemusers?: string | null;
  msdyn_projectteamid_bind$teams?: string | null;
  msdyn_salesorderid_bind$salesorders?: string | null;
  msdyn_workhourtemplate_bind$msdyn_workhourtemplates?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  stageid_bind$processstages?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface msdyn_project_Create extends msdyn_project {
}
interface msdyn_project_Update extends msdyn_project {
}
interface msdyn_project_Select {
  createdby_guid: WebAttribute<msdyn_project_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_project_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_project_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_project_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_project_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_project_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_project_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_project_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_actualdurationminutes: WebAttribute<msdyn_project_Select, { msdyn_actualdurationminutes: number | null }, {  }>;
  msdyn_actualend: WebAttribute<msdyn_project_Select, { msdyn_actualend: Date | null }, { msdyn_actualend_formatted?: string }>;
  msdyn_actualexpensecost: WebAttribute<msdyn_project_Select, { msdyn_actualexpensecost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_actualexpensecost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_actualexpensecost_base: WebAttribute<msdyn_project_Select, { msdyn_actualexpensecost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_actualexpensecost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_actualexpensesales: WebAttribute<msdyn_project_Select, { msdyn_actualexpensesales: number | null; transactioncurrencyid_guid: string | null }, { msdyn_actualexpensesales_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_actualexpensesales_base: WebAttribute<msdyn_project_Select, { msdyn_actualexpensesales_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_actualexpensesales_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_actualhours: WebAttribute<msdyn_project_Select, { msdyn_actualhours: number | null }, {  }>;
  msdyn_actuallaborcost: WebAttribute<msdyn_project_Select, { msdyn_actuallaborcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_actuallaborcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_actuallaborcost_base: WebAttribute<msdyn_project_Select, { msdyn_actuallaborcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_actuallaborcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_actualsales: WebAttribute<msdyn_project_Select, { msdyn_actualsales: number | null; transactioncurrencyid_guid: string | null }, { msdyn_actualsales_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_actualsales_base: WebAttribute<msdyn_project_Select, { msdyn_actualsales_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_actualsales_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_actualstart: WebAttribute<msdyn_project_Select, { msdyn_actualstart: Date | null }, { msdyn_actualstart_formatted?: string }>;
  msdyn_bulkgenerationstatus: WebAttribute<msdyn_project_Select, { msdyn_bulkgenerationstatus: msdyn_asyncoperationstatus | null }, { msdyn_bulkgenerationstatus_formatted?: string }>;
  msdyn_calendarid: WebAttribute<msdyn_project_Select, { msdyn_calendarid: string | null }, {  }>;
  msdyn_comments: WebAttribute<msdyn_project_Select, { msdyn_comments: string | null }, {  }>;
  msdyn_contractorganizationalunitid_guid: WebAttribute<msdyn_project_Select, { msdyn_contractorganizationalunitid_guid: string | null }, { msdyn_contractorganizationalunitid_formatted?: string }>;
  msdyn_costconsumption: WebAttribute<msdyn_project_Select, { msdyn_costconsumption: number | null }, {  }>;
  msdyn_costestimateatcomplete: WebAttribute<msdyn_project_Select, { msdyn_costestimateatcomplete: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costestimateatcomplete_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costestimateatcomplete_base: WebAttribute<msdyn_project_Select, { msdyn_costestimateatcomplete_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costestimateatcomplete_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costperformence: WebAttribute<msdyn_project_Select, { msdyn_costperformence: msdyn_project_msdyn_costperformence | null }, { msdyn_costperformence_formatted?: string }>;
  msdyn_costvariance: WebAttribute<msdyn_project_Select, { msdyn_costvariance: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costvariance_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costvariance_base: WebAttribute<msdyn_project_Select, { msdyn_costvariance_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costvariance_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_customer_guid: WebAttribute<msdyn_project_Select, { msdyn_customer_guid: string | null }, { msdyn_customer_formatted?: string }>;
  msdyn_description: WebAttribute<msdyn_project_Select, { msdyn_description: string | null }, {  }>;
  msdyn_disablecreateofteammemberformanager: WebAttribute<msdyn_project_Select, { msdyn_disablecreateofteammemberformanager: boolean | null }, {  }>;
  msdyn_effortestimateatcompleteeac: WebAttribute<msdyn_project_Select, { msdyn_effortestimateatcompleteeac: number | null }, {  }>;
  msdyn_exchangerate: WebAttribute<msdyn_project_Select, { msdyn_exchangerate: number | null }, {  }>;
  msdyn_islinkedtomsprojectclient: WebAttribute<msdyn_project_Select, { msdyn_islinkedtomsprojectclient: boolean | null }, {  }>;
  msdyn_istemplate: WebAttribute<msdyn_project_Select, { msdyn_istemplate: boolean | null }, {  }>;
  msdyn_linkeddocumenturl: WebAttribute<msdyn_project_Select, { msdyn_linkeddocumenturl: string | null }, {  }>;
  msdyn_overallprojectstatus: WebAttribute<msdyn_project_Select, { msdyn_overallprojectstatus: msdyn_project_msdyn_overallprojectstatus | null }, { msdyn_overallprojectstatus_formatted?: string }>;
  msdyn_plannedexpensecost: WebAttribute<msdyn_project_Select, { msdyn_plannedexpensecost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_plannedexpensecost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_plannedexpensecost_base: WebAttribute<msdyn_project_Select, { msdyn_plannedexpensecost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_plannedexpensecost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_plannedexpensesales: WebAttribute<msdyn_project_Select, { msdyn_plannedexpensesales: number | null; transactioncurrencyid_guid: string | null }, { msdyn_plannedexpensesales_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_plannedexpensesales_base: WebAttribute<msdyn_project_Select, { msdyn_plannedexpensesales_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_plannedexpensesales_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_plannedhours: WebAttribute<msdyn_project_Select, { msdyn_plannedhours: number | null }, {  }>;
  msdyn_plannedlaborcost: WebAttribute<msdyn_project_Select, { msdyn_plannedlaborcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_plannedlaborcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_plannedlaborcost_base: WebAttribute<msdyn_project_Select, { msdyn_plannedlaborcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_plannedlaborcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_plannedsales: WebAttribute<msdyn_project_Select, { msdyn_plannedsales: number | null; transactioncurrencyid_guid: string | null }, { msdyn_plannedsales_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_plannedsales_base: WebAttribute<msdyn_project_Select, { msdyn_plannedsales_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_plannedsales_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_progress: WebAttribute<msdyn_project_Select, { msdyn_progress: number | null }, {  }>;
  msdyn_projectid: WebAttribute<msdyn_project_Select, { msdyn_projectid: string | null }, {  }>;
  msdyn_projectmanager_guid: WebAttribute<msdyn_project_Select, { msdyn_projectmanager_guid: string | null }, { msdyn_projectmanager_formatted?: string }>;
  msdyn_projectresourcerequirementsvisibletore: WebAttribute<msdyn_project_Select, { msdyn_projectresourcerequirementsvisibletore: boolean | null }, {  }>;
  msdyn_projectteamid_guid: WebAttribute<msdyn_project_Select, { msdyn_projectteamid_guid: string | null }, { msdyn_projectteamid_formatted?: string }>;
  msdyn_projecttemplate_guid: WebAttribute<msdyn_project_Select, { msdyn_projecttemplate_guid: string | null }, { msdyn_projecttemplate_formatted?: string }>;
  msdyn_remainingcost: WebAttribute<msdyn_project_Select, { msdyn_remainingcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_remainingcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_remainingcost_base: WebAttribute<msdyn_project_Select, { msdyn_remainingcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_remainingcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_remaininghours: WebAttribute<msdyn_project_Select, { msdyn_remaininghours: number | null }, {  }>;
  msdyn_remainingsales: WebAttribute<msdyn_project_Select, { msdyn_remainingsales: number | null; transactioncurrencyid_guid: string | null }, { msdyn_remainingsales_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_remainingsales_base: WebAttribute<msdyn_project_Select, { msdyn_remainingsales_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_remainingsales_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_salesconsumption: WebAttribute<msdyn_project_Select, { msdyn_salesconsumption: number | null }, {  }>;
  msdyn_salesestimateatcompleteeac: WebAttribute<msdyn_project_Select, { msdyn_salesestimateatcompleteeac: number | null; transactioncurrencyid_guid: string | null }, { msdyn_salesestimateatcompleteeac_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_salesestimateatcompleteeac_base: WebAttribute<msdyn_project_Select, { msdyn_salesestimateatcompleteeac_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_salesestimateatcompleteeac_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_salesorderid_guid: WebAttribute<msdyn_project_Select, { msdyn_salesorderid_guid: string | null }, { msdyn_salesorderid_formatted?: string }>;
  msdyn_salesvariance: WebAttribute<msdyn_project_Select, { msdyn_salesvariance: number | null; transactioncurrencyid_guid: string | null }, { msdyn_salesvariance_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_salesvariance_base: WebAttribute<msdyn_project_Select, { msdyn_salesvariance_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_salesvariance_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_scheduleddurationminutes: WebAttribute<msdyn_project_Select, { msdyn_scheduleddurationminutes: number | null }, {  }>;
  msdyn_scheduledend: WebAttribute<msdyn_project_Select, { msdyn_scheduledend: Date | null }, { msdyn_scheduledend_formatted?: string }>;
  msdyn_scheduledstart: WebAttribute<msdyn_project_Select, { msdyn_scheduledstart: Date | null }, { msdyn_scheduledstart_formatted?: string }>;
  msdyn_scheduleperformance: WebAttribute<msdyn_project_Select, { msdyn_scheduleperformance: msdyn_project_msdyn_scheduleperformance | null }, { msdyn_scheduleperformance_formatted?: string }>;
  msdyn_schedulevariance: WebAttribute<msdyn_project_Select, { msdyn_schedulevariance: number | null }, {  }>;
  msdyn_stagename: WebAttribute<msdyn_project_Select, { msdyn_stagename: string | null }, {  }>;
  msdyn_statusupdatedon: WebAttribute<msdyn_project_Select, { msdyn_statusupdatedon: Date | null }, { msdyn_statusupdatedon_formatted?: string }>;
  msdyn_subject: WebAttribute<msdyn_project_Select, { msdyn_subject: string | null }, {  }>;
  msdyn_teamsize: WebAttribute<msdyn_project_Select, { msdyn_teamsize: number | null }, {  }>;
  msdyn_teamsize_date: WebAttribute<msdyn_project_Select, { msdyn_teamsize_date: Date | null }, { msdyn_teamsize_date_formatted?: string }>;
  msdyn_teamsize_state: WebAttribute<msdyn_project_Select, { msdyn_teamsize_state: number | null }, {  }>;
  msdyn_totalactualcost: WebAttribute<msdyn_project_Select, { msdyn_totalactualcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalactualcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalactualcost_base: WebAttribute<msdyn_project_Select, { msdyn_totalactualcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalactualcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalactualsales: WebAttribute<msdyn_project_Select, { msdyn_totalactualsales: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalactualsales_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalactualsales_base: WebAttribute<msdyn_project_Select, { msdyn_totalactualsales_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalactualsales_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalplannedcost: WebAttribute<msdyn_project_Select, { msdyn_totalplannedcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalplannedcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalplannedcost_base: WebAttribute<msdyn_project_Select, { msdyn_totalplannedcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalplannedcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalplannedsales: WebAttribute<msdyn_project_Select, { msdyn_totalplannedsales: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalplannedsales_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalplannedsales_base: WebAttribute<msdyn_project_Select, { msdyn_totalplannedsales_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalplannedsales_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_wbsduration: WebAttribute<msdyn_project_Select, { msdyn_wbsduration: number | null }, {  }>;
  msdyn_workhourtemplate_guid: WebAttribute<msdyn_project_Select, { msdyn_workhourtemplate_guid: string | null }, { msdyn_workhourtemplate_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_project_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_project_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_project_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_project_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_project_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  processid: WebAttribute<msdyn_project_Select, { processid: string | null }, {  }>;
  stageid: WebAttribute<msdyn_project_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<msdyn_project_Select, { statecode: msdyn_project_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_project_Select, { statuscode: msdyn_project_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_project_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_project_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<msdyn_project_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_project_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_project_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_project_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_actualdurationminutes: number;
  msdyn_actualend: Date;
  msdyn_actualexpensecost: number;
  msdyn_actualexpensecost_base: number;
  msdyn_actualexpensesales: number;
  msdyn_actualexpensesales_base: number;
  msdyn_actualhours: any;
  msdyn_actuallaborcost: number;
  msdyn_actuallaborcost_base: number;
  msdyn_actualsales: number;
  msdyn_actualsales_base: number;
  msdyn_actualstart: Date;
  msdyn_bulkgenerationstatus: msdyn_asyncoperationstatus;
  msdyn_calendarid: string;
  msdyn_comments: string;
  msdyn_contractorganizationalunitid_guid: XQW.Guid;
  msdyn_costconsumption: any;
  msdyn_costestimateatcomplete: number;
  msdyn_costestimateatcomplete_base: number;
  msdyn_costperformence: msdyn_project_msdyn_costperformence;
  msdyn_costvariance: number;
  msdyn_costvariance_base: number;
  msdyn_customer_guid: XQW.Guid;
  msdyn_description: string;
  msdyn_disablecreateofteammemberformanager: boolean;
  msdyn_effortestimateatcompleteeac: number;
  msdyn_exchangerate: any;
  msdyn_islinkedtomsprojectclient: boolean;
  msdyn_istemplate: boolean;
  msdyn_linkeddocumenturl: string;
  msdyn_overallprojectstatus: msdyn_project_msdyn_overallprojectstatus;
  msdyn_plannedexpensecost: number;
  msdyn_plannedexpensecost_base: number;
  msdyn_plannedexpensesales: number;
  msdyn_plannedexpensesales_base: number;
  msdyn_plannedhours: any;
  msdyn_plannedlaborcost: number;
  msdyn_plannedlaborcost_base: number;
  msdyn_plannedsales: number;
  msdyn_plannedsales_base: number;
  msdyn_progress: any;
  msdyn_projectid: XQW.Guid;
  msdyn_projectmanager_guid: XQW.Guid;
  msdyn_projectresourcerequirementsvisibletore: boolean;
  msdyn_projectteamid_guid: XQW.Guid;
  msdyn_projecttemplate_guid: XQW.Guid;
  msdyn_remainingcost: number;
  msdyn_remainingcost_base: number;
  msdyn_remaininghours: number;
  msdyn_remainingsales: number;
  msdyn_remainingsales_base: number;
  msdyn_salesconsumption: any;
  msdyn_salesestimateatcompleteeac: number;
  msdyn_salesestimateatcompleteeac_base: number;
  msdyn_salesorderid_guid: XQW.Guid;
  msdyn_salesvariance: number;
  msdyn_salesvariance_base: number;
  msdyn_scheduleddurationminutes: number;
  msdyn_scheduledend: Date;
  msdyn_scheduledstart: Date;
  msdyn_scheduleperformance: msdyn_project_msdyn_scheduleperformance;
  msdyn_schedulevariance: number;
  msdyn_stagename: string;
  msdyn_statusupdatedon: Date;
  msdyn_subject: string;
  msdyn_teamsize: number;
  msdyn_teamsize_date: Date;
  msdyn_teamsize_state: number;
  msdyn_totalactualcost: number;
  msdyn_totalactualcost_base: number;
  msdyn_totalactualsales: number;
  msdyn_totalactualsales_base: number;
  msdyn_totalplannedcost: number;
  msdyn_totalplannedcost_base: number;
  msdyn_totalplannedsales: number;
  msdyn_totalplannedsales_base: number;
  msdyn_wbsduration: number;
  msdyn_workhourtemplate_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  processid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: msdyn_project_statecode;
  statuscode: msdyn_project_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_project_Expand {
  bpf_msdyn_project_msdyn_bpf_665e73aa18c247d886bfc50499c73b82: WebExpand<msdyn_project_Expand, msdyn_bpf_665e73aa18c247d886bfc50499c73b82_Select, msdyn_bpf_665e73aa18c247d886bfc50499c73b82_Filter, { bpf_msdyn_project_msdyn_bpf_665e73aa18c247d886bfc50499c73b82: msdyn_bpf_665e73aa18c247d886bfc50499c73b82_Result[] }>;
  createdby: WebExpand<msdyn_project_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_project_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_project_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_project_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_ContractOrganizationalUnitId: WebExpand<msdyn_project_Expand, msdyn_organizationalunit_Select, msdyn_organizationalunit_Filter, { msdyn_ContractOrganizationalUnitId: msdyn_organizationalunit_Result }>;
  msdyn_ProjectTemplate: WebExpand<msdyn_project_Expand, msdyn_project_Select, msdyn_project_Filter, { msdyn_ProjectTemplate: msdyn_project_Result }>;
  msdyn_customer: WebExpand<msdyn_project_Expand, Account_Select, Account_Filter, { msdyn_customer: Account_Result }>;
  msdyn_msdyn_project_bookableresourcebooking_projectid: WebExpand<msdyn_project_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { msdyn_msdyn_project_bookableresourcebooking_projectid: BookableResourceBooking_Result[] }>;
  msdyn_msdyn_project_bookableresourcebookingheader_projectid: WebExpand<msdyn_project_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { msdyn_msdyn_project_bookableresourcebookingheader_projectid: BookableResourceBookingHeader_Result[] }>;
  msdyn_msdyn_project_invoicedetail_Project: WebExpand<msdyn_project_Expand, InvoiceDetail_Select, InvoiceDetail_Filter, { msdyn_msdyn_project_invoicedetail_Project: InvoiceDetail_Result[] }>;
  msdyn_msdyn_project_msdyn_actual_Project: WebExpand<msdyn_project_Expand, msdyn_actual_Select, msdyn_actual_Filter, { msdyn_msdyn_project_msdyn_actual_Project: msdyn_actual_Result[] }>;
  msdyn_msdyn_project_msdyn_approvalset_Project: WebExpand<msdyn_project_Expand, msdyn_approvalset_Select, msdyn_approvalset_Filter, { msdyn_msdyn_project_msdyn_approvalset_Project: msdyn_approvalset_Result[] }>;
  msdyn_msdyn_project_msdyn_contractlinescheduleofvalue_project: WebExpand<msdyn_project_Expand, msdyn_contractlinescheduleofvalue_Select, msdyn_contractlinescheduleofvalue_Filter, { msdyn_msdyn_project_msdyn_contractlinescheduleofvalue_project: msdyn_contractlinescheduleofvalue_Result[] }>;
  msdyn_msdyn_project_msdyn_estimate_Project: WebExpand<msdyn_project_Expand, msdyn_estimate_Select, msdyn_estimate_Filter, { msdyn_msdyn_project_msdyn_estimate_Project: msdyn_estimate_Result[] }>;
  msdyn_msdyn_project_msdyn_estimateline_Project: WebExpand<msdyn_project_Expand, msdyn_estimateline_Select, msdyn_estimateline_Filter, { msdyn_msdyn_project_msdyn_estimateline_Project: msdyn_estimateline_Result[] }>;
  msdyn_msdyn_project_msdyn_expense_Project: WebExpand<msdyn_project_Expand, msdyn_expense_Select, msdyn_expense_Filter, { msdyn_msdyn_project_msdyn_expense_Project: msdyn_expense_Result[] }>;
  msdyn_msdyn_project_msdyn_fact_Project: WebExpand<msdyn_project_Expand, msdyn_fact_Select, msdyn_fact_Filter, { msdyn_msdyn_project_msdyn_fact_Project: msdyn_fact_Result[] }>;
  msdyn_msdyn_project_msdyn_invoicelinetransaction_Project: WebExpand<msdyn_project_Expand, msdyn_invoicelinetransaction_Select, msdyn_invoicelinetransaction_Filter, { msdyn_msdyn_project_msdyn_invoicelinetransaction_Project: msdyn_invoicelinetransaction_Result[] }>;
  msdyn_msdyn_project_msdyn_journal_DefaultProject: WebExpand<msdyn_project_Expand, msdyn_journal_Select, msdyn_journal_Filter, { msdyn_msdyn_project_msdyn_journal_DefaultProject: msdyn_journal_Result[] }>;
  msdyn_msdyn_project_msdyn_journal_Project: WebExpand<msdyn_project_Expand, msdyn_journal_Select, msdyn_journal_Filter, { msdyn_msdyn_project_msdyn_journal_Project: msdyn_journal_Result[] }>;
  msdyn_msdyn_project_msdyn_journalline_Project: WebExpand<msdyn_project_Expand, msdyn_journalline_Select, msdyn_journalline_Filter, { msdyn_msdyn_project_msdyn_journalline_Project: msdyn_journalline_Result[] }>;
  msdyn_msdyn_project_msdyn_opportunitylinetransaction_Project: WebExpand<msdyn_project_Expand, msdyn_opportunitylinetransaction_Select, msdyn_opportunitylinetransaction_Filter, { msdyn_msdyn_project_msdyn_opportunitylinetransaction_Project: msdyn_opportunitylinetransaction_Result[] }>;
  msdyn_msdyn_project_msdyn_orderlinetransaction_Project: WebExpand<msdyn_project_Expand, msdyn_orderlinetransaction_Select, msdyn_orderlinetransaction_Filter, { msdyn_msdyn_project_msdyn_orderlinetransaction_Project: msdyn_orderlinetransaction_Result[] }>;
  msdyn_msdyn_project_msdyn_project_ProjectTemplate: WebExpand<msdyn_project_Expand, msdyn_project_Select, msdyn_project_Filter, { msdyn_msdyn_project_msdyn_project_ProjectTemplate: msdyn_project_Result[] }>;
  msdyn_msdyn_project_msdyn_projectapproval_Project: WebExpand<msdyn_project_Expand, msdyn_projectapproval_Select, msdyn_projectapproval_Filter, { msdyn_msdyn_project_msdyn_projectapproval_Project: msdyn_projectapproval_Result[] }>;
  msdyn_msdyn_project_msdyn_projectpricelist_Project: WebExpand<msdyn_project_Expand, msdyn_projectpricelist_Select, msdyn_projectpricelist_Filter, { msdyn_msdyn_project_msdyn_projectpricelist_Project: msdyn_projectpricelist_Result[] }>;
  msdyn_msdyn_project_msdyn_projecttask_project: WebExpand<msdyn_project_Expand, msdyn_projecttask_Select, msdyn_projecttask_Filter, { msdyn_msdyn_project_msdyn_projecttask_project: msdyn_projecttask_Result[] }>;
  msdyn_msdyn_project_msdyn_projecttaskdependency_Project: WebExpand<msdyn_project_Expand, msdyn_projecttaskdependency_Select, msdyn_projecttaskdependency_Filter, { msdyn_msdyn_project_msdyn_projecttaskdependency_Project: msdyn_projecttaskdependency_Result[] }>;
  msdyn_msdyn_project_msdyn_projectteam_project: WebExpand<msdyn_project_Expand, msdyn_projectteam_Select, msdyn_projectteam_Filter, { msdyn_msdyn_project_msdyn_projectteam_project: msdyn_projectteam_Result[] }>;
  msdyn_msdyn_project_msdyn_projecttransactioncategory_Project: WebExpand<msdyn_project_Expand, msdyn_projecttransactioncategory_Select, msdyn_projecttransactioncategory_Filter, { msdyn_msdyn_project_msdyn_projecttransactioncategory_Project: msdyn_projecttransactioncategory_Result[] }>;
  msdyn_msdyn_project_msdyn_quotelinetransaction_Project: WebExpand<msdyn_project_Expand, msdyn_quotelinetransaction_Select, msdyn_quotelinetransaction_Filter, { msdyn_msdyn_project_msdyn_quotelinetransaction_Project: msdyn_quotelinetransaction_Result[] }>;
  msdyn_msdyn_project_msdyn_resourceassignment_projectid: WebExpand<msdyn_project_Expand, msdyn_resourceassignment_Select, msdyn_resourceassignment_Filter, { msdyn_msdyn_project_msdyn_resourceassignment_projectid: msdyn_resourceassignment_Result[] }>;
  msdyn_msdyn_project_msdyn_timeentry_project: WebExpand<msdyn_project_Expand, msdyn_timeentry_Select, msdyn_timeentry_Filter, { msdyn_msdyn_project_msdyn_timeentry_project: msdyn_timeentry_Result[] }>;
  msdyn_msdyn_project_opportunityproduct_Project: WebExpand<msdyn_project_Expand, OpportunityProduct_Select, OpportunityProduct_Filter, { msdyn_msdyn_project_opportunityproduct_Project: OpportunityProduct_Result[] }>;
  msdyn_msdyn_project_quotedetail_Project: WebExpand<msdyn_project_Expand, QuoteDetail_Select, QuoteDetail_Filter, { msdyn_msdyn_project_quotedetail_Project: QuoteDetail_Result[] }>;
  msdyn_msdyn_project_salesorderdetail_Project: WebExpand<msdyn_project_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { msdyn_msdyn_project_salesorderdetail_Project: SalesOrderDetail_Result[] }>;
  msdyn_project_Annotations: WebExpand<msdyn_project_Expand, Annotation_Select, Annotation_Filter, { msdyn_project_Annotations: Annotation_Result[] }>;
  msdyn_project_AsyncOperations: WebExpand<msdyn_project_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_project_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_project_BulkDeleteFailures: WebExpand<msdyn_project_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_project_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_project_DuplicateBaseRecord: WebExpand<msdyn_project_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_project_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_project_DuplicateMatchingRecord: WebExpand<msdyn_project_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_project_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_project_MailboxTrackingFolders: WebExpand<msdyn_project_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_project_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_project_PrincipalObjectAttributeAccesses: WebExpand<msdyn_project_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_project_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_project_ProcessSession: WebExpand<msdyn_project_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_project_ProcessSession: ProcessSession_Result[] }>;
  msdyn_project_QueueItems: WebExpand<msdyn_project_Expand, QueueItem_Select, QueueItem_Filter, { msdyn_project_QueueItems: QueueItem_Result[] }>;
  msdyn_project_SharePointDocumentLocations: WebExpand<msdyn_project_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { msdyn_project_SharePointDocumentLocations: SharePointDocumentLocation_Result[] }>;
  msdyn_project_SharePointDocuments: WebExpand<msdyn_project_Expand, SharePointDocument_Select, SharePointDocument_Filter, { msdyn_project_SharePointDocuments: SharePointDocument_Result[] }>;
  msdyn_project_SyncErrors: WebExpand<msdyn_project_Expand, SyncError_Select, SyncError_Filter, { msdyn_project_SyncErrors: SyncError_Result[] }>;
  msdyn_project_UserEntityInstanceDatas: WebExpand<msdyn_project_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_project_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_project_connections1: WebExpand<msdyn_project_Expand, Connection_Select, Connection_Filter, { msdyn_project_connections1: Connection_Result[] }>;
  msdyn_project_connections2: WebExpand<msdyn_project_Expand, Connection_Select, Connection_Filter, { msdyn_project_connections2: Connection_Result[] }>;
  msdyn_project_resourcerequirement: WebExpand<msdyn_project_Expand, msdyn_resourcerequirement_Select, msdyn_resourcerequirement_Filter, { msdyn_project_resourcerequirement: msdyn_resourcerequirement_Result[] }>;
  msdyn_projectmanager: WebExpand<msdyn_project_Expand, SystemUser_Select, SystemUser_Filter, { msdyn_projectmanager: SystemUser_Result }>;
  msdyn_projectteamid: WebExpand<msdyn_project_Expand, Team_Select, Team_Filter, { msdyn_projectteamid: Team_Result }>;
  msdyn_salesorderid: WebExpand<msdyn_project_Expand, SalesOrder_Select, SalesOrder_Filter, { msdyn_salesorderid: SalesOrder_Result }>;
  msdyn_workhourtemplate: WebExpand<msdyn_project_Expand, msdyn_workhourtemplate_Select, msdyn_workhourtemplate_Filter, { msdyn_workhourtemplate: msdyn_workhourtemplate_Result }>;
  ownerid: WebExpand<msdyn_project_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_project_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_project_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_project_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  stageid: WebExpand<msdyn_project_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid: ProcessStage_Result }>;
  transactioncurrencyid: WebExpand<msdyn_project_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface msdyn_project_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_actualend_formatted?: string;
  msdyn_actualexpensecost_base_formatted?: string;
  msdyn_actualexpensecost_formatted?: string;
  msdyn_actualexpensesales_base_formatted?: string;
  msdyn_actualexpensesales_formatted?: string;
  msdyn_actuallaborcost_base_formatted?: string;
  msdyn_actuallaborcost_formatted?: string;
  msdyn_actualsales_base_formatted?: string;
  msdyn_actualsales_formatted?: string;
  msdyn_actualstart_formatted?: string;
  msdyn_bulkgenerationstatus_formatted?: string;
  msdyn_contractorganizationalunitid_formatted?: string;
  msdyn_costestimateatcomplete_base_formatted?: string;
  msdyn_costestimateatcomplete_formatted?: string;
  msdyn_costperformence_formatted?: string;
  msdyn_costvariance_base_formatted?: string;
  msdyn_costvariance_formatted?: string;
  msdyn_customer_formatted?: string;
  msdyn_overallprojectstatus_formatted?: string;
  msdyn_plannedexpensecost_base_formatted?: string;
  msdyn_plannedexpensecost_formatted?: string;
  msdyn_plannedexpensesales_base_formatted?: string;
  msdyn_plannedexpensesales_formatted?: string;
  msdyn_plannedlaborcost_base_formatted?: string;
  msdyn_plannedlaborcost_formatted?: string;
  msdyn_plannedsales_base_formatted?: string;
  msdyn_plannedsales_formatted?: string;
  msdyn_projectmanager_formatted?: string;
  msdyn_projectteamid_formatted?: string;
  msdyn_projecttemplate_formatted?: string;
  msdyn_remainingcost_base_formatted?: string;
  msdyn_remainingcost_formatted?: string;
  msdyn_remainingsales_base_formatted?: string;
  msdyn_remainingsales_formatted?: string;
  msdyn_salesestimateatcompleteeac_base_formatted?: string;
  msdyn_salesestimateatcompleteeac_formatted?: string;
  msdyn_salesorderid_formatted?: string;
  msdyn_salesvariance_base_formatted?: string;
  msdyn_salesvariance_formatted?: string;
  msdyn_scheduledend_formatted?: string;
  msdyn_scheduledstart_formatted?: string;
  msdyn_scheduleperformance_formatted?: string;
  msdyn_statusupdatedon_formatted?: string;
  msdyn_teamsize_date_formatted?: string;
  msdyn_totalactualcost_base_formatted?: string;
  msdyn_totalactualcost_formatted?: string;
  msdyn_totalactualsales_base_formatted?: string;
  msdyn_totalactualsales_formatted?: string;
  msdyn_totalplannedcost_base_formatted?: string;
  msdyn_totalplannedcost_formatted?: string;
  msdyn_totalplannedsales_base_formatted?: string;
  msdyn_totalplannedsales_formatted?: string;
  msdyn_workhourtemplate_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface msdyn_project_Result extends msdyn_project_Base, msdyn_project_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_contractorganizationalunitid_guid: string | null;
  msdyn_customer_guid: string | null;
  msdyn_projectmanager_guid: string | null;
  msdyn_projectteamid_guid: string | null;
  msdyn_projecttemplate_guid: string | null;
  msdyn_salesorderid_guid: string | null;
  msdyn_workhourtemplate_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface msdyn_project_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_ContractOrganizationalUnitId: WebMappingRetrieve<msdyn_organizationalunit_Select,msdyn_organizationalunit_Expand,msdyn_organizationalunit_Filter,msdyn_organizationalunit_Fixed,msdyn_organizationalunit_Result,msdyn_organizationalunit_FormattedResult>;
  msdyn_ProjectTemplate: WebMappingRetrieve<msdyn_project_Select,msdyn_project_Expand,msdyn_project_Filter,msdyn_project_Fixed,msdyn_project_Result,msdyn_project_FormattedResult>;
  msdyn_customer: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_projectmanager: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_projectteamid: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  msdyn_salesorderid: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  msdyn_workhourtemplate: WebMappingRetrieve<msdyn_workhourtemplate_Select,msdyn_workhourtemplate_Expand,msdyn_workhourtemplate_Filter,msdyn_workhourtemplate_Fixed,msdyn_workhourtemplate_Result,msdyn_workhourtemplate_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  stageid: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface msdyn_project_RelatedMany {
  bpf_msdyn_project_msdyn_bpf_665e73aa18c247d886bfc50499c73b82: WebMappingRetrieve<msdyn_bpf_665e73aa18c247d886bfc50499c73b82_Select,msdyn_bpf_665e73aa18c247d886bfc50499c73b82_Expand,msdyn_bpf_665e73aa18c247d886bfc50499c73b82_Filter,msdyn_bpf_665e73aa18c247d886bfc50499c73b82_Fixed,msdyn_bpf_665e73aa18c247d886bfc50499c73b82_Result,msdyn_bpf_665e73aa18c247d886bfc50499c73b82_FormattedResult>;
  msdyn_msdyn_project_bookableresourcebooking_projectid: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  msdyn_msdyn_project_bookableresourcebookingheader_projectid: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  msdyn_msdyn_project_invoicedetail_Project: WebMappingRetrieve<InvoiceDetail_Select,InvoiceDetail_Expand,InvoiceDetail_Filter,InvoiceDetail_Fixed,InvoiceDetail_Result,InvoiceDetail_FormattedResult>;
  msdyn_msdyn_project_msdyn_actual_Project: WebMappingRetrieve<msdyn_actual_Select,msdyn_actual_Expand,msdyn_actual_Filter,msdyn_actual_Fixed,msdyn_actual_Result,msdyn_actual_FormattedResult>;
  msdyn_msdyn_project_msdyn_approvalset_Project: WebMappingRetrieve<msdyn_approvalset_Select,msdyn_approvalset_Expand,msdyn_approvalset_Filter,msdyn_approvalset_Fixed,msdyn_approvalset_Result,msdyn_approvalset_FormattedResult>;
  msdyn_msdyn_project_msdyn_contractlinescheduleofvalue_project: WebMappingRetrieve<msdyn_contractlinescheduleofvalue_Select,msdyn_contractlinescheduleofvalue_Expand,msdyn_contractlinescheduleofvalue_Filter,msdyn_contractlinescheduleofvalue_Fixed,msdyn_contractlinescheduleofvalue_Result,msdyn_contractlinescheduleofvalue_FormattedResult>;
  msdyn_msdyn_project_msdyn_estimate_Project: WebMappingRetrieve<msdyn_estimate_Select,msdyn_estimate_Expand,msdyn_estimate_Filter,msdyn_estimate_Fixed,msdyn_estimate_Result,msdyn_estimate_FormattedResult>;
  msdyn_msdyn_project_msdyn_estimateline_Project: WebMappingRetrieve<msdyn_estimateline_Select,msdyn_estimateline_Expand,msdyn_estimateline_Filter,msdyn_estimateline_Fixed,msdyn_estimateline_Result,msdyn_estimateline_FormattedResult>;
  msdyn_msdyn_project_msdyn_expense_Project: WebMappingRetrieve<msdyn_expense_Select,msdyn_expense_Expand,msdyn_expense_Filter,msdyn_expense_Fixed,msdyn_expense_Result,msdyn_expense_FormattedResult>;
  msdyn_msdyn_project_msdyn_fact_Project: WebMappingRetrieve<msdyn_fact_Select,msdyn_fact_Expand,msdyn_fact_Filter,msdyn_fact_Fixed,msdyn_fact_Result,msdyn_fact_FormattedResult>;
  msdyn_msdyn_project_msdyn_invoicelinetransaction_Project: WebMappingRetrieve<msdyn_invoicelinetransaction_Select,msdyn_invoicelinetransaction_Expand,msdyn_invoicelinetransaction_Filter,msdyn_invoicelinetransaction_Fixed,msdyn_invoicelinetransaction_Result,msdyn_invoicelinetransaction_FormattedResult>;
  msdyn_msdyn_project_msdyn_journal_DefaultProject: WebMappingRetrieve<msdyn_journal_Select,msdyn_journal_Expand,msdyn_journal_Filter,msdyn_journal_Fixed,msdyn_journal_Result,msdyn_journal_FormattedResult>;
  msdyn_msdyn_project_msdyn_journal_Project: WebMappingRetrieve<msdyn_journal_Select,msdyn_journal_Expand,msdyn_journal_Filter,msdyn_journal_Fixed,msdyn_journal_Result,msdyn_journal_FormattedResult>;
  msdyn_msdyn_project_msdyn_journalline_Project: WebMappingRetrieve<msdyn_journalline_Select,msdyn_journalline_Expand,msdyn_journalline_Filter,msdyn_journalline_Fixed,msdyn_journalline_Result,msdyn_journalline_FormattedResult>;
  msdyn_msdyn_project_msdyn_opportunitylinetransaction_Project: WebMappingRetrieve<msdyn_opportunitylinetransaction_Select,msdyn_opportunitylinetransaction_Expand,msdyn_opportunitylinetransaction_Filter,msdyn_opportunitylinetransaction_Fixed,msdyn_opportunitylinetransaction_Result,msdyn_opportunitylinetransaction_FormattedResult>;
  msdyn_msdyn_project_msdyn_orderlinetransaction_Project: WebMappingRetrieve<msdyn_orderlinetransaction_Select,msdyn_orderlinetransaction_Expand,msdyn_orderlinetransaction_Filter,msdyn_orderlinetransaction_Fixed,msdyn_orderlinetransaction_Result,msdyn_orderlinetransaction_FormattedResult>;
  msdyn_msdyn_project_msdyn_project_ProjectTemplate: WebMappingRetrieve<msdyn_project_Select,msdyn_project_Expand,msdyn_project_Filter,msdyn_project_Fixed,msdyn_project_Result,msdyn_project_FormattedResult>;
  msdyn_msdyn_project_msdyn_projectapproval_Project: WebMappingRetrieve<msdyn_projectapproval_Select,msdyn_projectapproval_Expand,msdyn_projectapproval_Filter,msdyn_projectapproval_Fixed,msdyn_projectapproval_Result,msdyn_projectapproval_FormattedResult>;
  msdyn_msdyn_project_msdyn_projectpricelist_Project: WebMappingRetrieve<msdyn_projectpricelist_Select,msdyn_projectpricelist_Expand,msdyn_projectpricelist_Filter,msdyn_projectpricelist_Fixed,msdyn_projectpricelist_Result,msdyn_projectpricelist_FormattedResult>;
  msdyn_msdyn_project_msdyn_projecttask_project: WebMappingRetrieve<msdyn_projecttask_Select,msdyn_projecttask_Expand,msdyn_projecttask_Filter,msdyn_projecttask_Fixed,msdyn_projecttask_Result,msdyn_projecttask_FormattedResult>;
  msdyn_msdyn_project_msdyn_projecttaskdependency_Project: WebMappingRetrieve<msdyn_projecttaskdependency_Select,msdyn_projecttaskdependency_Expand,msdyn_projecttaskdependency_Filter,msdyn_projecttaskdependency_Fixed,msdyn_projecttaskdependency_Result,msdyn_projecttaskdependency_FormattedResult>;
  msdyn_msdyn_project_msdyn_projectteam_project: WebMappingRetrieve<msdyn_projectteam_Select,msdyn_projectteam_Expand,msdyn_projectteam_Filter,msdyn_projectteam_Fixed,msdyn_projectteam_Result,msdyn_projectteam_FormattedResult>;
  msdyn_msdyn_project_msdyn_projecttransactioncategory_Project: WebMappingRetrieve<msdyn_projecttransactioncategory_Select,msdyn_projecttransactioncategory_Expand,msdyn_projecttransactioncategory_Filter,msdyn_projecttransactioncategory_Fixed,msdyn_projecttransactioncategory_Result,msdyn_projecttransactioncategory_FormattedResult>;
  msdyn_msdyn_project_msdyn_quotelinetransaction_Project: WebMappingRetrieve<msdyn_quotelinetransaction_Select,msdyn_quotelinetransaction_Expand,msdyn_quotelinetransaction_Filter,msdyn_quotelinetransaction_Fixed,msdyn_quotelinetransaction_Result,msdyn_quotelinetransaction_FormattedResult>;
  msdyn_msdyn_project_msdyn_resourceassignment_projectid: WebMappingRetrieve<msdyn_resourceassignment_Select,msdyn_resourceassignment_Expand,msdyn_resourceassignment_Filter,msdyn_resourceassignment_Fixed,msdyn_resourceassignment_Result,msdyn_resourceassignment_FormattedResult>;
  msdyn_msdyn_project_msdyn_timeentry_project: WebMappingRetrieve<msdyn_timeentry_Select,msdyn_timeentry_Expand,msdyn_timeentry_Filter,msdyn_timeentry_Fixed,msdyn_timeentry_Result,msdyn_timeentry_FormattedResult>;
  msdyn_msdyn_project_opportunityproduct_Project: WebMappingRetrieve<OpportunityProduct_Select,OpportunityProduct_Expand,OpportunityProduct_Filter,OpportunityProduct_Fixed,OpportunityProduct_Result,OpportunityProduct_FormattedResult>;
  msdyn_msdyn_project_quotedetail_Project: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  msdyn_msdyn_project_salesorderdetail_Project: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  msdyn_project_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_project_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_project_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_project_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_project_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_project_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_project_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_project_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_project_QueueItems: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  msdyn_project_SharePointDocumentLocations: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  msdyn_project_SharePointDocuments: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  msdyn_project_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_project_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_project_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_project_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_project_resourcerequirement: WebMappingRetrieve<msdyn_resourcerequirement_Select,msdyn_resourcerequirement_Expand,msdyn_resourcerequirement_Filter,msdyn_resourcerequirement_Fixed,msdyn_resourcerequirement_Result,msdyn_resourcerequirement_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_projects: WebMappingRetrieve<msdyn_project_Select,msdyn_project_Expand,msdyn_project_Filter,msdyn_project_Fixed,msdyn_project_Result,msdyn_project_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_projects: WebMappingRelated<msdyn_project_RelatedOne,msdyn_project_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_projects: WebMappingCUDA<msdyn_project_Create,msdyn_project_Update,msdyn_project_Select>;
}
