interface msdyn_livechatconfig_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_agentdisplayname?: msdyn_agentdisplayname | null;
  msdyn_autodetectlanguage?: boolean | null;
  msdyn_avatarurl?: string | null;
  msdyn_averagewaittime_enabled?: boolean | null;
  msdyn_callingoptions?: msdyn_occallingoptions | null;
  msdyn_cobrowseprovider?: string | null;
  msdyn_conversationmode?: msdyn_livechatconfig_msdyn_conversationmode | null;
  msdyn_duringnonoperatinghours?: string | null;
  msdyn_emailtemplate?: string | null;
  msdyn_enablechatreconnect?: boolean | null;
  msdyn_enablechattranscriptdownload?: boolean | null;
  msdyn_enablechattranscriptemail?: boolean | null;
  msdyn_enablecobrowse?: boolean | null;
  msdyn_enablefileattachmentsforagents?: boolean | null;
  msdyn_enablefileattachmentsforcustomers?: boolean | null;
  msdyn_enablescreensharing?: boolean | null;
  msdyn_genericagentdisplayname?: string | null;
  msdyn_infolabel?: string | null;
  msdyn_language?: msdyn_widgetlanguage | null;
  msdyn_livechatconfigid?: string | null;
  msdyn_mailbox?: string | null;
  msdyn_name?: string | null;
  msdyn_offlinewidgetsubtitle?: string | null;
  msdyn_offlinewidgetthemecolor?: msdyn_widgetthemecolor | null;
  msdyn_offlinewidgettitle?: string | null;
  msdyn_portalurl?: string | null;
  msdyn_positioninqueue_enabled?: boolean | null;
  msdyn_postchatenabled?: boolean | null;
  msdyn_postconversationsurveyenable?: boolean | null;
  msdyn_postconversationsurveymessagetext?: string | null;
  msdyn_postconversationsurveymode?: msdyn_postconversationsurveymode | null;
  msdyn_prechatenabled?: boolean | null;
  msdyn_proactivechatenabled?: boolean | null;
  msdyn_redirectionurl?: string | null;
  msdyn_requestvisitorlocation?: boolean | null;
  msdyn_screensharingprovider?: string | null;
  msdyn_showagentname?: boolean | null;
  msdyn_showwidgetduringofflinehours?: boolean | null;
  msdyn_timetoreconnectwithpreviousagent?: number | null;
  msdyn_widgetappid?: string | null;
  msdyn_widgetposition?: msdyn_widgetposition | null;
  msdyn_widgetsnippet?: string | null;
  msdyn_widgetsoundnotification?: boolean | null;
  msdyn_widgetsubtitle?: string | null;
  msdyn_widgetthemecolor?: msdyn_widgetthemecolor | null;
  msdyn_widgettitle?: string | null;
  msdyn_widgetvisualnotification?: boolean | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_livechatconfig_statecode | null;
  statuscode?: msdyn_livechatconfig_statuscode | null;
  timezoneruleversionnumber?: number | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_livechatconfig_Relationships {
  msdyn_AuthsettingsId?: msdyn_authenticationsettings_Result | null;
  msdyn_PostConversationSurvey?: msfp_survey_Result | null;
  msdyn_WidgetLocale?: msdyn_chatwidgetlanguage_Result | null;
  msdyn_livechatconfig_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_livechatconfig_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_livechatconfig_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_livechatconfig_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_livechatconfig_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_livechatconfig_SyncErrors?: SyncError_Result[] | null;
  msdyn_livechatconfig_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_livechatconfig_msdyn_ocsystemmessage?: msdyn_ocsystemmessage_Result[] | null;
  msdyn_livechatconfig_msdyn_questionsequence?: msdyn_questionsequence_Result[] | null;
  msdyn_msdyn_livechatconfig_msdyn_chatquestionnaireresponse?: msdyn_chatquestionnaireresponse_Result[] | null;
  msdyn_msdyn_livechatconfig_msdyn_livechatwidgetlocation_livechatconfigid?: msdyn_livechatwidgetlocation_Result[] | null;
  msdyn_ocWidgetLanguage?: msdyn_oclanguage_Result | null;
}
interface msdyn_livechatconfig extends msdyn_livechatconfig_Base, msdyn_livechatconfig_Relationships {
  msdyn_AuthsettingsId_bind$msdyn_authenticationsettingses?: string | null;
  msdyn_PostConversationSurvey_bind$msfp_surveies?: string | null;
  msdyn_WidgetLocale_bind$msdyn_chatwidgetlanguages?: string | null;
  msdyn_liveworkstreamid_bind$msdyn_liveworkstreams?: string | null;
  msdyn_ocWidgetLanguage_bind$msdyn_oclanguages?: string | null;
  msdyn_oc_geolocationprovider_bind$msdyn_oc_geolocationproviders?: string | null;
  msdyn_operatinghourid_bind$msdyn_operatinghours?: string | null;
  msdyn_prechatquestionnaireauthenticated_bind$msdyn_questionsequences?: string | null;
  msdyn_prechatquestionnaireunauthenticated_bind$msdyn_questionsequences?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface msdyn_livechatconfig_Create extends msdyn_livechatconfig {
}
interface msdyn_livechatconfig_Update extends msdyn_livechatconfig {
}
interface msdyn_livechatconfig_Select {
  createdby_guid: WebAttribute<msdyn_livechatconfig_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_livechatconfig_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_livechatconfig_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<msdyn_livechatconfig_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_livechatconfig_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_livechatconfig_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_livechatconfig_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_agentdisplayname: WebAttribute<msdyn_livechatconfig_Select, { msdyn_agentdisplayname: msdyn_agentdisplayname | null }, { msdyn_agentdisplayname_formatted?: string }>;
  msdyn_authsettingsid_guid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_authsettingsid_guid: string | null }, { msdyn_authsettingsid_formatted?: string }>;
  msdyn_autodetectlanguage: WebAttribute<msdyn_livechatconfig_Select, { msdyn_autodetectlanguage: boolean | null }, {  }>;
  msdyn_avatarurl: WebAttribute<msdyn_livechatconfig_Select, { msdyn_avatarurl: string | null }, {  }>;
  msdyn_averagewaittime_enabled: WebAttribute<msdyn_livechatconfig_Select, { msdyn_averagewaittime_enabled: boolean | null }, {  }>;
  msdyn_callingoptions: WebAttribute<msdyn_livechatconfig_Select, { msdyn_callingoptions: msdyn_occallingoptions | null }, { msdyn_callingoptions_formatted?: string }>;
  msdyn_cobrowseprovider: WebAttribute<msdyn_livechatconfig_Select, { msdyn_cobrowseprovider: string | null }, {  }>;
  msdyn_conversationmode: WebAttribute<msdyn_livechatconfig_Select, { msdyn_conversationmode: msdyn_livechatconfig_msdyn_conversationmode | null }, { msdyn_conversationmode_formatted?: string }>;
  msdyn_duringnonoperatinghours: WebAttribute<msdyn_livechatconfig_Select, { msdyn_duringnonoperatinghours: string | null }, {  }>;
  msdyn_emailtemplate: WebAttribute<msdyn_livechatconfig_Select, { msdyn_emailtemplate: string | null }, {  }>;
  msdyn_enablechatreconnect: WebAttribute<msdyn_livechatconfig_Select, { msdyn_enablechatreconnect: boolean | null }, {  }>;
  msdyn_enablechattranscriptdownload: WebAttribute<msdyn_livechatconfig_Select, { msdyn_enablechattranscriptdownload: boolean | null }, {  }>;
  msdyn_enablechattranscriptemail: WebAttribute<msdyn_livechatconfig_Select, { msdyn_enablechattranscriptemail: boolean | null }, {  }>;
  msdyn_enablecobrowse: WebAttribute<msdyn_livechatconfig_Select, { msdyn_enablecobrowse: boolean | null }, {  }>;
  msdyn_enablefileattachmentsforagents: WebAttribute<msdyn_livechatconfig_Select, { msdyn_enablefileattachmentsforagents: boolean | null }, {  }>;
  msdyn_enablefileattachmentsforcustomers: WebAttribute<msdyn_livechatconfig_Select, { msdyn_enablefileattachmentsforcustomers: boolean | null }, {  }>;
  msdyn_enablescreensharing: WebAttribute<msdyn_livechatconfig_Select, { msdyn_enablescreensharing: boolean | null }, {  }>;
  msdyn_genericagentdisplayname: WebAttribute<msdyn_livechatconfig_Select, { msdyn_genericagentdisplayname: string | null }, {  }>;
  msdyn_infolabel: WebAttribute<msdyn_livechatconfig_Select, { msdyn_infolabel: string | null }, {  }>;
  msdyn_language: WebAttribute<msdyn_livechatconfig_Select, { msdyn_language: msdyn_widgetlanguage | null }, { msdyn_language_formatted?: string }>;
  msdyn_livechatconfigid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_livechatconfigid: string | null }, {  }>;
  msdyn_liveworkstreamid_guid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_liveworkstreamid_guid: string | null }, { msdyn_liveworkstreamid_formatted?: string }>;
  msdyn_mailbox: WebAttribute<msdyn_livechatconfig_Select, { msdyn_mailbox: string | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_livechatconfig_Select, { msdyn_name: string | null }, {  }>;
  msdyn_oc_geolocationprovider_guid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_oc_geolocationprovider_guid: string | null }, { msdyn_oc_geolocationprovider_formatted?: string }>;
  msdyn_ocwidgetlanguage_guid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_ocwidgetlanguage_guid: string | null }, { msdyn_ocwidgetlanguage_formatted?: string }>;
  msdyn_offlinewidgetsubtitle: WebAttribute<msdyn_livechatconfig_Select, { msdyn_offlinewidgetsubtitle: string | null }, {  }>;
  msdyn_offlinewidgetthemecolor: WebAttribute<msdyn_livechatconfig_Select, { msdyn_offlinewidgetthemecolor: msdyn_widgetthemecolor | null }, { msdyn_offlinewidgetthemecolor_formatted?: string }>;
  msdyn_offlinewidgettitle: WebAttribute<msdyn_livechatconfig_Select, { msdyn_offlinewidgettitle: string | null }, {  }>;
  msdyn_operatinghourid_guid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_operatinghourid_guid: string | null }, { msdyn_operatinghourid_formatted?: string }>;
  msdyn_portalurl: WebAttribute<msdyn_livechatconfig_Select, { msdyn_portalurl: string | null }, {  }>;
  msdyn_positioninqueue_enabled: WebAttribute<msdyn_livechatconfig_Select, { msdyn_positioninqueue_enabled: boolean | null }, {  }>;
  msdyn_postchatenabled: WebAttribute<msdyn_livechatconfig_Select, { msdyn_postchatenabled: boolean | null }, {  }>;
  msdyn_postconversationsurvey_guid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_postconversationsurvey_guid: string | null }, { msdyn_postconversationsurvey_formatted?: string }>;
  msdyn_postconversationsurveyenable: WebAttribute<msdyn_livechatconfig_Select, { msdyn_postconversationsurveyenable: boolean | null }, {  }>;
  msdyn_postconversationsurveymessagetext: WebAttribute<msdyn_livechatconfig_Select, { msdyn_postconversationsurveymessagetext: string | null }, {  }>;
  msdyn_postconversationsurveymode: WebAttribute<msdyn_livechatconfig_Select, { msdyn_postconversationsurveymode: msdyn_postconversationsurveymode | null }, { msdyn_postconversationsurveymode_formatted?: string }>;
  msdyn_prechatenabled: WebAttribute<msdyn_livechatconfig_Select, { msdyn_prechatenabled: boolean | null }, {  }>;
  msdyn_prechatquestionnaireauthenticated_guid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_prechatquestionnaireauthenticated_guid: string | null }, { msdyn_prechatquestionnaireauthenticated_formatted?: string }>;
  msdyn_prechatquestionnaireunauthenticated_guid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_prechatquestionnaireunauthenticated_guid: string | null }, { msdyn_prechatquestionnaireunauthenticated_formatted?: string }>;
  msdyn_proactivechatenabled: WebAttribute<msdyn_livechatconfig_Select, { msdyn_proactivechatenabled: boolean | null }, {  }>;
  msdyn_redirectionurl: WebAttribute<msdyn_livechatconfig_Select, { msdyn_redirectionurl: string | null }, {  }>;
  msdyn_requestvisitorlocation: WebAttribute<msdyn_livechatconfig_Select, { msdyn_requestvisitorlocation: boolean | null }, {  }>;
  msdyn_screensharingprovider: WebAttribute<msdyn_livechatconfig_Select, { msdyn_screensharingprovider: string | null }, {  }>;
  msdyn_showagentname: WebAttribute<msdyn_livechatconfig_Select, { msdyn_showagentname: boolean | null }, {  }>;
  msdyn_showwidgetduringofflinehours: WebAttribute<msdyn_livechatconfig_Select, { msdyn_showwidgetduringofflinehours: boolean | null }, {  }>;
  msdyn_timetoreconnectwithpreviousagent: WebAttribute<msdyn_livechatconfig_Select, { msdyn_timetoreconnectwithpreviousagent: number | null }, {  }>;
  msdyn_widgetappid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_widgetappid: string | null }, {  }>;
  msdyn_widgetlocale_guid: WebAttribute<msdyn_livechatconfig_Select, { msdyn_widgetlocale_guid: string | null }, { msdyn_widgetlocale_formatted?: string }>;
  msdyn_widgetposition: WebAttribute<msdyn_livechatconfig_Select, { msdyn_widgetposition: msdyn_widgetposition | null }, { msdyn_widgetposition_formatted?: string }>;
  msdyn_widgetsnippet: WebAttribute<msdyn_livechatconfig_Select, { msdyn_widgetsnippet: string | null }, {  }>;
  msdyn_widgetsoundnotification: WebAttribute<msdyn_livechatconfig_Select, { msdyn_widgetsoundnotification: boolean | null }, {  }>;
  msdyn_widgetsubtitle: WebAttribute<msdyn_livechatconfig_Select, { msdyn_widgetsubtitle: string | null }, {  }>;
  msdyn_widgetthemecolor: WebAttribute<msdyn_livechatconfig_Select, { msdyn_widgetthemecolor: msdyn_widgetthemecolor | null }, { msdyn_widgetthemecolor_formatted?: string }>;
  msdyn_widgettitle: WebAttribute<msdyn_livechatconfig_Select, { msdyn_widgettitle: string | null }, {  }>;
  msdyn_widgetvisualnotification: WebAttribute<msdyn_livechatconfig_Select, { msdyn_widgetvisualnotification: boolean | null }, {  }>;
  overriddencreatedon: WebAttribute<msdyn_livechatconfig_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_livechatconfig_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_livechatconfig_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_livechatconfig_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_livechatconfig_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_livechatconfig_Select, { statecode: msdyn_livechatconfig_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_livechatconfig_Select, { statuscode: msdyn_livechatconfig_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_livechatconfig_Select, { timezoneruleversionnumber: number | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_livechatconfig_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_livechatconfig_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_livechatconfig_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_agentdisplayname: msdyn_agentdisplayname;
  msdyn_authsettingsid_guid: XQW.Guid;
  msdyn_autodetectlanguage: boolean;
  msdyn_avatarurl: string;
  msdyn_averagewaittime_enabled: boolean;
  msdyn_callingoptions: msdyn_occallingoptions;
  msdyn_cobrowseprovider: string;
  msdyn_conversationmode: msdyn_livechatconfig_msdyn_conversationmode;
  msdyn_duringnonoperatinghours: string;
  msdyn_emailtemplate: string;
  msdyn_enablechatreconnect: boolean;
  msdyn_enablechattranscriptdownload: boolean;
  msdyn_enablechattranscriptemail: boolean;
  msdyn_enablecobrowse: boolean;
  msdyn_enablefileattachmentsforagents: boolean;
  msdyn_enablefileattachmentsforcustomers: boolean;
  msdyn_enablescreensharing: boolean;
  msdyn_genericagentdisplayname: string;
  msdyn_infolabel: string;
  msdyn_language: msdyn_widgetlanguage;
  msdyn_livechatconfigid: XQW.Guid;
  msdyn_liveworkstreamid_guid: XQW.Guid;
  msdyn_mailbox: string;
  msdyn_name: string;
  msdyn_oc_geolocationprovider_guid: XQW.Guid;
  msdyn_ocwidgetlanguage_guid: XQW.Guid;
  msdyn_offlinewidgetsubtitle: string;
  msdyn_offlinewidgetthemecolor: msdyn_widgetthemecolor;
  msdyn_offlinewidgettitle: string;
  msdyn_operatinghourid_guid: XQW.Guid;
  msdyn_portalurl: string;
  msdyn_positioninqueue_enabled: boolean;
  msdyn_postchatenabled: boolean;
  msdyn_postconversationsurvey_guid: XQW.Guid;
  msdyn_postconversationsurveyenable: boolean;
  msdyn_postconversationsurveymessagetext: string;
  msdyn_postconversationsurveymode: msdyn_postconversationsurveymode;
  msdyn_prechatenabled: boolean;
  msdyn_prechatquestionnaireauthenticated_guid: XQW.Guid;
  msdyn_prechatquestionnaireunauthenticated_guid: XQW.Guid;
  msdyn_proactivechatenabled: boolean;
  msdyn_redirectionurl: string;
  msdyn_requestvisitorlocation: boolean;
  msdyn_screensharingprovider: string;
  msdyn_showagentname: boolean;
  msdyn_showwidgetduringofflinehours: boolean;
  msdyn_timetoreconnectwithpreviousagent: number;
  msdyn_widgetappid: string;
  msdyn_widgetlocale_guid: XQW.Guid;
  msdyn_widgetposition: msdyn_widgetposition;
  msdyn_widgetsnippet: string;
  msdyn_widgetsoundnotification: boolean;
  msdyn_widgetsubtitle: string;
  msdyn_widgetthemecolor: msdyn_widgetthemecolor;
  msdyn_widgettitle: string;
  msdyn_widgetvisualnotification: boolean;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_livechatconfig_statecode;
  statuscode: msdyn_livechatconfig_statuscode;
  timezoneruleversionnumber: number;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_livechatconfig_Expand {
  createdby: WebExpand<msdyn_livechatconfig_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_livechatconfig_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_livechatconfig_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_livechatconfig_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_AuthsettingsId: WebExpand<msdyn_livechatconfig_Expand, msdyn_authenticationsettings_Select, msdyn_authenticationsettings_Filter, { msdyn_AuthsettingsId: msdyn_authenticationsettings_Result }>;
  msdyn_PostConversationSurvey: WebExpand<msdyn_livechatconfig_Expand, msfp_survey_Select, msfp_survey_Filter, { msdyn_PostConversationSurvey: msfp_survey_Result }>;
  msdyn_WidgetLocale: WebExpand<msdyn_livechatconfig_Expand, msdyn_chatwidgetlanguage_Select, msdyn_chatwidgetlanguage_Filter, { msdyn_WidgetLocale: msdyn_chatwidgetlanguage_Result }>;
  msdyn_livechatconfig_AsyncOperations: WebExpand<msdyn_livechatconfig_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_livechatconfig_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_livechatconfig_BulkDeleteFailures: WebExpand<msdyn_livechatconfig_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_livechatconfig_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_livechatconfig_MailboxTrackingFolders: WebExpand<msdyn_livechatconfig_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_livechatconfig_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_livechatconfig_PrincipalObjectAttributeAccesses: WebExpand<msdyn_livechatconfig_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_livechatconfig_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_livechatconfig_ProcessSession: WebExpand<msdyn_livechatconfig_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_livechatconfig_ProcessSession: ProcessSession_Result[] }>;
  msdyn_livechatconfig_SyncErrors: WebExpand<msdyn_livechatconfig_Expand, SyncError_Select, SyncError_Filter, { msdyn_livechatconfig_SyncErrors: SyncError_Result[] }>;
  msdyn_livechatconfig_UserEntityInstanceDatas: WebExpand<msdyn_livechatconfig_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_livechatconfig_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_livechatconfig_msdyn_ocsystemmessage: WebExpand<msdyn_livechatconfig_Expand, msdyn_ocsystemmessage_Select, msdyn_ocsystemmessage_Filter, { msdyn_livechatconfig_msdyn_ocsystemmessage: msdyn_ocsystemmessage_Result[] }>;
  msdyn_livechatconfig_msdyn_questionsequence: WebExpand<msdyn_livechatconfig_Expand, msdyn_questionsequence_Select, msdyn_questionsequence_Filter, { msdyn_livechatconfig_msdyn_questionsequence: msdyn_questionsequence_Result[] }>;
  msdyn_liveworkstreamid: WebExpand<msdyn_livechatconfig_Expand, msdyn_liveworkstream_Select, msdyn_liveworkstream_Filter, { msdyn_liveworkstreamid: msdyn_liveworkstream_Result }>;
  msdyn_msdyn_livechatconfig_msdyn_chatquestionnaireresponse: WebExpand<msdyn_livechatconfig_Expand, msdyn_chatquestionnaireresponse_Select, msdyn_chatquestionnaireresponse_Filter, { msdyn_msdyn_livechatconfig_msdyn_chatquestionnaireresponse: msdyn_chatquestionnaireresponse_Result[] }>;
  msdyn_msdyn_livechatconfig_msdyn_livechatwidgetlocation_livechatconfigid: WebExpand<msdyn_livechatconfig_Expand, msdyn_livechatwidgetlocation_Select, msdyn_livechatwidgetlocation_Filter, { msdyn_msdyn_livechatconfig_msdyn_livechatwidgetlocation_livechatconfigid: msdyn_livechatwidgetlocation_Result[] }>;
  msdyn_ocWidgetLanguage: WebExpand<msdyn_livechatconfig_Expand, msdyn_oclanguage_Select, msdyn_oclanguage_Filter, { msdyn_ocWidgetLanguage: msdyn_oclanguage_Result }>;
  msdyn_oc_geolocationprovider: WebExpand<msdyn_livechatconfig_Expand, msdyn_oc_geolocationprovider_Select, msdyn_oc_geolocationprovider_Filter, { msdyn_oc_geolocationprovider: msdyn_oc_geolocationprovider_Result }>;
  msdyn_operatinghourid: WebExpand<msdyn_livechatconfig_Expand, msdyn_operatinghour_Select, msdyn_operatinghour_Filter, { msdyn_operatinghourid: msdyn_operatinghour_Result }>;
  msdyn_prechatquestionnaireauthenticated: WebExpand<msdyn_livechatconfig_Expand, msdyn_questionsequence_Select, msdyn_questionsequence_Filter, { msdyn_prechatquestionnaireauthenticated: msdyn_questionsequence_Result }>;
  msdyn_prechatquestionnaireunauthenticated: WebExpand<msdyn_livechatconfig_Expand, msdyn_questionsequence_Select, msdyn_questionsequence_Filter, { msdyn_prechatquestionnaireunauthenticated: msdyn_questionsequence_Result }>;
  ownerid: WebExpand<msdyn_livechatconfig_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_livechatconfig_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_livechatconfig_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_livechatconfig_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
}
interface msdyn_livechatconfig_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_agentdisplayname_formatted?: string;
  msdyn_authsettingsid_formatted?: string;
  msdyn_callingoptions_formatted?: string;
  msdyn_conversationmode_formatted?: string;
  msdyn_language_formatted?: string;
  msdyn_liveworkstreamid_formatted?: string;
  msdyn_oc_geolocationprovider_formatted?: string;
  msdyn_ocwidgetlanguage_formatted?: string;
  msdyn_offlinewidgetthemecolor_formatted?: string;
  msdyn_operatinghourid_formatted?: string;
  msdyn_postconversationsurvey_formatted?: string;
  msdyn_postconversationsurveymode_formatted?: string;
  msdyn_prechatquestionnaireauthenticated_formatted?: string;
  msdyn_prechatquestionnaireunauthenticated_formatted?: string;
  msdyn_widgetlocale_formatted?: string;
  msdyn_widgetposition_formatted?: string;
  msdyn_widgetthemecolor_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface msdyn_livechatconfig_Result extends msdyn_livechatconfig_Base, msdyn_livechatconfig_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_authsettingsid_guid: string | null;
  msdyn_liveworkstreamid_guid: string | null;
  msdyn_oc_geolocationprovider_guid: string | null;
  msdyn_ocwidgetlanguage_guid: string | null;
  msdyn_operatinghourid_guid: string | null;
  msdyn_postconversationsurvey_guid: string | null;
  msdyn_prechatquestionnaireauthenticated_guid: string | null;
  msdyn_prechatquestionnaireunauthenticated_guid: string | null;
  msdyn_widgetlocale_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface msdyn_livechatconfig_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_AuthsettingsId: WebMappingRetrieve<msdyn_authenticationsettings_Select,msdyn_authenticationsettings_Expand,msdyn_authenticationsettings_Filter,msdyn_authenticationsettings_Fixed,msdyn_authenticationsettings_Result,msdyn_authenticationsettings_FormattedResult>;
  msdyn_PostConversationSurvey: WebMappingRetrieve<msfp_survey_Select,msfp_survey_Expand,msfp_survey_Filter,msfp_survey_Fixed,msfp_survey_Result,msfp_survey_FormattedResult>;
  msdyn_WidgetLocale: WebMappingRetrieve<msdyn_chatwidgetlanguage_Select,msdyn_chatwidgetlanguage_Expand,msdyn_chatwidgetlanguage_Filter,msdyn_chatwidgetlanguage_Fixed,msdyn_chatwidgetlanguage_Result,msdyn_chatwidgetlanguage_FormattedResult>;
  msdyn_liveworkstreamid: WebMappingRetrieve<msdyn_liveworkstream_Select,msdyn_liveworkstream_Expand,msdyn_liveworkstream_Filter,msdyn_liveworkstream_Fixed,msdyn_liveworkstream_Result,msdyn_liveworkstream_FormattedResult>;
  msdyn_ocWidgetLanguage: WebMappingRetrieve<msdyn_oclanguage_Select,msdyn_oclanguage_Expand,msdyn_oclanguage_Filter,msdyn_oclanguage_Fixed,msdyn_oclanguage_Result,msdyn_oclanguage_FormattedResult>;
  msdyn_oc_geolocationprovider: WebMappingRetrieve<msdyn_oc_geolocationprovider_Select,msdyn_oc_geolocationprovider_Expand,msdyn_oc_geolocationprovider_Filter,msdyn_oc_geolocationprovider_Fixed,msdyn_oc_geolocationprovider_Result,msdyn_oc_geolocationprovider_FormattedResult>;
  msdyn_operatinghourid: WebMappingRetrieve<msdyn_operatinghour_Select,msdyn_operatinghour_Expand,msdyn_operatinghour_Filter,msdyn_operatinghour_Fixed,msdyn_operatinghour_Result,msdyn_operatinghour_FormattedResult>;
  msdyn_prechatquestionnaireauthenticated: WebMappingRetrieve<msdyn_questionsequence_Select,msdyn_questionsequence_Expand,msdyn_questionsequence_Filter,msdyn_questionsequence_Fixed,msdyn_questionsequence_Result,msdyn_questionsequence_FormattedResult>;
  msdyn_prechatquestionnaireunauthenticated: WebMappingRetrieve<msdyn_questionsequence_Select,msdyn_questionsequence_Expand,msdyn_questionsequence_Filter,msdyn_questionsequence_Fixed,msdyn_questionsequence_Result,msdyn_questionsequence_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface msdyn_livechatconfig_RelatedMany {
  msdyn_livechatconfig_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_livechatconfig_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_livechatconfig_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_livechatconfig_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_livechatconfig_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_livechatconfig_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_livechatconfig_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_livechatconfig_msdyn_ocsystemmessage: WebMappingRetrieve<msdyn_ocsystemmessage_Select,msdyn_ocsystemmessage_Expand,msdyn_ocsystemmessage_Filter,msdyn_ocsystemmessage_Fixed,msdyn_ocsystemmessage_Result,msdyn_ocsystemmessage_FormattedResult>;
  msdyn_livechatconfig_msdyn_questionsequence: WebMappingRetrieve<msdyn_questionsequence_Select,msdyn_questionsequence_Expand,msdyn_questionsequence_Filter,msdyn_questionsequence_Fixed,msdyn_questionsequence_Result,msdyn_questionsequence_FormattedResult>;
  msdyn_msdyn_livechatconfig_msdyn_chatquestionnaireresponse: WebMappingRetrieve<msdyn_chatquestionnaireresponse_Select,msdyn_chatquestionnaireresponse_Expand,msdyn_chatquestionnaireresponse_Filter,msdyn_chatquestionnaireresponse_Fixed,msdyn_chatquestionnaireresponse_Result,msdyn_chatquestionnaireresponse_FormattedResult>;
  msdyn_msdyn_livechatconfig_msdyn_livechatwidgetlocation_livechatconfigid: WebMappingRetrieve<msdyn_livechatwidgetlocation_Select,msdyn_livechatwidgetlocation_Expand,msdyn_livechatwidgetlocation_Filter,msdyn_livechatwidgetlocation_Fixed,msdyn_livechatwidgetlocation_Result,msdyn_livechatwidgetlocation_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_livechatconfigs: WebMappingRetrieve<msdyn_livechatconfig_Select,msdyn_livechatconfig_Expand,msdyn_livechatconfig_Filter,msdyn_livechatconfig_Fixed,msdyn_livechatconfig_Result,msdyn_livechatconfig_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_livechatconfigs: WebMappingRelated<msdyn_livechatconfig_RelatedOne,msdyn_livechatconfig_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_livechatconfigs: WebMappingCUDA<msdyn_livechatconfig_Create,msdyn_livechatconfig_Update,msdyn_livechatconfig_Select>;
}
