interface msdyn_rma_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_autonumbering?: string | null;
  msdyn_daterequested?: Date | null;
  msdyn_description?: string | null;
  msdyn_eta?: Date | null;
  msdyn_name?: string | null;
  msdyn_packagingtrackingno?: string | null;
  msdyn_processingaction?: msdyn_rmaprocessingaction | null;
  msdyn_referenceno?: string | null;
  msdyn_rmaid?: string | null;
  msdyn_shippingtrackingno?: string | null;
  msdyn_systemstatus?: msdyn_rmasystemstatus | null;
  msdyn_taxable?: boolean | null;
  msdyn_totalamount?: number | null;
  msdyn_totalamount_base?: number | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_rma_statecode | null;
  statuscode?: msdyn_rma_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_rma_Relationships {
  msdyn_msdyn_rma_msdyn_rmaproduct_RMA?: msdyn_rmaproduct_Result[] | null;
  msdyn_msdyn_rma_msdyn_rmareceipt_RMA?: msdyn_rmareceipt_Result[] | null;
  msdyn_msdyn_rma_msdyn_rmareceiptproduct_RMA?: msdyn_rmareceiptproduct_Result[] | null;
  msdyn_msdyn_rma_msdyn_rtv_OriginatingRMA?: msdyn_rtv_Result[] | null;
  msdyn_msdyn_rma_msdyn_rtvproduct_RMA?: msdyn_rtvproduct_Result[] | null;
  msdyn_rma_ActivityPointers?: ActivityPointer_Result[] | null;
  msdyn_rma_Annotations?: Annotation_Result[] | null;
  msdyn_rma_Appointments?: Appointment_Result[] | null;
  msdyn_rma_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_rma_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_rma_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_rma_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_rma_Emails?: Email_Result[] | null;
  msdyn_rma_Faxes?: Fax_Result[] | null;
  msdyn_rma_Letters?: Letter_Result[] | null;
  msdyn_rma_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_rma_PhoneCalls?: PhoneCall_Result[] | null;
  msdyn_rma_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_rma_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_rma_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  msdyn_rma_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_rma_SharePointDocumentLocations?: SharePointDocumentLocation_Result[] | null;
  msdyn_rma_SharePointDocuments?: SharePointDocument_Result[] | null;
  msdyn_rma_SocialActivities?: SocialActivity_Result[] | null;
  msdyn_rma_SyncErrors?: SyncError_Result[] | null;
  msdyn_rma_Tasks?: Task_Result[] | null;
  msdyn_rma_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_rma_connections1?: Connection_Result[] | null;
  msdyn_rma_connections2?: Connection_Result[] | null;
  msdyn_rma_msdyn_approvals?: msdyn_approval_Result[] | null;
  msdyn_rma_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  msdyn_rma_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_rma_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_rma_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  msdyn_rma_msfp_alerts?: msfp_alert_Result[] | null;
  msdyn_rma_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  msdyn_rma_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
}
interface msdyn_rma extends msdyn_rma_Base, msdyn_rma_Relationships {
  msdyn_approvedby_bind$systemusers?: string | null;
  msdyn_billingaccount_bind$accounts?: string | null;
  msdyn_pricelist_bind$pricelevels?: string | null;
  msdyn_requestedbycontact_bind$contacts?: string | null;
  msdyn_serviceaccount_bind$accounts?: string | null;
  msdyn_shipvia_bind$msdyn_shipvias?: string | null;
  msdyn_substatus_bind$msdyn_rmasubstatuses?: string | null;
  msdyn_taxcode_bind$msdyn_taxcodes?: string | null;
  msdyn_workorder_bind$msdyn_workorders?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface msdyn_rma_Create extends msdyn_rma {
}
interface msdyn_rma_Update extends msdyn_rma {
}
interface msdyn_rma_Select {
  createdby_guid: WebAttribute<msdyn_rma_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_rma_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_rma_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_rma_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_rma_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_rma_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_rma_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_rma_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_approvedby_guid: WebAttribute<msdyn_rma_Select, { msdyn_approvedby_guid: string | null }, { msdyn_approvedby_formatted?: string }>;
  msdyn_autonumbering: WebAttribute<msdyn_rma_Select, { msdyn_autonumbering: string | null }, {  }>;
  msdyn_billingaccount_guid: WebAttribute<msdyn_rma_Select, { msdyn_billingaccount_guid: string | null }, { msdyn_billingaccount_formatted?: string }>;
  msdyn_daterequested: WebAttribute<msdyn_rma_Select, { msdyn_daterequested: Date | null }, { msdyn_daterequested_formatted?: string }>;
  msdyn_description: WebAttribute<msdyn_rma_Select, { msdyn_description: string | null }, {  }>;
  msdyn_eta: WebAttribute<msdyn_rma_Select, { msdyn_eta: Date | null }, { msdyn_eta_formatted?: string }>;
  msdyn_name: WebAttribute<msdyn_rma_Select, { msdyn_name: string | null }, {  }>;
  msdyn_packagingtrackingno: WebAttribute<msdyn_rma_Select, { msdyn_packagingtrackingno: string | null }, {  }>;
  msdyn_pricelist_guid: WebAttribute<msdyn_rma_Select, { msdyn_pricelist_guid: string | null }, { msdyn_pricelist_formatted?: string }>;
  msdyn_processingaction: WebAttribute<msdyn_rma_Select, { msdyn_processingaction: msdyn_rmaprocessingaction | null }, { msdyn_processingaction_formatted?: string }>;
  msdyn_referenceno: WebAttribute<msdyn_rma_Select, { msdyn_referenceno: string | null }, {  }>;
  msdyn_requestedbycontact_guid: WebAttribute<msdyn_rma_Select, { msdyn_requestedbycontact_guid: string | null }, { msdyn_requestedbycontact_formatted?: string }>;
  msdyn_rmaid: WebAttribute<msdyn_rma_Select, { msdyn_rmaid: string | null }, {  }>;
  msdyn_serviceaccount_guid: WebAttribute<msdyn_rma_Select, { msdyn_serviceaccount_guid: string | null }, { msdyn_serviceaccount_formatted?: string }>;
  msdyn_shippingtrackingno: WebAttribute<msdyn_rma_Select, { msdyn_shippingtrackingno: string | null }, {  }>;
  msdyn_shipvia_guid: WebAttribute<msdyn_rma_Select, { msdyn_shipvia_guid: string | null }, { msdyn_shipvia_formatted?: string }>;
  msdyn_substatus_guid: WebAttribute<msdyn_rma_Select, { msdyn_substatus_guid: string | null }, { msdyn_substatus_formatted?: string }>;
  msdyn_systemstatus: WebAttribute<msdyn_rma_Select, { msdyn_systemstatus: msdyn_rmasystemstatus | null }, { msdyn_systemstatus_formatted?: string }>;
  msdyn_taxable: WebAttribute<msdyn_rma_Select, { msdyn_taxable: boolean | null }, {  }>;
  msdyn_taxcode_guid: WebAttribute<msdyn_rma_Select, { msdyn_taxcode_guid: string | null }, { msdyn_taxcode_formatted?: string }>;
  msdyn_totalamount: WebAttribute<msdyn_rma_Select, { msdyn_totalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalamount_base: WebAttribute<msdyn_rma_Select, { msdyn_totalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_workorder_guid: WebAttribute<msdyn_rma_Select, { msdyn_workorder_guid: string | null }, { msdyn_workorder_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_rma_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_rma_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_rma_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_rma_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_rma_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_rma_Select, { statecode: msdyn_rma_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_rma_Select, { statuscode: msdyn_rma_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_rma_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_rma_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<msdyn_rma_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_rma_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_rma_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_approvedby_guid: XQW.Guid;
  msdyn_autonumbering: string;
  msdyn_billingaccount_guid: XQW.Guid;
  msdyn_daterequested: Date;
  msdyn_description: string;
  msdyn_eta: Date;
  msdyn_name: string;
  msdyn_packagingtrackingno: string;
  msdyn_pricelist_guid: XQW.Guid;
  msdyn_processingaction: msdyn_rmaprocessingaction;
  msdyn_referenceno: string;
  msdyn_requestedbycontact_guid: XQW.Guid;
  msdyn_rmaid: XQW.Guid;
  msdyn_serviceaccount_guid: XQW.Guid;
  msdyn_shippingtrackingno: string;
  msdyn_shipvia_guid: XQW.Guid;
  msdyn_substatus_guid: XQW.Guid;
  msdyn_systemstatus: msdyn_rmasystemstatus;
  msdyn_taxable: boolean;
  msdyn_taxcode_guid: XQW.Guid;
  msdyn_totalamount: number;
  msdyn_totalamount_base: number;
  msdyn_workorder_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_rma_statecode;
  statuscode: msdyn_rma_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_rma_Expand {
  createdby: WebExpand<msdyn_rma_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_rma_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_rma_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_rma_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_approvedby: WebExpand<msdyn_rma_Expand, SystemUser_Select, SystemUser_Filter, { msdyn_approvedby: SystemUser_Result }>;
  msdyn_billingaccount: WebExpand<msdyn_rma_Expand, Account_Select, Account_Filter, { msdyn_billingaccount: Account_Result }>;
  msdyn_msdyn_rma_msdyn_rmaproduct_RMA: WebExpand<msdyn_rma_Expand, msdyn_rmaproduct_Select, msdyn_rmaproduct_Filter, { msdyn_msdyn_rma_msdyn_rmaproduct_RMA: msdyn_rmaproduct_Result[] }>;
  msdyn_msdyn_rma_msdyn_rmareceipt_RMA: WebExpand<msdyn_rma_Expand, msdyn_rmareceipt_Select, msdyn_rmareceipt_Filter, { msdyn_msdyn_rma_msdyn_rmareceipt_RMA: msdyn_rmareceipt_Result[] }>;
  msdyn_msdyn_rma_msdyn_rmareceiptproduct_RMA: WebExpand<msdyn_rma_Expand, msdyn_rmareceiptproduct_Select, msdyn_rmareceiptproduct_Filter, { msdyn_msdyn_rma_msdyn_rmareceiptproduct_RMA: msdyn_rmareceiptproduct_Result[] }>;
  msdyn_msdyn_rma_msdyn_rtv_OriginatingRMA: WebExpand<msdyn_rma_Expand, msdyn_rtv_Select, msdyn_rtv_Filter, { msdyn_msdyn_rma_msdyn_rtv_OriginatingRMA: msdyn_rtv_Result[] }>;
  msdyn_msdyn_rma_msdyn_rtvproduct_RMA: WebExpand<msdyn_rma_Expand, msdyn_rtvproduct_Select, msdyn_rtvproduct_Filter, { msdyn_msdyn_rma_msdyn_rtvproduct_RMA: msdyn_rtvproduct_Result[] }>;
  msdyn_pricelist: WebExpand<msdyn_rma_Expand, PriceLevel_Select, PriceLevel_Filter, { msdyn_pricelist: PriceLevel_Result }>;
  msdyn_requestedbycontact: WebExpand<msdyn_rma_Expand, Contact_Select, Contact_Filter, { msdyn_requestedbycontact: Contact_Result }>;
  msdyn_rma_ActivityPointers: WebExpand<msdyn_rma_Expand, ActivityPointer_Select, ActivityPointer_Filter, { msdyn_rma_ActivityPointers: ActivityPointer_Result[] }>;
  msdyn_rma_Annotations: WebExpand<msdyn_rma_Expand, Annotation_Select, Annotation_Filter, { msdyn_rma_Annotations: Annotation_Result[] }>;
  msdyn_rma_Appointments: WebExpand<msdyn_rma_Expand, Appointment_Select, Appointment_Filter, { msdyn_rma_Appointments: Appointment_Result[] }>;
  msdyn_rma_AsyncOperations: WebExpand<msdyn_rma_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_rma_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_rma_BulkDeleteFailures: WebExpand<msdyn_rma_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_rma_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_rma_DuplicateBaseRecord: WebExpand<msdyn_rma_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_rma_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_rma_DuplicateMatchingRecord: WebExpand<msdyn_rma_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_rma_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_rma_Emails: WebExpand<msdyn_rma_Expand, Email_Select, Email_Filter, { msdyn_rma_Emails: Email_Result[] }>;
  msdyn_rma_Faxes: WebExpand<msdyn_rma_Expand, Fax_Select, Fax_Filter, { msdyn_rma_Faxes: Fax_Result[] }>;
  msdyn_rma_Letters: WebExpand<msdyn_rma_Expand, Letter_Select, Letter_Filter, { msdyn_rma_Letters: Letter_Result[] }>;
  msdyn_rma_MailboxTrackingFolders: WebExpand<msdyn_rma_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_rma_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_rma_PhoneCalls: WebExpand<msdyn_rma_Expand, PhoneCall_Select, PhoneCall_Filter, { msdyn_rma_PhoneCalls: PhoneCall_Result[] }>;
  msdyn_rma_PrincipalObjectAttributeAccesses: WebExpand<msdyn_rma_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_rma_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_rma_ProcessSession: WebExpand<msdyn_rma_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_rma_ProcessSession: ProcessSession_Result[] }>;
  msdyn_rma_RecurringAppointmentMasters: WebExpand<msdyn_rma_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { msdyn_rma_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  msdyn_rma_ServiceAppointments: WebExpand<msdyn_rma_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_rma_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_rma_SharePointDocumentLocations: WebExpand<msdyn_rma_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { msdyn_rma_SharePointDocumentLocations: SharePointDocumentLocation_Result[] }>;
  msdyn_rma_SharePointDocuments: WebExpand<msdyn_rma_Expand, SharePointDocument_Select, SharePointDocument_Filter, { msdyn_rma_SharePointDocuments: SharePointDocument_Result[] }>;
  msdyn_rma_SocialActivities: WebExpand<msdyn_rma_Expand, SocialActivity_Select, SocialActivity_Filter, { msdyn_rma_SocialActivities: SocialActivity_Result[] }>;
  msdyn_rma_SyncErrors: WebExpand<msdyn_rma_Expand, SyncError_Select, SyncError_Filter, { msdyn_rma_SyncErrors: SyncError_Result[] }>;
  msdyn_rma_Tasks: WebExpand<msdyn_rma_Expand, Task_Select, Task_Filter, { msdyn_rma_Tasks: Task_Result[] }>;
  msdyn_rma_UserEntityInstanceDatas: WebExpand<msdyn_rma_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_rma_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_rma_connections1: WebExpand<msdyn_rma_Expand, Connection_Select, Connection_Filter, { msdyn_rma_connections1: Connection_Result[] }>;
  msdyn_rma_connections2: WebExpand<msdyn_rma_Expand, Connection_Select, Connection_Filter, { msdyn_rma_connections2: Connection_Result[] }>;
  msdyn_rma_msdyn_approvals: WebExpand<msdyn_rma_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_rma_msdyn_approvals: msdyn_approval_Result[] }>;
  msdyn_rma_msdyn_bookingalerts: WebExpand<msdyn_rma_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_rma_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  msdyn_rma_msdyn_ocliveworkitems: WebExpand<msdyn_rma_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_rma_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  msdyn_rma_msdyn_ocoutboundmessages: WebExpand<msdyn_rma_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_rma_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_rma_msdyn_ocsessions: WebExpand<msdyn_rma_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_rma_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  msdyn_rma_msfp_alerts: WebExpand<msdyn_rma_Expand, msfp_alert_Select, msfp_alert_Filter, { msdyn_rma_msfp_alerts: msfp_alert_Result[] }>;
  msdyn_rma_msfp_surveyinvites: WebExpand<msdyn_rma_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msdyn_rma_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  msdyn_rma_msfp_surveyresponses: WebExpand<msdyn_rma_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msdyn_rma_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  msdyn_serviceaccount: WebExpand<msdyn_rma_Expand, Account_Select, Account_Filter, { msdyn_serviceaccount: Account_Result }>;
  msdyn_shipvia: WebExpand<msdyn_rma_Expand, msdyn_shipvia_Select, msdyn_shipvia_Filter, { msdyn_shipvia: msdyn_shipvia_Result }>;
  msdyn_substatus: WebExpand<msdyn_rma_Expand, msdyn_rmasubstatus_Select, msdyn_rmasubstatus_Filter, { msdyn_substatus: msdyn_rmasubstatus_Result }>;
  msdyn_taxcode: WebExpand<msdyn_rma_Expand, msdyn_taxcode_Select, msdyn_taxcode_Filter, { msdyn_taxcode: msdyn_taxcode_Result }>;
  msdyn_workorder: WebExpand<msdyn_rma_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_workorder: msdyn_workorder_Result }>;
  ownerid: WebExpand<msdyn_rma_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_rma_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_rma_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_rma_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  transactioncurrencyid: WebExpand<msdyn_rma_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface msdyn_rma_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_approvedby_formatted?: string;
  msdyn_billingaccount_formatted?: string;
  msdyn_daterequested_formatted?: string;
  msdyn_eta_formatted?: string;
  msdyn_pricelist_formatted?: string;
  msdyn_processingaction_formatted?: string;
  msdyn_requestedbycontact_formatted?: string;
  msdyn_serviceaccount_formatted?: string;
  msdyn_shipvia_formatted?: string;
  msdyn_substatus_formatted?: string;
  msdyn_systemstatus_formatted?: string;
  msdyn_taxcode_formatted?: string;
  msdyn_totalamount_base_formatted?: string;
  msdyn_totalamount_formatted?: string;
  msdyn_workorder_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface msdyn_rma_Result extends msdyn_rma_Base, msdyn_rma_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_approvedby_guid: string | null;
  msdyn_billingaccount_guid: string | null;
  msdyn_pricelist_guid: string | null;
  msdyn_requestedbycontact_guid: string | null;
  msdyn_serviceaccount_guid: string | null;
  msdyn_shipvia_guid: string | null;
  msdyn_substatus_guid: string | null;
  msdyn_taxcode_guid: string | null;
  msdyn_workorder_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface msdyn_rma_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_approvedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_billingaccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_pricelist: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  msdyn_requestedbycontact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  msdyn_serviceaccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_shipvia: WebMappingRetrieve<msdyn_shipvia_Select,msdyn_shipvia_Expand,msdyn_shipvia_Filter,msdyn_shipvia_Fixed,msdyn_shipvia_Result,msdyn_shipvia_FormattedResult>;
  msdyn_substatus: WebMappingRetrieve<msdyn_rmasubstatus_Select,msdyn_rmasubstatus_Expand,msdyn_rmasubstatus_Filter,msdyn_rmasubstatus_Fixed,msdyn_rmasubstatus_Result,msdyn_rmasubstatus_FormattedResult>;
  msdyn_taxcode: WebMappingRetrieve<msdyn_taxcode_Select,msdyn_taxcode_Expand,msdyn_taxcode_Filter,msdyn_taxcode_Fixed,msdyn_taxcode_Result,msdyn_taxcode_FormattedResult>;
  msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface msdyn_rma_RelatedMany {
  msdyn_msdyn_rma_msdyn_rmaproduct_RMA: WebMappingRetrieve<msdyn_rmaproduct_Select,msdyn_rmaproduct_Expand,msdyn_rmaproduct_Filter,msdyn_rmaproduct_Fixed,msdyn_rmaproduct_Result,msdyn_rmaproduct_FormattedResult>;
  msdyn_msdyn_rma_msdyn_rmareceipt_RMA: WebMappingRetrieve<msdyn_rmareceipt_Select,msdyn_rmareceipt_Expand,msdyn_rmareceipt_Filter,msdyn_rmareceipt_Fixed,msdyn_rmareceipt_Result,msdyn_rmareceipt_FormattedResult>;
  msdyn_msdyn_rma_msdyn_rmareceiptproduct_RMA: WebMappingRetrieve<msdyn_rmareceiptproduct_Select,msdyn_rmareceiptproduct_Expand,msdyn_rmareceiptproduct_Filter,msdyn_rmareceiptproduct_Fixed,msdyn_rmareceiptproduct_Result,msdyn_rmareceiptproduct_FormattedResult>;
  msdyn_msdyn_rma_msdyn_rtv_OriginatingRMA: WebMappingRetrieve<msdyn_rtv_Select,msdyn_rtv_Expand,msdyn_rtv_Filter,msdyn_rtv_Fixed,msdyn_rtv_Result,msdyn_rtv_FormattedResult>;
  msdyn_msdyn_rma_msdyn_rtvproduct_RMA: WebMappingRetrieve<msdyn_rtvproduct_Select,msdyn_rtvproduct_Expand,msdyn_rtvproduct_Filter,msdyn_rtvproduct_Fixed,msdyn_rtvproduct_Result,msdyn_rtvproduct_FormattedResult>;
  msdyn_rma_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  msdyn_rma_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_rma_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_rma_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_rma_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_rma_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_rma_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_rma_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_rma_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  msdyn_rma_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  msdyn_rma_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_rma_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  msdyn_rma_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_rma_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_rma_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  msdyn_rma_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_rma_SharePointDocumentLocations: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  msdyn_rma_SharePointDocuments: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  msdyn_rma_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  msdyn_rma_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_rma_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  msdyn_rma_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_rma_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_rma_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_rma_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_rma_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_rma_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_rma_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_rma_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msdyn_rma_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msdyn_rma_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msdyn_rma_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_rmas: WebMappingRetrieve<msdyn_rma_Select,msdyn_rma_Expand,msdyn_rma_Filter,msdyn_rma_Fixed,msdyn_rma_Result,msdyn_rma_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_rmas: WebMappingRelated<msdyn_rma_RelatedOne,msdyn_rma_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_rmas: WebMappingCUDA<msdyn_rma_Create,msdyn_rma_Update,msdyn_rma_Select>;
}
