interface msdyn_agreement_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_agreementdetails?: string | null;
  msdyn_agreementid?: string | null;
  msdyn_agreementrecordgeneration?: Date | null;
  msdyn_autonumbering?: string | null;
  msdyn_childindex?: number | null;
  msdyn_datecanceled?: Date | null;
  msdyn_description?: string | null;
  msdyn_duration?: number | null;
  msdyn_enddate?: Date | null;
  msdyn_name?: string | null;
  msdyn_processstartedon?: Date | null;
  msdyn_startdate?: Date | null;
  msdyn_systemstatus?: msdyn_agreementsystemstatus | null;
  msdyn_taxable?: boolean | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  stageid?: string | null;
  statecode?: msdyn_agreement_statecode | null;
  statuscode?: msdyn_agreement_statuscode | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_agreement_Relationships {
  bpf_msdyn_agreement_msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3?: msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_Result[] | null;
  msdyn_agreement_ActivityPointers?: ActivityPointer_Result[] | null;
  msdyn_agreement_Annotations?: Annotation_Result[] | null;
  msdyn_agreement_Appointments?: Appointment_Result[] | null;
  msdyn_agreement_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_agreement_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_agreement_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_agreement_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_agreement_Emails?: Email_Result[] | null;
  msdyn_agreement_Faxes?: Fax_Result[] | null;
  msdyn_agreement_Letters?: Letter_Result[] | null;
  msdyn_agreement_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_agreement_PhoneCalls?: PhoneCall_Result[] | null;
  msdyn_agreement_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_agreement_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_agreement_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  msdyn_agreement_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_agreement_SharePointDocumentLocations?: SharePointDocumentLocation_Result[] | null;
  msdyn_agreement_SharePointDocuments?: SharePointDocument_Result[] | null;
  msdyn_agreement_SocialActivities?: SocialActivity_Result[] | null;
  msdyn_agreement_SyncErrors?: SyncError_Result[] | null;
  msdyn_agreement_Tasks?: Task_Result[] | null;
  msdyn_agreement_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_agreement_connections1?: Connection_Result[] | null;
  msdyn_agreement_connections2?: Connection_Result[] | null;
  msdyn_agreement_msdyn_approvals?: msdyn_approval_Result[] | null;
  msdyn_agreement_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  msdyn_agreement_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_agreement_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_agreement_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  msdyn_agreement_msfp_alerts?: msfp_alert_Result[] | null;
  msdyn_agreement_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  msdyn_agreement_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  msdyn_msdyn_agreement_invoicedetail_Agreement?: InvoiceDetail_Result[] | null;
  msdyn_msdyn_agreement_msdyn_actual_Agreement?: msdyn_actual_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreement_OriginatingAgreement?: msdyn_agreement_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreementbookingdate_Agreement?: msdyn_agreementbookingdate_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreementbookingincident_Agreement?: msdyn_agreementbookingincident_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreementbookingproduct_Agreement?: msdyn_agreementbookingproduct_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreementbookingservice_Agreement?: msdyn_agreementbookingservice_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreementbookingservicetask_Agreement?: msdyn_agreementbookingservicetask_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreementbookingsetup_Agreement?: msdyn_agreementbookingsetup_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreementinvoicedate_Agreement?: msdyn_agreementinvoicedate_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreementinvoiceproduct_Agreement?: msdyn_agreementinvoiceproduct_Result[] | null;
  msdyn_msdyn_agreement_msdyn_agreementinvoicesetup_Agreement?: msdyn_agreementinvoicesetup_Result[] | null;
  msdyn_msdyn_agreement_msdyn_workorder_Agreement?: msdyn_workorder_Result[] | null;
  msdyn_msdyn_agreement_quotedetail_Agreement?: QuoteDetail_Result[] | null;
  msdyn_msdyn_agreement_salesorderdetail_Agreement?: SalesOrderDetail_Result[] | null;
  msdyn_originatingagreement_msdyn_agreement?: msdyn_agreement_Result | null;
}
interface msdyn_agreement extends msdyn_agreement_Base, msdyn_agreement_Relationships {
  msdyn_billingaccount_bind$accounts?: string | null;
  msdyn_originatingagreement_msdyn_agreement_bind$msdyn_agreements?: string | null;
  msdyn_pricelist_bind$pricelevels?: string | null;
  msdyn_salestaxcode_bind$msdyn_taxcodes?: string | null;
  msdyn_serviceaccount_bind$accounts?: string | null;
  msdyn_serviceterritory_bind$territories?: string | null;
  msdyn_substatus_bind$msdyn_agreementsubstatuses?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  stageid_bind$processstages?: string | null;
}
interface msdyn_agreement_Create extends msdyn_agreement {
}
interface msdyn_agreement_Update extends msdyn_agreement {
}
interface msdyn_agreement_Select {
  createdby_guid: WebAttribute<msdyn_agreement_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_agreement_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_agreement_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<msdyn_agreement_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_agreement_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_agreement_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_agreement_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_agreementdetails: WebAttribute<msdyn_agreement_Select, { msdyn_agreementdetails: string | null }, {  }>;
  msdyn_agreementid: WebAttribute<msdyn_agreement_Select, { msdyn_agreementid: string | null }, {  }>;
  msdyn_agreementrecordgeneration: WebAttribute<msdyn_agreement_Select, { msdyn_agreementrecordgeneration: Date | null }, { msdyn_agreementrecordgeneration_formatted?: string }>;
  msdyn_autonumbering: WebAttribute<msdyn_agreement_Select, { msdyn_autonumbering: string | null }, {  }>;
  msdyn_billingaccount_guid: WebAttribute<msdyn_agreement_Select, { msdyn_billingaccount_guid: string | null }, { msdyn_billingaccount_formatted?: string }>;
  msdyn_childindex: WebAttribute<msdyn_agreement_Select, { msdyn_childindex: number | null }, {  }>;
  msdyn_datecanceled: WebAttribute<msdyn_agreement_Select, { msdyn_datecanceled: Date | null }, { msdyn_datecanceled_formatted?: string }>;
  msdyn_description: WebAttribute<msdyn_agreement_Select, { msdyn_description: string | null }, {  }>;
  msdyn_duration: WebAttribute<msdyn_agreement_Select, { msdyn_duration: number | null }, {  }>;
  msdyn_enddate: WebAttribute<msdyn_agreement_Select, { msdyn_enddate: Date | null }, { msdyn_enddate_formatted?: string }>;
  msdyn_name: WebAttribute<msdyn_agreement_Select, { msdyn_name: string | null }, {  }>;
  msdyn_originatingagreement_guid: WebAttribute<msdyn_agreement_Select, { msdyn_originatingagreement_guid: string | null }, { msdyn_originatingagreement_formatted?: string }>;
  msdyn_pricelist_guid: WebAttribute<msdyn_agreement_Select, { msdyn_pricelist_guid: string | null }, { msdyn_pricelist_formatted?: string }>;
  msdyn_processstartedon: WebAttribute<msdyn_agreement_Select, { msdyn_processstartedon: Date | null }, { msdyn_processstartedon_formatted?: string }>;
  msdyn_salestaxcode_guid: WebAttribute<msdyn_agreement_Select, { msdyn_salestaxcode_guid: string | null }, { msdyn_salestaxcode_formatted?: string }>;
  msdyn_serviceaccount_guid: WebAttribute<msdyn_agreement_Select, { msdyn_serviceaccount_guid: string | null }, { msdyn_serviceaccount_formatted?: string }>;
  msdyn_serviceterritory_guid: WebAttribute<msdyn_agreement_Select, { msdyn_serviceterritory_guid: string | null }, { msdyn_serviceterritory_formatted?: string }>;
  msdyn_startdate: WebAttribute<msdyn_agreement_Select, { msdyn_startdate: Date | null }, { msdyn_startdate_formatted?: string }>;
  msdyn_substatus_guid: WebAttribute<msdyn_agreement_Select, { msdyn_substatus_guid: string | null }, { msdyn_substatus_formatted?: string }>;
  msdyn_systemstatus: WebAttribute<msdyn_agreement_Select, { msdyn_systemstatus: msdyn_agreementsystemstatus | null }, { msdyn_systemstatus_formatted?: string }>;
  msdyn_taxable: WebAttribute<msdyn_agreement_Select, { msdyn_taxable: boolean | null }, {  }>;
  overriddencreatedon: WebAttribute<msdyn_agreement_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_agreement_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_agreement_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_agreement_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_agreement_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  processid: WebAttribute<msdyn_agreement_Select, { processid: string | null }, {  }>;
  stageid: WebAttribute<msdyn_agreement_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<msdyn_agreement_Select, { statecode: msdyn_agreement_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_agreement_Select, { statuscode: msdyn_agreement_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_agreement_Select, { timezoneruleversionnumber: number | null }, {  }>;
  traversedpath: WebAttribute<msdyn_agreement_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_agreement_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_agreement_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_agreement_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_agreementdetails: string;
  msdyn_agreementid: XQW.Guid;
  msdyn_agreementrecordgeneration: Date;
  msdyn_autonumbering: string;
  msdyn_billingaccount_guid: XQW.Guid;
  msdyn_childindex: number;
  msdyn_datecanceled: Date;
  msdyn_description: string;
  msdyn_duration: number;
  msdyn_enddate: Date;
  msdyn_name: string;
  msdyn_originatingagreement_guid: XQW.Guid;
  msdyn_pricelist_guid: XQW.Guid;
  msdyn_processstartedon: Date;
  msdyn_salestaxcode_guid: XQW.Guid;
  msdyn_serviceaccount_guid: XQW.Guid;
  msdyn_serviceterritory_guid: XQW.Guid;
  msdyn_startdate: Date;
  msdyn_substatus_guid: XQW.Guid;
  msdyn_systemstatus: msdyn_agreementsystemstatus;
  msdyn_taxable: boolean;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  processid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: msdyn_agreement_statecode;
  statuscode: msdyn_agreement_statuscode;
  timezoneruleversionnumber: number;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_agreement_Expand {
  bpf_msdyn_agreement_msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3: WebExpand<msdyn_agreement_Expand, msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_Select, msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_Filter, { bpf_msdyn_agreement_msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3: msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_Result[] }>;
  createdby: WebExpand<msdyn_agreement_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_agreement_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_agreement_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_agreement_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_agreement_ActivityPointers: WebExpand<msdyn_agreement_Expand, ActivityPointer_Select, ActivityPointer_Filter, { msdyn_agreement_ActivityPointers: ActivityPointer_Result[] }>;
  msdyn_agreement_Annotations: WebExpand<msdyn_agreement_Expand, Annotation_Select, Annotation_Filter, { msdyn_agreement_Annotations: Annotation_Result[] }>;
  msdyn_agreement_Appointments: WebExpand<msdyn_agreement_Expand, Appointment_Select, Appointment_Filter, { msdyn_agreement_Appointments: Appointment_Result[] }>;
  msdyn_agreement_AsyncOperations: WebExpand<msdyn_agreement_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_agreement_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_agreement_BulkDeleteFailures: WebExpand<msdyn_agreement_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_agreement_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_agreement_DuplicateBaseRecord: WebExpand<msdyn_agreement_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_agreement_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_agreement_DuplicateMatchingRecord: WebExpand<msdyn_agreement_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_agreement_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_agreement_Emails: WebExpand<msdyn_agreement_Expand, Email_Select, Email_Filter, { msdyn_agreement_Emails: Email_Result[] }>;
  msdyn_agreement_Faxes: WebExpand<msdyn_agreement_Expand, Fax_Select, Fax_Filter, { msdyn_agreement_Faxes: Fax_Result[] }>;
  msdyn_agreement_Letters: WebExpand<msdyn_agreement_Expand, Letter_Select, Letter_Filter, { msdyn_agreement_Letters: Letter_Result[] }>;
  msdyn_agreement_MailboxTrackingFolders: WebExpand<msdyn_agreement_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_agreement_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_agreement_PhoneCalls: WebExpand<msdyn_agreement_Expand, PhoneCall_Select, PhoneCall_Filter, { msdyn_agreement_PhoneCalls: PhoneCall_Result[] }>;
  msdyn_agreement_PrincipalObjectAttributeAccesses: WebExpand<msdyn_agreement_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_agreement_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_agreement_ProcessSession: WebExpand<msdyn_agreement_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_agreement_ProcessSession: ProcessSession_Result[] }>;
  msdyn_agreement_RecurringAppointmentMasters: WebExpand<msdyn_agreement_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { msdyn_agreement_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  msdyn_agreement_ServiceAppointments: WebExpand<msdyn_agreement_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_agreement_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_agreement_SharePointDocumentLocations: WebExpand<msdyn_agreement_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { msdyn_agreement_SharePointDocumentLocations: SharePointDocumentLocation_Result[] }>;
  msdyn_agreement_SharePointDocuments: WebExpand<msdyn_agreement_Expand, SharePointDocument_Select, SharePointDocument_Filter, { msdyn_agreement_SharePointDocuments: SharePointDocument_Result[] }>;
  msdyn_agreement_SocialActivities: WebExpand<msdyn_agreement_Expand, SocialActivity_Select, SocialActivity_Filter, { msdyn_agreement_SocialActivities: SocialActivity_Result[] }>;
  msdyn_agreement_SyncErrors: WebExpand<msdyn_agreement_Expand, SyncError_Select, SyncError_Filter, { msdyn_agreement_SyncErrors: SyncError_Result[] }>;
  msdyn_agreement_Tasks: WebExpand<msdyn_agreement_Expand, Task_Select, Task_Filter, { msdyn_agreement_Tasks: Task_Result[] }>;
  msdyn_agreement_UserEntityInstanceDatas: WebExpand<msdyn_agreement_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_agreement_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_agreement_connections1: WebExpand<msdyn_agreement_Expand, Connection_Select, Connection_Filter, { msdyn_agreement_connections1: Connection_Result[] }>;
  msdyn_agreement_connections2: WebExpand<msdyn_agreement_Expand, Connection_Select, Connection_Filter, { msdyn_agreement_connections2: Connection_Result[] }>;
  msdyn_agreement_msdyn_approvals: WebExpand<msdyn_agreement_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_agreement_msdyn_approvals: msdyn_approval_Result[] }>;
  msdyn_agreement_msdyn_bookingalerts: WebExpand<msdyn_agreement_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_agreement_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  msdyn_agreement_msdyn_ocliveworkitems: WebExpand<msdyn_agreement_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_agreement_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  msdyn_agreement_msdyn_ocoutboundmessages: WebExpand<msdyn_agreement_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_agreement_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_agreement_msdyn_ocsessions: WebExpand<msdyn_agreement_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_agreement_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  msdyn_agreement_msfp_alerts: WebExpand<msdyn_agreement_Expand, msfp_alert_Select, msfp_alert_Filter, { msdyn_agreement_msfp_alerts: msfp_alert_Result[] }>;
  msdyn_agreement_msfp_surveyinvites: WebExpand<msdyn_agreement_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msdyn_agreement_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  msdyn_agreement_msfp_surveyresponses: WebExpand<msdyn_agreement_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msdyn_agreement_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  msdyn_billingaccount: WebExpand<msdyn_agreement_Expand, Account_Select, Account_Filter, { msdyn_billingaccount: Account_Result }>;
  msdyn_msdyn_agreement_invoicedetail_Agreement: WebExpand<msdyn_agreement_Expand, InvoiceDetail_Select, InvoiceDetail_Filter, { msdyn_msdyn_agreement_invoicedetail_Agreement: InvoiceDetail_Result[] }>;
  msdyn_msdyn_agreement_msdyn_actual_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_actual_Select, msdyn_actual_Filter, { msdyn_msdyn_agreement_msdyn_actual_Agreement: msdyn_actual_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreement_OriginatingAgreement: WebExpand<msdyn_agreement_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { msdyn_msdyn_agreement_msdyn_agreement_OriginatingAgreement: msdyn_agreement_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreementbookingdate_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreementbookingdate_Select, msdyn_agreementbookingdate_Filter, { msdyn_msdyn_agreement_msdyn_agreementbookingdate_Agreement: msdyn_agreementbookingdate_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreementbookingincident_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreementbookingincident_Select, msdyn_agreementbookingincident_Filter, { msdyn_msdyn_agreement_msdyn_agreementbookingincident_Agreement: msdyn_agreementbookingincident_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreementbookingproduct_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreementbookingproduct_Select, msdyn_agreementbookingproduct_Filter, { msdyn_msdyn_agreement_msdyn_agreementbookingproduct_Agreement: msdyn_agreementbookingproduct_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreementbookingservice_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreementbookingservice_Select, msdyn_agreementbookingservice_Filter, { msdyn_msdyn_agreement_msdyn_agreementbookingservice_Agreement: msdyn_agreementbookingservice_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreementbookingservicetask_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreementbookingservicetask_Select, msdyn_agreementbookingservicetask_Filter, { msdyn_msdyn_agreement_msdyn_agreementbookingservicetask_Agreement: msdyn_agreementbookingservicetask_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreementbookingsetup_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreementbookingsetup_Select, msdyn_agreementbookingsetup_Filter, { msdyn_msdyn_agreement_msdyn_agreementbookingsetup_Agreement: msdyn_agreementbookingsetup_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreementinvoicedate_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreementinvoicedate_Select, msdyn_agreementinvoicedate_Filter, { msdyn_msdyn_agreement_msdyn_agreementinvoicedate_Agreement: msdyn_agreementinvoicedate_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreementinvoiceproduct_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreementinvoiceproduct_Select, msdyn_agreementinvoiceproduct_Filter, { msdyn_msdyn_agreement_msdyn_agreementinvoiceproduct_Agreement: msdyn_agreementinvoiceproduct_Result[] }>;
  msdyn_msdyn_agreement_msdyn_agreementinvoicesetup_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreementinvoicesetup_Select, msdyn_agreementinvoicesetup_Filter, { msdyn_msdyn_agreement_msdyn_agreementinvoicesetup_Agreement: msdyn_agreementinvoicesetup_Result[] }>;
  msdyn_msdyn_agreement_msdyn_workorder_Agreement: WebExpand<msdyn_agreement_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_msdyn_agreement_msdyn_workorder_Agreement: msdyn_workorder_Result[] }>;
  msdyn_msdyn_agreement_quotedetail_Agreement: WebExpand<msdyn_agreement_Expand, QuoteDetail_Select, QuoteDetail_Filter, { msdyn_msdyn_agreement_quotedetail_Agreement: QuoteDetail_Result[] }>;
  msdyn_msdyn_agreement_salesorderdetail_Agreement: WebExpand<msdyn_agreement_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { msdyn_msdyn_agreement_salesorderdetail_Agreement: SalesOrderDetail_Result[] }>;
  msdyn_originatingagreement_msdyn_agreement: WebExpand<msdyn_agreement_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { msdyn_originatingagreement_msdyn_agreement: msdyn_agreement_Result }>;
  msdyn_pricelist: WebExpand<msdyn_agreement_Expand, PriceLevel_Select, PriceLevel_Filter, { msdyn_pricelist: PriceLevel_Result }>;
  msdyn_salestaxcode: WebExpand<msdyn_agreement_Expand, msdyn_taxcode_Select, msdyn_taxcode_Filter, { msdyn_salestaxcode: msdyn_taxcode_Result }>;
  msdyn_serviceaccount: WebExpand<msdyn_agreement_Expand, Account_Select, Account_Filter, { msdyn_serviceaccount: Account_Result }>;
  msdyn_serviceterritory: WebExpand<msdyn_agreement_Expand, Territory_Select, Territory_Filter, { msdyn_serviceterritory: Territory_Result }>;
  msdyn_substatus: WebExpand<msdyn_agreement_Expand, msdyn_agreementsubstatus_Select, msdyn_agreementsubstatus_Filter, { msdyn_substatus: msdyn_agreementsubstatus_Result }>;
  ownerid: WebExpand<msdyn_agreement_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_agreement_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_agreement_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_agreement_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  stageid: WebExpand<msdyn_agreement_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid: ProcessStage_Result }>;
}
interface msdyn_agreement_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_agreementrecordgeneration_formatted?: string;
  msdyn_billingaccount_formatted?: string;
  msdyn_datecanceled_formatted?: string;
  msdyn_enddate_formatted?: string;
  msdyn_originatingagreement_formatted?: string;
  msdyn_pricelist_formatted?: string;
  msdyn_processstartedon_formatted?: string;
  msdyn_salestaxcode_formatted?: string;
  msdyn_serviceaccount_formatted?: string;
  msdyn_serviceterritory_formatted?: string;
  msdyn_startdate_formatted?: string;
  msdyn_substatus_formatted?: string;
  msdyn_systemstatus_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface msdyn_agreement_Result extends msdyn_agreement_Base, msdyn_agreement_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_billingaccount_guid: string | null;
  msdyn_originatingagreement_guid: string | null;
  msdyn_pricelist_guid: string | null;
  msdyn_salestaxcode_guid: string | null;
  msdyn_serviceaccount_guid: string | null;
  msdyn_serviceterritory_guid: string | null;
  msdyn_substatus_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface msdyn_agreement_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_billingaccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_originatingagreement_msdyn_agreement: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  msdyn_pricelist: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  msdyn_salestaxcode: WebMappingRetrieve<msdyn_taxcode_Select,msdyn_taxcode_Expand,msdyn_taxcode_Filter,msdyn_taxcode_Fixed,msdyn_taxcode_Result,msdyn_taxcode_FormattedResult>;
  msdyn_serviceaccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_serviceterritory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  msdyn_substatus: WebMappingRetrieve<msdyn_agreementsubstatus_Select,msdyn_agreementsubstatus_Expand,msdyn_agreementsubstatus_Filter,msdyn_agreementsubstatus_Fixed,msdyn_agreementsubstatus_Result,msdyn_agreementsubstatus_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  stageid: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
}
interface msdyn_agreement_RelatedMany {
  bpf_msdyn_agreement_msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3: WebMappingRetrieve<msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_Select,msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_Expand,msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_Filter,msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_Fixed,msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_Result,msdyn_bpf_baa0a411a239410cb8bded8b5fdd88e3_FormattedResult>;
  msdyn_agreement_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  msdyn_agreement_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_agreement_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_agreement_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_agreement_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_agreement_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_agreement_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_agreement_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_agreement_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  msdyn_agreement_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  msdyn_agreement_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_agreement_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  msdyn_agreement_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_agreement_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_agreement_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  msdyn_agreement_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_agreement_SharePointDocumentLocations: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  msdyn_agreement_SharePointDocuments: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  msdyn_agreement_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  msdyn_agreement_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_agreement_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  msdyn_agreement_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_agreement_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_agreement_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_agreement_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_agreement_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_agreement_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_agreement_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_agreement_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msdyn_agreement_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msdyn_agreement_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msdyn_agreement_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  msdyn_msdyn_agreement_invoicedetail_Agreement: WebMappingRetrieve<InvoiceDetail_Select,InvoiceDetail_Expand,InvoiceDetail_Filter,InvoiceDetail_Fixed,InvoiceDetail_Result,InvoiceDetail_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_actual_Agreement: WebMappingRetrieve<msdyn_actual_Select,msdyn_actual_Expand,msdyn_actual_Filter,msdyn_actual_Fixed,msdyn_actual_Result,msdyn_actual_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreement_OriginatingAgreement: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreementbookingdate_Agreement: WebMappingRetrieve<msdyn_agreementbookingdate_Select,msdyn_agreementbookingdate_Expand,msdyn_agreementbookingdate_Filter,msdyn_agreementbookingdate_Fixed,msdyn_agreementbookingdate_Result,msdyn_agreementbookingdate_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreementbookingincident_Agreement: WebMappingRetrieve<msdyn_agreementbookingincident_Select,msdyn_agreementbookingincident_Expand,msdyn_agreementbookingincident_Filter,msdyn_agreementbookingincident_Fixed,msdyn_agreementbookingincident_Result,msdyn_agreementbookingincident_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreementbookingproduct_Agreement: WebMappingRetrieve<msdyn_agreementbookingproduct_Select,msdyn_agreementbookingproduct_Expand,msdyn_agreementbookingproduct_Filter,msdyn_agreementbookingproduct_Fixed,msdyn_agreementbookingproduct_Result,msdyn_agreementbookingproduct_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreementbookingservice_Agreement: WebMappingRetrieve<msdyn_agreementbookingservice_Select,msdyn_agreementbookingservice_Expand,msdyn_agreementbookingservice_Filter,msdyn_agreementbookingservice_Fixed,msdyn_agreementbookingservice_Result,msdyn_agreementbookingservice_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreementbookingservicetask_Agreement: WebMappingRetrieve<msdyn_agreementbookingservicetask_Select,msdyn_agreementbookingservicetask_Expand,msdyn_agreementbookingservicetask_Filter,msdyn_agreementbookingservicetask_Fixed,msdyn_agreementbookingservicetask_Result,msdyn_agreementbookingservicetask_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreementbookingsetup_Agreement: WebMappingRetrieve<msdyn_agreementbookingsetup_Select,msdyn_agreementbookingsetup_Expand,msdyn_agreementbookingsetup_Filter,msdyn_agreementbookingsetup_Fixed,msdyn_agreementbookingsetup_Result,msdyn_agreementbookingsetup_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreementinvoicedate_Agreement: WebMappingRetrieve<msdyn_agreementinvoicedate_Select,msdyn_agreementinvoicedate_Expand,msdyn_agreementinvoicedate_Filter,msdyn_agreementinvoicedate_Fixed,msdyn_agreementinvoicedate_Result,msdyn_agreementinvoicedate_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreementinvoiceproduct_Agreement: WebMappingRetrieve<msdyn_agreementinvoiceproduct_Select,msdyn_agreementinvoiceproduct_Expand,msdyn_agreementinvoiceproduct_Filter,msdyn_agreementinvoiceproduct_Fixed,msdyn_agreementinvoiceproduct_Result,msdyn_agreementinvoiceproduct_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_agreementinvoicesetup_Agreement: WebMappingRetrieve<msdyn_agreementinvoicesetup_Select,msdyn_agreementinvoicesetup_Expand,msdyn_agreementinvoicesetup_Filter,msdyn_agreementinvoicesetup_Fixed,msdyn_agreementinvoicesetup_Result,msdyn_agreementinvoicesetup_FormattedResult>;
  msdyn_msdyn_agreement_msdyn_workorder_Agreement: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  msdyn_msdyn_agreement_quotedetail_Agreement: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  msdyn_msdyn_agreement_salesorderdetail_Agreement: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_agreements: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_agreements: WebMappingRelated<msdyn_agreement_RelatedOne,msdyn_agreement_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_agreements: WebMappingCUDA<msdyn_agreement_Create,msdyn_agreement_Update,msdyn_agreement_Select>;
}
