interface msdyn_quotebookingservice_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_Internalflags?: string | null;
  msdyn_currency?: number | null;
  msdyn_currency_base?: number | null;
  msdyn_duration?: number | null;
  msdyn_durationtobill?: number | null;
  msdyn_estimatedcostamount?: number | null;
  msdyn_estimatedcostamount_base?: number | null;
  msdyn_estimatedsalesamount?: number | null;
  msdyn_estimatedsalesamount_base?: number | null;
  msdyn_iscopied?: boolean | null;
  msdyn_lineorder?: number | null;
  msdyn_minimumchargeamount?: number | null;
  msdyn_minimumchargeamount_base?: number | null;
  msdyn_minimumchargeduration?: number | null;
  msdyn_name?: string | null;
  msdyn_quotebookingserviceid?: string | null;
  msdyn_unitamount?: number | null;
  msdyn_unitamount_base?: number | null;
  msdyn_unitcostamount?: number | null;
  msdyn_unitcostamount_base?: number | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_quotebookingservice_statecode | null;
  statuscode?: msdyn_quotebookingservice_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_quotebookingservice_Relationships {
  msdyn_Service?: Product_Result | null;
  msdyn_quotebookingservice_ActivityPointers?: ActivityPointer_Result[] | null;
  msdyn_quotebookingservice_Annotations?: Annotation_Result[] | null;
  msdyn_quotebookingservice_Appointments?: Appointment_Result[] | null;
  msdyn_quotebookingservice_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_quotebookingservice_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_quotebookingservice_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_quotebookingservice_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_quotebookingservice_Emails?: Email_Result[] | null;
  msdyn_quotebookingservice_Faxes?: Fax_Result[] | null;
  msdyn_quotebookingservice_Letters?: Letter_Result[] | null;
  msdyn_quotebookingservice_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_quotebookingservice_PhoneCalls?: PhoneCall_Result[] | null;
  msdyn_quotebookingservice_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_quotebookingservice_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_quotebookingservice_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  msdyn_quotebookingservice_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_quotebookingservice_SocialActivities?: SocialActivity_Result[] | null;
  msdyn_quotebookingservice_SyncErrors?: SyncError_Result[] | null;
  msdyn_quotebookingservice_Tasks?: Task_Result[] | null;
  msdyn_quotebookingservice_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_quotebookingservice_connections1?: Connection_Result[] | null;
  msdyn_quotebookingservice_connections2?: Connection_Result[] | null;
  msdyn_quotebookingservice_msdyn_approvals?: msdyn_approval_Result[] | null;
  msdyn_quotebookingservice_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  msdyn_quotebookingservice_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_quotebookingservice_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_quotebookingservice_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  msdyn_quotebookingservice_msfp_alerts?: msfp_alert_Result[] | null;
  msdyn_quotebookingservice_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  msdyn_quotebookingservice_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
}
interface msdyn_quotebookingservice extends msdyn_quotebookingservice_Base, msdyn_quotebookingservice_Relationships {
  msdyn_Service_bind$products?: string | null;
  msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  msdyn_pricelist_bind$pricelevels?: string | null;
  msdyn_quote_bind$quotes?: string | null;
  msdyn_quotebookingincident_bind$msdyn_quotebookingincidents?: string | null;
  msdyn_quotebookingsetup_bind$msdyn_quotebookingsetups?: string | null;
  msdyn_unit_bind$uoms?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface msdyn_quotebookingservice_Create extends msdyn_quotebookingservice {
}
interface msdyn_quotebookingservice_Update extends msdyn_quotebookingservice {
}
interface msdyn_quotebookingservice_Select {
  createdby_guid: WebAttribute<msdyn_quotebookingservice_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_quotebookingservice_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_quotebookingservice_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_quotebookingservice_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_quotebookingservice_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_quotebookingservice_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_quotebookingservice_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_quotebookingservice_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_Internalflags: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_Internalflags: string | null }, {  }>;
  msdyn_currency: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_currency: number | null; transactioncurrencyid_guid: string | null }, { msdyn_currency_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_currency_base: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_currency_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_currency_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_customerasset_guid: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_customerasset_guid: string | null }, { msdyn_customerasset_formatted?: string }>;
  msdyn_duration: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_duration: number | null }, {  }>;
  msdyn_durationtobill: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_durationtobill: number | null }, {  }>;
  msdyn_estimatedcostamount: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_estimatedcostamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedcostamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedcostamount_base: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_estimatedcostamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedcostamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedsalesamount: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_estimatedsalesamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedsalesamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedsalesamount_base: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_estimatedsalesamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedsalesamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_iscopied: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_iscopied: boolean | null }, {  }>;
  msdyn_lineorder: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_lineorder: number | null }, {  }>;
  msdyn_minimumchargeamount: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_minimumchargeamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_minimumchargeamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_minimumchargeamount_base: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_minimumchargeamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_minimumchargeamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_minimumchargeduration: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_minimumchargeduration: number | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_name: string | null }, {  }>;
  msdyn_pricelist_guid: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_pricelist_guid: string | null }, { msdyn_pricelist_formatted?: string }>;
  msdyn_quote_guid: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_quote_guid: string | null }, { msdyn_quote_formatted?: string }>;
  msdyn_quotebookingincident_guid: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_quotebookingincident_guid: string | null }, { msdyn_quotebookingincident_formatted?: string }>;
  msdyn_quotebookingserviceid: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_quotebookingserviceid: string | null }, {  }>;
  msdyn_quotebookingsetup_guid: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_quotebookingsetup_guid: string | null }, { msdyn_quotebookingsetup_formatted?: string }>;
  msdyn_service_guid: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_service_guid: string | null }, { msdyn_service_formatted?: string }>;
  msdyn_unit_guid: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_unit_guid: string | null }, { msdyn_unit_formatted?: string }>;
  msdyn_unitamount: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_unitamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unitamount_base: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_unitamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unitcostamount: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_unitcostamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitcostamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unitcostamount_base: WebAttribute<msdyn_quotebookingservice_Select, { msdyn_unitcostamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitcostamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_quotebookingservice_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_quotebookingservice_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_quotebookingservice_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_quotebookingservice_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_quotebookingservice_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_quotebookingservice_Select, { statecode: msdyn_quotebookingservice_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_quotebookingservice_Select, { statuscode: msdyn_quotebookingservice_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_quotebookingservice_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_quotebookingservice_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<msdyn_quotebookingservice_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_quotebookingservice_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_quotebookingservice_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_Internalflags: string;
  msdyn_currency: number;
  msdyn_currency_base: number;
  msdyn_customerasset_guid: XQW.Guid;
  msdyn_duration: number;
  msdyn_durationtobill: number;
  msdyn_estimatedcostamount: number;
  msdyn_estimatedcostamount_base: number;
  msdyn_estimatedsalesamount: number;
  msdyn_estimatedsalesamount_base: number;
  msdyn_iscopied: boolean;
  msdyn_lineorder: number;
  msdyn_minimumchargeamount: number;
  msdyn_minimumchargeamount_base: number;
  msdyn_minimumchargeduration: number;
  msdyn_name: string;
  msdyn_pricelist_guid: XQW.Guid;
  msdyn_quote_guid: XQW.Guid;
  msdyn_quotebookingincident_guid: XQW.Guid;
  msdyn_quotebookingserviceid: XQW.Guid;
  msdyn_quotebookingsetup_guid: XQW.Guid;
  msdyn_service_guid: XQW.Guid;
  msdyn_unit_guid: XQW.Guid;
  msdyn_unitamount: number;
  msdyn_unitamount_base: number;
  msdyn_unitcostamount: number;
  msdyn_unitcostamount_base: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_quotebookingservice_statecode;
  statuscode: msdyn_quotebookingservice_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_quotebookingservice_Expand {
  createdby: WebExpand<msdyn_quotebookingservice_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_quotebookingservice_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_quotebookingservice_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_quotebookingservice_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_Service: WebExpand<msdyn_quotebookingservice_Expand, Product_Select, Product_Filter, { msdyn_Service: Product_Result }>;
  msdyn_customerasset: WebExpand<msdyn_quotebookingservice_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_customerasset: msdyn_customerasset_Result }>;
  msdyn_pricelist: WebExpand<msdyn_quotebookingservice_Expand, PriceLevel_Select, PriceLevel_Filter, { msdyn_pricelist: PriceLevel_Result }>;
  msdyn_quote: WebExpand<msdyn_quotebookingservice_Expand, Quote_Select, Quote_Filter, { msdyn_quote: Quote_Result }>;
  msdyn_quotebookingincident: WebExpand<msdyn_quotebookingservice_Expand, msdyn_quotebookingincident_Select, msdyn_quotebookingincident_Filter, { msdyn_quotebookingincident: msdyn_quotebookingincident_Result }>;
  msdyn_quotebookingservice_ActivityPointers: WebExpand<msdyn_quotebookingservice_Expand, ActivityPointer_Select, ActivityPointer_Filter, { msdyn_quotebookingservice_ActivityPointers: ActivityPointer_Result[] }>;
  msdyn_quotebookingservice_Annotations: WebExpand<msdyn_quotebookingservice_Expand, Annotation_Select, Annotation_Filter, { msdyn_quotebookingservice_Annotations: Annotation_Result[] }>;
  msdyn_quotebookingservice_Appointments: WebExpand<msdyn_quotebookingservice_Expand, Appointment_Select, Appointment_Filter, { msdyn_quotebookingservice_Appointments: Appointment_Result[] }>;
  msdyn_quotebookingservice_AsyncOperations: WebExpand<msdyn_quotebookingservice_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_quotebookingservice_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_quotebookingservice_BulkDeleteFailures: WebExpand<msdyn_quotebookingservice_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_quotebookingservice_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_quotebookingservice_DuplicateBaseRecord: WebExpand<msdyn_quotebookingservice_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_quotebookingservice_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_quotebookingservice_DuplicateMatchingRecord: WebExpand<msdyn_quotebookingservice_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_quotebookingservice_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_quotebookingservice_Emails: WebExpand<msdyn_quotebookingservice_Expand, Email_Select, Email_Filter, { msdyn_quotebookingservice_Emails: Email_Result[] }>;
  msdyn_quotebookingservice_Faxes: WebExpand<msdyn_quotebookingservice_Expand, Fax_Select, Fax_Filter, { msdyn_quotebookingservice_Faxes: Fax_Result[] }>;
  msdyn_quotebookingservice_Letters: WebExpand<msdyn_quotebookingservice_Expand, Letter_Select, Letter_Filter, { msdyn_quotebookingservice_Letters: Letter_Result[] }>;
  msdyn_quotebookingservice_MailboxTrackingFolders: WebExpand<msdyn_quotebookingservice_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_quotebookingservice_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_quotebookingservice_PhoneCalls: WebExpand<msdyn_quotebookingservice_Expand, PhoneCall_Select, PhoneCall_Filter, { msdyn_quotebookingservice_PhoneCalls: PhoneCall_Result[] }>;
  msdyn_quotebookingservice_PrincipalObjectAttributeAccesses: WebExpand<msdyn_quotebookingservice_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_quotebookingservice_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_quotebookingservice_ProcessSession: WebExpand<msdyn_quotebookingservice_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_quotebookingservice_ProcessSession: ProcessSession_Result[] }>;
  msdyn_quotebookingservice_RecurringAppointmentMasters: WebExpand<msdyn_quotebookingservice_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { msdyn_quotebookingservice_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  msdyn_quotebookingservice_ServiceAppointments: WebExpand<msdyn_quotebookingservice_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_quotebookingservice_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_quotebookingservice_SocialActivities: WebExpand<msdyn_quotebookingservice_Expand, SocialActivity_Select, SocialActivity_Filter, { msdyn_quotebookingservice_SocialActivities: SocialActivity_Result[] }>;
  msdyn_quotebookingservice_SyncErrors: WebExpand<msdyn_quotebookingservice_Expand, SyncError_Select, SyncError_Filter, { msdyn_quotebookingservice_SyncErrors: SyncError_Result[] }>;
  msdyn_quotebookingservice_Tasks: WebExpand<msdyn_quotebookingservice_Expand, Task_Select, Task_Filter, { msdyn_quotebookingservice_Tasks: Task_Result[] }>;
  msdyn_quotebookingservice_UserEntityInstanceDatas: WebExpand<msdyn_quotebookingservice_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_quotebookingservice_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_quotebookingservice_connections1: WebExpand<msdyn_quotebookingservice_Expand, Connection_Select, Connection_Filter, { msdyn_quotebookingservice_connections1: Connection_Result[] }>;
  msdyn_quotebookingservice_connections2: WebExpand<msdyn_quotebookingservice_Expand, Connection_Select, Connection_Filter, { msdyn_quotebookingservice_connections2: Connection_Result[] }>;
  msdyn_quotebookingservice_msdyn_approvals: WebExpand<msdyn_quotebookingservice_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_quotebookingservice_msdyn_approvals: msdyn_approval_Result[] }>;
  msdyn_quotebookingservice_msdyn_bookingalerts: WebExpand<msdyn_quotebookingservice_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_quotebookingservice_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  msdyn_quotebookingservice_msdyn_ocliveworkitems: WebExpand<msdyn_quotebookingservice_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_quotebookingservice_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  msdyn_quotebookingservice_msdyn_ocoutboundmessages: WebExpand<msdyn_quotebookingservice_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_quotebookingservice_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_quotebookingservice_msdyn_ocsessions: WebExpand<msdyn_quotebookingservice_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_quotebookingservice_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  msdyn_quotebookingservice_msfp_alerts: WebExpand<msdyn_quotebookingservice_Expand, msfp_alert_Select, msfp_alert_Filter, { msdyn_quotebookingservice_msfp_alerts: msfp_alert_Result[] }>;
  msdyn_quotebookingservice_msfp_surveyinvites: WebExpand<msdyn_quotebookingservice_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msdyn_quotebookingservice_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  msdyn_quotebookingservice_msfp_surveyresponses: WebExpand<msdyn_quotebookingservice_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msdyn_quotebookingservice_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  msdyn_quotebookingsetup: WebExpand<msdyn_quotebookingservice_Expand, msdyn_quotebookingsetup_Select, msdyn_quotebookingsetup_Filter, { msdyn_quotebookingsetup: msdyn_quotebookingsetup_Result }>;
  msdyn_unit: WebExpand<msdyn_quotebookingservice_Expand, UoM_Select, UoM_Filter, { msdyn_unit: UoM_Result }>;
  ownerid: WebExpand<msdyn_quotebookingservice_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_quotebookingservice_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_quotebookingservice_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_quotebookingservice_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  transactioncurrencyid: WebExpand<msdyn_quotebookingservice_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface msdyn_quotebookingservice_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_currency_base_formatted?: string;
  msdyn_currency_formatted?: string;
  msdyn_customerasset_formatted?: string;
  msdyn_estimatedcostamount_base_formatted?: string;
  msdyn_estimatedcostamount_formatted?: string;
  msdyn_estimatedsalesamount_base_formatted?: string;
  msdyn_estimatedsalesamount_formatted?: string;
  msdyn_minimumchargeamount_base_formatted?: string;
  msdyn_minimumchargeamount_formatted?: string;
  msdyn_pricelist_formatted?: string;
  msdyn_quote_formatted?: string;
  msdyn_quotebookingincident_formatted?: string;
  msdyn_quotebookingsetup_formatted?: string;
  msdyn_service_formatted?: string;
  msdyn_unit_formatted?: string;
  msdyn_unitamount_base_formatted?: string;
  msdyn_unitamount_formatted?: string;
  msdyn_unitcostamount_base_formatted?: string;
  msdyn_unitcostamount_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface msdyn_quotebookingservice_Result extends msdyn_quotebookingservice_Base, msdyn_quotebookingservice_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_customerasset_guid: string | null;
  msdyn_pricelist_guid: string | null;
  msdyn_quote_guid: string | null;
  msdyn_quotebookingincident_guid: string | null;
  msdyn_quotebookingsetup_guid: string | null;
  msdyn_service_guid: string | null;
  msdyn_unit_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface msdyn_quotebookingservice_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_Service: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_pricelist: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  msdyn_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  msdyn_quotebookingincident: WebMappingRetrieve<msdyn_quotebookingincident_Select,msdyn_quotebookingincident_Expand,msdyn_quotebookingincident_Filter,msdyn_quotebookingincident_Fixed,msdyn_quotebookingincident_Result,msdyn_quotebookingincident_FormattedResult>;
  msdyn_quotebookingsetup: WebMappingRetrieve<msdyn_quotebookingsetup_Select,msdyn_quotebookingsetup_Expand,msdyn_quotebookingsetup_Filter,msdyn_quotebookingsetup_Fixed,msdyn_quotebookingsetup_Result,msdyn_quotebookingsetup_FormattedResult>;
  msdyn_unit: WebMappingRetrieve<UoM_Select,UoM_Expand,UoM_Filter,UoM_Fixed,UoM_Result,UoM_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface msdyn_quotebookingservice_RelatedMany {
  msdyn_quotebookingservice_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  msdyn_quotebookingservice_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_quotebookingservice_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_quotebookingservice_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_quotebookingservice_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_quotebookingservice_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_quotebookingservice_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_quotebookingservice_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_quotebookingservice_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  msdyn_quotebookingservice_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  msdyn_quotebookingservice_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_quotebookingservice_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  msdyn_quotebookingservice_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_quotebookingservice_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_quotebookingservice_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  msdyn_quotebookingservice_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_quotebookingservice_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  msdyn_quotebookingservice_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_quotebookingservice_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  msdyn_quotebookingservice_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_quotebookingservice_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_quotebookingservice_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_quotebookingservice_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_quotebookingservice_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_quotebookingservice_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_quotebookingservice_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_quotebookingservice_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msdyn_quotebookingservice_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msdyn_quotebookingservice_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msdyn_quotebookingservice_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_quotebookingservices: WebMappingRetrieve<msdyn_quotebookingservice_Select,msdyn_quotebookingservice_Expand,msdyn_quotebookingservice_Filter,msdyn_quotebookingservice_Fixed,msdyn_quotebookingservice_Result,msdyn_quotebookingservice_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_quotebookingservices: WebMappingRelated<msdyn_quotebookingservice_RelatedOne,msdyn_quotebookingservice_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_quotebookingservices: WebMappingCUDA<msdyn_quotebookingservice_Create,msdyn_quotebookingservice_Update,msdyn_quotebookingservice_Select>;
}
