interface msdyn_workorder_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_address1?: string | null;
  msdyn_address2?: string | null;
  msdyn_address3?: string | null;
  msdyn_addressname?: string | null;
  msdyn_autonumbering?: string | null;
  msdyn_bookingsummary?: string | null;
  msdyn_childindex?: number | null;
  msdyn_city?: string | null;
  msdyn_completedon?: Date | null;
  msdyn_country?: string | null;
  msdyn_datewindowend?: Date | null;
  msdyn_datewindowstart?: Date | null;
  msdyn_estimatesubtotalamount?: number | null;
  msdyn_estimatesubtotalamount_base?: number | null;
  msdyn_firstarrivedon?: Date | null;
  msdyn_followupnote?: string | null;
  msdyn_followuprequired?: boolean | null;
  msdyn_instructions?: string | null;
  msdyn_internalflags?: string | null;
  msdyn_isfollowup?: boolean | null;
  msdyn_ismobile?: boolean | null;
  msdyn_latitude?: number | null;
  msdyn_longitude?: number | null;
  msdyn_mapcontrol?: string | null;
  msdyn_name?: string | null;
  msdyn_postalcode?: string | null;
  msdyn_primaryincidentdescription?: string | null;
  msdyn_primaryincidentestimatedduration?: number | null;
  msdyn_stateorprovince?: string | null;
  msdyn_subtotalamount?: number | null;
  msdyn_subtotalamount_base?: number | null;
  msdyn_systemstatus?: msdyn_wosystemstatus | null;
  msdyn_taxable?: boolean | null;
  msdyn_timeclosed?: Date | null;
  msdyn_timefrompromised?: Date | null;
  msdyn_timetopromised?: Date | null;
  msdyn_timewindowend?: Date | null;
  msdyn_timewindowstart?: Date | null;
  msdyn_totalamount?: number | null;
  msdyn_totalamount_base?: number | null;
  msdyn_totalestimatedduration?: number | null;
  msdyn_totalsalestax?: number | null;
  msdyn_totalsalestax_base?: number | null;
  msdyn_worklocation?: msdyn_worklocation | null;
  msdyn_workorderid?: string | null;
  msdyn_workordersummary?: string | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  stageid?: string | null;
  statecode?: msdyn_workorder_statecode | null;
  statuscode?: msdyn_workorder_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_workorder_Relationships {
  bpf_msdyn_workorder_msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b?: msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_Result[] | null;
  bpf_msdyn_workorder_msdyn_bpf_989e9b1857e24af18787d5143b67523b?: msdyn_bpf_989e9b1857e24af18787d5143b67523b_Result[] | null;
  bpf_msdyn_workorder_msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39?: msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_Result[] | null;
  msdyn_FunctionalLocation?: msdyn_FunctionalLocation_Result | null;
  msdyn_IoTAlert?: msdyn_iotalert_Result | null;
  msdyn_PrimaryResolution?: msdyn_resolution_Result | null;
  msdyn_SupportContact?: BookableResource_Result | null;
  msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder?: BookableResourceBooking_Result[] | null;
  msdyn_msdyn_workorder_invoicedetail?: InvoiceDetail_Result[] | null;
  msdyn_msdyn_workorder_msdyn_actual_WorkOrder?: msdyn_actual_Result[] | null;
  msdyn_msdyn_workorder_msdyn_agreementbookingdate_WorkOrder?: msdyn_agreementbookingdate_Result[] | null;
  msdyn_msdyn_workorder_msdyn_inventoryjournal_AllocatedToWorkOrder?: msdyn_inventoryjournal_Result[] | null;
  msdyn_msdyn_workorder_msdyn_iotalert_Workorder?: msdyn_iotalert_Result[] | null;
  msdyn_msdyn_workorder_msdyn_payment_WorkOrder?: msdyn_payment_Result[] | null;
  msdyn_msdyn_workorder_msdyn_paymentdetail_Workorder?: msdyn_paymentdetail_Result[] | null;
  msdyn_msdyn_workorder_msdyn_purchaseorder_WorkOrder?: msdyn_purchaseorder_Result[] | null;
  msdyn_msdyn_workorder_msdyn_purchaseorderproduct_AssociateToWorkOrder?: msdyn_purchaseorderproduct_Result[] | null;
  msdyn_msdyn_workorder_msdyn_purchaseorderreceiptproduct_AssociateToWorkOrder?: msdyn_purchaseorderreceiptproduct_Result[] | null;
  msdyn_msdyn_workorder_msdyn_requirementcharacteristic_WorkOrder?: msdyn_requirementcharacteristic_Result[] | null;
  msdyn_msdyn_workorder_msdyn_requirementresourcepreference_WorkOrder?: msdyn_requirementresourcepreference_Result[] | null;
  msdyn_msdyn_workorder_msdyn_resourcerequirement_WorkOrder?: msdyn_resourcerequirement_Result[] | null;
  msdyn_msdyn_workorder_msdyn_rma_WorkOrder?: msdyn_rma_Result[] | null;
  msdyn_msdyn_workorder_msdyn_rtv_WorkOrder?: msdyn_rtv_Result[] | null;
  msdyn_msdyn_workorder_msdyn_rtvproduct_WorkOrder?: msdyn_rtvproduct_Result[] | null;
  msdyn_msdyn_workorder_msdyn_timeentry_WorkOrder?: msdyn_timeentry_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workorder_ParentWorkOrder?: msdyn_workorder_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workordercharacteristic_WorkOrder?: msdyn_workordercharacteristic_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workorderincident_WorkOrder?: msdyn_workorderincident_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workorderproduct_WorkOrder?: msdyn_workorderproduct_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workorderresolution_WorkOrder?: msdyn_workorderresolution_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workorderresourcerestriction_WorkOrder?: msdyn_workorderresourcerestriction_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workorderservice_WorkOrder?: msdyn_workorderservice_Result[] | null;
  msdyn_msdyn_workorder_msdyn_workorderservicetask_WorkOrder?: msdyn_workorderservicetask_Result[] | null;
  msdyn_parentworkorder_msdyn_workorder?: msdyn_workorder_Result | null;
  msdyn_workorder_ActivityPointers?: ActivityPointer_Result[] | null;
  msdyn_workorder_Annotations?: Annotation_Result[] | null;
  msdyn_workorder_Appointments?: Appointment_Result[] | null;
  msdyn_workorder_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_workorder_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_workorder_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_workorder_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_workorder_Emails?: Email_Result[] | null;
  msdyn_workorder_Faxes?: Fax_Result[] | null;
  msdyn_workorder_Letters?: Letter_Result[] | null;
  msdyn_workorder_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_workorder_PhoneCalls?: PhoneCall_Result[] | null;
  msdyn_workorder_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_workorder_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_workorder_QueueItems?: QueueItem_Result[] | null;
  msdyn_workorder_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  msdyn_workorder_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_workorder_SharePointDocumentLocations?: SharePointDocumentLocation_Result[] | null;
  msdyn_workorder_SharePointDocuments?: SharePointDocument_Result[] | null;
  msdyn_workorder_SocialActivities?: SocialActivity_Result[] | null;
  msdyn_workorder_SyncErrors?: SyncError_Result[] | null;
  msdyn_workorder_Tasks?: Task_Result[] | null;
  msdyn_workorder_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_workorder_connections1?: Connection_Result[] | null;
  msdyn_workorder_connections2?: Connection_Result[] | null;
  msdyn_workorder_msdyn_approvals?: msdyn_approval_Result[] | null;
  msdyn_workorder_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  msdyn_workorder_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_workorder_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_workorder_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  msdyn_workorder_msfp_alerts?: msfp_alert_Result[] | null;
  msdyn_workorder_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  msdyn_workorder_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  navigationPropertyNameNotDefined?: KnowledgeBaseRecord_Result[] | null;
  navigationPropertyNameNotDefined1?: KnowledgeArticle_Result[] | null;
}
interface msdyn_workorder extends msdyn_workorder_Base, msdyn_workorder_Relationships {
  msdyn_FunctionalLocation_bind$msdyn_functionallocations?: string | null;
  msdyn_IoTAlert_bind$msdyn_iotalerts?: string | null;
  msdyn_PrimaryResolution_bind$msdyn_resolutions?: string | null;
  msdyn_SupportContact_bind$bookableresources?: string | null;
  msdyn_agreement_bind$msdyn_agreements?: string | null;
  msdyn_billingaccount_bind$accounts?: string | null;
  msdyn_closedby_bind$systemusers?: string | null;
  msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  msdyn_opportunityid_bind$opportunities?: string | null;
  msdyn_parentworkorder_msdyn_workorder_bind$msdyn_workorders?: string | null;
  msdyn_preferredresource_bind$bookableresources?: string | null;
  msdyn_pricelist_bind$pricelevels?: string | null;
  msdyn_primaryincidenttype_bind$msdyn_incidenttypes?: string | null;
  msdyn_priority_bind$msdyn_priorities?: string | null;
  msdyn_reportedbycontact_bind$contacts?: string | null;
  msdyn_serviceaccount_bind$accounts?: string | null;
  msdyn_servicerequest_bind$incidents?: string | null;
  msdyn_serviceterritory_bind$territories?: string | null;
  msdyn_substatus_bind$msdyn_workordersubstatuses?: string | null;
  msdyn_taxcode_bind$msdyn_taxcodes?: string | null;
  msdyn_timegroup_bind$msdyn_timegroups?: string | null;
  msdyn_timegroupdetailselected_bind$msdyn_timegroupdetails?: string | null;
  msdyn_workhourtemplate_bind$msdyn_workhourtemplates?: string | null;
  msdyn_workorderarrivaltimekpiid_bind$slakpiinstances?: string | null;
  msdyn_workorderresolutionkpiid_bind$slakpiinstances?: string | null;
  msdyn_workordertype_bind$msdyn_workordertypes?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  stageid_bind$processstages?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface msdyn_workorder_Create extends msdyn_workorder {
}
interface msdyn_workorder_Update extends msdyn_workorder {
}
interface msdyn_workorder_Select {
  createdby_guid: WebAttribute<msdyn_workorder_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_workorder_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_workorder_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_workorder_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_workorder_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_workorder_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_workorder_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_workorder_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_address1: WebAttribute<msdyn_workorder_Select, { msdyn_address1: string | null }, {  }>;
  msdyn_address2: WebAttribute<msdyn_workorder_Select, { msdyn_address2: string | null }, {  }>;
  msdyn_address3: WebAttribute<msdyn_workorder_Select, { msdyn_address3: string | null }, {  }>;
  msdyn_addressname: WebAttribute<msdyn_workorder_Select, { msdyn_addressname: string | null }, {  }>;
  msdyn_agreement_guid: WebAttribute<msdyn_workorder_Select, { msdyn_agreement_guid: string | null }, { msdyn_agreement_formatted?: string }>;
  msdyn_autonumbering: WebAttribute<msdyn_workorder_Select, { msdyn_autonumbering: string | null }, {  }>;
  msdyn_billingaccount_guid: WebAttribute<msdyn_workorder_Select, { msdyn_billingaccount_guid: string | null }, { msdyn_billingaccount_formatted?: string }>;
  msdyn_bookingsummary: WebAttribute<msdyn_workorder_Select, { msdyn_bookingsummary: string | null }, {  }>;
  msdyn_childindex: WebAttribute<msdyn_workorder_Select, { msdyn_childindex: number | null }, {  }>;
  msdyn_city: WebAttribute<msdyn_workorder_Select, { msdyn_city: string | null }, {  }>;
  msdyn_closedby_guid: WebAttribute<msdyn_workorder_Select, { msdyn_closedby_guid: string | null }, { msdyn_closedby_formatted?: string }>;
  msdyn_completedon: WebAttribute<msdyn_workorder_Select, { msdyn_completedon: Date | null }, { msdyn_completedon_formatted?: string }>;
  msdyn_country: WebAttribute<msdyn_workorder_Select, { msdyn_country: string | null }, {  }>;
  msdyn_customerasset_guid: WebAttribute<msdyn_workorder_Select, { msdyn_customerasset_guid: string | null }, { msdyn_customerasset_formatted?: string }>;
  msdyn_datewindowend: WebAttribute<msdyn_workorder_Select, { msdyn_datewindowend: Date | null }, { msdyn_datewindowend_formatted?: string }>;
  msdyn_datewindowstart: WebAttribute<msdyn_workorder_Select, { msdyn_datewindowstart: Date | null }, { msdyn_datewindowstart_formatted?: string }>;
  msdyn_estimatesubtotalamount: WebAttribute<msdyn_workorder_Select, { msdyn_estimatesubtotalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatesubtotalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatesubtotalamount_base: WebAttribute<msdyn_workorder_Select, { msdyn_estimatesubtotalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatesubtotalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_firstarrivedon: WebAttribute<msdyn_workorder_Select, { msdyn_firstarrivedon: Date | null }, { msdyn_firstarrivedon_formatted?: string }>;
  msdyn_followupnote: WebAttribute<msdyn_workorder_Select, { msdyn_followupnote: string | null }, {  }>;
  msdyn_followuprequired: WebAttribute<msdyn_workorder_Select, { msdyn_followuprequired: boolean | null }, {  }>;
  msdyn_functionallocation_guid: WebAttribute<msdyn_workorder_Select, { msdyn_functionallocation_guid: string | null }, { msdyn_functionallocation_formatted?: string }>;
  msdyn_instructions: WebAttribute<msdyn_workorder_Select, { msdyn_instructions: string | null }, {  }>;
  msdyn_internalflags: WebAttribute<msdyn_workorder_Select, { msdyn_internalflags: string | null }, {  }>;
  msdyn_iotalert_guid: WebAttribute<msdyn_workorder_Select, { msdyn_iotalert_guid: string | null }, { msdyn_iotalert_formatted?: string }>;
  msdyn_isfollowup: WebAttribute<msdyn_workorder_Select, { msdyn_isfollowup: boolean | null }, {  }>;
  msdyn_ismobile: WebAttribute<msdyn_workorder_Select, { msdyn_ismobile: boolean | null }, {  }>;
  msdyn_latitude: WebAttribute<msdyn_workorder_Select, { msdyn_latitude: number | null }, {  }>;
  msdyn_longitude: WebAttribute<msdyn_workorder_Select, { msdyn_longitude: number | null }, {  }>;
  msdyn_mapcontrol: WebAttribute<msdyn_workorder_Select, { msdyn_mapcontrol: string | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_workorder_Select, { msdyn_name: string | null }, {  }>;
  msdyn_opportunityid_guid: WebAttribute<msdyn_workorder_Select, { msdyn_opportunityid_guid: string | null }, { msdyn_opportunityid_formatted?: string }>;
  msdyn_parentworkorder_guid: WebAttribute<msdyn_workorder_Select, { msdyn_parentworkorder_guid: string | null }, { msdyn_parentworkorder_formatted?: string }>;
  msdyn_postalcode: WebAttribute<msdyn_workorder_Select, { msdyn_postalcode: string | null }, {  }>;
  msdyn_preferredresource_guid: WebAttribute<msdyn_workorder_Select, { msdyn_preferredresource_guid: string | null }, { msdyn_preferredresource_formatted?: string }>;
  msdyn_pricelist_guid: WebAttribute<msdyn_workorder_Select, { msdyn_pricelist_guid: string | null }, { msdyn_pricelist_formatted?: string }>;
  msdyn_primaryincidentdescription: WebAttribute<msdyn_workorder_Select, { msdyn_primaryincidentdescription: string | null }, {  }>;
  msdyn_primaryincidentestimatedduration: WebAttribute<msdyn_workorder_Select, { msdyn_primaryincidentestimatedduration: number | null }, {  }>;
  msdyn_primaryincidenttype_guid: WebAttribute<msdyn_workorder_Select, { msdyn_primaryincidenttype_guid: string | null }, { msdyn_primaryincidenttype_formatted?: string }>;
  msdyn_primaryresolution_guid: WebAttribute<msdyn_workorder_Select, { msdyn_primaryresolution_guid: string | null }, { msdyn_primaryresolution_formatted?: string }>;
  msdyn_priority_guid: WebAttribute<msdyn_workorder_Select, { msdyn_priority_guid: string | null }, { msdyn_priority_formatted?: string }>;
  msdyn_reportedbycontact_guid: WebAttribute<msdyn_workorder_Select, { msdyn_reportedbycontact_guid: string | null }, { msdyn_reportedbycontact_formatted?: string }>;
  msdyn_serviceaccount_guid: WebAttribute<msdyn_workorder_Select, { msdyn_serviceaccount_guid: string | null }, { msdyn_serviceaccount_formatted?: string }>;
  msdyn_servicerequest_guid: WebAttribute<msdyn_workorder_Select, { msdyn_servicerequest_guid: string | null }, { msdyn_servicerequest_formatted?: string }>;
  msdyn_serviceterritory_guid: WebAttribute<msdyn_workorder_Select, { msdyn_serviceterritory_guid: string | null }, { msdyn_serviceterritory_formatted?: string }>;
  msdyn_stateorprovince: WebAttribute<msdyn_workorder_Select, { msdyn_stateorprovince: string | null }, {  }>;
  msdyn_substatus_guid: WebAttribute<msdyn_workorder_Select, { msdyn_substatus_guid: string | null }, { msdyn_substatus_formatted?: string }>;
  msdyn_subtotalamount: WebAttribute<msdyn_workorder_Select, { msdyn_subtotalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_subtotalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_subtotalamount_base: WebAttribute<msdyn_workorder_Select, { msdyn_subtotalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_subtotalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_supportcontact_guid: WebAttribute<msdyn_workorder_Select, { msdyn_supportcontact_guid: string | null }, { msdyn_supportcontact_formatted?: string }>;
  msdyn_systemstatus: WebAttribute<msdyn_workorder_Select, { msdyn_systemstatus: msdyn_wosystemstatus | null }, { msdyn_systemstatus_formatted?: string }>;
  msdyn_taxable: WebAttribute<msdyn_workorder_Select, { msdyn_taxable: boolean | null }, {  }>;
  msdyn_taxcode_guid: WebAttribute<msdyn_workorder_Select, { msdyn_taxcode_guid: string | null }, { msdyn_taxcode_formatted?: string }>;
  msdyn_timeclosed: WebAttribute<msdyn_workorder_Select, { msdyn_timeclosed: Date | null }, { msdyn_timeclosed_formatted?: string }>;
  msdyn_timefrompromised: WebAttribute<msdyn_workorder_Select, { msdyn_timefrompromised: Date | null }, { msdyn_timefrompromised_formatted?: string }>;
  msdyn_timegroup_guid: WebAttribute<msdyn_workorder_Select, { msdyn_timegroup_guid: string | null }, { msdyn_timegroup_formatted?: string }>;
  msdyn_timegroupdetailselected_guid: WebAttribute<msdyn_workorder_Select, { msdyn_timegroupdetailselected_guid: string | null }, { msdyn_timegroupdetailselected_formatted?: string }>;
  msdyn_timetopromised: WebAttribute<msdyn_workorder_Select, { msdyn_timetopromised: Date | null }, { msdyn_timetopromised_formatted?: string }>;
  msdyn_timewindowend: WebAttribute<msdyn_workorder_Select, { msdyn_timewindowend: Date | null }, { msdyn_timewindowend_formatted?: string }>;
  msdyn_timewindowstart: WebAttribute<msdyn_workorder_Select, { msdyn_timewindowstart: Date | null }, { msdyn_timewindowstart_formatted?: string }>;
  msdyn_totalamount: WebAttribute<msdyn_workorder_Select, { msdyn_totalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalamount_base: WebAttribute<msdyn_workorder_Select, { msdyn_totalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalestimatedduration: WebAttribute<msdyn_workorder_Select, { msdyn_totalestimatedduration: number | null }, {  }>;
  msdyn_totalsalestax: WebAttribute<msdyn_workorder_Select, { msdyn_totalsalestax: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalsalestax_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalsalestax_base: WebAttribute<msdyn_workorder_Select, { msdyn_totalsalestax_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalsalestax_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_workhourtemplate_guid: WebAttribute<msdyn_workorder_Select, { msdyn_workhourtemplate_guid: string | null }, { msdyn_workhourtemplate_formatted?: string }>;
  msdyn_worklocation: WebAttribute<msdyn_workorder_Select, { msdyn_worklocation: msdyn_worklocation | null }, { msdyn_worklocation_formatted?: string }>;
  msdyn_workorderarrivaltimekpiid_guid: WebAttribute<msdyn_workorder_Select, { msdyn_workorderarrivaltimekpiid_guid: string | null }, { msdyn_workorderarrivaltimekpiid_formatted?: string }>;
  msdyn_workorderid: WebAttribute<msdyn_workorder_Select, { msdyn_workorderid: string | null }, {  }>;
  msdyn_workorderresolutionkpiid_guid: WebAttribute<msdyn_workorder_Select, { msdyn_workorderresolutionkpiid_guid: string | null }, { msdyn_workorderresolutionkpiid_formatted?: string }>;
  msdyn_workordersummary: WebAttribute<msdyn_workorder_Select, { msdyn_workordersummary: string | null }, {  }>;
  msdyn_workordertype_guid: WebAttribute<msdyn_workorder_Select, { msdyn_workordertype_guid: string | null }, { msdyn_workordertype_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_workorder_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_workorder_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_workorder_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_workorder_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_workorder_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  processid: WebAttribute<msdyn_workorder_Select, { processid: string | null }, {  }>;
  stageid: WebAttribute<msdyn_workorder_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<msdyn_workorder_Select, { statecode: msdyn_workorder_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_workorder_Select, { statuscode: msdyn_workorder_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_workorder_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_workorder_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<msdyn_workorder_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_workorder_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_workorder_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_workorder_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_address1: string;
  msdyn_address2: string;
  msdyn_address3: string;
  msdyn_addressname: string;
  msdyn_agreement_guid: XQW.Guid;
  msdyn_autonumbering: string;
  msdyn_billingaccount_guid: XQW.Guid;
  msdyn_bookingsummary: string;
  msdyn_childindex: number;
  msdyn_city: string;
  msdyn_closedby_guid: XQW.Guid;
  msdyn_completedon: Date;
  msdyn_country: string;
  msdyn_customerasset_guid: XQW.Guid;
  msdyn_datewindowend: Date;
  msdyn_datewindowstart: Date;
  msdyn_estimatesubtotalamount: number;
  msdyn_estimatesubtotalamount_base: number;
  msdyn_firstarrivedon: Date;
  msdyn_followupnote: string;
  msdyn_followuprequired: boolean;
  msdyn_functionallocation_guid: XQW.Guid;
  msdyn_instructions: string;
  msdyn_internalflags: string;
  msdyn_iotalert_guid: XQW.Guid;
  msdyn_isfollowup: boolean;
  msdyn_ismobile: boolean;
  msdyn_latitude: number;
  msdyn_longitude: number;
  msdyn_mapcontrol: string;
  msdyn_name: string;
  msdyn_opportunityid_guid: XQW.Guid;
  msdyn_parentworkorder_guid: XQW.Guid;
  msdyn_postalcode: string;
  msdyn_preferredresource_guid: XQW.Guid;
  msdyn_pricelist_guid: XQW.Guid;
  msdyn_primaryincidentdescription: string;
  msdyn_primaryincidentestimatedduration: number;
  msdyn_primaryincidenttype_guid: XQW.Guid;
  msdyn_primaryresolution_guid: XQW.Guid;
  msdyn_priority_guid: XQW.Guid;
  msdyn_reportedbycontact_guid: XQW.Guid;
  msdyn_serviceaccount_guid: XQW.Guid;
  msdyn_servicerequest_guid: XQW.Guid;
  msdyn_serviceterritory_guid: XQW.Guid;
  msdyn_stateorprovince: string;
  msdyn_substatus_guid: XQW.Guid;
  msdyn_subtotalamount: number;
  msdyn_subtotalamount_base: number;
  msdyn_supportcontact_guid: XQW.Guid;
  msdyn_systemstatus: msdyn_wosystemstatus;
  msdyn_taxable: boolean;
  msdyn_taxcode_guid: XQW.Guid;
  msdyn_timeclosed: Date;
  msdyn_timefrompromised: Date;
  msdyn_timegroup_guid: XQW.Guid;
  msdyn_timegroupdetailselected_guid: XQW.Guid;
  msdyn_timetopromised: Date;
  msdyn_timewindowend: Date;
  msdyn_timewindowstart: Date;
  msdyn_totalamount: number;
  msdyn_totalamount_base: number;
  msdyn_totalestimatedduration: number;
  msdyn_totalsalestax: number;
  msdyn_totalsalestax_base: number;
  msdyn_workhourtemplate_guid: XQW.Guid;
  msdyn_worklocation: msdyn_worklocation;
  msdyn_workorderarrivaltimekpiid_guid: XQW.Guid;
  msdyn_workorderid: XQW.Guid;
  msdyn_workorderresolutionkpiid_guid: XQW.Guid;
  msdyn_workordersummary: string;
  msdyn_workordertype_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  processid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: msdyn_workorder_statecode;
  statuscode: msdyn_workorder_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_workorder_Expand {
  bpf_msdyn_workorder_msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b: WebExpand<msdyn_workorder_Expand, msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_Select, msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_Filter, { bpf_msdyn_workorder_msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b: msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_Result[] }>;
  bpf_msdyn_workorder_msdyn_bpf_989e9b1857e24af18787d5143b67523b: WebExpand<msdyn_workorder_Expand, msdyn_bpf_989e9b1857e24af18787d5143b67523b_Select, msdyn_bpf_989e9b1857e24af18787d5143b67523b_Filter, { bpf_msdyn_workorder_msdyn_bpf_989e9b1857e24af18787d5143b67523b: msdyn_bpf_989e9b1857e24af18787d5143b67523b_Result[] }>;
  bpf_msdyn_workorder_msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39: WebExpand<msdyn_workorder_Expand, msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_Select, msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_Filter, { bpf_msdyn_workorder_msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39: msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_Result[] }>;
  createdby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_FunctionalLocation: WebExpand<msdyn_workorder_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { msdyn_FunctionalLocation: msdyn_FunctionalLocation_Result }>;
  msdyn_IoTAlert: WebExpand<msdyn_workorder_Expand, msdyn_iotalert_Select, msdyn_iotalert_Filter, { msdyn_IoTAlert: msdyn_iotalert_Result }>;
  msdyn_PrimaryResolution: WebExpand<msdyn_workorder_Expand, msdyn_resolution_Select, msdyn_resolution_Filter, { msdyn_PrimaryResolution: msdyn_resolution_Result }>;
  msdyn_SupportContact: WebExpand<msdyn_workorder_Expand, BookableResource_Select, BookableResource_Filter, { msdyn_SupportContact: BookableResource_Result }>;
  msdyn_agreement: WebExpand<msdyn_workorder_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { msdyn_agreement: msdyn_agreement_Result }>;
  msdyn_billingaccount: WebExpand<msdyn_workorder_Expand, Account_Select, Account_Filter, { msdyn_billingaccount: Account_Result }>;
  msdyn_closedby: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { msdyn_closedby: SystemUser_Result }>;
  msdyn_customerasset: WebExpand<msdyn_workorder_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_customerasset: msdyn_customerasset_Result }>;
  msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder: WebExpand<msdyn_workorder_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder: BookableResourceBooking_Result[] }>;
  msdyn_msdyn_workorder_invoicedetail: WebExpand<msdyn_workorder_Expand, InvoiceDetail_Select, InvoiceDetail_Filter, { msdyn_msdyn_workorder_invoicedetail: InvoiceDetail_Result[] }>;
  msdyn_msdyn_workorder_msdyn_actual_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_actual_Select, msdyn_actual_Filter, { msdyn_msdyn_workorder_msdyn_actual_WorkOrder: msdyn_actual_Result[] }>;
  msdyn_msdyn_workorder_msdyn_agreementbookingdate_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_agreementbookingdate_Select, msdyn_agreementbookingdate_Filter, { msdyn_msdyn_workorder_msdyn_agreementbookingdate_WorkOrder: msdyn_agreementbookingdate_Result[] }>;
  msdyn_msdyn_workorder_msdyn_inventoryjournal_AllocatedToWorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_inventoryjournal_Select, msdyn_inventoryjournal_Filter, { msdyn_msdyn_workorder_msdyn_inventoryjournal_AllocatedToWorkOrder: msdyn_inventoryjournal_Result[] }>;
  msdyn_msdyn_workorder_msdyn_iotalert_Workorder: WebExpand<msdyn_workorder_Expand, msdyn_iotalert_Select, msdyn_iotalert_Filter, { msdyn_msdyn_workorder_msdyn_iotalert_Workorder: msdyn_iotalert_Result[] }>;
  msdyn_msdyn_workorder_msdyn_payment_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_payment_Select, msdyn_payment_Filter, { msdyn_msdyn_workorder_msdyn_payment_WorkOrder: msdyn_payment_Result[] }>;
  msdyn_msdyn_workorder_msdyn_paymentdetail_Workorder: WebExpand<msdyn_workorder_Expand, msdyn_paymentdetail_Select, msdyn_paymentdetail_Filter, { msdyn_msdyn_workorder_msdyn_paymentdetail_Workorder: msdyn_paymentdetail_Result[] }>;
  msdyn_msdyn_workorder_msdyn_purchaseorder_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_purchaseorder_Select, msdyn_purchaseorder_Filter, { msdyn_msdyn_workorder_msdyn_purchaseorder_WorkOrder: msdyn_purchaseorder_Result[] }>;
  msdyn_msdyn_workorder_msdyn_purchaseorderproduct_AssociateToWorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_purchaseorderproduct_Select, msdyn_purchaseorderproduct_Filter, { msdyn_msdyn_workorder_msdyn_purchaseorderproduct_AssociateToWorkOrder: msdyn_purchaseorderproduct_Result[] }>;
  msdyn_msdyn_workorder_msdyn_purchaseorderreceiptproduct_AssociateToWorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_purchaseorderreceiptproduct_Select, msdyn_purchaseorderreceiptproduct_Filter, { msdyn_msdyn_workorder_msdyn_purchaseorderreceiptproduct_AssociateToWorkOrder: msdyn_purchaseorderreceiptproduct_Result[] }>;
  msdyn_msdyn_workorder_msdyn_requirementcharacteristic_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_requirementcharacteristic_Select, msdyn_requirementcharacteristic_Filter, { msdyn_msdyn_workorder_msdyn_requirementcharacteristic_WorkOrder: msdyn_requirementcharacteristic_Result[] }>;
  msdyn_msdyn_workorder_msdyn_requirementresourcepreference_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_requirementresourcepreference_Select, msdyn_requirementresourcepreference_Filter, { msdyn_msdyn_workorder_msdyn_requirementresourcepreference_WorkOrder: msdyn_requirementresourcepreference_Result[] }>;
  msdyn_msdyn_workorder_msdyn_resourcerequirement_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_resourcerequirement_Select, msdyn_resourcerequirement_Filter, { msdyn_msdyn_workorder_msdyn_resourcerequirement_WorkOrder: msdyn_resourcerequirement_Result[] }>;
  msdyn_msdyn_workorder_msdyn_rma_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_rma_Select, msdyn_rma_Filter, { msdyn_msdyn_workorder_msdyn_rma_WorkOrder: msdyn_rma_Result[] }>;
  msdyn_msdyn_workorder_msdyn_rtv_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_rtv_Select, msdyn_rtv_Filter, { msdyn_msdyn_workorder_msdyn_rtv_WorkOrder: msdyn_rtv_Result[] }>;
  msdyn_msdyn_workorder_msdyn_rtvproduct_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_rtvproduct_Select, msdyn_rtvproduct_Filter, { msdyn_msdyn_workorder_msdyn_rtvproduct_WorkOrder: msdyn_rtvproduct_Result[] }>;
  msdyn_msdyn_workorder_msdyn_timeentry_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_timeentry_Select, msdyn_timeentry_Filter, { msdyn_msdyn_workorder_msdyn_timeentry_WorkOrder: msdyn_timeentry_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workorder_ParentWorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_msdyn_workorder_msdyn_workorder_ParentWorkOrder: msdyn_workorder_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workordercharacteristic_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workordercharacteristic_Select, msdyn_workordercharacteristic_Filter, { msdyn_msdyn_workorder_msdyn_workordercharacteristic_WorkOrder: msdyn_workordercharacteristic_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workorderincident_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workorderincident_Select, msdyn_workorderincident_Filter, { msdyn_msdyn_workorder_msdyn_workorderincident_WorkOrder: msdyn_workorderincident_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workorderproduct_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { msdyn_msdyn_workorder_msdyn_workorderproduct_WorkOrder: msdyn_workorderproduct_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workorderresolution_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workorderresolution_Select, msdyn_workorderresolution_Filter, { msdyn_msdyn_workorder_msdyn_workorderresolution_WorkOrder: msdyn_workorderresolution_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workorderresourcerestriction_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workorderresourcerestriction_Select, msdyn_workorderresourcerestriction_Filter, { msdyn_msdyn_workorder_msdyn_workorderresourcerestriction_WorkOrder: msdyn_workorderresourcerestriction_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workorderservice_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { msdyn_msdyn_workorder_msdyn_workorderservice_WorkOrder: msdyn_workorderservice_Result[] }>;
  msdyn_msdyn_workorder_msdyn_workorderservicetask_WorkOrder: WebExpand<msdyn_workorder_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { msdyn_msdyn_workorder_msdyn_workorderservicetask_WorkOrder: msdyn_workorderservicetask_Result[] }>;
  msdyn_opportunityid: WebExpand<msdyn_workorder_Expand, Opportunity_Select, Opportunity_Filter, { msdyn_opportunityid: Opportunity_Result }>;
  msdyn_parentworkorder_msdyn_workorder: WebExpand<msdyn_workorder_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_parentworkorder_msdyn_workorder: msdyn_workorder_Result }>;
  msdyn_preferredresource: WebExpand<msdyn_workorder_Expand, BookableResource_Select, BookableResource_Filter, { msdyn_preferredresource: BookableResource_Result }>;
  msdyn_pricelist: WebExpand<msdyn_workorder_Expand, PriceLevel_Select, PriceLevel_Filter, { msdyn_pricelist: PriceLevel_Result }>;
  msdyn_primaryincidenttype: WebExpand<msdyn_workorder_Expand, msdyn_incidenttype_Select, msdyn_incidenttype_Filter, { msdyn_primaryincidenttype: msdyn_incidenttype_Result }>;
  msdyn_priority: WebExpand<msdyn_workorder_Expand, msdyn_priority_Select, msdyn_priority_Filter, { msdyn_priority: msdyn_priority_Result }>;
  msdyn_reportedbycontact: WebExpand<msdyn_workorder_Expand, Contact_Select, Contact_Filter, { msdyn_reportedbycontact: Contact_Result }>;
  msdyn_serviceaccount: WebExpand<msdyn_workorder_Expand, Account_Select, Account_Filter, { msdyn_serviceaccount: Account_Result }>;
  msdyn_servicerequest: WebExpand<msdyn_workorder_Expand, Incident_Select, Incident_Filter, { msdyn_servicerequest: Incident_Result }>;
  msdyn_serviceterritory: WebExpand<msdyn_workorder_Expand, Territory_Select, Territory_Filter, { msdyn_serviceterritory: Territory_Result }>;
  msdyn_substatus: WebExpand<msdyn_workorder_Expand, msdyn_workordersubstatus_Select, msdyn_workordersubstatus_Filter, { msdyn_substatus: msdyn_workordersubstatus_Result }>;
  msdyn_taxcode: WebExpand<msdyn_workorder_Expand, msdyn_taxcode_Select, msdyn_taxcode_Filter, { msdyn_taxcode: msdyn_taxcode_Result }>;
  msdyn_timegroup: WebExpand<msdyn_workorder_Expand, msdyn_timegroup_Select, msdyn_timegroup_Filter, { msdyn_timegroup: msdyn_timegroup_Result }>;
  msdyn_timegroupdetailselected: WebExpand<msdyn_workorder_Expand, msdyn_timegroupdetail_Select, msdyn_timegroupdetail_Filter, { msdyn_timegroupdetailselected: msdyn_timegroupdetail_Result }>;
  msdyn_workhourtemplate: WebExpand<msdyn_workorder_Expand, msdyn_workhourtemplate_Select, msdyn_workhourtemplate_Filter, { msdyn_workhourtemplate: msdyn_workhourtemplate_Result }>;
  msdyn_workorder_ActivityPointers: WebExpand<msdyn_workorder_Expand, ActivityPointer_Select, ActivityPointer_Filter, { msdyn_workorder_ActivityPointers: ActivityPointer_Result[] }>;
  msdyn_workorder_Annotations: WebExpand<msdyn_workorder_Expand, Annotation_Select, Annotation_Filter, { msdyn_workorder_Annotations: Annotation_Result[] }>;
  msdyn_workorder_Appointments: WebExpand<msdyn_workorder_Expand, Appointment_Select, Appointment_Filter, { msdyn_workorder_Appointments: Appointment_Result[] }>;
  msdyn_workorder_AsyncOperations: WebExpand<msdyn_workorder_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_workorder_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_workorder_BulkDeleteFailures: WebExpand<msdyn_workorder_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_workorder_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_workorder_DuplicateBaseRecord: WebExpand<msdyn_workorder_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_workorder_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_workorder_DuplicateMatchingRecord: WebExpand<msdyn_workorder_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_workorder_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_workorder_Emails: WebExpand<msdyn_workorder_Expand, Email_Select, Email_Filter, { msdyn_workorder_Emails: Email_Result[] }>;
  msdyn_workorder_Faxes: WebExpand<msdyn_workorder_Expand, Fax_Select, Fax_Filter, { msdyn_workorder_Faxes: Fax_Result[] }>;
  msdyn_workorder_Letters: WebExpand<msdyn_workorder_Expand, Letter_Select, Letter_Filter, { msdyn_workorder_Letters: Letter_Result[] }>;
  msdyn_workorder_MailboxTrackingFolders: WebExpand<msdyn_workorder_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_workorder_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_workorder_PhoneCalls: WebExpand<msdyn_workorder_Expand, PhoneCall_Select, PhoneCall_Filter, { msdyn_workorder_PhoneCalls: PhoneCall_Result[] }>;
  msdyn_workorder_PrincipalObjectAttributeAccesses: WebExpand<msdyn_workorder_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_workorder_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_workorder_ProcessSession: WebExpand<msdyn_workorder_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_workorder_ProcessSession: ProcessSession_Result[] }>;
  msdyn_workorder_QueueItems: WebExpand<msdyn_workorder_Expand, QueueItem_Select, QueueItem_Filter, { msdyn_workorder_QueueItems: QueueItem_Result[] }>;
  msdyn_workorder_RecurringAppointmentMasters: WebExpand<msdyn_workorder_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { msdyn_workorder_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  msdyn_workorder_ServiceAppointments: WebExpand<msdyn_workorder_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_workorder_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_workorder_SharePointDocumentLocations: WebExpand<msdyn_workorder_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { msdyn_workorder_SharePointDocumentLocations: SharePointDocumentLocation_Result[] }>;
  msdyn_workorder_SharePointDocuments: WebExpand<msdyn_workorder_Expand, SharePointDocument_Select, SharePointDocument_Filter, { msdyn_workorder_SharePointDocuments: SharePointDocument_Result[] }>;
  msdyn_workorder_SocialActivities: WebExpand<msdyn_workorder_Expand, SocialActivity_Select, SocialActivity_Filter, { msdyn_workorder_SocialActivities: SocialActivity_Result[] }>;
  msdyn_workorder_SyncErrors: WebExpand<msdyn_workorder_Expand, SyncError_Select, SyncError_Filter, { msdyn_workorder_SyncErrors: SyncError_Result[] }>;
  msdyn_workorder_Tasks: WebExpand<msdyn_workorder_Expand, Task_Select, Task_Filter, { msdyn_workorder_Tasks: Task_Result[] }>;
  msdyn_workorder_UserEntityInstanceDatas: WebExpand<msdyn_workorder_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_workorder_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_workorder_connections1: WebExpand<msdyn_workorder_Expand, Connection_Select, Connection_Filter, { msdyn_workorder_connections1: Connection_Result[] }>;
  msdyn_workorder_connections2: WebExpand<msdyn_workorder_Expand, Connection_Select, Connection_Filter, { msdyn_workorder_connections2: Connection_Result[] }>;
  msdyn_workorder_msdyn_approvals: WebExpand<msdyn_workorder_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_workorder_msdyn_approvals: msdyn_approval_Result[] }>;
  msdyn_workorder_msdyn_bookingalerts: WebExpand<msdyn_workorder_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_workorder_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  msdyn_workorder_msdyn_ocliveworkitems: WebExpand<msdyn_workorder_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_workorder_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  msdyn_workorder_msdyn_ocoutboundmessages: WebExpand<msdyn_workorder_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_workorder_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_workorder_msdyn_ocsessions: WebExpand<msdyn_workorder_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_workorder_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  msdyn_workorder_msfp_alerts: WebExpand<msdyn_workorder_Expand, msfp_alert_Select, msfp_alert_Filter, { msdyn_workorder_msfp_alerts: msfp_alert_Result[] }>;
  msdyn_workorder_msfp_surveyinvites: WebExpand<msdyn_workorder_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msdyn_workorder_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  msdyn_workorder_msfp_surveyresponses: WebExpand<msdyn_workorder_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msdyn_workorder_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  msdyn_workorderarrivaltimekpiid: WebExpand<msdyn_workorder_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { msdyn_workorderarrivaltimekpiid: SLAKPIInstance_Result }>;
  msdyn_workorderresolutionkpiid: WebExpand<msdyn_workorder_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { msdyn_workorderresolutionkpiid: SLAKPIInstance_Result }>;
  msdyn_workordertype: WebExpand<msdyn_workorder_Expand, msdyn_workordertype_Select, msdyn_workordertype_Filter, { msdyn_workordertype: msdyn_workordertype_Result }>;
  navigationPropertyNameNotDefined: WebExpand<msdyn_workorder_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { navigationPropertyNameNotDefined: KnowledgeBaseRecord_Result[] }>;
  navigationPropertyNameNotDefined1: WebExpand<msdyn_workorder_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { navigationPropertyNameNotDefined: KnowledgeArticle_Result[] }>;
  ownerid: WebExpand<msdyn_workorder_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_workorder_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_workorder_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_workorder_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  stageid: WebExpand<msdyn_workorder_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid: ProcessStage_Result }>;
  transactioncurrencyid: WebExpand<msdyn_workorder_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface msdyn_workorder_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_agreement_formatted?: string;
  msdyn_billingaccount_formatted?: string;
  msdyn_closedby_formatted?: string;
  msdyn_completedon_formatted?: string;
  msdyn_customerasset_formatted?: string;
  msdyn_datewindowend_formatted?: string;
  msdyn_datewindowstart_formatted?: string;
  msdyn_estimatesubtotalamount_base_formatted?: string;
  msdyn_estimatesubtotalamount_formatted?: string;
  msdyn_firstarrivedon_formatted?: string;
  msdyn_functionallocation_formatted?: string;
  msdyn_iotalert_formatted?: string;
  msdyn_opportunityid_formatted?: string;
  msdyn_parentworkorder_formatted?: string;
  msdyn_preferredresource_formatted?: string;
  msdyn_pricelist_formatted?: string;
  msdyn_primaryincidenttype_formatted?: string;
  msdyn_primaryresolution_formatted?: string;
  msdyn_priority_formatted?: string;
  msdyn_reportedbycontact_formatted?: string;
  msdyn_serviceaccount_formatted?: string;
  msdyn_servicerequest_formatted?: string;
  msdyn_serviceterritory_formatted?: string;
  msdyn_substatus_formatted?: string;
  msdyn_subtotalamount_base_formatted?: string;
  msdyn_subtotalamount_formatted?: string;
  msdyn_supportcontact_formatted?: string;
  msdyn_systemstatus_formatted?: string;
  msdyn_taxcode_formatted?: string;
  msdyn_timeclosed_formatted?: string;
  msdyn_timefrompromised_formatted?: string;
  msdyn_timegroup_formatted?: string;
  msdyn_timegroupdetailselected_formatted?: string;
  msdyn_timetopromised_formatted?: string;
  msdyn_timewindowend_formatted?: string;
  msdyn_timewindowstart_formatted?: string;
  msdyn_totalamount_base_formatted?: string;
  msdyn_totalamount_formatted?: string;
  msdyn_totalsalestax_base_formatted?: string;
  msdyn_totalsalestax_formatted?: string;
  msdyn_workhourtemplate_formatted?: string;
  msdyn_worklocation_formatted?: string;
  msdyn_workorderarrivaltimekpiid_formatted?: string;
  msdyn_workorderresolutionkpiid_formatted?: string;
  msdyn_workordertype_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface msdyn_workorder_Result extends msdyn_workorder_Base, msdyn_workorder_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_agreement_guid: string | null;
  msdyn_billingaccount_guid: string | null;
  msdyn_closedby_guid: string | null;
  msdyn_customerasset_guid: string | null;
  msdyn_functionallocation_guid: string | null;
  msdyn_iotalert_guid: string | null;
  msdyn_opportunityid_guid: string | null;
  msdyn_parentworkorder_guid: string | null;
  msdyn_preferredresource_guid: string | null;
  msdyn_pricelist_guid: string | null;
  msdyn_primaryincidenttype_guid: string | null;
  msdyn_primaryresolution_guid: string | null;
  msdyn_priority_guid: string | null;
  msdyn_reportedbycontact_guid: string | null;
  msdyn_serviceaccount_guid: string | null;
  msdyn_servicerequest_guid: string | null;
  msdyn_serviceterritory_guid: string | null;
  msdyn_substatus_guid: string | null;
  msdyn_supportcontact_guid: string | null;
  msdyn_taxcode_guid: string | null;
  msdyn_timegroup_guid: string | null;
  msdyn_timegroupdetailselected_guid: string | null;
  msdyn_workhourtemplate_guid: string | null;
  msdyn_workorderarrivaltimekpiid_guid: string | null;
  msdyn_workorderresolutionkpiid_guid: string | null;
  msdyn_workordertype_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface msdyn_workorder_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_FunctionalLocation: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  msdyn_IoTAlert: WebMappingRetrieve<msdyn_iotalert_Select,msdyn_iotalert_Expand,msdyn_iotalert_Filter,msdyn_iotalert_Fixed,msdyn_iotalert_Result,msdyn_iotalert_FormattedResult>;
  msdyn_PrimaryResolution: WebMappingRetrieve<msdyn_resolution_Select,msdyn_resolution_Expand,msdyn_resolution_Filter,msdyn_resolution_Fixed,msdyn_resolution_Result,msdyn_resolution_FormattedResult>;
  msdyn_SupportContact: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  msdyn_agreement: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  msdyn_billingaccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_closedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_opportunityid: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  msdyn_parentworkorder_msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  msdyn_preferredresource: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  msdyn_pricelist: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  msdyn_primaryincidenttype: WebMappingRetrieve<msdyn_incidenttype_Select,msdyn_incidenttype_Expand,msdyn_incidenttype_Filter,msdyn_incidenttype_Fixed,msdyn_incidenttype_Result,msdyn_incidenttype_FormattedResult>;
  msdyn_priority: WebMappingRetrieve<msdyn_priority_Select,msdyn_priority_Expand,msdyn_priority_Filter,msdyn_priority_Fixed,msdyn_priority_Result,msdyn_priority_FormattedResult>;
  msdyn_reportedbycontact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  msdyn_serviceaccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_servicerequest: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  msdyn_serviceterritory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  msdyn_substatus: WebMappingRetrieve<msdyn_workordersubstatus_Select,msdyn_workordersubstatus_Expand,msdyn_workordersubstatus_Filter,msdyn_workordersubstatus_Fixed,msdyn_workordersubstatus_Result,msdyn_workordersubstatus_FormattedResult>;
  msdyn_taxcode: WebMappingRetrieve<msdyn_taxcode_Select,msdyn_taxcode_Expand,msdyn_taxcode_Filter,msdyn_taxcode_Fixed,msdyn_taxcode_Result,msdyn_taxcode_FormattedResult>;
  msdyn_timegroup: WebMappingRetrieve<msdyn_timegroup_Select,msdyn_timegroup_Expand,msdyn_timegroup_Filter,msdyn_timegroup_Fixed,msdyn_timegroup_Result,msdyn_timegroup_FormattedResult>;
  msdyn_timegroupdetailselected: WebMappingRetrieve<msdyn_timegroupdetail_Select,msdyn_timegroupdetail_Expand,msdyn_timegroupdetail_Filter,msdyn_timegroupdetail_Fixed,msdyn_timegroupdetail_Result,msdyn_timegroupdetail_FormattedResult>;
  msdyn_workhourtemplate: WebMappingRetrieve<msdyn_workhourtemplate_Select,msdyn_workhourtemplate_Expand,msdyn_workhourtemplate_Filter,msdyn_workhourtemplate_Fixed,msdyn_workhourtemplate_Result,msdyn_workhourtemplate_FormattedResult>;
  msdyn_workorderarrivaltimekpiid: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  msdyn_workorderresolutionkpiid: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  msdyn_workordertype: WebMappingRetrieve<msdyn_workordertype_Select,msdyn_workordertype_Expand,msdyn_workordertype_Filter,msdyn_workordertype_Fixed,msdyn_workordertype_Result,msdyn_workordertype_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  stageid: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface msdyn_workorder_RelatedMany {
  bpf_msdyn_workorder_msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b: WebMappingRetrieve<msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_Select,msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_Expand,msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_Filter,msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_Fixed,msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_Result,msdyn_bpf_477c16f59170487b8b4dc895c5dcd09b_FormattedResult>;
  bpf_msdyn_workorder_msdyn_bpf_989e9b1857e24af18787d5143b67523b: WebMappingRetrieve<msdyn_bpf_989e9b1857e24af18787d5143b67523b_Select,msdyn_bpf_989e9b1857e24af18787d5143b67523b_Expand,msdyn_bpf_989e9b1857e24af18787d5143b67523b_Filter,msdyn_bpf_989e9b1857e24af18787d5143b67523b_Fixed,msdyn_bpf_989e9b1857e24af18787d5143b67523b_Result,msdyn_bpf_989e9b1857e24af18787d5143b67523b_FormattedResult>;
  bpf_msdyn_workorder_msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39: WebMappingRetrieve<msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_Select,msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_Expand,msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_Filter,msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_Fixed,msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_Result,msdyn_bpf_d3d97bac8c294105840e99e37a9d1c39_FormattedResult>;
  msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  msdyn_msdyn_workorder_invoicedetail: WebMappingRetrieve<InvoiceDetail_Select,InvoiceDetail_Expand,InvoiceDetail_Filter,InvoiceDetail_Fixed,InvoiceDetail_Result,InvoiceDetail_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_actual_WorkOrder: WebMappingRetrieve<msdyn_actual_Select,msdyn_actual_Expand,msdyn_actual_Filter,msdyn_actual_Fixed,msdyn_actual_Result,msdyn_actual_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_agreementbookingdate_WorkOrder: WebMappingRetrieve<msdyn_agreementbookingdate_Select,msdyn_agreementbookingdate_Expand,msdyn_agreementbookingdate_Filter,msdyn_agreementbookingdate_Fixed,msdyn_agreementbookingdate_Result,msdyn_agreementbookingdate_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_inventoryjournal_AllocatedToWorkOrder: WebMappingRetrieve<msdyn_inventoryjournal_Select,msdyn_inventoryjournal_Expand,msdyn_inventoryjournal_Filter,msdyn_inventoryjournal_Fixed,msdyn_inventoryjournal_Result,msdyn_inventoryjournal_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_iotalert_Workorder: WebMappingRetrieve<msdyn_iotalert_Select,msdyn_iotalert_Expand,msdyn_iotalert_Filter,msdyn_iotalert_Fixed,msdyn_iotalert_Result,msdyn_iotalert_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_payment_WorkOrder: WebMappingRetrieve<msdyn_payment_Select,msdyn_payment_Expand,msdyn_payment_Filter,msdyn_payment_Fixed,msdyn_payment_Result,msdyn_payment_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_paymentdetail_Workorder: WebMappingRetrieve<msdyn_paymentdetail_Select,msdyn_paymentdetail_Expand,msdyn_paymentdetail_Filter,msdyn_paymentdetail_Fixed,msdyn_paymentdetail_Result,msdyn_paymentdetail_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_purchaseorder_WorkOrder: WebMappingRetrieve<msdyn_purchaseorder_Select,msdyn_purchaseorder_Expand,msdyn_purchaseorder_Filter,msdyn_purchaseorder_Fixed,msdyn_purchaseorder_Result,msdyn_purchaseorder_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_purchaseorderproduct_AssociateToWorkOrder: WebMappingRetrieve<msdyn_purchaseorderproduct_Select,msdyn_purchaseorderproduct_Expand,msdyn_purchaseorderproduct_Filter,msdyn_purchaseorderproduct_Fixed,msdyn_purchaseorderproduct_Result,msdyn_purchaseorderproduct_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_purchaseorderreceiptproduct_AssociateToWorkOrder: WebMappingRetrieve<msdyn_purchaseorderreceiptproduct_Select,msdyn_purchaseorderreceiptproduct_Expand,msdyn_purchaseorderreceiptproduct_Filter,msdyn_purchaseorderreceiptproduct_Fixed,msdyn_purchaseorderreceiptproduct_Result,msdyn_purchaseorderreceiptproduct_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_requirementcharacteristic_WorkOrder: WebMappingRetrieve<msdyn_requirementcharacteristic_Select,msdyn_requirementcharacteristic_Expand,msdyn_requirementcharacteristic_Filter,msdyn_requirementcharacteristic_Fixed,msdyn_requirementcharacteristic_Result,msdyn_requirementcharacteristic_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_requirementresourcepreference_WorkOrder: WebMappingRetrieve<msdyn_requirementresourcepreference_Select,msdyn_requirementresourcepreference_Expand,msdyn_requirementresourcepreference_Filter,msdyn_requirementresourcepreference_Fixed,msdyn_requirementresourcepreference_Result,msdyn_requirementresourcepreference_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_resourcerequirement_WorkOrder: WebMappingRetrieve<msdyn_resourcerequirement_Select,msdyn_resourcerequirement_Expand,msdyn_resourcerequirement_Filter,msdyn_resourcerequirement_Fixed,msdyn_resourcerequirement_Result,msdyn_resourcerequirement_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_rma_WorkOrder: WebMappingRetrieve<msdyn_rma_Select,msdyn_rma_Expand,msdyn_rma_Filter,msdyn_rma_Fixed,msdyn_rma_Result,msdyn_rma_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_rtv_WorkOrder: WebMappingRetrieve<msdyn_rtv_Select,msdyn_rtv_Expand,msdyn_rtv_Filter,msdyn_rtv_Fixed,msdyn_rtv_Result,msdyn_rtv_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_rtvproduct_WorkOrder: WebMappingRetrieve<msdyn_rtvproduct_Select,msdyn_rtvproduct_Expand,msdyn_rtvproduct_Filter,msdyn_rtvproduct_Fixed,msdyn_rtvproduct_Result,msdyn_rtvproduct_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_timeentry_WorkOrder: WebMappingRetrieve<msdyn_timeentry_Select,msdyn_timeentry_Expand,msdyn_timeentry_Filter,msdyn_timeentry_Fixed,msdyn_timeentry_Result,msdyn_timeentry_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workorder_ParentWorkOrder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workordercharacteristic_WorkOrder: WebMappingRetrieve<msdyn_workordercharacteristic_Select,msdyn_workordercharacteristic_Expand,msdyn_workordercharacteristic_Filter,msdyn_workordercharacteristic_Fixed,msdyn_workordercharacteristic_Result,msdyn_workordercharacteristic_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workorderincident_WorkOrder: WebMappingRetrieve<msdyn_workorderincident_Select,msdyn_workorderincident_Expand,msdyn_workorderincident_Filter,msdyn_workorderincident_Fixed,msdyn_workorderincident_Result,msdyn_workorderincident_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workorderproduct_WorkOrder: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workorderresolution_WorkOrder: WebMappingRetrieve<msdyn_workorderresolution_Select,msdyn_workorderresolution_Expand,msdyn_workorderresolution_Filter,msdyn_workorderresolution_Fixed,msdyn_workorderresolution_Result,msdyn_workorderresolution_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workorderresourcerestriction_WorkOrder: WebMappingRetrieve<msdyn_workorderresourcerestriction_Select,msdyn_workorderresourcerestriction_Expand,msdyn_workorderresourcerestriction_Filter,msdyn_workorderresourcerestriction_Fixed,msdyn_workorderresourcerestriction_Result,msdyn_workorderresourcerestriction_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workorderservice_WorkOrder: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  msdyn_msdyn_workorder_msdyn_workorderservicetask_WorkOrder: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  msdyn_workorder_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  msdyn_workorder_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_workorder_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_workorder_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_workorder_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_workorder_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_workorder_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_workorder_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_workorder_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  msdyn_workorder_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  msdyn_workorder_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_workorder_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  msdyn_workorder_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_workorder_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_workorder_QueueItems: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  msdyn_workorder_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  msdyn_workorder_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_workorder_SharePointDocumentLocations: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  msdyn_workorder_SharePointDocuments: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  msdyn_workorder_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  msdyn_workorder_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_workorder_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  msdyn_workorder_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_workorder_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorder_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorder_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_workorder_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_workorder_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_workorder_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_workorder_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msdyn_workorder_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msdyn_workorder_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msdyn_workorder_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  navigationPropertyNameNotDefined: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  navigationPropertyNameNotDefined1: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_workorders: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_workorders: WebMappingRelated<msdyn_workorder_RelatedOne,msdyn_workorder_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_workorders: WebMappingCUDA<msdyn_workorder_Create,msdyn_workorder_Update,msdyn_workorder_Select>;
}
