interface msdyn_workorderincident_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_description?: string | null;
  msdyn_estimatedduration?: number | null;
  msdyn_incidentresolved?: boolean | null;
  msdyn_internalflags?: string | null;
  msdyn_ismobile?: boolean | null;
  msdyn_isprimary?: boolean | null;
  msdyn_itemspopulated?: boolean | null;
  msdyn_name?: string | null;
  msdyn_taskspercentcompleted?: number | null;
  msdyn_workorderincidentid?: string | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_workorderincident_statecode | null;
  statuscode?: msdyn_workorderincident_statuscode | null;
  timezoneruleversionnumber?: number | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_workorderincident_Relationships {
  msdyn_FunctionalLocation?: msdyn_FunctionalLocation_Result | null;
  msdyn_PrimaryResolution?: msdyn_resolution_Result | null;
  msdyn_ResourceRequirement?: msdyn_resourcerequirement_Result | null;
  msdyn_msdyn_workorderincident_msdyn_requirementcharacteristic_WorkOrderIncident?: msdyn_requirementcharacteristic_Result[] | null;
  msdyn_msdyn_workorderincident_msdyn_workordercharacteristic_WorkOrderIncident?: msdyn_workordercharacteristic_Result[] | null;
  msdyn_msdyn_workorderincident_msdyn_workorderproduct_WorkOrderIncident?: msdyn_workorderproduct_Result[] | null;
  msdyn_msdyn_workorderincident_msdyn_workorderresolution_WorkOrderIncident?: msdyn_workorderresolution_Result[] | null;
  msdyn_msdyn_workorderincident_msdyn_workorderservice_WorkOrderIncident?: msdyn_workorderservice_Result[] | null;
  msdyn_msdyn_workorderincident_msdyn_workorderservicetask_WorkOrderIncident?: msdyn_workorderservicetask_Result[] | null;
  msdyn_workorderincident_ActivityPointers?: ActivityPointer_Result[] | null;
  msdyn_workorderincident_Annotations?: Annotation_Result[] | null;
  msdyn_workorderincident_Appointments?: Appointment_Result[] | null;
  msdyn_workorderincident_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_workorderincident_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_workorderincident_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_workorderincident_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_workorderincident_Emails?: Email_Result[] | null;
  msdyn_workorderincident_Faxes?: Fax_Result[] | null;
  msdyn_workorderincident_Letters?: Letter_Result[] | null;
  msdyn_workorderincident_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_workorderincident_PhoneCalls?: PhoneCall_Result[] | null;
  msdyn_workorderincident_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_workorderincident_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_workorderincident_QueueItems?: QueueItem_Result[] | null;
  msdyn_workorderincident_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  msdyn_workorderincident_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_workorderincident_SharePointDocumentLocations?: SharePointDocumentLocation_Result[] | null;
  msdyn_workorderincident_SharePointDocuments?: SharePointDocument_Result[] | null;
  msdyn_workorderincident_SocialActivities?: SocialActivity_Result[] | null;
  msdyn_workorderincident_SyncErrors?: SyncError_Result[] | null;
  msdyn_workorderincident_Tasks?: Task_Result[] | null;
  msdyn_workorderincident_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_workorderincident_connections1?: Connection_Result[] | null;
  msdyn_workorderincident_connections2?: Connection_Result[] | null;
  msdyn_workorderincident_msdyn_approvals?: msdyn_approval_Result[] | null;
  msdyn_workorderincident_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  msdyn_workorderincident_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_workorderincident_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_workorderincident_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  msdyn_workorderincident_msfp_alerts?: msfp_alert_Result[] | null;
  msdyn_workorderincident_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  msdyn_workorderincident_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
}
interface msdyn_workorderincident extends msdyn_workorderincident_Base, msdyn_workorderincident_Relationships {
  msdyn_FunctionalLocation_bind$msdyn_functionallocations?: string | null;
  msdyn_PrimaryResolution_bind$msdyn_resolutions?: string | null;
  msdyn_ResourceRequirement_bind$msdyn_resourcerequirements?: string | null;
  msdyn_agreementbookingincident_bind$msdyn_agreementbookingincidents?: string | null;
  msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  msdyn_incidenttype_bind$msdyn_incidenttypes?: string | null;
  msdyn_workorder_bind$msdyn_workorders?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface msdyn_workorderincident_Create extends msdyn_workorderincident {
}
interface msdyn_workorderincident_Update extends msdyn_workorderincident {
}
interface msdyn_workorderincident_Select {
  createdby_guid: WebAttribute<msdyn_workorderincident_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_workorderincident_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_workorderincident_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<msdyn_workorderincident_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_workorderincident_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_workorderincident_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_workorderincident_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_agreementbookingincident_guid: WebAttribute<msdyn_workorderincident_Select, { msdyn_agreementbookingincident_guid: string | null }, { msdyn_agreementbookingincident_formatted?: string }>;
  msdyn_customerasset_guid: WebAttribute<msdyn_workorderincident_Select, { msdyn_customerasset_guid: string | null }, { msdyn_customerasset_formatted?: string }>;
  msdyn_description: WebAttribute<msdyn_workorderincident_Select, { msdyn_description: string | null }, {  }>;
  msdyn_estimatedduration: WebAttribute<msdyn_workorderincident_Select, { msdyn_estimatedduration: number | null }, {  }>;
  msdyn_functionallocation_guid: WebAttribute<msdyn_workorderincident_Select, { msdyn_functionallocation_guid: string | null }, { msdyn_functionallocation_formatted?: string }>;
  msdyn_incidentresolved: WebAttribute<msdyn_workorderincident_Select, { msdyn_incidentresolved: boolean | null }, {  }>;
  msdyn_incidenttype_guid: WebAttribute<msdyn_workorderincident_Select, { msdyn_incidenttype_guid: string | null }, { msdyn_incidenttype_formatted?: string }>;
  msdyn_internalflags: WebAttribute<msdyn_workorderincident_Select, { msdyn_internalflags: string | null }, {  }>;
  msdyn_ismobile: WebAttribute<msdyn_workorderincident_Select, { msdyn_ismobile: boolean | null }, {  }>;
  msdyn_isprimary: WebAttribute<msdyn_workorderincident_Select, { msdyn_isprimary: boolean | null }, {  }>;
  msdyn_itemspopulated: WebAttribute<msdyn_workorderincident_Select, { msdyn_itemspopulated: boolean | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_workorderincident_Select, { msdyn_name: string | null }, {  }>;
  msdyn_primaryresolution_guid: WebAttribute<msdyn_workorderincident_Select, { msdyn_primaryresolution_guid: string | null }, { msdyn_primaryresolution_formatted?: string }>;
  msdyn_resourcerequirement_guid: WebAttribute<msdyn_workorderincident_Select, { msdyn_resourcerequirement_guid: string | null }, { msdyn_resourcerequirement_formatted?: string }>;
  msdyn_taskspercentcompleted: WebAttribute<msdyn_workorderincident_Select, { msdyn_taskspercentcompleted: number | null }, {  }>;
  msdyn_workorder_guid: WebAttribute<msdyn_workorderincident_Select, { msdyn_workorder_guid: string | null }, { msdyn_workorder_formatted?: string }>;
  msdyn_workorderincidentid: WebAttribute<msdyn_workorderincident_Select, { msdyn_workorderincidentid: string | null }, {  }>;
  overriddencreatedon: WebAttribute<msdyn_workorderincident_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_workorderincident_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_workorderincident_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_workorderincident_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_workorderincident_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_workorderincident_Select, { statecode: msdyn_workorderincident_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_workorderincident_Select, { statuscode: msdyn_workorderincident_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_workorderincident_Select, { timezoneruleversionnumber: number | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_workorderincident_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_workorderincident_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_workorderincident_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_agreementbookingincident_guid: XQW.Guid;
  msdyn_customerasset_guid: XQW.Guid;
  msdyn_description: string;
  msdyn_estimatedduration: number;
  msdyn_functionallocation_guid: XQW.Guid;
  msdyn_incidentresolved: boolean;
  msdyn_incidenttype_guid: XQW.Guid;
  msdyn_internalflags: string;
  msdyn_ismobile: boolean;
  msdyn_isprimary: boolean;
  msdyn_itemspopulated: boolean;
  msdyn_name: string;
  msdyn_primaryresolution_guid: XQW.Guid;
  msdyn_resourcerequirement_guid: XQW.Guid;
  msdyn_taskspercentcompleted: number;
  msdyn_workorder_guid: XQW.Guid;
  msdyn_workorderincidentid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_workorderincident_statecode;
  statuscode: msdyn_workorderincident_statuscode;
  timezoneruleversionnumber: number;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_workorderincident_Expand {
  createdby: WebExpand<msdyn_workorderincident_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_workorderincident_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_workorderincident_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_workorderincident_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_FunctionalLocation: WebExpand<msdyn_workorderincident_Expand, msdyn_FunctionalLocation_Select, msdyn_FunctionalLocation_Filter, { msdyn_FunctionalLocation: msdyn_FunctionalLocation_Result }>;
  msdyn_PrimaryResolution: WebExpand<msdyn_workorderincident_Expand, msdyn_resolution_Select, msdyn_resolution_Filter, { msdyn_PrimaryResolution: msdyn_resolution_Result }>;
  msdyn_ResourceRequirement: WebExpand<msdyn_workorderincident_Expand, msdyn_resourcerequirement_Select, msdyn_resourcerequirement_Filter, { msdyn_ResourceRequirement: msdyn_resourcerequirement_Result }>;
  msdyn_agreementbookingincident: WebExpand<msdyn_workorderincident_Expand, msdyn_agreementbookingincident_Select, msdyn_agreementbookingincident_Filter, { msdyn_agreementbookingincident: msdyn_agreementbookingincident_Result }>;
  msdyn_customerasset: WebExpand<msdyn_workorderincident_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_customerasset: msdyn_customerasset_Result }>;
  msdyn_incidenttype: WebExpand<msdyn_workorderincident_Expand, msdyn_incidenttype_Select, msdyn_incidenttype_Filter, { msdyn_incidenttype: msdyn_incidenttype_Result }>;
  msdyn_msdyn_workorderincident_msdyn_requirementcharacteristic_WorkOrderIncident: WebExpand<msdyn_workorderincident_Expand, msdyn_requirementcharacteristic_Select, msdyn_requirementcharacteristic_Filter, { msdyn_msdyn_workorderincident_msdyn_requirementcharacteristic_WorkOrderIncident: msdyn_requirementcharacteristic_Result[] }>;
  msdyn_msdyn_workorderincident_msdyn_workordercharacteristic_WorkOrderIncident: WebExpand<msdyn_workorderincident_Expand, msdyn_workordercharacteristic_Select, msdyn_workordercharacteristic_Filter, { msdyn_msdyn_workorderincident_msdyn_workordercharacteristic_WorkOrderIncident: msdyn_workordercharacteristic_Result[] }>;
  msdyn_msdyn_workorderincident_msdyn_workorderproduct_WorkOrderIncident: WebExpand<msdyn_workorderincident_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { msdyn_msdyn_workorderincident_msdyn_workorderproduct_WorkOrderIncident: msdyn_workorderproduct_Result[] }>;
  msdyn_msdyn_workorderincident_msdyn_workorderresolution_WorkOrderIncident: WebExpand<msdyn_workorderincident_Expand, msdyn_workorderresolution_Select, msdyn_workorderresolution_Filter, { msdyn_msdyn_workorderincident_msdyn_workorderresolution_WorkOrderIncident: msdyn_workorderresolution_Result[] }>;
  msdyn_msdyn_workorderincident_msdyn_workorderservice_WorkOrderIncident: WebExpand<msdyn_workorderincident_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { msdyn_msdyn_workorderincident_msdyn_workorderservice_WorkOrderIncident: msdyn_workorderservice_Result[] }>;
  msdyn_msdyn_workorderincident_msdyn_workorderservicetask_WorkOrderIncident: WebExpand<msdyn_workorderincident_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { msdyn_msdyn_workorderincident_msdyn_workorderservicetask_WorkOrderIncident: msdyn_workorderservicetask_Result[] }>;
  msdyn_workorder: WebExpand<msdyn_workorderincident_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_workorder: msdyn_workorder_Result }>;
  msdyn_workorderincident_ActivityPointers: WebExpand<msdyn_workorderincident_Expand, ActivityPointer_Select, ActivityPointer_Filter, { msdyn_workorderincident_ActivityPointers: ActivityPointer_Result[] }>;
  msdyn_workorderincident_Annotations: WebExpand<msdyn_workorderincident_Expand, Annotation_Select, Annotation_Filter, { msdyn_workorderincident_Annotations: Annotation_Result[] }>;
  msdyn_workorderincident_Appointments: WebExpand<msdyn_workorderincident_Expand, Appointment_Select, Appointment_Filter, { msdyn_workorderincident_Appointments: Appointment_Result[] }>;
  msdyn_workorderincident_AsyncOperations: WebExpand<msdyn_workorderincident_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_workorderincident_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_workorderincident_BulkDeleteFailures: WebExpand<msdyn_workorderincident_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_workorderincident_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_workorderincident_DuplicateBaseRecord: WebExpand<msdyn_workorderincident_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_workorderincident_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_workorderincident_DuplicateMatchingRecord: WebExpand<msdyn_workorderincident_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_workorderincident_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_workorderincident_Emails: WebExpand<msdyn_workorderincident_Expand, Email_Select, Email_Filter, { msdyn_workorderincident_Emails: Email_Result[] }>;
  msdyn_workorderincident_Faxes: WebExpand<msdyn_workorderincident_Expand, Fax_Select, Fax_Filter, { msdyn_workorderincident_Faxes: Fax_Result[] }>;
  msdyn_workorderincident_Letters: WebExpand<msdyn_workorderincident_Expand, Letter_Select, Letter_Filter, { msdyn_workorderincident_Letters: Letter_Result[] }>;
  msdyn_workorderincident_MailboxTrackingFolders: WebExpand<msdyn_workorderincident_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_workorderincident_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_workorderincident_PhoneCalls: WebExpand<msdyn_workorderincident_Expand, PhoneCall_Select, PhoneCall_Filter, { msdyn_workorderincident_PhoneCalls: PhoneCall_Result[] }>;
  msdyn_workorderincident_PrincipalObjectAttributeAccesses: WebExpand<msdyn_workorderincident_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_workorderincident_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_workorderincident_ProcessSession: WebExpand<msdyn_workorderincident_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_workorderincident_ProcessSession: ProcessSession_Result[] }>;
  msdyn_workorderincident_QueueItems: WebExpand<msdyn_workorderincident_Expand, QueueItem_Select, QueueItem_Filter, { msdyn_workorderincident_QueueItems: QueueItem_Result[] }>;
  msdyn_workorderincident_RecurringAppointmentMasters: WebExpand<msdyn_workorderincident_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { msdyn_workorderincident_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  msdyn_workorderincident_ServiceAppointments: WebExpand<msdyn_workorderincident_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_workorderincident_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_workorderincident_SharePointDocumentLocations: WebExpand<msdyn_workorderincident_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { msdyn_workorderincident_SharePointDocumentLocations: SharePointDocumentLocation_Result[] }>;
  msdyn_workorderincident_SharePointDocuments: WebExpand<msdyn_workorderincident_Expand, SharePointDocument_Select, SharePointDocument_Filter, { msdyn_workorderincident_SharePointDocuments: SharePointDocument_Result[] }>;
  msdyn_workorderincident_SocialActivities: WebExpand<msdyn_workorderincident_Expand, SocialActivity_Select, SocialActivity_Filter, { msdyn_workorderincident_SocialActivities: SocialActivity_Result[] }>;
  msdyn_workorderincident_SyncErrors: WebExpand<msdyn_workorderincident_Expand, SyncError_Select, SyncError_Filter, { msdyn_workorderincident_SyncErrors: SyncError_Result[] }>;
  msdyn_workorderincident_Tasks: WebExpand<msdyn_workorderincident_Expand, Task_Select, Task_Filter, { msdyn_workorderincident_Tasks: Task_Result[] }>;
  msdyn_workorderincident_UserEntityInstanceDatas: WebExpand<msdyn_workorderincident_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_workorderincident_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_workorderincident_connections1: WebExpand<msdyn_workorderincident_Expand, Connection_Select, Connection_Filter, { msdyn_workorderincident_connections1: Connection_Result[] }>;
  msdyn_workorderincident_connections2: WebExpand<msdyn_workorderincident_Expand, Connection_Select, Connection_Filter, { msdyn_workorderincident_connections2: Connection_Result[] }>;
  msdyn_workorderincident_msdyn_approvals: WebExpand<msdyn_workorderincident_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_workorderincident_msdyn_approvals: msdyn_approval_Result[] }>;
  msdyn_workorderincident_msdyn_bookingalerts: WebExpand<msdyn_workorderincident_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_workorderincident_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  msdyn_workorderincident_msdyn_ocliveworkitems: WebExpand<msdyn_workorderincident_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_workorderincident_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  msdyn_workorderincident_msdyn_ocoutboundmessages: WebExpand<msdyn_workorderincident_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_workorderincident_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_workorderincident_msdyn_ocsessions: WebExpand<msdyn_workorderincident_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_workorderincident_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  msdyn_workorderincident_msfp_alerts: WebExpand<msdyn_workorderincident_Expand, msfp_alert_Select, msfp_alert_Filter, { msdyn_workorderincident_msfp_alerts: msfp_alert_Result[] }>;
  msdyn_workorderincident_msfp_surveyinvites: WebExpand<msdyn_workorderincident_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msdyn_workorderincident_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  msdyn_workorderincident_msfp_surveyresponses: WebExpand<msdyn_workorderincident_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msdyn_workorderincident_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  ownerid: WebExpand<msdyn_workorderincident_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_workorderincident_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_workorderincident_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_workorderincident_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
}
interface msdyn_workorderincident_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_agreementbookingincident_formatted?: string;
  msdyn_customerasset_formatted?: string;
  msdyn_functionallocation_formatted?: string;
  msdyn_incidenttype_formatted?: string;
  msdyn_primaryresolution_formatted?: string;
  msdyn_resourcerequirement_formatted?: string;
  msdyn_workorder_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface msdyn_workorderincident_Result extends msdyn_workorderincident_Base, msdyn_workorderincident_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_agreementbookingincident_guid: string | null;
  msdyn_customerasset_guid: string | null;
  msdyn_functionallocation_guid: string | null;
  msdyn_incidenttype_guid: string | null;
  msdyn_primaryresolution_guid: string | null;
  msdyn_resourcerequirement_guid: string | null;
  msdyn_workorder_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface msdyn_workorderincident_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_FunctionalLocation: WebMappingRetrieve<msdyn_FunctionalLocation_Select,msdyn_FunctionalLocation_Expand,msdyn_FunctionalLocation_Filter,msdyn_FunctionalLocation_Fixed,msdyn_FunctionalLocation_Result,msdyn_FunctionalLocation_FormattedResult>;
  msdyn_PrimaryResolution: WebMappingRetrieve<msdyn_resolution_Select,msdyn_resolution_Expand,msdyn_resolution_Filter,msdyn_resolution_Fixed,msdyn_resolution_Result,msdyn_resolution_FormattedResult>;
  msdyn_ResourceRequirement: WebMappingRetrieve<msdyn_resourcerequirement_Select,msdyn_resourcerequirement_Expand,msdyn_resourcerequirement_Filter,msdyn_resourcerequirement_Fixed,msdyn_resourcerequirement_Result,msdyn_resourcerequirement_FormattedResult>;
  msdyn_agreementbookingincident: WebMappingRetrieve<msdyn_agreementbookingincident_Select,msdyn_agreementbookingincident_Expand,msdyn_agreementbookingincident_Filter,msdyn_agreementbookingincident_Fixed,msdyn_agreementbookingincident_Result,msdyn_agreementbookingincident_FormattedResult>;
  msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_incidenttype: WebMappingRetrieve<msdyn_incidenttype_Select,msdyn_incidenttype_Expand,msdyn_incidenttype_Filter,msdyn_incidenttype_Fixed,msdyn_incidenttype_Result,msdyn_incidenttype_FormattedResult>;
  msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface msdyn_workorderincident_RelatedMany {
  msdyn_msdyn_workorderincident_msdyn_requirementcharacteristic_WorkOrderIncident: WebMappingRetrieve<msdyn_requirementcharacteristic_Select,msdyn_requirementcharacteristic_Expand,msdyn_requirementcharacteristic_Filter,msdyn_requirementcharacteristic_Fixed,msdyn_requirementcharacteristic_Result,msdyn_requirementcharacteristic_FormattedResult>;
  msdyn_msdyn_workorderincident_msdyn_workordercharacteristic_WorkOrderIncident: WebMappingRetrieve<msdyn_workordercharacteristic_Select,msdyn_workordercharacteristic_Expand,msdyn_workordercharacteristic_Filter,msdyn_workordercharacteristic_Fixed,msdyn_workordercharacteristic_Result,msdyn_workordercharacteristic_FormattedResult>;
  msdyn_msdyn_workorderincident_msdyn_workorderproduct_WorkOrderIncident: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  msdyn_msdyn_workorderincident_msdyn_workorderresolution_WorkOrderIncident: WebMappingRetrieve<msdyn_workorderresolution_Select,msdyn_workorderresolution_Expand,msdyn_workorderresolution_Filter,msdyn_workorderresolution_Fixed,msdyn_workorderresolution_Result,msdyn_workorderresolution_FormattedResult>;
  msdyn_msdyn_workorderincident_msdyn_workorderservice_WorkOrderIncident: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  msdyn_msdyn_workorderincident_msdyn_workorderservicetask_WorkOrderIncident: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  msdyn_workorderincident_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  msdyn_workorderincident_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_workorderincident_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_workorderincident_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_workorderincident_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_workorderincident_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_workorderincident_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_workorderincident_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_workorderincident_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  msdyn_workorderincident_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  msdyn_workorderincident_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_workorderincident_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  msdyn_workorderincident_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_workorderincident_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_workorderincident_QueueItems: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  msdyn_workorderincident_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  msdyn_workorderincident_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_workorderincident_SharePointDocumentLocations: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  msdyn_workorderincident_SharePointDocuments: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  msdyn_workorderincident_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  msdyn_workorderincident_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_workorderincident_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  msdyn_workorderincident_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_workorderincident_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorderincident_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_workorderincident_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_workorderincident_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_workorderincident_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_workorderincident_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_workorderincident_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msdyn_workorderincident_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msdyn_workorderincident_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msdyn_workorderincident_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_workorderincidents: WebMappingRetrieve<msdyn_workorderincident_Select,msdyn_workorderincident_Expand,msdyn_workorderincident_Filter,msdyn_workorderincident_Fixed,msdyn_workorderincident_Result,msdyn_workorderincident_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_workorderincidents: WebMappingRelated<msdyn_workorderincident_RelatedOne,msdyn_workorderincident_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_workorderincidents: WebMappingCUDA<msdyn_workorderincident_Create,msdyn_workorderincident_Update,msdyn_workorderincident_Select>;
}
