interface msdyn_quotebookingproduct_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_Internalflags?: string | null;
  msdyn_currency?: number | null;
  msdyn_currency_base?: number | null;
  msdyn_estimatedcost?: number | null;
  msdyn_estimatedcost_base?: number | null;
  msdyn_estimatedsalesamount?: number | null;
  msdyn_estimatedsalesamount_base?: number | null;
  msdyn_iscopied?: boolean | null;
  msdyn_lineorder?: number | null;
  msdyn_name?: string | null;
  msdyn_qtytobill?: number | null;
  msdyn_quantity?: number | null;
  msdyn_quotebookingproductid?: string | null;
  msdyn_unitamount?: number | null;
  msdyn_unitamount_base?: number | null;
  msdyn_unitcostamount?: number | null;
  msdyn_unitcostamount_base?: number | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_quotebookingproduct_statecode | null;
  statuscode?: msdyn_quotebookingproduct_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_quotebookingproduct_Relationships {
  msdyn_quotebookingproduct_ActivityPointers?: ActivityPointer_Result[] | null;
  msdyn_quotebookingproduct_Annotations?: Annotation_Result[] | null;
  msdyn_quotebookingproduct_Appointments?: Appointment_Result[] | null;
  msdyn_quotebookingproduct_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_quotebookingproduct_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_quotebookingproduct_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_quotebookingproduct_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_quotebookingproduct_Emails?: Email_Result[] | null;
  msdyn_quotebookingproduct_Faxes?: Fax_Result[] | null;
  msdyn_quotebookingproduct_Letters?: Letter_Result[] | null;
  msdyn_quotebookingproduct_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_quotebookingproduct_PhoneCalls?: PhoneCall_Result[] | null;
  msdyn_quotebookingproduct_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_quotebookingproduct_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_quotebookingproduct_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  msdyn_quotebookingproduct_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_quotebookingproduct_SocialActivities?: SocialActivity_Result[] | null;
  msdyn_quotebookingproduct_SyncErrors?: SyncError_Result[] | null;
  msdyn_quotebookingproduct_Tasks?: Task_Result[] | null;
  msdyn_quotebookingproduct_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_quotebookingproduct_connections1?: Connection_Result[] | null;
  msdyn_quotebookingproduct_connections2?: Connection_Result[] | null;
  msdyn_quotebookingproduct_msdyn_approvals?: msdyn_approval_Result[] | null;
  msdyn_quotebookingproduct_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  msdyn_quotebookingproduct_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_quotebookingproduct_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_quotebookingproduct_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  msdyn_quotebookingproduct_msfp_alerts?: msfp_alert_Result[] | null;
  msdyn_quotebookingproduct_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  msdyn_quotebookingproduct_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
}
interface msdyn_quotebookingproduct extends msdyn_quotebookingproduct_Base, msdyn_quotebookingproduct_Relationships {
  msdyn_customerasset_bind$msdyn_customerassets?: string | null;
  msdyn_pricelist_bind$pricelevels?: string | null;
  msdyn_product_bind$products?: string | null;
  msdyn_quote_bind$quotes?: string | null;
  msdyn_quotebookingincident_bind$msdyn_quotebookingincidents?: string | null;
  msdyn_quotebookingsetup_bind$msdyn_quotebookingsetups?: string | null;
  msdyn_unit_bind$uoms?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface msdyn_quotebookingproduct_Create extends msdyn_quotebookingproduct {
}
interface msdyn_quotebookingproduct_Update extends msdyn_quotebookingproduct {
}
interface msdyn_quotebookingproduct_Select {
  createdby_guid: WebAttribute<msdyn_quotebookingproduct_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_quotebookingproduct_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_quotebookingproduct_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_quotebookingproduct_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_quotebookingproduct_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_quotebookingproduct_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_quotebookingproduct_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_quotebookingproduct_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_Internalflags: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_Internalflags: string | null }, {  }>;
  msdyn_currency: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_currency: number | null; transactioncurrencyid_guid: string | null }, { msdyn_currency_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_currency_base: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_currency_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_currency_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_customerasset_guid: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_customerasset_guid: string | null }, { msdyn_customerasset_formatted?: string }>;
  msdyn_estimatedcost: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_estimatedcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedcost_base: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_estimatedcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedsalesamount: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_estimatedsalesamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedsalesamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedsalesamount_base: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_estimatedsalesamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedsalesamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_iscopied: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_iscopied: boolean | null }, {  }>;
  msdyn_lineorder: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_lineorder: number | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_name: string | null }, {  }>;
  msdyn_pricelist_guid: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_pricelist_guid: string | null }, { msdyn_pricelist_formatted?: string }>;
  msdyn_product_guid: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_product_guid: string | null }, { msdyn_product_formatted?: string }>;
  msdyn_qtytobill: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_qtytobill: number | null }, {  }>;
  msdyn_quantity: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_quantity: number | null }, {  }>;
  msdyn_quote_guid: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_quote_guid: string | null }, { msdyn_quote_formatted?: string }>;
  msdyn_quotebookingincident_guid: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_quotebookingincident_guid: string | null }, { msdyn_quotebookingincident_formatted?: string }>;
  msdyn_quotebookingproductid: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_quotebookingproductid: string | null }, {  }>;
  msdyn_quotebookingsetup_guid: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_quotebookingsetup_guid: string | null }, { msdyn_quotebookingsetup_formatted?: string }>;
  msdyn_unit_guid: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_unit_guid: string | null }, { msdyn_unit_formatted?: string }>;
  msdyn_unitamount: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_unitamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unitamount_base: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_unitamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unitcostamount: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_unitcostamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitcostamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_unitcostamount_base: WebAttribute<msdyn_quotebookingproduct_Select, { msdyn_unitcostamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_unitcostamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_quotebookingproduct_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_quotebookingproduct_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_quotebookingproduct_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_quotebookingproduct_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_quotebookingproduct_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_quotebookingproduct_Select, { statecode: msdyn_quotebookingproduct_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_quotebookingproduct_Select, { statuscode: msdyn_quotebookingproduct_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_quotebookingproduct_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_quotebookingproduct_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<msdyn_quotebookingproduct_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_quotebookingproduct_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_quotebookingproduct_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_Internalflags: string;
  msdyn_currency: number;
  msdyn_currency_base: number;
  msdyn_customerasset_guid: XQW.Guid;
  msdyn_estimatedcost: number;
  msdyn_estimatedcost_base: number;
  msdyn_estimatedsalesamount: number;
  msdyn_estimatedsalesamount_base: number;
  msdyn_iscopied: boolean;
  msdyn_lineorder: number;
  msdyn_name: string;
  msdyn_pricelist_guid: XQW.Guid;
  msdyn_product_guid: XQW.Guid;
  msdyn_qtytobill: number;
  msdyn_quantity: number;
  msdyn_quote_guid: XQW.Guid;
  msdyn_quotebookingincident_guid: XQW.Guid;
  msdyn_quotebookingproductid: XQW.Guid;
  msdyn_quotebookingsetup_guid: XQW.Guid;
  msdyn_unit_guid: XQW.Guid;
  msdyn_unitamount: number;
  msdyn_unitamount_base: number;
  msdyn_unitcostamount: number;
  msdyn_unitcostamount_base: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_quotebookingproduct_statecode;
  statuscode: msdyn_quotebookingproduct_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_quotebookingproduct_Expand {
  createdby: WebExpand<msdyn_quotebookingproduct_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_quotebookingproduct_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_quotebookingproduct_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_quotebookingproduct_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_customerasset: WebExpand<msdyn_quotebookingproduct_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_customerasset: msdyn_customerasset_Result }>;
  msdyn_pricelist: WebExpand<msdyn_quotebookingproduct_Expand, PriceLevel_Select, PriceLevel_Filter, { msdyn_pricelist: PriceLevel_Result }>;
  msdyn_product: WebExpand<msdyn_quotebookingproduct_Expand, Product_Select, Product_Filter, { msdyn_product: Product_Result }>;
  msdyn_quote: WebExpand<msdyn_quotebookingproduct_Expand, Quote_Select, Quote_Filter, { msdyn_quote: Quote_Result }>;
  msdyn_quotebookingincident: WebExpand<msdyn_quotebookingproduct_Expand, msdyn_quotebookingincident_Select, msdyn_quotebookingincident_Filter, { msdyn_quotebookingincident: msdyn_quotebookingincident_Result }>;
  msdyn_quotebookingproduct_ActivityPointers: WebExpand<msdyn_quotebookingproduct_Expand, ActivityPointer_Select, ActivityPointer_Filter, { msdyn_quotebookingproduct_ActivityPointers: ActivityPointer_Result[] }>;
  msdyn_quotebookingproduct_Annotations: WebExpand<msdyn_quotebookingproduct_Expand, Annotation_Select, Annotation_Filter, { msdyn_quotebookingproduct_Annotations: Annotation_Result[] }>;
  msdyn_quotebookingproduct_Appointments: WebExpand<msdyn_quotebookingproduct_Expand, Appointment_Select, Appointment_Filter, { msdyn_quotebookingproduct_Appointments: Appointment_Result[] }>;
  msdyn_quotebookingproduct_AsyncOperations: WebExpand<msdyn_quotebookingproduct_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_quotebookingproduct_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_quotebookingproduct_BulkDeleteFailures: WebExpand<msdyn_quotebookingproduct_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_quotebookingproduct_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_quotebookingproduct_DuplicateBaseRecord: WebExpand<msdyn_quotebookingproduct_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_quotebookingproduct_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_quotebookingproduct_DuplicateMatchingRecord: WebExpand<msdyn_quotebookingproduct_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_quotebookingproduct_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_quotebookingproduct_Emails: WebExpand<msdyn_quotebookingproduct_Expand, Email_Select, Email_Filter, { msdyn_quotebookingproduct_Emails: Email_Result[] }>;
  msdyn_quotebookingproduct_Faxes: WebExpand<msdyn_quotebookingproduct_Expand, Fax_Select, Fax_Filter, { msdyn_quotebookingproduct_Faxes: Fax_Result[] }>;
  msdyn_quotebookingproduct_Letters: WebExpand<msdyn_quotebookingproduct_Expand, Letter_Select, Letter_Filter, { msdyn_quotebookingproduct_Letters: Letter_Result[] }>;
  msdyn_quotebookingproduct_MailboxTrackingFolders: WebExpand<msdyn_quotebookingproduct_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_quotebookingproduct_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_quotebookingproduct_PhoneCalls: WebExpand<msdyn_quotebookingproduct_Expand, PhoneCall_Select, PhoneCall_Filter, { msdyn_quotebookingproduct_PhoneCalls: PhoneCall_Result[] }>;
  msdyn_quotebookingproduct_PrincipalObjectAttributeAccesses: WebExpand<msdyn_quotebookingproduct_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_quotebookingproduct_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_quotebookingproduct_ProcessSession: WebExpand<msdyn_quotebookingproduct_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_quotebookingproduct_ProcessSession: ProcessSession_Result[] }>;
  msdyn_quotebookingproduct_RecurringAppointmentMasters: WebExpand<msdyn_quotebookingproduct_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { msdyn_quotebookingproduct_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  msdyn_quotebookingproduct_ServiceAppointments: WebExpand<msdyn_quotebookingproduct_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_quotebookingproduct_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_quotebookingproduct_SocialActivities: WebExpand<msdyn_quotebookingproduct_Expand, SocialActivity_Select, SocialActivity_Filter, { msdyn_quotebookingproduct_SocialActivities: SocialActivity_Result[] }>;
  msdyn_quotebookingproduct_SyncErrors: WebExpand<msdyn_quotebookingproduct_Expand, SyncError_Select, SyncError_Filter, { msdyn_quotebookingproduct_SyncErrors: SyncError_Result[] }>;
  msdyn_quotebookingproduct_Tasks: WebExpand<msdyn_quotebookingproduct_Expand, Task_Select, Task_Filter, { msdyn_quotebookingproduct_Tasks: Task_Result[] }>;
  msdyn_quotebookingproduct_UserEntityInstanceDatas: WebExpand<msdyn_quotebookingproduct_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_quotebookingproduct_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_quotebookingproduct_connections1: WebExpand<msdyn_quotebookingproduct_Expand, Connection_Select, Connection_Filter, { msdyn_quotebookingproduct_connections1: Connection_Result[] }>;
  msdyn_quotebookingproduct_connections2: WebExpand<msdyn_quotebookingproduct_Expand, Connection_Select, Connection_Filter, { msdyn_quotebookingproduct_connections2: Connection_Result[] }>;
  msdyn_quotebookingproduct_msdyn_approvals: WebExpand<msdyn_quotebookingproduct_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_quotebookingproduct_msdyn_approvals: msdyn_approval_Result[] }>;
  msdyn_quotebookingproduct_msdyn_bookingalerts: WebExpand<msdyn_quotebookingproduct_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_quotebookingproduct_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  msdyn_quotebookingproduct_msdyn_ocliveworkitems: WebExpand<msdyn_quotebookingproduct_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_quotebookingproduct_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  msdyn_quotebookingproduct_msdyn_ocoutboundmessages: WebExpand<msdyn_quotebookingproduct_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_quotebookingproduct_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_quotebookingproduct_msdyn_ocsessions: WebExpand<msdyn_quotebookingproduct_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_quotebookingproduct_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  msdyn_quotebookingproduct_msfp_alerts: WebExpand<msdyn_quotebookingproduct_Expand, msfp_alert_Select, msfp_alert_Filter, { msdyn_quotebookingproduct_msfp_alerts: msfp_alert_Result[] }>;
  msdyn_quotebookingproduct_msfp_surveyinvites: WebExpand<msdyn_quotebookingproduct_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msdyn_quotebookingproduct_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  msdyn_quotebookingproduct_msfp_surveyresponses: WebExpand<msdyn_quotebookingproduct_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msdyn_quotebookingproduct_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  msdyn_quotebookingsetup: WebExpand<msdyn_quotebookingproduct_Expand, msdyn_quotebookingsetup_Select, msdyn_quotebookingsetup_Filter, { msdyn_quotebookingsetup: msdyn_quotebookingsetup_Result }>;
  msdyn_unit: WebExpand<msdyn_quotebookingproduct_Expand, UoM_Select, UoM_Filter, { msdyn_unit: UoM_Result }>;
  ownerid: WebExpand<msdyn_quotebookingproduct_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_quotebookingproduct_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_quotebookingproduct_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_quotebookingproduct_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  transactioncurrencyid: WebExpand<msdyn_quotebookingproduct_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface msdyn_quotebookingproduct_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_currency_base_formatted?: string;
  msdyn_currency_formatted?: string;
  msdyn_customerasset_formatted?: string;
  msdyn_estimatedcost_base_formatted?: string;
  msdyn_estimatedcost_formatted?: string;
  msdyn_estimatedsalesamount_base_formatted?: string;
  msdyn_estimatedsalesamount_formatted?: string;
  msdyn_pricelist_formatted?: string;
  msdyn_product_formatted?: string;
  msdyn_quote_formatted?: string;
  msdyn_quotebookingincident_formatted?: string;
  msdyn_quotebookingsetup_formatted?: string;
  msdyn_unit_formatted?: string;
  msdyn_unitamount_base_formatted?: string;
  msdyn_unitamount_formatted?: string;
  msdyn_unitcostamount_base_formatted?: string;
  msdyn_unitcostamount_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface msdyn_quotebookingproduct_Result extends msdyn_quotebookingproduct_Base, msdyn_quotebookingproduct_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_customerasset_guid: string | null;
  msdyn_pricelist_guid: string | null;
  msdyn_product_guid: string | null;
  msdyn_quote_guid: string | null;
  msdyn_quotebookingincident_guid: string | null;
  msdyn_quotebookingsetup_guid: string | null;
  msdyn_unit_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface msdyn_quotebookingproduct_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_customerasset: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_pricelist: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  msdyn_product: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  msdyn_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  msdyn_quotebookingincident: WebMappingRetrieve<msdyn_quotebookingincident_Select,msdyn_quotebookingincident_Expand,msdyn_quotebookingincident_Filter,msdyn_quotebookingincident_Fixed,msdyn_quotebookingincident_Result,msdyn_quotebookingincident_FormattedResult>;
  msdyn_quotebookingsetup: WebMappingRetrieve<msdyn_quotebookingsetup_Select,msdyn_quotebookingsetup_Expand,msdyn_quotebookingsetup_Filter,msdyn_quotebookingsetup_Fixed,msdyn_quotebookingsetup_Result,msdyn_quotebookingsetup_FormattedResult>;
  msdyn_unit: WebMappingRetrieve<UoM_Select,UoM_Expand,UoM_Filter,UoM_Fixed,UoM_Result,UoM_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface msdyn_quotebookingproduct_RelatedMany {
  msdyn_quotebookingproduct_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  msdyn_quotebookingproduct_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_quotebookingproduct_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_quotebookingproduct_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_quotebookingproduct_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_quotebookingproduct_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_quotebookingproduct_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_quotebookingproduct_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_quotebookingproduct_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  msdyn_quotebookingproduct_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  msdyn_quotebookingproduct_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_quotebookingproduct_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  msdyn_quotebookingproduct_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_quotebookingproduct_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_quotebookingproduct_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  msdyn_quotebookingproduct_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_quotebookingproduct_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  msdyn_quotebookingproduct_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_quotebookingproduct_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  msdyn_quotebookingproduct_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_quotebookingproduct_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_quotebookingproduct_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_quotebookingproduct_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_quotebookingproduct_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_quotebookingproduct_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_quotebookingproduct_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_quotebookingproduct_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msdyn_quotebookingproduct_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msdyn_quotebookingproduct_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msdyn_quotebookingproduct_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_quotebookingproducts: WebMappingRetrieve<msdyn_quotebookingproduct_Select,msdyn_quotebookingproduct_Expand,msdyn_quotebookingproduct_Filter,msdyn_quotebookingproduct_Fixed,msdyn_quotebookingproduct_Result,msdyn_quotebookingproduct_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_quotebookingproducts: WebMappingRelated<msdyn_quotebookingproduct_RelatedOne,msdyn_quotebookingproduct_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_quotebookingproducts: WebMappingCUDA<msdyn_quotebookingproduct_Create,msdyn_quotebookingproduct_Update,msdyn_quotebookingproduct_Select>;
}
