interface msdyn_resourcerequirement_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_allocationmethod?: msdyn_resourcerequirement_msdyn_allocationmethod | null;
  msdyn_calendarid?: string | null;
  msdyn_city?: string | null;
  msdyn_costprice?: number | null;
  msdyn_costprice_base?: number | null;
  msdyn_country?: string | null;
  msdyn_duration?: number | null;
  msdyn_effort?: number | null;
  msdyn_fromdate?: Date | null;
  msdyn_fulfilledduration?: number | null;
  msdyn_fulfilledhours?: number | null;
  msdyn_hours?: number | null;
  msdyn_internalflags?: string | null;
  msdyn_isprimary?: boolean | null;
  msdyn_istemplate?: boolean | null;
  msdyn_latitude?: number | null;
  msdyn_longitude?: number | null;
  msdyn_name?: string | null;
  msdyn_percentage?: number | null;
  msdyn_pooltype?: msdyn_pooltype | null;
  msdyn_proposedduration?: number | null;
  msdyn_quantity?: number | null;
  msdyn_remainingduration?: number | null;
  msdyn_requeststatus?: string | null;
  msdyn_requirementgroupcontrolviewid?: string | null;
  msdyn_resourcerequirementid?: string | null;
  msdyn_resourcetype?: msdyn_bookableresourcetype | null;
  msdyn_sortoptions?: string | null;
  msdyn_stateorprovince?: string | null;
  msdyn_templaterequirementid?: string | null;
  msdyn_timefrompromised?: Date | null;
  msdyn_timetopromised?: Date | null;
  msdyn_timewindowend?: Date | null;
  msdyn_timewindowstart?: Date | null;
  msdyn_timezonefortimewindow?: number | null;
  msdyn_todate?: Date | null;
  msdyn_type?: msdyn_resourcerequirement_msdyn_type | null;
  msdyn_worklocation?: msdyn_worklocation | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_resourcerequirement_statecode | null;
  statuscode?: msdyn_resourcerequirement_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_resourcerequirement_Relationships {
  msdyn_AppointmentRequirementId?: Appointment_Result | null;
  msdyn_BookingSetupMetadataId?: msdyn_bookingsetupmetadata_Result | null;
  msdyn_Priority?: msdyn_priority_Result | null;
  msdyn_Status?: msdyn_requirementstatus_Result | null;
  msdyn_Territory?: Territory_Result | null;
  msdyn_TimeGroup?: msdyn_timegroup_Result | null;
  msdyn_WorkOrder?: msdyn_workorder_Result | null;
  msdyn_msdyn_resourcerequirement_msdyn_requirementcharacteristic_RequirementSystemUse?: msdyn_requirementcharacteristic_Result[] | null;
  msdyn_msdyn_resourcerequirement_msdyn_workorderincident_ResourceRequirement?: msdyn_workorderincident_Result[] | null;
  msdyn_resourcerequirement_Annotations?: Annotation_Result[] | null;
  msdyn_resourcerequirement_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_resourcerequirement_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_resourcerequirement_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_resourcerequirement_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_resourcerequirement_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_resourcerequirement_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_resourcerequirement_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_resourcerequirement_SyncErrors?: SyncError_Result[] | null;
  msdyn_resourcerequirement_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_resourcerequirement_bookableresource?: BookableResource_Result[] | null;
  msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement?: BookableResourceBooking_Result[] | null;
  msdyn_resourcerequirement_bookableresourcebookingheader_ResourceRequirement?: BookableResourceBookingHeader_Result[] | null;
  msdyn_resourcerequirement_bookingheader?: BookableResourceBookingHeader_Result[] | null;
  msdyn_resourcerequirement_characteristicreq?: msdyn_characteristicreqforteammember_Result[] | null;
  msdyn_resourcerequirement_details?: msdyn_resourcerequirementdetail_Result[] | null;
  msdyn_resourcerequirement_projectteam?: msdyn_projectteam_Result[] | null;
  msdyn_resourcerequirement_request?: msdyn_resourcerequest_Result[] | null;
  msdyn_resourcerequirement_requirementcharacteristic_resourcerequirement?: msdyn_requirementcharacteristic_Result[] | null;
  msdyn_resourcerequirement_requirementdependency_dependentrequirement?: msdyn_requirementdependency_Result[] | null;
  msdyn_resourcerequirement_requirementdependency_resourcerequirement?: msdyn_requirementdependency_Result[] | null;
  msdyn_resourcerequirement_requirementorganizationunit_ResourceRequirement?: msdyn_requirementorganizationunit_Result[] | null;
  msdyn_resourcerequirement_requirementresourcecategory_resourcerequirement?: msdyn_requirementresourcecategory_Result[] | null;
  msdyn_resourcerequirement_requirementresourcepreference_ResourceRequirement?: msdyn_requirementresourcepreference_Result[] | null;
  msdyn_resourcerequirement_systemuser?: SystemUser_Result[] | null;
}
interface msdyn_resourcerequirement extends msdyn_resourcerequirement_Base, msdyn_resourcerequirement_Relationships {
  msdyn_AppointmentRequirementId_bind$appointments?: string | null;
  msdyn_BookingSetupMetadataId_bind$msdyn_bookingsetupmetadatas?: string | null;
  msdyn_Priority_bind$msdyn_priorities?: string | null;
  msdyn_Status_bind$msdyn_requirementstatuses?: string | null;
  msdyn_Territory_bind$territories?: string | null;
  msdyn_TimeGroup_bind$msdyn_timegroups?: string | null;
  msdyn_WorkOrder_bind$msdyn_workorders?: string | null;
  msdyn_projectid_bind$msdyn_projects?: string | null;
  msdyn_requirementgroupid_bind$msdyn_requirementgroups?: string | null;
  msdyn_requirementrelationshipid_bind$msdyn_requirementrelationships?: string | null;
  msdyn_roleid_bind$bookableresourcecategories?: string | null;
  msdyn_serviceappointment_bind$serviceappointments?: string | null;
  msdyn_workhourtemplate_bind$msdyn_workhourtemplates?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface msdyn_resourcerequirement_Create extends msdyn_resourcerequirement {
}
interface msdyn_resourcerequirement_Update extends msdyn_resourcerequirement {
}
interface msdyn_resourcerequirement_Select {
  createdby_guid: WebAttribute<msdyn_resourcerequirement_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_resourcerequirement_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_resourcerequirement_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_resourcerequirement_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_resourcerequirement_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_resourcerequirement_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_resourcerequirement_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_resourcerequirement_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_allocationmethod: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_allocationmethod: msdyn_resourcerequirement_msdyn_allocationmethod | null }, { msdyn_allocationmethod_formatted?: string }>;
  msdyn_appointmentrequirementid_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_appointmentrequirementid_guid: string | null }, { msdyn_appointmentrequirementid_formatted?: string }>;
  msdyn_bookingsetupmetadataid_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_bookingsetupmetadataid_guid: string | null }, { msdyn_bookingsetupmetadataid_formatted?: string }>;
  msdyn_calendarid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_calendarid: string | null }, {  }>;
  msdyn_city: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_city: string | null }, {  }>;
  msdyn_costprice: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_costprice: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costprice_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costprice_base: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_costprice_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costprice_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_country: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_country: string | null }, {  }>;
  msdyn_duration: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_duration: number | null }, {  }>;
  msdyn_effort: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_effort: number | null }, {  }>;
  msdyn_fromdate: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_fromdate: Date | null }, { msdyn_fromdate_formatted?: string }>;
  msdyn_fulfilledduration: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_fulfilledduration: number | null }, {  }>;
  msdyn_fulfilledhours: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_fulfilledhours: number | null }, {  }>;
  msdyn_hours: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_hours: number | null }, {  }>;
  msdyn_internalflags: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_internalflags: string | null }, {  }>;
  msdyn_isprimary: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_isprimary: boolean | null }, {  }>;
  msdyn_istemplate: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_istemplate: boolean | null }, {  }>;
  msdyn_latitude: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_latitude: number | null }, {  }>;
  msdyn_longitude: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_longitude: number | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_name: string | null }, {  }>;
  msdyn_percentage: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_percentage: number | null }, {  }>;
  msdyn_pooltype: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_pooltype: msdyn_pooltype | null }, { msdyn_pooltype_formatted?: string }>;
  msdyn_priority_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_priority_guid: string | null }, { msdyn_priority_formatted?: string }>;
  msdyn_projectid_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_projectid_guid: string | null }, { msdyn_projectid_formatted?: string }>;
  msdyn_proposedduration: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_proposedduration: number | null }, {  }>;
  msdyn_quantity: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_quantity: number | null }, {  }>;
  msdyn_remainingduration: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_remainingduration: number | null }, {  }>;
  msdyn_requeststatus: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_requeststatus: string | null }, {  }>;
  msdyn_requirementgroupcontrolviewid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_requirementgroupcontrolviewid: string | null }, {  }>;
  msdyn_requirementgroupid_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_requirementgroupid_guid: string | null }, { msdyn_requirementgroupid_formatted?: string }>;
  msdyn_requirementrelationshipid_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_requirementrelationshipid_guid: string | null }, { msdyn_requirementrelationshipid_formatted?: string }>;
  msdyn_resourcerequirementid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_resourcerequirementid: string | null }, {  }>;
  msdyn_resourcetype: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_resourcetype: msdyn_bookableresourcetype | null }, { msdyn_resourcetype_formatted?: string }>;
  msdyn_roleid_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_roleid_guid: string | null }, { msdyn_roleid_formatted?: string }>;
  msdyn_serviceappointment_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_serviceappointment_guid: string | null }, { msdyn_serviceappointment_formatted?: string }>;
  msdyn_sortoptions: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_sortoptions: string | null }, {  }>;
  msdyn_stateorprovince: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_stateorprovince: string | null }, {  }>;
  msdyn_status_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_status_guid: string | null }, { msdyn_status_formatted?: string }>;
  msdyn_templaterequirementid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_templaterequirementid: string | null }, {  }>;
  msdyn_territory_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_territory_guid: string | null }, { msdyn_territory_formatted?: string }>;
  msdyn_timefrompromised: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_timefrompromised: Date | null }, { msdyn_timefrompromised_formatted?: string }>;
  msdyn_timegroup_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_timegroup_guid: string | null }, { msdyn_timegroup_formatted?: string }>;
  msdyn_timetopromised: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_timetopromised: Date | null }, { msdyn_timetopromised_formatted?: string }>;
  msdyn_timewindowend: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_timewindowend: Date | null }, { msdyn_timewindowend_formatted?: string }>;
  msdyn_timewindowstart: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_timewindowstart: Date | null }, { msdyn_timewindowstart_formatted?: string }>;
  msdyn_timezonefortimewindow: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_timezonefortimewindow: number | null }, {  }>;
  msdyn_todate: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_todate: Date | null }, { msdyn_todate_formatted?: string }>;
  msdyn_type: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_type: msdyn_resourcerequirement_msdyn_type | null }, { msdyn_type_formatted?: string }>;
  msdyn_workhourtemplate_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_workhourtemplate_guid: string | null }, { msdyn_workhourtemplate_formatted?: string }>;
  msdyn_worklocation: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_worklocation: msdyn_worklocation | null }, { msdyn_worklocation_formatted?: string }>;
  msdyn_workorder_guid: WebAttribute<msdyn_resourcerequirement_Select, { msdyn_workorder_guid: string | null }, { msdyn_workorder_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_resourcerequirement_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_resourcerequirement_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_resourcerequirement_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_resourcerequirement_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_resourcerequirement_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_resourcerequirement_Select, { statecode: msdyn_resourcerequirement_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_resourcerequirement_Select, { statuscode: msdyn_resourcerequirement_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_resourcerequirement_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_resourcerequirement_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<msdyn_resourcerequirement_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_resourcerequirement_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_resourcerequirement_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_allocationmethod: msdyn_resourcerequirement_msdyn_allocationmethod;
  msdyn_appointmentrequirementid_guid: XQW.Guid;
  msdyn_bookingsetupmetadataid_guid: XQW.Guid;
  msdyn_calendarid: string;
  msdyn_city: string;
  msdyn_costprice: number;
  msdyn_costprice_base: number;
  msdyn_country: string;
  msdyn_duration: number;
  msdyn_effort: any;
  msdyn_fromdate: Date;
  msdyn_fulfilledduration: number;
  msdyn_fulfilledhours: any;
  msdyn_hours: any;
  msdyn_internalflags: string;
  msdyn_isprimary: boolean;
  msdyn_istemplate: boolean;
  msdyn_latitude: number;
  msdyn_longitude: number;
  msdyn_name: string;
  msdyn_percentage: any;
  msdyn_pooltype: msdyn_pooltype;
  msdyn_priority_guid: XQW.Guid;
  msdyn_projectid_guid: XQW.Guid;
  msdyn_proposedduration: number;
  msdyn_quantity: any;
  msdyn_remainingduration: number;
  msdyn_requeststatus: string;
  msdyn_requirementgroupcontrolviewid: string;
  msdyn_requirementgroupid_guid: XQW.Guid;
  msdyn_requirementrelationshipid_guid: XQW.Guid;
  msdyn_resourcerequirementid: XQW.Guid;
  msdyn_resourcetype: msdyn_bookableresourcetype;
  msdyn_roleid_guid: XQW.Guid;
  msdyn_serviceappointment_guid: XQW.Guid;
  msdyn_sortoptions: string;
  msdyn_stateorprovince: string;
  msdyn_status_guid: XQW.Guid;
  msdyn_templaterequirementid: string;
  msdyn_territory_guid: XQW.Guid;
  msdyn_timefrompromised: Date;
  msdyn_timegroup_guid: XQW.Guid;
  msdyn_timetopromised: Date;
  msdyn_timewindowend: Date;
  msdyn_timewindowstart: Date;
  msdyn_timezonefortimewindow: number;
  msdyn_todate: Date;
  msdyn_type: msdyn_resourcerequirement_msdyn_type;
  msdyn_workhourtemplate_guid: XQW.Guid;
  msdyn_worklocation: msdyn_worklocation;
  msdyn_workorder_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_resourcerequirement_statecode;
  statuscode: msdyn_resourcerequirement_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_resourcerequirement_Expand {
  createdby: WebExpand<msdyn_resourcerequirement_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_resourcerequirement_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_resourcerequirement_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_resourcerequirement_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_AppointmentRequirementId: WebExpand<msdyn_resourcerequirement_Expand, Appointment_Select, Appointment_Filter, { msdyn_AppointmentRequirementId: Appointment_Result }>;
  msdyn_BookingSetupMetadataId: WebExpand<msdyn_resourcerequirement_Expand, msdyn_bookingsetupmetadata_Select, msdyn_bookingsetupmetadata_Filter, { msdyn_BookingSetupMetadataId: msdyn_bookingsetupmetadata_Result }>;
  msdyn_Priority: WebExpand<msdyn_resourcerequirement_Expand, msdyn_priority_Select, msdyn_priority_Filter, { msdyn_Priority: msdyn_priority_Result }>;
  msdyn_Status: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementstatus_Select, msdyn_requirementstatus_Filter, { msdyn_Status: msdyn_requirementstatus_Result }>;
  msdyn_Territory: WebExpand<msdyn_resourcerequirement_Expand, Territory_Select, Territory_Filter, { msdyn_Territory: Territory_Result }>;
  msdyn_TimeGroup: WebExpand<msdyn_resourcerequirement_Expand, msdyn_timegroup_Select, msdyn_timegroup_Filter, { msdyn_TimeGroup: msdyn_timegroup_Result }>;
  msdyn_WorkOrder: WebExpand<msdyn_resourcerequirement_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_WorkOrder: msdyn_workorder_Result }>;
  msdyn_msdyn_resourcerequirement_msdyn_requirementcharacteristic_RequirementSystemUse: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementcharacteristic_Select, msdyn_requirementcharacteristic_Filter, { msdyn_msdyn_resourcerequirement_msdyn_requirementcharacteristic_RequirementSystemUse: msdyn_requirementcharacteristic_Result[] }>;
  msdyn_msdyn_resourcerequirement_msdyn_workorderincident_ResourceRequirement: WebExpand<msdyn_resourcerequirement_Expand, msdyn_workorderincident_Select, msdyn_workorderincident_Filter, { msdyn_msdyn_resourcerequirement_msdyn_workorderincident_ResourceRequirement: msdyn_workorderincident_Result[] }>;
  msdyn_projectid: WebExpand<msdyn_resourcerequirement_Expand, msdyn_project_Select, msdyn_project_Filter, { msdyn_projectid: msdyn_project_Result }>;
  msdyn_requirementgroupid: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementgroup_Select, msdyn_requirementgroup_Filter, { msdyn_requirementgroupid: msdyn_requirementgroup_Result }>;
  msdyn_requirementrelationshipid: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementrelationship_Select, msdyn_requirementrelationship_Filter, { msdyn_requirementrelationshipid: msdyn_requirementrelationship_Result }>;
  msdyn_resourcerequirement_Annotations: WebExpand<msdyn_resourcerequirement_Expand, Annotation_Select, Annotation_Filter, { msdyn_resourcerequirement_Annotations: Annotation_Result[] }>;
  msdyn_resourcerequirement_AsyncOperations: WebExpand<msdyn_resourcerequirement_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_resourcerequirement_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_resourcerequirement_BulkDeleteFailures: WebExpand<msdyn_resourcerequirement_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_resourcerequirement_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_resourcerequirement_DuplicateBaseRecord: WebExpand<msdyn_resourcerequirement_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_resourcerequirement_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_resourcerequirement_DuplicateMatchingRecord: WebExpand<msdyn_resourcerequirement_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_resourcerequirement_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_resourcerequirement_MailboxTrackingFolders: WebExpand<msdyn_resourcerequirement_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_resourcerequirement_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_resourcerequirement_PrincipalObjectAttributeAccesses: WebExpand<msdyn_resourcerequirement_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_resourcerequirement_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_resourcerequirement_ProcessSession: WebExpand<msdyn_resourcerequirement_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_resourcerequirement_ProcessSession: ProcessSession_Result[] }>;
  msdyn_resourcerequirement_SyncErrors: WebExpand<msdyn_resourcerequirement_Expand, SyncError_Select, SyncError_Filter, { msdyn_resourcerequirement_SyncErrors: SyncError_Result[] }>;
  msdyn_resourcerequirement_UserEntityInstanceDatas: WebExpand<msdyn_resourcerequirement_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_resourcerequirement_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_resourcerequirement_bookableresource: WebExpand<msdyn_resourcerequirement_Expand, BookableResource_Select, BookableResource_Filter, { msdyn_resourcerequirement_bookableresource: BookableResource_Result[] }>;
  msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement: WebExpand<msdyn_resourcerequirement_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement: BookableResourceBooking_Result[] }>;
  msdyn_resourcerequirement_bookableresourcebookingheader_ResourceRequirement: WebExpand<msdyn_resourcerequirement_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { msdyn_resourcerequirement_bookableresourcebookingheader_ResourceRequirement: BookableResourceBookingHeader_Result[] }>;
  msdyn_resourcerequirement_bookingheader: WebExpand<msdyn_resourcerequirement_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { msdyn_resourcerequirement_bookingheader: BookableResourceBookingHeader_Result[] }>;
  msdyn_resourcerequirement_characteristicreq: WebExpand<msdyn_resourcerequirement_Expand, msdyn_characteristicreqforteammember_Select, msdyn_characteristicreqforteammember_Filter, { msdyn_resourcerequirement_characteristicreq: msdyn_characteristicreqforteammember_Result[] }>;
  msdyn_resourcerequirement_details: WebExpand<msdyn_resourcerequirement_Expand, msdyn_resourcerequirementdetail_Select, msdyn_resourcerequirementdetail_Filter, { msdyn_resourcerequirement_details: msdyn_resourcerequirementdetail_Result[] }>;
  msdyn_resourcerequirement_projectteam: WebExpand<msdyn_resourcerequirement_Expand, msdyn_projectteam_Select, msdyn_projectteam_Filter, { msdyn_resourcerequirement_projectteam: msdyn_projectteam_Result[] }>;
  msdyn_resourcerequirement_request: WebExpand<msdyn_resourcerequirement_Expand, msdyn_resourcerequest_Select, msdyn_resourcerequest_Filter, { msdyn_resourcerequirement_request: msdyn_resourcerequest_Result[] }>;
  msdyn_resourcerequirement_requirementcharacteristic_resourcerequirement: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementcharacteristic_Select, msdyn_requirementcharacteristic_Filter, { msdyn_resourcerequirement_requirementcharacteristic_resourcerequirement: msdyn_requirementcharacteristic_Result[] }>;
  msdyn_resourcerequirement_requirementdependency_dependentrequirement: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementdependency_Select, msdyn_requirementdependency_Filter, { msdyn_resourcerequirement_requirementdependency_dependentrequirement: msdyn_requirementdependency_Result[] }>;
  msdyn_resourcerequirement_requirementdependency_resourcerequirement: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementdependency_Select, msdyn_requirementdependency_Filter, { msdyn_resourcerequirement_requirementdependency_resourcerequirement: msdyn_requirementdependency_Result[] }>;
  msdyn_resourcerequirement_requirementorganizationunit_ResourceRequirement: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementorganizationunit_Select, msdyn_requirementorganizationunit_Filter, { msdyn_resourcerequirement_requirementorganizationunit_ResourceRequirement: msdyn_requirementorganizationunit_Result[] }>;
  msdyn_resourcerequirement_requirementresourcecategory_resourcerequirement: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementresourcecategory_Select, msdyn_requirementresourcecategory_Filter, { msdyn_resourcerequirement_requirementresourcecategory_resourcerequirement: msdyn_requirementresourcecategory_Result[] }>;
  msdyn_resourcerequirement_requirementresourcepreference_ResourceRequirement: WebExpand<msdyn_resourcerequirement_Expand, msdyn_requirementresourcepreference_Select, msdyn_requirementresourcepreference_Filter, { msdyn_resourcerequirement_requirementresourcepreference_ResourceRequirement: msdyn_requirementresourcepreference_Result[] }>;
  msdyn_resourcerequirement_systemuser: WebExpand<msdyn_resourcerequirement_Expand, SystemUser_Select, SystemUser_Filter, { msdyn_resourcerequirement_systemuser: SystemUser_Result[] }>;
  msdyn_roleid: WebExpand<msdyn_resourcerequirement_Expand, BookableResourceCategory_Select, BookableResourceCategory_Filter, { msdyn_roleid: BookableResourceCategory_Result }>;
  msdyn_serviceappointment: WebExpand<msdyn_resourcerequirement_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_serviceappointment: ServiceAppointment_Result }>;
  msdyn_workhourtemplate: WebExpand<msdyn_resourcerequirement_Expand, msdyn_workhourtemplate_Select, msdyn_workhourtemplate_Filter, { msdyn_workhourtemplate: msdyn_workhourtemplate_Result }>;
  ownerid: WebExpand<msdyn_resourcerequirement_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_resourcerequirement_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_resourcerequirement_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_resourcerequirement_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  transactioncurrencyid: WebExpand<msdyn_resourcerequirement_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface msdyn_resourcerequirement_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_allocationmethod_formatted?: string;
  msdyn_appointmentrequirementid_formatted?: string;
  msdyn_bookingsetupmetadataid_formatted?: string;
  msdyn_costprice_base_formatted?: string;
  msdyn_costprice_formatted?: string;
  msdyn_fromdate_formatted?: string;
  msdyn_pooltype_formatted?: string;
  msdyn_priority_formatted?: string;
  msdyn_projectid_formatted?: string;
  msdyn_requirementgroupid_formatted?: string;
  msdyn_requirementrelationshipid_formatted?: string;
  msdyn_resourcetype_formatted?: string;
  msdyn_roleid_formatted?: string;
  msdyn_serviceappointment_formatted?: string;
  msdyn_status_formatted?: string;
  msdyn_territory_formatted?: string;
  msdyn_timefrompromised_formatted?: string;
  msdyn_timegroup_formatted?: string;
  msdyn_timetopromised_formatted?: string;
  msdyn_timewindowend_formatted?: string;
  msdyn_timewindowstart_formatted?: string;
  msdyn_todate_formatted?: string;
  msdyn_type_formatted?: string;
  msdyn_workhourtemplate_formatted?: string;
  msdyn_worklocation_formatted?: string;
  msdyn_workorder_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface msdyn_resourcerequirement_Result extends msdyn_resourcerequirement_Base, msdyn_resourcerequirement_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_appointmentrequirementid_guid: string | null;
  msdyn_bookingsetupmetadataid_guid: string | null;
  msdyn_priority_guid: string | null;
  msdyn_projectid_guid: string | null;
  msdyn_requirementgroupid_guid: string | null;
  msdyn_requirementrelationshipid_guid: string | null;
  msdyn_roleid_guid: string | null;
  msdyn_serviceappointment_guid: string | null;
  msdyn_status_guid: string | null;
  msdyn_territory_guid: string | null;
  msdyn_timegroup_guid: string | null;
  msdyn_workhourtemplate_guid: string | null;
  msdyn_workorder_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface msdyn_resourcerequirement_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_AppointmentRequirementId: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_BookingSetupMetadataId: WebMappingRetrieve<msdyn_bookingsetupmetadata_Select,msdyn_bookingsetupmetadata_Expand,msdyn_bookingsetupmetadata_Filter,msdyn_bookingsetupmetadata_Fixed,msdyn_bookingsetupmetadata_Result,msdyn_bookingsetupmetadata_FormattedResult>;
  msdyn_Priority: WebMappingRetrieve<msdyn_priority_Select,msdyn_priority_Expand,msdyn_priority_Filter,msdyn_priority_Fixed,msdyn_priority_Result,msdyn_priority_FormattedResult>;
  msdyn_Status: WebMappingRetrieve<msdyn_requirementstatus_Select,msdyn_requirementstatus_Expand,msdyn_requirementstatus_Filter,msdyn_requirementstatus_Fixed,msdyn_requirementstatus_Result,msdyn_requirementstatus_FormattedResult>;
  msdyn_Territory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  msdyn_TimeGroup: WebMappingRetrieve<msdyn_timegroup_Select,msdyn_timegroup_Expand,msdyn_timegroup_Filter,msdyn_timegroup_Fixed,msdyn_timegroup_Result,msdyn_timegroup_FormattedResult>;
  msdyn_WorkOrder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  msdyn_projectid: WebMappingRetrieve<msdyn_project_Select,msdyn_project_Expand,msdyn_project_Filter,msdyn_project_Fixed,msdyn_project_Result,msdyn_project_FormattedResult>;
  msdyn_requirementgroupid: WebMappingRetrieve<msdyn_requirementgroup_Select,msdyn_requirementgroup_Expand,msdyn_requirementgroup_Filter,msdyn_requirementgroup_Fixed,msdyn_requirementgroup_Result,msdyn_requirementgroup_FormattedResult>;
  msdyn_requirementrelationshipid: WebMappingRetrieve<msdyn_requirementrelationship_Select,msdyn_requirementrelationship_Expand,msdyn_requirementrelationship_Filter,msdyn_requirementrelationship_Fixed,msdyn_requirementrelationship_Result,msdyn_requirementrelationship_FormattedResult>;
  msdyn_roleid: WebMappingRetrieve<BookableResourceCategory_Select,BookableResourceCategory_Expand,BookableResourceCategory_Filter,BookableResourceCategory_Fixed,BookableResourceCategory_Result,BookableResourceCategory_FormattedResult>;
  msdyn_serviceappointment: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_workhourtemplate: WebMappingRetrieve<msdyn_workhourtemplate_Select,msdyn_workhourtemplate_Expand,msdyn_workhourtemplate_Filter,msdyn_workhourtemplate_Fixed,msdyn_workhourtemplate_Result,msdyn_workhourtemplate_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface msdyn_resourcerequirement_RelatedMany {
  msdyn_msdyn_resourcerequirement_msdyn_requirementcharacteristic_RequirementSystemUse: WebMappingRetrieve<msdyn_requirementcharacteristic_Select,msdyn_requirementcharacteristic_Expand,msdyn_requirementcharacteristic_Filter,msdyn_requirementcharacteristic_Fixed,msdyn_requirementcharacteristic_Result,msdyn_requirementcharacteristic_FormattedResult>;
  msdyn_msdyn_resourcerequirement_msdyn_workorderincident_ResourceRequirement: WebMappingRetrieve<msdyn_workorderincident_Select,msdyn_workorderincident_Expand,msdyn_workorderincident_Filter,msdyn_workorderincident_Fixed,msdyn_workorderincident_Result,msdyn_workorderincident_FormattedResult>;
  msdyn_resourcerequirement_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_resourcerequirement_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_resourcerequirement_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_resourcerequirement_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_resourcerequirement_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_resourcerequirement_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_resourcerequirement_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_resourcerequirement_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_resourcerequirement_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_resourcerequirement_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_resourcerequirement_bookableresource: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  msdyn_resourcerequirement_bookableresourcebookingheader_ResourceRequirement: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  msdyn_resourcerequirement_bookingheader: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  msdyn_resourcerequirement_characteristicreq: WebMappingRetrieve<msdyn_characteristicreqforteammember_Select,msdyn_characteristicreqforteammember_Expand,msdyn_characteristicreqforteammember_Filter,msdyn_characteristicreqforteammember_Fixed,msdyn_characteristicreqforteammember_Result,msdyn_characteristicreqforteammember_FormattedResult>;
  msdyn_resourcerequirement_details: WebMappingRetrieve<msdyn_resourcerequirementdetail_Select,msdyn_resourcerequirementdetail_Expand,msdyn_resourcerequirementdetail_Filter,msdyn_resourcerequirementdetail_Fixed,msdyn_resourcerequirementdetail_Result,msdyn_resourcerequirementdetail_FormattedResult>;
  msdyn_resourcerequirement_projectteam: WebMappingRetrieve<msdyn_projectteam_Select,msdyn_projectteam_Expand,msdyn_projectteam_Filter,msdyn_projectteam_Fixed,msdyn_projectteam_Result,msdyn_projectteam_FormattedResult>;
  msdyn_resourcerequirement_request: WebMappingRetrieve<msdyn_resourcerequest_Select,msdyn_resourcerequest_Expand,msdyn_resourcerequest_Filter,msdyn_resourcerequest_Fixed,msdyn_resourcerequest_Result,msdyn_resourcerequest_FormattedResult>;
  msdyn_resourcerequirement_requirementcharacteristic_resourcerequirement: WebMappingRetrieve<msdyn_requirementcharacteristic_Select,msdyn_requirementcharacteristic_Expand,msdyn_requirementcharacteristic_Filter,msdyn_requirementcharacteristic_Fixed,msdyn_requirementcharacteristic_Result,msdyn_requirementcharacteristic_FormattedResult>;
  msdyn_resourcerequirement_requirementdependency_dependentrequirement: WebMappingRetrieve<msdyn_requirementdependency_Select,msdyn_requirementdependency_Expand,msdyn_requirementdependency_Filter,msdyn_requirementdependency_Fixed,msdyn_requirementdependency_Result,msdyn_requirementdependency_FormattedResult>;
  msdyn_resourcerequirement_requirementdependency_resourcerequirement: WebMappingRetrieve<msdyn_requirementdependency_Select,msdyn_requirementdependency_Expand,msdyn_requirementdependency_Filter,msdyn_requirementdependency_Fixed,msdyn_requirementdependency_Result,msdyn_requirementdependency_FormattedResult>;
  msdyn_resourcerequirement_requirementorganizationunit_ResourceRequirement: WebMappingRetrieve<msdyn_requirementorganizationunit_Select,msdyn_requirementorganizationunit_Expand,msdyn_requirementorganizationunit_Filter,msdyn_requirementorganizationunit_Fixed,msdyn_requirementorganizationunit_Result,msdyn_requirementorganizationunit_FormattedResult>;
  msdyn_resourcerequirement_requirementresourcecategory_resourcerequirement: WebMappingRetrieve<msdyn_requirementresourcecategory_Select,msdyn_requirementresourcecategory_Expand,msdyn_requirementresourcecategory_Filter,msdyn_requirementresourcecategory_Fixed,msdyn_requirementresourcecategory_Result,msdyn_requirementresourcecategory_FormattedResult>;
  msdyn_resourcerequirement_requirementresourcepreference_ResourceRequirement: WebMappingRetrieve<msdyn_requirementresourcepreference_Select,msdyn_requirementresourcepreference_Expand,msdyn_requirementresourcepreference_Filter,msdyn_requirementresourcepreference_Fixed,msdyn_requirementresourcepreference_Result,msdyn_requirementresourcepreference_FormattedResult>;
  msdyn_resourcerequirement_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_resourcerequirements: WebMappingRetrieve<msdyn_resourcerequirement_Select,msdyn_resourcerequirement_Expand,msdyn_resourcerequirement_Filter,msdyn_resourcerequirement_Fixed,msdyn_resourcerequirement_Result,msdyn_resourcerequirement_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_resourcerequirements: WebMappingRelated<msdyn_resourcerequirement_RelatedOne,msdyn_resourcerequirement_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_resourcerequirements: WebMappingCUDA<msdyn_resourcerequirement_Create,msdyn_resourcerequirement_Update,msdyn_resourcerequirement_Select>;
}
