interface msdyn_rtv_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_address1?: string | null;
  msdyn_address2?: string | null;
  msdyn_address3?: string | null;
  msdyn_autonumbering?: string | null;
  msdyn_city?: string | null;
  msdyn_country?: string | null;
  msdyn_latitude?: number | null;
  msdyn_longitude?: number | null;
  msdyn_name?: string | null;
  msdyn_postalcode?: string | null;
  msdyn_referenceno?: string | null;
  msdyn_requestdate?: Date | null;
  msdyn_returndate?: Date | null;
  msdyn_rtvid?: string | null;
  msdyn_stateorprovince?: string | null;
  msdyn_systemstatus?: msdyn_rtvsystemstatus | null;
  msdyn_totalamount?: number | null;
  msdyn_totalamount_base?: number | null;
  msdyn_vendorrma?: string | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_rtv_statecode | null;
  statuscode?: msdyn_rtv_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_rtv_Relationships {
  msdyn_msdyn_rtv_msdyn_rmareceiptproduct_RTV?: msdyn_rmareceiptproduct_Result[] | null;
  msdyn_msdyn_rtv_msdyn_rtvproduct_RTV?: msdyn_rtvproduct_Result[] | null;
  msdyn_rtv_ActivityPointers?: ActivityPointer_Result[] | null;
  msdyn_rtv_Annotations?: Annotation_Result[] | null;
  msdyn_rtv_Appointments?: Appointment_Result[] | null;
  msdyn_rtv_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_rtv_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_rtv_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_rtv_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_rtv_Emails?: Email_Result[] | null;
  msdyn_rtv_Faxes?: Fax_Result[] | null;
  msdyn_rtv_Letters?: Letter_Result[] | null;
  msdyn_rtv_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_rtv_PhoneCalls?: PhoneCall_Result[] | null;
  msdyn_rtv_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_rtv_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_rtv_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  msdyn_rtv_ServiceAppointments?: ServiceAppointment_Result[] | null;
  msdyn_rtv_SharePointDocumentLocations?: SharePointDocumentLocation_Result[] | null;
  msdyn_rtv_SharePointDocuments?: SharePointDocument_Result[] | null;
  msdyn_rtv_SocialActivities?: SocialActivity_Result[] | null;
  msdyn_rtv_SyncErrors?: SyncError_Result[] | null;
  msdyn_rtv_Tasks?: Task_Result[] | null;
  msdyn_rtv_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_rtv_connections1?: Connection_Result[] | null;
  msdyn_rtv_connections2?: Connection_Result[] | null;
  msdyn_rtv_msdyn_approvals?: msdyn_approval_Result[] | null;
  msdyn_rtv_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  msdyn_rtv_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_rtv_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  msdyn_rtv_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  msdyn_rtv_msfp_alerts?: msfp_alert_Result[] | null;
  msdyn_rtv_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  msdyn_rtv_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
}
interface msdyn_rtv extends msdyn_rtv_Base, msdyn_rtv_Relationships {
  msdyn_approveddeclinedby_bind$systemusers?: string | null;
  msdyn_booking_bind$bookableresourcebookings?: string | null;
  msdyn_originalpurchaseorder_bind$msdyn_purchaseorders?: string | null;
  msdyn_originatingrma_bind$msdyn_rmas?: string | null;
  msdyn_returnedby_bind$systemusers?: string | null;
  msdyn_shipvia_bind$msdyn_shipvias?: string | null;
  msdyn_substatus_bind$msdyn_rtvsubstatuses?: string | null;
  msdyn_taxcode_bind$msdyn_taxcodes?: string | null;
  msdyn_vendor_bind$accounts?: string | null;
  msdyn_vendorcontact_bind$contacts?: string | null;
  msdyn_workorder_bind$msdyn_workorders?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface msdyn_rtv_Create extends msdyn_rtv {
}
interface msdyn_rtv_Update extends msdyn_rtv {
}
interface msdyn_rtv_Select {
  createdby_guid: WebAttribute<msdyn_rtv_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_rtv_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_rtv_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_rtv_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_rtv_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_rtv_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_rtv_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_rtv_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_address1: WebAttribute<msdyn_rtv_Select, { msdyn_address1: string | null }, {  }>;
  msdyn_address2: WebAttribute<msdyn_rtv_Select, { msdyn_address2: string | null }, {  }>;
  msdyn_address3: WebAttribute<msdyn_rtv_Select, { msdyn_address3: string | null }, {  }>;
  msdyn_approveddeclinedby_guid: WebAttribute<msdyn_rtv_Select, { msdyn_approveddeclinedby_guid: string | null }, { msdyn_approveddeclinedby_formatted?: string }>;
  msdyn_autonumbering: WebAttribute<msdyn_rtv_Select, { msdyn_autonumbering: string | null }, {  }>;
  msdyn_booking_guid: WebAttribute<msdyn_rtv_Select, { msdyn_booking_guid: string | null }, { msdyn_booking_formatted?: string }>;
  msdyn_city: WebAttribute<msdyn_rtv_Select, { msdyn_city: string | null }, {  }>;
  msdyn_country: WebAttribute<msdyn_rtv_Select, { msdyn_country: string | null }, {  }>;
  msdyn_latitude: WebAttribute<msdyn_rtv_Select, { msdyn_latitude: number | null }, {  }>;
  msdyn_longitude: WebAttribute<msdyn_rtv_Select, { msdyn_longitude: number | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_rtv_Select, { msdyn_name: string | null }, {  }>;
  msdyn_originalpurchaseorder_guid: WebAttribute<msdyn_rtv_Select, { msdyn_originalpurchaseorder_guid: string | null }, { msdyn_originalpurchaseorder_formatted?: string }>;
  msdyn_originatingrma_guid: WebAttribute<msdyn_rtv_Select, { msdyn_originatingrma_guid: string | null }, { msdyn_originatingrma_formatted?: string }>;
  msdyn_postalcode: WebAttribute<msdyn_rtv_Select, { msdyn_postalcode: string | null }, {  }>;
  msdyn_referenceno: WebAttribute<msdyn_rtv_Select, { msdyn_referenceno: string | null }, {  }>;
  msdyn_requestdate: WebAttribute<msdyn_rtv_Select, { msdyn_requestdate: Date | null }, { msdyn_requestdate_formatted?: string }>;
  msdyn_returndate: WebAttribute<msdyn_rtv_Select, { msdyn_returndate: Date | null }, { msdyn_returndate_formatted?: string }>;
  msdyn_returnedby_guid: WebAttribute<msdyn_rtv_Select, { msdyn_returnedby_guid: string | null }, { msdyn_returnedby_formatted?: string }>;
  msdyn_rtvid: WebAttribute<msdyn_rtv_Select, { msdyn_rtvid: string | null }, {  }>;
  msdyn_shipvia_guid: WebAttribute<msdyn_rtv_Select, { msdyn_shipvia_guid: string | null }, { msdyn_shipvia_formatted?: string }>;
  msdyn_stateorprovince: WebAttribute<msdyn_rtv_Select, { msdyn_stateorprovince: string | null }, {  }>;
  msdyn_substatus_guid: WebAttribute<msdyn_rtv_Select, { msdyn_substatus_guid: string | null }, { msdyn_substatus_formatted?: string }>;
  msdyn_systemstatus: WebAttribute<msdyn_rtv_Select, { msdyn_systemstatus: msdyn_rtvsystemstatus | null }, { msdyn_systemstatus_formatted?: string }>;
  msdyn_taxcode_guid: WebAttribute<msdyn_rtv_Select, { msdyn_taxcode_guid: string | null }, { msdyn_taxcode_formatted?: string }>;
  msdyn_totalamount: WebAttribute<msdyn_rtv_Select, { msdyn_totalamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_totalamount_base: WebAttribute<msdyn_rtv_Select, { msdyn_totalamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_totalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_vendor_guid: WebAttribute<msdyn_rtv_Select, { msdyn_vendor_guid: string | null }, { msdyn_vendor_formatted?: string }>;
  msdyn_vendorcontact_guid: WebAttribute<msdyn_rtv_Select, { msdyn_vendorcontact_guid: string | null }, { msdyn_vendorcontact_formatted?: string }>;
  msdyn_vendorrma: WebAttribute<msdyn_rtv_Select, { msdyn_vendorrma: string | null }, {  }>;
  msdyn_workorder_guid: WebAttribute<msdyn_rtv_Select, { msdyn_workorder_guid: string | null }, { msdyn_workorder_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_rtv_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_rtv_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_rtv_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_rtv_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_rtv_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_rtv_Select, { statecode: msdyn_rtv_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_rtv_Select, { statuscode: msdyn_rtv_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_rtv_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_rtv_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<msdyn_rtv_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_rtv_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_rtv_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_address1: string;
  msdyn_address2: string;
  msdyn_address3: string;
  msdyn_approveddeclinedby_guid: XQW.Guid;
  msdyn_autonumbering: string;
  msdyn_booking_guid: XQW.Guid;
  msdyn_city: string;
  msdyn_country: string;
  msdyn_latitude: number;
  msdyn_longitude: number;
  msdyn_name: string;
  msdyn_originalpurchaseorder_guid: XQW.Guid;
  msdyn_originatingrma_guid: XQW.Guid;
  msdyn_postalcode: string;
  msdyn_referenceno: string;
  msdyn_requestdate: Date;
  msdyn_returndate: Date;
  msdyn_returnedby_guid: XQW.Guid;
  msdyn_rtvid: XQW.Guid;
  msdyn_shipvia_guid: XQW.Guid;
  msdyn_stateorprovince: string;
  msdyn_substatus_guid: XQW.Guid;
  msdyn_systemstatus: msdyn_rtvsystemstatus;
  msdyn_taxcode_guid: XQW.Guid;
  msdyn_totalamount: number;
  msdyn_totalamount_base: number;
  msdyn_vendor_guid: XQW.Guid;
  msdyn_vendorcontact_guid: XQW.Guid;
  msdyn_vendorrma: string;
  msdyn_workorder_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_rtv_statecode;
  statuscode: msdyn_rtv_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_rtv_Expand {
  createdby: WebExpand<msdyn_rtv_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_rtv_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_rtv_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_rtv_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_approveddeclinedby: WebExpand<msdyn_rtv_Expand, SystemUser_Select, SystemUser_Filter, { msdyn_approveddeclinedby: SystemUser_Result }>;
  msdyn_booking: WebExpand<msdyn_rtv_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { msdyn_booking: BookableResourceBooking_Result }>;
  msdyn_msdyn_rtv_msdyn_rmareceiptproduct_RTV: WebExpand<msdyn_rtv_Expand, msdyn_rmareceiptproduct_Select, msdyn_rmareceiptproduct_Filter, { msdyn_msdyn_rtv_msdyn_rmareceiptproduct_RTV: msdyn_rmareceiptproduct_Result[] }>;
  msdyn_msdyn_rtv_msdyn_rtvproduct_RTV: WebExpand<msdyn_rtv_Expand, msdyn_rtvproduct_Select, msdyn_rtvproduct_Filter, { msdyn_msdyn_rtv_msdyn_rtvproduct_RTV: msdyn_rtvproduct_Result[] }>;
  msdyn_originalpurchaseorder: WebExpand<msdyn_rtv_Expand, msdyn_purchaseorder_Select, msdyn_purchaseorder_Filter, { msdyn_originalpurchaseorder: msdyn_purchaseorder_Result }>;
  msdyn_originatingrma: WebExpand<msdyn_rtv_Expand, msdyn_rma_Select, msdyn_rma_Filter, { msdyn_originatingrma: msdyn_rma_Result }>;
  msdyn_returnedby: WebExpand<msdyn_rtv_Expand, SystemUser_Select, SystemUser_Filter, { msdyn_returnedby: SystemUser_Result }>;
  msdyn_rtv_ActivityPointers: WebExpand<msdyn_rtv_Expand, ActivityPointer_Select, ActivityPointer_Filter, { msdyn_rtv_ActivityPointers: ActivityPointer_Result[] }>;
  msdyn_rtv_Annotations: WebExpand<msdyn_rtv_Expand, Annotation_Select, Annotation_Filter, { msdyn_rtv_Annotations: Annotation_Result[] }>;
  msdyn_rtv_Appointments: WebExpand<msdyn_rtv_Expand, Appointment_Select, Appointment_Filter, { msdyn_rtv_Appointments: Appointment_Result[] }>;
  msdyn_rtv_AsyncOperations: WebExpand<msdyn_rtv_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_rtv_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_rtv_BulkDeleteFailures: WebExpand<msdyn_rtv_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_rtv_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_rtv_DuplicateBaseRecord: WebExpand<msdyn_rtv_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_rtv_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_rtv_DuplicateMatchingRecord: WebExpand<msdyn_rtv_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_rtv_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_rtv_Emails: WebExpand<msdyn_rtv_Expand, Email_Select, Email_Filter, { msdyn_rtv_Emails: Email_Result[] }>;
  msdyn_rtv_Faxes: WebExpand<msdyn_rtv_Expand, Fax_Select, Fax_Filter, { msdyn_rtv_Faxes: Fax_Result[] }>;
  msdyn_rtv_Letters: WebExpand<msdyn_rtv_Expand, Letter_Select, Letter_Filter, { msdyn_rtv_Letters: Letter_Result[] }>;
  msdyn_rtv_MailboxTrackingFolders: WebExpand<msdyn_rtv_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_rtv_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_rtv_PhoneCalls: WebExpand<msdyn_rtv_Expand, PhoneCall_Select, PhoneCall_Filter, { msdyn_rtv_PhoneCalls: PhoneCall_Result[] }>;
  msdyn_rtv_PrincipalObjectAttributeAccesses: WebExpand<msdyn_rtv_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_rtv_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_rtv_ProcessSession: WebExpand<msdyn_rtv_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_rtv_ProcessSession: ProcessSession_Result[] }>;
  msdyn_rtv_RecurringAppointmentMasters: WebExpand<msdyn_rtv_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { msdyn_rtv_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  msdyn_rtv_ServiceAppointments: WebExpand<msdyn_rtv_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { msdyn_rtv_ServiceAppointments: ServiceAppointment_Result[] }>;
  msdyn_rtv_SharePointDocumentLocations: WebExpand<msdyn_rtv_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { msdyn_rtv_SharePointDocumentLocations: SharePointDocumentLocation_Result[] }>;
  msdyn_rtv_SharePointDocuments: WebExpand<msdyn_rtv_Expand, SharePointDocument_Select, SharePointDocument_Filter, { msdyn_rtv_SharePointDocuments: SharePointDocument_Result[] }>;
  msdyn_rtv_SocialActivities: WebExpand<msdyn_rtv_Expand, SocialActivity_Select, SocialActivity_Filter, { msdyn_rtv_SocialActivities: SocialActivity_Result[] }>;
  msdyn_rtv_SyncErrors: WebExpand<msdyn_rtv_Expand, SyncError_Select, SyncError_Filter, { msdyn_rtv_SyncErrors: SyncError_Result[] }>;
  msdyn_rtv_Tasks: WebExpand<msdyn_rtv_Expand, Task_Select, Task_Filter, { msdyn_rtv_Tasks: Task_Result[] }>;
  msdyn_rtv_UserEntityInstanceDatas: WebExpand<msdyn_rtv_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_rtv_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_rtv_connections1: WebExpand<msdyn_rtv_Expand, Connection_Select, Connection_Filter, { msdyn_rtv_connections1: Connection_Result[] }>;
  msdyn_rtv_connections2: WebExpand<msdyn_rtv_Expand, Connection_Select, Connection_Filter, { msdyn_rtv_connections2: Connection_Result[] }>;
  msdyn_rtv_msdyn_approvals: WebExpand<msdyn_rtv_Expand, msdyn_approval_Select, msdyn_approval_Filter, { msdyn_rtv_msdyn_approvals: msdyn_approval_Result[] }>;
  msdyn_rtv_msdyn_bookingalerts: WebExpand<msdyn_rtv_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { msdyn_rtv_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  msdyn_rtv_msdyn_ocliveworkitems: WebExpand<msdyn_rtv_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_rtv_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  msdyn_rtv_msdyn_ocoutboundmessages: WebExpand<msdyn_rtv_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_rtv_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_rtv_msdyn_ocsessions: WebExpand<msdyn_rtv_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { msdyn_rtv_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  msdyn_rtv_msfp_alerts: WebExpand<msdyn_rtv_Expand, msfp_alert_Select, msfp_alert_Filter, { msdyn_rtv_msfp_alerts: msfp_alert_Result[] }>;
  msdyn_rtv_msfp_surveyinvites: WebExpand<msdyn_rtv_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { msdyn_rtv_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  msdyn_rtv_msfp_surveyresponses: WebExpand<msdyn_rtv_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { msdyn_rtv_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  msdyn_shipvia: WebExpand<msdyn_rtv_Expand, msdyn_shipvia_Select, msdyn_shipvia_Filter, { msdyn_shipvia: msdyn_shipvia_Result }>;
  msdyn_substatus: WebExpand<msdyn_rtv_Expand, msdyn_rtvsubstatus_Select, msdyn_rtvsubstatus_Filter, { msdyn_substatus: msdyn_rtvsubstatus_Result }>;
  msdyn_taxcode: WebExpand<msdyn_rtv_Expand, msdyn_taxcode_Select, msdyn_taxcode_Filter, { msdyn_taxcode: msdyn_taxcode_Result }>;
  msdyn_vendor: WebExpand<msdyn_rtv_Expand, Account_Select, Account_Filter, { msdyn_vendor: Account_Result }>;
  msdyn_vendorcontact: WebExpand<msdyn_rtv_Expand, Contact_Select, Contact_Filter, { msdyn_vendorcontact: Contact_Result }>;
  msdyn_workorder: WebExpand<msdyn_rtv_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_workorder: msdyn_workorder_Result }>;
  ownerid: WebExpand<msdyn_rtv_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_rtv_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_rtv_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_rtv_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  transactioncurrencyid: WebExpand<msdyn_rtv_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface msdyn_rtv_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_approveddeclinedby_formatted?: string;
  msdyn_booking_formatted?: string;
  msdyn_originalpurchaseorder_formatted?: string;
  msdyn_originatingrma_formatted?: string;
  msdyn_requestdate_formatted?: string;
  msdyn_returndate_formatted?: string;
  msdyn_returnedby_formatted?: string;
  msdyn_shipvia_formatted?: string;
  msdyn_substatus_formatted?: string;
  msdyn_systemstatus_formatted?: string;
  msdyn_taxcode_formatted?: string;
  msdyn_totalamount_base_formatted?: string;
  msdyn_totalamount_formatted?: string;
  msdyn_vendor_formatted?: string;
  msdyn_vendorcontact_formatted?: string;
  msdyn_workorder_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface msdyn_rtv_Result extends msdyn_rtv_Base, msdyn_rtv_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_approveddeclinedby_guid: string | null;
  msdyn_booking_guid: string | null;
  msdyn_originalpurchaseorder_guid: string | null;
  msdyn_originatingrma_guid: string | null;
  msdyn_returnedby_guid: string | null;
  msdyn_shipvia_guid: string | null;
  msdyn_substatus_guid: string | null;
  msdyn_taxcode_guid: string | null;
  msdyn_vendor_guid: string | null;
  msdyn_vendorcontact_guid: string | null;
  msdyn_workorder_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface msdyn_rtv_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_approveddeclinedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_booking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  msdyn_originalpurchaseorder: WebMappingRetrieve<msdyn_purchaseorder_Select,msdyn_purchaseorder_Expand,msdyn_purchaseorder_Filter,msdyn_purchaseorder_Fixed,msdyn_purchaseorder_Result,msdyn_purchaseorder_FormattedResult>;
  msdyn_originatingrma: WebMappingRetrieve<msdyn_rma_Select,msdyn_rma_Expand,msdyn_rma_Filter,msdyn_rma_Fixed,msdyn_rma_Result,msdyn_rma_FormattedResult>;
  msdyn_returnedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_shipvia: WebMappingRetrieve<msdyn_shipvia_Select,msdyn_shipvia_Expand,msdyn_shipvia_Filter,msdyn_shipvia_Fixed,msdyn_shipvia_Result,msdyn_shipvia_FormattedResult>;
  msdyn_substatus: WebMappingRetrieve<msdyn_rtvsubstatus_Select,msdyn_rtvsubstatus_Expand,msdyn_rtvsubstatus_Filter,msdyn_rtvsubstatus_Fixed,msdyn_rtvsubstatus_Result,msdyn_rtvsubstatus_FormattedResult>;
  msdyn_taxcode: WebMappingRetrieve<msdyn_taxcode_Select,msdyn_taxcode_Expand,msdyn_taxcode_Filter,msdyn_taxcode_Fixed,msdyn_taxcode_Result,msdyn_taxcode_FormattedResult>;
  msdyn_vendor: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_vendorcontact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface msdyn_rtv_RelatedMany {
  msdyn_msdyn_rtv_msdyn_rmareceiptproduct_RTV: WebMappingRetrieve<msdyn_rmareceiptproduct_Select,msdyn_rmareceiptproduct_Expand,msdyn_rmareceiptproduct_Filter,msdyn_rmareceiptproduct_Fixed,msdyn_rmareceiptproduct_Result,msdyn_rmareceiptproduct_FormattedResult>;
  msdyn_msdyn_rtv_msdyn_rtvproduct_RTV: WebMappingRetrieve<msdyn_rtvproduct_Select,msdyn_rtvproduct_Expand,msdyn_rtvproduct_Filter,msdyn_rtvproduct_Fixed,msdyn_rtvproduct_Result,msdyn_rtvproduct_FormattedResult>;
  msdyn_rtv_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  msdyn_rtv_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_rtv_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  msdyn_rtv_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_rtv_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_rtv_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_rtv_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_rtv_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  msdyn_rtv_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  msdyn_rtv_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  msdyn_rtv_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_rtv_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  msdyn_rtv_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_rtv_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_rtv_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  msdyn_rtv_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  msdyn_rtv_SharePointDocumentLocations: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  msdyn_rtv_SharePointDocuments: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  msdyn_rtv_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  msdyn_rtv_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_rtv_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  msdyn_rtv_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_rtv_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_rtv_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  msdyn_rtv_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  msdyn_rtv_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  msdyn_rtv_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_rtv_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  msdyn_rtv_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  msdyn_rtv_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  msdyn_rtv_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  msdyn_rtv_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_rtvs: WebMappingRetrieve<msdyn_rtv_Select,msdyn_rtv_Expand,msdyn_rtv_Filter,msdyn_rtv_Fixed,msdyn_rtv_Result,msdyn_rtv_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_rtvs: WebMappingRelated<msdyn_rtv_RelatedOne,msdyn_rtv_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_rtvs: WebMappingCUDA<msdyn_rtv_Create,msdyn_rtv_Update,msdyn_rtv_Select>;
}
