interface msdyn_liveworkstream_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_allowedpresences?: msdyn_basepresencestatus | null;
  msdyn_apikey?: string | null;
  msdyn_apikeyversionnumber?: number | null;
  msdyn_assignworkitemafterdecline?: number | null;
  msdyn_autocloseafterinactivity?: number | null;
  msdyn_bot_rule?: string | null;
  msdyn_capacityformat?: msdyn_capacityformat | null;
  msdyn_capacityrequired?: number | null;
  msdyn_connectorsurl?: string | null;
  msdyn_conversationmode?: msdyn_liveworkstream_msdyn_conversationmode | null;
  msdyn_customerid?: string | null;
  msdyn_direction?: msdyn_msdyn_liveworkstream_msdyn_direction | null;
  msdyn_enableagentaffinity?: boolean | null;
  msdyn_enableautomatedmessages?: boolean | null;
  msdyn_enableselectingfrompushbasedworkstreams?: boolean | null;
  msdyn_fallbacklanguage?: string | null;
  msdyn_followupafterwaiting?: number | null;
  msdyn_handlingtimethreshold?: number | null;
  msdyn_isdefault?: boolean | null;
  msdyn_lastvalidationon?: Date | null;
  msdyn_lastvalidationstatus?: string | null;
  msdyn_liveworkstreamid?: string | null;
  msdyn_matchinglogic?: msdyn_liveworkstream_msdyn_matchinglogic | null;
  msdyn_maxconcurrentconnection?: number | null;
  msdyn_mode?: msdyn_ocadminmode | null;
  msdyn_name?: string | null;
  msdyn_notification?: msdyn_notificationtypes | null;
  msdyn_notificationscenarioplaceholder?: string | null;
  msdyn_notificationtemplate_consult?: string | null;
  msdyn_notificationtemplate_incoming_auth?: string | null;
  msdyn_notificationtemplate_incoming_unauth?: string | null;
  msdyn_notificationtemplate_supervisorassign?: string | null;
  msdyn_notificationtemplate_transfer?: string | null;
  msdyn_recordidentificationrule?: string | null;
  msdyn_recordidentificationvalidationrule?: string | null;
  msdyn_screenpoptimeout?: number | null;
  msdyn_screenpoptimeout_optionSet?: msdyn_screenpoptimeout | null;
  msdyn_sessionscenarioplaceholder?: string | null;
  msdyn_sessiontemplate_default?: string | null;
  msdyn_skillattachmentrulescount?: number | null;
  msdyn_skillattachmentrulescount_date?: Date | null;
  msdyn_skillattachmentrulescount_state?: number | null;
  msdyn_smsprovider?: msdyn_smsprovider | null;
  msdyn_streamsource?: msdyn_streamsource | null;
  msdyn_telesigninboundurl?: string | null;
  msdyn_twilioinboundurl?: string | null;
  msdyn_waitingtimethreshold?: number | null;
  msdyn_workdistributionmode?: msdyn_workdistributionmode | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_liveworkstream_statecode | null;
  statuscode?: msdyn_liveworkstream_statuscode | null;
  timezoneruleversionnumber?: number | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_liveworkstream_Relationships {
  msdyn_entityroutingconfigurationId?: msdyn_entityroutingconfiguration_Result | null;
  msdyn_liveworkstream_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_liveworkstream_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_liveworkstream_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_liveworkstream_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_liveworkstream_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_liveworkstream_SyncErrors?: SyncError_Result[] | null;
  msdyn_liveworkstream_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  msdyn_liveworkstream_msdyn_liveworkstreamcapacityprofile?: msdyn_liveworkstreamcapacityprofile_Result[] | null;
  msdyn_liveworkstream_msdyn_routingconfiguration_liveworkstreamid?: msdyn_routingconfiguration_Result[] | null;
  msdyn_liveworkstream_msdyn_rulesetdependencymapping_msdyn_referencedpolymorphicentityid?: msdyn_rulesetdependencymapping_Result[] | null;
  msdyn_liveworkstream_ocruleitem?: msdyn_ocruleitem_Result[] | null;
  msdyn_liveworkstream_queueitem_liveworkstreamid?: QueueItem_Result[] | null;
  msdyn_liveworkstream_skillattachmentruleitem?: msdyn_skillattachmentruleitem_Result[] | null;
  msdyn_masterentityroutingconfigurationId?: msdyn_masterentityroutingconfiguration_Result | null;
  msdyn_msdyn_cannedmessage_liveworkstream?: msdyn_cannedmessage_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_entityconfig?: msdyn_entityconfig_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_livechatconfig_liveworkstreamid?: msdyn_livechatconfig_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_liveconversation?: msdyn_liveconversation_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_occustommessagingchannel_liveworkstreamid?: msdyn_occustommessagingchannel_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_ocfbpage?: msdyn_ocfbpage_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_oclinechannelconfig_liveworkstreamid?: msdyn_oclinechannelconfig_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_ocliveworkitem_liveworkstreamid?: msdyn_ocliveworkitem_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_ocliveworkstreamcontextvariable_liveworkstreamid?: msdyn_ocliveworkstreamcontextvariable_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_ocsmschannelsetting_liveworkstreamid?: msdyn_ocsmschannelsetting_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_octeamschannelconfig_liveworkstreamid?: msdyn_octeamschannelconfig_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_octwitterhandle_liveworkstreamid?: msdyn_octwitterhandle_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_ocwechatchannelconfig_liveworkstreamid?: msdyn_ocwechatchannelconfig_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_ocwhatsappchannelnumber_liveworkstreamid?: msdyn_ocwhatsappchannelnumber_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_scenario?: msdyn_scenario_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_smsnumber?: msdyn_smsnumber_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_surveyquestion?: msdyn_surveyquestion_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_unifiedroutingrun_workstream?: msdyn_unifiedroutingrun_Result[] | null;
  msdyn_msdyn_liveworkstream_msdyn_urnotificationtemplatemapping_workstream?: msdyn_urnotificationtemplatemapping_Result[] | null;
  msdyn_msdyn_liveworkstream_systemuser?: SystemUser_Result[] | null;
  msdyn_msdyn_ocoutboundconfiguration_msdyn_liveworkstream?: msdyn_ocoutboundconfiguration_Result[] | null;
  msdyn_ocoutboundmessage_ocliveworkstream?: msdyn_ocoutboundmessage_Result[] | null;
}
interface msdyn_liveworkstream extends msdyn_liveworkstream_Base, msdyn_liveworkstream_Relationships {
  msdyn_bot_queue_bind$queues?: string | null;
  msdyn_bot_user_bind$systemusers?: string | null;
  msdyn_entityroutingconfigurationId_bind$msdyn_entityroutingconfigurations?: string | null;
  msdyn_masterentityroutingconfigurationId_bind$msdyn_masterentityroutingconfigurations?: string | null;
  msdyn_outboundqueueid_bind$queues?: string | null;
  msdyn_routingcontractid_bind$msdyn_decisioncontracts?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface msdyn_liveworkstream_Create extends msdyn_liveworkstream {
}
interface msdyn_liveworkstream_Update extends msdyn_liveworkstream {
}
interface msdyn_liveworkstream_Select {
  createdby_guid: WebAttribute<msdyn_liveworkstream_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_liveworkstream_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_liveworkstream_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<msdyn_liveworkstream_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_liveworkstream_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_liveworkstream_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_liveworkstream_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_allowedpresences: WebAttribute<msdyn_liveworkstream_Select, { msdyn_allowedpresences: msdyn_basepresencestatus | null }, { msdyn_allowedpresences_formatted?: string }>;
  msdyn_apikey: WebAttribute<msdyn_liveworkstream_Select, { msdyn_apikey: string | null }, {  }>;
  msdyn_apikeyversionnumber: WebAttribute<msdyn_liveworkstream_Select, { msdyn_apikeyversionnumber: number | null }, {  }>;
  msdyn_assignworkitemafterdecline: WebAttribute<msdyn_liveworkstream_Select, { msdyn_assignworkitemafterdecline: number | null }, {  }>;
  msdyn_autocloseafterinactivity: WebAttribute<msdyn_liveworkstream_Select, { msdyn_autocloseafterinactivity: number | null }, {  }>;
  msdyn_bot_queue_guid: WebAttribute<msdyn_liveworkstream_Select, { msdyn_bot_queue_guid: string | null }, { msdyn_bot_queue_formatted?: string }>;
  msdyn_bot_rule: WebAttribute<msdyn_liveworkstream_Select, { msdyn_bot_rule: string | null }, {  }>;
  msdyn_bot_user_guid: WebAttribute<msdyn_liveworkstream_Select, { msdyn_bot_user_guid: string | null }, { msdyn_bot_user_formatted?: string }>;
  msdyn_capacityformat: WebAttribute<msdyn_liveworkstream_Select, { msdyn_capacityformat: msdyn_capacityformat | null }, { msdyn_capacityformat_formatted?: string }>;
  msdyn_capacityrequired: WebAttribute<msdyn_liveworkstream_Select, { msdyn_capacityrequired: number | null }, {  }>;
  msdyn_connectorsurl: WebAttribute<msdyn_liveworkstream_Select, { msdyn_connectorsurl: string | null }, {  }>;
  msdyn_conversationmode: WebAttribute<msdyn_liveworkstream_Select, { msdyn_conversationmode: msdyn_liveworkstream_msdyn_conversationmode | null }, { msdyn_conversationmode_formatted?: string }>;
  msdyn_customerid: WebAttribute<msdyn_liveworkstream_Select, { msdyn_customerid: string | null }, {  }>;
  msdyn_direction: WebAttribute<msdyn_liveworkstream_Select, { msdyn_direction: msdyn_msdyn_liveworkstream_msdyn_direction | null }, { msdyn_direction_formatted?: string }>;
  msdyn_enableagentaffinity: WebAttribute<msdyn_liveworkstream_Select, { msdyn_enableagentaffinity: boolean | null }, {  }>;
  msdyn_enableautomatedmessages: WebAttribute<msdyn_liveworkstream_Select, { msdyn_enableautomatedmessages: boolean | null }, {  }>;
  msdyn_enableselectingfrompushbasedworkstreams: WebAttribute<msdyn_liveworkstream_Select, { msdyn_enableselectingfrompushbasedworkstreams: boolean | null }, {  }>;
  msdyn_entityroutingconfigurationid_guid: WebAttribute<msdyn_liveworkstream_Select, { msdyn_entityroutingconfigurationid_guid: string | null }, { msdyn_entityroutingconfigurationid_formatted?: string }>;
  msdyn_fallbacklanguage: WebAttribute<msdyn_liveworkstream_Select, { msdyn_fallbacklanguage: string | null }, {  }>;
  msdyn_followupafterwaiting: WebAttribute<msdyn_liveworkstream_Select, { msdyn_followupafterwaiting: number | null }, {  }>;
  msdyn_handlingtimethreshold: WebAttribute<msdyn_liveworkstream_Select, { msdyn_handlingtimethreshold: number | null }, {  }>;
  msdyn_isdefault: WebAttribute<msdyn_liveworkstream_Select, { msdyn_isdefault: boolean | null }, {  }>;
  msdyn_lastvalidationon: WebAttribute<msdyn_liveworkstream_Select, { msdyn_lastvalidationon: Date | null }, { msdyn_lastvalidationon_formatted?: string }>;
  msdyn_lastvalidationstatus: WebAttribute<msdyn_liveworkstream_Select, { msdyn_lastvalidationstatus: string | null }, {  }>;
  msdyn_liveworkstreamid: WebAttribute<msdyn_liveworkstream_Select, { msdyn_liveworkstreamid: string | null }, {  }>;
  msdyn_masterentityroutingconfigurationid_guid: WebAttribute<msdyn_liveworkstream_Select, { msdyn_masterentityroutingconfigurationid_guid: string | null }, { msdyn_masterentityroutingconfigurationid_formatted?: string }>;
  msdyn_matchinglogic: WebAttribute<msdyn_liveworkstream_Select, { msdyn_matchinglogic: msdyn_liveworkstream_msdyn_matchinglogic | null }, { msdyn_matchinglogic_formatted?: string }>;
  msdyn_maxconcurrentconnection: WebAttribute<msdyn_liveworkstream_Select, { msdyn_maxconcurrentconnection: number | null }, {  }>;
  msdyn_mode: WebAttribute<msdyn_liveworkstream_Select, { msdyn_mode: msdyn_ocadminmode | null }, { msdyn_mode_formatted?: string }>;
  msdyn_name: WebAttribute<msdyn_liveworkstream_Select, { msdyn_name: string | null }, {  }>;
  msdyn_notification: WebAttribute<msdyn_liveworkstream_Select, { msdyn_notification: msdyn_notificationtypes | null }, { msdyn_notification_formatted?: string }>;
  msdyn_notificationscenarioplaceholder: WebAttribute<msdyn_liveworkstream_Select, { msdyn_notificationscenarioplaceholder: string | null }, {  }>;
  msdyn_notificationtemplate_consult: WebAttribute<msdyn_liveworkstream_Select, { msdyn_notificationtemplate_consult: string | null }, {  }>;
  msdyn_notificationtemplate_incoming_auth: WebAttribute<msdyn_liveworkstream_Select, { msdyn_notificationtemplate_incoming_auth: string | null }, {  }>;
  msdyn_notificationtemplate_incoming_unauth: WebAttribute<msdyn_liveworkstream_Select, { msdyn_notificationtemplate_incoming_unauth: string | null }, {  }>;
  msdyn_notificationtemplate_supervisorassign: WebAttribute<msdyn_liveworkstream_Select, { msdyn_notificationtemplate_supervisorassign: string | null }, {  }>;
  msdyn_notificationtemplate_transfer: WebAttribute<msdyn_liveworkstream_Select, { msdyn_notificationtemplate_transfer: string | null }, {  }>;
  msdyn_outboundqueueid_guid: WebAttribute<msdyn_liveworkstream_Select, { msdyn_outboundqueueid_guid: string | null }, { msdyn_outboundqueueid_formatted?: string }>;
  msdyn_recordidentificationrule: WebAttribute<msdyn_liveworkstream_Select, { msdyn_recordidentificationrule: string | null }, {  }>;
  msdyn_recordidentificationvalidationrule: WebAttribute<msdyn_liveworkstream_Select, { msdyn_recordidentificationvalidationrule: string | null }, {  }>;
  msdyn_routingcontractid_guid: WebAttribute<msdyn_liveworkstream_Select, { msdyn_routingcontractid_guid: string | null }, { msdyn_routingcontractid_formatted?: string }>;
  msdyn_screenpoptimeout: WebAttribute<msdyn_liveworkstream_Select, { msdyn_screenpoptimeout: number | null }, {  }>;
  msdyn_screenpoptimeout_optionSet: WebAttribute<msdyn_liveworkstream_Select, { msdyn_screenpoptimeout_optionSet: msdyn_screenpoptimeout | null }, { msdyn_screenpoptimeout_optionSet_formatted?: string }>;
  msdyn_sessionscenarioplaceholder: WebAttribute<msdyn_liveworkstream_Select, { msdyn_sessionscenarioplaceholder: string | null }, {  }>;
  msdyn_sessiontemplate_default: WebAttribute<msdyn_liveworkstream_Select, { msdyn_sessiontemplate_default: string | null }, {  }>;
  msdyn_skillattachmentrulescount: WebAttribute<msdyn_liveworkstream_Select, { msdyn_skillattachmentrulescount: number | null }, {  }>;
  msdyn_skillattachmentrulescount_date: WebAttribute<msdyn_liveworkstream_Select, { msdyn_skillattachmentrulescount_date: Date | null }, { msdyn_skillattachmentrulescount_date_formatted?: string }>;
  msdyn_skillattachmentrulescount_state: WebAttribute<msdyn_liveworkstream_Select, { msdyn_skillattachmentrulescount_state: number | null }, {  }>;
  msdyn_smsprovider: WebAttribute<msdyn_liveworkstream_Select, { msdyn_smsprovider: msdyn_smsprovider | null }, { msdyn_smsprovider_formatted?: string }>;
  msdyn_streamsource: WebAttribute<msdyn_liveworkstream_Select, { msdyn_streamsource: msdyn_streamsource | null }, { msdyn_streamsource_formatted?: string }>;
  msdyn_telesigninboundurl: WebAttribute<msdyn_liveworkstream_Select, { msdyn_telesigninboundurl: string | null }, {  }>;
  msdyn_twilioinboundurl: WebAttribute<msdyn_liveworkstream_Select, { msdyn_twilioinboundurl: string | null }, {  }>;
  msdyn_waitingtimethreshold: WebAttribute<msdyn_liveworkstream_Select, { msdyn_waitingtimethreshold: number | null }, {  }>;
  msdyn_workdistributionmode: WebAttribute<msdyn_liveworkstream_Select, { msdyn_workdistributionmode: msdyn_workdistributionmode | null }, { msdyn_workdistributionmode_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_liveworkstream_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_liveworkstream_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_liveworkstream_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_liveworkstream_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_liveworkstream_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<msdyn_liveworkstream_Select, { statecode: msdyn_liveworkstream_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_liveworkstream_Select, { statuscode: msdyn_liveworkstream_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_liveworkstream_Select, { timezoneruleversionnumber: number | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_liveworkstream_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_liveworkstream_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_liveworkstream_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_allowedpresences: msdyn_basepresencestatus;
  msdyn_apikey: string;
  msdyn_apikeyversionnumber: number;
  msdyn_assignworkitemafterdecline: number;
  msdyn_autocloseafterinactivity: number;
  msdyn_bot_queue_guid: XQW.Guid;
  msdyn_bot_rule: string;
  msdyn_bot_user_guid: XQW.Guid;
  msdyn_capacityformat: msdyn_capacityformat;
  msdyn_capacityrequired: number;
  msdyn_connectorsurl: string;
  msdyn_conversationmode: msdyn_liveworkstream_msdyn_conversationmode;
  msdyn_customerid: string;
  msdyn_direction: msdyn_msdyn_liveworkstream_msdyn_direction;
  msdyn_enableagentaffinity: boolean;
  msdyn_enableautomatedmessages: boolean;
  msdyn_enableselectingfrompushbasedworkstreams: boolean;
  msdyn_entityroutingconfigurationid_guid: XQW.Guid;
  msdyn_fallbacklanguage: string;
  msdyn_followupafterwaiting: number;
  msdyn_handlingtimethreshold: number;
  msdyn_isdefault: boolean;
  msdyn_lastvalidationon: Date;
  msdyn_lastvalidationstatus: string;
  msdyn_liveworkstreamid: XQW.Guid;
  msdyn_masterentityroutingconfigurationid_guid: XQW.Guid;
  msdyn_matchinglogic: msdyn_liveworkstream_msdyn_matchinglogic;
  msdyn_maxconcurrentconnection: number;
  msdyn_mode: msdyn_ocadminmode;
  msdyn_name: string;
  msdyn_notification: msdyn_notificationtypes;
  msdyn_notificationscenarioplaceholder: string;
  msdyn_notificationtemplate_consult: string;
  msdyn_notificationtemplate_incoming_auth: string;
  msdyn_notificationtemplate_incoming_unauth: string;
  msdyn_notificationtemplate_supervisorassign: string;
  msdyn_notificationtemplate_transfer: string;
  msdyn_outboundqueueid_guid: XQW.Guid;
  msdyn_recordidentificationrule: string;
  msdyn_recordidentificationvalidationrule: string;
  msdyn_routingcontractid_guid: XQW.Guid;
  msdyn_screenpoptimeout: number;
  msdyn_screenpoptimeout_optionSet: msdyn_screenpoptimeout;
  msdyn_sessionscenarioplaceholder: string;
  msdyn_sessiontemplate_default: string;
  msdyn_skillattachmentrulescount: number;
  msdyn_skillattachmentrulescount_date: Date;
  msdyn_skillattachmentrulescount_state: number;
  msdyn_smsprovider: msdyn_smsprovider;
  msdyn_streamsource: msdyn_streamsource;
  msdyn_telesigninboundurl: string;
  msdyn_twilioinboundurl: string;
  msdyn_waitingtimethreshold: number;
  msdyn_workdistributionmode: msdyn_workdistributionmode;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: msdyn_liveworkstream_statecode;
  statuscode: msdyn_liveworkstream_statuscode;
  timezoneruleversionnumber: number;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_liveworkstream_Expand {
  createdby: WebExpand<msdyn_liveworkstream_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_liveworkstream_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_liveworkstream_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_liveworkstream_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_bot_queue: WebExpand<msdyn_liveworkstream_Expand, Queue_Select, Queue_Filter, { msdyn_bot_queue: Queue_Result }>;
  msdyn_bot_user: WebExpand<msdyn_liveworkstream_Expand, SystemUser_Select, SystemUser_Filter, { msdyn_bot_user: SystemUser_Result }>;
  msdyn_entityroutingconfigurationId: WebExpand<msdyn_liveworkstream_Expand, msdyn_entityroutingconfiguration_Select, msdyn_entityroutingconfiguration_Filter, { msdyn_entityroutingconfigurationId: msdyn_entityroutingconfiguration_Result }>;
  msdyn_liveworkstream_AsyncOperations: WebExpand<msdyn_liveworkstream_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_liveworkstream_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_liveworkstream_BulkDeleteFailures: WebExpand<msdyn_liveworkstream_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_liveworkstream_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_liveworkstream_MailboxTrackingFolders: WebExpand<msdyn_liveworkstream_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_liveworkstream_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_liveworkstream_PrincipalObjectAttributeAccesses: WebExpand<msdyn_liveworkstream_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_liveworkstream_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_liveworkstream_ProcessSession: WebExpand<msdyn_liveworkstream_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_liveworkstream_ProcessSession: ProcessSession_Result[] }>;
  msdyn_liveworkstream_SyncErrors: WebExpand<msdyn_liveworkstream_Expand, SyncError_Select, SyncError_Filter, { msdyn_liveworkstream_SyncErrors: SyncError_Result[] }>;
  msdyn_liveworkstream_UserEntityInstanceDatas: WebExpand<msdyn_liveworkstream_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_liveworkstream_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_liveworkstream_msdyn_liveworkstreamcapacityprofile: WebExpand<msdyn_liveworkstream_Expand, msdyn_liveworkstreamcapacityprofile_Select, msdyn_liveworkstreamcapacityprofile_Filter, { msdyn_liveworkstream_msdyn_liveworkstreamcapacityprofile: msdyn_liveworkstreamcapacityprofile_Result[] }>;
  msdyn_liveworkstream_msdyn_routingconfiguration_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_routingconfiguration_Select, msdyn_routingconfiguration_Filter, { msdyn_liveworkstream_msdyn_routingconfiguration_liveworkstreamid: msdyn_routingconfiguration_Result[] }>;
  msdyn_liveworkstream_msdyn_rulesetdependencymapping_msdyn_referencedpolymorphicentityid: WebExpand<msdyn_liveworkstream_Expand, msdyn_rulesetdependencymapping_Select, msdyn_rulesetdependencymapping_Filter, { msdyn_liveworkstream_msdyn_rulesetdependencymapping_msdyn_referencedpolymorphicentityid: msdyn_rulesetdependencymapping_Result[] }>;
  msdyn_liveworkstream_ocruleitem: WebExpand<msdyn_liveworkstream_Expand, msdyn_ocruleitem_Select, msdyn_ocruleitem_Filter, { msdyn_liveworkstream_ocruleitem: msdyn_ocruleitem_Result[] }>;
  msdyn_liveworkstream_queueitem_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, QueueItem_Select, QueueItem_Filter, { msdyn_liveworkstream_queueitem_liveworkstreamid: QueueItem_Result[] }>;
  msdyn_liveworkstream_skillattachmentruleitem: WebExpand<msdyn_liveworkstream_Expand, msdyn_skillattachmentruleitem_Select, msdyn_skillattachmentruleitem_Filter, { msdyn_liveworkstream_skillattachmentruleitem: msdyn_skillattachmentruleitem_Result[] }>;
  msdyn_masterentityroutingconfigurationId: WebExpand<msdyn_liveworkstream_Expand, msdyn_masterentityroutingconfiguration_Select, msdyn_masterentityroutingconfiguration_Filter, { msdyn_masterentityroutingconfigurationId: msdyn_masterentityroutingconfiguration_Result }>;
  msdyn_msdyn_cannedmessage_liveworkstream: WebExpand<msdyn_liveworkstream_Expand, msdyn_cannedmessage_Select, msdyn_cannedmessage_Filter, { msdyn_msdyn_cannedmessage_liveworkstream: msdyn_cannedmessage_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_entityconfig: WebExpand<msdyn_liveworkstream_Expand, msdyn_entityconfig_Select, msdyn_entityconfig_Filter, { msdyn_msdyn_liveworkstream_msdyn_entityconfig: msdyn_entityconfig_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_livechatconfig_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_livechatconfig_Select, msdyn_livechatconfig_Filter, { msdyn_msdyn_liveworkstream_msdyn_livechatconfig_liveworkstreamid: msdyn_livechatconfig_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_liveconversation: WebExpand<msdyn_liveworkstream_Expand, msdyn_liveconversation_Select, msdyn_liveconversation_Filter, { msdyn_msdyn_liveworkstream_msdyn_liveconversation: msdyn_liveconversation_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_occustommessagingchannel_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_occustommessagingchannel_Select, msdyn_occustommessagingchannel_Filter, { msdyn_msdyn_liveworkstream_msdyn_occustommessagingchannel_liveworkstreamid: msdyn_occustommessagingchannel_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_ocfbpage: WebExpand<msdyn_liveworkstream_Expand, msdyn_ocfbpage_Select, msdyn_ocfbpage_Filter, { msdyn_msdyn_liveworkstream_msdyn_ocfbpage: msdyn_ocfbpage_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_oclinechannelconfig_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_oclinechannelconfig_Select, msdyn_oclinechannelconfig_Filter, { msdyn_msdyn_liveworkstream_msdyn_oclinechannelconfig_liveworkstreamid: msdyn_oclinechannelconfig_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_ocliveworkitem_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { msdyn_msdyn_liveworkstream_msdyn_ocliveworkitem_liveworkstreamid: msdyn_ocliveworkitem_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_ocliveworkstreamcontextvariable_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_ocliveworkstreamcontextvariable_Select, msdyn_ocliveworkstreamcontextvariable_Filter, { msdyn_msdyn_liveworkstream_msdyn_ocliveworkstreamcontextvariable_liveworkstreamid: msdyn_ocliveworkstreamcontextvariable_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_ocsmschannelsetting_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_ocsmschannelsetting_Select, msdyn_ocsmschannelsetting_Filter, { msdyn_msdyn_liveworkstream_msdyn_ocsmschannelsetting_liveworkstreamid: msdyn_ocsmschannelsetting_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_octeamschannelconfig_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_octeamschannelconfig_Select, msdyn_octeamschannelconfig_Filter, { msdyn_msdyn_liveworkstream_msdyn_octeamschannelconfig_liveworkstreamid: msdyn_octeamschannelconfig_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_octwitterhandle_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_octwitterhandle_Select, msdyn_octwitterhandle_Filter, { msdyn_msdyn_liveworkstream_msdyn_octwitterhandle_liveworkstreamid: msdyn_octwitterhandle_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_ocwechatchannelconfig_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_ocwechatchannelconfig_Select, msdyn_ocwechatchannelconfig_Filter, { msdyn_msdyn_liveworkstream_msdyn_ocwechatchannelconfig_liveworkstreamid: msdyn_ocwechatchannelconfig_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_ocwhatsappchannelnumber_liveworkstreamid: WebExpand<msdyn_liveworkstream_Expand, msdyn_ocwhatsappchannelnumber_Select, msdyn_ocwhatsappchannelnumber_Filter, { msdyn_msdyn_liveworkstream_msdyn_ocwhatsappchannelnumber_liveworkstreamid: msdyn_ocwhatsappchannelnumber_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_scenario: WebExpand<msdyn_liveworkstream_Expand, msdyn_scenario_Select, msdyn_scenario_Filter, { msdyn_msdyn_liveworkstream_msdyn_scenario: msdyn_scenario_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_smsnumber: WebExpand<msdyn_liveworkstream_Expand, msdyn_smsnumber_Select, msdyn_smsnumber_Filter, { msdyn_msdyn_liveworkstream_msdyn_smsnumber: msdyn_smsnumber_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_surveyquestion: WebExpand<msdyn_liveworkstream_Expand, msdyn_surveyquestion_Select, msdyn_surveyquestion_Filter, { msdyn_msdyn_liveworkstream_msdyn_surveyquestion: msdyn_surveyquestion_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_unifiedroutingrun_workstream: WebExpand<msdyn_liveworkstream_Expand, msdyn_unifiedroutingrun_Select, msdyn_unifiedroutingrun_Filter, { msdyn_msdyn_liveworkstream_msdyn_unifiedroutingrun_workstream: msdyn_unifiedroutingrun_Result[] }>;
  msdyn_msdyn_liveworkstream_msdyn_urnotificationtemplatemapping_workstream: WebExpand<msdyn_liveworkstream_Expand, msdyn_urnotificationtemplatemapping_Select, msdyn_urnotificationtemplatemapping_Filter, { msdyn_msdyn_liveworkstream_msdyn_urnotificationtemplatemapping_workstream: msdyn_urnotificationtemplatemapping_Result[] }>;
  msdyn_msdyn_liveworkstream_systemuser: WebExpand<msdyn_liveworkstream_Expand, SystemUser_Select, SystemUser_Filter, { msdyn_msdyn_liveworkstream_systemuser: SystemUser_Result[] }>;
  msdyn_msdyn_ocoutboundconfiguration_msdyn_liveworkstream: WebExpand<msdyn_liveworkstream_Expand, msdyn_ocoutboundconfiguration_Select, msdyn_ocoutboundconfiguration_Filter, { msdyn_msdyn_ocoutboundconfiguration_msdyn_liveworkstream: msdyn_ocoutboundconfiguration_Result[] }>;
  msdyn_ocoutboundmessage_ocliveworkstream: WebExpand<msdyn_liveworkstream_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { msdyn_ocoutboundmessage_ocliveworkstream: msdyn_ocoutboundmessage_Result[] }>;
  msdyn_outboundqueueid: WebExpand<msdyn_liveworkstream_Expand, Queue_Select, Queue_Filter, { msdyn_outboundqueueid: Queue_Result }>;
  msdyn_routingcontractid: WebExpand<msdyn_liveworkstream_Expand, msdyn_decisioncontract_Select, msdyn_decisioncontract_Filter, { msdyn_routingcontractid: msdyn_decisioncontract_Result }>;
  ownerid: WebExpand<msdyn_liveworkstream_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_liveworkstream_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_liveworkstream_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_liveworkstream_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
}
interface msdyn_liveworkstream_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_allowedpresences_formatted?: string;
  msdyn_bot_queue_formatted?: string;
  msdyn_bot_user_formatted?: string;
  msdyn_capacityformat_formatted?: string;
  msdyn_conversationmode_formatted?: string;
  msdyn_direction_formatted?: string;
  msdyn_entityroutingconfigurationid_formatted?: string;
  msdyn_lastvalidationon_formatted?: string;
  msdyn_masterentityroutingconfigurationid_formatted?: string;
  msdyn_matchinglogic_formatted?: string;
  msdyn_mode_formatted?: string;
  msdyn_notification_formatted?: string;
  msdyn_outboundqueueid_formatted?: string;
  msdyn_routingcontractid_formatted?: string;
  msdyn_screenpoptimeout_optionSet_formatted?: string;
  msdyn_skillattachmentrulescount_date_formatted?: string;
  msdyn_smsprovider_formatted?: string;
  msdyn_streamsource_formatted?: string;
  msdyn_workdistributionmode_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface msdyn_liveworkstream_Result extends msdyn_liveworkstream_Base, msdyn_liveworkstream_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_bot_queue_guid: string | null;
  msdyn_bot_user_guid: string | null;
  msdyn_entityroutingconfigurationid_guid: string | null;
  msdyn_masterentityroutingconfigurationid_guid: string | null;
  msdyn_outboundqueueid_guid: string | null;
  msdyn_routingcontractid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface msdyn_liveworkstream_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_bot_queue: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  msdyn_bot_user: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_entityroutingconfigurationId: WebMappingRetrieve<msdyn_entityroutingconfiguration_Select,msdyn_entityroutingconfiguration_Expand,msdyn_entityroutingconfiguration_Filter,msdyn_entityroutingconfiguration_Fixed,msdyn_entityroutingconfiguration_Result,msdyn_entityroutingconfiguration_FormattedResult>;
  msdyn_masterentityroutingconfigurationId: WebMappingRetrieve<msdyn_masterentityroutingconfiguration_Select,msdyn_masterentityroutingconfiguration_Expand,msdyn_masterentityroutingconfiguration_Filter,msdyn_masterentityroutingconfiguration_Fixed,msdyn_masterentityroutingconfiguration_Result,msdyn_masterentityroutingconfiguration_FormattedResult>;
  msdyn_outboundqueueid: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  msdyn_routingcontractid: WebMappingRetrieve<msdyn_decisioncontract_Select,msdyn_decisioncontract_Expand,msdyn_decisioncontract_Filter,msdyn_decisioncontract_Fixed,msdyn_decisioncontract_Result,msdyn_decisioncontract_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface msdyn_liveworkstream_RelatedMany {
  msdyn_liveworkstream_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_liveworkstream_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_liveworkstream_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_liveworkstream_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_liveworkstream_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_liveworkstream_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_liveworkstream_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  msdyn_liveworkstream_msdyn_liveworkstreamcapacityprofile: WebMappingRetrieve<msdyn_liveworkstreamcapacityprofile_Select,msdyn_liveworkstreamcapacityprofile_Expand,msdyn_liveworkstreamcapacityprofile_Filter,msdyn_liveworkstreamcapacityprofile_Fixed,msdyn_liveworkstreamcapacityprofile_Result,msdyn_liveworkstreamcapacityprofile_FormattedResult>;
  msdyn_liveworkstream_msdyn_routingconfiguration_liveworkstreamid: WebMappingRetrieve<msdyn_routingconfiguration_Select,msdyn_routingconfiguration_Expand,msdyn_routingconfiguration_Filter,msdyn_routingconfiguration_Fixed,msdyn_routingconfiguration_Result,msdyn_routingconfiguration_FormattedResult>;
  msdyn_liveworkstream_msdyn_rulesetdependencymapping_msdyn_referencedpolymorphicentityid: WebMappingRetrieve<msdyn_rulesetdependencymapping_Select,msdyn_rulesetdependencymapping_Expand,msdyn_rulesetdependencymapping_Filter,msdyn_rulesetdependencymapping_Fixed,msdyn_rulesetdependencymapping_Result,msdyn_rulesetdependencymapping_FormattedResult>;
  msdyn_liveworkstream_ocruleitem: WebMappingRetrieve<msdyn_ocruleitem_Select,msdyn_ocruleitem_Expand,msdyn_ocruleitem_Filter,msdyn_ocruleitem_Fixed,msdyn_ocruleitem_Result,msdyn_ocruleitem_FormattedResult>;
  msdyn_liveworkstream_queueitem_liveworkstreamid: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  msdyn_liveworkstream_skillattachmentruleitem: WebMappingRetrieve<msdyn_skillattachmentruleitem_Select,msdyn_skillattachmentruleitem_Expand,msdyn_skillattachmentruleitem_Filter,msdyn_skillattachmentruleitem_Fixed,msdyn_skillattachmentruleitem_Result,msdyn_skillattachmentruleitem_FormattedResult>;
  msdyn_msdyn_cannedmessage_liveworkstream: WebMappingRetrieve<msdyn_cannedmessage_Select,msdyn_cannedmessage_Expand,msdyn_cannedmessage_Filter,msdyn_cannedmessage_Fixed,msdyn_cannedmessage_Result,msdyn_cannedmessage_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_entityconfig: WebMappingRetrieve<msdyn_entityconfig_Select,msdyn_entityconfig_Expand,msdyn_entityconfig_Filter,msdyn_entityconfig_Fixed,msdyn_entityconfig_Result,msdyn_entityconfig_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_livechatconfig_liveworkstreamid: WebMappingRetrieve<msdyn_livechatconfig_Select,msdyn_livechatconfig_Expand,msdyn_livechatconfig_Filter,msdyn_livechatconfig_Fixed,msdyn_livechatconfig_Result,msdyn_livechatconfig_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_liveconversation: WebMappingRetrieve<msdyn_liveconversation_Select,msdyn_liveconversation_Expand,msdyn_liveconversation_Filter,msdyn_liveconversation_Fixed,msdyn_liveconversation_Result,msdyn_liveconversation_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_occustommessagingchannel_liveworkstreamid: WebMappingRetrieve<msdyn_occustommessagingchannel_Select,msdyn_occustommessagingchannel_Expand,msdyn_occustommessagingchannel_Filter,msdyn_occustommessagingchannel_Fixed,msdyn_occustommessagingchannel_Result,msdyn_occustommessagingchannel_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_ocfbpage: WebMappingRetrieve<msdyn_ocfbpage_Select,msdyn_ocfbpage_Expand,msdyn_ocfbpage_Filter,msdyn_ocfbpage_Fixed,msdyn_ocfbpage_Result,msdyn_ocfbpage_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_oclinechannelconfig_liveworkstreamid: WebMappingRetrieve<msdyn_oclinechannelconfig_Select,msdyn_oclinechannelconfig_Expand,msdyn_oclinechannelconfig_Filter,msdyn_oclinechannelconfig_Fixed,msdyn_oclinechannelconfig_Result,msdyn_oclinechannelconfig_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_ocliveworkitem_liveworkstreamid: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_ocliveworkstreamcontextvariable_liveworkstreamid: WebMappingRetrieve<msdyn_ocliveworkstreamcontextvariable_Select,msdyn_ocliveworkstreamcontextvariable_Expand,msdyn_ocliveworkstreamcontextvariable_Filter,msdyn_ocliveworkstreamcontextvariable_Fixed,msdyn_ocliveworkstreamcontextvariable_Result,msdyn_ocliveworkstreamcontextvariable_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_ocsmschannelsetting_liveworkstreamid: WebMappingRetrieve<msdyn_ocsmschannelsetting_Select,msdyn_ocsmschannelsetting_Expand,msdyn_ocsmschannelsetting_Filter,msdyn_ocsmschannelsetting_Fixed,msdyn_ocsmschannelsetting_Result,msdyn_ocsmschannelsetting_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_octeamschannelconfig_liveworkstreamid: WebMappingRetrieve<msdyn_octeamschannelconfig_Select,msdyn_octeamschannelconfig_Expand,msdyn_octeamschannelconfig_Filter,msdyn_octeamschannelconfig_Fixed,msdyn_octeamschannelconfig_Result,msdyn_octeamschannelconfig_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_octwitterhandle_liveworkstreamid: WebMappingRetrieve<msdyn_octwitterhandle_Select,msdyn_octwitterhandle_Expand,msdyn_octwitterhandle_Filter,msdyn_octwitterhandle_Fixed,msdyn_octwitterhandle_Result,msdyn_octwitterhandle_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_ocwechatchannelconfig_liveworkstreamid: WebMappingRetrieve<msdyn_ocwechatchannelconfig_Select,msdyn_ocwechatchannelconfig_Expand,msdyn_ocwechatchannelconfig_Filter,msdyn_ocwechatchannelconfig_Fixed,msdyn_ocwechatchannelconfig_Result,msdyn_ocwechatchannelconfig_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_ocwhatsappchannelnumber_liveworkstreamid: WebMappingRetrieve<msdyn_ocwhatsappchannelnumber_Select,msdyn_ocwhatsappchannelnumber_Expand,msdyn_ocwhatsappchannelnumber_Filter,msdyn_ocwhatsappchannelnumber_Fixed,msdyn_ocwhatsappchannelnumber_Result,msdyn_ocwhatsappchannelnumber_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_scenario: WebMappingRetrieve<msdyn_scenario_Select,msdyn_scenario_Expand,msdyn_scenario_Filter,msdyn_scenario_Fixed,msdyn_scenario_Result,msdyn_scenario_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_smsnumber: WebMappingRetrieve<msdyn_smsnumber_Select,msdyn_smsnumber_Expand,msdyn_smsnumber_Filter,msdyn_smsnumber_Fixed,msdyn_smsnumber_Result,msdyn_smsnumber_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_surveyquestion: WebMappingRetrieve<msdyn_surveyquestion_Select,msdyn_surveyquestion_Expand,msdyn_surveyquestion_Filter,msdyn_surveyquestion_Fixed,msdyn_surveyquestion_Result,msdyn_surveyquestion_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_unifiedroutingrun_workstream: WebMappingRetrieve<msdyn_unifiedroutingrun_Select,msdyn_unifiedroutingrun_Expand,msdyn_unifiedroutingrun_Filter,msdyn_unifiedroutingrun_Fixed,msdyn_unifiedroutingrun_Result,msdyn_unifiedroutingrun_FormattedResult>;
  msdyn_msdyn_liveworkstream_msdyn_urnotificationtemplatemapping_workstream: WebMappingRetrieve<msdyn_urnotificationtemplatemapping_Select,msdyn_urnotificationtemplatemapping_Expand,msdyn_urnotificationtemplatemapping_Filter,msdyn_urnotificationtemplatemapping_Fixed,msdyn_urnotificationtemplatemapping_Result,msdyn_urnotificationtemplatemapping_FormattedResult>;
  msdyn_msdyn_liveworkstream_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_msdyn_ocoutboundconfiguration_msdyn_liveworkstream: WebMappingRetrieve<msdyn_ocoutboundconfiguration_Select,msdyn_ocoutboundconfiguration_Expand,msdyn_ocoutboundconfiguration_Filter,msdyn_ocoutboundconfiguration_Fixed,msdyn_ocoutboundconfiguration_Result,msdyn_ocoutboundconfiguration_FormattedResult>;
  msdyn_ocoutboundmessage_ocliveworkstream: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_liveworkstreams: WebMappingRetrieve<msdyn_liveworkstream_Select,msdyn_liveworkstream_Expand,msdyn_liveworkstream_Filter,msdyn_liveworkstream_Fixed,msdyn_liveworkstream_Result,msdyn_liveworkstream_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_liveworkstreams: WebMappingRelated<msdyn_liveworkstream_RelatedOne,msdyn_liveworkstream_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_liveworkstreams: WebMappingCUDA<msdyn_liveworkstream_Create,msdyn_liveworkstream_Update,msdyn_liveworkstream_Select>;
}
