interface msdyn_transactioncategory_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_billingtype?: msdyn_billingtype | null;
  msdyn_name?: string | null;
  msdyn_transactioncategoryid?: string | null;
  overriddencreatedon?: Date | null;
  statecode?: msdyn_transactioncategory_statecode | null;
  statuscode?: msdyn_transactioncategory_statuscode | null;
  timezoneruleversionnumber?: number | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_transactioncategory_Relationships {
  msdyn_DefaultUnit?: UoM_Result | null;
  msdyn_UnitGroup?: UoMSchedule_Result | null;
  msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory?: BookableResourceCategory_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_actual_TransactionCategory?: msdyn_actual_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_estimateline_TransactionCategory?: msdyn_estimateline_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_expensecatego?: msdyn_expensecategory_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_fact_TransactionCategory?: msdyn_fact_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_invoicelinetransaction_TransactionCategory?: msdyn_invoicelinetransaction_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_journalline_TransactionCategory?: msdyn_journalline_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_opportunitylinetransaction_TransactionCategory?: msdyn_opportunitylinetransaction_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_opportunitylinetransactioncategory_TransactionCategory?: msdyn_opportunitylinetransactioncategory_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory?: msdyn_orderlinetransaction_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_orderlinetransactioncategory_TransactionCategory?: msdyn_orderlinetransactioncategory_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_projectapproval_TransactionCategory?: msdyn_projectapproval_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_projecttask_transactioncategory?: msdyn_projecttask_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_projecttransactioncategory_TransactionCategory?: msdyn_projecttransactioncategory_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_quotelineanalyticsbreakdown_TransactionCategory?: msdyn_quotelineanalyticsbreakdown_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_quotelinetransaction_TransactionCategory?: msdyn_quotelinetransaction_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_quotelinetransactioncategory_TransactionCategory?: msdyn_quotelinetransactioncategory_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_resourcecategorymarkuppricelevel_transactioncategory?: msdyn_resourcecategorymarkuppricelevel_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_resourcecategorypricelevel_transactioncategory?: msdyn_resourcecategorypricelevel_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_timeentry_transactioncategory?: msdyn_timeentry_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategoryclassification_transactioncategory?: msdyn_transactioncategoryclassification_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategoryhierarchyelement_ChildCategory?: msdyn_transactioncategoryhierarchyelement_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategoryhierarchyelement_ParentCategory?: msdyn_transactioncategoryhierarchyelement_Result[] | null;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategorypricelevel_TransactionCategory?: msdyn_transactioncategorypricelevel_Result[] | null;
  msdyn_msdyn_transactioncategory_product_TransactionCategory?: Product_Result[] | null;
  msdyn_transactioncategory_Annotations?: Annotation_Result[] | null;
  msdyn_transactioncategory_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_transactioncategory_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_transactioncategory_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_transactioncategory_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_transactioncategory_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_transactioncategory_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_transactioncategory_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_transactioncategory_SyncErrors?: SyncError_Result[] | null;
  msdyn_transactioncategory_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
}
interface msdyn_transactioncategory extends msdyn_transactioncategory_Base, msdyn_transactioncategory_Relationships {
  msdyn_DefaultUnit_bind$uoms?: string | null;
  msdyn_UnitGroup_bind$uomschedules?: string | null;
}
interface msdyn_transactioncategory_Create extends msdyn_transactioncategory {
}
interface msdyn_transactioncategory_Update extends msdyn_transactioncategory {
}
interface msdyn_transactioncategory_Select {
  createdby_guid: WebAttribute<msdyn_transactioncategory_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_transactioncategory_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_transactioncategory_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<msdyn_transactioncategory_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_transactioncategory_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_transactioncategory_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_transactioncategory_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_billingtype: WebAttribute<msdyn_transactioncategory_Select, { msdyn_billingtype: msdyn_billingtype | null }, { msdyn_billingtype_formatted?: string }>;
  msdyn_defaultunit_guid: WebAttribute<msdyn_transactioncategory_Select, { msdyn_defaultunit_guid: string | null }, { msdyn_defaultunit_formatted?: string }>;
  msdyn_name: WebAttribute<msdyn_transactioncategory_Select, { msdyn_name: string | null }, {  }>;
  msdyn_transactioncategoryid: WebAttribute<msdyn_transactioncategory_Select, { msdyn_transactioncategoryid: string | null }, {  }>;
  msdyn_unitgroup_guid: WebAttribute<msdyn_transactioncategory_Select, { msdyn_unitgroup_guid: string | null }, { msdyn_unitgroup_formatted?: string }>;
  organizationid_guid: WebAttribute<msdyn_transactioncategory_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_transactioncategory_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  statecode: WebAttribute<msdyn_transactioncategory_Select, { statecode: msdyn_transactioncategory_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_transactioncategory_Select, { statuscode: msdyn_transactioncategory_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_transactioncategory_Select, { timezoneruleversionnumber: number | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_transactioncategory_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_transactioncategory_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_transactioncategory_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_billingtype: msdyn_billingtype;
  msdyn_defaultunit_guid: XQW.Guid;
  msdyn_name: string;
  msdyn_transactioncategoryid: XQW.Guid;
  msdyn_unitgroup_guid: XQW.Guid;
  organizationid_guid: XQW.Guid;
  overriddencreatedon: Date;
  statecode: msdyn_transactioncategory_statecode;
  statuscode: msdyn_transactioncategory_statuscode;
  timezoneruleversionnumber: number;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_transactioncategory_Expand {
  createdby: WebExpand<msdyn_transactioncategory_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_transactioncategory_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_transactioncategory_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_transactioncategory_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_DefaultUnit: WebExpand<msdyn_transactioncategory_Expand, UoM_Select, UoM_Filter, { msdyn_DefaultUnit: UoM_Result }>;
  msdyn_UnitGroup: WebExpand<msdyn_transactioncategory_Expand, UoMSchedule_Select, UoMSchedule_Filter, { msdyn_UnitGroup: UoMSchedule_Result }>;
  msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, BookableResourceCategory_Select, BookableResourceCategory_Filter, { msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory: BookableResourceCategory_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_actual_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_actual_Select, msdyn_actual_Filter, { msdyn_msdyn_transactioncategory_msdyn_actual_TransactionCategory: msdyn_actual_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_estimateline_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_estimateline_Select, msdyn_estimateline_Filter, { msdyn_msdyn_transactioncategory_msdyn_estimateline_TransactionCategory: msdyn_estimateline_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_expensecatego: WebExpand<msdyn_transactioncategory_Expand, msdyn_expensecategory_Select, msdyn_expensecategory_Filter, { msdyn_msdyn_transactioncategory_msdyn_expensecatego: msdyn_expensecategory_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_fact_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_fact_Select, msdyn_fact_Filter, { msdyn_msdyn_transactioncategory_msdyn_fact_TransactionCategory: msdyn_fact_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_invoicelinetransaction_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_invoicelinetransaction_Select, msdyn_invoicelinetransaction_Filter, { msdyn_msdyn_transactioncategory_msdyn_invoicelinetransaction_TransactionCategory: msdyn_invoicelinetransaction_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_journalline_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_journalline_Select, msdyn_journalline_Filter, { msdyn_msdyn_transactioncategory_msdyn_journalline_TransactionCategory: msdyn_journalline_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_opportunitylinetransaction_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_opportunitylinetransaction_Select, msdyn_opportunitylinetransaction_Filter, { msdyn_msdyn_transactioncategory_msdyn_opportunitylinetransaction_TransactionCategory: msdyn_opportunitylinetransaction_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_opportunitylinetransactioncategory_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_opportunitylinetransactioncategory_Select, msdyn_opportunitylinetransactioncategory_Filter, { msdyn_msdyn_transactioncategory_msdyn_opportunitylinetransactioncategory_TransactionCategory: msdyn_opportunitylinetransactioncategory_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_orderlinetransaction_Select, msdyn_orderlinetransaction_Filter, { msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory: msdyn_orderlinetransaction_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_orderlinetransactioncategory_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_orderlinetransactioncategory_Select, msdyn_orderlinetransactioncategory_Filter, { msdyn_msdyn_transactioncategory_msdyn_orderlinetransactioncategory_TransactionCategory: msdyn_orderlinetransactioncategory_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_projectapproval_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_projectapproval_Select, msdyn_projectapproval_Filter, { msdyn_msdyn_transactioncategory_msdyn_projectapproval_TransactionCategory: msdyn_projectapproval_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_projecttask_transactioncategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_projecttask_Select, msdyn_projecttask_Filter, { msdyn_msdyn_transactioncategory_msdyn_projecttask_transactioncategory: msdyn_projecttask_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_projecttransactioncategory_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_projecttransactioncategory_Select, msdyn_projecttransactioncategory_Filter, { msdyn_msdyn_transactioncategory_msdyn_projecttransactioncategory_TransactionCategory: msdyn_projecttransactioncategory_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_quotelineanalyticsbreakdown_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_quotelineanalyticsbreakdown_Select, msdyn_quotelineanalyticsbreakdown_Filter, { msdyn_msdyn_transactioncategory_msdyn_quotelineanalyticsbreakdown_TransactionCategory: msdyn_quotelineanalyticsbreakdown_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_quotelinetransaction_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_quotelinetransaction_Select, msdyn_quotelinetransaction_Filter, { msdyn_msdyn_transactioncategory_msdyn_quotelinetransaction_TransactionCategory: msdyn_quotelinetransaction_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_quotelinetransactioncategory_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_quotelinetransactioncategory_Select, msdyn_quotelinetransactioncategory_Filter, { msdyn_msdyn_transactioncategory_msdyn_quotelinetransactioncategory_TransactionCategory: msdyn_quotelinetransactioncategory_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_resourcecategorymarkuppricelevel_transactioncategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_resourcecategorymarkuppricelevel_Select, msdyn_resourcecategorymarkuppricelevel_Filter, { msdyn_msdyn_transactioncategory_msdyn_resourcecategorymarkuppricelevel_transactioncategory: msdyn_resourcecategorymarkuppricelevel_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_resourcecategorypricelevel_transactioncategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_resourcecategorypricelevel_Select, msdyn_resourcecategorypricelevel_Filter, { msdyn_msdyn_transactioncategory_msdyn_resourcecategorypricelevel_transactioncategory: msdyn_resourcecategorypricelevel_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_timeentry_transactioncategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_timeentry_Select, msdyn_timeentry_Filter, { msdyn_msdyn_transactioncategory_msdyn_timeentry_transactioncategory: msdyn_timeentry_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategoryclassification_transactioncategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_transactioncategoryclassification_Select, msdyn_transactioncategoryclassification_Filter, { msdyn_msdyn_transactioncategory_msdyn_transactioncategoryclassification_transactioncategory: msdyn_transactioncategoryclassification_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategoryhierarchyelement_ChildCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_transactioncategoryhierarchyelement_Select, msdyn_transactioncategoryhierarchyelement_Filter, { msdyn_msdyn_transactioncategory_msdyn_transactioncategoryhierarchyelement_ChildCategory: msdyn_transactioncategoryhierarchyelement_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategoryhierarchyelement_ParentCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_transactioncategoryhierarchyelement_Select, msdyn_transactioncategoryhierarchyelement_Filter, { msdyn_msdyn_transactioncategory_msdyn_transactioncategoryhierarchyelement_ParentCategory: msdyn_transactioncategoryhierarchyelement_Result[] }>;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategorypricelevel_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, msdyn_transactioncategorypricelevel_Select, msdyn_transactioncategorypricelevel_Filter, { msdyn_msdyn_transactioncategory_msdyn_transactioncategorypricelevel_TransactionCategory: msdyn_transactioncategorypricelevel_Result[] }>;
  msdyn_msdyn_transactioncategory_product_TransactionCategory: WebExpand<msdyn_transactioncategory_Expand, Product_Select, Product_Filter, { msdyn_msdyn_transactioncategory_product_TransactionCategory: Product_Result[] }>;
  msdyn_transactioncategory_Annotations: WebExpand<msdyn_transactioncategory_Expand, Annotation_Select, Annotation_Filter, { msdyn_transactioncategory_Annotations: Annotation_Result[] }>;
  msdyn_transactioncategory_AsyncOperations: WebExpand<msdyn_transactioncategory_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_transactioncategory_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_transactioncategory_BulkDeleteFailures: WebExpand<msdyn_transactioncategory_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_transactioncategory_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_transactioncategory_DuplicateBaseRecord: WebExpand<msdyn_transactioncategory_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_transactioncategory_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_transactioncategory_DuplicateMatchingRecord: WebExpand<msdyn_transactioncategory_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_transactioncategory_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_transactioncategory_MailboxTrackingFolders: WebExpand<msdyn_transactioncategory_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_transactioncategory_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_transactioncategory_PrincipalObjectAttributeAccesses: WebExpand<msdyn_transactioncategory_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_transactioncategory_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_transactioncategory_ProcessSession: WebExpand<msdyn_transactioncategory_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_transactioncategory_ProcessSession: ProcessSession_Result[] }>;
  msdyn_transactioncategory_SyncErrors: WebExpand<msdyn_transactioncategory_Expand, SyncError_Select, SyncError_Filter, { msdyn_transactioncategory_SyncErrors: SyncError_Result[] }>;
  msdyn_transactioncategory_UserEntityInstanceDatas: WebExpand<msdyn_transactioncategory_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_transactioncategory_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  organizationid: WebExpand<msdyn_transactioncategory_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
}
interface msdyn_transactioncategory_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_billingtype_formatted?: string;
  msdyn_defaultunit_formatted?: string;
  msdyn_unitgroup_formatted?: string;
  organizationid_formatted?: string;
  overriddencreatedon_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface msdyn_transactioncategory_Result extends msdyn_transactioncategory_Base, msdyn_transactioncategory_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_defaultunit_guid: string | null;
  msdyn_unitgroup_guid: string | null;
  organizationid_guid: string | null;
}
interface msdyn_transactioncategory_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_DefaultUnit: WebMappingRetrieve<UoM_Select,UoM_Expand,UoM_Filter,UoM_Fixed,UoM_Result,UoM_FormattedResult>;
  msdyn_UnitGroup: WebMappingRetrieve<UoMSchedule_Select,UoMSchedule_Expand,UoMSchedule_Filter,UoMSchedule_Fixed,UoMSchedule_Result,UoMSchedule_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
}
interface msdyn_transactioncategory_RelatedMany {
  msdyn_msdyn_transactioncategory_bookableresourcecategory_TransactionCategory: WebMappingRetrieve<BookableResourceCategory_Select,BookableResourceCategory_Expand,BookableResourceCategory_Filter,BookableResourceCategory_Fixed,BookableResourceCategory_Result,BookableResourceCategory_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_actual_TransactionCategory: WebMappingRetrieve<msdyn_actual_Select,msdyn_actual_Expand,msdyn_actual_Filter,msdyn_actual_Fixed,msdyn_actual_Result,msdyn_actual_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_estimateline_TransactionCategory: WebMappingRetrieve<msdyn_estimateline_Select,msdyn_estimateline_Expand,msdyn_estimateline_Filter,msdyn_estimateline_Fixed,msdyn_estimateline_Result,msdyn_estimateline_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_expensecatego: WebMappingRetrieve<msdyn_expensecategory_Select,msdyn_expensecategory_Expand,msdyn_expensecategory_Filter,msdyn_expensecategory_Fixed,msdyn_expensecategory_Result,msdyn_expensecategory_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_fact_TransactionCategory: WebMappingRetrieve<msdyn_fact_Select,msdyn_fact_Expand,msdyn_fact_Filter,msdyn_fact_Fixed,msdyn_fact_Result,msdyn_fact_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_invoicelinetransaction_TransactionCategory: WebMappingRetrieve<msdyn_invoicelinetransaction_Select,msdyn_invoicelinetransaction_Expand,msdyn_invoicelinetransaction_Filter,msdyn_invoicelinetransaction_Fixed,msdyn_invoicelinetransaction_Result,msdyn_invoicelinetransaction_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_journalline_TransactionCategory: WebMappingRetrieve<msdyn_journalline_Select,msdyn_journalline_Expand,msdyn_journalline_Filter,msdyn_journalline_Fixed,msdyn_journalline_Result,msdyn_journalline_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_opportunitylinetransaction_TransactionCategory: WebMappingRetrieve<msdyn_opportunitylinetransaction_Select,msdyn_opportunitylinetransaction_Expand,msdyn_opportunitylinetransaction_Filter,msdyn_opportunitylinetransaction_Fixed,msdyn_opportunitylinetransaction_Result,msdyn_opportunitylinetransaction_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_opportunitylinetransactioncategory_TransactionCategory: WebMappingRetrieve<msdyn_opportunitylinetransactioncategory_Select,msdyn_opportunitylinetransactioncategory_Expand,msdyn_opportunitylinetransactioncategory_Filter,msdyn_opportunitylinetransactioncategory_Fixed,msdyn_opportunitylinetransactioncategory_Result,msdyn_opportunitylinetransactioncategory_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_orderlinetransaction_TransactionCategory: WebMappingRetrieve<msdyn_orderlinetransaction_Select,msdyn_orderlinetransaction_Expand,msdyn_orderlinetransaction_Filter,msdyn_orderlinetransaction_Fixed,msdyn_orderlinetransaction_Result,msdyn_orderlinetransaction_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_orderlinetransactioncategory_TransactionCategory: WebMappingRetrieve<msdyn_orderlinetransactioncategory_Select,msdyn_orderlinetransactioncategory_Expand,msdyn_orderlinetransactioncategory_Filter,msdyn_orderlinetransactioncategory_Fixed,msdyn_orderlinetransactioncategory_Result,msdyn_orderlinetransactioncategory_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_projectapproval_TransactionCategory: WebMappingRetrieve<msdyn_projectapproval_Select,msdyn_projectapproval_Expand,msdyn_projectapproval_Filter,msdyn_projectapproval_Fixed,msdyn_projectapproval_Result,msdyn_projectapproval_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_projecttask_transactioncategory: WebMappingRetrieve<msdyn_projecttask_Select,msdyn_projecttask_Expand,msdyn_projecttask_Filter,msdyn_projecttask_Fixed,msdyn_projecttask_Result,msdyn_projecttask_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_projecttransactioncategory_TransactionCategory: WebMappingRetrieve<msdyn_projecttransactioncategory_Select,msdyn_projecttransactioncategory_Expand,msdyn_projecttransactioncategory_Filter,msdyn_projecttransactioncategory_Fixed,msdyn_projecttransactioncategory_Result,msdyn_projecttransactioncategory_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_quotelineanalyticsbreakdown_TransactionCategory: WebMappingRetrieve<msdyn_quotelineanalyticsbreakdown_Select,msdyn_quotelineanalyticsbreakdown_Expand,msdyn_quotelineanalyticsbreakdown_Filter,msdyn_quotelineanalyticsbreakdown_Fixed,msdyn_quotelineanalyticsbreakdown_Result,msdyn_quotelineanalyticsbreakdown_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_quotelinetransaction_TransactionCategory: WebMappingRetrieve<msdyn_quotelinetransaction_Select,msdyn_quotelinetransaction_Expand,msdyn_quotelinetransaction_Filter,msdyn_quotelinetransaction_Fixed,msdyn_quotelinetransaction_Result,msdyn_quotelinetransaction_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_quotelinetransactioncategory_TransactionCategory: WebMappingRetrieve<msdyn_quotelinetransactioncategory_Select,msdyn_quotelinetransactioncategory_Expand,msdyn_quotelinetransactioncategory_Filter,msdyn_quotelinetransactioncategory_Fixed,msdyn_quotelinetransactioncategory_Result,msdyn_quotelinetransactioncategory_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_resourcecategorymarkuppricelevel_transactioncategory: WebMappingRetrieve<msdyn_resourcecategorymarkuppricelevel_Select,msdyn_resourcecategorymarkuppricelevel_Expand,msdyn_resourcecategorymarkuppricelevel_Filter,msdyn_resourcecategorymarkuppricelevel_Fixed,msdyn_resourcecategorymarkuppricelevel_Result,msdyn_resourcecategorymarkuppricelevel_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_resourcecategorypricelevel_transactioncategory: WebMappingRetrieve<msdyn_resourcecategorypricelevel_Select,msdyn_resourcecategorypricelevel_Expand,msdyn_resourcecategorypricelevel_Filter,msdyn_resourcecategorypricelevel_Fixed,msdyn_resourcecategorypricelevel_Result,msdyn_resourcecategorypricelevel_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_timeentry_transactioncategory: WebMappingRetrieve<msdyn_timeentry_Select,msdyn_timeentry_Expand,msdyn_timeentry_Filter,msdyn_timeentry_Fixed,msdyn_timeentry_Result,msdyn_timeentry_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategoryclassification_transactioncategory: WebMappingRetrieve<msdyn_transactioncategoryclassification_Select,msdyn_transactioncategoryclassification_Expand,msdyn_transactioncategoryclassification_Filter,msdyn_transactioncategoryclassification_Fixed,msdyn_transactioncategoryclassification_Result,msdyn_transactioncategoryclassification_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategoryhierarchyelement_ChildCategory: WebMappingRetrieve<msdyn_transactioncategoryhierarchyelement_Select,msdyn_transactioncategoryhierarchyelement_Expand,msdyn_transactioncategoryhierarchyelement_Filter,msdyn_transactioncategoryhierarchyelement_Fixed,msdyn_transactioncategoryhierarchyelement_Result,msdyn_transactioncategoryhierarchyelement_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategoryhierarchyelement_ParentCategory: WebMappingRetrieve<msdyn_transactioncategoryhierarchyelement_Select,msdyn_transactioncategoryhierarchyelement_Expand,msdyn_transactioncategoryhierarchyelement_Filter,msdyn_transactioncategoryhierarchyelement_Fixed,msdyn_transactioncategoryhierarchyelement_Result,msdyn_transactioncategoryhierarchyelement_FormattedResult>;
  msdyn_msdyn_transactioncategory_msdyn_transactioncategorypricelevel_TransactionCategory: WebMappingRetrieve<msdyn_transactioncategorypricelevel_Select,msdyn_transactioncategorypricelevel_Expand,msdyn_transactioncategorypricelevel_Filter,msdyn_transactioncategorypricelevel_Fixed,msdyn_transactioncategorypricelevel_Result,msdyn_transactioncategorypricelevel_FormattedResult>;
  msdyn_msdyn_transactioncategory_product_TransactionCategory: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  msdyn_transactioncategory_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  msdyn_transactioncategory_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_transactioncategory_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_transactioncategory_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_transactioncategory_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_transactioncategory_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_transactioncategory_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_transactioncategory_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_transactioncategory_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_transactioncategory_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_transactioncategories: WebMappingRetrieve<msdyn_transactioncategory_Select,msdyn_transactioncategory_Expand,msdyn_transactioncategory_Filter,msdyn_transactioncategory_Fixed,msdyn_transactioncategory_Result,msdyn_transactioncategory_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_transactioncategories: WebMappingRelated<msdyn_transactioncategory_RelatedOne,msdyn_transactioncategory_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_transactioncategories: WebMappingCUDA<msdyn_transactioncategory_Create,msdyn_transactioncategory_Update,msdyn_transactioncategory_Select>;
}
