interface msdyn_quotebookingsetup_Base extends WebEntity {
  createdon?: Date | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_Internalflags?: string | null;
  msdyn_autogeneratebooking?: boolean | null;
  msdyn_autogenerateworkorder?: boolean | null;
  msdyn_description?: string | null;
  msdyn_estimatedcost?: number | null;
  msdyn_estimatedcost_base?: number | null;
  msdyn_estimatedduration?: number | null;
  msdyn_estimatedmargin?: number | null;
  msdyn_estimatedmarginperwo?: number | null;
  msdyn_estimatedproductcost?: number | null;
  msdyn_estimatedproductcost_base?: number | null;
  msdyn_estimatedproductrevenue?: number | null;
  msdyn_estimatedproductrevenue_base?: number | null;
  msdyn_estimatedrevenue?: number | null;
  msdyn_estimatedrevenue_base?: number | null;
  msdyn_estimatedrevenueperwo?: number | null;
  msdyn_estimatedrevenueperwo_base?: number | null;
  msdyn_estimatedservicecost?: number | null;
  msdyn_estimatedservicecost_base?: number | null;
  msdyn_estimatedservicerevenue?: number | null;
  msdyn_estimatedservicerevenue_base?: number | null;
  msdyn_generateworkorderdaysinadvance?: number | null;
  msdyn_latitude?: number | null;
  msdyn_longitude?: number | null;
  msdyn_margin?: number | null;
  msdyn_name?: string | null;
  msdyn_numberofwo?: number | null;
  msdyn_postbookingflexibility?: number | null;
  msdyn_postponegenerationuntil?: Date | null;
  msdyn_prebookingflexibility?: number | null;
  msdyn_preferredstarttime?: Date | null;
  msdyn_quotebookingsetupid?: string | null;
  msdyn_quotedetailid?: string | null;
  msdyn_recurrencesettings?: string | null;
  msdyn_revision?: number | null;
  msdyn_timewindowend?: Date | null;
  msdyn_timewindowstart?: Date | null;
  msdyn_worklocation?: msdyn_worklocation | null;
  msdyn_workordersummary?: string | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  stageid?: string | null;
  statecode?: msdyn_quotebookingsetup_statecode | null;
  statuscode?: msdyn_quotebookingsetup_statuscode | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface msdyn_quotebookingsetup_Relationships {
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingincident_QuoteBookingSetup?: msdyn_quotebookingincident_Result[] | null;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingproduct_QuoteBookingSetup?: msdyn_quotebookingproduct_Result[] | null;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservice_QuoteBookingSetup?: msdyn_quotebookingservice_Result[] | null;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservicetask_QuoteBookingSetup?: msdyn_quotebookingservicetask_Result[] | null;
  msdyn_quotebookingsetup_AsyncOperations?: AsyncOperation_Result[] | null;
  msdyn_quotebookingsetup_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  msdyn_quotebookingsetup_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  msdyn_quotebookingsetup_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  msdyn_quotebookingsetup_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  msdyn_quotebookingsetup_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  msdyn_quotebookingsetup_ProcessSession?: ProcessSession_Result[] | null;
  msdyn_quotebookingsetup_SyncErrors?: SyncError_Result[] | null;
  msdyn_quotebookingsetup_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
}
interface msdyn_quotebookingsetup extends msdyn_quotebookingsetup_Base, msdyn_quotebookingsetup_Relationships {
  msdyn_preferredresource_bind$bookableresources?: string | null;
  msdyn_priority_bind$msdyn_priorities?: string | null;
  msdyn_quote_bind$quotes?: string | null;
  msdyn_quotedetail_msdyn_quotebookingset_bind$quotedetails?: string | null;
  msdyn_workordertype_bind$msdyn_workordertypes?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  stageid_bind$processstages?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface msdyn_quotebookingsetup_Create extends msdyn_quotebookingsetup {
}
interface msdyn_quotebookingsetup_Update extends msdyn_quotebookingsetup {
}
interface msdyn_quotebookingsetup_Select {
  createdby_guid: WebAttribute<msdyn_quotebookingsetup_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<msdyn_quotebookingsetup_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<msdyn_quotebookingsetup_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  exchangerate: WebAttribute<msdyn_quotebookingsetup_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<msdyn_quotebookingsetup_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<msdyn_quotebookingsetup_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<msdyn_quotebookingsetup_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<msdyn_quotebookingsetup_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_Internalflags: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_Internalflags: string | null }, {  }>;
  msdyn_autogeneratebooking: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_autogeneratebooking: boolean | null }, {  }>;
  msdyn_autogenerateworkorder: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_autogenerateworkorder: boolean | null }, {  }>;
  msdyn_description: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_description: string | null }, {  }>;
  msdyn_estimatedcost: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedcost_base: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedduration: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedduration: number | null }, {  }>;
  msdyn_estimatedmargin: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedmargin: number | null }, {  }>;
  msdyn_estimatedmarginperwo: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedmarginperwo: number | null }, {  }>;
  msdyn_estimatedproductcost: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedproductcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedproductcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedproductcost_base: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedproductcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedproductcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedproductrevenue: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedproductrevenue: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedproductrevenue_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedproductrevenue_base: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedproductrevenue_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedproductrevenue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedrevenue: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedrevenue: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedrevenue_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedrevenue_base: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedrevenue_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedrevenue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedrevenueperwo: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedrevenueperwo: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedrevenueperwo_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedrevenueperwo_base: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedrevenueperwo_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedrevenueperwo_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedservicecost: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedservicecost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedservicecost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedservicecost_base: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedservicecost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedservicecost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedservicerevenue: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedservicerevenue: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedservicerevenue_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedservicerevenue_base: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_estimatedservicerevenue_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedservicerevenue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_generateworkorderdaysinadvance: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_generateworkorderdaysinadvance: number | null }, {  }>;
  msdyn_latitude: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_latitude: number | null }, {  }>;
  msdyn_longitude: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_longitude: number | null }, {  }>;
  msdyn_margin: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_margin: number | null }, {  }>;
  msdyn_name: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_name: string | null }, {  }>;
  msdyn_numberofwo: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_numberofwo: number | null }, {  }>;
  msdyn_postbookingflexibility: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_postbookingflexibility: number | null }, {  }>;
  msdyn_postponegenerationuntil: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_postponegenerationuntil: Date | null }, { msdyn_postponegenerationuntil_formatted?: string }>;
  msdyn_prebookingflexibility: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_prebookingflexibility: number | null }, {  }>;
  msdyn_preferredresource_guid: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_preferredresource_guid: string | null }, { msdyn_preferredresource_formatted?: string }>;
  msdyn_preferredstarttime: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_preferredstarttime: Date | null }, { msdyn_preferredstarttime_formatted?: string }>;
  msdyn_priority_guid: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_priority_guid: string | null }, { msdyn_priority_formatted?: string }>;
  msdyn_quote_guid: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_quote_guid: string | null }, { msdyn_quote_formatted?: string }>;
  msdyn_quotebookingsetupid: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_quotebookingsetupid: string | null }, {  }>;
  msdyn_quotedetail_msdyn_quotebookingset_guid: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_quotedetail_msdyn_quotebookingset_guid: string | null }, { msdyn_quotedetail_msdyn_quotebookingset_formatted?: string }>;
  msdyn_quotedetailid: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_quotedetailid: string | null }, {  }>;
  msdyn_recurrencesettings: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_recurrencesettings: string | null }, {  }>;
  msdyn_revision: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_revision: number | null }, {  }>;
  msdyn_timewindowend: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_timewindowend: Date | null }, { msdyn_timewindowend_formatted?: string }>;
  msdyn_timewindowstart: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_timewindowstart: Date | null }, { msdyn_timewindowstart_formatted?: string }>;
  msdyn_worklocation: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_worklocation: msdyn_worklocation | null }, { msdyn_worklocation_formatted?: string }>;
  msdyn_workordersummary: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_workordersummary: string | null }, {  }>;
  msdyn_workordertype_guid: WebAttribute<msdyn_quotebookingsetup_Select, { msdyn_workordertype_guid: string | null }, { msdyn_workordertype_formatted?: string }>;
  overriddencreatedon: WebAttribute<msdyn_quotebookingsetup_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<msdyn_quotebookingsetup_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<msdyn_quotebookingsetup_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<msdyn_quotebookingsetup_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<msdyn_quotebookingsetup_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  processid: WebAttribute<msdyn_quotebookingsetup_Select, { processid: string | null }, {  }>;
  stageid: WebAttribute<msdyn_quotebookingsetup_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<msdyn_quotebookingsetup_Select, { statecode: msdyn_quotebookingsetup_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<msdyn_quotebookingsetup_Select, { statuscode: msdyn_quotebookingsetup_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<msdyn_quotebookingsetup_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<msdyn_quotebookingsetup_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<msdyn_quotebookingsetup_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<msdyn_quotebookingsetup_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<msdyn_quotebookingsetup_Select, { versionnumber: number | null }, {  }>;
}
interface msdyn_quotebookingsetup_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_Internalflags: string;
  msdyn_autogeneratebooking: boolean;
  msdyn_autogenerateworkorder: boolean;
  msdyn_description: string;
  msdyn_estimatedcost: number;
  msdyn_estimatedcost_base: number;
  msdyn_estimatedduration: number;
  msdyn_estimatedmargin: any;
  msdyn_estimatedmarginperwo: any;
  msdyn_estimatedproductcost: number;
  msdyn_estimatedproductcost_base: number;
  msdyn_estimatedproductrevenue: number;
  msdyn_estimatedproductrevenue_base: number;
  msdyn_estimatedrevenue: number;
  msdyn_estimatedrevenue_base: number;
  msdyn_estimatedrevenueperwo: number;
  msdyn_estimatedrevenueperwo_base: number;
  msdyn_estimatedservicecost: number;
  msdyn_estimatedservicecost_base: number;
  msdyn_estimatedservicerevenue: number;
  msdyn_estimatedservicerevenue_base: number;
  msdyn_generateworkorderdaysinadvance: number;
  msdyn_latitude: number;
  msdyn_longitude: number;
  msdyn_margin: any;
  msdyn_name: string;
  msdyn_numberofwo: number;
  msdyn_postbookingflexibility: number;
  msdyn_postponegenerationuntil: Date;
  msdyn_prebookingflexibility: number;
  msdyn_preferredresource_guid: XQW.Guid;
  msdyn_preferredstarttime: Date;
  msdyn_priority_guid: XQW.Guid;
  msdyn_quote_guid: XQW.Guid;
  msdyn_quotebookingsetupid: XQW.Guid;
  msdyn_quotedetail_msdyn_quotebookingset_guid: XQW.Guid;
  msdyn_quotedetailid: string;
  msdyn_recurrencesettings: string;
  msdyn_revision: number;
  msdyn_timewindowend: Date;
  msdyn_timewindowstart: Date;
  msdyn_worklocation: msdyn_worklocation;
  msdyn_workordersummary: string;
  msdyn_workordertype_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  processid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: msdyn_quotebookingsetup_statecode;
  statuscode: msdyn_quotebookingsetup_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface msdyn_quotebookingsetup_Expand {
  createdby: WebExpand<msdyn_quotebookingsetup_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<msdyn_quotebookingsetup_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<msdyn_quotebookingsetup_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<msdyn_quotebookingsetup_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingincident_QuoteBookingSetup: WebExpand<msdyn_quotebookingsetup_Expand, msdyn_quotebookingincident_Select, msdyn_quotebookingincident_Filter, { msdyn_msdyn_quotebookingsetup_msdyn_quotebookingincident_QuoteBookingSetup: msdyn_quotebookingincident_Result[] }>;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingproduct_QuoteBookingSetup: WebExpand<msdyn_quotebookingsetup_Expand, msdyn_quotebookingproduct_Select, msdyn_quotebookingproduct_Filter, { msdyn_msdyn_quotebookingsetup_msdyn_quotebookingproduct_QuoteBookingSetup: msdyn_quotebookingproduct_Result[] }>;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservice_QuoteBookingSetup: WebExpand<msdyn_quotebookingsetup_Expand, msdyn_quotebookingservice_Select, msdyn_quotebookingservice_Filter, { msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservice_QuoteBookingSetup: msdyn_quotebookingservice_Result[] }>;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservicetask_QuoteBookingSetup: WebExpand<msdyn_quotebookingsetup_Expand, msdyn_quotebookingservicetask_Select, msdyn_quotebookingservicetask_Filter, { msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservicetask_QuoteBookingSetup: msdyn_quotebookingservicetask_Result[] }>;
  msdyn_preferredresource: WebExpand<msdyn_quotebookingsetup_Expand, BookableResource_Select, BookableResource_Filter, { msdyn_preferredresource: BookableResource_Result }>;
  msdyn_priority: WebExpand<msdyn_quotebookingsetup_Expand, msdyn_priority_Select, msdyn_priority_Filter, { msdyn_priority: msdyn_priority_Result }>;
  msdyn_quote: WebExpand<msdyn_quotebookingsetup_Expand, Quote_Select, Quote_Filter, { msdyn_quote: Quote_Result }>;
  msdyn_quotebookingsetup_AsyncOperations: WebExpand<msdyn_quotebookingsetup_Expand, AsyncOperation_Select, AsyncOperation_Filter, { msdyn_quotebookingsetup_AsyncOperations: AsyncOperation_Result[] }>;
  msdyn_quotebookingsetup_BulkDeleteFailures: WebExpand<msdyn_quotebookingsetup_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { msdyn_quotebookingsetup_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  msdyn_quotebookingsetup_DuplicateBaseRecord: WebExpand<msdyn_quotebookingsetup_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_quotebookingsetup_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  msdyn_quotebookingsetup_DuplicateMatchingRecord: WebExpand<msdyn_quotebookingsetup_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { msdyn_quotebookingsetup_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  msdyn_quotebookingsetup_MailboxTrackingFolders: WebExpand<msdyn_quotebookingsetup_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { msdyn_quotebookingsetup_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  msdyn_quotebookingsetup_PrincipalObjectAttributeAccesses: WebExpand<msdyn_quotebookingsetup_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { msdyn_quotebookingsetup_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  msdyn_quotebookingsetup_ProcessSession: WebExpand<msdyn_quotebookingsetup_Expand, ProcessSession_Select, ProcessSession_Filter, { msdyn_quotebookingsetup_ProcessSession: ProcessSession_Result[] }>;
  msdyn_quotebookingsetup_SyncErrors: WebExpand<msdyn_quotebookingsetup_Expand, SyncError_Select, SyncError_Filter, { msdyn_quotebookingsetup_SyncErrors: SyncError_Result[] }>;
  msdyn_quotebookingsetup_UserEntityInstanceDatas: WebExpand<msdyn_quotebookingsetup_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { msdyn_quotebookingsetup_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  msdyn_quotedetail_msdyn_quotebookingset: WebExpand<msdyn_quotebookingsetup_Expand, QuoteDetail_Select, QuoteDetail_Filter, { msdyn_quotedetail_msdyn_quotebookingset: QuoteDetail_Result }>;
  msdyn_workordertype: WebExpand<msdyn_quotebookingsetup_Expand, msdyn_workordertype_Select, msdyn_workordertype_Filter, { msdyn_workordertype: msdyn_workordertype_Result }>;
  ownerid: WebExpand<msdyn_quotebookingsetup_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<msdyn_quotebookingsetup_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<msdyn_quotebookingsetup_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<msdyn_quotebookingsetup_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  stageid: WebExpand<msdyn_quotebookingsetup_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid: ProcessStage_Result }>;
  transactioncurrencyid: WebExpand<msdyn_quotebookingsetup_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface msdyn_quotebookingsetup_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_estimatedcost_base_formatted?: string;
  msdyn_estimatedcost_formatted?: string;
  msdyn_estimatedproductcost_base_formatted?: string;
  msdyn_estimatedproductcost_formatted?: string;
  msdyn_estimatedproductrevenue_base_formatted?: string;
  msdyn_estimatedproductrevenue_formatted?: string;
  msdyn_estimatedrevenue_base_formatted?: string;
  msdyn_estimatedrevenue_formatted?: string;
  msdyn_estimatedrevenueperwo_base_formatted?: string;
  msdyn_estimatedrevenueperwo_formatted?: string;
  msdyn_estimatedservicecost_base_formatted?: string;
  msdyn_estimatedservicecost_formatted?: string;
  msdyn_estimatedservicerevenue_base_formatted?: string;
  msdyn_estimatedservicerevenue_formatted?: string;
  msdyn_postponegenerationuntil_formatted?: string;
  msdyn_preferredresource_formatted?: string;
  msdyn_preferredstarttime_formatted?: string;
  msdyn_priority_formatted?: string;
  msdyn_quote_formatted?: string;
  msdyn_quotedetail_msdyn_quotebookingset_formatted?: string;
  msdyn_timewindowend_formatted?: string;
  msdyn_timewindowstart_formatted?: string;
  msdyn_worklocation_formatted?: string;
  msdyn_workordertype_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface msdyn_quotebookingsetup_Result extends msdyn_quotebookingsetup_Base, msdyn_quotebookingsetup_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_preferredresource_guid: string | null;
  msdyn_priority_guid: string | null;
  msdyn_quote_guid: string | null;
  msdyn_quotedetail_msdyn_quotebookingset_guid: string | null;
  msdyn_workordertype_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface msdyn_quotebookingsetup_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_preferredresource: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  msdyn_priority: WebMappingRetrieve<msdyn_priority_Select,msdyn_priority_Expand,msdyn_priority_Filter,msdyn_priority_Fixed,msdyn_priority_Result,msdyn_priority_FormattedResult>;
  msdyn_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  msdyn_quotedetail_msdyn_quotebookingset: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  msdyn_workordertype: WebMappingRetrieve<msdyn_workordertype_Select,msdyn_workordertype_Expand,msdyn_workordertype_Filter,msdyn_workordertype_Fixed,msdyn_workordertype_Result,msdyn_workordertype_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  stageid: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface msdyn_quotebookingsetup_RelatedMany {
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingincident_QuoteBookingSetup: WebMappingRetrieve<msdyn_quotebookingincident_Select,msdyn_quotebookingincident_Expand,msdyn_quotebookingincident_Filter,msdyn_quotebookingincident_Fixed,msdyn_quotebookingincident_Result,msdyn_quotebookingincident_FormattedResult>;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingproduct_QuoteBookingSetup: WebMappingRetrieve<msdyn_quotebookingproduct_Select,msdyn_quotebookingproduct_Expand,msdyn_quotebookingproduct_Filter,msdyn_quotebookingproduct_Fixed,msdyn_quotebookingproduct_Result,msdyn_quotebookingproduct_FormattedResult>;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservice_QuoteBookingSetup: WebMappingRetrieve<msdyn_quotebookingservice_Select,msdyn_quotebookingservice_Expand,msdyn_quotebookingservice_Filter,msdyn_quotebookingservice_Fixed,msdyn_quotebookingservice_Result,msdyn_quotebookingservice_FormattedResult>;
  msdyn_msdyn_quotebookingsetup_msdyn_quotebookingservicetask_QuoteBookingSetup: WebMappingRetrieve<msdyn_quotebookingservicetask_Select,msdyn_quotebookingservicetask_Expand,msdyn_quotebookingservicetask_Filter,msdyn_quotebookingservicetask_Fixed,msdyn_quotebookingservicetask_Result,msdyn_quotebookingservicetask_FormattedResult>;
  msdyn_quotebookingsetup_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  msdyn_quotebookingsetup_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  msdyn_quotebookingsetup_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_quotebookingsetup_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  msdyn_quotebookingsetup_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  msdyn_quotebookingsetup_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  msdyn_quotebookingsetup_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  msdyn_quotebookingsetup_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_quotebookingsetup_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  msdyn_quotebookingsetups: WebMappingRetrieve<msdyn_quotebookingsetup_Select,msdyn_quotebookingsetup_Expand,msdyn_quotebookingsetup_Filter,msdyn_quotebookingsetup_Fixed,msdyn_quotebookingsetup_Result,msdyn_quotebookingsetup_FormattedResult>;
}
interface WebEntitiesRelated {
  msdyn_quotebookingsetups: WebMappingRelated<msdyn_quotebookingsetup_RelatedOne,msdyn_quotebookingsetup_RelatedMany>;
}
interface WebEntitiesCUDA {
  msdyn_quotebookingsetups: WebMappingCUDA<msdyn_quotebookingsetup_Create,msdyn_quotebookingsetup_Update,msdyn_quotebookingsetup_Select>;
}
