interface PriceLevel_Base extends WebEntity {
  begindate?: Date | null;
  createdon?: Date | null;
  description?: string | null;
  enddate?: Date | null;
  exchangerate?: number | null;
  freighttermscode?: pricelevel_freighttermscode | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyn_breakhoursbillable?: boolean | null;
  msdyn_entity?: msdyn_pricelistentity | null;
  msdyn_module?: msdyn_module | null;
  name?: string | null;
  overriddencreatedon?: Date | null;
  paymentmethodcode?: pricelevel_paymentmethodcode | null;
  pricelevelid?: string | null;
  shippingmethodcode?: pricelevel_shippingmethodcode | null;
  statecode?: pricelevel_statecode | null;
  statuscode?: pricelevel_statuscode | null;
  timezoneruleversionnumber?: number | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface PriceLevel_Relationships {
  PriceLevel_AsyncOperations?: AsyncOperation_Result[] | null;
  PriceLevel_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  PriceLevel_ProcessSessions?: ProcessSession_Result[] | null;
  PriceLevel_SyncErrors?: SyncError_Result[] | null;
  PriceList_Campaigns?: Campaign_Result[] | null;
  msdyn_CopiedFromPriceLevel?: PriceLevel_Result | null;
  msdyn_TimeUnit?: UoM_Result | null;
  msdyn_organizationalunit_pricelevel?: msdyn_organizationalunit_Result[] | null;
  msdyn_pricelevel_entitlement_PriceListToApply?: Entitlement_Result[] | null;
  msdyn_pricelevel_msdyn_accountpricelist_PriceList?: msdyn_accountpricelist_Result[] | null;
  msdyn_pricelevel_msdyn_actual_PriceList?: msdyn_actual_Result[] | null;
  msdyn_pricelevel_msdyn_agreement_PriceList?: msdyn_agreement_Result[] | null;
  msdyn_pricelevel_msdyn_agreementbookingproduct_PriceList?: msdyn_agreementbookingproduct_Result[] | null;
  msdyn_pricelevel_msdyn_agreementbookingservice_PriceList?: msdyn_agreementbookingservice_Result[] | null;
  msdyn_pricelevel_msdyn_agreementinvoiceproduct_PriceList?: msdyn_agreementinvoiceproduct_Result[] | null;
  msdyn_pricelevel_msdyn_contactpricelist_PriceList?: msdyn_contactpricelist_Result[] | null;
  msdyn_pricelevel_msdyn_estimateline_PriceList?: msdyn_estimateline_Result[] | null;
  msdyn_pricelevel_msdyn_fieldservicepricelistitem_PriceList?: msdyn_fieldservicepricelistitem_Result[] | null;
  msdyn_pricelevel_msdyn_invoicelinetransaction_PriceList?: msdyn_invoicelinetransaction_Result[] | null;
  msdyn_pricelevel_msdyn_journalline_PriceList?: msdyn_journalline_Result[] | null;
  msdyn_pricelevel_msdyn_opportunitylinetransaction_PriceList?: msdyn_opportunitylinetransaction_Result[] | null;
  msdyn_pricelevel_msdyn_opportunitypricelist_PriceList?: msdyn_opportunitypricelist_Result[] | null;
  msdyn_pricelevel_msdyn_orderlinetransaction_PriceList?: msdyn_orderlinetransaction_Result[] | null;
  msdyn_pricelevel_msdyn_orderpricelist_PriceList?: msdyn_orderpricelist_Result[] | null;
  msdyn_pricelevel_msdyn_projectparameterpricelist_PriceList?: msdyn_projectparameterpricelist_Result[] | null;
  msdyn_pricelevel_msdyn_projectpricelist_PriceList?: msdyn_projectpricelist_Result[] | null;
  msdyn_pricelevel_msdyn_quotebookingproduct_PriceList?: msdyn_quotebookingproduct_Result[] | null;
  msdyn_pricelevel_msdyn_quotebookingservice_PriceList?: msdyn_quotebookingservice_Result[] | null;
  msdyn_pricelevel_msdyn_quotelinetransaction_PriceList?: msdyn_quotelinetransaction_Result[] | null;
  msdyn_pricelevel_msdyn_quotepricelist_PriceList?: msdyn_quotepricelist_Result[] | null;
  msdyn_pricelevel_msdyn_resourcecategorymarkuppricelevel_PriceList?: msdyn_resourcecategorymarkuppricelevel_Result[] | null;
  msdyn_pricelevel_msdyn_resourcecategorypricelevel_PriceList?: msdyn_resourcecategorypricelevel_Result[] | null;
  msdyn_pricelevel_msdyn_rma_PriceList?: msdyn_rma_Result[] | null;
  msdyn_pricelevel_msdyn_rmaproduct_PriceList?: msdyn_rmaproduct_Result[] | null;
  msdyn_pricelevel_msdyn_transactioncategorypricelevel_PriceList?: msdyn_transactioncategorypricelevel_Result[] | null;
  msdyn_pricelevel_msdyn_workorder_PriceList?: msdyn_workorder_Result[] | null;
  msdyn_pricelevel_msdyn_workorderproduct_PriceList?: msdyn_workorderproduct_Result[] | null;
  msdyn_pricelevel_msdyn_workorderservice_PriceList?: msdyn_workorderservice_Result[] | null;
  msdyn_pricelevel_msdyn_workordertype_PriceList?: msdyn_workordertype_Result[] | null;
  msdyn_pricelevel_opportunityproduct_PriceList?: OpportunityProduct_Result[] | null;
  msdyn_pricelevel_pricelevel_CopiedFromPriceLevel?: PriceLevel_Result[] | null;
  msdyn_pricelevel_quotedetail_PriceList?: QuoteDetail_Result[] | null;
  price_level_accounts?: Account_Result[] | null;
  price_level_contacts?: Contact_Result[] | null;
  price_level_invoices?: Invoice_Result[] | null;
  price_level_opportunties?: Opportunity_Result[] | null;
  price_level_orders?: SalesOrder_Result[] | null;
  price_level_product_price_levels?: ProductPriceLevel_Result[] | null;
  price_level_products?: Product_Result[] | null;
  price_level_quotes?: Quote_Result[] | null;
  pricelevel_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  pricelevel_connections1?: Connection_Result[] | null;
  pricelevel_connections2?: Connection_Result[] | null;
  pricelevel_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  userentityinstancedata_pricelevel?: UserEntityInstanceData_Result[] | null;
}
interface PriceLevel extends PriceLevel_Base, PriceLevel_Relationships {
  msdyn_CopiedFromPriceLevel_bind$pricelevels?: string | null;
  msdyn_TimeUnit_bind$uoms?: string | null;
}
interface PriceLevel_Create extends PriceLevel {
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface PriceLevel_Update extends PriceLevel {
}
interface PriceLevel_Select {
  begindate: WebAttribute<PriceLevel_Select, { begindate: Date | null }, { begindate_formatted?: string }>;
  createdby_guid: WebAttribute<PriceLevel_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<PriceLevel_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<PriceLevel_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<PriceLevel_Select, { description: string | null }, {  }>;
  enddate: WebAttribute<PriceLevel_Select, { enddate: Date | null }, { enddate_formatted?: string }>;
  exchangerate: WebAttribute<PriceLevel_Select, { exchangerate: number | null }, {  }>;
  freighttermscode: WebAttribute<PriceLevel_Select, { freighttermscode: pricelevel_freighttermscode | null }, { freighttermscode_formatted?: string }>;
  importsequencenumber: WebAttribute<PriceLevel_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<PriceLevel_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<PriceLevel_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<PriceLevel_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_breakhoursbillable: WebAttribute<PriceLevel_Select, { msdyn_breakhoursbillable: boolean | null }, {  }>;
  msdyn_copiedfrompricelevel_guid: WebAttribute<PriceLevel_Select, { msdyn_copiedfrompricelevel_guid: string | null }, { msdyn_copiedfrompricelevel_formatted?: string }>;
  msdyn_entity: WebAttribute<PriceLevel_Select, { msdyn_entity: msdyn_pricelistentity | null }, { msdyn_entity_formatted?: string }>;
  msdyn_module: WebAttribute<PriceLevel_Select, { msdyn_module: msdyn_module | null }, { msdyn_module_formatted?: string }>;
  msdyn_timeunit_guid: WebAttribute<PriceLevel_Select, { msdyn_timeunit_guid: string | null }, { msdyn_timeunit_formatted?: string }>;
  name: WebAttribute<PriceLevel_Select, { name: string | null }, {  }>;
  organizationid_guid: WebAttribute<PriceLevel_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  overriddencreatedon: WebAttribute<PriceLevel_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  paymentmethodcode: WebAttribute<PriceLevel_Select, { paymentmethodcode: pricelevel_paymentmethodcode | null }, { paymentmethodcode_formatted?: string }>;
  pricelevelid: WebAttribute<PriceLevel_Select, { pricelevelid: string | null }, {  }>;
  shippingmethodcode: WebAttribute<PriceLevel_Select, { shippingmethodcode: pricelevel_shippingmethodcode | null }, { shippingmethodcode_formatted?: string }>;
  statecode: WebAttribute<PriceLevel_Select, { statecode: pricelevel_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<PriceLevel_Select, { statuscode: pricelevel_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<PriceLevel_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<PriceLevel_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<PriceLevel_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<PriceLevel_Select, { versionnumber: number | null }, {  }>;
}
interface PriceLevel_Filter {
  begindate: Date;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  enddate: Date;
  exchangerate: any;
  freighttermscode: pricelevel_freighttermscode;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_breakhoursbillable: boolean;
  msdyn_copiedfrompricelevel_guid: XQW.Guid;
  msdyn_entity: msdyn_pricelistentity;
  msdyn_module: msdyn_module;
  msdyn_timeunit_guid: XQW.Guid;
  name: string;
  organizationid_guid: XQW.Guid;
  overriddencreatedon: Date;
  paymentmethodcode: pricelevel_paymentmethodcode;
  pricelevelid: XQW.Guid;
  shippingmethodcode: pricelevel_shippingmethodcode;
  statecode: pricelevel_statecode;
  statuscode: pricelevel_statuscode;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface PriceLevel_Expand {
  PriceLevel_AsyncOperations: WebExpand<PriceLevel_Expand, AsyncOperation_Select, AsyncOperation_Filter, { PriceLevel_AsyncOperations: AsyncOperation_Result[] }>;
  PriceLevel_BulkDeleteFailures: WebExpand<PriceLevel_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { PriceLevel_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  PriceLevel_ProcessSessions: WebExpand<PriceLevel_Expand, ProcessSession_Select, ProcessSession_Filter, { PriceLevel_ProcessSessions: ProcessSession_Result[] }>;
  PriceLevel_SyncErrors: WebExpand<PriceLevel_Expand, SyncError_Select, SyncError_Filter, { PriceLevel_SyncErrors: SyncError_Result[] }>;
  PriceList_Campaigns: WebExpand<PriceLevel_Expand, Campaign_Select, Campaign_Filter, { PriceList_Campaigns: Campaign_Result[] }>;
  createdby: WebExpand<PriceLevel_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<PriceLevel_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<PriceLevel_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<PriceLevel_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_CopiedFromPriceLevel: WebExpand<PriceLevel_Expand, PriceLevel_Select, PriceLevel_Filter, { msdyn_CopiedFromPriceLevel: PriceLevel_Result }>;
  msdyn_TimeUnit: WebExpand<PriceLevel_Expand, UoM_Select, UoM_Filter, { msdyn_TimeUnit: UoM_Result }>;
  msdyn_organizationalunit_pricelevel: WebExpand<PriceLevel_Expand, msdyn_organizationalunit_Select, msdyn_organizationalunit_Filter, { msdyn_organizationalunit_pricelevel: msdyn_organizationalunit_Result[] }>;
  msdyn_pricelevel_entitlement_PriceListToApply: WebExpand<PriceLevel_Expand, Entitlement_Select, Entitlement_Filter, { msdyn_pricelevel_entitlement_PriceListToApply: Entitlement_Result[] }>;
  msdyn_pricelevel_msdyn_accountpricelist_PriceList: WebExpand<PriceLevel_Expand, msdyn_accountpricelist_Select, msdyn_accountpricelist_Filter, { msdyn_pricelevel_msdyn_accountpricelist_PriceList: msdyn_accountpricelist_Result[] }>;
  msdyn_pricelevel_msdyn_actual_PriceList: WebExpand<PriceLevel_Expand, msdyn_actual_Select, msdyn_actual_Filter, { msdyn_pricelevel_msdyn_actual_PriceList: msdyn_actual_Result[] }>;
  msdyn_pricelevel_msdyn_agreement_PriceList: WebExpand<PriceLevel_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { msdyn_pricelevel_msdyn_agreement_PriceList: msdyn_agreement_Result[] }>;
  msdyn_pricelevel_msdyn_agreementbookingproduct_PriceList: WebExpand<PriceLevel_Expand, msdyn_agreementbookingproduct_Select, msdyn_agreementbookingproduct_Filter, { msdyn_pricelevel_msdyn_agreementbookingproduct_PriceList: msdyn_agreementbookingproduct_Result[] }>;
  msdyn_pricelevel_msdyn_agreementbookingservice_PriceList: WebExpand<PriceLevel_Expand, msdyn_agreementbookingservice_Select, msdyn_agreementbookingservice_Filter, { msdyn_pricelevel_msdyn_agreementbookingservice_PriceList: msdyn_agreementbookingservice_Result[] }>;
  msdyn_pricelevel_msdyn_agreementinvoiceproduct_PriceList: WebExpand<PriceLevel_Expand, msdyn_agreementinvoiceproduct_Select, msdyn_agreementinvoiceproduct_Filter, { msdyn_pricelevel_msdyn_agreementinvoiceproduct_PriceList: msdyn_agreementinvoiceproduct_Result[] }>;
  msdyn_pricelevel_msdyn_contactpricelist_PriceList: WebExpand<PriceLevel_Expand, msdyn_contactpricelist_Select, msdyn_contactpricelist_Filter, { msdyn_pricelevel_msdyn_contactpricelist_PriceList: msdyn_contactpricelist_Result[] }>;
  msdyn_pricelevel_msdyn_estimateline_PriceList: WebExpand<PriceLevel_Expand, msdyn_estimateline_Select, msdyn_estimateline_Filter, { msdyn_pricelevel_msdyn_estimateline_PriceList: msdyn_estimateline_Result[] }>;
  msdyn_pricelevel_msdyn_fieldservicepricelistitem_PriceList: WebExpand<PriceLevel_Expand, msdyn_fieldservicepricelistitem_Select, msdyn_fieldservicepricelistitem_Filter, { msdyn_pricelevel_msdyn_fieldservicepricelistitem_PriceList: msdyn_fieldservicepricelistitem_Result[] }>;
  msdyn_pricelevel_msdyn_invoicelinetransaction_PriceList: WebExpand<PriceLevel_Expand, msdyn_invoicelinetransaction_Select, msdyn_invoicelinetransaction_Filter, { msdyn_pricelevel_msdyn_invoicelinetransaction_PriceList: msdyn_invoicelinetransaction_Result[] }>;
  msdyn_pricelevel_msdyn_journalline_PriceList: WebExpand<PriceLevel_Expand, msdyn_journalline_Select, msdyn_journalline_Filter, { msdyn_pricelevel_msdyn_journalline_PriceList: msdyn_journalline_Result[] }>;
  msdyn_pricelevel_msdyn_opportunitylinetransaction_PriceList: WebExpand<PriceLevel_Expand, msdyn_opportunitylinetransaction_Select, msdyn_opportunitylinetransaction_Filter, { msdyn_pricelevel_msdyn_opportunitylinetransaction_PriceList: msdyn_opportunitylinetransaction_Result[] }>;
  msdyn_pricelevel_msdyn_opportunitypricelist_PriceList: WebExpand<PriceLevel_Expand, msdyn_opportunitypricelist_Select, msdyn_opportunitypricelist_Filter, { msdyn_pricelevel_msdyn_opportunitypricelist_PriceList: msdyn_opportunitypricelist_Result[] }>;
  msdyn_pricelevel_msdyn_orderlinetransaction_PriceList: WebExpand<PriceLevel_Expand, msdyn_orderlinetransaction_Select, msdyn_orderlinetransaction_Filter, { msdyn_pricelevel_msdyn_orderlinetransaction_PriceList: msdyn_orderlinetransaction_Result[] }>;
  msdyn_pricelevel_msdyn_orderpricelist_PriceList: WebExpand<PriceLevel_Expand, msdyn_orderpricelist_Select, msdyn_orderpricelist_Filter, { msdyn_pricelevel_msdyn_orderpricelist_PriceList: msdyn_orderpricelist_Result[] }>;
  msdyn_pricelevel_msdyn_projectparameterpricelist_PriceList: WebExpand<PriceLevel_Expand, msdyn_projectparameterpricelist_Select, msdyn_projectparameterpricelist_Filter, { msdyn_pricelevel_msdyn_projectparameterpricelist_PriceList: msdyn_projectparameterpricelist_Result[] }>;
  msdyn_pricelevel_msdyn_projectpricelist_PriceList: WebExpand<PriceLevel_Expand, msdyn_projectpricelist_Select, msdyn_projectpricelist_Filter, { msdyn_pricelevel_msdyn_projectpricelist_PriceList: msdyn_projectpricelist_Result[] }>;
  msdyn_pricelevel_msdyn_quotebookingproduct_PriceList: WebExpand<PriceLevel_Expand, msdyn_quotebookingproduct_Select, msdyn_quotebookingproduct_Filter, { msdyn_pricelevel_msdyn_quotebookingproduct_PriceList: msdyn_quotebookingproduct_Result[] }>;
  msdyn_pricelevel_msdyn_quotebookingservice_PriceList: WebExpand<PriceLevel_Expand, msdyn_quotebookingservice_Select, msdyn_quotebookingservice_Filter, { msdyn_pricelevel_msdyn_quotebookingservice_PriceList: msdyn_quotebookingservice_Result[] }>;
  msdyn_pricelevel_msdyn_quotelinetransaction_PriceList: WebExpand<PriceLevel_Expand, msdyn_quotelinetransaction_Select, msdyn_quotelinetransaction_Filter, { msdyn_pricelevel_msdyn_quotelinetransaction_PriceList: msdyn_quotelinetransaction_Result[] }>;
  msdyn_pricelevel_msdyn_quotepricelist_PriceList: WebExpand<PriceLevel_Expand, msdyn_quotepricelist_Select, msdyn_quotepricelist_Filter, { msdyn_pricelevel_msdyn_quotepricelist_PriceList: msdyn_quotepricelist_Result[] }>;
  msdyn_pricelevel_msdyn_resourcecategorymarkuppricelevel_PriceList: WebExpand<PriceLevel_Expand, msdyn_resourcecategorymarkuppricelevel_Select, msdyn_resourcecategorymarkuppricelevel_Filter, { msdyn_pricelevel_msdyn_resourcecategorymarkuppricelevel_PriceList: msdyn_resourcecategorymarkuppricelevel_Result[] }>;
  msdyn_pricelevel_msdyn_resourcecategorypricelevel_PriceList: WebExpand<PriceLevel_Expand, msdyn_resourcecategorypricelevel_Select, msdyn_resourcecategorypricelevel_Filter, { msdyn_pricelevel_msdyn_resourcecategorypricelevel_PriceList: msdyn_resourcecategorypricelevel_Result[] }>;
  msdyn_pricelevel_msdyn_rma_PriceList: WebExpand<PriceLevel_Expand, msdyn_rma_Select, msdyn_rma_Filter, { msdyn_pricelevel_msdyn_rma_PriceList: msdyn_rma_Result[] }>;
  msdyn_pricelevel_msdyn_rmaproduct_PriceList: WebExpand<PriceLevel_Expand, msdyn_rmaproduct_Select, msdyn_rmaproduct_Filter, { msdyn_pricelevel_msdyn_rmaproduct_PriceList: msdyn_rmaproduct_Result[] }>;
  msdyn_pricelevel_msdyn_transactioncategorypricelevel_PriceList: WebExpand<PriceLevel_Expand, msdyn_transactioncategorypricelevel_Select, msdyn_transactioncategorypricelevel_Filter, { msdyn_pricelevel_msdyn_transactioncategorypricelevel_PriceList: msdyn_transactioncategorypricelevel_Result[] }>;
  msdyn_pricelevel_msdyn_workorder_PriceList: WebExpand<PriceLevel_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { msdyn_pricelevel_msdyn_workorder_PriceList: msdyn_workorder_Result[] }>;
  msdyn_pricelevel_msdyn_workorderproduct_PriceList: WebExpand<PriceLevel_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { msdyn_pricelevel_msdyn_workorderproduct_PriceList: msdyn_workorderproduct_Result[] }>;
  msdyn_pricelevel_msdyn_workorderservice_PriceList: WebExpand<PriceLevel_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { msdyn_pricelevel_msdyn_workorderservice_PriceList: msdyn_workorderservice_Result[] }>;
  msdyn_pricelevel_msdyn_workordertype_PriceList: WebExpand<PriceLevel_Expand, msdyn_workordertype_Select, msdyn_workordertype_Filter, { msdyn_pricelevel_msdyn_workordertype_PriceList: msdyn_workordertype_Result[] }>;
  msdyn_pricelevel_opportunityproduct_PriceList: WebExpand<PriceLevel_Expand, OpportunityProduct_Select, OpportunityProduct_Filter, { msdyn_pricelevel_opportunityproduct_PriceList: OpportunityProduct_Result[] }>;
  msdyn_pricelevel_pricelevel_CopiedFromPriceLevel: WebExpand<PriceLevel_Expand, PriceLevel_Select, PriceLevel_Filter, { msdyn_pricelevel_pricelevel_CopiedFromPriceLevel: PriceLevel_Result[] }>;
  msdyn_pricelevel_quotedetail_PriceList: WebExpand<PriceLevel_Expand, QuoteDetail_Select, QuoteDetail_Filter, { msdyn_pricelevel_quotedetail_PriceList: QuoteDetail_Result[] }>;
  organizationid: WebExpand<PriceLevel_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  price_level_accounts: WebExpand<PriceLevel_Expand, Account_Select, Account_Filter, { price_level_accounts: Account_Result[] }>;
  price_level_contacts: WebExpand<PriceLevel_Expand, Contact_Select, Contact_Filter, { price_level_contacts: Contact_Result[] }>;
  price_level_invoices: WebExpand<PriceLevel_Expand, Invoice_Select, Invoice_Filter, { price_level_invoices: Invoice_Result[] }>;
  price_level_opportunties: WebExpand<PriceLevel_Expand, Opportunity_Select, Opportunity_Filter, { price_level_opportunties: Opportunity_Result[] }>;
  price_level_orders: WebExpand<PriceLevel_Expand, SalesOrder_Select, SalesOrder_Filter, { price_level_orders: SalesOrder_Result[] }>;
  price_level_product_price_levels: WebExpand<PriceLevel_Expand, ProductPriceLevel_Select, ProductPriceLevel_Filter, { price_level_product_price_levels: ProductPriceLevel_Result[] }>;
  price_level_products: WebExpand<PriceLevel_Expand, Product_Select, Product_Filter, { price_level_products: Product_Result[] }>;
  price_level_quotes: WebExpand<PriceLevel_Expand, Quote_Select, Quote_Filter, { price_level_quotes: Quote_Result[] }>;
  pricelevel_MailboxTrackingFolders: WebExpand<PriceLevel_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { pricelevel_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  pricelevel_connections1: WebExpand<PriceLevel_Expand, Connection_Select, Connection_Filter, { pricelevel_connections1: Connection_Result[] }>;
  pricelevel_connections2: WebExpand<PriceLevel_Expand, Connection_Select, Connection_Filter, { pricelevel_connections2: Connection_Result[] }>;
  pricelevel_principalobjectattributeaccess: WebExpand<PriceLevel_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { pricelevel_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  transactioncurrencyid: WebExpand<PriceLevel_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_pricelevel: WebExpand<PriceLevel_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_pricelevel: UserEntityInstanceData_Result[] }>;
}
interface PriceLevel_FormattedResult {
  begindate_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  enddate_formatted?: string;
  freighttermscode_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_copiedfrompricelevel_formatted?: string;
  msdyn_entity_formatted?: string;
  msdyn_module_formatted?: string;
  msdyn_timeunit_formatted?: string;
  organizationid_formatted?: string;
  overriddencreatedon_formatted?: string;
  paymentmethodcode_formatted?: string;
  shippingmethodcode_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface PriceLevel_Result extends PriceLevel_Base, PriceLevel_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_copiedfrompricelevel_guid: string | null;
  msdyn_timeunit_guid: string | null;
  organizationid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface PriceLevel_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_CopiedFromPriceLevel: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  msdyn_TimeUnit: WebMappingRetrieve<UoM_Select,UoM_Expand,UoM_Filter,UoM_Fixed,UoM_Result,UoM_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface PriceLevel_RelatedMany {
  PriceLevel_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  PriceLevel_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  PriceLevel_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  PriceLevel_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  PriceList_Campaigns: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  msdyn_organizationalunit_pricelevel: WebMappingRetrieve<msdyn_organizationalunit_Select,msdyn_organizationalunit_Expand,msdyn_organizationalunit_Filter,msdyn_organizationalunit_Fixed,msdyn_organizationalunit_Result,msdyn_organizationalunit_FormattedResult>;
  msdyn_pricelevel_entitlement_PriceListToApply: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  msdyn_pricelevel_msdyn_accountpricelist_PriceList: WebMappingRetrieve<msdyn_accountpricelist_Select,msdyn_accountpricelist_Expand,msdyn_accountpricelist_Filter,msdyn_accountpricelist_Fixed,msdyn_accountpricelist_Result,msdyn_accountpricelist_FormattedResult>;
  msdyn_pricelevel_msdyn_actual_PriceList: WebMappingRetrieve<msdyn_actual_Select,msdyn_actual_Expand,msdyn_actual_Filter,msdyn_actual_Fixed,msdyn_actual_Result,msdyn_actual_FormattedResult>;
  msdyn_pricelevel_msdyn_agreement_PriceList: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  msdyn_pricelevel_msdyn_agreementbookingproduct_PriceList: WebMappingRetrieve<msdyn_agreementbookingproduct_Select,msdyn_agreementbookingproduct_Expand,msdyn_agreementbookingproduct_Filter,msdyn_agreementbookingproduct_Fixed,msdyn_agreementbookingproduct_Result,msdyn_agreementbookingproduct_FormattedResult>;
  msdyn_pricelevel_msdyn_agreementbookingservice_PriceList: WebMappingRetrieve<msdyn_agreementbookingservice_Select,msdyn_agreementbookingservice_Expand,msdyn_agreementbookingservice_Filter,msdyn_agreementbookingservice_Fixed,msdyn_agreementbookingservice_Result,msdyn_agreementbookingservice_FormattedResult>;
  msdyn_pricelevel_msdyn_agreementinvoiceproduct_PriceList: WebMappingRetrieve<msdyn_agreementinvoiceproduct_Select,msdyn_agreementinvoiceproduct_Expand,msdyn_agreementinvoiceproduct_Filter,msdyn_agreementinvoiceproduct_Fixed,msdyn_agreementinvoiceproduct_Result,msdyn_agreementinvoiceproduct_FormattedResult>;
  msdyn_pricelevel_msdyn_contactpricelist_PriceList: WebMappingRetrieve<msdyn_contactpricelist_Select,msdyn_contactpricelist_Expand,msdyn_contactpricelist_Filter,msdyn_contactpricelist_Fixed,msdyn_contactpricelist_Result,msdyn_contactpricelist_FormattedResult>;
  msdyn_pricelevel_msdyn_estimateline_PriceList: WebMappingRetrieve<msdyn_estimateline_Select,msdyn_estimateline_Expand,msdyn_estimateline_Filter,msdyn_estimateline_Fixed,msdyn_estimateline_Result,msdyn_estimateline_FormattedResult>;
  msdyn_pricelevel_msdyn_fieldservicepricelistitem_PriceList: WebMappingRetrieve<msdyn_fieldservicepricelistitem_Select,msdyn_fieldservicepricelistitem_Expand,msdyn_fieldservicepricelistitem_Filter,msdyn_fieldservicepricelistitem_Fixed,msdyn_fieldservicepricelistitem_Result,msdyn_fieldservicepricelistitem_FormattedResult>;
  msdyn_pricelevel_msdyn_invoicelinetransaction_PriceList: WebMappingRetrieve<msdyn_invoicelinetransaction_Select,msdyn_invoicelinetransaction_Expand,msdyn_invoicelinetransaction_Filter,msdyn_invoicelinetransaction_Fixed,msdyn_invoicelinetransaction_Result,msdyn_invoicelinetransaction_FormattedResult>;
  msdyn_pricelevel_msdyn_journalline_PriceList: WebMappingRetrieve<msdyn_journalline_Select,msdyn_journalline_Expand,msdyn_journalline_Filter,msdyn_journalline_Fixed,msdyn_journalline_Result,msdyn_journalline_FormattedResult>;
  msdyn_pricelevel_msdyn_opportunitylinetransaction_PriceList: WebMappingRetrieve<msdyn_opportunitylinetransaction_Select,msdyn_opportunitylinetransaction_Expand,msdyn_opportunitylinetransaction_Filter,msdyn_opportunitylinetransaction_Fixed,msdyn_opportunitylinetransaction_Result,msdyn_opportunitylinetransaction_FormattedResult>;
  msdyn_pricelevel_msdyn_opportunitypricelist_PriceList: WebMappingRetrieve<msdyn_opportunitypricelist_Select,msdyn_opportunitypricelist_Expand,msdyn_opportunitypricelist_Filter,msdyn_opportunitypricelist_Fixed,msdyn_opportunitypricelist_Result,msdyn_opportunitypricelist_FormattedResult>;
  msdyn_pricelevel_msdyn_orderlinetransaction_PriceList: WebMappingRetrieve<msdyn_orderlinetransaction_Select,msdyn_orderlinetransaction_Expand,msdyn_orderlinetransaction_Filter,msdyn_orderlinetransaction_Fixed,msdyn_orderlinetransaction_Result,msdyn_orderlinetransaction_FormattedResult>;
  msdyn_pricelevel_msdyn_orderpricelist_PriceList: WebMappingRetrieve<msdyn_orderpricelist_Select,msdyn_orderpricelist_Expand,msdyn_orderpricelist_Filter,msdyn_orderpricelist_Fixed,msdyn_orderpricelist_Result,msdyn_orderpricelist_FormattedResult>;
  msdyn_pricelevel_msdyn_projectparameterpricelist_PriceList: WebMappingRetrieve<msdyn_projectparameterpricelist_Select,msdyn_projectparameterpricelist_Expand,msdyn_projectparameterpricelist_Filter,msdyn_projectparameterpricelist_Fixed,msdyn_projectparameterpricelist_Result,msdyn_projectparameterpricelist_FormattedResult>;
  msdyn_pricelevel_msdyn_projectpricelist_PriceList: WebMappingRetrieve<msdyn_projectpricelist_Select,msdyn_projectpricelist_Expand,msdyn_projectpricelist_Filter,msdyn_projectpricelist_Fixed,msdyn_projectpricelist_Result,msdyn_projectpricelist_FormattedResult>;
  msdyn_pricelevel_msdyn_quotebookingproduct_PriceList: WebMappingRetrieve<msdyn_quotebookingproduct_Select,msdyn_quotebookingproduct_Expand,msdyn_quotebookingproduct_Filter,msdyn_quotebookingproduct_Fixed,msdyn_quotebookingproduct_Result,msdyn_quotebookingproduct_FormattedResult>;
  msdyn_pricelevel_msdyn_quotebookingservice_PriceList: WebMappingRetrieve<msdyn_quotebookingservice_Select,msdyn_quotebookingservice_Expand,msdyn_quotebookingservice_Filter,msdyn_quotebookingservice_Fixed,msdyn_quotebookingservice_Result,msdyn_quotebookingservice_FormattedResult>;
  msdyn_pricelevel_msdyn_quotelinetransaction_PriceList: WebMappingRetrieve<msdyn_quotelinetransaction_Select,msdyn_quotelinetransaction_Expand,msdyn_quotelinetransaction_Filter,msdyn_quotelinetransaction_Fixed,msdyn_quotelinetransaction_Result,msdyn_quotelinetransaction_FormattedResult>;
  msdyn_pricelevel_msdyn_quotepricelist_PriceList: WebMappingRetrieve<msdyn_quotepricelist_Select,msdyn_quotepricelist_Expand,msdyn_quotepricelist_Filter,msdyn_quotepricelist_Fixed,msdyn_quotepricelist_Result,msdyn_quotepricelist_FormattedResult>;
  msdyn_pricelevel_msdyn_resourcecategorymarkuppricelevel_PriceList: WebMappingRetrieve<msdyn_resourcecategorymarkuppricelevel_Select,msdyn_resourcecategorymarkuppricelevel_Expand,msdyn_resourcecategorymarkuppricelevel_Filter,msdyn_resourcecategorymarkuppricelevel_Fixed,msdyn_resourcecategorymarkuppricelevel_Result,msdyn_resourcecategorymarkuppricelevel_FormattedResult>;
  msdyn_pricelevel_msdyn_resourcecategorypricelevel_PriceList: WebMappingRetrieve<msdyn_resourcecategorypricelevel_Select,msdyn_resourcecategorypricelevel_Expand,msdyn_resourcecategorypricelevel_Filter,msdyn_resourcecategorypricelevel_Fixed,msdyn_resourcecategorypricelevel_Result,msdyn_resourcecategorypricelevel_FormattedResult>;
  msdyn_pricelevel_msdyn_rma_PriceList: WebMappingRetrieve<msdyn_rma_Select,msdyn_rma_Expand,msdyn_rma_Filter,msdyn_rma_Fixed,msdyn_rma_Result,msdyn_rma_FormattedResult>;
  msdyn_pricelevel_msdyn_rmaproduct_PriceList: WebMappingRetrieve<msdyn_rmaproduct_Select,msdyn_rmaproduct_Expand,msdyn_rmaproduct_Filter,msdyn_rmaproduct_Fixed,msdyn_rmaproduct_Result,msdyn_rmaproduct_FormattedResult>;
  msdyn_pricelevel_msdyn_transactioncategorypricelevel_PriceList: WebMappingRetrieve<msdyn_transactioncategorypricelevel_Select,msdyn_transactioncategorypricelevel_Expand,msdyn_transactioncategorypricelevel_Filter,msdyn_transactioncategorypricelevel_Fixed,msdyn_transactioncategorypricelevel_Result,msdyn_transactioncategorypricelevel_FormattedResult>;
  msdyn_pricelevel_msdyn_workorder_PriceList: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  msdyn_pricelevel_msdyn_workorderproduct_PriceList: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  msdyn_pricelevel_msdyn_workorderservice_PriceList: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  msdyn_pricelevel_msdyn_workordertype_PriceList: WebMappingRetrieve<msdyn_workordertype_Select,msdyn_workordertype_Expand,msdyn_workordertype_Filter,msdyn_workordertype_Fixed,msdyn_workordertype_Result,msdyn_workordertype_FormattedResult>;
  msdyn_pricelevel_opportunityproduct_PriceList: WebMappingRetrieve<OpportunityProduct_Select,OpportunityProduct_Expand,OpportunityProduct_Filter,OpportunityProduct_Fixed,OpportunityProduct_Result,OpportunityProduct_FormattedResult>;
  msdyn_pricelevel_pricelevel_CopiedFromPriceLevel: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  msdyn_pricelevel_quotedetail_PriceList: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  price_level_accounts: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  price_level_contacts: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  price_level_invoices: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  price_level_opportunties: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  price_level_orders: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  price_level_product_price_levels: WebMappingRetrieve<ProductPriceLevel_Select,ProductPriceLevel_Expand,ProductPriceLevel_Filter,ProductPriceLevel_Fixed,ProductPriceLevel_Result,ProductPriceLevel_FormattedResult>;
  price_level_products: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  price_level_quotes: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  pricelevel_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  pricelevel_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  pricelevel_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  pricelevel_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  userentityinstancedata_pricelevel: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  pricelevels: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
}
interface WebEntitiesRelated {
  pricelevels: WebMappingRelated<PriceLevel_RelatedOne,PriceLevel_RelatedMany>;
}
interface WebEntitiesCUDA {
  pricelevels: WebMappingCUDA<PriceLevel_Create,PriceLevel_Update,PriceLevel_Select>;
}
