interface Product_Base extends WebEntity {
  createdon?: Date | null;
  currentcost?: number | null;
  currentcost_base?: number | null;
  description?: string | null;
  dmtimportstate?: number | null;
  entityimageid?: string | null;
  exchangerate?: number | null;
  hierarchypath?: string | null;
  importsequencenumber?: number | null;
  iskit?: boolean | null;
  isreparented?: boolean | null;
  isstockitem?: boolean | null;
  modifiedon?: Date | null;
  msdyn_converttocustomerasset?: boolean | null;
  msdyn_fieldserviceproducttype?: msdyn_fieldserviceproducttype | null;
  msdyn_purchasename?: string | null;
  msdyn_taxable?: boolean | null;
  msdyn_upccode?: string | null;
  name?: string | null;
  overriddencreatedon?: Date | null;
  price?: number | null;
  price_base?: number | null;
  processid?: string | null;
  productid?: string | null;
  productnumber?: string | null;
  productstructure?: product_productstructure | null;
  producttypecode?: product_producttypecode | null;
  producturl?: string | null;
  quantitydecimal?: number | null;
  quantityonhand?: number | null;
  size?: string | null;
  stageid?: string | null;
  standardcost?: number | null;
  standardcost_base?: number | null;
  statecode?: product_statecode | null;
  statuscode?: product_statuscode | null;
  stockvolume?: number | null;
  stockweight?: number | null;
  suppliername?: string | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  validfromdate?: Date | null;
  validtodate?: Date | null;
  vendorid?: string | null;
  vendorname?: string | null;
  vendorpartnumber?: string | null;
  versionnumber?: number | null;
}
interface Product_Relationships {
  CreatedByExternalParty?: ExternalParty_Result | null;
  ModifiedByExternalParty?: ExternalParty_Result | null;
  Product_Annotation?: Annotation_Result[] | null;
  Product_AsyncOperations?: AsyncOperation_Result[] | null;
  Product_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Product_DynamicProperty?: DynamicProperty_Result[] | null;
  Product_DynamicPropertyAssociation?: DynamicPropertyAssociation_Result[] | null;
  Product_ProcessSessions?: ProcessSession_Result[] | null;
  Product_ProductAssociation_AssocProd?: ProductAssociation_Result[] | null;
  Product_ProductAssociation_Prod?: ProductAssociation_Result[] | null;
  Product_SharepointDocument?: SharePointDocument_Result[] | null;
  Product_SharepointDocumentLocation?: SharePointDocumentLocation_Result[] | null;
  Product_SyncErrors?: SyncError_Result[] | null;
  campaignproduct_association?: Campaign_Result[] | null;
  competitorproduct_association?: Competitor_Result[] | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  leadproduct_association?: Lead_Result[] | null;
  msdyn_TransactionCategory?: msdyn_transactioncategory_Result | null;
  msdyn_product_msdyn_actual_Product?: msdyn_actual_Result[] | null;
  msdyn_product_msdyn_agreementbookingproduct_Product?: msdyn_agreementbookingproduct_Result[] | null;
  msdyn_product_msdyn_agreementbookingservice_Service?: msdyn_agreementbookingservice_Result[] | null;
  msdyn_product_msdyn_agreementinvoiceproduct_Product?: msdyn_agreementinvoiceproduct_Result[] | null;
  msdyn_product_msdyn_customerasset_Product?: msdyn_customerasset_Result[] | null;
  msdyn_product_msdyn_estimateline_Product?: msdyn_estimateline_Result[] | null;
  msdyn_product_msdyn_fact_Product?: msdyn_fact_Result[] | null;
  msdyn_product_msdyn_fieldcomputation_ProductId?: msdyn_fieldcomputation_Result[] | null;
  msdyn_product_msdyn_fieldservicepricelistitem_ProductService?: msdyn_fieldservicepricelistitem_Result[] | null;
  msdyn_product_msdyn_fieldservicesetting?: msdyn_fieldservicesetting_Result[] | null;
  msdyn_product_msdyn_incidenttypeproduct_Product?: msdyn_incidenttypeproduct_Result[] | null;
  msdyn_product_msdyn_incidenttyperecommendationresult_ProductService?: msdyn_incidenttyperecommendationresult_Result[] | null;
  msdyn_product_msdyn_incidenttypeservice_Service?: msdyn_incidenttypeservice_Result[] | null;
  msdyn_product_msdyn_inventoryadjustmentproduct_Product?: msdyn_inventoryadjustmentproduct_Result[] | null;
  msdyn_product_msdyn_inventoryjournal_Product?: msdyn_inventoryjournal_Result[] | null;
  msdyn_product_msdyn_invoicelinetransaction_Product?: msdyn_invoicelinetransaction_Result[] | null;
  msdyn_product_msdyn_journalline_Product?: msdyn_journalline_Result[] | null;
  msdyn_product_msdyn_opportunitylinetransaction_Product?: msdyn_opportunitylinetransaction_Result[] | null;
  msdyn_product_msdyn_orderinvoicingproduct_Product?: msdyn_orderinvoicingproduct_Result[] | null;
  msdyn_product_msdyn_orderlinetransaction_Product?: msdyn_orderlinetransaction_Result[] | null;
  msdyn_product_msdyn_productinventory_Product?: msdyn_productinventory_Result[] | null;
  msdyn_product_msdyn_purchaseorderproduct_Product?: msdyn_purchaseorderproduct_Result[] | null;
  msdyn_product_msdyn_quotebookingproduct_Product?: msdyn_quotebookingproduct_Result[] | null;
  msdyn_product_msdyn_quotebookingservice_Service?: msdyn_quotebookingservice_Result[] | null;
  msdyn_product_msdyn_quoteinvoicingproduct_Product?: msdyn_quoteinvoicingproduct_Result[] | null;
  msdyn_product_msdyn_quotelinetransaction_Product?: msdyn_quotelinetransaction_Result[] | null;
  msdyn_product_msdyn_rmaproduct_Product?: msdyn_rmaproduct_Result[] | null;
  msdyn_product_msdyn_rtvproduct_Product?: msdyn_rtvproduct_Result[] | null;
  msdyn_product_msdyn_workorderproduct_Product?: msdyn_workorderproduct_Result[] | null;
  msdyn_product_msdyn_workorderservice_Service?: msdyn_workorderservice_Result[] | null;
  navigationPropertyNameNotDefined?: KnowledgeBaseRecord_Result[] | null;
  navigationPropertyNameNotDefined1?: KnowledgeArticle_Result[] | null;
  opportunity_products?: OpportunityProduct_Result[] | null;
  product_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  product_ProductSubstitute_productid?: ProductSubstitute_Result[] | null;
  product_ProductSubstitute_substitutedproductid?: ProductSubstitute_Result[] | null;
  product_connections1?: Connection_Result[] | null;
  product_connections2?: Connection_Result[] | null;
  product_contract_line_items?: ContractDetail_Result[] | null;
  product_entitlement_association?: Entitlement_Result[] | null;
  product_entitlementtemplate_association?: EntitlementTemplate_Result[] | null;
  product_incidents?: Incident_Result[] | null;
  product_invoice_details?: InvoiceDetail_Result[] | null;
  product_order_details?: SalesOrderDetail_Result[] | null;
  product_parent_product?: Product_Result[] | null;
  product_price_levels?: ProductPriceLevel_Result[] | null;
  product_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  product_quote_details?: QuoteDetail_Result[] | null;
  productsalesliterature_association?: SalesLiterature_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  userentityinstancedata_product?: UserEntityInstanceData_Result[] | null;
}
interface Product extends Product_Base, Product_Relationships {
  defaultuomid_bind$uoms?: string | null;
  defaultuomscheduleid_bind$uomschedules?: string | null;
  msdyn_TransactionCategory_bind$msdyn_transactioncategories?: string | null;
  msdyn_defaultvendor_bind$accounts?: string | null;
  parentproductid_bind$products?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  subjectid_bind$subjects?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface Product_Create extends Product {
}
interface Product_Update extends Product {
  pricelevelid_bind$pricelevels?: string | null;
}
interface Product_Select {
  createdby_guid: WebAttribute<Product_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdbyexternalparty_guid: WebAttribute<Product_Select, { createdbyexternalparty_guid: string | null }, { createdbyexternalparty_formatted?: string }>;
  createdon: WebAttribute<Product_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Product_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  currentcost: WebAttribute<Product_Select, { currentcost: number | null; transactioncurrencyid_guid: string | null }, { currentcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  currentcost_base: WebAttribute<Product_Select, { currentcost_base: number | null; transactioncurrencyid_guid: string | null }, { currentcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  defaultuomid_guid: WebAttribute<Product_Select, { defaultuomid_guid: string | null }, { defaultuomid_formatted?: string }>;
  defaultuomscheduleid_guid: WebAttribute<Product_Select, { defaultuomscheduleid_guid: string | null }, { defaultuomscheduleid_formatted?: string }>;
  description: WebAttribute<Product_Select, { description: string | null }, {  }>;
  dmtimportstate: WebAttribute<Product_Select, { dmtimportstate: number | null }, {  }>;
  entityimageid: WebAttribute<Product_Select, { entityimageid: string | null }, {  }>;
  exchangerate: WebAttribute<Product_Select, { exchangerate: number | null }, {  }>;
  hierarchypath: WebAttribute<Product_Select, { hierarchypath: string | null }, {  }>;
  importsequencenumber: WebAttribute<Product_Select, { importsequencenumber: number | null }, {  }>;
  iskit: WebAttribute<Product_Select, { iskit: boolean | null }, {  }>;
  isreparented: WebAttribute<Product_Select, { isreparented: boolean | null }, {  }>;
  isstockitem: WebAttribute<Product_Select, { isstockitem: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<Product_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedbyexternalparty_guid: WebAttribute<Product_Select, { modifiedbyexternalparty_guid: string | null }, { modifiedbyexternalparty_formatted?: string }>;
  modifiedon: WebAttribute<Product_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Product_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_converttocustomerasset: WebAttribute<Product_Select, { msdyn_converttocustomerasset: boolean | null }, {  }>;
  msdyn_defaultvendor_guid: WebAttribute<Product_Select, { msdyn_defaultvendor_guid: string | null }, { msdyn_defaultvendor_formatted?: string }>;
  msdyn_fieldserviceproducttype: WebAttribute<Product_Select, { msdyn_fieldserviceproducttype: msdyn_fieldserviceproducttype | null }, { msdyn_fieldserviceproducttype_formatted?: string }>;
  msdyn_purchasename: WebAttribute<Product_Select, { msdyn_purchasename: string | null }, {  }>;
  msdyn_taxable: WebAttribute<Product_Select, { msdyn_taxable: boolean | null }, {  }>;
  msdyn_transactioncategory_guid: WebAttribute<Product_Select, { msdyn_transactioncategory_guid: string | null }, { msdyn_transactioncategory_formatted?: string }>;
  msdyn_upccode: WebAttribute<Product_Select, { msdyn_upccode: string | null }, {  }>;
  name: WebAttribute<Product_Select, { name: string | null }, {  }>;
  organizationid_guid: WebAttribute<Product_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  overriddencreatedon: WebAttribute<Product_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  parentproductid_guid: WebAttribute<Product_Select, { parentproductid_guid: string | null }, { parentproductid_formatted?: string }>;
  price: WebAttribute<Product_Select, { price: number | null; transactioncurrencyid_guid: string | null }, { price_formatted?: string; transactioncurrencyid_formatted?: string }>;
  price_base: WebAttribute<Product_Select, { price_base: number | null; transactioncurrencyid_guid: string | null }, { price_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  pricelevelid_guid: WebAttribute<Product_Select, { pricelevelid_guid: string | null }, { pricelevelid_formatted?: string }>;
  processid: WebAttribute<Product_Select, { processid: string | null }, {  }>;
  productid: WebAttribute<Product_Select, { productid: string | null }, {  }>;
  productnumber: WebAttribute<Product_Select, { productnumber: string | null }, {  }>;
  productstructure: WebAttribute<Product_Select, { productstructure: product_productstructure | null }, { productstructure_formatted?: string }>;
  producttypecode: WebAttribute<Product_Select, { producttypecode: product_producttypecode | null }, { producttypecode_formatted?: string }>;
  producturl: WebAttribute<Product_Select, { producturl: string | null }, {  }>;
  quantitydecimal: WebAttribute<Product_Select, { quantitydecimal: number | null }, {  }>;
  quantityonhand: WebAttribute<Product_Select, { quantityonhand: number | null }, {  }>;
  size: WebAttribute<Product_Select, { size: string | null }, {  }>;
  stageid: WebAttribute<Product_Select, { stageid: string | null }, {  }>;
  standardcost: WebAttribute<Product_Select, { standardcost: number | null; transactioncurrencyid_guid: string | null }, { standardcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  standardcost_base: WebAttribute<Product_Select, { standardcost_base: number | null; transactioncurrencyid_guid: string | null }, { standardcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  statecode: WebAttribute<Product_Select, { statecode: product_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Product_Select, { statuscode: product_statuscode | null }, { statuscode_formatted?: string }>;
  stockvolume: WebAttribute<Product_Select, { stockvolume: number | null }, {  }>;
  stockweight: WebAttribute<Product_Select, { stockweight: number | null }, {  }>;
  subjectid_guid: WebAttribute<Product_Select, { subjectid_guid: string | null }, { subjectid_formatted?: string }>;
  suppliername: WebAttribute<Product_Select, { suppliername: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<Product_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<Product_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Product_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Product_Select, { utcconversiontimezonecode: number | null }, {  }>;
  validfromdate: WebAttribute<Product_Select, { validfromdate: Date | null }, { validfromdate_formatted?: string }>;
  validtodate: WebAttribute<Product_Select, { validtodate: Date | null }, { validtodate_formatted?: string }>;
  vendorid: WebAttribute<Product_Select, { vendorid: string | null }, {  }>;
  vendorname: WebAttribute<Product_Select, { vendorname: string | null }, {  }>;
  vendorpartnumber: WebAttribute<Product_Select, { vendorpartnumber: string | null }, {  }>;
  versionnumber: WebAttribute<Product_Select, { versionnumber: number | null }, {  }>;
}
interface Product_Filter {
  createdby_guid: XQW.Guid;
  createdbyexternalparty_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  currentcost: number;
  currentcost_base: number;
  defaultuomid_guid: XQW.Guid;
  defaultuomscheduleid_guid: XQW.Guid;
  description: string;
  dmtimportstate: number;
  entityimageid: XQW.Guid;
  exchangerate: any;
  hierarchypath: string;
  importsequencenumber: number;
  iskit: boolean;
  isreparented: boolean;
  isstockitem: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedbyexternalparty_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_converttocustomerasset: boolean;
  msdyn_defaultvendor_guid: XQW.Guid;
  msdyn_fieldserviceproducttype: msdyn_fieldserviceproducttype;
  msdyn_purchasename: string;
  msdyn_taxable: boolean;
  msdyn_transactioncategory_guid: XQW.Guid;
  msdyn_upccode: string;
  name: string;
  organizationid_guid: XQW.Guid;
  overriddencreatedon: Date;
  parentproductid_guid: XQW.Guid;
  price: number;
  price_base: number;
  pricelevelid_guid: XQW.Guid;
  processid: XQW.Guid;
  productid: XQW.Guid;
  productnumber: string;
  productstructure: product_productstructure;
  producttypecode: product_producttypecode;
  producturl: string;
  quantitydecimal: number;
  quantityonhand: any;
  size: string;
  stageid: XQW.Guid;
  standardcost: number;
  standardcost_base: number;
  statecode: product_statecode;
  statuscode: product_statuscode;
  stockvolume: any;
  stockweight: any;
  subjectid_guid: XQW.Guid;
  suppliername: string;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  validfromdate: Date;
  validtodate: Date;
  vendorid: string;
  vendorname: string;
  vendorpartnumber: string;
  versionnumber: number;
}
interface Product_Expand {
  CreatedByExternalParty: WebExpand<Product_Expand, ExternalParty_Select, ExternalParty_Filter, { CreatedByExternalParty: ExternalParty_Result }>;
  ModifiedByExternalParty: WebExpand<Product_Expand, ExternalParty_Select, ExternalParty_Filter, { ModifiedByExternalParty: ExternalParty_Result }>;
  Product_Annotation: WebExpand<Product_Expand, Annotation_Select, Annotation_Filter, { Product_Annotation: Annotation_Result[] }>;
  Product_AsyncOperations: WebExpand<Product_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Product_AsyncOperations: AsyncOperation_Result[] }>;
  Product_BulkDeleteFailures: WebExpand<Product_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Product_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Product_DynamicProperty: WebExpand<Product_Expand, DynamicProperty_Select, DynamicProperty_Filter, { Product_DynamicProperty: DynamicProperty_Result[] }>;
  Product_DynamicPropertyAssociation: WebExpand<Product_Expand, DynamicPropertyAssociation_Select, DynamicPropertyAssociation_Filter, { Product_DynamicPropertyAssociation: DynamicPropertyAssociation_Result[] }>;
  Product_ProcessSessions: WebExpand<Product_Expand, ProcessSession_Select, ProcessSession_Filter, { Product_ProcessSessions: ProcessSession_Result[] }>;
  Product_ProductAssociation_AssocProd: WebExpand<Product_Expand, ProductAssociation_Select, ProductAssociation_Filter, { Product_ProductAssociation_AssocProd: ProductAssociation_Result[] }>;
  Product_ProductAssociation_Prod: WebExpand<Product_Expand, ProductAssociation_Select, ProductAssociation_Filter, { Product_ProductAssociation_Prod: ProductAssociation_Result[] }>;
  Product_SharepointDocument: WebExpand<Product_Expand, SharePointDocument_Select, SharePointDocument_Filter, { Product_SharepointDocument: SharePointDocument_Result[] }>;
  Product_SharepointDocumentLocation: WebExpand<Product_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { Product_SharepointDocumentLocation: SharePointDocumentLocation_Result[] }>;
  Product_SyncErrors: WebExpand<Product_Expand, SyncError_Select, SyncError_Filter, { Product_SyncErrors: SyncError_Result[] }>;
  campaignproduct_association: WebExpand<Product_Expand, Campaign_Select, Campaign_Filter, { campaignproduct_association: Campaign_Result[] }>;
  competitorproduct_association: WebExpand<Product_Expand, Competitor_Select, Competitor_Filter, { competitorproduct_association: Competitor_Result[] }>;
  createdby: WebExpand<Product_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Product_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  defaultuomid: WebExpand<Product_Expand, UoM_Select, UoM_Filter, { defaultuomid: UoM_Result }>;
  defaultuomscheduleid: WebExpand<Product_Expand, UoMSchedule_Select, UoMSchedule_Filter, { defaultuomscheduleid: UoMSchedule_Result }>;
  entityimageid_imagedescriptor: WebExpand<Product_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  leadproduct_association: WebExpand<Product_Expand, Lead_Select, Lead_Filter, { leadproduct_association: Lead_Result[] }>;
  modifiedby: WebExpand<Product_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Product_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_TransactionCategory: WebExpand<Product_Expand, msdyn_transactioncategory_Select, msdyn_transactioncategory_Filter, { msdyn_TransactionCategory: msdyn_transactioncategory_Result }>;
  msdyn_defaultvendor: WebExpand<Product_Expand, Account_Select, Account_Filter, { msdyn_defaultvendor: Account_Result }>;
  msdyn_product_msdyn_actual_Product: WebExpand<Product_Expand, msdyn_actual_Select, msdyn_actual_Filter, { msdyn_product_msdyn_actual_Product: msdyn_actual_Result[] }>;
  msdyn_product_msdyn_agreementbookingproduct_Product: WebExpand<Product_Expand, msdyn_agreementbookingproduct_Select, msdyn_agreementbookingproduct_Filter, { msdyn_product_msdyn_agreementbookingproduct_Product: msdyn_agreementbookingproduct_Result[] }>;
  msdyn_product_msdyn_agreementbookingservice_Service: WebExpand<Product_Expand, msdyn_agreementbookingservice_Select, msdyn_agreementbookingservice_Filter, { msdyn_product_msdyn_agreementbookingservice_Service: msdyn_agreementbookingservice_Result[] }>;
  msdyn_product_msdyn_agreementinvoiceproduct_Product: WebExpand<Product_Expand, msdyn_agreementinvoiceproduct_Select, msdyn_agreementinvoiceproduct_Filter, { msdyn_product_msdyn_agreementinvoiceproduct_Product: msdyn_agreementinvoiceproduct_Result[] }>;
  msdyn_product_msdyn_customerasset_Product: WebExpand<Product_Expand, msdyn_customerasset_Select, msdyn_customerasset_Filter, { msdyn_product_msdyn_customerasset_Product: msdyn_customerasset_Result[] }>;
  msdyn_product_msdyn_estimateline_Product: WebExpand<Product_Expand, msdyn_estimateline_Select, msdyn_estimateline_Filter, { msdyn_product_msdyn_estimateline_Product: msdyn_estimateline_Result[] }>;
  msdyn_product_msdyn_fact_Product: WebExpand<Product_Expand, msdyn_fact_Select, msdyn_fact_Filter, { msdyn_product_msdyn_fact_Product: msdyn_fact_Result[] }>;
  msdyn_product_msdyn_fieldcomputation_ProductId: WebExpand<Product_Expand, msdyn_fieldcomputation_Select, msdyn_fieldcomputation_Filter, { msdyn_product_msdyn_fieldcomputation_ProductId: msdyn_fieldcomputation_Result[] }>;
  msdyn_product_msdyn_fieldservicepricelistitem_ProductService: WebExpand<Product_Expand, msdyn_fieldservicepricelistitem_Select, msdyn_fieldservicepricelistitem_Filter, { msdyn_product_msdyn_fieldservicepricelistitem_ProductService: msdyn_fieldservicepricelistitem_Result[] }>;
  msdyn_product_msdyn_fieldservicesetting: WebExpand<Product_Expand, msdyn_fieldservicesetting_Select, msdyn_fieldservicesetting_Filter, { msdyn_product_msdyn_fieldservicesetting: msdyn_fieldservicesetting_Result[] }>;
  msdyn_product_msdyn_incidenttypeproduct_Product: WebExpand<Product_Expand, msdyn_incidenttypeproduct_Select, msdyn_incidenttypeproduct_Filter, { msdyn_product_msdyn_incidenttypeproduct_Product: msdyn_incidenttypeproduct_Result[] }>;
  msdyn_product_msdyn_incidenttyperecommendationresult_ProductService: WebExpand<Product_Expand, msdyn_incidenttyperecommendationresult_Select, msdyn_incidenttyperecommendationresult_Filter, { msdyn_product_msdyn_incidenttyperecommendationresult_ProductService: msdyn_incidenttyperecommendationresult_Result[] }>;
  msdyn_product_msdyn_incidenttypeservice_Service: WebExpand<Product_Expand, msdyn_incidenttypeservice_Select, msdyn_incidenttypeservice_Filter, { msdyn_product_msdyn_incidenttypeservice_Service: msdyn_incidenttypeservice_Result[] }>;
  msdyn_product_msdyn_inventoryadjustmentproduct_Product: WebExpand<Product_Expand, msdyn_inventoryadjustmentproduct_Select, msdyn_inventoryadjustmentproduct_Filter, { msdyn_product_msdyn_inventoryadjustmentproduct_Product: msdyn_inventoryadjustmentproduct_Result[] }>;
  msdyn_product_msdyn_inventoryjournal_Product: WebExpand<Product_Expand, msdyn_inventoryjournal_Select, msdyn_inventoryjournal_Filter, { msdyn_product_msdyn_inventoryjournal_Product: msdyn_inventoryjournal_Result[] }>;
  msdyn_product_msdyn_invoicelinetransaction_Product: WebExpand<Product_Expand, msdyn_invoicelinetransaction_Select, msdyn_invoicelinetransaction_Filter, { msdyn_product_msdyn_invoicelinetransaction_Product: msdyn_invoicelinetransaction_Result[] }>;
  msdyn_product_msdyn_journalline_Product: WebExpand<Product_Expand, msdyn_journalline_Select, msdyn_journalline_Filter, { msdyn_product_msdyn_journalline_Product: msdyn_journalline_Result[] }>;
  msdyn_product_msdyn_opportunitylinetransaction_Product: WebExpand<Product_Expand, msdyn_opportunitylinetransaction_Select, msdyn_opportunitylinetransaction_Filter, { msdyn_product_msdyn_opportunitylinetransaction_Product: msdyn_opportunitylinetransaction_Result[] }>;
  msdyn_product_msdyn_orderinvoicingproduct_Product: WebExpand<Product_Expand, msdyn_orderinvoicingproduct_Select, msdyn_orderinvoicingproduct_Filter, { msdyn_product_msdyn_orderinvoicingproduct_Product: msdyn_orderinvoicingproduct_Result[] }>;
  msdyn_product_msdyn_orderlinetransaction_Product: WebExpand<Product_Expand, msdyn_orderlinetransaction_Select, msdyn_orderlinetransaction_Filter, { msdyn_product_msdyn_orderlinetransaction_Product: msdyn_orderlinetransaction_Result[] }>;
  msdyn_product_msdyn_productinventory_Product: WebExpand<Product_Expand, msdyn_productinventory_Select, msdyn_productinventory_Filter, { msdyn_product_msdyn_productinventory_Product: msdyn_productinventory_Result[] }>;
  msdyn_product_msdyn_purchaseorderproduct_Product: WebExpand<Product_Expand, msdyn_purchaseorderproduct_Select, msdyn_purchaseorderproduct_Filter, { msdyn_product_msdyn_purchaseorderproduct_Product: msdyn_purchaseorderproduct_Result[] }>;
  msdyn_product_msdyn_quotebookingproduct_Product: WebExpand<Product_Expand, msdyn_quotebookingproduct_Select, msdyn_quotebookingproduct_Filter, { msdyn_product_msdyn_quotebookingproduct_Product: msdyn_quotebookingproduct_Result[] }>;
  msdyn_product_msdyn_quotebookingservice_Service: WebExpand<Product_Expand, msdyn_quotebookingservice_Select, msdyn_quotebookingservice_Filter, { msdyn_product_msdyn_quotebookingservice_Service: msdyn_quotebookingservice_Result[] }>;
  msdyn_product_msdyn_quoteinvoicingproduct_Product: WebExpand<Product_Expand, msdyn_quoteinvoicingproduct_Select, msdyn_quoteinvoicingproduct_Filter, { msdyn_product_msdyn_quoteinvoicingproduct_Product: msdyn_quoteinvoicingproduct_Result[] }>;
  msdyn_product_msdyn_quotelinetransaction_Product: WebExpand<Product_Expand, msdyn_quotelinetransaction_Select, msdyn_quotelinetransaction_Filter, { msdyn_product_msdyn_quotelinetransaction_Product: msdyn_quotelinetransaction_Result[] }>;
  msdyn_product_msdyn_rmaproduct_Product: WebExpand<Product_Expand, msdyn_rmaproduct_Select, msdyn_rmaproduct_Filter, { msdyn_product_msdyn_rmaproduct_Product: msdyn_rmaproduct_Result[] }>;
  msdyn_product_msdyn_rtvproduct_Product: WebExpand<Product_Expand, msdyn_rtvproduct_Select, msdyn_rtvproduct_Filter, { msdyn_product_msdyn_rtvproduct_Product: msdyn_rtvproduct_Result[] }>;
  msdyn_product_msdyn_workorderproduct_Product: WebExpand<Product_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { msdyn_product_msdyn_workorderproduct_Product: msdyn_workorderproduct_Result[] }>;
  msdyn_product_msdyn_workorderservice_Service: WebExpand<Product_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { msdyn_product_msdyn_workorderservice_Service: msdyn_workorderservice_Result[] }>;
  navigationPropertyNameNotDefined: WebExpand<Product_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { navigationPropertyNameNotDefined: KnowledgeBaseRecord_Result[] }>;
  navigationPropertyNameNotDefined1: WebExpand<Product_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { navigationPropertyNameNotDefined: KnowledgeArticle_Result[] }>;
  opportunity_products: WebExpand<Product_Expand, OpportunityProduct_Select, OpportunityProduct_Filter, { opportunity_products: OpportunityProduct_Result[] }>;
  organizationid: WebExpand<Product_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  parentproductid: WebExpand<Product_Expand, Product_Select, Product_Filter, { parentproductid: Product_Result }>;
  pricelevelid: WebExpand<Product_Expand, PriceLevel_Select, PriceLevel_Filter, { pricelevelid: PriceLevel_Result }>;
  product_MailboxTrackingFolders: WebExpand<Product_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { product_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  product_ProductSubstitute_productid: WebExpand<Product_Expand, ProductSubstitute_Select, ProductSubstitute_Filter, { product_ProductSubstitute_productid: ProductSubstitute_Result[] }>;
  product_ProductSubstitute_substitutedproductid: WebExpand<Product_Expand, ProductSubstitute_Select, ProductSubstitute_Filter, { product_ProductSubstitute_substitutedproductid: ProductSubstitute_Result[] }>;
  product_connections1: WebExpand<Product_Expand, Connection_Select, Connection_Filter, { product_connections1: Connection_Result[] }>;
  product_connections2: WebExpand<Product_Expand, Connection_Select, Connection_Filter, { product_connections2: Connection_Result[] }>;
  product_contract_line_items: WebExpand<Product_Expand, ContractDetail_Select, ContractDetail_Filter, { product_contract_line_items: ContractDetail_Result[] }>;
  product_entitlement_association: WebExpand<Product_Expand, Entitlement_Select, Entitlement_Filter, { product_entitlement_association: Entitlement_Result[] }>;
  product_entitlementtemplate_association: WebExpand<Product_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { product_entitlementtemplate_association: EntitlementTemplate_Result[] }>;
  product_incidents: WebExpand<Product_Expand, Incident_Select, Incident_Filter, { product_incidents: Incident_Result[] }>;
  product_invoice_details: WebExpand<Product_Expand, InvoiceDetail_Select, InvoiceDetail_Filter, { product_invoice_details: InvoiceDetail_Result[] }>;
  product_order_details: WebExpand<Product_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { product_order_details: SalesOrderDetail_Result[] }>;
  product_parent_product: WebExpand<Product_Expand, Product_Select, Product_Filter, { product_parent_product: Product_Result[] }>;
  product_price_levels: WebExpand<Product_Expand, ProductPriceLevel_Select, ProductPriceLevel_Filter, { product_price_levels: ProductPriceLevel_Result[] }>;
  product_principalobjectattributeaccess: WebExpand<Product_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { product_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  product_quote_details: WebExpand<Product_Expand, QuoteDetail_Select, QuoteDetail_Filter, { product_quote_details: QuoteDetail_Result[] }>;
  productsalesliterature_association: WebExpand<Product_Expand, SalesLiterature_Select, SalesLiterature_Filter, { productsalesliterature_association: SalesLiterature_Result[] }>;
  stageid_processstage: WebExpand<Product_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  subjectid: WebExpand<Product_Expand, Subject_Select, Subject_Filter, { subjectid: Subject_Result }>;
  transactioncurrencyid: WebExpand<Product_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_product: WebExpand<Product_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_product: UserEntityInstanceData_Result[] }>;
}
interface Product_FormattedResult {
  createdby_formatted?: string;
  createdbyexternalparty_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  currentcost_base_formatted?: string;
  currentcost_formatted?: string;
  defaultuomid_formatted?: string;
  defaultuomscheduleid_formatted?: string;
  modifiedby_formatted?: string;
  modifiedbyexternalparty_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_defaultvendor_formatted?: string;
  msdyn_fieldserviceproducttype_formatted?: string;
  msdyn_transactioncategory_formatted?: string;
  organizationid_formatted?: string;
  overriddencreatedon_formatted?: string;
  parentproductid_formatted?: string;
  price_base_formatted?: string;
  price_formatted?: string;
  pricelevelid_formatted?: string;
  productstructure_formatted?: string;
  producttypecode_formatted?: string;
  standardcost_base_formatted?: string;
  standardcost_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  subjectid_formatted?: string;
  transactioncurrencyid_formatted?: string;
  validfromdate_formatted?: string;
  validtodate_formatted?: string;
}
interface Product_Result extends Product_Base, Product_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdbyexternalparty_guid: string | null;
  createdonbehalfby_guid: string | null;
  defaultuomid_guid: string | null;
  defaultuomscheduleid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedbyexternalparty_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_defaultvendor_guid: string | null;
  msdyn_transactioncategory_guid: string | null;
  organizationid_guid: string | null;
  parentproductid_guid: string | null;
  pricelevelid_guid: string | null;
  subjectid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Product_RelatedOne {
  CreatedByExternalParty: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  ModifiedByExternalParty: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  defaultuomid: WebMappingRetrieve<UoM_Select,UoM_Expand,UoM_Filter,UoM_Fixed,UoM_Result,UoM_FormattedResult>;
  defaultuomscheduleid: WebMappingRetrieve<UoMSchedule_Select,UoMSchedule_Expand,UoMSchedule_Filter,UoMSchedule_Fixed,UoMSchedule_Result,UoMSchedule_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_TransactionCategory: WebMappingRetrieve<msdyn_transactioncategory_Select,msdyn_transactioncategory_Expand,msdyn_transactioncategory_Filter,msdyn_transactioncategory_Fixed,msdyn_transactioncategory_Result,msdyn_transactioncategory_FormattedResult>;
  msdyn_defaultvendor: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  parentproductid: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  pricelevelid: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  subjectid: WebMappingRetrieve<Subject_Select,Subject_Expand,Subject_Filter,Subject_Fixed,Subject_Result,Subject_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Product_RelatedMany {
  Product_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Product_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Product_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Product_DynamicProperty: WebMappingRetrieve<DynamicProperty_Select,DynamicProperty_Expand,DynamicProperty_Filter,DynamicProperty_Fixed,DynamicProperty_Result,DynamicProperty_FormattedResult>;
  Product_DynamicPropertyAssociation: WebMappingRetrieve<DynamicPropertyAssociation_Select,DynamicPropertyAssociation_Expand,DynamicPropertyAssociation_Filter,DynamicPropertyAssociation_Fixed,DynamicPropertyAssociation_Result,DynamicPropertyAssociation_FormattedResult>;
  Product_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Product_ProductAssociation_AssocProd: WebMappingRetrieve<ProductAssociation_Select,ProductAssociation_Expand,ProductAssociation_Filter,ProductAssociation_Fixed,ProductAssociation_Result,ProductAssociation_FormattedResult>;
  Product_ProductAssociation_Prod: WebMappingRetrieve<ProductAssociation_Select,ProductAssociation_Expand,ProductAssociation_Filter,ProductAssociation_Fixed,ProductAssociation_Result,ProductAssociation_FormattedResult>;
  Product_SharepointDocument: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  Product_SharepointDocumentLocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  Product_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  campaignproduct_association: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  competitorproduct_association: WebMappingRetrieve<Competitor_Select,Competitor_Expand,Competitor_Filter,Competitor_Fixed,Competitor_Result,Competitor_FormattedResult>;
  leadproduct_association: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  msdyn_product_msdyn_actual_Product: WebMappingRetrieve<msdyn_actual_Select,msdyn_actual_Expand,msdyn_actual_Filter,msdyn_actual_Fixed,msdyn_actual_Result,msdyn_actual_FormattedResult>;
  msdyn_product_msdyn_agreementbookingproduct_Product: WebMappingRetrieve<msdyn_agreementbookingproduct_Select,msdyn_agreementbookingproduct_Expand,msdyn_agreementbookingproduct_Filter,msdyn_agreementbookingproduct_Fixed,msdyn_agreementbookingproduct_Result,msdyn_agreementbookingproduct_FormattedResult>;
  msdyn_product_msdyn_agreementbookingservice_Service: WebMappingRetrieve<msdyn_agreementbookingservice_Select,msdyn_agreementbookingservice_Expand,msdyn_agreementbookingservice_Filter,msdyn_agreementbookingservice_Fixed,msdyn_agreementbookingservice_Result,msdyn_agreementbookingservice_FormattedResult>;
  msdyn_product_msdyn_agreementinvoiceproduct_Product: WebMappingRetrieve<msdyn_agreementinvoiceproduct_Select,msdyn_agreementinvoiceproduct_Expand,msdyn_agreementinvoiceproduct_Filter,msdyn_agreementinvoiceproduct_Fixed,msdyn_agreementinvoiceproduct_Result,msdyn_agreementinvoiceproduct_FormattedResult>;
  msdyn_product_msdyn_customerasset_Product: WebMappingRetrieve<msdyn_customerasset_Select,msdyn_customerasset_Expand,msdyn_customerasset_Filter,msdyn_customerasset_Fixed,msdyn_customerasset_Result,msdyn_customerasset_FormattedResult>;
  msdyn_product_msdyn_estimateline_Product: WebMappingRetrieve<msdyn_estimateline_Select,msdyn_estimateline_Expand,msdyn_estimateline_Filter,msdyn_estimateline_Fixed,msdyn_estimateline_Result,msdyn_estimateline_FormattedResult>;
  msdyn_product_msdyn_fact_Product: WebMappingRetrieve<msdyn_fact_Select,msdyn_fact_Expand,msdyn_fact_Filter,msdyn_fact_Fixed,msdyn_fact_Result,msdyn_fact_FormattedResult>;
  msdyn_product_msdyn_fieldcomputation_ProductId: WebMappingRetrieve<msdyn_fieldcomputation_Select,msdyn_fieldcomputation_Expand,msdyn_fieldcomputation_Filter,msdyn_fieldcomputation_Fixed,msdyn_fieldcomputation_Result,msdyn_fieldcomputation_FormattedResult>;
  msdyn_product_msdyn_fieldservicepricelistitem_ProductService: WebMappingRetrieve<msdyn_fieldservicepricelistitem_Select,msdyn_fieldservicepricelistitem_Expand,msdyn_fieldservicepricelistitem_Filter,msdyn_fieldservicepricelistitem_Fixed,msdyn_fieldservicepricelistitem_Result,msdyn_fieldservicepricelistitem_FormattedResult>;
  msdyn_product_msdyn_fieldservicesetting: WebMappingRetrieve<msdyn_fieldservicesetting_Select,msdyn_fieldservicesetting_Expand,msdyn_fieldservicesetting_Filter,msdyn_fieldservicesetting_Fixed,msdyn_fieldservicesetting_Result,msdyn_fieldservicesetting_FormattedResult>;
  msdyn_product_msdyn_incidenttypeproduct_Product: WebMappingRetrieve<msdyn_incidenttypeproduct_Select,msdyn_incidenttypeproduct_Expand,msdyn_incidenttypeproduct_Filter,msdyn_incidenttypeproduct_Fixed,msdyn_incidenttypeproduct_Result,msdyn_incidenttypeproduct_FormattedResult>;
  msdyn_product_msdyn_incidenttyperecommendationresult_ProductService: WebMappingRetrieve<msdyn_incidenttyperecommendationresult_Select,msdyn_incidenttyperecommendationresult_Expand,msdyn_incidenttyperecommendationresult_Filter,msdyn_incidenttyperecommendationresult_Fixed,msdyn_incidenttyperecommendationresult_Result,msdyn_incidenttyperecommendationresult_FormattedResult>;
  msdyn_product_msdyn_incidenttypeservice_Service: WebMappingRetrieve<msdyn_incidenttypeservice_Select,msdyn_incidenttypeservice_Expand,msdyn_incidenttypeservice_Filter,msdyn_incidenttypeservice_Fixed,msdyn_incidenttypeservice_Result,msdyn_incidenttypeservice_FormattedResult>;
  msdyn_product_msdyn_inventoryadjustmentproduct_Product: WebMappingRetrieve<msdyn_inventoryadjustmentproduct_Select,msdyn_inventoryadjustmentproduct_Expand,msdyn_inventoryadjustmentproduct_Filter,msdyn_inventoryadjustmentproduct_Fixed,msdyn_inventoryadjustmentproduct_Result,msdyn_inventoryadjustmentproduct_FormattedResult>;
  msdyn_product_msdyn_inventoryjournal_Product: WebMappingRetrieve<msdyn_inventoryjournal_Select,msdyn_inventoryjournal_Expand,msdyn_inventoryjournal_Filter,msdyn_inventoryjournal_Fixed,msdyn_inventoryjournal_Result,msdyn_inventoryjournal_FormattedResult>;
  msdyn_product_msdyn_invoicelinetransaction_Product: WebMappingRetrieve<msdyn_invoicelinetransaction_Select,msdyn_invoicelinetransaction_Expand,msdyn_invoicelinetransaction_Filter,msdyn_invoicelinetransaction_Fixed,msdyn_invoicelinetransaction_Result,msdyn_invoicelinetransaction_FormattedResult>;
  msdyn_product_msdyn_journalline_Product: WebMappingRetrieve<msdyn_journalline_Select,msdyn_journalline_Expand,msdyn_journalline_Filter,msdyn_journalline_Fixed,msdyn_journalline_Result,msdyn_journalline_FormattedResult>;
  msdyn_product_msdyn_opportunitylinetransaction_Product: WebMappingRetrieve<msdyn_opportunitylinetransaction_Select,msdyn_opportunitylinetransaction_Expand,msdyn_opportunitylinetransaction_Filter,msdyn_opportunitylinetransaction_Fixed,msdyn_opportunitylinetransaction_Result,msdyn_opportunitylinetransaction_FormattedResult>;
  msdyn_product_msdyn_orderinvoicingproduct_Product: WebMappingRetrieve<msdyn_orderinvoicingproduct_Select,msdyn_orderinvoicingproduct_Expand,msdyn_orderinvoicingproduct_Filter,msdyn_orderinvoicingproduct_Fixed,msdyn_orderinvoicingproduct_Result,msdyn_orderinvoicingproduct_FormattedResult>;
  msdyn_product_msdyn_orderlinetransaction_Product: WebMappingRetrieve<msdyn_orderlinetransaction_Select,msdyn_orderlinetransaction_Expand,msdyn_orderlinetransaction_Filter,msdyn_orderlinetransaction_Fixed,msdyn_orderlinetransaction_Result,msdyn_orderlinetransaction_FormattedResult>;
  msdyn_product_msdyn_productinventory_Product: WebMappingRetrieve<msdyn_productinventory_Select,msdyn_productinventory_Expand,msdyn_productinventory_Filter,msdyn_productinventory_Fixed,msdyn_productinventory_Result,msdyn_productinventory_FormattedResult>;
  msdyn_product_msdyn_purchaseorderproduct_Product: WebMappingRetrieve<msdyn_purchaseorderproduct_Select,msdyn_purchaseorderproduct_Expand,msdyn_purchaseorderproduct_Filter,msdyn_purchaseorderproduct_Fixed,msdyn_purchaseorderproduct_Result,msdyn_purchaseorderproduct_FormattedResult>;
  msdyn_product_msdyn_quotebookingproduct_Product: WebMappingRetrieve<msdyn_quotebookingproduct_Select,msdyn_quotebookingproduct_Expand,msdyn_quotebookingproduct_Filter,msdyn_quotebookingproduct_Fixed,msdyn_quotebookingproduct_Result,msdyn_quotebookingproduct_FormattedResult>;
  msdyn_product_msdyn_quotebookingservice_Service: WebMappingRetrieve<msdyn_quotebookingservice_Select,msdyn_quotebookingservice_Expand,msdyn_quotebookingservice_Filter,msdyn_quotebookingservice_Fixed,msdyn_quotebookingservice_Result,msdyn_quotebookingservice_FormattedResult>;
  msdyn_product_msdyn_quoteinvoicingproduct_Product: WebMappingRetrieve<msdyn_quoteinvoicingproduct_Select,msdyn_quoteinvoicingproduct_Expand,msdyn_quoteinvoicingproduct_Filter,msdyn_quoteinvoicingproduct_Fixed,msdyn_quoteinvoicingproduct_Result,msdyn_quoteinvoicingproduct_FormattedResult>;
  msdyn_product_msdyn_quotelinetransaction_Product: WebMappingRetrieve<msdyn_quotelinetransaction_Select,msdyn_quotelinetransaction_Expand,msdyn_quotelinetransaction_Filter,msdyn_quotelinetransaction_Fixed,msdyn_quotelinetransaction_Result,msdyn_quotelinetransaction_FormattedResult>;
  msdyn_product_msdyn_rmaproduct_Product: WebMappingRetrieve<msdyn_rmaproduct_Select,msdyn_rmaproduct_Expand,msdyn_rmaproduct_Filter,msdyn_rmaproduct_Fixed,msdyn_rmaproduct_Result,msdyn_rmaproduct_FormattedResult>;
  msdyn_product_msdyn_rtvproduct_Product: WebMappingRetrieve<msdyn_rtvproduct_Select,msdyn_rtvproduct_Expand,msdyn_rtvproduct_Filter,msdyn_rtvproduct_Fixed,msdyn_rtvproduct_Result,msdyn_rtvproduct_FormattedResult>;
  msdyn_product_msdyn_workorderproduct_Product: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  msdyn_product_msdyn_workorderservice_Service: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  navigationPropertyNameNotDefined: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  navigationPropertyNameNotDefined1: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  opportunity_products: WebMappingRetrieve<OpportunityProduct_Select,OpportunityProduct_Expand,OpportunityProduct_Filter,OpportunityProduct_Fixed,OpportunityProduct_Result,OpportunityProduct_FormattedResult>;
  product_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  product_ProductSubstitute_productid: WebMappingRetrieve<ProductSubstitute_Select,ProductSubstitute_Expand,ProductSubstitute_Filter,ProductSubstitute_Fixed,ProductSubstitute_Result,ProductSubstitute_FormattedResult>;
  product_ProductSubstitute_substitutedproductid: WebMappingRetrieve<ProductSubstitute_Select,ProductSubstitute_Expand,ProductSubstitute_Filter,ProductSubstitute_Fixed,ProductSubstitute_Result,ProductSubstitute_FormattedResult>;
  product_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  product_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  product_contract_line_items: WebMappingRetrieve<ContractDetail_Select,ContractDetail_Expand,ContractDetail_Filter,ContractDetail_Fixed,ContractDetail_Result,ContractDetail_FormattedResult>;
  product_entitlement_association: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  product_entitlementtemplate_association: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  product_incidents: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  product_invoice_details: WebMappingRetrieve<InvoiceDetail_Select,InvoiceDetail_Expand,InvoiceDetail_Filter,InvoiceDetail_Fixed,InvoiceDetail_Result,InvoiceDetail_FormattedResult>;
  product_order_details: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  product_parent_product: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  product_price_levels: WebMappingRetrieve<ProductPriceLevel_Select,ProductPriceLevel_Expand,ProductPriceLevel_Filter,ProductPriceLevel_Fixed,ProductPriceLevel_Result,ProductPriceLevel_FormattedResult>;
  product_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  product_quote_details: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  productsalesliterature_association: WebMappingRetrieve<SalesLiterature_Select,SalesLiterature_Expand,SalesLiterature_Filter,SalesLiterature_Fixed,SalesLiterature_Result,SalesLiterature_FormattedResult>;
  userentityinstancedata_product: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  products: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
}
interface WebEntitiesRelated {
  products: WebMappingRelated<Product_RelatedOne,Product_RelatedMany>;
}
interface WebEntitiesCUDA {
  products: WebMappingCUDA<Product_Create,Product_Update,Product_Select>;
}
