interface QuoteDetail_Base extends WebEntity {
  baseamount?: number | null;
  baseamount_base?: number | null;
  createdon?: Date | null;
  description?: string | null;
  exchangerate?: number | null;
  extendedamount?: number | null;
  extendedamount_base?: number | null;
  importsequencenumber?: number | null;
  ispriceoverridden?: boolean | null;
  isproductoverridden?: boolean | null;
  lineitemnumber?: number | null;
  manualdiscountamount?: number | null;
  manualdiscountamount_base?: number | null;
  modifiedon?: Date | null;
  msdyn_billingmethod?: msdyn_billingmethod | null;
  msdyn_billingstartdate?: Date | null;
  msdyn_budgetamount?: number | null;
  msdyn_budgetamount_base?: number | null;
  msdyn_costamount?: number | null;
  msdyn_costamount_base?: number | null;
  msdyn_costpriceperunit?: number | null;
  msdyn_costpriceperunit_base?: number | null;
  msdyn_duration?: number | null;
  msdyn_enddate?: Date | null;
  msdyn_estimatedcost?: number | null;
  msdyn_estimatedcost_base?: number | null;
  msdyn_estimatedmargin?: number | null;
  msdyn_estimatedrevenue?: number | null;
  msdyn_estimatedrevenue_base?: number | null;
  msdyn_importdetailsfromagreement?: boolean | null;
  msdyn_includeexpense?: boolean | null;
  msdyn_includefee?: boolean | null;
  msdyn_includematerial?: boolean | null;
  msdyn_includetime?: boolean | null;
  msdyn_linedescription?: string | null;
  msdyn_linetype?: msdyn_linetype | null;
  msdyn_opportunityline?: string | null;
  msdyn_startdate?: Date | null;
  msdyn_taxable?: boolean | null;
  overriddencreatedon?: Date | null;
  parentbundleid?: string | null;
  priceperunit?: number | null;
  priceperunit_base?: number | null;
  pricingerrorcode?: qooi_pricingerrorcode | null;
  productassociationid?: string | null;
  productdescription?: string | null;
  productname?: string | null;
  productnumber?: string | null;
  producttypecode?: qooiproduct_producttype | null;
  propertyconfigurationstatus?: qooiproduct_propertiesconfigurationstatus | null;
  quantity?: number | null;
  quotedetailid?: string | null;
  quotedetailname?: string | null;
  quotestatecode?: quotedetail_quotestatecode | null;
  requestdeliveryby?: Date | null;
  sequencenumber?: number | null;
  shipto_addressid?: string | null;
  shipto_city?: string | null;
  shipto_contactname?: string | null;
  shipto_country?: string | null;
  shipto_fax?: string | null;
  shipto_freighttermscode?: quotedetail_shipto_freighttermscode | null;
  shipto_line1?: string | null;
  shipto_line2?: string | null;
  shipto_line3?: string | null;
  shipto_name?: string | null;
  shipto_postalcode?: string | null;
  shipto_stateorprovince?: string | null;
  shipto_telephone?: string | null;
  skippricecalculation?: qooidetail_skippricecalculation | null;
  tax?: number | null;
  tax_base?: number | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
  volumediscountamount?: number | null;
  volumediscountamount_base?: number | null;
  willcall?: boolean | null;
}
interface QuoteDetail_Relationships {
  QuoteDetail_AsyncOperations?: AsyncOperation_Result[] | null;
  QuoteDetail_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  QuoteDetail_Dynamicpropertyinstance?: DynamicPropertyInstance_Result[] | null;
  QuoteDetail_ProcessSessions?: ProcessSession_Result[] | null;
  QuoteDetail_SyncErrors?: SyncError_Result[] | null;
  msdyn_Agreement?: msdyn_agreement_Result | null;
  msdyn_PriceList?: PriceLevel_Result | null;
  msdyn_Project?: msdyn_project_Result | null;
  msdyn_SalesTaxCode?: msdyn_taxcode_Result | null;
  msdyn_ServiceAccount?: Account_Result | null;
  msdyn_ServiceTerritory?: Territory_Result | null;
  msdyn_quotedetail_msdyn_quotebookingsetup?: msdyn_quotebookingsetup_Result[] | null;
  msdyn_quotedetail_msdyn_quotelineinvoiceschedu?: msdyn_quotelineinvoiceschedule_Result[] | null;
  msdyn_quotedetail_msdyn_quotelineresourcecatego?: msdyn_quotelineresourcecategory_Result[] | null;
  msdyn_quotedetail_msdyn_quotelinescheduleofv?: msdyn_quotelinescheduleofvalue_Result[] | null;
  msdyn_quotedetail_msdyn_quotelinetransaction?: msdyn_quotelinetransaction_Result[] | null;
  msdyn_quotedetail_msdyn_quotelinetransactioncat?: msdyn_quotelinetransactioncategory_Result[] | null;
  msdyn_quotedetail_msdyn_quotelinetransactioncla?: msdyn_quotelinetransactionclassification_Result[] | null;
  msdyn_quotedetail_salesorderdetail?: SalesOrderDetail_Result[] | null;
  parentbundleid_quotedetail?: QuoteDetail_Result | null;
  parentbundleidref_quotedetail?: QuoteDetail_Result | null;
  productassociationid_productassociation?: ProductAssociation_Result | null;
  quotedetail_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  quotedetail_parent_quotedetail?: QuoteDetail_Result[] | null;
  quotedetail_parentref_quotedetail?: QuoteDetail_Result[] | null;
  quotedetail_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  userentityinstancedata_quotedetail?: UserEntityInstanceData_Result[] | null;
}
interface QuoteDetail extends QuoteDetail_Base, QuoteDetail_Relationships {
  msdyn_Agreement_bind$msdyn_agreements?: string | null;
  msdyn_PriceList_bind$pricelevels?: string | null;
  msdyn_Project_bind$msdyn_projects?: string | null;
  msdyn_SalesTaxCode_bind$msdyn_taxcodes?: string | null;
  msdyn_ServiceAccount_bind$accounts?: string | null;
  msdyn_ServiceTerritory_bind$territories?: string | null;
  msdyn_invoicefrequency_bind$msdyn_invoicefrequencies?: string | null;
  parentbundleidref_quotedetail_bind$quotedetails?: string | null;
  productid_bind$products?: string | null;
  quoteid_bind$quotes?: string | null;
  salesrepid_bind$systemusers?: string | null;
  uomid_bind$uoms?: string | null;
}
interface QuoteDetail_Create extends QuoteDetail {
  parentbundleid_quotedetail_bind$quotedetails?: string | null;
  productassociationid_productassociation_bind$productassociations?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface QuoteDetail_Update extends QuoteDetail {
}
interface QuoteDetail_Select {
  baseamount: WebAttribute<QuoteDetail_Select, { baseamount: number | null; transactioncurrencyid_guid: string | null }, { baseamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  baseamount_base: WebAttribute<QuoteDetail_Select, { baseamount_base: number | null; transactioncurrencyid_guid: string | null }, { baseamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  createdby_guid: WebAttribute<QuoteDetail_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<QuoteDetail_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<QuoteDetail_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<QuoteDetail_Select, { description: string | null }, {  }>;
  exchangerate: WebAttribute<QuoteDetail_Select, { exchangerate: number | null }, {  }>;
  extendedamount: WebAttribute<QuoteDetail_Select, { extendedamount: number | null; transactioncurrencyid_guid: string | null }, { extendedamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  extendedamount_base: WebAttribute<QuoteDetail_Select, { extendedamount_base: number | null; transactioncurrencyid_guid: string | null }, { extendedamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  importsequencenumber: WebAttribute<QuoteDetail_Select, { importsequencenumber: number | null }, {  }>;
  ispriceoverridden: WebAttribute<QuoteDetail_Select, { ispriceoverridden: boolean | null }, {  }>;
  isproductoverridden: WebAttribute<QuoteDetail_Select, { isproductoverridden: boolean | null }, {  }>;
  lineitemnumber: WebAttribute<QuoteDetail_Select, { lineitemnumber: number | null }, {  }>;
  manualdiscountamount: WebAttribute<QuoteDetail_Select, { manualdiscountamount: number | null; transactioncurrencyid_guid: string | null }, { manualdiscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  manualdiscountamount_base: WebAttribute<QuoteDetail_Select, { manualdiscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { manualdiscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  modifiedby_guid: WebAttribute<QuoteDetail_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<QuoteDetail_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<QuoteDetail_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_agreement_guid: WebAttribute<QuoteDetail_Select, { msdyn_agreement_guid: string | null }, { msdyn_agreement_formatted?: string }>;
  msdyn_billingmethod: WebAttribute<QuoteDetail_Select, { msdyn_billingmethod: msdyn_billingmethod | null }, { msdyn_billingmethod_formatted?: string }>;
  msdyn_billingstartdate: WebAttribute<QuoteDetail_Select, { msdyn_billingstartdate: Date | null }, { msdyn_billingstartdate_formatted?: string }>;
  msdyn_budgetamount: WebAttribute<QuoteDetail_Select, { msdyn_budgetamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_budgetamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_budgetamount_base: WebAttribute<QuoteDetail_Select, { msdyn_budgetamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_budgetamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costamount: WebAttribute<QuoteDetail_Select, { msdyn_costamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costamount_base: WebAttribute<QuoteDetail_Select, { msdyn_costamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costpriceperunit: WebAttribute<QuoteDetail_Select, { msdyn_costpriceperunit: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costpriceperunit_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costpriceperunit_base: WebAttribute<QuoteDetail_Select, { msdyn_costpriceperunit_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costpriceperunit_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_duration: WebAttribute<QuoteDetail_Select, { msdyn_duration: number | null }, {  }>;
  msdyn_enddate: WebAttribute<QuoteDetail_Select, { msdyn_enddate: Date | null }, { msdyn_enddate_formatted?: string }>;
  msdyn_estimatedcost: WebAttribute<QuoteDetail_Select, { msdyn_estimatedcost: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedcost_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedcost_base: WebAttribute<QuoteDetail_Select, { msdyn_estimatedcost_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedcost_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedmargin: WebAttribute<QuoteDetail_Select, { msdyn_estimatedmargin: number | null }, {  }>;
  msdyn_estimatedrevenue: WebAttribute<QuoteDetail_Select, { msdyn_estimatedrevenue: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedrevenue_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_estimatedrevenue_base: WebAttribute<QuoteDetail_Select, { msdyn_estimatedrevenue_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_estimatedrevenue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_importdetailsfromagreement: WebAttribute<QuoteDetail_Select, { msdyn_importdetailsfromagreement: boolean | null }, {  }>;
  msdyn_includeexpense: WebAttribute<QuoteDetail_Select, { msdyn_includeexpense: boolean | null }, {  }>;
  msdyn_includefee: WebAttribute<QuoteDetail_Select, { msdyn_includefee: boolean | null }, {  }>;
  msdyn_includematerial: WebAttribute<QuoteDetail_Select, { msdyn_includematerial: boolean | null }, {  }>;
  msdyn_includetime: WebAttribute<QuoteDetail_Select, { msdyn_includetime: boolean | null }, {  }>;
  msdyn_invoicefrequency_guid: WebAttribute<QuoteDetail_Select, { msdyn_invoicefrequency_guid: string | null }, { msdyn_invoicefrequency_formatted?: string }>;
  msdyn_linedescription: WebAttribute<QuoteDetail_Select, { msdyn_linedescription: string | null }, {  }>;
  msdyn_linetype: WebAttribute<QuoteDetail_Select, { msdyn_linetype: msdyn_linetype | null }, { msdyn_linetype_formatted?: string }>;
  msdyn_opportunityline: WebAttribute<QuoteDetail_Select, { msdyn_opportunityline: string | null }, {  }>;
  msdyn_pricelist_guid: WebAttribute<QuoteDetail_Select, { msdyn_pricelist_guid: string | null }, { msdyn_pricelist_formatted?: string }>;
  msdyn_project_guid: WebAttribute<QuoteDetail_Select, { msdyn_project_guid: string | null }, { msdyn_project_formatted?: string }>;
  msdyn_salestaxcode_guid: WebAttribute<QuoteDetail_Select, { msdyn_salestaxcode_guid: string | null }, { msdyn_salestaxcode_formatted?: string }>;
  msdyn_serviceaccount_guid: WebAttribute<QuoteDetail_Select, { msdyn_serviceaccount_guid: string | null }, { msdyn_serviceaccount_formatted?: string }>;
  msdyn_serviceterritory_guid: WebAttribute<QuoteDetail_Select, { msdyn_serviceterritory_guid: string | null }, { msdyn_serviceterritory_formatted?: string }>;
  msdyn_startdate: WebAttribute<QuoteDetail_Select, { msdyn_startdate: Date | null }, { msdyn_startdate_formatted?: string }>;
  msdyn_taxable: WebAttribute<QuoteDetail_Select, { msdyn_taxable: boolean | null }, {  }>;
  overriddencreatedon: WebAttribute<QuoteDetail_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<QuoteDetail_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<QuoteDetail_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<QuoteDetail_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<QuoteDetail_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  parentbundleid: WebAttribute<QuoteDetail_Select, { parentbundleid: string | null }, {  }>;
  parentbundleidref_guid: WebAttribute<QuoteDetail_Select, { parentbundleidref_guid: string | null }, { parentbundleidref_formatted?: string }>;
  priceperunit: WebAttribute<QuoteDetail_Select, { priceperunit: number | null; transactioncurrencyid_guid: string | null }, { priceperunit_formatted?: string; transactioncurrencyid_formatted?: string }>;
  priceperunit_base: WebAttribute<QuoteDetail_Select, { priceperunit_base: number | null; transactioncurrencyid_guid: string | null }, { priceperunit_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  pricingerrorcode: WebAttribute<QuoteDetail_Select, { pricingerrorcode: qooi_pricingerrorcode | null }, { pricingerrorcode_formatted?: string }>;
  productassociationid: WebAttribute<QuoteDetail_Select, { productassociationid: string | null }, {  }>;
  productdescription: WebAttribute<QuoteDetail_Select, { productdescription: string | null }, {  }>;
  productid_guid: WebAttribute<QuoteDetail_Select, { productid_guid: string | null }, { productid_formatted?: string }>;
  productname: WebAttribute<QuoteDetail_Select, { productname: string | null }, {  }>;
  productnumber: WebAttribute<QuoteDetail_Select, { productnumber: string | null }, {  }>;
  producttypecode: WebAttribute<QuoteDetail_Select, { producttypecode: qooiproduct_producttype | null }, { producttypecode_formatted?: string }>;
  propertyconfigurationstatus: WebAttribute<QuoteDetail_Select, { propertyconfigurationstatus: qooiproduct_propertiesconfigurationstatus | null }, { propertyconfigurationstatus_formatted?: string }>;
  quantity: WebAttribute<QuoteDetail_Select, { quantity: number | null }, {  }>;
  quotedetailid: WebAttribute<QuoteDetail_Select, { quotedetailid: string | null }, {  }>;
  quotedetailname: WebAttribute<QuoteDetail_Select, { quotedetailname: string | null }, {  }>;
  quoteid_guid: WebAttribute<QuoteDetail_Select, { quoteid_guid: string | null }, { quoteid_formatted?: string }>;
  quotestatecode: WebAttribute<QuoteDetail_Select, { quotestatecode: quotedetail_quotestatecode | null }, { quotestatecode_formatted?: string }>;
  requestdeliveryby: WebAttribute<QuoteDetail_Select, { requestdeliveryby: Date | null }, { requestdeliveryby_formatted?: string }>;
  salesrepid_guid: WebAttribute<QuoteDetail_Select, { salesrepid_guid: string | null }, { salesrepid_formatted?: string }>;
  sequencenumber: WebAttribute<QuoteDetail_Select, { sequencenumber: number | null }, {  }>;
  shipto_addressid: WebAttribute<QuoteDetail_Select, { shipto_addressid: string | null }, {  }>;
  shipto_city: WebAttribute<QuoteDetail_Select, { shipto_city: string | null }, {  }>;
  shipto_contactname: WebAttribute<QuoteDetail_Select, { shipto_contactname: string | null }, {  }>;
  shipto_country: WebAttribute<QuoteDetail_Select, { shipto_country: string | null }, {  }>;
  shipto_fax: WebAttribute<QuoteDetail_Select, { shipto_fax: string | null }, {  }>;
  shipto_freighttermscode: WebAttribute<QuoteDetail_Select, { shipto_freighttermscode: quotedetail_shipto_freighttermscode | null }, { shipto_freighttermscode_formatted?: string }>;
  shipto_line1: WebAttribute<QuoteDetail_Select, { shipto_line1: string | null }, {  }>;
  shipto_line2: WebAttribute<QuoteDetail_Select, { shipto_line2: string | null }, {  }>;
  shipto_line3: WebAttribute<QuoteDetail_Select, { shipto_line3: string | null }, {  }>;
  shipto_name: WebAttribute<QuoteDetail_Select, { shipto_name: string | null }, {  }>;
  shipto_postalcode: WebAttribute<QuoteDetail_Select, { shipto_postalcode: string | null }, {  }>;
  shipto_stateorprovince: WebAttribute<QuoteDetail_Select, { shipto_stateorprovince: string | null }, {  }>;
  shipto_telephone: WebAttribute<QuoteDetail_Select, { shipto_telephone: string | null }, {  }>;
  skippricecalculation: WebAttribute<QuoteDetail_Select, { skippricecalculation: qooidetail_skippricecalculation | null }, { skippricecalculation_formatted?: string }>;
  tax: WebAttribute<QuoteDetail_Select, { tax: number | null; transactioncurrencyid_guid: string | null }, { tax_formatted?: string; transactioncurrencyid_formatted?: string }>;
  tax_base: WebAttribute<QuoteDetail_Select, { tax_base: number | null; transactioncurrencyid_guid: string | null }, { tax_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<QuoteDetail_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<QuoteDetail_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  uomid_guid: WebAttribute<QuoteDetail_Select, { uomid_guid: string | null }, { uomid_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<QuoteDetail_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<QuoteDetail_Select, { versionnumber: number | null }, {  }>;
  volumediscountamount: WebAttribute<QuoteDetail_Select, { volumediscountamount: number | null; transactioncurrencyid_guid: string | null }, { volumediscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  volumediscountamount_base: WebAttribute<QuoteDetail_Select, { volumediscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { volumediscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  willcall: WebAttribute<QuoteDetail_Select, { willcall: boolean | null }, {  }>;
}
interface QuoteDetail_Filter {
  baseamount: number;
  baseamount_base: number;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  exchangerate: any;
  extendedamount: number;
  extendedamount_base: number;
  importsequencenumber: number;
  ispriceoverridden: boolean;
  isproductoverridden: boolean;
  lineitemnumber: number;
  manualdiscountamount: number;
  manualdiscountamount_base: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_agreement_guid: XQW.Guid;
  msdyn_billingmethod: msdyn_billingmethod;
  msdyn_billingstartdate: Date;
  msdyn_budgetamount: number;
  msdyn_budgetamount_base: number;
  msdyn_costamount: number;
  msdyn_costamount_base: number;
  msdyn_costpriceperunit: number;
  msdyn_costpriceperunit_base: number;
  msdyn_duration: number;
  msdyn_enddate: Date;
  msdyn_estimatedcost: number;
  msdyn_estimatedcost_base: number;
  msdyn_estimatedmargin: any;
  msdyn_estimatedrevenue: number;
  msdyn_estimatedrevenue_base: number;
  msdyn_importdetailsfromagreement: boolean;
  msdyn_includeexpense: boolean;
  msdyn_includefee: boolean;
  msdyn_includematerial: boolean;
  msdyn_includetime: boolean;
  msdyn_invoicefrequency_guid: XQW.Guid;
  msdyn_linedescription: string;
  msdyn_linetype: msdyn_linetype;
  msdyn_opportunityline: string;
  msdyn_pricelist_guid: XQW.Guid;
  msdyn_project_guid: XQW.Guid;
  msdyn_salestaxcode_guid: XQW.Guid;
  msdyn_serviceaccount_guid: XQW.Guid;
  msdyn_serviceterritory_guid: XQW.Guid;
  msdyn_startdate: Date;
  msdyn_taxable: boolean;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  parentbundleid: XQW.Guid;
  parentbundleidref_guid: XQW.Guid;
  priceperunit: number;
  priceperunit_base: number;
  pricingerrorcode: qooi_pricingerrorcode;
  productassociationid: XQW.Guid;
  productdescription: string;
  productid_guid: XQW.Guid;
  productname: string;
  productnumber: string;
  producttypecode: qooiproduct_producttype;
  propertyconfigurationstatus: qooiproduct_propertiesconfigurationstatus;
  quantity: any;
  quotedetailid: XQW.Guid;
  quotedetailname: string;
  quoteid_guid: XQW.Guid;
  quotestatecode: quotedetail_quotestatecode;
  requestdeliveryby: Date;
  salesrepid_guid: XQW.Guid;
  sequencenumber: number;
  shipto_addressid: XQW.Guid;
  shipto_city: string;
  shipto_contactname: string;
  shipto_country: string;
  shipto_fax: string;
  shipto_freighttermscode: quotedetail_shipto_freighttermscode;
  shipto_line1: string;
  shipto_line2: string;
  shipto_line3: string;
  shipto_name: string;
  shipto_postalcode: string;
  shipto_stateorprovince: string;
  shipto_telephone: string;
  skippricecalculation: qooidetail_skippricecalculation;
  tax: number;
  tax_base: number;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  uomid_guid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
  volumediscountamount: number;
  volumediscountamount_base: number;
  willcall: boolean;
}
interface QuoteDetail_Expand {
  QuoteDetail_AsyncOperations: WebExpand<QuoteDetail_Expand, AsyncOperation_Select, AsyncOperation_Filter, { QuoteDetail_AsyncOperations: AsyncOperation_Result[] }>;
  QuoteDetail_BulkDeleteFailures: WebExpand<QuoteDetail_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { QuoteDetail_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  QuoteDetail_Dynamicpropertyinstance: WebExpand<QuoteDetail_Expand, DynamicPropertyInstance_Select, DynamicPropertyInstance_Filter, { QuoteDetail_Dynamicpropertyinstance: DynamicPropertyInstance_Result[] }>;
  QuoteDetail_ProcessSessions: WebExpand<QuoteDetail_Expand, ProcessSession_Select, ProcessSession_Filter, { QuoteDetail_ProcessSessions: ProcessSession_Result[] }>;
  QuoteDetail_SyncErrors: WebExpand<QuoteDetail_Expand, SyncError_Select, SyncError_Filter, { QuoteDetail_SyncErrors: SyncError_Result[] }>;
  createdby: WebExpand<QuoteDetail_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<QuoteDetail_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<QuoteDetail_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<QuoteDetail_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_Agreement: WebExpand<QuoteDetail_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { msdyn_Agreement: msdyn_agreement_Result }>;
  msdyn_PriceList: WebExpand<QuoteDetail_Expand, PriceLevel_Select, PriceLevel_Filter, { msdyn_PriceList: PriceLevel_Result }>;
  msdyn_Project: WebExpand<QuoteDetail_Expand, msdyn_project_Select, msdyn_project_Filter, { msdyn_Project: msdyn_project_Result }>;
  msdyn_SalesTaxCode: WebExpand<QuoteDetail_Expand, msdyn_taxcode_Select, msdyn_taxcode_Filter, { msdyn_SalesTaxCode: msdyn_taxcode_Result }>;
  msdyn_ServiceAccount: WebExpand<QuoteDetail_Expand, Account_Select, Account_Filter, { msdyn_ServiceAccount: Account_Result }>;
  msdyn_ServiceTerritory: WebExpand<QuoteDetail_Expand, Territory_Select, Territory_Filter, { msdyn_ServiceTerritory: Territory_Result }>;
  msdyn_invoicefrequency: WebExpand<QuoteDetail_Expand, msdyn_invoicefrequency_Select, msdyn_invoicefrequency_Filter, { msdyn_invoicefrequency: msdyn_invoicefrequency_Result }>;
  msdyn_quotedetail_msdyn_quotebookingsetup: WebExpand<QuoteDetail_Expand, msdyn_quotebookingsetup_Select, msdyn_quotebookingsetup_Filter, { msdyn_quotedetail_msdyn_quotebookingsetup: msdyn_quotebookingsetup_Result[] }>;
  msdyn_quotedetail_msdyn_quotelineinvoiceschedu: WebExpand<QuoteDetail_Expand, msdyn_quotelineinvoiceschedule_Select, msdyn_quotelineinvoiceschedule_Filter, { msdyn_quotedetail_msdyn_quotelineinvoiceschedu: msdyn_quotelineinvoiceschedule_Result[] }>;
  msdyn_quotedetail_msdyn_quotelineresourcecatego: WebExpand<QuoteDetail_Expand, msdyn_quotelineresourcecategory_Select, msdyn_quotelineresourcecategory_Filter, { msdyn_quotedetail_msdyn_quotelineresourcecatego: msdyn_quotelineresourcecategory_Result[] }>;
  msdyn_quotedetail_msdyn_quotelinescheduleofv: WebExpand<QuoteDetail_Expand, msdyn_quotelinescheduleofvalue_Select, msdyn_quotelinescheduleofvalue_Filter, { msdyn_quotedetail_msdyn_quotelinescheduleofv: msdyn_quotelinescheduleofvalue_Result[] }>;
  msdyn_quotedetail_msdyn_quotelinetransaction: WebExpand<QuoteDetail_Expand, msdyn_quotelinetransaction_Select, msdyn_quotelinetransaction_Filter, { msdyn_quotedetail_msdyn_quotelinetransaction: msdyn_quotelinetransaction_Result[] }>;
  msdyn_quotedetail_msdyn_quotelinetransactioncat: WebExpand<QuoteDetail_Expand, msdyn_quotelinetransactioncategory_Select, msdyn_quotelinetransactioncategory_Filter, { msdyn_quotedetail_msdyn_quotelinetransactioncat: msdyn_quotelinetransactioncategory_Result[] }>;
  msdyn_quotedetail_msdyn_quotelinetransactioncla: WebExpand<QuoteDetail_Expand, msdyn_quotelinetransactionclassification_Select, msdyn_quotelinetransactionclassification_Filter, { msdyn_quotedetail_msdyn_quotelinetransactioncla: msdyn_quotelinetransactionclassification_Result[] }>;
  msdyn_quotedetail_salesorderdetail: WebExpand<QuoteDetail_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { msdyn_quotedetail_salesorderdetail: SalesOrderDetail_Result[] }>;
  owningteam: WebExpand<QuoteDetail_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<QuoteDetail_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  parentbundleid_quotedetail: WebExpand<QuoteDetail_Expand, QuoteDetail_Select, QuoteDetail_Filter, { parentbundleid_quotedetail: QuoteDetail_Result }>;
  parentbundleidref_quotedetail: WebExpand<QuoteDetail_Expand, QuoteDetail_Select, QuoteDetail_Filter, { parentbundleidref_quotedetail: QuoteDetail_Result }>;
  productassociationid_productassociation: WebExpand<QuoteDetail_Expand, ProductAssociation_Select, ProductAssociation_Filter, { productassociationid_productassociation: ProductAssociation_Result }>;
  productid: WebExpand<QuoteDetail_Expand, Product_Select, Product_Filter, { productid: Product_Result }>;
  quotedetail_MailboxTrackingFolders: WebExpand<QuoteDetail_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { quotedetail_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  quotedetail_parent_quotedetail: WebExpand<QuoteDetail_Expand, QuoteDetail_Select, QuoteDetail_Filter, { quotedetail_parent_quotedetail: QuoteDetail_Result[] }>;
  quotedetail_parentref_quotedetail: WebExpand<QuoteDetail_Expand, QuoteDetail_Select, QuoteDetail_Filter, { quotedetail_parentref_quotedetail: QuoteDetail_Result[] }>;
  quotedetail_principalobjectattributeaccess: WebExpand<QuoteDetail_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { quotedetail_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  quoteid: WebExpand<QuoteDetail_Expand, Quote_Select, Quote_Filter, { quoteid: Quote_Result }>;
  salesrepid: WebExpand<QuoteDetail_Expand, SystemUser_Select, SystemUser_Filter, { salesrepid: SystemUser_Result }>;
  transactioncurrencyid: WebExpand<QuoteDetail_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  uomid: WebExpand<QuoteDetail_Expand, UoM_Select, UoM_Filter, { uomid: UoM_Result }>;
  userentityinstancedata_quotedetail: WebExpand<QuoteDetail_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_quotedetail: UserEntityInstanceData_Result[] }>;
}
interface QuoteDetail_FormattedResult {
  baseamount_base_formatted?: string;
  baseamount_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  extendedamount_base_formatted?: string;
  extendedamount_formatted?: string;
  manualdiscountamount_base_formatted?: string;
  manualdiscountamount_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_agreement_formatted?: string;
  msdyn_billingmethod_formatted?: string;
  msdyn_billingstartdate_formatted?: string;
  msdyn_budgetamount_base_formatted?: string;
  msdyn_budgetamount_formatted?: string;
  msdyn_costamount_base_formatted?: string;
  msdyn_costamount_formatted?: string;
  msdyn_costpriceperunit_base_formatted?: string;
  msdyn_costpriceperunit_formatted?: string;
  msdyn_enddate_formatted?: string;
  msdyn_estimatedcost_base_formatted?: string;
  msdyn_estimatedcost_formatted?: string;
  msdyn_estimatedrevenue_base_formatted?: string;
  msdyn_estimatedrevenue_formatted?: string;
  msdyn_invoicefrequency_formatted?: string;
  msdyn_linetype_formatted?: string;
  msdyn_pricelist_formatted?: string;
  msdyn_project_formatted?: string;
  msdyn_salestaxcode_formatted?: string;
  msdyn_serviceaccount_formatted?: string;
  msdyn_serviceterritory_formatted?: string;
  msdyn_startdate_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  parentbundleidref_formatted?: string;
  priceperunit_base_formatted?: string;
  priceperunit_formatted?: string;
  pricingerrorcode_formatted?: string;
  productid_formatted?: string;
  producttypecode_formatted?: string;
  propertyconfigurationstatus_formatted?: string;
  quoteid_formatted?: string;
  quotestatecode_formatted?: string;
  requestdeliveryby_formatted?: string;
  salesrepid_formatted?: string;
  shipto_freighttermscode_formatted?: string;
  skippricecalculation_formatted?: string;
  tax_base_formatted?: string;
  tax_formatted?: string;
  transactioncurrencyid_formatted?: string;
  uomid_formatted?: string;
  volumediscountamount_base_formatted?: string;
  volumediscountamount_formatted?: string;
}
interface QuoteDetail_Result extends QuoteDetail_Base, QuoteDetail_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_agreement_guid: string | null;
  msdyn_invoicefrequency_guid: string | null;
  msdyn_pricelist_guid: string | null;
  msdyn_project_guid: string | null;
  msdyn_salestaxcode_guid: string | null;
  msdyn_serviceaccount_guid: string | null;
  msdyn_serviceterritory_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  parentbundleidref_guid: string | null;
  productid_guid: string | null;
  quoteid_guid: string | null;
  salesrepid_guid: string | null;
  transactioncurrencyid_guid: string | null;
  uomid_guid: string | null;
}
interface QuoteDetail_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_Agreement: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  msdyn_PriceList: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  msdyn_Project: WebMappingRetrieve<msdyn_project_Select,msdyn_project_Expand,msdyn_project_Filter,msdyn_project_Fixed,msdyn_project_Result,msdyn_project_FormattedResult>;
  msdyn_SalesTaxCode: WebMappingRetrieve<msdyn_taxcode_Select,msdyn_taxcode_Expand,msdyn_taxcode_Filter,msdyn_taxcode_Fixed,msdyn_taxcode_Result,msdyn_taxcode_FormattedResult>;
  msdyn_ServiceAccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  msdyn_ServiceTerritory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  msdyn_invoicefrequency: WebMappingRetrieve<msdyn_invoicefrequency_Select,msdyn_invoicefrequency_Expand,msdyn_invoicefrequency_Filter,msdyn_invoicefrequency_Fixed,msdyn_invoicefrequency_Result,msdyn_invoicefrequency_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  parentbundleid_quotedetail: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  parentbundleidref_quotedetail: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  productassociationid_productassociation: WebMappingRetrieve<ProductAssociation_Select,ProductAssociation_Expand,ProductAssociation_Filter,ProductAssociation_Fixed,ProductAssociation_Result,ProductAssociation_FormattedResult>;
  productid: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  quoteid: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  salesrepid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
  uomid: WebMappingRetrieve<UoM_Select,UoM_Expand,UoM_Filter,UoM_Fixed,UoM_Result,UoM_FormattedResult>;
}
interface QuoteDetail_RelatedMany {
  QuoteDetail_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  QuoteDetail_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  QuoteDetail_Dynamicpropertyinstance: WebMappingRetrieve<DynamicPropertyInstance_Select,DynamicPropertyInstance_Expand,DynamicPropertyInstance_Filter,DynamicPropertyInstance_Fixed,DynamicPropertyInstance_Result,DynamicPropertyInstance_FormattedResult>;
  QuoteDetail_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  QuoteDetail_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_quotedetail_msdyn_quotebookingsetup: WebMappingRetrieve<msdyn_quotebookingsetup_Select,msdyn_quotebookingsetup_Expand,msdyn_quotebookingsetup_Filter,msdyn_quotebookingsetup_Fixed,msdyn_quotebookingsetup_Result,msdyn_quotebookingsetup_FormattedResult>;
  msdyn_quotedetail_msdyn_quotelineinvoiceschedu: WebMappingRetrieve<msdyn_quotelineinvoiceschedule_Select,msdyn_quotelineinvoiceschedule_Expand,msdyn_quotelineinvoiceschedule_Filter,msdyn_quotelineinvoiceschedule_Fixed,msdyn_quotelineinvoiceschedule_Result,msdyn_quotelineinvoiceschedule_FormattedResult>;
  msdyn_quotedetail_msdyn_quotelineresourcecatego: WebMappingRetrieve<msdyn_quotelineresourcecategory_Select,msdyn_quotelineresourcecategory_Expand,msdyn_quotelineresourcecategory_Filter,msdyn_quotelineresourcecategory_Fixed,msdyn_quotelineresourcecategory_Result,msdyn_quotelineresourcecategory_FormattedResult>;
  msdyn_quotedetail_msdyn_quotelinescheduleofv: WebMappingRetrieve<msdyn_quotelinescheduleofvalue_Select,msdyn_quotelinescheduleofvalue_Expand,msdyn_quotelinescheduleofvalue_Filter,msdyn_quotelinescheduleofvalue_Fixed,msdyn_quotelinescheduleofvalue_Result,msdyn_quotelinescheduleofvalue_FormattedResult>;
  msdyn_quotedetail_msdyn_quotelinetransaction: WebMappingRetrieve<msdyn_quotelinetransaction_Select,msdyn_quotelinetransaction_Expand,msdyn_quotelinetransaction_Filter,msdyn_quotelinetransaction_Fixed,msdyn_quotelinetransaction_Result,msdyn_quotelinetransaction_FormattedResult>;
  msdyn_quotedetail_msdyn_quotelinetransactioncat: WebMappingRetrieve<msdyn_quotelinetransactioncategory_Select,msdyn_quotelinetransactioncategory_Expand,msdyn_quotelinetransactioncategory_Filter,msdyn_quotelinetransactioncategory_Fixed,msdyn_quotelinetransactioncategory_Result,msdyn_quotelinetransactioncategory_FormattedResult>;
  msdyn_quotedetail_msdyn_quotelinetransactioncla: WebMappingRetrieve<msdyn_quotelinetransactionclassification_Select,msdyn_quotelinetransactionclassification_Expand,msdyn_quotelinetransactionclassification_Filter,msdyn_quotelinetransactionclassification_Fixed,msdyn_quotelinetransactionclassification_Result,msdyn_quotelinetransactionclassification_FormattedResult>;
  msdyn_quotedetail_salesorderdetail: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  quotedetail_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  quotedetail_parent_quotedetail: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  quotedetail_parentref_quotedetail: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  quotedetail_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  userentityinstancedata_quotedetail: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  quotedetails: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
}
interface WebEntitiesRelated {
  quotedetails: WebMappingRelated<QuoteDetail_RelatedOne,QuoteDetail_RelatedMany>;
}
interface WebEntitiesCUDA {
  quotedetails: WebMappingCUDA<QuoteDetail_Create,QuoteDetail_Update,QuoteDetail_Select>;
}
