interface SalesOrderDetail_Base extends WebEntity {
  baseamount?: number | null;
  baseamount_base?: number | null;
  createdon?: Date | null;
  description?: string | null;
  exchangerate?: number | null;
  extendedamount?: number | null;
  extendedamount_base?: number | null;
  importsequencenumber?: number | null;
  iscopied?: boolean | null;
  ispriceoverridden?: boolean | null;
  isproductoverridden?: boolean | null;
  lineitemnumber?: number | null;
  manualdiscountamount?: number | null;
  manualdiscountamount_base?: number | null;
  modifiedon?: Date | null;
  msdyn_billingmethod?: msdyn_billingmethod | null;
  msdyn_billingstartdate?: Date | null;
  msdyn_billingstatus?: msdyn_billingstatus | null;
  msdyn_budgetamount?: number | null;
  msdyn_budgetamount_base?: number | null;
  msdyn_costamount?: number | null;
  msdyn_costamount_base?: number | null;
  msdyn_costpriceperunit?: number | null;
  msdyn_costpriceperunit_base?: number | null;
  msdyn_includeexpense?: boolean | null;
  msdyn_includefee?: boolean | null;
  msdyn_includematerial?: boolean | null;
  msdyn_includetime?: boolean | null;
  msdyn_linetype?: msdyn_linetype | null;
  msdyn_quoteline?: string | null;
  overriddencreatedon?: Date | null;
  parentbundleid?: string | null;
  priceperunit?: number | null;
  priceperunit_base?: number | null;
  pricingerrorcode?: qooi_pricingerrorcode | null;
  productassociationid?: string | null;
  productdescription?: string | null;
  productname?: string | null;
  productnumber?: string | null;
  producttypecode?: qooiproduct_producttype | null;
  propertyconfigurationstatus?: qooiproduct_propertiesconfigurationstatus | null;
  quantity?: number | null;
  quantitybackordered?: number | null;
  quantitycancelled?: number | null;
  quantityshipped?: number | null;
  requestdeliveryby?: Date | null;
  salesorderdetailid?: string | null;
  salesorderdetailname?: string | null;
  salesorderispricelocked?: boolean | null;
  salesorderstatecode?: salesorderdetail_salesorderstatecode | null;
  sequencenumber?: number | null;
  shipto_addressid?: string | null;
  shipto_city?: string | null;
  shipto_contactname?: string | null;
  shipto_country?: string | null;
  shipto_fax?: string | null;
  shipto_freighttermscode?: salesorderdetail_shipto_freighttermscode | null;
  shipto_line1?: string | null;
  shipto_line2?: string | null;
  shipto_line3?: string | null;
  shipto_name?: string | null;
  shipto_postalcode?: string | null;
  shipto_stateorprovince?: string | null;
  shipto_telephone?: string | null;
  skippricecalculation?: qooidetail_skippricecalculation | null;
  tax?: number | null;
  tax_base?: number | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
  volumediscountamount?: number | null;
  volumediscountamount_base?: number | null;
  willcall?: boolean | null;
}
interface SalesOrderDetail_Relationships {
  QuoteDetailId?: QuoteDetail_Result | null;
  SalesOrderDetail_AsyncOperations?: AsyncOperation_Result[] | null;
  SalesOrderDetail_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  SalesOrderDetail_Dynamicpropertyinstance?: DynamicPropertyInstance_Result[] | null;
  SalesOrderDetail_ProcessSessions?: ProcessSession_Result[] | null;
  SalesOrderDetail_SyncErrors?: SyncError_Result[] | null;
  msdyn_Project?: msdyn_project_Result | null;
  msdyn_salesorderdetail_invoicedetail?: InvoiceDetail_Result[] | null;
  msdyn_salesorderdetail_msdyn_actual?: msdyn_actual_Result[] | null;
  msdyn_salesorderdetail_msdyn_contractlineinvoic?: msdyn_contractlineinvoiceschedule_Result[] | null;
  msdyn_salesorderdetail_msdyn_contractlineschedu?: msdyn_contractlinescheduleofvalue_Result[] | null;
  msdyn_salesorderdetail_msdyn_contractperformance_ContractLineId?: msdyn_contractperformance_Result[] | null;
  msdyn_salesorderdetail_msdyn_fact?: msdyn_fact_Result[] | null;
  msdyn_salesorderdetail_msdyn_invoicelinetransac?: msdyn_invoicelinetransaction_Result[] | null;
  msdyn_salesorderdetail_msdyn_journalline?: msdyn_journalline_Result[] | null;
  msdyn_salesorderdetail_msdyn_orderlineresourcec?: msdyn_orderlineresourcecategory_Result[] | null;
  msdyn_salesorderdetail_msdyn_orderlinetransacti?: msdyn_orderlinetransaction_Result[] | null;
  msdyn_salesorderdetail_msdyn_orderlinetranscat?: msdyn_orderlinetransactioncategory_Result[] | null;
  msdyn_salesorderdetail_msdyn_orderlinetransclas?: msdyn_orderlinetransactionclassification_Result[] | null;
  parentbundleid_salesorderdetail?: SalesOrderDetail_Result | null;
  parentbundleidref_salesorderdetail?: SalesOrderDetail_Result | null;
  productassociationid_productassociation?: ProductAssociation_Result | null;
  salesorderdetail_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  salesorderdetail_parent_salesorderdetail?: SalesOrderDetail_Result[] | null;
  salesorderdetail_parentref_salesorderdetail?: SalesOrderDetail_Result[] | null;
  salesorderdetail_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  userentityinstancedata_salesorderdetail?: UserEntityInstanceData_Result[] | null;
}
interface SalesOrderDetail extends SalesOrderDetail_Base, SalesOrderDetail_Relationships {
  QuoteDetailId_bind$quotedetails?: string | null;
  msdyn_Project_bind$msdyn_projects?: string | null;
  msdyn_agreement_bind$msdyn_agreements?: string | null;
  msdyn_invoicefrequency_bind$msdyn_invoicefrequencies?: string | null;
  parentbundleidref_salesorderdetail_bind$salesorderdetails?: string | null;
  productid_bind$products?: string | null;
  salesorderid_bind$salesorders?: string | null;
  salesrepid_bind$systemusers?: string | null;
  uomid_bind$uoms?: string | null;
}
interface SalesOrderDetail_Create extends SalesOrderDetail {
  parentbundleid_salesorderdetail_bind$salesorderdetails?: string | null;
  productassociationid_productassociation_bind$productassociations?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface SalesOrderDetail_Update extends SalesOrderDetail {
}
interface SalesOrderDetail_Select {
  baseamount: WebAttribute<SalesOrderDetail_Select, { baseamount: number | null; transactioncurrencyid_guid: string | null }, { baseamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  baseamount_base: WebAttribute<SalesOrderDetail_Select, { baseamount_base: number | null; transactioncurrencyid_guid: string | null }, { baseamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  createdby_guid: WebAttribute<SalesOrderDetail_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<SalesOrderDetail_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<SalesOrderDetail_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<SalesOrderDetail_Select, { description: string | null }, {  }>;
  exchangerate: WebAttribute<SalesOrderDetail_Select, { exchangerate: number | null }, {  }>;
  extendedamount: WebAttribute<SalesOrderDetail_Select, { extendedamount: number | null; transactioncurrencyid_guid: string | null }, { extendedamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  extendedamount_base: WebAttribute<SalesOrderDetail_Select, { extendedamount_base: number | null; transactioncurrencyid_guid: string | null }, { extendedamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  importsequencenumber: WebAttribute<SalesOrderDetail_Select, { importsequencenumber: number | null }, {  }>;
  iscopied: WebAttribute<SalesOrderDetail_Select, { iscopied: boolean | null }, {  }>;
  ispriceoverridden: WebAttribute<SalesOrderDetail_Select, { ispriceoverridden: boolean | null }, {  }>;
  isproductoverridden: WebAttribute<SalesOrderDetail_Select, { isproductoverridden: boolean | null }, {  }>;
  lineitemnumber: WebAttribute<SalesOrderDetail_Select, { lineitemnumber: number | null }, {  }>;
  manualdiscountamount: WebAttribute<SalesOrderDetail_Select, { manualdiscountamount: number | null; transactioncurrencyid_guid: string | null }, { manualdiscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  manualdiscountamount_base: WebAttribute<SalesOrderDetail_Select, { manualdiscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { manualdiscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  modifiedby_guid: WebAttribute<SalesOrderDetail_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<SalesOrderDetail_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<SalesOrderDetail_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyn_agreement_guid: WebAttribute<SalesOrderDetail_Select, { msdyn_agreement_guid: string | null }, { msdyn_agreement_formatted?: string }>;
  msdyn_billingmethod: WebAttribute<SalesOrderDetail_Select, { msdyn_billingmethod: msdyn_billingmethod | null }, { msdyn_billingmethod_formatted?: string }>;
  msdyn_billingstartdate: WebAttribute<SalesOrderDetail_Select, { msdyn_billingstartdate: Date | null }, { msdyn_billingstartdate_formatted?: string }>;
  msdyn_billingstatus: WebAttribute<SalesOrderDetail_Select, { msdyn_billingstatus: msdyn_billingstatus | null }, { msdyn_billingstatus_formatted?: string }>;
  msdyn_budgetamount: WebAttribute<SalesOrderDetail_Select, { msdyn_budgetamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_budgetamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_budgetamount_base: WebAttribute<SalesOrderDetail_Select, { msdyn_budgetamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_budgetamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costamount: WebAttribute<SalesOrderDetail_Select, { msdyn_costamount: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costamount_base: WebAttribute<SalesOrderDetail_Select, { msdyn_costamount_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costpriceperunit: WebAttribute<SalesOrderDetail_Select, { msdyn_costpriceperunit: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costpriceperunit_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_costpriceperunit_base: WebAttribute<SalesOrderDetail_Select, { msdyn_costpriceperunit_base: number | null; transactioncurrencyid_guid: string | null }, { msdyn_costpriceperunit_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  msdyn_includeexpense: WebAttribute<SalesOrderDetail_Select, { msdyn_includeexpense: boolean | null }, {  }>;
  msdyn_includefee: WebAttribute<SalesOrderDetail_Select, { msdyn_includefee: boolean | null }, {  }>;
  msdyn_includematerial: WebAttribute<SalesOrderDetail_Select, { msdyn_includematerial: boolean | null }, {  }>;
  msdyn_includetime: WebAttribute<SalesOrderDetail_Select, { msdyn_includetime: boolean | null }, {  }>;
  msdyn_invoicefrequency_guid: WebAttribute<SalesOrderDetail_Select, { msdyn_invoicefrequency_guid: string | null }, { msdyn_invoicefrequency_formatted?: string }>;
  msdyn_linetype: WebAttribute<SalesOrderDetail_Select, { msdyn_linetype: msdyn_linetype | null }, { msdyn_linetype_formatted?: string }>;
  msdyn_project_guid: WebAttribute<SalesOrderDetail_Select, { msdyn_project_guid: string | null }, { msdyn_project_formatted?: string }>;
  msdyn_quoteline: WebAttribute<SalesOrderDetail_Select, { msdyn_quoteline: string | null }, {  }>;
  overriddencreatedon: WebAttribute<SalesOrderDetail_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<SalesOrderDetail_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<SalesOrderDetail_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<SalesOrderDetail_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<SalesOrderDetail_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  parentbundleid: WebAttribute<SalesOrderDetail_Select, { parentbundleid: string | null }, {  }>;
  parentbundleidref_guid: WebAttribute<SalesOrderDetail_Select, { parentbundleidref_guid: string | null }, { parentbundleidref_formatted?: string }>;
  priceperunit: WebAttribute<SalesOrderDetail_Select, { priceperunit: number | null; transactioncurrencyid_guid: string | null }, { priceperunit_formatted?: string; transactioncurrencyid_formatted?: string }>;
  priceperunit_base: WebAttribute<SalesOrderDetail_Select, { priceperunit_base: number | null; transactioncurrencyid_guid: string | null }, { priceperunit_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  pricingerrorcode: WebAttribute<SalesOrderDetail_Select, { pricingerrorcode: qooi_pricingerrorcode | null }, { pricingerrorcode_formatted?: string }>;
  productassociationid: WebAttribute<SalesOrderDetail_Select, { productassociationid: string | null }, {  }>;
  productdescription: WebAttribute<SalesOrderDetail_Select, { productdescription: string | null }, {  }>;
  productid_guid: WebAttribute<SalesOrderDetail_Select, { productid_guid: string | null }, { productid_formatted?: string }>;
  productname: WebAttribute<SalesOrderDetail_Select, { productname: string | null }, {  }>;
  productnumber: WebAttribute<SalesOrderDetail_Select, { productnumber: string | null }, {  }>;
  producttypecode: WebAttribute<SalesOrderDetail_Select, { producttypecode: qooiproduct_producttype | null }, { producttypecode_formatted?: string }>;
  propertyconfigurationstatus: WebAttribute<SalesOrderDetail_Select, { propertyconfigurationstatus: qooiproduct_propertiesconfigurationstatus | null }, { propertyconfigurationstatus_formatted?: string }>;
  quantity: WebAttribute<SalesOrderDetail_Select, { quantity: number | null }, {  }>;
  quantitybackordered: WebAttribute<SalesOrderDetail_Select, { quantitybackordered: number | null }, {  }>;
  quantitycancelled: WebAttribute<SalesOrderDetail_Select, { quantitycancelled: number | null }, {  }>;
  quantityshipped: WebAttribute<SalesOrderDetail_Select, { quantityshipped: number | null }, {  }>;
  quotedetailid_guid: WebAttribute<SalesOrderDetail_Select, { quotedetailid_guid: string | null }, { quotedetailid_formatted?: string }>;
  requestdeliveryby: WebAttribute<SalesOrderDetail_Select, { requestdeliveryby: Date | null }, { requestdeliveryby_formatted?: string }>;
  salesorderdetailid: WebAttribute<SalesOrderDetail_Select, { salesorderdetailid: string | null }, {  }>;
  salesorderdetailname: WebAttribute<SalesOrderDetail_Select, { salesorderdetailname: string | null }, {  }>;
  salesorderid_guid: WebAttribute<SalesOrderDetail_Select, { salesorderid_guid: string | null }, { salesorderid_formatted?: string }>;
  salesorderispricelocked: WebAttribute<SalesOrderDetail_Select, { salesorderispricelocked: boolean | null }, {  }>;
  salesorderstatecode: WebAttribute<SalesOrderDetail_Select, { salesorderstatecode: salesorderdetail_salesorderstatecode | null }, { salesorderstatecode_formatted?: string }>;
  salesrepid_guid: WebAttribute<SalesOrderDetail_Select, { salesrepid_guid: string | null }, { salesrepid_formatted?: string }>;
  sequencenumber: WebAttribute<SalesOrderDetail_Select, { sequencenumber: number | null }, {  }>;
  shipto_addressid: WebAttribute<SalesOrderDetail_Select, { shipto_addressid: string | null }, {  }>;
  shipto_city: WebAttribute<SalesOrderDetail_Select, { shipto_city: string | null }, {  }>;
  shipto_contactname: WebAttribute<SalesOrderDetail_Select, { shipto_contactname: string | null }, {  }>;
  shipto_country: WebAttribute<SalesOrderDetail_Select, { shipto_country: string | null }, {  }>;
  shipto_fax: WebAttribute<SalesOrderDetail_Select, { shipto_fax: string | null }, {  }>;
  shipto_freighttermscode: WebAttribute<SalesOrderDetail_Select, { shipto_freighttermscode: salesorderdetail_shipto_freighttermscode | null }, { shipto_freighttermscode_formatted?: string }>;
  shipto_line1: WebAttribute<SalesOrderDetail_Select, { shipto_line1: string | null }, {  }>;
  shipto_line2: WebAttribute<SalesOrderDetail_Select, { shipto_line2: string | null }, {  }>;
  shipto_line3: WebAttribute<SalesOrderDetail_Select, { shipto_line3: string | null }, {  }>;
  shipto_name: WebAttribute<SalesOrderDetail_Select, { shipto_name: string | null }, {  }>;
  shipto_postalcode: WebAttribute<SalesOrderDetail_Select, { shipto_postalcode: string | null }, {  }>;
  shipto_stateorprovince: WebAttribute<SalesOrderDetail_Select, { shipto_stateorprovince: string | null }, {  }>;
  shipto_telephone: WebAttribute<SalesOrderDetail_Select, { shipto_telephone: string | null }, {  }>;
  skippricecalculation: WebAttribute<SalesOrderDetail_Select, { skippricecalculation: qooidetail_skippricecalculation | null }, { skippricecalculation_formatted?: string }>;
  tax: WebAttribute<SalesOrderDetail_Select, { tax: number | null; transactioncurrencyid_guid: string | null }, { tax_formatted?: string; transactioncurrencyid_formatted?: string }>;
  tax_base: WebAttribute<SalesOrderDetail_Select, { tax_base: number | null; transactioncurrencyid_guid: string | null }, { tax_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<SalesOrderDetail_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<SalesOrderDetail_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  uomid_guid: WebAttribute<SalesOrderDetail_Select, { uomid_guid: string | null }, { uomid_formatted?: string }>;
  utcconversiontimezonecode: WebAttribute<SalesOrderDetail_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<SalesOrderDetail_Select, { versionnumber: number | null }, {  }>;
  volumediscountamount: WebAttribute<SalesOrderDetail_Select, { volumediscountamount: number | null; transactioncurrencyid_guid: string | null }, { volumediscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  volumediscountamount_base: WebAttribute<SalesOrderDetail_Select, { volumediscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { volumediscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  willcall: WebAttribute<SalesOrderDetail_Select, { willcall: boolean | null }, {  }>;
}
interface SalesOrderDetail_Filter {
  baseamount: number;
  baseamount_base: number;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  exchangerate: any;
  extendedamount: number;
  extendedamount_base: number;
  importsequencenumber: number;
  iscopied: boolean;
  ispriceoverridden: boolean;
  isproductoverridden: boolean;
  lineitemnumber: number;
  manualdiscountamount: number;
  manualdiscountamount_base: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyn_agreement_guid: XQW.Guid;
  msdyn_billingmethod: msdyn_billingmethod;
  msdyn_billingstartdate: Date;
  msdyn_billingstatus: msdyn_billingstatus;
  msdyn_budgetamount: number;
  msdyn_budgetamount_base: number;
  msdyn_costamount: number;
  msdyn_costamount_base: number;
  msdyn_costpriceperunit: number;
  msdyn_costpriceperunit_base: number;
  msdyn_includeexpense: boolean;
  msdyn_includefee: boolean;
  msdyn_includematerial: boolean;
  msdyn_includetime: boolean;
  msdyn_invoicefrequency_guid: XQW.Guid;
  msdyn_linetype: msdyn_linetype;
  msdyn_project_guid: XQW.Guid;
  msdyn_quoteline: string;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  parentbundleid: XQW.Guid;
  parentbundleidref_guid: XQW.Guid;
  priceperunit: number;
  priceperunit_base: number;
  pricingerrorcode: qooi_pricingerrorcode;
  productassociationid: XQW.Guid;
  productdescription: string;
  productid_guid: XQW.Guid;
  productname: string;
  productnumber: string;
  producttypecode: qooiproduct_producttype;
  propertyconfigurationstatus: qooiproduct_propertiesconfigurationstatus;
  quantity: any;
  quantitybackordered: any;
  quantitycancelled: any;
  quantityshipped: any;
  quotedetailid_guid: XQW.Guid;
  requestdeliveryby: Date;
  salesorderdetailid: XQW.Guid;
  salesorderdetailname: string;
  salesorderid_guid: XQW.Guid;
  salesorderispricelocked: boolean;
  salesorderstatecode: salesorderdetail_salesorderstatecode;
  salesrepid_guid: XQW.Guid;
  sequencenumber: number;
  shipto_addressid: XQW.Guid;
  shipto_city: string;
  shipto_contactname: string;
  shipto_country: string;
  shipto_fax: string;
  shipto_freighttermscode: salesorderdetail_shipto_freighttermscode;
  shipto_line1: string;
  shipto_line2: string;
  shipto_line3: string;
  shipto_name: string;
  shipto_postalcode: string;
  shipto_stateorprovince: string;
  shipto_telephone: string;
  skippricecalculation: qooidetail_skippricecalculation;
  tax: number;
  tax_base: number;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  uomid_guid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
  volumediscountamount: number;
  volumediscountamount_base: number;
  willcall: boolean;
}
interface SalesOrderDetail_Expand {
  QuoteDetailId: WebExpand<SalesOrderDetail_Expand, QuoteDetail_Select, QuoteDetail_Filter, { QuoteDetailId: QuoteDetail_Result }>;
  SalesOrderDetail_AsyncOperations: WebExpand<SalesOrderDetail_Expand, AsyncOperation_Select, AsyncOperation_Filter, { SalesOrderDetail_AsyncOperations: AsyncOperation_Result[] }>;
  SalesOrderDetail_BulkDeleteFailures: WebExpand<SalesOrderDetail_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { SalesOrderDetail_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  SalesOrderDetail_Dynamicpropertyinstance: WebExpand<SalesOrderDetail_Expand, DynamicPropertyInstance_Select, DynamicPropertyInstance_Filter, { SalesOrderDetail_Dynamicpropertyinstance: DynamicPropertyInstance_Result[] }>;
  SalesOrderDetail_ProcessSessions: WebExpand<SalesOrderDetail_Expand, ProcessSession_Select, ProcessSession_Filter, { SalesOrderDetail_ProcessSessions: ProcessSession_Result[] }>;
  SalesOrderDetail_SyncErrors: WebExpand<SalesOrderDetail_Expand, SyncError_Select, SyncError_Filter, { SalesOrderDetail_SyncErrors: SyncError_Result[] }>;
  createdby: WebExpand<SalesOrderDetail_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<SalesOrderDetail_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<SalesOrderDetail_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<SalesOrderDetail_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_Project: WebExpand<SalesOrderDetail_Expand, msdyn_project_Select, msdyn_project_Filter, { msdyn_Project: msdyn_project_Result }>;
  msdyn_agreement: WebExpand<SalesOrderDetail_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { msdyn_agreement: msdyn_agreement_Result }>;
  msdyn_invoicefrequency: WebExpand<SalesOrderDetail_Expand, msdyn_invoicefrequency_Select, msdyn_invoicefrequency_Filter, { msdyn_invoicefrequency: msdyn_invoicefrequency_Result }>;
  msdyn_salesorderdetail_invoicedetail: WebExpand<SalesOrderDetail_Expand, InvoiceDetail_Select, InvoiceDetail_Filter, { msdyn_salesorderdetail_invoicedetail: InvoiceDetail_Result[] }>;
  msdyn_salesorderdetail_msdyn_actual: WebExpand<SalesOrderDetail_Expand, msdyn_actual_Select, msdyn_actual_Filter, { msdyn_salesorderdetail_msdyn_actual: msdyn_actual_Result[] }>;
  msdyn_salesorderdetail_msdyn_contractlineinvoic: WebExpand<SalesOrderDetail_Expand, msdyn_contractlineinvoiceschedule_Select, msdyn_contractlineinvoiceschedule_Filter, { msdyn_salesorderdetail_msdyn_contractlineinvoic: msdyn_contractlineinvoiceschedule_Result[] }>;
  msdyn_salesorderdetail_msdyn_contractlineschedu: WebExpand<SalesOrderDetail_Expand, msdyn_contractlinescheduleofvalue_Select, msdyn_contractlinescheduleofvalue_Filter, { msdyn_salesorderdetail_msdyn_contractlineschedu: msdyn_contractlinescheduleofvalue_Result[] }>;
  msdyn_salesorderdetail_msdyn_contractperformance_ContractLineId: WebExpand<SalesOrderDetail_Expand, msdyn_contractperformance_Select, msdyn_contractperformance_Filter, { msdyn_salesorderdetail_msdyn_contractperformance_ContractLineId: msdyn_contractperformance_Result[] }>;
  msdyn_salesorderdetail_msdyn_fact: WebExpand<SalesOrderDetail_Expand, msdyn_fact_Select, msdyn_fact_Filter, { msdyn_salesorderdetail_msdyn_fact: msdyn_fact_Result[] }>;
  msdyn_salesorderdetail_msdyn_invoicelinetransac: WebExpand<SalesOrderDetail_Expand, msdyn_invoicelinetransaction_Select, msdyn_invoicelinetransaction_Filter, { msdyn_salesorderdetail_msdyn_invoicelinetransac: msdyn_invoicelinetransaction_Result[] }>;
  msdyn_salesorderdetail_msdyn_journalline: WebExpand<SalesOrderDetail_Expand, msdyn_journalline_Select, msdyn_journalline_Filter, { msdyn_salesorderdetail_msdyn_journalline: msdyn_journalline_Result[] }>;
  msdyn_salesorderdetail_msdyn_orderlineresourcec: WebExpand<SalesOrderDetail_Expand, msdyn_orderlineresourcecategory_Select, msdyn_orderlineresourcecategory_Filter, { msdyn_salesorderdetail_msdyn_orderlineresourcec: msdyn_orderlineresourcecategory_Result[] }>;
  msdyn_salesorderdetail_msdyn_orderlinetransacti: WebExpand<SalesOrderDetail_Expand, msdyn_orderlinetransaction_Select, msdyn_orderlinetransaction_Filter, { msdyn_salesorderdetail_msdyn_orderlinetransacti: msdyn_orderlinetransaction_Result[] }>;
  msdyn_salesorderdetail_msdyn_orderlinetranscat: WebExpand<SalesOrderDetail_Expand, msdyn_orderlinetransactioncategory_Select, msdyn_orderlinetransactioncategory_Filter, { msdyn_salesorderdetail_msdyn_orderlinetranscat: msdyn_orderlinetransactioncategory_Result[] }>;
  msdyn_salesorderdetail_msdyn_orderlinetransclas: WebExpand<SalesOrderDetail_Expand, msdyn_orderlinetransactionclassification_Select, msdyn_orderlinetransactionclassification_Filter, { msdyn_salesorderdetail_msdyn_orderlinetransclas: msdyn_orderlinetransactionclassification_Result[] }>;
  owningteam: WebExpand<SalesOrderDetail_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<SalesOrderDetail_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  parentbundleid_salesorderdetail: WebExpand<SalesOrderDetail_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { parentbundleid_salesorderdetail: SalesOrderDetail_Result }>;
  parentbundleidref_salesorderdetail: WebExpand<SalesOrderDetail_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { parentbundleidref_salesorderdetail: SalesOrderDetail_Result }>;
  productassociationid_productassociation: WebExpand<SalesOrderDetail_Expand, ProductAssociation_Select, ProductAssociation_Filter, { productassociationid_productassociation: ProductAssociation_Result }>;
  productid: WebExpand<SalesOrderDetail_Expand, Product_Select, Product_Filter, { productid: Product_Result }>;
  salesorderdetail_MailboxTrackingFolders: WebExpand<SalesOrderDetail_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { salesorderdetail_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  salesorderdetail_parent_salesorderdetail: WebExpand<SalesOrderDetail_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { salesorderdetail_parent_salesorderdetail: SalesOrderDetail_Result[] }>;
  salesorderdetail_parentref_salesorderdetail: WebExpand<SalesOrderDetail_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { salesorderdetail_parentref_salesorderdetail: SalesOrderDetail_Result[] }>;
  salesorderdetail_principalobjectattributeaccess: WebExpand<SalesOrderDetail_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { salesorderdetail_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  salesorderid: WebExpand<SalesOrderDetail_Expand, SalesOrder_Select, SalesOrder_Filter, { salesorderid: SalesOrder_Result }>;
  salesrepid: WebExpand<SalesOrderDetail_Expand, SystemUser_Select, SystemUser_Filter, { salesrepid: SystemUser_Result }>;
  transactioncurrencyid: WebExpand<SalesOrderDetail_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  uomid: WebExpand<SalesOrderDetail_Expand, UoM_Select, UoM_Filter, { uomid: UoM_Result }>;
  userentityinstancedata_salesorderdetail: WebExpand<SalesOrderDetail_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_salesorderdetail: UserEntityInstanceData_Result[] }>;
}
interface SalesOrderDetail_FormattedResult {
  baseamount_base_formatted?: string;
  baseamount_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  extendedamount_base_formatted?: string;
  extendedamount_formatted?: string;
  manualdiscountamount_base_formatted?: string;
  manualdiscountamount_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyn_agreement_formatted?: string;
  msdyn_billingmethod_formatted?: string;
  msdyn_billingstartdate_formatted?: string;
  msdyn_billingstatus_formatted?: string;
  msdyn_budgetamount_base_formatted?: string;
  msdyn_budgetamount_formatted?: string;
  msdyn_costamount_base_formatted?: string;
  msdyn_costamount_formatted?: string;
  msdyn_costpriceperunit_base_formatted?: string;
  msdyn_costpriceperunit_formatted?: string;
  msdyn_invoicefrequency_formatted?: string;
  msdyn_linetype_formatted?: string;
  msdyn_project_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  parentbundleidref_formatted?: string;
  priceperunit_base_formatted?: string;
  priceperunit_formatted?: string;
  pricingerrorcode_formatted?: string;
  productid_formatted?: string;
  producttypecode_formatted?: string;
  propertyconfigurationstatus_formatted?: string;
  quotedetailid_formatted?: string;
  requestdeliveryby_formatted?: string;
  salesorderid_formatted?: string;
  salesorderstatecode_formatted?: string;
  salesrepid_formatted?: string;
  shipto_freighttermscode_formatted?: string;
  skippricecalculation_formatted?: string;
  tax_base_formatted?: string;
  tax_formatted?: string;
  transactioncurrencyid_formatted?: string;
  uomid_formatted?: string;
  volumediscountamount_base_formatted?: string;
  volumediscountamount_formatted?: string;
}
interface SalesOrderDetail_Result extends SalesOrderDetail_Base, SalesOrderDetail_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  msdyn_agreement_guid: string | null;
  msdyn_invoicefrequency_guid: string | null;
  msdyn_project_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  parentbundleidref_guid: string | null;
  productid_guid: string | null;
  quotedetailid_guid: string | null;
  salesorderid_guid: string | null;
  salesrepid_guid: string | null;
  transactioncurrencyid_guid: string | null;
  uomid_guid: string | null;
}
interface SalesOrderDetail_RelatedOne {
  QuoteDetailId: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  msdyn_Project: WebMappingRetrieve<msdyn_project_Select,msdyn_project_Expand,msdyn_project_Filter,msdyn_project_Fixed,msdyn_project_Result,msdyn_project_FormattedResult>;
  msdyn_agreement: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  msdyn_invoicefrequency: WebMappingRetrieve<msdyn_invoicefrequency_Select,msdyn_invoicefrequency_Expand,msdyn_invoicefrequency_Filter,msdyn_invoicefrequency_Fixed,msdyn_invoicefrequency_Result,msdyn_invoicefrequency_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  parentbundleid_salesorderdetail: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  parentbundleidref_salesorderdetail: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  productassociationid_productassociation: WebMappingRetrieve<ProductAssociation_Select,ProductAssociation_Expand,ProductAssociation_Filter,ProductAssociation_Fixed,ProductAssociation_Result,ProductAssociation_FormattedResult>;
  productid: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  salesorderid: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  salesrepid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
  uomid: WebMappingRetrieve<UoM_Select,UoM_Expand,UoM_Filter,UoM_Fixed,UoM_Result,UoM_FormattedResult>;
}
interface SalesOrderDetail_RelatedMany {
  SalesOrderDetail_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  SalesOrderDetail_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  SalesOrderDetail_Dynamicpropertyinstance: WebMappingRetrieve<DynamicPropertyInstance_Select,DynamicPropertyInstance_Expand,DynamicPropertyInstance_Filter,DynamicPropertyInstance_Fixed,DynamicPropertyInstance_Result,DynamicPropertyInstance_FormattedResult>;
  SalesOrderDetail_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  SalesOrderDetail_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  msdyn_salesorderdetail_invoicedetail: WebMappingRetrieve<InvoiceDetail_Select,InvoiceDetail_Expand,InvoiceDetail_Filter,InvoiceDetail_Fixed,InvoiceDetail_Result,InvoiceDetail_FormattedResult>;
  msdyn_salesorderdetail_msdyn_actual: WebMappingRetrieve<msdyn_actual_Select,msdyn_actual_Expand,msdyn_actual_Filter,msdyn_actual_Fixed,msdyn_actual_Result,msdyn_actual_FormattedResult>;
  msdyn_salesorderdetail_msdyn_contractlineinvoic: WebMappingRetrieve<msdyn_contractlineinvoiceschedule_Select,msdyn_contractlineinvoiceschedule_Expand,msdyn_contractlineinvoiceschedule_Filter,msdyn_contractlineinvoiceschedule_Fixed,msdyn_contractlineinvoiceschedule_Result,msdyn_contractlineinvoiceschedule_FormattedResult>;
  msdyn_salesorderdetail_msdyn_contractlineschedu: WebMappingRetrieve<msdyn_contractlinescheduleofvalue_Select,msdyn_contractlinescheduleofvalue_Expand,msdyn_contractlinescheduleofvalue_Filter,msdyn_contractlinescheduleofvalue_Fixed,msdyn_contractlinescheduleofvalue_Result,msdyn_contractlinescheduleofvalue_FormattedResult>;
  msdyn_salesorderdetail_msdyn_contractperformance_ContractLineId: WebMappingRetrieve<msdyn_contractperformance_Select,msdyn_contractperformance_Expand,msdyn_contractperformance_Filter,msdyn_contractperformance_Fixed,msdyn_contractperformance_Result,msdyn_contractperformance_FormattedResult>;
  msdyn_salesorderdetail_msdyn_fact: WebMappingRetrieve<msdyn_fact_Select,msdyn_fact_Expand,msdyn_fact_Filter,msdyn_fact_Fixed,msdyn_fact_Result,msdyn_fact_FormattedResult>;
  msdyn_salesorderdetail_msdyn_invoicelinetransac: WebMappingRetrieve<msdyn_invoicelinetransaction_Select,msdyn_invoicelinetransaction_Expand,msdyn_invoicelinetransaction_Filter,msdyn_invoicelinetransaction_Fixed,msdyn_invoicelinetransaction_Result,msdyn_invoicelinetransaction_FormattedResult>;
  msdyn_salesorderdetail_msdyn_journalline: WebMappingRetrieve<msdyn_journalline_Select,msdyn_journalline_Expand,msdyn_journalline_Filter,msdyn_journalline_Fixed,msdyn_journalline_Result,msdyn_journalline_FormattedResult>;
  msdyn_salesorderdetail_msdyn_orderlineresourcec: WebMappingRetrieve<msdyn_orderlineresourcecategory_Select,msdyn_orderlineresourcecategory_Expand,msdyn_orderlineresourcecategory_Filter,msdyn_orderlineresourcecategory_Fixed,msdyn_orderlineresourcecategory_Result,msdyn_orderlineresourcecategory_FormattedResult>;
  msdyn_salesorderdetail_msdyn_orderlinetransacti: WebMappingRetrieve<msdyn_orderlinetransaction_Select,msdyn_orderlinetransaction_Expand,msdyn_orderlinetransaction_Filter,msdyn_orderlinetransaction_Fixed,msdyn_orderlinetransaction_Result,msdyn_orderlinetransaction_FormattedResult>;
  msdyn_salesorderdetail_msdyn_orderlinetranscat: WebMappingRetrieve<msdyn_orderlinetransactioncategory_Select,msdyn_orderlinetransactioncategory_Expand,msdyn_orderlinetransactioncategory_Filter,msdyn_orderlinetransactioncategory_Fixed,msdyn_orderlinetransactioncategory_Result,msdyn_orderlinetransactioncategory_FormattedResult>;
  msdyn_salesorderdetail_msdyn_orderlinetransclas: WebMappingRetrieve<msdyn_orderlinetransactionclassification_Select,msdyn_orderlinetransactionclassification_Expand,msdyn_orderlinetransactionclassification_Filter,msdyn_orderlinetransactionclassification_Fixed,msdyn_orderlinetransactionclassification_Result,msdyn_orderlinetransactionclassification_FormattedResult>;
  salesorderdetail_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  salesorderdetail_parent_salesorderdetail: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  salesorderdetail_parentref_salesorderdetail: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  salesorderdetail_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  userentityinstancedata_salesorderdetail: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  salesorderdetails: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
}
interface WebEntitiesRelated {
  salesorderdetails: WebMappingRelated<SalesOrderDetail_RelatedOne,SalesOrderDetail_RelatedMany>;
}
interface WebEntitiesCUDA {
  salesorderdetails: WebMappingCUDA<SalesOrderDetail_Create,SalesOrderDetail_Update,SalesOrderDetail_Select>;
}
