interface SharePointDocument_Base extends WebEntity {
  absoluteurl?: string | null;
  appcreatedby?: string | null;
  appmodifiedby?: string | null;
  author?: string | null;
  checkedoutto?: string | null;
  checkincomment?: string | null;
  childfoldercount?: number | null;
  childitemcount?: number | null;
  contenttype?: string | null;
  contenttypeid?: number | null;
  copysource?: string | null;
  createdon?: Date | null;
  documentid?: number | null;
  documentlocationtype?: sharepointdocumentlocation_locationtype | null;
  edit?: string | null;
  editurl?: string | null;
  exchangerate?: number | null;
  filesize?: number | null;
  filetype?: string | null;
  fullname?: string | null;
  iconclassname?: string | null;
  ischeckedout?: boolean | null;
  isfolder?: boolean | null;
  isrecursivefetch?: boolean | null;
  locationid?: string | null;
  locationname?: string | null;
  modified?: Date | null;
  modifiedon?: Date | null;
  readurl?: string | null;
  relativelocation?: string | null;
  servicetype?: sharepointsite_servicetype | null;
  sharepointcreatedon?: Date | null;
  sharepointdocumentid?: string | null;
  sharepointmodifiedby?: string | null;
  title?: string | null;
  version?: string | null;
}
interface SharePointDocument_Relationships {
  SharePointDocument_Annotation?: Annotation_Result[] | null;
  regardingobjectid_account?: Account_Result | null;
  regardingobjectid_kbarticle?: KbArticle_Result | null;
  regardingobjectid_knowledgearticle?: KnowledgeArticle_Result | null;
  regardingobjectid_lead?: Lead_Result | null;
  regardingobjectid_msdyn_agreement?: msdyn_agreement_Result | null;
  regardingobjectid_msdyn_agreementbookingdate?: msdyn_agreementbookingdate_Result | null;
  regardingobjectid_msdyn_agreementbookingsetup?: msdyn_agreementbookingsetup_Result | null;
  regardingobjectid_msdyn_agreementinvoicedate?: msdyn_agreementinvoicedate_Result | null;
  regardingobjectid_msdyn_agreementinvoicesetup?: msdyn_agreementinvoicesetup_Result | null;
  regardingobjectid_msdyn_bookingtimestamp?: msdyn_bookingtimestamp_Result | null;
  regardingobjectid_msdyn_expense?: msdyn_expense_Result | null;
  regardingobjectid_msdyn_incidenttypeproduct?: msdyn_incidenttypeproduct_Result | null;
  regardingobjectid_msdyn_inventoryadjustment?: msdyn_inventoryadjustment_Result | null;
  regardingobjectid_msdyn_inventoryadjustmentproduct?: msdyn_inventoryadjustmentproduct_Result | null;
  regardingobjectid_msdyn_inventorytransfer?: msdyn_inventorytransfer_Result | null;
  regardingobjectid_msdyn_knowledgearticletemplate?: msdyn_knowledgearticletemplate_Result | null;
  regardingobjectid_msdyn_playbookactivity?: msdyn_playbookactivity_Result | null;
  regardingobjectid_msdyn_project?: msdyn_project_Result | null;
  regardingobjectid_msdyn_purchaseorder?: msdyn_purchaseorder_Result | null;
  regardingobjectid_msdyn_purchaseorderproduct?: msdyn_purchaseorderproduct_Result | null;
  regardingobjectid_msdyn_purchaseorderreceipt?: msdyn_purchaseorderreceipt_Result | null;
  regardingobjectid_msdyn_resourceterritory?: msdyn_resourceterritory_Result | null;
  regardingobjectid_msdyn_rma?: msdyn_rma_Result | null;
  regardingobjectid_msdyn_rmareceipt?: msdyn_rmareceipt_Result | null;
  regardingobjectid_msdyn_rtv?: msdyn_rtv_Result | null;
  regardingobjectid_msdyn_timegroup?: msdyn_timegroup_Result | null;
  regardingobjectid_msdyn_timegroupdetail?: msdyn_timegroupdetail_Result | null;
  regardingobjectid_msdyn_warehouse?: msdyn_warehouse_Result | null;
  regardingobjectid_msdyn_workorder?: msdyn_workorder_Result | null;
  regardingobjectid_msdyn_workorderincident?: msdyn_workorderincident_Result | null;
  regardingobjectid_msdyn_workorderproduct?: msdyn_workorderproduct_Result | null;
  regardingobjectid_msdyn_workorderservice?: msdyn_workorderservice_Result | null;
  regardingobjectid_msdyn_workorderservicetask?: msdyn_workorderservicetask_Result | null;
  regardingobjectid_opportunity?: Opportunity_Result | null;
  regardingobjectid_opportunity1?: Contact_Result | null;
  regardingobjectid_product?: Product_Result | null;
  regardingobjectid_quote?: Quote_Result | null;
  regardingobjectid_salesliterature?: SalesLiterature_Result | null;
}
interface SharePointDocument extends SharePointDocument_Base, SharePointDocument_Relationships {
  businessunitid_bind$businessunits?: string | null;
  regardingobjectid_account_bind$accounts?: string | null;
  regardingobjectid_kbarticle_bind$kbarticles?: string | null;
  regardingobjectid_knowledgearticle_bind$knowledgearticles?: string | null;
  regardingobjectid_lead_bind$leads?: string | null;
  regardingobjectid_msdyn_agreement_bind$msdyn_agreements?: string | null;
  regardingobjectid_msdyn_agreementbookingdate_bind$msdyn_agreementbookingdates?: string | null;
  regardingobjectid_msdyn_agreementbookingsetup_bind$msdyn_agreementbookingsetups?: string | null;
  regardingobjectid_msdyn_agreementinvoicedate_bind$msdyn_agreementinvoicedates?: string | null;
  regardingobjectid_msdyn_agreementinvoicesetup_bind$msdyn_agreementinvoicesetups?: string | null;
  regardingobjectid_msdyn_bookingtimestamp_bind$msdyn_bookingtimestamps?: string | null;
  regardingobjectid_msdyn_expense_bind$msdyn_expenses?: string | null;
  regardingobjectid_msdyn_incidenttypeproduct_bind$msdyn_incidenttypeproducts?: string | null;
  regardingobjectid_msdyn_inventoryadjustment_bind$msdyn_inventoryadjustments?: string | null;
  regardingobjectid_msdyn_inventoryadjustmentproduct_bind$msdyn_inventoryadjustmentproducts?: string | null;
  regardingobjectid_msdyn_inventorytransfer_bind$msdyn_inventorytransfers?: string | null;
  regardingobjectid_msdyn_knowledgearticletemplate_bind$msdyn_knowledgearticletemplates?: string | null;
  regardingobjectid_msdyn_playbookactivity_bind$msdyn_playbookactivities?: string | null;
  regardingobjectid_msdyn_project_bind$msdyn_projects?: string | null;
  regardingobjectid_msdyn_purchaseorder_bind$msdyn_purchaseorders?: string | null;
  regardingobjectid_msdyn_purchaseorderproduct_bind$msdyn_purchaseorderproducts?: string | null;
  regardingobjectid_msdyn_purchaseorderreceipt_bind$msdyn_purchaseorderreceipts?: string | null;
  regardingobjectid_msdyn_resourceterritory_bind$msdyn_resourceterritories?: string | null;
  regardingobjectid_msdyn_rma_bind$msdyn_rmas?: string | null;
  regardingobjectid_msdyn_rmareceipt_bind$msdyn_rmareceipts?: string | null;
  regardingobjectid_msdyn_rtv_bind$msdyn_rtvs?: string | null;
  regardingobjectid_msdyn_timegroup_bind$msdyn_timegroups?: string | null;
  regardingobjectid_msdyn_timegroupdetail_bind$msdyn_timegroupdetails?: string | null;
  regardingobjectid_msdyn_warehouse_bind$msdyn_warehouses?: string | null;
  regardingobjectid_msdyn_workorder_bind$msdyn_workorders?: string | null;
  regardingobjectid_msdyn_workorderincident_bind$msdyn_workorderincidents?: string | null;
  regardingobjectid_msdyn_workorderproduct_bind$msdyn_workorderproducts?: string | null;
  regardingobjectid_msdyn_workorderservice_bind$msdyn_workorderservices?: string | null;
  regardingobjectid_msdyn_workorderservicetask_bind$msdyn_workorderservicetasks?: string | null;
  regardingobjectid_opportunity_bind$contacts?: string | null;
  regardingobjectid_opportunity_bind$opportunities?: string | null;
  regardingobjectid_product_bind$products?: string | null;
  regardingobjectid_quote_bind$quotes?: string | null;
  regardingobjectid_salesliterature_bind$salesliteratures?: string | null;
}
interface SharePointDocument_Create extends SharePointDocument {
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface SharePointDocument_Update extends SharePointDocument {
}
interface SharePointDocument_Select {
  absoluteurl: WebAttribute<SharePointDocument_Select, { absoluteurl: string | null }, {  }>;
  appcreatedby: WebAttribute<SharePointDocument_Select, { appcreatedby: string | null }, {  }>;
  appmodifiedby: WebAttribute<SharePointDocument_Select, { appmodifiedby: string | null }, {  }>;
  author: WebAttribute<SharePointDocument_Select, { author: string | null }, {  }>;
  businessunitid_guid: WebAttribute<SharePointDocument_Select, { businessunitid_guid: string | null }, { businessunitid_formatted?: string }>;
  checkedoutto: WebAttribute<SharePointDocument_Select, { checkedoutto: string | null }, {  }>;
  checkincomment: WebAttribute<SharePointDocument_Select, { checkincomment: string | null }, {  }>;
  childfoldercount: WebAttribute<SharePointDocument_Select, { childfoldercount: number | null }, {  }>;
  childitemcount: WebAttribute<SharePointDocument_Select, { childitemcount: number | null }, {  }>;
  contenttype: WebAttribute<SharePointDocument_Select, { contenttype: string | null }, {  }>;
  contenttypeid: WebAttribute<SharePointDocument_Select, { contenttypeid: number | null }, {  }>;
  copysource: WebAttribute<SharePointDocument_Select, { copysource: string | null }, {  }>;
  createdby_guid: WebAttribute<SharePointDocument_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<SharePointDocument_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<SharePointDocument_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  documentid: WebAttribute<SharePointDocument_Select, { documentid: number | null }, {  }>;
  documentlocationtype: WebAttribute<SharePointDocument_Select, { documentlocationtype: sharepointdocumentlocation_locationtype | null }, { documentlocationtype_formatted?: string }>;
  edit: WebAttribute<SharePointDocument_Select, { edit: string | null }, {  }>;
  editurl: WebAttribute<SharePointDocument_Select, { editurl: string | null }, {  }>;
  exchangerate: WebAttribute<SharePointDocument_Select, { exchangerate: number | null }, {  }>;
  filesize: WebAttribute<SharePointDocument_Select, { filesize: number | null }, {  }>;
  filetype: WebAttribute<SharePointDocument_Select, { filetype: string | null }, {  }>;
  fullname: WebAttribute<SharePointDocument_Select, { fullname: string | null }, {  }>;
  iconclassname: WebAttribute<SharePointDocument_Select, { iconclassname: string | null }, {  }>;
  ischeckedout: WebAttribute<SharePointDocument_Select, { ischeckedout: boolean | null }, {  }>;
  isfolder: WebAttribute<SharePointDocument_Select, { isfolder: boolean | null }, {  }>;
  isrecursivefetch: WebAttribute<SharePointDocument_Select, { isrecursivefetch: boolean | null }, {  }>;
  locationid: WebAttribute<SharePointDocument_Select, { locationid: string | null }, {  }>;
  locationname: WebAttribute<SharePointDocument_Select, { locationname: string | null }, {  }>;
  modified: WebAttribute<SharePointDocument_Select, { modified: Date | null }, { modified_formatted?: string }>;
  modifiedby_guid: WebAttribute<SharePointDocument_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<SharePointDocument_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<SharePointDocument_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  organizationid_guid: WebAttribute<SharePointDocument_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  ownerid_guid: WebAttribute<SharePointDocument_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<SharePointDocument_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<SharePointDocument_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<SharePointDocument_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  readurl: WebAttribute<SharePointDocument_Select, { readurl: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<SharePointDocument_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  relativelocation: WebAttribute<SharePointDocument_Select, { relativelocation: string | null }, {  }>;
  servicetype: WebAttribute<SharePointDocument_Select, { servicetype: sharepointsite_servicetype | null }, { servicetype_formatted?: string }>;
  sharepointcreatedon: WebAttribute<SharePointDocument_Select, { sharepointcreatedon: Date | null }, { sharepointcreatedon_formatted?: string }>;
  sharepointdocumentid: WebAttribute<SharePointDocument_Select, { sharepointdocumentid: string | null }, {  }>;
  sharepointmodifiedby: WebAttribute<SharePointDocument_Select, { sharepointmodifiedby: string | null }, {  }>;
  title: WebAttribute<SharePointDocument_Select, { title: string | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<SharePointDocument_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  version: WebAttribute<SharePointDocument_Select, { version: string | null }, {  }>;
}
interface SharePointDocument_Filter {
  absoluteurl: string;
  appcreatedby: string;
  appmodifiedby: string;
  author: string;
  businessunitid_guid: XQW.Guid;
  checkedoutto: string;
  checkincomment: string;
  childfoldercount: number;
  childitemcount: number;
  contenttype: string;
  contenttypeid: number;
  copysource: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  documentid: number;
  documentlocationtype: sharepointdocumentlocation_locationtype;
  edit: string;
  editurl: string;
  exchangerate: any;
  filesize: number;
  filetype: string;
  fullname: string;
  iconclassname: string;
  ischeckedout: boolean;
  isfolder: boolean;
  isrecursivefetch: boolean;
  locationid: string;
  locationname: string;
  modified: Date;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  organizationid_guid: XQW.Guid;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  readurl: string;
  regardingobjectid_guid: XQW.Guid;
  relativelocation: string;
  servicetype: sharepointsite_servicetype;
  sharepointcreatedon: Date;
  sharepointdocumentid: XQW.Guid;
  sharepointmodifiedby: string;
  title: string;
  transactioncurrencyid_guid: XQW.Guid;
  version: string;
}
interface SharePointDocument_Expand {
  SharePointDocument_Annotation: WebExpand<SharePointDocument_Expand, Annotation_Select, Annotation_Filter, { SharePointDocument_Annotation: Annotation_Result[] }>;
  businessunitid: WebExpand<SharePointDocument_Expand, BusinessUnit_Select, BusinessUnit_Filter, { businessunitid: BusinessUnit_Result }>;
  createdby: WebExpand<SharePointDocument_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<SharePointDocument_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<SharePointDocument_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<SharePointDocument_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  organizationid: WebExpand<SharePointDocument_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  ownerid: WebExpand<SharePointDocument_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<SharePointDocument_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  regardingobjectid_account: WebExpand<SharePointDocument_Expand, Account_Select, Account_Filter, { regardingobjectid_account: Account_Result }>;
  regardingobjectid_kbarticle: WebExpand<SharePointDocument_Expand, KbArticle_Select, KbArticle_Filter, { regardingobjectid_kbarticle: KbArticle_Result }>;
  regardingobjectid_knowledgearticle: WebExpand<SharePointDocument_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle: KnowledgeArticle_Result }>;
  regardingobjectid_lead: WebExpand<SharePointDocument_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead: Lead_Result }>;
  regardingobjectid_msdyn_agreement: WebExpand<SharePointDocument_Expand, msdyn_agreement_Select, msdyn_agreement_Filter, { regardingobjectid_msdyn_agreement: msdyn_agreement_Result }>;
  regardingobjectid_msdyn_agreementbookingdate: WebExpand<SharePointDocument_Expand, msdyn_agreementbookingdate_Select, msdyn_agreementbookingdate_Filter, { regardingobjectid_msdyn_agreementbookingdate: msdyn_agreementbookingdate_Result }>;
  regardingobjectid_msdyn_agreementbookingsetup: WebExpand<SharePointDocument_Expand, msdyn_agreementbookingsetup_Select, msdyn_agreementbookingsetup_Filter, { regardingobjectid_msdyn_agreementbookingsetup: msdyn_agreementbookingsetup_Result }>;
  regardingobjectid_msdyn_agreementinvoicedate: WebExpand<SharePointDocument_Expand, msdyn_agreementinvoicedate_Select, msdyn_agreementinvoicedate_Filter, { regardingobjectid_msdyn_agreementinvoicedate: msdyn_agreementinvoicedate_Result }>;
  regardingobjectid_msdyn_agreementinvoicesetup: WebExpand<SharePointDocument_Expand, msdyn_agreementinvoicesetup_Select, msdyn_agreementinvoicesetup_Filter, { regardingobjectid_msdyn_agreementinvoicesetup: msdyn_agreementinvoicesetup_Result }>;
  regardingobjectid_msdyn_bookingtimestamp: WebExpand<SharePointDocument_Expand, msdyn_bookingtimestamp_Select, msdyn_bookingtimestamp_Filter, { regardingobjectid_msdyn_bookingtimestamp: msdyn_bookingtimestamp_Result }>;
  regardingobjectid_msdyn_expense: WebExpand<SharePointDocument_Expand, msdyn_expense_Select, msdyn_expense_Filter, { regardingobjectid_msdyn_expense: msdyn_expense_Result }>;
  regardingobjectid_msdyn_incidenttypeproduct: WebExpand<SharePointDocument_Expand, msdyn_incidenttypeproduct_Select, msdyn_incidenttypeproduct_Filter, { regardingobjectid_msdyn_incidenttypeproduct: msdyn_incidenttypeproduct_Result }>;
  regardingobjectid_msdyn_inventoryadjustment: WebExpand<SharePointDocument_Expand, msdyn_inventoryadjustment_Select, msdyn_inventoryadjustment_Filter, { regardingobjectid_msdyn_inventoryadjustment: msdyn_inventoryadjustment_Result }>;
  regardingobjectid_msdyn_inventoryadjustmentproduct: WebExpand<SharePointDocument_Expand, msdyn_inventoryadjustmentproduct_Select, msdyn_inventoryadjustmentproduct_Filter, { regardingobjectid_msdyn_inventoryadjustmentproduct: msdyn_inventoryadjustmentproduct_Result }>;
  regardingobjectid_msdyn_inventorytransfer: WebExpand<SharePointDocument_Expand, msdyn_inventorytransfer_Select, msdyn_inventorytransfer_Filter, { regardingobjectid_msdyn_inventorytransfer: msdyn_inventorytransfer_Result }>;
  regardingobjectid_msdyn_knowledgearticletemplate: WebExpand<SharePointDocument_Expand, msdyn_knowledgearticletemplate_Select, msdyn_knowledgearticletemplate_Filter, { regardingobjectid_msdyn_knowledgearticletemplate: msdyn_knowledgearticletemplate_Result }>;
  regardingobjectid_msdyn_playbookactivity: WebExpand<SharePointDocument_Expand, msdyn_playbookactivity_Select, msdyn_playbookactivity_Filter, { regardingobjectid_msdyn_playbookactivity: msdyn_playbookactivity_Result }>;
  regardingobjectid_msdyn_project: WebExpand<SharePointDocument_Expand, msdyn_project_Select, msdyn_project_Filter, { regardingobjectid_msdyn_project: msdyn_project_Result }>;
  regardingobjectid_msdyn_purchaseorder: WebExpand<SharePointDocument_Expand, msdyn_purchaseorder_Select, msdyn_purchaseorder_Filter, { regardingobjectid_msdyn_purchaseorder: msdyn_purchaseorder_Result }>;
  regardingobjectid_msdyn_purchaseorderproduct: WebExpand<SharePointDocument_Expand, msdyn_purchaseorderproduct_Select, msdyn_purchaseorderproduct_Filter, { regardingobjectid_msdyn_purchaseorderproduct: msdyn_purchaseorderproduct_Result }>;
  regardingobjectid_msdyn_purchaseorderreceipt: WebExpand<SharePointDocument_Expand, msdyn_purchaseorderreceipt_Select, msdyn_purchaseorderreceipt_Filter, { regardingobjectid_msdyn_purchaseorderreceipt: msdyn_purchaseorderreceipt_Result }>;
  regardingobjectid_msdyn_resourceterritory: WebExpand<SharePointDocument_Expand, msdyn_resourceterritory_Select, msdyn_resourceterritory_Filter, { regardingobjectid_msdyn_resourceterritory: msdyn_resourceterritory_Result }>;
  regardingobjectid_msdyn_rma: WebExpand<SharePointDocument_Expand, msdyn_rma_Select, msdyn_rma_Filter, { regardingobjectid_msdyn_rma: msdyn_rma_Result }>;
  regardingobjectid_msdyn_rmareceipt: WebExpand<SharePointDocument_Expand, msdyn_rmareceipt_Select, msdyn_rmareceipt_Filter, { regardingobjectid_msdyn_rmareceipt: msdyn_rmareceipt_Result }>;
  regardingobjectid_msdyn_rtv: WebExpand<SharePointDocument_Expand, msdyn_rtv_Select, msdyn_rtv_Filter, { regardingobjectid_msdyn_rtv: msdyn_rtv_Result }>;
  regardingobjectid_msdyn_timegroup: WebExpand<SharePointDocument_Expand, msdyn_timegroup_Select, msdyn_timegroup_Filter, { regardingobjectid_msdyn_timegroup: msdyn_timegroup_Result }>;
  regardingobjectid_msdyn_timegroupdetail: WebExpand<SharePointDocument_Expand, msdyn_timegroupdetail_Select, msdyn_timegroupdetail_Filter, { regardingobjectid_msdyn_timegroupdetail: msdyn_timegroupdetail_Result }>;
  regardingobjectid_msdyn_warehouse: WebExpand<SharePointDocument_Expand, msdyn_warehouse_Select, msdyn_warehouse_Filter, { regardingobjectid_msdyn_warehouse: msdyn_warehouse_Result }>;
  regardingobjectid_msdyn_workorder: WebExpand<SharePointDocument_Expand, msdyn_workorder_Select, msdyn_workorder_Filter, { regardingobjectid_msdyn_workorder: msdyn_workorder_Result }>;
  regardingobjectid_msdyn_workorderincident: WebExpand<SharePointDocument_Expand, msdyn_workorderincident_Select, msdyn_workorderincident_Filter, { regardingobjectid_msdyn_workorderincident: msdyn_workorderincident_Result }>;
  regardingobjectid_msdyn_workorderproduct: WebExpand<SharePointDocument_Expand, msdyn_workorderproduct_Select, msdyn_workorderproduct_Filter, { regardingobjectid_msdyn_workorderproduct: msdyn_workorderproduct_Result }>;
  regardingobjectid_msdyn_workorderservice: WebExpand<SharePointDocument_Expand, msdyn_workorderservice_Select, msdyn_workorderservice_Filter, { regardingobjectid_msdyn_workorderservice: msdyn_workorderservice_Result }>;
  regardingobjectid_msdyn_workorderservicetask: WebExpand<SharePointDocument_Expand, msdyn_workorderservicetask_Select, msdyn_workorderservicetask_Filter, { regardingobjectid_msdyn_workorderservicetask: msdyn_workorderservicetask_Result }>;
  regardingobjectid_opportunity: WebExpand<SharePointDocument_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity: Opportunity_Result }>;
  regardingobjectid_opportunity1: WebExpand<SharePointDocument_Expand, Contact_Select, Contact_Filter, { regardingobjectid_opportunity: Contact_Result }>;
  regardingobjectid_product: WebExpand<SharePointDocument_Expand, Product_Select, Product_Filter, { regardingobjectid_product: Product_Result }>;
  regardingobjectid_quote: WebExpand<SharePointDocument_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote: Quote_Result }>;
  regardingobjectid_salesliterature: WebExpand<SharePointDocument_Expand, SalesLiterature_Select, SalesLiterature_Filter, { regardingobjectid_salesliterature: SalesLiterature_Result }>;
  transactioncurrencyid: WebExpand<SharePointDocument_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface SharePointDocument_FormattedResult {
  businessunitid_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  documentlocationtype_formatted?: string;
  modified_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  organizationid_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  regardingobjectid_formatted?: string;
  servicetype_formatted?: string;
  sharepointcreatedon_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface SharePointDocument_Result extends SharePointDocument_Base, SharePointDocument_Relationships {
  "@odata.etag": string;
  businessunitid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  organizationid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface SharePointDocument_RelatedOne {
  businessunitid: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  regardingobjectid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_kbarticle: WebMappingRetrieve<KbArticle_Select,KbArticle_Expand,KbArticle_Filter,KbArticle_Fixed,KbArticle_Result,KbArticle_FormattedResult>;
  regardingobjectid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_agreement: WebMappingRetrieve<msdyn_agreement_Select,msdyn_agreement_Expand,msdyn_agreement_Filter,msdyn_agreement_Fixed,msdyn_agreement_Result,msdyn_agreement_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingdate: WebMappingRetrieve<msdyn_agreementbookingdate_Select,msdyn_agreementbookingdate_Expand,msdyn_agreementbookingdate_Filter,msdyn_agreementbookingdate_Fixed,msdyn_agreementbookingdate_Result,msdyn_agreementbookingdate_FormattedResult>;
  regardingobjectid_msdyn_agreementbookingsetup: WebMappingRetrieve<msdyn_agreementbookingsetup_Select,msdyn_agreementbookingsetup_Expand,msdyn_agreementbookingsetup_Filter,msdyn_agreementbookingsetup_Fixed,msdyn_agreementbookingsetup_Result,msdyn_agreementbookingsetup_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoicedate: WebMappingRetrieve<msdyn_agreementinvoicedate_Select,msdyn_agreementinvoicedate_Expand,msdyn_agreementinvoicedate_Filter,msdyn_agreementinvoicedate_Fixed,msdyn_agreementinvoicedate_Result,msdyn_agreementinvoicedate_FormattedResult>;
  regardingobjectid_msdyn_agreementinvoicesetup: WebMappingRetrieve<msdyn_agreementinvoicesetup_Select,msdyn_agreementinvoicesetup_Expand,msdyn_agreementinvoicesetup_Filter,msdyn_agreementinvoicesetup_Fixed,msdyn_agreementinvoicesetup_Result,msdyn_agreementinvoicesetup_FormattedResult>;
  regardingobjectid_msdyn_bookingtimestamp: WebMappingRetrieve<msdyn_bookingtimestamp_Select,msdyn_bookingtimestamp_Expand,msdyn_bookingtimestamp_Filter,msdyn_bookingtimestamp_Fixed,msdyn_bookingtimestamp_Result,msdyn_bookingtimestamp_FormattedResult>;
  regardingobjectid_msdyn_expense: WebMappingRetrieve<msdyn_expense_Select,msdyn_expense_Expand,msdyn_expense_Filter,msdyn_expense_Fixed,msdyn_expense_Result,msdyn_expense_FormattedResult>;
  regardingobjectid_msdyn_incidenttypeproduct: WebMappingRetrieve<msdyn_incidenttypeproduct_Select,msdyn_incidenttypeproduct_Expand,msdyn_incidenttypeproduct_Filter,msdyn_incidenttypeproduct_Fixed,msdyn_incidenttypeproduct_Result,msdyn_incidenttypeproduct_FormattedResult>;
  regardingobjectid_msdyn_inventoryadjustment: WebMappingRetrieve<msdyn_inventoryadjustment_Select,msdyn_inventoryadjustment_Expand,msdyn_inventoryadjustment_Filter,msdyn_inventoryadjustment_Fixed,msdyn_inventoryadjustment_Result,msdyn_inventoryadjustment_FormattedResult>;
  regardingobjectid_msdyn_inventoryadjustmentproduct: WebMappingRetrieve<msdyn_inventoryadjustmentproduct_Select,msdyn_inventoryadjustmentproduct_Expand,msdyn_inventoryadjustmentproduct_Filter,msdyn_inventoryadjustmentproduct_Fixed,msdyn_inventoryadjustmentproduct_Result,msdyn_inventoryadjustmentproduct_FormattedResult>;
  regardingobjectid_msdyn_inventorytransfer: WebMappingRetrieve<msdyn_inventorytransfer_Select,msdyn_inventorytransfer_Expand,msdyn_inventorytransfer_Filter,msdyn_inventorytransfer_Fixed,msdyn_inventorytransfer_Result,msdyn_inventorytransfer_FormattedResult>;
  regardingobjectid_msdyn_knowledgearticletemplate: WebMappingRetrieve<msdyn_knowledgearticletemplate_Select,msdyn_knowledgearticletemplate_Expand,msdyn_knowledgearticletemplate_Filter,msdyn_knowledgearticletemplate_Fixed,msdyn_knowledgearticletemplate_Result,msdyn_knowledgearticletemplate_FormattedResult>;
  regardingobjectid_msdyn_playbookactivity: WebMappingRetrieve<msdyn_playbookactivity_Select,msdyn_playbookactivity_Expand,msdyn_playbookactivity_Filter,msdyn_playbookactivity_Fixed,msdyn_playbookactivity_Result,msdyn_playbookactivity_FormattedResult>;
  regardingobjectid_msdyn_project: WebMappingRetrieve<msdyn_project_Select,msdyn_project_Expand,msdyn_project_Filter,msdyn_project_Fixed,msdyn_project_Result,msdyn_project_FormattedResult>;
  regardingobjectid_msdyn_purchaseorder: WebMappingRetrieve<msdyn_purchaseorder_Select,msdyn_purchaseorder_Expand,msdyn_purchaseorder_Filter,msdyn_purchaseorder_Fixed,msdyn_purchaseorder_Result,msdyn_purchaseorder_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderproduct: WebMappingRetrieve<msdyn_purchaseorderproduct_Select,msdyn_purchaseorderproduct_Expand,msdyn_purchaseorderproduct_Filter,msdyn_purchaseorderproduct_Fixed,msdyn_purchaseorderproduct_Result,msdyn_purchaseorderproduct_FormattedResult>;
  regardingobjectid_msdyn_purchaseorderreceipt: WebMappingRetrieve<msdyn_purchaseorderreceipt_Select,msdyn_purchaseorderreceipt_Expand,msdyn_purchaseorderreceipt_Filter,msdyn_purchaseorderreceipt_Fixed,msdyn_purchaseorderreceipt_Result,msdyn_purchaseorderreceipt_FormattedResult>;
  regardingobjectid_msdyn_resourceterritory: WebMappingRetrieve<msdyn_resourceterritory_Select,msdyn_resourceterritory_Expand,msdyn_resourceterritory_Filter,msdyn_resourceterritory_Fixed,msdyn_resourceterritory_Result,msdyn_resourceterritory_FormattedResult>;
  regardingobjectid_msdyn_rma: WebMappingRetrieve<msdyn_rma_Select,msdyn_rma_Expand,msdyn_rma_Filter,msdyn_rma_Fixed,msdyn_rma_Result,msdyn_rma_FormattedResult>;
  regardingobjectid_msdyn_rmareceipt: WebMappingRetrieve<msdyn_rmareceipt_Select,msdyn_rmareceipt_Expand,msdyn_rmareceipt_Filter,msdyn_rmareceipt_Fixed,msdyn_rmareceipt_Result,msdyn_rmareceipt_FormattedResult>;
  regardingobjectid_msdyn_rtv: WebMappingRetrieve<msdyn_rtv_Select,msdyn_rtv_Expand,msdyn_rtv_Filter,msdyn_rtv_Fixed,msdyn_rtv_Result,msdyn_rtv_FormattedResult>;
  regardingobjectid_msdyn_timegroup: WebMappingRetrieve<msdyn_timegroup_Select,msdyn_timegroup_Expand,msdyn_timegroup_Filter,msdyn_timegroup_Fixed,msdyn_timegroup_Result,msdyn_timegroup_FormattedResult>;
  regardingobjectid_msdyn_timegroupdetail: WebMappingRetrieve<msdyn_timegroupdetail_Select,msdyn_timegroupdetail_Expand,msdyn_timegroupdetail_Filter,msdyn_timegroupdetail_Fixed,msdyn_timegroupdetail_Result,msdyn_timegroupdetail_FormattedResult>;
  regardingobjectid_msdyn_warehouse: WebMappingRetrieve<msdyn_warehouse_Select,msdyn_warehouse_Expand,msdyn_warehouse_Filter,msdyn_warehouse_Fixed,msdyn_warehouse_Result,msdyn_warehouse_FormattedResult>;
  regardingobjectid_msdyn_workorder: WebMappingRetrieve<msdyn_workorder_Select,msdyn_workorder_Expand,msdyn_workorder_Filter,msdyn_workorder_Fixed,msdyn_workorder_Result,msdyn_workorder_FormattedResult>;
  regardingobjectid_msdyn_workorderincident: WebMappingRetrieve<msdyn_workorderincident_Select,msdyn_workorderincident_Expand,msdyn_workorderincident_Filter,msdyn_workorderincident_Fixed,msdyn_workorderincident_Result,msdyn_workorderincident_FormattedResult>;
  regardingobjectid_msdyn_workorderproduct: WebMappingRetrieve<msdyn_workorderproduct_Select,msdyn_workorderproduct_Expand,msdyn_workorderproduct_Filter,msdyn_workorderproduct_Fixed,msdyn_workorderproduct_Result,msdyn_workorderproduct_FormattedResult>;
  regardingobjectid_msdyn_workorderservice: WebMappingRetrieve<msdyn_workorderservice_Select,msdyn_workorderservice_Expand,msdyn_workorderservice_Filter,msdyn_workorderservice_Fixed,msdyn_workorderservice_Result,msdyn_workorderservice_FormattedResult>;
  regardingobjectid_msdyn_workorderservicetask: WebMappingRetrieve<msdyn_workorderservicetask_Select,msdyn_workorderservicetask_Expand,msdyn_workorderservicetask_Filter,msdyn_workorderservicetask_Fixed,msdyn_workorderservicetask_Result,msdyn_workorderservicetask_FormattedResult>;
  regardingobjectid_opportunity: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_opportunity1: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_product: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  regardingobjectid_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesliterature: WebMappingRetrieve<SalesLiterature_Select,SalesLiterature_Expand,SalesLiterature_Filter,SalesLiterature_Fixed,SalesLiterature_Result,SalesLiterature_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface SharePointDocument_RelatedMany {
  SharePointDocument_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
}
interface WebEntitiesRetrieve {
  sharepointdocuments: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
}
interface WebEntitiesRelated {
  sharepointdocuments: WebMappingRelated<SharePointDocument_RelatedOne,SharePointDocument_RelatedMany>;
}
interface WebEntitiesCUDA {
  sharepointdocuments: WebMappingCUDA<SharePointDocument_Create,SharePointDocument_Update,SharePointDocument_Select>;
}
