interface UII_hostedapplication_Base extends WebEntity {
  createdon?: Date | null;
  importsequencenumber?: number | null;
  modifiedon?: Date | null;
  msdyusd_allowmultiplepages?: boolean | null;
  msdyusd_apiversion?: msdyusd_uii_hostedapplication_msdyusd_apiversion | null;
  msdyusd_autolaunch?: boolean | null;
  msdyusd_cifurl?: string | null;
  msdyusd_crmwindowhosttype?: msdyusd_uii_hostedapplication_msdyusd_crmwindowhosttype | null;
  msdyusd_customparameters?: string | null;
  msdyusd_dashboardname?: string | null;
  msdyusd_displayname?: string | null;
  msdyusd_hostingtype?: msdyusd_uii_hostedapplication_msdyusd_hostingtype | null;
  msdyusd_maximumbrowsers?: number | null;
  msdyusd_paneltype?: msdyusd_uii_hostedapplication_msdyusd_paneltype | null;
  msdyusd_prefetchdata?: boolean | null;
  msdyusd_savedurl?: string | null;
  msdyusd_scanfordataparameters?: boolean | null;
  msdyusd_specifyurl?: boolean | null;
  msdyusd_trusteddomain?: string | null;
  msdyusd_xaml?: string | null;
  overriddencreatedon?: Date | null;
  statecode?: uii_hostedapplication_statecode | null;
  statuscode?: uii_hostedapplication_statuscode | null;
  timezoneruleversionnumber?: number | null;
  uii_adaptermode?: uii_hostedapplication_uii_adaptermode | null;
  uii_adaptertype?: string | null;
  uii_adapteruri?: string | null;
  uii_applicationhostingmode?: uii_hostedapplication_uii_applicationhostingmode | null;
  uii_assemblytype?: string | null;
  uii_assemblyuri?: string | null;
  uii_automationxml?: string | null;
  uii_displaygroup?: string | null;
  uii_extensionsxml?: string | null;
  uii_externalapparguments?: string | null;
  uii_externalappuri?: string | null;
  uii_externalappworkingdirectory?: string | null;
  uii_findwindowclass?: string | null;
  uii_hostedapplicationid?: string | null;
  uii_hostedapplicationtype?: uii_hostedapplication_uii_hostedapplicationtype | null;
  uii_icafilename?: string | null;
  uii_isappdynamic?: boolean | null;
  uii_isattachinputthread?: boolean | null;
  uii_isautosignon?: boolean | null;
  uii_isdependentonworkflow?: boolean | null;
  uii_isglobalapplication?: boolean | null;
  uii_islimittoprocess?: boolean | null;
  uii_isnomessagepump?: boolean | null;
  uii_isrestoreifminimized?: boolean | null;
  uii_isretainframeandcaption?: boolean | null;
  uii_isretainontaskbar?: boolean | null;
  uii_isretainsystemmenu?: boolean | null;
  uii_isshowintoolbardropdown?: boolean | null;
  uii_isshowmenu?: boolean | null;
  uii_isusenewbrowserprocess?: boolean | null;
  uii_iswebappusetoolbar?: boolean | null;
  uii_mainwindowacquisitiontimeout?: number | null;
  uii_managedapplication?: boolean | null;
  uii_managehosting?: boolean | null;
  uii_managepopups?: boolean | null;
  uii_minimumsizex?: number | null;
  uii_minimumsizey?: number | null;
  uii_name?: string | null;
  uii_optimalsizex?: number | null;
  uii_optimalsizey?: number | null;
  uii_processacquisitionfilename?: string | null;
  uii_remote_processacquisitionattempts?: number | null;
  uii_remote_processacquisitiondelay?: number | null;
  uii_removesizingcontrols?: boolean | null;
  uii_sortorder?: number | null;
  uii_toplevelwindowcaption?: string | null;
  uii_toplevelwindowmode?: uii_hostedapplication_uii_toplevelwindowmode | null;
  uii_usercanclose?: boolean | null;
  uii_webappurl?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface UII_hostedapplication_Relationships {
  msdyusd_AnswerShowTab?: msdyusd_answer_Result[] | null;
  msdyusd_ShowTab?: msdyusd_task_Result[] | null;
  msdyusd_configuration_hostedcontrol?: msdyusd_configuration_Result[] | null;
  msdyusd_form_hostedapplication?: msdyusd_form_Result[] | null;
  msdyusd_toolbarstrip_uii_hostedapplication?: msdyusd_toolbarstrip_Result[] | null;
  msdyusd_tracesourcesetting_hostedcontrol?: msdyusd_tracesourcesetting_Result[] | null;
  msdyusd_uii_hostedapplication_msdyusd_agentscriptaction_Application?: msdyusd_agentscriptaction_Result[] | null;
  msdyusd_uii_hostedapplication_msdyusd_languagemodule?: msdyusd_languagemodule_Result[] | null;
  msdyusd_uii_hostedapplication_msdyusd_toolbarbutton_showtab?: msdyusd_toolbarbutton_Result[] | null;
  msdyusd_uii_hostedapplication_msdyusd_uiievent?: msdyusd_uiievent_Result[] | null;
  msdyusd_uii_hostedapplication_msdyusd_windowroute_Application?: msdyusd_windowroute_Result[] | null;
  msdyusd_uii_hostedapplication_msdyusd_windowroute_From?: msdyusd_windowroute_Result[] | null;
  msdyusd_uii_hostedapplication_msdyusd_windowroute_showtab?: msdyusd_windowroute_Result[] | null;
  uii_hostedapplication_ActivityPointers?: ActivityPointer_Result[] | null;
  uii_hostedapplication_Annotations?: Annotation_Result[] | null;
  uii_hostedapplication_Appointments?: Appointment_Result[] | null;
  uii_hostedapplication_AsyncOperations?: AsyncOperation_Result[] | null;
  uii_hostedapplication_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  uii_hostedapplication_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  uii_hostedapplication_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  uii_hostedapplication_Emails?: Email_Result[] | null;
  uii_hostedapplication_Faxes?: Fax_Result[] | null;
  uii_hostedapplication_Letters?: Letter_Result[] | null;
  uii_hostedapplication_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  uii_hostedapplication_PhoneCalls?: PhoneCall_Result[] | null;
  uii_hostedapplication_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  uii_hostedapplication_ProcessSession?: ProcessSession_Result[] | null;
  uii_hostedapplication_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  uii_hostedapplication_ServiceAppointments?: ServiceAppointment_Result[] | null;
  uii_hostedapplication_SocialActivities?: SocialActivity_Result[] | null;
  uii_hostedapplication_SyncErrors?: SyncError_Result[] | null;
  uii_hostedapplication_Tasks?: Task_Result[] | null;
  uii_hostedapplication_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  uii_hostedapplication_msdyn_approvals?: msdyn_approval_Result[] | null;
  uii_hostedapplication_msdyn_bookingalerts?: msdyn_bookingalert_Result[] | null;
  uii_hostedapplication_msdyn_ocliveworkitems?: msdyn_ocliveworkitem_Result[] | null;
  uii_hostedapplication_msdyn_ocoutboundmessages?: msdyn_ocoutboundmessage_Result[] | null;
  uii_hostedapplication_msdyn_ocsessions?: msdyn_ocsession_Result[] | null;
  uii_hostedapplication_msfp_alerts?: msfp_alert_Result[] | null;
  uii_hostedapplication_msfp_surveyinvites?: msfp_surveyinvite_Result[] | null;
  uii_hostedapplication_msfp_surveyresponses?: msfp_surveyresponse_Result[] | null;
  uii_uii_hostedapplication_uii_action?: UII_action_Result[] | null;
  uii_uii_hostedapplication_uii_audit?: UII_audit_Result[] | null;
  uii_uii_hostedapplication_uii_workflowstep?: UII_workflowstep_Result[] | null;
}
interface UII_hostedapplication extends UII_hostedapplication_Base, UII_hostedapplication_Relationships {
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface UII_hostedapplication_Create extends UII_hostedapplication {
}
interface UII_hostedapplication_Update extends UII_hostedapplication {
}
interface UII_hostedapplication_Select {
  createdby_guid: WebAttribute<UII_hostedapplication_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<UII_hostedapplication_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<UII_hostedapplication_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  importsequencenumber: WebAttribute<UII_hostedapplication_Select, { importsequencenumber: number | null }, {  }>;
  modifiedby_guid: WebAttribute<UII_hostedapplication_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<UII_hostedapplication_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<UII_hostedapplication_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  msdyusd_allowmultiplepages: WebAttribute<UII_hostedapplication_Select, { msdyusd_allowmultiplepages: boolean | null }, {  }>;
  msdyusd_apiversion: WebAttribute<UII_hostedapplication_Select, { msdyusd_apiversion: msdyusd_uii_hostedapplication_msdyusd_apiversion | null }, { msdyusd_apiversion_formatted?: string }>;
  msdyusd_autolaunch: WebAttribute<UII_hostedapplication_Select, { msdyusd_autolaunch: boolean | null }, {  }>;
  msdyusd_cifurl: WebAttribute<UII_hostedapplication_Select, { msdyusd_cifurl: string | null }, {  }>;
  msdyusd_crmwindowhosttype: WebAttribute<UII_hostedapplication_Select, { msdyusd_crmwindowhosttype: msdyusd_uii_hostedapplication_msdyusd_crmwindowhosttype | null }, { msdyusd_crmwindowhosttype_formatted?: string }>;
  msdyusd_customparameters: WebAttribute<UII_hostedapplication_Select, { msdyusd_customparameters: string | null }, {  }>;
  msdyusd_dashboardname: WebAttribute<UII_hostedapplication_Select, { msdyusd_dashboardname: string | null }, {  }>;
  msdyusd_displayname: WebAttribute<UII_hostedapplication_Select, { msdyusd_displayname: string | null }, {  }>;
  msdyusd_hostingtype: WebAttribute<UII_hostedapplication_Select, { msdyusd_hostingtype: msdyusd_uii_hostedapplication_msdyusd_hostingtype | null }, { msdyusd_hostingtype_formatted?: string }>;
  msdyusd_maximumbrowsers: WebAttribute<UII_hostedapplication_Select, { msdyusd_maximumbrowsers: number | null }, {  }>;
  msdyusd_paneltype: WebAttribute<UII_hostedapplication_Select, { msdyusd_paneltype: msdyusd_uii_hostedapplication_msdyusd_paneltype | null }, { msdyusd_paneltype_formatted?: string }>;
  msdyusd_prefetchdata: WebAttribute<UII_hostedapplication_Select, { msdyusd_prefetchdata: boolean | null }, {  }>;
  msdyusd_savedurl: WebAttribute<UII_hostedapplication_Select, { msdyusd_savedurl: string | null }, {  }>;
  msdyusd_scanfordataparameters: WebAttribute<UII_hostedapplication_Select, { msdyusd_scanfordataparameters: boolean | null }, {  }>;
  msdyusd_specifyurl: WebAttribute<UII_hostedapplication_Select, { msdyusd_specifyurl: boolean | null }, {  }>;
  msdyusd_trusteddomain: WebAttribute<UII_hostedapplication_Select, { msdyusd_trusteddomain: string | null }, {  }>;
  msdyusd_xaml: WebAttribute<UII_hostedapplication_Select, { msdyusd_xaml: string | null }, {  }>;
  overriddencreatedon: WebAttribute<UII_hostedapplication_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<UII_hostedapplication_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<UII_hostedapplication_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<UII_hostedapplication_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<UII_hostedapplication_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  statecode: WebAttribute<UII_hostedapplication_Select, { statecode: uii_hostedapplication_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<UII_hostedapplication_Select, { statuscode: uii_hostedapplication_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<UII_hostedapplication_Select, { timezoneruleversionnumber: number | null }, {  }>;
  uii_adaptermode: WebAttribute<UII_hostedapplication_Select, { uii_adaptermode: uii_hostedapplication_uii_adaptermode | null }, { uii_adaptermode_formatted?: string }>;
  uii_adaptertype: WebAttribute<UII_hostedapplication_Select, { uii_adaptertype: string | null }, {  }>;
  uii_adapteruri: WebAttribute<UII_hostedapplication_Select, { uii_adapteruri: string | null }, {  }>;
  uii_applicationhostingmode: WebAttribute<UII_hostedapplication_Select, { uii_applicationhostingmode: uii_hostedapplication_uii_applicationhostingmode | null }, { uii_applicationhostingmode_formatted?: string }>;
  uii_assemblytype: WebAttribute<UII_hostedapplication_Select, { uii_assemblytype: string | null }, {  }>;
  uii_assemblyuri: WebAttribute<UII_hostedapplication_Select, { uii_assemblyuri: string | null }, {  }>;
  uii_automationxml: WebAttribute<UII_hostedapplication_Select, { uii_automationxml: string | null }, {  }>;
  uii_displaygroup: WebAttribute<UII_hostedapplication_Select, { uii_displaygroup: string | null }, {  }>;
  uii_extensionsxml: WebAttribute<UII_hostedapplication_Select, { uii_extensionsxml: string | null }, {  }>;
  uii_externalapparguments: WebAttribute<UII_hostedapplication_Select, { uii_externalapparguments: string | null }, {  }>;
  uii_externalappuri: WebAttribute<UII_hostedapplication_Select, { uii_externalappuri: string | null }, {  }>;
  uii_externalappworkingdirectory: WebAttribute<UII_hostedapplication_Select, { uii_externalappworkingdirectory: string | null }, {  }>;
  uii_findwindowclass: WebAttribute<UII_hostedapplication_Select, { uii_findwindowclass: string | null }, {  }>;
  uii_hostedapplicationid: WebAttribute<UII_hostedapplication_Select, { uii_hostedapplicationid: string | null }, {  }>;
  uii_hostedapplicationtype: WebAttribute<UII_hostedapplication_Select, { uii_hostedapplicationtype: uii_hostedapplication_uii_hostedapplicationtype | null }, { uii_hostedapplicationtype_formatted?: string }>;
  uii_icafilename: WebAttribute<UII_hostedapplication_Select, { uii_icafilename: string | null }, {  }>;
  uii_isappdynamic: WebAttribute<UII_hostedapplication_Select, { uii_isappdynamic: boolean | null }, {  }>;
  uii_isattachinputthread: WebAttribute<UII_hostedapplication_Select, { uii_isattachinputthread: boolean | null }, {  }>;
  uii_isautosignon: WebAttribute<UII_hostedapplication_Select, { uii_isautosignon: boolean | null }, {  }>;
  uii_isdependentonworkflow: WebAttribute<UII_hostedapplication_Select, { uii_isdependentonworkflow: boolean | null }, {  }>;
  uii_isglobalapplication: WebAttribute<UII_hostedapplication_Select, { uii_isglobalapplication: boolean | null }, {  }>;
  uii_islimittoprocess: WebAttribute<UII_hostedapplication_Select, { uii_islimittoprocess: boolean | null }, {  }>;
  uii_isnomessagepump: WebAttribute<UII_hostedapplication_Select, { uii_isnomessagepump: boolean | null }, {  }>;
  uii_isrestoreifminimized: WebAttribute<UII_hostedapplication_Select, { uii_isrestoreifminimized: boolean | null }, {  }>;
  uii_isretainframeandcaption: WebAttribute<UII_hostedapplication_Select, { uii_isretainframeandcaption: boolean | null }, {  }>;
  uii_isretainontaskbar: WebAttribute<UII_hostedapplication_Select, { uii_isretainontaskbar: boolean | null }, {  }>;
  uii_isretainsystemmenu: WebAttribute<UII_hostedapplication_Select, { uii_isretainsystemmenu: boolean | null }, {  }>;
  uii_isshowintoolbardropdown: WebAttribute<UII_hostedapplication_Select, { uii_isshowintoolbardropdown: boolean | null }, {  }>;
  uii_isshowmenu: WebAttribute<UII_hostedapplication_Select, { uii_isshowmenu: boolean | null }, {  }>;
  uii_isusenewbrowserprocess: WebAttribute<UII_hostedapplication_Select, { uii_isusenewbrowserprocess: boolean | null }, {  }>;
  uii_iswebappusetoolbar: WebAttribute<UII_hostedapplication_Select, { uii_iswebappusetoolbar: boolean | null }, {  }>;
  uii_mainwindowacquisitiontimeout: WebAttribute<UII_hostedapplication_Select, { uii_mainwindowacquisitiontimeout: number | null }, {  }>;
  uii_managedapplication: WebAttribute<UII_hostedapplication_Select, { uii_managedapplication: boolean | null }, {  }>;
  uii_managehosting: WebAttribute<UII_hostedapplication_Select, { uii_managehosting: boolean | null }, {  }>;
  uii_managepopups: WebAttribute<UII_hostedapplication_Select, { uii_managepopups: boolean | null }, {  }>;
  uii_minimumsizex: WebAttribute<UII_hostedapplication_Select, { uii_minimumsizex: number | null }, {  }>;
  uii_minimumsizey: WebAttribute<UII_hostedapplication_Select, { uii_minimumsizey: number | null }, {  }>;
  uii_name: WebAttribute<UII_hostedapplication_Select, { uii_name: string | null }, {  }>;
  uii_optimalsizex: WebAttribute<UII_hostedapplication_Select, { uii_optimalsizex: number | null }, {  }>;
  uii_optimalsizey: WebAttribute<UII_hostedapplication_Select, { uii_optimalsizey: number | null }, {  }>;
  uii_processacquisitionfilename: WebAttribute<UII_hostedapplication_Select, { uii_processacquisitionfilename: string | null }, {  }>;
  uii_remote_processacquisitionattempts: WebAttribute<UII_hostedapplication_Select, { uii_remote_processacquisitionattempts: number | null }, {  }>;
  uii_remote_processacquisitiondelay: WebAttribute<UII_hostedapplication_Select, { uii_remote_processacquisitiondelay: number | null }, {  }>;
  uii_removesizingcontrols: WebAttribute<UII_hostedapplication_Select, { uii_removesizingcontrols: boolean | null }, {  }>;
  uii_sortorder: WebAttribute<UII_hostedapplication_Select, { uii_sortorder: number | null }, {  }>;
  uii_toplevelwindowcaption: WebAttribute<UII_hostedapplication_Select, { uii_toplevelwindowcaption: string | null }, {  }>;
  uii_toplevelwindowmode: WebAttribute<UII_hostedapplication_Select, { uii_toplevelwindowmode: uii_hostedapplication_uii_toplevelwindowmode | null }, { uii_toplevelwindowmode_formatted?: string }>;
  uii_usercanclose: WebAttribute<UII_hostedapplication_Select, { uii_usercanclose: boolean | null }, {  }>;
  uii_webappurl: WebAttribute<UII_hostedapplication_Select, { uii_webappurl: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<UII_hostedapplication_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<UII_hostedapplication_Select, { versionnumber: number | null }, {  }>;
}
interface UII_hostedapplication_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  importsequencenumber: number;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  msdyusd_allowmultiplepages: boolean;
  msdyusd_apiversion: msdyusd_uii_hostedapplication_msdyusd_apiversion;
  msdyusd_autolaunch: boolean;
  msdyusd_cifurl: string;
  msdyusd_crmwindowhosttype: msdyusd_uii_hostedapplication_msdyusd_crmwindowhosttype;
  msdyusd_customparameters: string;
  msdyusd_dashboardname: string;
  msdyusd_displayname: string;
  msdyusd_hostingtype: msdyusd_uii_hostedapplication_msdyusd_hostingtype;
  msdyusd_maximumbrowsers: number;
  msdyusd_paneltype: msdyusd_uii_hostedapplication_msdyusd_paneltype;
  msdyusd_prefetchdata: boolean;
  msdyusd_savedurl: string;
  msdyusd_scanfordataparameters: boolean;
  msdyusd_specifyurl: boolean;
  msdyusd_trusteddomain: string;
  msdyusd_xaml: string;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  statecode: uii_hostedapplication_statecode;
  statuscode: uii_hostedapplication_statuscode;
  timezoneruleversionnumber: number;
  uii_adaptermode: uii_hostedapplication_uii_adaptermode;
  uii_adaptertype: string;
  uii_adapteruri: string;
  uii_applicationhostingmode: uii_hostedapplication_uii_applicationhostingmode;
  uii_assemblytype: string;
  uii_assemblyuri: string;
  uii_automationxml: string;
  uii_displaygroup: string;
  uii_extensionsxml: string;
  uii_externalapparguments: string;
  uii_externalappuri: string;
  uii_externalappworkingdirectory: string;
  uii_findwindowclass: string;
  uii_hostedapplicationid: XQW.Guid;
  uii_hostedapplicationtype: uii_hostedapplication_uii_hostedapplicationtype;
  uii_icafilename: string;
  uii_isappdynamic: boolean;
  uii_isattachinputthread: boolean;
  uii_isautosignon: boolean;
  uii_isdependentonworkflow: boolean;
  uii_isglobalapplication: boolean;
  uii_islimittoprocess: boolean;
  uii_isnomessagepump: boolean;
  uii_isrestoreifminimized: boolean;
  uii_isretainframeandcaption: boolean;
  uii_isretainontaskbar: boolean;
  uii_isretainsystemmenu: boolean;
  uii_isshowintoolbardropdown: boolean;
  uii_isshowmenu: boolean;
  uii_isusenewbrowserprocess: boolean;
  uii_iswebappusetoolbar: boolean;
  uii_mainwindowacquisitiontimeout: number;
  uii_managedapplication: boolean;
  uii_managehosting: boolean;
  uii_managepopups: boolean;
  uii_minimumsizex: number;
  uii_minimumsizey: number;
  uii_name: string;
  uii_optimalsizex: number;
  uii_optimalsizey: number;
  uii_processacquisitionfilename: string;
  uii_remote_processacquisitionattempts: number;
  uii_remote_processacquisitiondelay: number;
  uii_removesizingcontrols: boolean;
  uii_sortorder: number;
  uii_toplevelwindowcaption: string;
  uii_toplevelwindowmode: uii_hostedapplication_uii_toplevelwindowmode;
  uii_usercanclose: boolean;
  uii_webappurl: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface UII_hostedapplication_Expand {
  createdby: WebExpand<UII_hostedapplication_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<UII_hostedapplication_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<UII_hostedapplication_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<UII_hostedapplication_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyusd_AnswerShowTab: WebExpand<UII_hostedapplication_Expand, msdyusd_answer_Select, msdyusd_answer_Filter, { msdyusd_AnswerShowTab: msdyusd_answer_Result[] }>;
  msdyusd_ShowTab: WebExpand<UII_hostedapplication_Expand, msdyusd_task_Select, msdyusd_task_Filter, { msdyusd_ShowTab: msdyusd_task_Result[] }>;
  msdyusd_configuration_hostedcontrol: WebExpand<UII_hostedapplication_Expand, msdyusd_configuration_Select, msdyusd_configuration_Filter, { msdyusd_configuration_hostedcontrol: msdyusd_configuration_Result[] }>;
  msdyusd_form_hostedapplication: WebExpand<UII_hostedapplication_Expand, msdyusd_form_Select, msdyusd_form_Filter, { msdyusd_form_hostedapplication: msdyusd_form_Result[] }>;
  msdyusd_toolbarstrip_uii_hostedapplication: WebExpand<UII_hostedapplication_Expand, msdyusd_toolbarstrip_Select, msdyusd_toolbarstrip_Filter, { msdyusd_toolbarstrip_uii_hostedapplication: msdyusd_toolbarstrip_Result[] }>;
  msdyusd_tracesourcesetting_hostedcontrol: WebExpand<UII_hostedapplication_Expand, msdyusd_tracesourcesetting_Select, msdyusd_tracesourcesetting_Filter, { msdyusd_tracesourcesetting_hostedcontrol: msdyusd_tracesourcesetting_Result[] }>;
  msdyusd_uii_hostedapplication_msdyusd_agentscriptaction_Application: WebExpand<UII_hostedapplication_Expand, msdyusd_agentscriptaction_Select, msdyusd_agentscriptaction_Filter, { msdyusd_uii_hostedapplication_msdyusd_agentscriptaction_Application: msdyusd_agentscriptaction_Result[] }>;
  msdyusd_uii_hostedapplication_msdyusd_languagemodule: WebExpand<UII_hostedapplication_Expand, msdyusd_languagemodule_Select, msdyusd_languagemodule_Filter, { msdyusd_uii_hostedapplication_msdyusd_languagemodule: msdyusd_languagemodule_Result[] }>;
  msdyusd_uii_hostedapplication_msdyusd_toolbarbutton_showtab: WebExpand<UII_hostedapplication_Expand, msdyusd_toolbarbutton_Select, msdyusd_toolbarbutton_Filter, { msdyusd_uii_hostedapplication_msdyusd_toolbarbutton_showtab: msdyusd_toolbarbutton_Result[] }>;
  msdyusd_uii_hostedapplication_msdyusd_uiievent: WebExpand<UII_hostedapplication_Expand, msdyusd_uiievent_Select, msdyusd_uiievent_Filter, { msdyusd_uii_hostedapplication_msdyusd_uiievent: msdyusd_uiievent_Result[] }>;
  msdyusd_uii_hostedapplication_msdyusd_windowroute_Application: WebExpand<UII_hostedapplication_Expand, msdyusd_windowroute_Select, msdyusd_windowroute_Filter, { msdyusd_uii_hostedapplication_msdyusd_windowroute_Application: msdyusd_windowroute_Result[] }>;
  msdyusd_uii_hostedapplication_msdyusd_windowroute_From: WebExpand<UII_hostedapplication_Expand, msdyusd_windowroute_Select, msdyusd_windowroute_Filter, { msdyusd_uii_hostedapplication_msdyusd_windowroute_From: msdyusd_windowroute_Result[] }>;
  msdyusd_uii_hostedapplication_msdyusd_windowroute_showtab: WebExpand<UII_hostedapplication_Expand, msdyusd_windowroute_Select, msdyusd_windowroute_Filter, { msdyusd_uii_hostedapplication_msdyusd_windowroute_showtab: msdyusd_windowroute_Result[] }>;
  ownerid: WebExpand<UII_hostedapplication_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<UII_hostedapplication_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<UII_hostedapplication_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<UII_hostedapplication_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  uii_hostedapplication_ActivityPointers: WebExpand<UII_hostedapplication_Expand, ActivityPointer_Select, ActivityPointer_Filter, { uii_hostedapplication_ActivityPointers: ActivityPointer_Result[] }>;
  uii_hostedapplication_Annotations: WebExpand<UII_hostedapplication_Expand, Annotation_Select, Annotation_Filter, { uii_hostedapplication_Annotations: Annotation_Result[] }>;
  uii_hostedapplication_Appointments: WebExpand<UII_hostedapplication_Expand, Appointment_Select, Appointment_Filter, { uii_hostedapplication_Appointments: Appointment_Result[] }>;
  uii_hostedapplication_AsyncOperations: WebExpand<UII_hostedapplication_Expand, AsyncOperation_Select, AsyncOperation_Filter, { uii_hostedapplication_AsyncOperations: AsyncOperation_Result[] }>;
  uii_hostedapplication_BulkDeleteFailures: WebExpand<UII_hostedapplication_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { uii_hostedapplication_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  uii_hostedapplication_DuplicateBaseRecord: WebExpand<UII_hostedapplication_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { uii_hostedapplication_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  uii_hostedapplication_DuplicateMatchingRecord: WebExpand<UII_hostedapplication_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { uii_hostedapplication_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  uii_hostedapplication_Emails: WebExpand<UII_hostedapplication_Expand, Email_Select, Email_Filter, { uii_hostedapplication_Emails: Email_Result[] }>;
  uii_hostedapplication_Faxes: WebExpand<UII_hostedapplication_Expand, Fax_Select, Fax_Filter, { uii_hostedapplication_Faxes: Fax_Result[] }>;
  uii_hostedapplication_Letters: WebExpand<UII_hostedapplication_Expand, Letter_Select, Letter_Filter, { uii_hostedapplication_Letters: Letter_Result[] }>;
  uii_hostedapplication_MailboxTrackingFolders: WebExpand<UII_hostedapplication_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { uii_hostedapplication_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  uii_hostedapplication_PhoneCalls: WebExpand<UII_hostedapplication_Expand, PhoneCall_Select, PhoneCall_Filter, { uii_hostedapplication_PhoneCalls: PhoneCall_Result[] }>;
  uii_hostedapplication_PrincipalObjectAttributeAccesses: WebExpand<UII_hostedapplication_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { uii_hostedapplication_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  uii_hostedapplication_ProcessSession: WebExpand<UII_hostedapplication_Expand, ProcessSession_Select, ProcessSession_Filter, { uii_hostedapplication_ProcessSession: ProcessSession_Result[] }>;
  uii_hostedapplication_RecurringAppointmentMasters: WebExpand<UII_hostedapplication_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { uii_hostedapplication_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  uii_hostedapplication_ServiceAppointments: WebExpand<UII_hostedapplication_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { uii_hostedapplication_ServiceAppointments: ServiceAppointment_Result[] }>;
  uii_hostedapplication_SocialActivities: WebExpand<UII_hostedapplication_Expand, SocialActivity_Select, SocialActivity_Filter, { uii_hostedapplication_SocialActivities: SocialActivity_Result[] }>;
  uii_hostedapplication_SyncErrors: WebExpand<UII_hostedapplication_Expand, SyncError_Select, SyncError_Filter, { uii_hostedapplication_SyncErrors: SyncError_Result[] }>;
  uii_hostedapplication_Tasks: WebExpand<UII_hostedapplication_Expand, Task_Select, Task_Filter, { uii_hostedapplication_Tasks: Task_Result[] }>;
  uii_hostedapplication_UserEntityInstanceDatas: WebExpand<UII_hostedapplication_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { uii_hostedapplication_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  uii_hostedapplication_msdyn_approvals: WebExpand<UII_hostedapplication_Expand, msdyn_approval_Select, msdyn_approval_Filter, { uii_hostedapplication_msdyn_approvals: msdyn_approval_Result[] }>;
  uii_hostedapplication_msdyn_bookingalerts: WebExpand<UII_hostedapplication_Expand, msdyn_bookingalert_Select, msdyn_bookingalert_Filter, { uii_hostedapplication_msdyn_bookingalerts: msdyn_bookingalert_Result[] }>;
  uii_hostedapplication_msdyn_ocliveworkitems: WebExpand<UII_hostedapplication_Expand, msdyn_ocliveworkitem_Select, msdyn_ocliveworkitem_Filter, { uii_hostedapplication_msdyn_ocliveworkitems: msdyn_ocliveworkitem_Result[] }>;
  uii_hostedapplication_msdyn_ocoutboundmessages: WebExpand<UII_hostedapplication_Expand, msdyn_ocoutboundmessage_Select, msdyn_ocoutboundmessage_Filter, { uii_hostedapplication_msdyn_ocoutboundmessages: msdyn_ocoutboundmessage_Result[] }>;
  uii_hostedapplication_msdyn_ocsessions: WebExpand<UII_hostedapplication_Expand, msdyn_ocsession_Select, msdyn_ocsession_Filter, { uii_hostedapplication_msdyn_ocsessions: msdyn_ocsession_Result[] }>;
  uii_hostedapplication_msfp_alerts: WebExpand<UII_hostedapplication_Expand, msfp_alert_Select, msfp_alert_Filter, { uii_hostedapplication_msfp_alerts: msfp_alert_Result[] }>;
  uii_hostedapplication_msfp_surveyinvites: WebExpand<UII_hostedapplication_Expand, msfp_surveyinvite_Select, msfp_surveyinvite_Filter, { uii_hostedapplication_msfp_surveyinvites: msfp_surveyinvite_Result[] }>;
  uii_hostedapplication_msfp_surveyresponses: WebExpand<UII_hostedapplication_Expand, msfp_surveyresponse_Select, msfp_surveyresponse_Filter, { uii_hostedapplication_msfp_surveyresponses: msfp_surveyresponse_Result[] }>;
  uii_uii_hostedapplication_uii_action: WebExpand<UII_hostedapplication_Expand, UII_action_Select, UII_action_Filter, { uii_uii_hostedapplication_uii_action: UII_action_Result[] }>;
  uii_uii_hostedapplication_uii_audit: WebExpand<UII_hostedapplication_Expand, UII_audit_Select, UII_audit_Filter, { uii_uii_hostedapplication_uii_audit: UII_audit_Result[] }>;
  uii_uii_hostedapplication_uii_workflowstep: WebExpand<UII_hostedapplication_Expand, UII_workflowstep_Select, UII_workflowstep_Filter, { uii_uii_hostedapplication_uii_workflowstep: UII_workflowstep_Result[] }>;
}
interface UII_hostedapplication_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  msdyusd_apiversion_formatted?: string;
  msdyusd_crmwindowhosttype_formatted?: string;
  msdyusd_hostingtype_formatted?: string;
  msdyusd_paneltype_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  uii_adaptermode_formatted?: string;
  uii_applicationhostingmode_formatted?: string;
  uii_hostedapplicationtype_formatted?: string;
  uii_toplevelwindowmode_formatted?: string;
}
interface UII_hostedapplication_Result extends UII_hostedapplication_Base, UII_hostedapplication_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface UII_hostedapplication_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface UII_hostedapplication_RelatedMany {
  msdyusd_AnswerShowTab: WebMappingRetrieve<msdyusd_answer_Select,msdyusd_answer_Expand,msdyusd_answer_Filter,msdyusd_answer_Fixed,msdyusd_answer_Result,msdyusd_answer_FormattedResult>;
  msdyusd_ShowTab: WebMappingRetrieve<msdyusd_task_Select,msdyusd_task_Expand,msdyusd_task_Filter,msdyusd_task_Fixed,msdyusd_task_Result,msdyusd_task_FormattedResult>;
  msdyusd_configuration_hostedcontrol: WebMappingRetrieve<msdyusd_configuration_Select,msdyusd_configuration_Expand,msdyusd_configuration_Filter,msdyusd_configuration_Fixed,msdyusd_configuration_Result,msdyusd_configuration_FormattedResult>;
  msdyusd_form_hostedapplication: WebMappingRetrieve<msdyusd_form_Select,msdyusd_form_Expand,msdyusd_form_Filter,msdyusd_form_Fixed,msdyusd_form_Result,msdyusd_form_FormattedResult>;
  msdyusd_toolbarstrip_uii_hostedapplication: WebMappingRetrieve<msdyusd_toolbarstrip_Select,msdyusd_toolbarstrip_Expand,msdyusd_toolbarstrip_Filter,msdyusd_toolbarstrip_Fixed,msdyusd_toolbarstrip_Result,msdyusd_toolbarstrip_FormattedResult>;
  msdyusd_tracesourcesetting_hostedcontrol: WebMappingRetrieve<msdyusd_tracesourcesetting_Select,msdyusd_tracesourcesetting_Expand,msdyusd_tracesourcesetting_Filter,msdyusd_tracesourcesetting_Fixed,msdyusd_tracesourcesetting_Result,msdyusd_tracesourcesetting_FormattedResult>;
  msdyusd_uii_hostedapplication_msdyusd_agentscriptaction_Application: WebMappingRetrieve<msdyusd_agentscriptaction_Select,msdyusd_agentscriptaction_Expand,msdyusd_agentscriptaction_Filter,msdyusd_agentscriptaction_Fixed,msdyusd_agentscriptaction_Result,msdyusd_agentscriptaction_FormattedResult>;
  msdyusd_uii_hostedapplication_msdyusd_languagemodule: WebMappingRetrieve<msdyusd_languagemodule_Select,msdyusd_languagemodule_Expand,msdyusd_languagemodule_Filter,msdyusd_languagemodule_Fixed,msdyusd_languagemodule_Result,msdyusd_languagemodule_FormattedResult>;
  msdyusd_uii_hostedapplication_msdyusd_toolbarbutton_showtab: WebMappingRetrieve<msdyusd_toolbarbutton_Select,msdyusd_toolbarbutton_Expand,msdyusd_toolbarbutton_Filter,msdyusd_toolbarbutton_Fixed,msdyusd_toolbarbutton_Result,msdyusd_toolbarbutton_FormattedResult>;
  msdyusd_uii_hostedapplication_msdyusd_uiievent: WebMappingRetrieve<msdyusd_uiievent_Select,msdyusd_uiievent_Expand,msdyusd_uiievent_Filter,msdyusd_uiievent_Fixed,msdyusd_uiievent_Result,msdyusd_uiievent_FormattedResult>;
  msdyusd_uii_hostedapplication_msdyusd_windowroute_Application: WebMappingRetrieve<msdyusd_windowroute_Select,msdyusd_windowroute_Expand,msdyusd_windowroute_Filter,msdyusd_windowroute_Fixed,msdyusd_windowroute_Result,msdyusd_windowroute_FormattedResult>;
  msdyusd_uii_hostedapplication_msdyusd_windowroute_From: WebMappingRetrieve<msdyusd_windowroute_Select,msdyusd_windowroute_Expand,msdyusd_windowroute_Filter,msdyusd_windowroute_Fixed,msdyusd_windowroute_Result,msdyusd_windowroute_FormattedResult>;
  msdyusd_uii_hostedapplication_msdyusd_windowroute_showtab: WebMappingRetrieve<msdyusd_windowroute_Select,msdyusd_windowroute_Expand,msdyusd_windowroute_Filter,msdyusd_windowroute_Fixed,msdyusd_windowroute_Result,msdyusd_windowroute_FormattedResult>;
  uii_hostedapplication_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  uii_hostedapplication_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  uii_hostedapplication_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  uii_hostedapplication_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  uii_hostedapplication_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  uii_hostedapplication_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  uii_hostedapplication_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  uii_hostedapplication_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  uii_hostedapplication_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  uii_hostedapplication_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  uii_hostedapplication_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  uii_hostedapplication_PhoneCalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  uii_hostedapplication_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  uii_hostedapplication_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  uii_hostedapplication_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  uii_hostedapplication_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  uii_hostedapplication_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  uii_hostedapplication_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  uii_hostedapplication_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  uii_hostedapplication_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  uii_hostedapplication_msdyn_approvals: WebMappingRetrieve<msdyn_approval_Select,msdyn_approval_Expand,msdyn_approval_Filter,msdyn_approval_Fixed,msdyn_approval_Result,msdyn_approval_FormattedResult>;
  uii_hostedapplication_msdyn_bookingalerts: WebMappingRetrieve<msdyn_bookingalert_Select,msdyn_bookingalert_Expand,msdyn_bookingalert_Filter,msdyn_bookingalert_Fixed,msdyn_bookingalert_Result,msdyn_bookingalert_FormattedResult>;
  uii_hostedapplication_msdyn_ocliveworkitems: WebMappingRetrieve<msdyn_ocliveworkitem_Select,msdyn_ocliveworkitem_Expand,msdyn_ocliveworkitem_Filter,msdyn_ocliveworkitem_Fixed,msdyn_ocliveworkitem_Result,msdyn_ocliveworkitem_FormattedResult>;
  uii_hostedapplication_msdyn_ocoutboundmessages: WebMappingRetrieve<msdyn_ocoutboundmessage_Select,msdyn_ocoutboundmessage_Expand,msdyn_ocoutboundmessage_Filter,msdyn_ocoutboundmessage_Fixed,msdyn_ocoutboundmessage_Result,msdyn_ocoutboundmessage_FormattedResult>;
  uii_hostedapplication_msdyn_ocsessions: WebMappingRetrieve<msdyn_ocsession_Select,msdyn_ocsession_Expand,msdyn_ocsession_Filter,msdyn_ocsession_Fixed,msdyn_ocsession_Result,msdyn_ocsession_FormattedResult>;
  uii_hostedapplication_msfp_alerts: WebMappingRetrieve<msfp_alert_Select,msfp_alert_Expand,msfp_alert_Filter,msfp_alert_Fixed,msfp_alert_Result,msfp_alert_FormattedResult>;
  uii_hostedapplication_msfp_surveyinvites: WebMappingRetrieve<msfp_surveyinvite_Select,msfp_surveyinvite_Expand,msfp_surveyinvite_Filter,msfp_surveyinvite_Fixed,msfp_surveyinvite_Result,msfp_surveyinvite_FormattedResult>;
  uii_hostedapplication_msfp_surveyresponses: WebMappingRetrieve<msfp_surveyresponse_Select,msfp_surveyresponse_Expand,msfp_surveyresponse_Filter,msfp_surveyresponse_Fixed,msfp_surveyresponse_Result,msfp_surveyresponse_FormattedResult>;
  uii_uii_hostedapplication_uii_action: WebMappingRetrieve<UII_action_Select,UII_action_Expand,UII_action_Filter,UII_action_Fixed,UII_action_Result,UII_action_FormattedResult>;
  uii_uii_hostedapplication_uii_audit: WebMappingRetrieve<UII_audit_Select,UII_audit_Expand,UII_audit_Filter,UII_audit_Fixed,UII_audit_Result,UII_audit_FormattedResult>;
  uii_uii_hostedapplication_uii_workflowstep: WebMappingRetrieve<UII_workflowstep_Select,UII_workflowstep_Expand,UII_workflowstep_Filter,UII_workflowstep_Fixed,UII_workflowstep_Result,UII_workflowstep_FormattedResult>;
}
interface WebEntitiesRetrieve {
  uii_hostedapplications: WebMappingRetrieve<UII_hostedapplication_Select,UII_hostedapplication_Expand,UII_hostedapplication_Filter,UII_hostedapplication_Fixed,UII_hostedapplication_Result,UII_hostedapplication_FormattedResult>;
}
interface WebEntitiesRelated {
  uii_hostedapplications: WebMappingRelated<UII_hostedapplication_RelatedOne,UII_hostedapplication_RelatedMany>;
}
interface WebEntitiesCUDA {
  uii_hostedapplications: WebMappingCUDA<UII_hostedapplication_Create,UII_hostedapplication_Update,UII_hostedapplication_Select>;
}
