declare namespace Form.msdyn_quotelinetransaction.Main {
  namespace ProjectInformation {
    namespace Tabs {
      interface SummaryTab extends Xrm.SectionCollectionBase {
        get(name: "SummaryTab_section_2"): Xrm.PageSection;
        get(name: "SummaryTab_section_3"): Xrm.PageSection;
        get(name: "tab_2_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface _1c4a4b5314d240799d6a4fd07d7e8a2b extends Xrm.SectionCollectionBase {
        get(name: "AmountSection"): Xrm.PageSection;
        get(name: "BillingSection"): Xrm.PageSection;
        get(name: "DateSection"): Xrm.PageSection;
        get(name: "GeneralSection"): Xrm.PageSection;
        get(name: "ProductResourceSection"): Xrm.PageSection;
        get(name: "ProjectSection"): Xrm.PageSection;
        get(name: "QuantitySection"): Xrm.PageSection;
        get(name: "VendorSection"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "msdyn_accountcustomer"): Xrm.LookupAttribute<"account">;
      get(name: "msdyn_accountvendor"): Xrm.LookupAttribute<"account">;
      get(name: "msdyn_amount"): Xrm.NumberAttribute;
      get(name: "msdyn_amount_after_tax"): Xrm.NumberAttribute;
      get(name: "msdyn_amountmethod"): Xrm.OptionSetAttribute<msdyn_amountmethod>;
      get(name: "msdyn_basisamount"): Xrm.NumberAttribute;
      get(name: "msdyn_basisquantity"): Xrm.NumberAttribute;
      get(name: "msdyn_billingtype"): Xrm.OptionSetAttribute<msdyn_billingtype>;
      get(name: "msdyn_bookableresource"): Xrm.LookupAttribute<"bookableresource">;
      get(name: "msdyn_contactcustomer"): Xrm.LookupAttribute<"contact">;
      get(name: "msdyn_contactvendor"): Xrm.LookupAttribute<"contact">;
      get(name: "msdyn_customertype"): Xrm.OptionSetAttribute<msdyn_partytype>;
      get(name: "msdyn_description"): Xrm.Attribute<string>;
      get(name: "msdyn_documentdate"): Xrm.DateAttribute;
      get(name: "msdyn_enddatetime"): Xrm.DateAttribute;
      get(name: "msdyn_origin"): Xrm.LookupAttribute<"msdyn_quotelinetransaction">;
      get(name: "msdyn_percent"): Xrm.NumberAttribute;
      get(name: "msdyn_price"): Xrm.NumberAttribute;
      get(name: "msdyn_pricelist"): Xrm.LookupAttribute<"pricelevel">;
      get(name: "msdyn_product"): Xrm.LookupAttribute<"product">;
      get(name: "msdyn_project"): Xrm.LookupAttribute<"msdyn_project">;
      get(name: "msdyn_quantity"): Xrm.NumberAttribute;
      get(name: "msdyn_quoteid"): Xrm.LookupAttribute<"quote">;
      get(name: "msdyn_quotelineid"): Xrm.LookupAttribute<"quotedetail">;
      get(name: "msdyn_resourcecategory"): Xrm.LookupAttribute<"bookableresourcecategory">;
      get(name: "msdyn_resourceorganizationalunitid"): Xrm.LookupAttribute<"msdyn_organizationalunit">;
      get(name: "msdyn_startdatetime"): Xrm.DateAttribute;
      get(name: "msdyn_task"): Xrm.LookupAttribute<"msdyn_projecttask">;
      get(name: "msdyn_tax"): Xrm.NumberAttribute;
      get(name: "msdyn_transactioncategory"): Xrm.LookupAttribute<"msdyn_transactioncategory">;
      get(name: "msdyn_transactionclassification"): Xrm.OptionSetAttribute<msdyn_transactionclassification>;
      get(name: "msdyn_transactiontypecode"): Xrm.OptionSetAttribute<msdyn_transactiontypecode>;
      get(name: "msdyn_unit"): Xrm.LookupAttribute<"uom">;
      get(name: "msdyn_unitschedule"): Xrm.LookupAttribute<"uomschedule">;
      get(name: "msdyn_vendortype"): Xrm.OptionSetAttribute<msdyn_partytype>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "transactioncurrencyid"): Xrm.LookupAttribute<"transactioncurrency">;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "msdyn_accountcustomer"): Xrm.LookupControl<"account">;
      get(name: "msdyn_accountvendor"): Xrm.LookupControl<"account">;
      get(name: "msdyn_amount"): Xrm.NumberControl;
      get(name: "msdyn_amount1"): Xrm.NumberControl;
      get(name: "msdyn_amount_after_tax"): Xrm.NumberControl;
      get(name: "msdyn_amountmethod"): Xrm.OptionSetControl<msdyn_amountmethod>;
      get(name: "msdyn_basisamount"): Xrm.NumberControl;
      get(name: "msdyn_basisquantity"): Xrm.NumberControl;
      get(name: "msdyn_billingtype"): Xrm.OptionSetControl<msdyn_billingtype>;
      get(name: "msdyn_billingtype1"): Xrm.OptionSetControl<msdyn_billingtype>;
      get(name: "msdyn_bookableresource"): Xrm.LookupControl<"bookableresource">;
      get(name: "msdyn_contactcustomer"): Xrm.LookupControl<"contact">;
      get(name: "msdyn_contactvendor"): Xrm.LookupControl<"contact">;
      get(name: "msdyn_customertype"): Xrm.OptionSetControl<msdyn_partytype>;
      get(name: "msdyn_description"): Xrm.StringControl;
      get(name: "msdyn_description1"): Xrm.StringControl;
      get(name: "msdyn_documentdate"): Xrm.DateControl;
      get(name: "msdyn_enddatetime"): Xrm.DateControl;
      get(name: "msdyn_enddatetime1"): Xrm.DateControl;
      get(name: "msdyn_origin"): Xrm.LookupControl<"msdyn_quotelinetransaction">;
      get(name: "msdyn_percent"): Xrm.NumberControl;
      get(name: "msdyn_price"): Xrm.NumberControl;
      get(name: "msdyn_price1"): Xrm.NumberControl;
      get(name: "msdyn_pricelist"): Xrm.LookupControl<"pricelevel">;
      get(name: "msdyn_pricelist1"): Xrm.LookupControl<"pricelevel">;
      get(name: "msdyn_product"): Xrm.LookupControl<"product">;
      get(name: "msdyn_project"): Xrm.LookupControl<"msdyn_project">;
      get(name: "msdyn_quantity"): Xrm.NumberControl;
      get(name: "msdyn_quantity1"): Xrm.NumberControl;
      get(name: "msdyn_quoteid"): Xrm.LookupControl<"quote">;
      get(name: "msdyn_quoteid1"): Xrm.LookupControl<"quote">;
      get(name: "msdyn_quotelineid"): Xrm.LookupControl<"quotedetail">;
      get(name: "msdyn_resourcecategory"): Xrm.LookupControl<"bookableresourcecategory">;
      get(name: "msdyn_resourcecategory1"): Xrm.LookupControl<"bookableresourcecategory">;
      get(name: "msdyn_resourceorganizationalunitid"): Xrm.LookupControl<"msdyn_organizationalunit">;
      get(name: "msdyn_startdatetime"): Xrm.DateControl;
      get(name: "msdyn_startdatetime1"): Xrm.DateControl;
      get(name: "msdyn_task"): Xrm.LookupControl<"msdyn_projecttask">;
      get(name: "msdyn_tax"): Xrm.NumberControl;
      get(name: "msdyn_transactioncategory"): Xrm.LookupControl<"msdyn_transactioncategory">;
      get(name: "msdyn_transactioncategory1"): Xrm.LookupControl<"msdyn_transactioncategory">;
      get(name: "msdyn_transactionclassification"): Xrm.OptionSetControl<msdyn_transactionclassification>;
      get(name: "msdyn_transactionclassification1"): Xrm.OptionSetControl<msdyn_transactionclassification>;
      get(name: "msdyn_transactiontypecode"): Xrm.OptionSetControl<msdyn_transactiontypecode>;
      get(name: "msdyn_transactiontypecode1"): Xrm.OptionSetControl<msdyn_transactiontypecode>;
      get(name: "msdyn_unit"): Xrm.LookupControl<"uom">;
      get(name: "msdyn_unit1"): Xrm.LookupControl<"uom">;
      get(name: "msdyn_unitschedule"): Xrm.LookupControl<"uomschedule">;
      get(name: "msdyn_vendortype"): Xrm.OptionSetControl<msdyn_partytype>;
      get(name: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "transactioncurrencyid"): Xrm.LookupControl<"transactioncurrency">;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "SummaryTab"): Xrm.PageTab<Tabs.SummaryTab>;
      get(name: "{1c4a4b53-14d2-4079-9d6a-4fd07d7e8a2b}"): Xrm.PageTab<Tabs._1c4a4b5314d240799d6a4fd07d7e8a2b>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface ProjectInformation extends Xrm.PageBase<ProjectInformation.Attributes,ProjectInformation.Tabs,ProjectInformation.Controls> {
    getAttribute(attributeName: "msdyn_accountcustomer"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "msdyn_accountvendor"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "msdyn_amount"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_amount_after_tax"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_amountmethod"): Xrm.OptionSetAttribute<msdyn_amountmethod>;
    getAttribute(attributeName: "msdyn_basisamount"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_basisquantity"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_billingtype"): Xrm.OptionSetAttribute<msdyn_billingtype>;
    getAttribute(attributeName: "msdyn_bookableresource"): Xrm.LookupAttribute<"bookableresource">;
    getAttribute(attributeName: "msdyn_contactcustomer"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "msdyn_contactvendor"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "msdyn_customertype"): Xrm.OptionSetAttribute<msdyn_partytype>;
    getAttribute(attributeName: "msdyn_description"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_documentdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_enddatetime"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_origin"): Xrm.LookupAttribute<"msdyn_quotelinetransaction">;
    getAttribute(attributeName: "msdyn_percent"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_price"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_pricelist"): Xrm.LookupAttribute<"pricelevel">;
    getAttribute(attributeName: "msdyn_product"): Xrm.LookupAttribute<"product">;
    getAttribute(attributeName: "msdyn_project"): Xrm.LookupAttribute<"msdyn_project">;
    getAttribute(attributeName: "msdyn_quantity"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_quoteid"): Xrm.LookupAttribute<"quote">;
    getAttribute(attributeName: "msdyn_quotelineid"): Xrm.LookupAttribute<"quotedetail">;
    getAttribute(attributeName: "msdyn_resourcecategory"): Xrm.LookupAttribute<"bookableresourcecategory">;
    getAttribute(attributeName: "msdyn_resourceorganizationalunitid"): Xrm.LookupAttribute<"msdyn_organizationalunit">;
    getAttribute(attributeName: "msdyn_startdatetime"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_task"): Xrm.LookupAttribute<"msdyn_projecttask">;
    getAttribute(attributeName: "msdyn_tax"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_transactioncategory"): Xrm.LookupAttribute<"msdyn_transactioncategory">;
    getAttribute(attributeName: "msdyn_transactionclassification"): Xrm.OptionSetAttribute<msdyn_transactionclassification>;
    getAttribute(attributeName: "msdyn_transactiontypecode"): Xrm.OptionSetAttribute<msdyn_transactiontypecode>;
    getAttribute(attributeName: "msdyn_unit"): Xrm.LookupAttribute<"uom">;
    getAttribute(attributeName: "msdyn_unitschedule"): Xrm.LookupAttribute<"uomschedule">;
    getAttribute(attributeName: "msdyn_vendortype"): Xrm.OptionSetAttribute<msdyn_partytype>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "transactioncurrencyid"): Xrm.LookupAttribute<"transactioncurrency">;
    getAttribute(attributeName: string): undefined;
    getAttribute(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Attribute<any>>): Xrm.Attribute<any>[];
    getControl(controlName: "msdyn_accountcustomer"): Xrm.LookupControl<"account">;
    getControl(controlName: "msdyn_accountvendor"): Xrm.LookupControl<"account">;
    getControl(controlName: "msdyn_amount"): Xrm.NumberControl;
    getControl(controlName: "msdyn_amount1"): Xrm.NumberControl;
    getControl(controlName: "msdyn_amount_after_tax"): Xrm.NumberControl;
    getControl(controlName: "msdyn_amountmethod"): Xrm.OptionSetControl<msdyn_amountmethod>;
    getControl(controlName: "msdyn_basisamount"): Xrm.NumberControl;
    getControl(controlName: "msdyn_basisquantity"): Xrm.NumberControl;
    getControl(controlName: "msdyn_billingtype"): Xrm.OptionSetControl<msdyn_billingtype>;
    getControl(controlName: "msdyn_billingtype1"): Xrm.OptionSetControl<msdyn_billingtype>;
    getControl(controlName: "msdyn_bookableresource"): Xrm.LookupControl<"bookableresource">;
    getControl(controlName: "msdyn_contactcustomer"): Xrm.LookupControl<"contact">;
    getControl(controlName: "msdyn_contactvendor"): Xrm.LookupControl<"contact">;
    getControl(controlName: "msdyn_customertype"): Xrm.OptionSetControl<msdyn_partytype>;
    getControl(controlName: "msdyn_description"): Xrm.StringControl;
    getControl(controlName: "msdyn_description1"): Xrm.StringControl;
    getControl(controlName: "msdyn_documentdate"): Xrm.DateControl;
    getControl(controlName: "msdyn_enddatetime"): Xrm.DateControl;
    getControl(controlName: "msdyn_enddatetime1"): Xrm.DateControl;
    getControl(controlName: "msdyn_origin"): Xrm.LookupControl<"msdyn_quotelinetransaction">;
    getControl(controlName: "msdyn_percent"): Xrm.NumberControl;
    getControl(controlName: "msdyn_price"): Xrm.NumberControl;
    getControl(controlName: "msdyn_price1"): Xrm.NumberControl;
    getControl(controlName: "msdyn_pricelist"): Xrm.LookupControl<"pricelevel">;
    getControl(controlName: "msdyn_pricelist1"): Xrm.LookupControl<"pricelevel">;
    getControl(controlName: "msdyn_product"): Xrm.LookupControl<"product">;
    getControl(controlName: "msdyn_project"): Xrm.LookupControl<"msdyn_project">;
    getControl(controlName: "msdyn_quantity"): Xrm.NumberControl;
    getControl(controlName: "msdyn_quantity1"): Xrm.NumberControl;
    getControl(controlName: "msdyn_quoteid"): Xrm.LookupControl<"quote">;
    getControl(controlName: "msdyn_quoteid1"): Xrm.LookupControl<"quote">;
    getControl(controlName: "msdyn_quotelineid"): Xrm.LookupControl<"quotedetail">;
    getControl(controlName: "msdyn_resourcecategory"): Xrm.LookupControl<"bookableresourcecategory">;
    getControl(controlName: "msdyn_resourcecategory1"): Xrm.LookupControl<"bookableresourcecategory">;
    getControl(controlName: "msdyn_resourceorganizationalunitid"): Xrm.LookupControl<"msdyn_organizationalunit">;
    getControl(controlName: "msdyn_startdatetime"): Xrm.DateControl;
    getControl(controlName: "msdyn_startdatetime1"): Xrm.DateControl;
    getControl(controlName: "msdyn_task"): Xrm.LookupControl<"msdyn_projecttask">;
    getControl(controlName: "msdyn_tax"): Xrm.NumberControl;
    getControl(controlName: "msdyn_transactioncategory"): Xrm.LookupControl<"msdyn_transactioncategory">;
    getControl(controlName: "msdyn_transactioncategory1"): Xrm.LookupControl<"msdyn_transactioncategory">;
    getControl(controlName: "msdyn_transactionclassification"): Xrm.OptionSetControl<msdyn_transactionclassification>;
    getControl(controlName: "msdyn_transactionclassification1"): Xrm.OptionSetControl<msdyn_transactionclassification>;
    getControl(controlName: "msdyn_transactiontypecode"): Xrm.OptionSetControl<msdyn_transactiontypecode>;
    getControl(controlName: "msdyn_transactiontypecode1"): Xrm.OptionSetControl<msdyn_transactiontypecode>;
    getControl(controlName: "msdyn_unit"): Xrm.LookupControl<"uom">;
    getControl(controlName: "msdyn_unit1"): Xrm.LookupControl<"uom">;
    getControl(controlName: "msdyn_unitschedule"): Xrm.LookupControl<"uomschedule">;
    getControl(controlName: "msdyn_vendortype"): Xrm.OptionSetControl<msdyn_partytype>;
    getControl(controlName: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "transactioncurrencyid"): Xrm.LookupControl<"transactioncurrency">;
    getControl(controlName: string): undefined;
    getControl(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Control<any>>): Xrm.Control<any>[];
  }
}
