declare namespace Form.msdyn_actual.Main {
  namespace Information {
    namespace Tabs {
      interface FieldService extends Xrm.SectionCollectionBase {
        get(name: "tab_2_section_1"): Xrm.PageSection;
        get(name: "tab_2_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface _88d21a952ebc49e9a5686a7a0107bcec extends Xrm.SectionCollectionBase {
        get(name: "Accounting"): Xrm.PageSection;
        get(name: "{88d21a95-2ebc-49e9-a568-6a7a0107bcec}_section_10"): Xrm.PageSection;
        get(name: "{88d21a95-2ebc-49e9-a568-6a7a0107bcec}_section_3"): Xrm.PageSection;
        get(name: "{88d21a95-2ebc-49e9-a568-6a7a0107bcec}_section_4"): Xrm.PageSection;
        get(name: "{88d21a95-2ebc-49e9-a568-6a7a0107bcec}_section_5"): Xrm.PageSection;
        get(name: "{88d21a95-2ebc-49e9-a568-6a7a0107bcec}_section_6"): Xrm.PageSection;
        get(name: "{88d21a95-2ebc-49e9-a568-6a7a0107bcec}_section_8"): Xrm.PageSection;
        get(name: "{88d21a95-2ebc-49e9-a568-6a7a0107bcec}_section_9"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "msdyn_accountcustomer"): Xrm.LookupAttribute<"account">;
      get(name: "msdyn_accountingdate"): Xrm.DateAttribute;
      get(name: "msdyn_accountvendor"): Xrm.LookupAttribute<"account">;
      get(name: "msdyn_adjustmentstatus"): Xrm.OptionSetAttribute<msdyn_adjustmentstatus>;
      get(name: "msdyn_agreement"): Xrm.LookupAttribute<"msdyn_agreement">;
      get(name: "msdyn_amount"): Xrm.NumberAttribute;
      get(name: "msdyn_amountmethod"): Xrm.OptionSetAttribute<msdyn_amountmethod>;
      get(name: "msdyn_basisamount"): Xrm.NumberAttribute;
      get(name: "msdyn_basisquantity"): Xrm.NumberAttribute;
      get(name: "msdyn_billingstatus"): Xrm.OptionSetAttribute<msdyn_billingstatus>;
      get(name: "msdyn_billingtype"): Xrm.OptionSetAttribute<msdyn_billingtype>;
      get(name: "msdyn_bookableresource"): Xrm.LookupAttribute<"bookableresource">;
      get(name: "msdyn_contactcustomer"): Xrm.LookupAttribute<"contact">;
      get(name: "msdyn_contactvendor"): Xrm.LookupAttribute<"contact">;
      get(name: "msdyn_contractorganizationalunitid"): Xrm.LookupAttribute<"msdyn_organizationalunit">;
      get(name: "msdyn_customertype"): Xrm.OptionSetAttribute<msdyn_partytype>;
      get(name: "msdyn_description"): Xrm.Attribute<string>;
      get(name: "msdyn_documentdate"): Xrm.DateAttribute;
      get(name: "msdyn_enddatetime"): Xrm.DateAttribute;
      get(name: "msdyn_externaldescription"): Xrm.Attribute<string>;
      get(name: "msdyn_incidenttype"): Xrm.LookupAttribute<"msdyn_incidenttype">;
      get(name: "msdyn_invoice"): Xrm.LookupAttribute<"invoice">;
      get(name: "msdyn_isjournalized"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_journaltype"): Xrm.OptionSetAttribute<msdyn_bookingjournaltype>;
      get(name: "msdyn_percent"): Xrm.NumberAttribute;
      get(name: "msdyn_price"): Xrm.NumberAttribute;
      get(name: "msdyn_pricelist"): Xrm.LookupAttribute<"pricelevel">;
      get(name: "msdyn_product"): Xrm.LookupAttribute<"product">;
      get(name: "msdyn_producttype"): Xrm.OptionSetAttribute<msdyn_fieldserviceproducttype>;
      get(name: "msdyn_project"): Xrm.LookupAttribute<"msdyn_project">;
      get(name: "msdyn_quantity"): Xrm.NumberAttribute;
      get(name: "msdyn_resourcecategory"): Xrm.LookupAttribute<"bookableresourcecategory">;
      get(name: "msdyn_resourceorganizationalunitid"): Xrm.LookupAttribute<"msdyn_organizationalunit">;
      get(name: "msdyn_serviceaccount"): Xrm.LookupAttribute<"account">;
      get(name: "msdyn_serviceterritory"): Xrm.LookupAttribute<"territory">;
      get(name: "msdyn_startdatetime"): Xrm.DateAttribute;
      get(name: "msdyn_task"): Xrm.LookupAttribute<"msdyn_projecttask">;
      get(name: "msdyn_taxcode"): Xrm.LookupAttribute<"msdyn_taxcode">;
      get(name: "msdyn_transactioncategory"): Xrm.LookupAttribute<"msdyn_transactioncategory">;
      get(name: "msdyn_transactionclassification"): Xrm.OptionSetAttribute<msdyn_transactionclassification>;
      get(name: "msdyn_transactiontypecode"): Xrm.OptionSetAttribute<msdyn_transactiontypecode>;
      get(name: "msdyn_unit"): Xrm.LookupAttribute<"uom">;
      get(name: "msdyn_unitschedule"): Xrm.LookupAttribute<"uomschedule">;
      get(name: "msdyn_vendortype"): Xrm.OptionSetAttribute<msdyn_partytype>;
      get(name: "msdyn_warehouse"): Xrm.LookupAttribute<"msdyn_warehouse">;
      get(name: "msdyn_worklocation"): Xrm.OptionSetAttribute<msdyn_worklocation>;
      get(name: "msdyn_workorder"): Xrm.LookupAttribute<"msdyn_workorder">;
      get(name: "msdyn_workordertype"): Xrm.LookupAttribute<"msdyn_workordertype">;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "transactioncurrencyid"): Xrm.LookupAttribute<"transactioncurrency">;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "msdyn_accountcustomer"): Xrm.LookupControl<"account">;
      get(name: "msdyn_accountingdate"): Xrm.DateControl;
      get(name: "msdyn_accountvendor"): Xrm.LookupControl<"account">;
      get(name: "msdyn_adjustmentstatus"): Xrm.OptionSetControl<msdyn_adjustmentstatus>;
      get(name: "msdyn_agreement"): Xrm.LookupControl<"msdyn_agreement">;
      get(name: "msdyn_amount"): Xrm.NumberControl;
      get(name: "msdyn_amountmethod"): Xrm.OptionSetControl<msdyn_amountmethod>;
      get(name: "msdyn_basisamount"): Xrm.NumberControl;
      get(name: "msdyn_basisquantity"): Xrm.NumberControl;
      get(name: "msdyn_billingstatus"): Xrm.OptionSetControl<msdyn_billingstatus>;
      get(name: "msdyn_billingtype"): Xrm.OptionSetControl<msdyn_billingtype>;
      get(name: "msdyn_bookableresource"): Xrm.LookupControl<"bookableresource">;
      get(name: "msdyn_contactcustomer"): Xrm.LookupControl<"contact">;
      get(name: "msdyn_contactvendor"): Xrm.LookupControl<"contact">;
      get(name: "msdyn_contractorganizationalunitid"): Xrm.LookupControl<"msdyn_organizationalunit">;
      get(name: "msdyn_customertype"): Xrm.OptionSetControl<msdyn_partytype>;
      get(name: "msdyn_description"): Xrm.StringControl;
      get(name: "msdyn_documentdate"): Xrm.DateControl;
      get(name: "msdyn_enddatetime"): Xrm.DateControl;
      get(name: "msdyn_externaldescription"): Xrm.StringControl;
      get(name: "msdyn_incidenttype"): Xrm.LookupControl<"msdyn_incidenttype">;
      get(name: "msdyn_invoice"): Xrm.LookupControl<"invoice">;
      get(name: "msdyn_isjournalized"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_journaltype"): Xrm.OptionSetControl<msdyn_bookingjournaltype>;
      get(name: "msdyn_percent"): Xrm.NumberControl;
      get(name: "msdyn_price"): Xrm.NumberControl;
      get(name: "msdyn_pricelist"): Xrm.LookupControl<"pricelevel">;
      get(name: "msdyn_product"): Xrm.LookupControl<"product">;
      get(name: "msdyn_producttype"): Xrm.OptionSetControl<msdyn_fieldserviceproducttype>;
      get(name: "msdyn_project"): Xrm.LookupControl<"msdyn_project">;
      get(name: "msdyn_quantity"): Xrm.NumberControl;
      get(name: "msdyn_resourcecategory"): Xrm.LookupControl<"bookableresourcecategory">;
      get(name: "msdyn_resourceorganizationalunitid"): Xrm.LookupControl<"msdyn_organizationalunit">;
      get(name: "msdyn_serviceaccount"): Xrm.LookupControl<"account">;
      get(name: "msdyn_serviceterritory"): Xrm.LookupControl<"territory">;
      get(name: "msdyn_startdatetime"): Xrm.DateControl;
      get(name: "msdyn_task"): Xrm.LookupControl<"msdyn_projecttask">;
      get(name: "msdyn_taxcode"): Xrm.LookupControl<"msdyn_taxcode">;
      get(name: "msdyn_transactioncategory"): Xrm.LookupControl<"msdyn_transactioncategory">;
      get(name: "msdyn_transactionclassification"): Xrm.OptionSetControl<msdyn_transactionclassification>;
      get(name: "msdyn_transactiontypecode"): Xrm.OptionSetControl<msdyn_transactiontypecode>;
      get(name: "msdyn_unit"): Xrm.LookupControl<"uom">;
      get(name: "msdyn_unitschedule"): Xrm.LookupControl<"uomschedule">;
      get(name: "msdyn_vendortype"): Xrm.OptionSetControl<msdyn_partytype>;
      get(name: "msdyn_warehouse"): Xrm.LookupControl<"msdyn_warehouse">;
      get(name: "msdyn_worklocation"): Xrm.OptionSetControl<msdyn_worklocation>;
      get(name: "msdyn_workorder"): Xrm.LookupControl<"msdyn_workorder">;
      get(name: "msdyn_workordertype"): Xrm.LookupControl<"msdyn_workordertype">;
      get(name: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "transactioncurrencyid"): Xrm.LookupControl<"transactioncurrency">;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "FieldService"): Xrm.PageTab<Tabs.FieldService>;
      get(name: "{88d21a95-2ebc-49e9-a568-6a7a0107bcec}"): Xrm.PageTab<Tabs._88d21a952ebc49e9a5686a7a0107bcec>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "msdyn_accountcustomer"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "msdyn_accountingdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_accountvendor"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "msdyn_adjustmentstatus"): Xrm.OptionSetAttribute<msdyn_adjustmentstatus>;
    getAttribute(attributeName: "msdyn_agreement"): Xrm.LookupAttribute<"msdyn_agreement">;
    getAttribute(attributeName: "msdyn_amount"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_amountmethod"): Xrm.OptionSetAttribute<msdyn_amountmethod>;
    getAttribute(attributeName: "msdyn_basisamount"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_basisquantity"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_billingstatus"): Xrm.OptionSetAttribute<msdyn_billingstatus>;
    getAttribute(attributeName: "msdyn_billingtype"): Xrm.OptionSetAttribute<msdyn_billingtype>;
    getAttribute(attributeName: "msdyn_bookableresource"): Xrm.LookupAttribute<"bookableresource">;
    getAttribute(attributeName: "msdyn_contactcustomer"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "msdyn_contactvendor"): Xrm.LookupAttribute<"contact">;
    getAttribute(attributeName: "msdyn_contractorganizationalunitid"): Xrm.LookupAttribute<"msdyn_organizationalunit">;
    getAttribute(attributeName: "msdyn_customertype"): Xrm.OptionSetAttribute<msdyn_partytype>;
    getAttribute(attributeName: "msdyn_description"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_documentdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_enddatetime"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_externaldescription"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_incidenttype"): Xrm.LookupAttribute<"msdyn_incidenttype">;
    getAttribute(attributeName: "msdyn_invoice"): Xrm.LookupAttribute<"invoice">;
    getAttribute(attributeName: "msdyn_isjournalized"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_journaltype"): Xrm.OptionSetAttribute<msdyn_bookingjournaltype>;
    getAttribute(attributeName: "msdyn_percent"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_price"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_pricelist"): Xrm.LookupAttribute<"pricelevel">;
    getAttribute(attributeName: "msdyn_product"): Xrm.LookupAttribute<"product">;
    getAttribute(attributeName: "msdyn_producttype"): Xrm.OptionSetAttribute<msdyn_fieldserviceproducttype>;
    getAttribute(attributeName: "msdyn_project"): Xrm.LookupAttribute<"msdyn_project">;
    getAttribute(attributeName: "msdyn_quantity"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_resourcecategory"): Xrm.LookupAttribute<"bookableresourcecategory">;
    getAttribute(attributeName: "msdyn_resourceorganizationalunitid"): Xrm.LookupAttribute<"msdyn_organizationalunit">;
    getAttribute(attributeName: "msdyn_serviceaccount"): Xrm.LookupAttribute<"account">;
    getAttribute(attributeName: "msdyn_serviceterritory"): Xrm.LookupAttribute<"territory">;
    getAttribute(attributeName: "msdyn_startdatetime"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_task"): Xrm.LookupAttribute<"msdyn_projecttask">;
    getAttribute(attributeName: "msdyn_taxcode"): Xrm.LookupAttribute<"msdyn_taxcode">;
    getAttribute(attributeName: "msdyn_transactioncategory"): Xrm.LookupAttribute<"msdyn_transactioncategory">;
    getAttribute(attributeName: "msdyn_transactionclassification"): Xrm.OptionSetAttribute<msdyn_transactionclassification>;
    getAttribute(attributeName: "msdyn_transactiontypecode"): Xrm.OptionSetAttribute<msdyn_transactiontypecode>;
    getAttribute(attributeName: "msdyn_unit"): Xrm.LookupAttribute<"uom">;
    getAttribute(attributeName: "msdyn_unitschedule"): Xrm.LookupAttribute<"uomschedule">;
    getAttribute(attributeName: "msdyn_vendortype"): Xrm.OptionSetAttribute<msdyn_partytype>;
    getAttribute(attributeName: "msdyn_warehouse"): Xrm.LookupAttribute<"msdyn_warehouse">;
    getAttribute(attributeName: "msdyn_worklocation"): Xrm.OptionSetAttribute<msdyn_worklocation>;
    getAttribute(attributeName: "msdyn_workorder"): Xrm.LookupAttribute<"msdyn_workorder">;
    getAttribute(attributeName: "msdyn_workordertype"): Xrm.LookupAttribute<"msdyn_workordertype">;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "transactioncurrencyid"): Xrm.LookupAttribute<"transactioncurrency">;
    getAttribute(attributeName: string): undefined;
    getAttribute(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Attribute<any>>): Xrm.Attribute<any>[];
    getControl(controlName: "msdyn_accountcustomer"): Xrm.LookupControl<"account">;
    getControl(controlName: "msdyn_accountingdate"): Xrm.DateControl;
    getControl(controlName: "msdyn_accountvendor"): Xrm.LookupControl<"account">;
    getControl(controlName: "msdyn_adjustmentstatus"): Xrm.OptionSetControl<msdyn_adjustmentstatus>;
    getControl(controlName: "msdyn_agreement"): Xrm.LookupControl<"msdyn_agreement">;
    getControl(controlName: "msdyn_amount"): Xrm.NumberControl;
    getControl(controlName: "msdyn_amountmethod"): Xrm.OptionSetControl<msdyn_amountmethod>;
    getControl(controlName: "msdyn_basisamount"): Xrm.NumberControl;
    getControl(controlName: "msdyn_basisquantity"): Xrm.NumberControl;
    getControl(controlName: "msdyn_billingstatus"): Xrm.OptionSetControl<msdyn_billingstatus>;
    getControl(controlName: "msdyn_billingtype"): Xrm.OptionSetControl<msdyn_billingtype>;
    getControl(controlName: "msdyn_bookableresource"): Xrm.LookupControl<"bookableresource">;
    getControl(controlName: "msdyn_contactcustomer"): Xrm.LookupControl<"contact">;
    getControl(controlName: "msdyn_contactvendor"): Xrm.LookupControl<"contact">;
    getControl(controlName: "msdyn_contractorganizationalunitid"): Xrm.LookupControl<"msdyn_organizationalunit">;
    getControl(controlName: "msdyn_customertype"): Xrm.OptionSetControl<msdyn_partytype>;
    getControl(controlName: "msdyn_description"): Xrm.StringControl;
    getControl(controlName: "msdyn_documentdate"): Xrm.DateControl;
    getControl(controlName: "msdyn_enddatetime"): Xrm.DateControl;
    getControl(controlName: "msdyn_externaldescription"): Xrm.StringControl;
    getControl(controlName: "msdyn_incidenttype"): Xrm.LookupControl<"msdyn_incidenttype">;
    getControl(controlName: "msdyn_invoice"): Xrm.LookupControl<"invoice">;
    getControl(controlName: "msdyn_isjournalized"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_journaltype"): Xrm.OptionSetControl<msdyn_bookingjournaltype>;
    getControl(controlName: "msdyn_percent"): Xrm.NumberControl;
    getControl(controlName: "msdyn_price"): Xrm.NumberControl;
    getControl(controlName: "msdyn_pricelist"): Xrm.LookupControl<"pricelevel">;
    getControl(controlName: "msdyn_product"): Xrm.LookupControl<"product">;
    getControl(controlName: "msdyn_producttype"): Xrm.OptionSetControl<msdyn_fieldserviceproducttype>;
    getControl(controlName: "msdyn_project"): Xrm.LookupControl<"msdyn_project">;
    getControl(controlName: "msdyn_quantity"): Xrm.NumberControl;
    getControl(controlName: "msdyn_resourcecategory"): Xrm.LookupControl<"bookableresourcecategory">;
    getControl(controlName: "msdyn_resourceorganizationalunitid"): Xrm.LookupControl<"msdyn_organizationalunit">;
    getControl(controlName: "msdyn_serviceaccount"): Xrm.LookupControl<"account">;
    getControl(controlName: "msdyn_serviceterritory"): Xrm.LookupControl<"territory">;
    getControl(controlName: "msdyn_startdatetime"): Xrm.DateControl;
    getControl(controlName: "msdyn_task"): Xrm.LookupControl<"msdyn_projecttask">;
    getControl(controlName: "msdyn_taxcode"): Xrm.LookupControl<"msdyn_taxcode">;
    getControl(controlName: "msdyn_transactioncategory"): Xrm.LookupControl<"msdyn_transactioncategory">;
    getControl(controlName: "msdyn_transactionclassification"): Xrm.OptionSetControl<msdyn_transactionclassification>;
    getControl(controlName: "msdyn_transactiontypecode"): Xrm.OptionSetControl<msdyn_transactiontypecode>;
    getControl(controlName: "msdyn_unit"): Xrm.LookupControl<"uom">;
    getControl(controlName: "msdyn_unitschedule"): Xrm.LookupControl<"uomschedule">;
    getControl(controlName: "msdyn_vendortype"): Xrm.OptionSetControl<msdyn_partytype>;
    getControl(controlName: "msdyn_warehouse"): Xrm.LookupControl<"msdyn_warehouse">;
    getControl(controlName: "msdyn_worklocation"): Xrm.OptionSetControl<msdyn_worklocation>;
    getControl(controlName: "msdyn_workorder"): Xrm.LookupControl<"msdyn_workorder">;
    getControl(controlName: "msdyn_workordertype"): Xrm.LookupControl<"msdyn_workordertype">;
    getControl(controlName: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "transactioncurrencyid"): Xrm.LookupControl<"transactioncurrency">;
    getControl(controlName: string): undefined;
    getControl(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Control<any>>): Xrm.Control<any>[];
  }
}
