declare namespace Form.msdyn_fieldservicesetting.Main {
  namespace Information {
    namespace Tabs {
      interface RemoteAssist extends Xrm.SectionCollectionBase {
        get(name: "tab_13_section_1_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface TimeEntry extends Xrm.SectionCollectionBase {
        get(name: "TimeEntry"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface _4cc8a00d6d794310a61a6b5a0597caf4 extends Xrm.SectionCollectionBase {
        get(name: "{c420a5ef-ca73-43ea-a432-4f9ece791087}"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_10 extends Xrm.SectionCollectionBase {
        get(name: "tab_10_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_11 extends Xrm.SectionCollectionBase {
        get(name: "tab_11_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_12 extends Xrm.SectionCollectionBase {
        get(name: "tab_12_section_1"): Xrm.PageSection;
        get(name: "tab_12_section_2"): Xrm.PageSection;
        get(name: "tab_12_section_3"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_13 extends Xrm.SectionCollectionBase {
        get(name: "tab_13_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_14 extends Xrm.SectionCollectionBase {
        get(name: "tab_14_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_4 extends Xrm.SectionCollectionBase {
        get(name: "tab_4_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_6 extends Xrm.SectionCollectionBase {
        get(name: "Crew Management"): Xrm.PageSection;
        get(name: "Mobile"): Xrm.PageSection;
        get(name: "tab_3_section_1"): Xrm.PageSection;
        get(name: "tab_6_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_7 extends Xrm.SectionCollectionBase {
        get(name: "tab_7_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_8 extends Xrm.SectionCollectionBase {
        get(name: "tab_8_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_9 extends Xrm.SectionCollectionBase {
        get(name: "tab_9_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "msdyn_advancedsettings"): Xrm.Attribute<string>;
      get(name: "msdyn_agreementprefix"): Xrm.Attribute<string>;
      get(name: "msdyn_agreementrecordgeneration"): Xrm.DateAttribute;
      get(name: "msdyn_agreementstartingnumber"): Xrm.NumberAttribute;
      get(name: "msdyn_analyticsingestdatainxdays"): Xrm.NumberAttribute;
      get(name: "msdyn_autoallocateestimatedproducts"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_autogeneratewoforagreementbooking"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_autogeocodeaddresses"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_autonumberingoptin"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_breakpaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
      get(name: "msdyn_businessclosurepaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
      get(name: "msdyn_calculateprice"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_calculatetax"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_datepopulationtype"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_defaultcrewstrategy"): Xrm.OptionSetAttribute<msdyn_crewstrategy>;
      get(name: "msdyn_defaultwarehouse"): Xrm.LookupAttribute<"msdyn_warehouse">;
      get(name: "msdyn_defaultworkordercompletedstatus"): Xrm.OptionSetAttribute<msdyn_wosystemstatus>;
      get(name: "msdyn_disablecustomerassetvalidation"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_disableremoteassistbookingstatuschanges"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_enableaddresssuggestions"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_enableincidenttyperecommendation"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_enablelegacyscheduleassistant"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_enablemainformdialogforsubgrids"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_enablesuggestedduration"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_enhancedbackgroundprocessing"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_entitynumberlength"): Xrm.NumberAttribute;
      get(name: "msdyn_generateactuals"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_generateagreementinvoicesxdaysinadvance"): Xrm.NumberAttribute;
      get(name: "msdyn_generateagreementwoxdaysinadvance"): Xrm.NumberAttribute;
      get(name: "msdyn_generatebookingdatesxmonthsinadvance"): Xrm.NumberAttribute;
      get(name: "msdyn_generateinvoicedatesxmonthsinadvance"): Xrm.NumberAttribute;
      get(name: "msdyn_historicaldatafilter"): Xrm.OptionSetAttribute<msdyn_fieldservicesetting_msdyn_historicaldatafilter>;
      get(name: "msdyn_inspectionanalyticsenabled"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_inspectionanalyticsfrequency"): Xrm.OptionSetAttribute<msdyn_fieldservicesetting_msdyn_inspectionanalyticsfrequency>;
      get(name: "msdyn_inspectionanalyticsrecommendedtime"): Xrm.DateAttribute;
      get(name: "msdyn_internalflags"): Xrm.Attribute<string>;
      get(name: "msdyn_inventoryadjustmentprefix"): Xrm.Attribute<string>;
      get(name: "msdyn_inventoryadjustmentstartingnumber"): Xrm.NumberAttribute;
      get(name: "msdyn_inventorytransferprefix"): Xrm.Attribute<string>;
      get(name: "msdyn_inventorytransferstartingnumber"): Xrm.NumberAttribute;
      get(name: "msdyn_lastrunofincidenttyperecommendation"): Xrm.DateAttribute;
      get(name: "msdyn_name"): Xrm.Attribute<string>;
      get(name: "msdyn_overtimepaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
      get(name: "msdyn_productcostorder"): Xrm.OptionSetAttribute<msdyn_productcostorder>;
      get(name: "msdyn_purchaseorderapprovalrequired"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_purchaseorderprefix"): Xrm.Attribute<string>;
      get(name: "msdyn_purchaseorderstartingnumber"): Xrm.NumberAttribute;
      get(name: "msdyn_returntopxrecommendations"): Xrm.NumberAttribute;
      get(name: "msdyn_rmaprefix"): Xrm.Attribute<string>;
      get(name: "msdyn_rmastartingnumber"): Xrm.NumberAttribute;
      get(name: "msdyn_rtvprefix"): Xrm.Attribute<string>;
      get(name: "msdyn_rtvstartingnumber"): Xrm.NumberAttribute;
      get(name: "msdyn_runfrequencyofincidenttyperecommendation"): Xrm.OptionSetAttribute<msdyn_fieldservicesetting_msdyn_runfrequencyofincidenttyperecommendation>;
      get(name: "msdyn_showsimplifiedworkordercommands"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_suggestreparentingcustomerassets"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyn_timecostactualssource"): Xrm.OptionSetAttribute<msdyn_timecostactualssource>;
      get(name: "msdyn_timeentrygenerationstrategy"): Xrm.OptionSetAttribute<msdyn_timeentrygenerationstrategy>;
      get(name: "msdyn_timestampfrequency"): Xrm.OptionSetAttribute<msdyn_timestampfrequency>;
      get(name: "msdyn_travelchargeitemid"): Xrm.LookupAttribute<"product">;
      get(name: "msdyn_travelpaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
      get(name: "msdyn_useofproductsoutofstock"): Xrm.OptionSetAttribute<msdyn_outofstockoptions>;
      get(name: "msdyn_workorderinvoicecreation"): Xrm.OptionSetAttribute<msdyn_autocreateinvoices>;
      get(name: "msdyn_workorderprefix"): Xrm.Attribute<string>;
      get(name: "msdyn_workorderstartingnumber"): Xrm.NumberAttribute;
      get(name: "msdyn_workpaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "statecode"): Xrm.OptionSetAttribute<msdyn_fieldservicesetting_statecode>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "IncidentTypeSuggestionResultGrid"): Xrm.SubGridControl<"msdyn_incidenttyperecommendationresult">;
      get(name: "WebResource_AgreementRecordGeneration_TimeField"): Xrm.WebResourceControl;
      get(name: "WebResource_AgreementRecordGeneration_TimeField1"): Xrm.WebResourceControl;
      get(name: "fieldserviceslaconfigurationgrid"): Xrm.SubGridControl<"msdyn_fieldserviceslaconfiguration">;
      get(name: "footer_statecode"): Xrm.OptionSetControl<msdyn_fieldservicesetting_statecode>;
      get(name: "msdyn_advancedsettings"): Xrm.StringControl;
      get(name: "msdyn_agreementprefix"): Xrm.StringControl;
      get(name: "msdyn_agreementrecordgeneration"): Xrm.DateControl;
      get(name: "msdyn_agreementrecordgeneration1"): Xrm.DateControl;
      get(name: "msdyn_agreementstartingnumber"): Xrm.NumberControl;
      get(name: "msdyn_analyticsingestdatainxdays"): Xrm.NumberControl;
      get(name: "msdyn_autoallocateestimatedproducts"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_autogeneratewoforagreementbooking"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_autogeocodeaddresses"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_autonumberingoptin"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_breakpaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
      get(name: "msdyn_businessclosurepaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
      get(name: "msdyn_calculateprice"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_calculatetax"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_datepopulationtype"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_defaultcrewstrategy"): Xrm.OptionSetControl<msdyn_crewstrategy>;
      get(name: "msdyn_defaultwarehouse"): Xrm.LookupControl<"msdyn_warehouse">;
      get(name: "msdyn_defaultworkordercompletedstatus"): Xrm.OptionSetControl<msdyn_wosystemstatus>;
      get(name: "msdyn_disablecustomerassetvalidation"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_disableremoteassistbookingstatuschanges"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_enableaddresssuggestions"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_enableincidenttyperecommendation"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_enablelegacyscheduleassistant"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_enablemainformdialogforsubgrids"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_enablesuggestedduration"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_enhancedbackgroundprocessing"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_entitynumberlength"): Xrm.NumberControl;
      get(name: "msdyn_generateactuals"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_generateagreementinvoicesxdaysinadvance"): Xrm.NumberControl;
      get(name: "msdyn_generateagreementwoxdaysinadvance"): Xrm.NumberControl;
      get(name: "msdyn_generatebookingdatesxmonthsinadvance"): Xrm.NumberControl;
      get(name: "msdyn_generateinvoicedatesxmonthsinadvance"): Xrm.NumberControl;
      get(name: "msdyn_historicaldatafilter"): Xrm.OptionSetControl<msdyn_fieldservicesetting_msdyn_historicaldatafilter>;
      get(name: "msdyn_inspectionanalyticsenabled"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_inspectionanalyticsfrequency"): Xrm.OptionSetControl<msdyn_fieldservicesetting_msdyn_inspectionanalyticsfrequency>;
      get(name: "msdyn_inspectionanalyticsrecommendedtime"): Xrm.DateControl;
      get(name: "msdyn_internalflags"): Xrm.StringControl;
      get(name: "msdyn_inventoryadjustmentprefix"): Xrm.StringControl;
      get(name: "msdyn_inventoryadjustmentstartingnumber"): Xrm.NumberControl;
      get(name: "msdyn_inventorytransferprefix"): Xrm.StringControl;
      get(name: "msdyn_inventorytransferstartingnumber"): Xrm.NumberControl;
      get(name: "msdyn_lastrunofincidenttyperecommendation"): Xrm.DateControl;
      get(name: "msdyn_name"): Xrm.StringControl;
      get(name: "msdyn_overtimepaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
      get(name: "msdyn_productcostorder"): Xrm.OptionSetControl<msdyn_productcostorder>;
      get(name: "msdyn_purchaseorderapprovalrequired"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_purchaseorderprefix"): Xrm.StringControl;
      get(name: "msdyn_purchaseorderstartingnumber"): Xrm.NumberControl;
      get(name: "msdyn_returntopxrecommendations"): Xrm.NumberControl;
      get(name: "msdyn_rmaprefix"): Xrm.StringControl;
      get(name: "msdyn_rmastartingnumber"): Xrm.NumberControl;
      get(name: "msdyn_rtvprefix"): Xrm.StringControl;
      get(name: "msdyn_rtvstartingnumber"): Xrm.NumberControl;
      get(name: "msdyn_runfrequencyofincidenttyperecommendation"): Xrm.OptionSetControl<msdyn_fieldservicesetting_msdyn_runfrequencyofincidenttyperecommendation>;
      get(name: "msdyn_showsimplifiedworkordercommands"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_suggestreparentingcustomerassets"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyn_timecostactualssource"): Xrm.OptionSetControl<msdyn_timecostactualssource>;
      get(name: "msdyn_timeentrygenerationstrategy"): Xrm.OptionSetControl<msdyn_timeentrygenerationstrategy>;
      get(name: "msdyn_timestampfrequency"): Xrm.OptionSetControl<msdyn_timestampfrequency>;
      get(name: "msdyn_travelchargeitemid"): Xrm.LookupControl<"product">;
      get(name: "msdyn_travelpaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
      get(name: "msdyn_useofproductsoutofstock"): Xrm.OptionSetControl<msdyn_outofstockoptions>;
      get(name: "msdyn_workorderinvoicecreation"): Xrm.OptionSetControl<msdyn_autocreateinvoices>;
      get(name: "msdyn_workorderprefix"): Xrm.StringControl;
      get(name: "msdyn_workorderstartingnumber"): Xrm.NumberControl;
      get(name: "msdyn_workpaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "RemoteAssist"): Xrm.PageTab<Tabs.RemoteAssist>;
      get(name: "TimeEntry"): Xrm.PageTab<Tabs.TimeEntry>;
      get(name: "{4cc8a00d-6d79-4310-a61a-6b5a0597caf4}"): Xrm.PageTab<Tabs._4cc8a00d6d794310a61a6b5a0597caf4>;
      get(name: "tab_10"): Xrm.PageTab<Tabs.tab_10>;
      get(name: "tab_11"): Xrm.PageTab<Tabs.tab_11>;
      get(name: "tab_12"): Xrm.PageTab<Tabs.tab_12>;
      get(name: "tab_13"): Xrm.PageTab<Tabs.tab_13>;
      get(name: "tab_14"): Xrm.PageTab<Tabs.tab_14>;
      get(name: "tab_4"): Xrm.PageTab<Tabs.tab_4>;
      get(name: "tab_6"): Xrm.PageTab<Tabs.tab_6>;
      get(name: "tab_7"): Xrm.PageTab<Tabs.tab_7>;
      get(name: "tab_8"): Xrm.PageTab<Tabs.tab_8>;
      get(name: "tab_9"): Xrm.PageTab<Tabs.tab_9>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "msdyn_advancedsettings"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_agreementprefix"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_agreementrecordgeneration"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_agreementstartingnumber"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_analyticsingestdatainxdays"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_autoallocateestimatedproducts"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_autogeneratewoforagreementbooking"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_autogeocodeaddresses"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_autonumberingoptin"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_breakpaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
    getAttribute(attributeName: "msdyn_businessclosurepaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
    getAttribute(attributeName: "msdyn_calculateprice"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_calculatetax"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_datepopulationtype"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_defaultcrewstrategy"): Xrm.OptionSetAttribute<msdyn_crewstrategy>;
    getAttribute(attributeName: "msdyn_defaultwarehouse"): Xrm.LookupAttribute<"msdyn_warehouse">;
    getAttribute(attributeName: "msdyn_defaultworkordercompletedstatus"): Xrm.OptionSetAttribute<msdyn_wosystemstatus>;
    getAttribute(attributeName: "msdyn_disablecustomerassetvalidation"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_disableremoteassistbookingstatuschanges"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_enableaddresssuggestions"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_enableincidenttyperecommendation"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_enablelegacyscheduleassistant"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_enablemainformdialogforsubgrids"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_enablesuggestedduration"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_enhancedbackgroundprocessing"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_entitynumberlength"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_generateactuals"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_generateagreementinvoicesxdaysinadvance"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_generateagreementwoxdaysinadvance"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_generatebookingdatesxmonthsinadvance"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_generateinvoicedatesxmonthsinadvance"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_historicaldatafilter"): Xrm.OptionSetAttribute<msdyn_fieldservicesetting_msdyn_historicaldatafilter>;
    getAttribute(attributeName: "msdyn_inspectionanalyticsenabled"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_inspectionanalyticsfrequency"): Xrm.OptionSetAttribute<msdyn_fieldservicesetting_msdyn_inspectionanalyticsfrequency>;
    getAttribute(attributeName: "msdyn_inspectionanalyticsrecommendedtime"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_internalflags"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_inventoryadjustmentprefix"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_inventoryadjustmentstartingnumber"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_inventorytransferprefix"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_inventorytransferstartingnumber"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_lastrunofincidenttyperecommendation"): Xrm.DateAttribute;
    getAttribute(attributeName: "msdyn_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_overtimepaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
    getAttribute(attributeName: "msdyn_productcostorder"): Xrm.OptionSetAttribute<msdyn_productcostorder>;
    getAttribute(attributeName: "msdyn_purchaseorderapprovalrequired"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_purchaseorderprefix"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_purchaseorderstartingnumber"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_returntopxrecommendations"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_rmaprefix"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_rmastartingnumber"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_rtvprefix"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_rtvstartingnumber"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_runfrequencyofincidenttyperecommendation"): Xrm.OptionSetAttribute<msdyn_fieldservicesetting_msdyn_runfrequencyofincidenttyperecommendation>;
    getAttribute(attributeName: "msdyn_showsimplifiedworkordercommands"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_suggestreparentingcustomerassets"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyn_timecostactualssource"): Xrm.OptionSetAttribute<msdyn_timecostactualssource>;
    getAttribute(attributeName: "msdyn_timeentrygenerationstrategy"): Xrm.OptionSetAttribute<msdyn_timeentrygenerationstrategy>;
    getAttribute(attributeName: "msdyn_timestampfrequency"): Xrm.OptionSetAttribute<msdyn_timestampfrequency>;
    getAttribute(attributeName: "msdyn_travelchargeitemid"): Xrm.LookupAttribute<"product">;
    getAttribute(attributeName: "msdyn_travelpaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
    getAttribute(attributeName: "msdyn_useofproductsoutofstock"): Xrm.OptionSetAttribute<msdyn_outofstockoptions>;
    getAttribute(attributeName: "msdyn_workorderinvoicecreation"): Xrm.OptionSetAttribute<msdyn_autocreateinvoices>;
    getAttribute(attributeName: "msdyn_workorderprefix"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyn_workorderstartingnumber"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyn_workpaytype"): Xrm.LookupAttribute<"msdyn_resourcepaytype">;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "statecode"): Xrm.OptionSetAttribute<msdyn_fieldservicesetting_statecode>;
    getAttribute(attributeName: string): undefined;
    getAttribute(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Attribute<any>>): Xrm.Attribute<any>[];
    getControl(controlName: "IncidentTypeSuggestionResultGrid"): Xrm.SubGridControl<"msdyn_incidenttyperecommendationresult">;
    getControl(controlName: "WebResource_AgreementRecordGeneration_TimeField"): Xrm.WebResourceControl;
    getControl(controlName: "WebResource_AgreementRecordGeneration_TimeField1"): Xrm.WebResourceControl;
    getControl(controlName: "fieldserviceslaconfigurationgrid"): Xrm.SubGridControl<"msdyn_fieldserviceslaconfiguration">;
    getControl(controlName: "footer_statecode"): Xrm.OptionSetControl<msdyn_fieldservicesetting_statecode>;
    getControl(controlName: "msdyn_advancedsettings"): Xrm.StringControl;
    getControl(controlName: "msdyn_agreementprefix"): Xrm.StringControl;
    getControl(controlName: "msdyn_agreementrecordgeneration"): Xrm.DateControl;
    getControl(controlName: "msdyn_agreementrecordgeneration1"): Xrm.DateControl;
    getControl(controlName: "msdyn_agreementstartingnumber"): Xrm.NumberControl;
    getControl(controlName: "msdyn_analyticsingestdatainxdays"): Xrm.NumberControl;
    getControl(controlName: "msdyn_autoallocateestimatedproducts"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_autogeneratewoforagreementbooking"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_autogeocodeaddresses"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_autonumberingoptin"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_breakpaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
    getControl(controlName: "msdyn_businessclosurepaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
    getControl(controlName: "msdyn_calculateprice"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_calculatetax"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_datepopulationtype"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_defaultcrewstrategy"): Xrm.OptionSetControl<msdyn_crewstrategy>;
    getControl(controlName: "msdyn_defaultwarehouse"): Xrm.LookupControl<"msdyn_warehouse">;
    getControl(controlName: "msdyn_defaultworkordercompletedstatus"): Xrm.OptionSetControl<msdyn_wosystemstatus>;
    getControl(controlName: "msdyn_disablecustomerassetvalidation"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_disableremoteassistbookingstatuschanges"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_enableaddresssuggestions"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_enableincidenttyperecommendation"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_enablelegacyscheduleassistant"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_enablemainformdialogforsubgrids"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_enablesuggestedduration"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_enhancedbackgroundprocessing"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_entitynumberlength"): Xrm.NumberControl;
    getControl(controlName: "msdyn_generateactuals"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_generateagreementinvoicesxdaysinadvance"): Xrm.NumberControl;
    getControl(controlName: "msdyn_generateagreementwoxdaysinadvance"): Xrm.NumberControl;
    getControl(controlName: "msdyn_generatebookingdatesxmonthsinadvance"): Xrm.NumberControl;
    getControl(controlName: "msdyn_generateinvoicedatesxmonthsinadvance"): Xrm.NumberControl;
    getControl(controlName: "msdyn_historicaldatafilter"): Xrm.OptionSetControl<msdyn_fieldservicesetting_msdyn_historicaldatafilter>;
    getControl(controlName: "msdyn_inspectionanalyticsenabled"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_inspectionanalyticsfrequency"): Xrm.OptionSetControl<msdyn_fieldservicesetting_msdyn_inspectionanalyticsfrequency>;
    getControl(controlName: "msdyn_inspectionanalyticsrecommendedtime"): Xrm.DateControl;
    getControl(controlName: "msdyn_internalflags"): Xrm.StringControl;
    getControl(controlName: "msdyn_inventoryadjustmentprefix"): Xrm.StringControl;
    getControl(controlName: "msdyn_inventoryadjustmentstartingnumber"): Xrm.NumberControl;
    getControl(controlName: "msdyn_inventorytransferprefix"): Xrm.StringControl;
    getControl(controlName: "msdyn_inventorytransferstartingnumber"): Xrm.NumberControl;
    getControl(controlName: "msdyn_lastrunofincidenttyperecommendation"): Xrm.DateControl;
    getControl(controlName: "msdyn_name"): Xrm.StringControl;
    getControl(controlName: "msdyn_overtimepaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
    getControl(controlName: "msdyn_productcostorder"): Xrm.OptionSetControl<msdyn_productcostorder>;
    getControl(controlName: "msdyn_purchaseorderapprovalrequired"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_purchaseorderprefix"): Xrm.StringControl;
    getControl(controlName: "msdyn_purchaseorderstartingnumber"): Xrm.NumberControl;
    getControl(controlName: "msdyn_returntopxrecommendations"): Xrm.NumberControl;
    getControl(controlName: "msdyn_rmaprefix"): Xrm.StringControl;
    getControl(controlName: "msdyn_rmastartingnumber"): Xrm.NumberControl;
    getControl(controlName: "msdyn_rtvprefix"): Xrm.StringControl;
    getControl(controlName: "msdyn_rtvstartingnumber"): Xrm.NumberControl;
    getControl(controlName: "msdyn_runfrequencyofincidenttyperecommendation"): Xrm.OptionSetControl<msdyn_fieldservicesetting_msdyn_runfrequencyofincidenttyperecommendation>;
    getControl(controlName: "msdyn_showsimplifiedworkordercommands"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_suggestreparentingcustomerassets"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyn_timecostactualssource"): Xrm.OptionSetControl<msdyn_timecostactualssource>;
    getControl(controlName: "msdyn_timeentrygenerationstrategy"): Xrm.OptionSetControl<msdyn_timeentrygenerationstrategy>;
    getControl(controlName: "msdyn_timestampfrequency"): Xrm.OptionSetControl<msdyn_timestampfrequency>;
    getControl(controlName: "msdyn_travelchargeitemid"): Xrm.LookupControl<"product">;
    getControl(controlName: "msdyn_travelpaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
    getControl(controlName: "msdyn_useofproductsoutofstock"): Xrm.OptionSetControl<msdyn_outofstockoptions>;
    getControl(controlName: "msdyn_workorderinvoicecreation"): Xrm.OptionSetControl<msdyn_autocreateinvoices>;
    getControl(controlName: "msdyn_workorderprefix"): Xrm.StringControl;
    getControl(controlName: "msdyn_workorderstartingnumber"): Xrm.NumberControl;
    getControl(controlName: "msdyn_workpaytype"): Xrm.LookupControl<"msdyn_resourcepaytype">;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: string): undefined;
    getControl(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Control<any>>): Xrm.Control<any>[];
  }
}
