declare namespace Form.uii_hostedapplication.Main {
  namespace Information {
    namespace Tabs {
      interface Hosting extends Xrm.SectionCollectionBase {
        get(name: "AlternateTopLevelWindow"): Xrm.PageSection;
        get(name: "ApplicationHosting"): Xrm.PageSection;
        get(name: "AssemblyInfo"): Xrm.PageSection;
        get(name: "CitrixApplicationSettings"): Xrm.PageSection;
        get(name: "DynamicPositioningAttributes"): Xrm.PageSection;
        get(name: "ExternalApplicationSettings"): Xrm.PageSection;
        get(name: "WebApplicationHomePage"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface TranslationServices extends Xrm.SectionCollectionBase {
        get(name: "tab_6_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface _1becaf090b9b49f180dec827f0acf7bf extends Xrm.SectionCollectionBase {
        get(name: "{10aea57c-4cbd-4f9d-98fe-1445527e4a45}"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface _9c1adb13c3d8de11a89900155d289c61 extends Xrm.SectionCollectionBase {
        get(name: "{08b2d4ae-c5d8-de11-a899-00155d289c61}"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface b49ba11cc3d8de11a89900155d289c61 extends Xrm.SectionCollectionBase {
        get(name: "{4ef881cf-c5d8-de11-a899-00155d289c61}"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface c0330026825742198bc2998017d1b6f7 extends Xrm.SectionCollectionBase {
        get(name: "CIFConfiguration"): Xrm.PageSection;
        get(name: "usdpanel"): Xrm.PageSection;
        get(name: "{04ca7cc4-d509-470c-a65b-76067e429b6e}"): Xrm.PageSection;
        get(name: "{4b8adb5c-c3d8-de11-a899-00155d289c61}"): Xrm.PageSection;
        get(name: "{badd49e5-c3d8-de11-a899-00155d289c61}"): Xrm.PageSection;
        get(name: "{c0330026-8257-4219-8bc2-998017d1b6f7}_section_7"): Xrm.PageSection;
        get(name: "{c6d143eb-c3d8-de11-a899-00155d289c61}"): Xrm.PageSection;
        get(name: "{c7d143eb-c3d8-de11-a899-00155d289c61}"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "msdyusd_allowmultiplepages"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyusd_apiversion"): Xrm.OptionSetAttribute<msdyusd_uii_hostedapplication_msdyusd_apiversion>;
      get(name: "msdyusd_cifurl"): Xrm.Attribute<string>;
      get(name: "msdyusd_crmwindowhosttype"): Xrm.OptionSetAttribute<msdyusd_uii_hostedapplication_msdyusd_crmwindowhosttype>;
      get(name: "msdyusd_customparameters"): Xrm.Attribute<string>;
      get(name: "msdyusd_dashboardname"): Xrm.Attribute<string>;
      get(name: "msdyusd_displayname"): Xrm.Attribute<string>;
      get(name: "msdyusd_hostingtype"): Xrm.OptionSetAttribute<msdyusd_uii_hostedapplication_msdyusd_hostingtype>;
      get(name: "msdyusd_maximumbrowsers"): Xrm.NumberAttribute;
      get(name: "msdyusd_paneltype"): Xrm.OptionSetAttribute<msdyusd_uii_hostedapplication_msdyusd_paneltype>;
      get(name: "msdyusd_prefetchdata"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyusd_savedurl"): Xrm.Attribute<string>;
      get(name: "msdyusd_scanfordataparameters"): Xrm.OptionSetAttribute<boolean>;
      get(name: "msdyusd_trusteddomain"): Xrm.Attribute<string>;
      get(name: "msdyusd_xaml"): Xrm.Attribute<string>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "statecode"): Xrm.OptionSetAttribute<uii_hostedapplication_statecode>;
      get(name: "uii_adaptermode"): Xrm.OptionSetAttribute<uii_hostedapplication_uii_adaptermode>;
      get(name: "uii_adaptertype"): Xrm.Attribute<string>;
      get(name: "uii_adapteruri"): Xrm.Attribute<string>;
      get(name: "uii_applicationhostingmode"): Xrm.OptionSetAttribute<uii_hostedapplication_uii_applicationhostingmode>;
      get(name: "uii_assemblytype"): Xrm.Attribute<string>;
      get(name: "uii_assemblyuri"): Xrm.Attribute<string>;
      get(name: "uii_automationxml"): Xrm.Attribute<string>;
      get(name: "uii_displaygroup"): Xrm.Attribute<string>;
      get(name: "uii_extensionsxml"): Xrm.Attribute<string>;
      get(name: "uii_externalapparguments"): Xrm.Attribute<string>;
      get(name: "uii_externalappuri"): Xrm.Attribute<string>;
      get(name: "uii_externalappworkingdirectory"): Xrm.Attribute<string>;
      get(name: "uii_findwindowclass"): Xrm.Attribute<string>;
      get(name: "uii_hostedapplicationtype"): Xrm.OptionSetAttribute<uii_hostedapplication_uii_hostedapplicationtype>;
      get(name: "uii_icafilename"): Xrm.Attribute<string>;
      get(name: "uii_isappdynamic"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isattachinputthread"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isdependentonworkflow"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isglobalapplication"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_islimittoprocess"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isnomessagepump"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isrestoreifminimized"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isretainframeandcaption"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isretainontaskbar"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isretainsystemmenu"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isshowintoolbardropdown"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isshowmenu"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_isusenewbrowserprocess"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_iswebappusetoolbar"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_mainwindowacquisitiontimeout"): Xrm.NumberAttribute;
      get(name: "uii_managehosting"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_managepopups"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_minimumsizex"): Xrm.NumberAttribute;
      get(name: "uii_minimumsizey"): Xrm.NumberAttribute;
      get(name: "uii_name"): Xrm.Attribute<string>;
      get(name: "uii_optimalsizex"): Xrm.NumberAttribute;
      get(name: "uii_optimalsizey"): Xrm.NumberAttribute;
      get(name: "uii_processacquisitionfilename"): Xrm.Attribute<string>;
      get(name: "uii_remote_processacquisitionattempts"): Xrm.NumberAttribute;
      get(name: "uii_remote_processacquisitiondelay"): Xrm.NumberAttribute;
      get(name: "uii_removesizingcontrols"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_sortorder"): Xrm.NumberAttribute;
      get(name: "uii_toplevelwindowcaption"): Xrm.Attribute<string>;
      get(name: "uii_toplevelwindowmode"): Xrm.OptionSetAttribute<uii_hostedapplication_uii_toplevelwindowmode>;
      get(name: "uii_usercanclose"): Xrm.OptionSetAttribute<boolean>;
      get(name: "uii_webappurl"): Xrm.Attribute<string>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "Languages"): Xrm.SubGridControl<"msdyusd_languagemodule">;
      get(name: "footer_statecode"): Xrm.OptionSetControl<uii_hostedapplication_statecode>;
      get(name: "msdyusd_allowmultiplepages"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyusd_apiversion"): Xrm.OptionSetControl<msdyusd_uii_hostedapplication_msdyusd_apiversion>;
      get(name: "msdyusd_cifurl"): Xrm.StringControl;
      get(name: "msdyusd_crmwindowhosttype"): Xrm.OptionSetControl<msdyusd_uii_hostedapplication_msdyusd_crmwindowhosttype>;
      get(name: "msdyusd_customparameters"): Xrm.StringControl;
      get(name: "msdyusd_dashboardname"): Xrm.StringControl;
      get(name: "msdyusd_displayname"): Xrm.StringControl;
      get(name: "msdyusd_hostingtype"): Xrm.OptionSetControl<msdyusd_uii_hostedapplication_msdyusd_hostingtype>;
      get(name: "msdyusd_maximumbrowsers"): Xrm.NumberControl;
      get(name: "msdyusd_paneltype"): Xrm.OptionSetControl<msdyusd_uii_hostedapplication_msdyusd_paneltype>;
      get(name: "msdyusd_prefetchdata"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyusd_savedurl"): Xrm.StringControl;
      get(name: "msdyusd_scanfordataparameters"): Xrm.OptionSetControl<boolean>;
      get(name: "msdyusd_trusteddomain"): Xrm.StringControl;
      get(name: "msdyusd_xaml"): Xrm.StringControl;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "uii_adaptermode"): Xrm.OptionSetControl<uii_hostedapplication_uii_adaptermode>;
      get(name: "uii_adaptertype"): Xrm.StringControl;
      get(name: "uii_adapteruri"): Xrm.StringControl;
      get(name: "uii_applicationhostingmode"): Xrm.OptionSetControl<uii_hostedapplication_uii_applicationhostingmode>;
      get(name: "uii_assemblytype"): Xrm.StringControl;
      get(name: "uii_assemblyuri"): Xrm.StringControl;
      get(name: "uii_automationxml"): Xrm.StringControl;
      get(name: "uii_displaygroup"): Xrm.StringControl;
      get(name: "uii_extensionsxml"): Xrm.StringControl;
      get(name: "uii_externalapparguments"): Xrm.StringControl;
      get(name: "uii_externalappuri"): Xrm.StringControl;
      get(name: "uii_externalappworkingdirectory"): Xrm.StringControl;
      get(name: "uii_findwindowclass"): Xrm.StringControl;
      get(name: "uii_hostedapplicationtype"): Xrm.OptionSetControl<uii_hostedapplication_uii_hostedapplicationtype>;
      get(name: "uii_icafilename"): Xrm.StringControl;
      get(name: "uii_isappdynamic"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isattachinputthread"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isdependentonworkflow"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isglobalapplication"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_islimittoprocess"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isnomessagepump"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isrestoreifminimized"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isretainframeandcaption"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isretainontaskbar"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isretainsystemmenu"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isshowintoolbardropdown"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isshowmenu"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_isusenewbrowserprocess"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_iswebappusetoolbar"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_mainwindowacquisitiontimeout"): Xrm.NumberControl;
      get(name: "uii_managehosting"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_managepopups"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_minimumsizex"): Xrm.NumberControl;
      get(name: "uii_minimumsizey"): Xrm.NumberControl;
      get(name: "uii_name"): Xrm.StringControl;
      get(name: "uii_optimalsizex"): Xrm.NumberControl;
      get(name: "uii_optimalsizey"): Xrm.NumberControl;
      get(name: "uii_processacquisitionfilename"): Xrm.StringControl;
      get(name: "uii_remote_processacquisitionattempts"): Xrm.NumberControl;
      get(name: "uii_remote_processacquisitiondelay"): Xrm.NumberControl;
      get(name: "uii_removesizingcontrols"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_sortorder"): Xrm.NumberControl;
      get(name: "uii_toplevelwindowcaption"): Xrm.StringControl;
      get(name: "uii_toplevelwindowmode"): Xrm.OptionSetControl<uii_hostedapplication_uii_toplevelwindowmode>;
      get(name: "uii_usercanclose"): Xrm.OptionSetControl<boolean>;
      get(name: "uii_webappurl"): Xrm.StringControl;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "Hosting"): Xrm.PageTab<Tabs.Hosting>;
      get(name: "TranslationServices"): Xrm.PageTab<Tabs.TranslationServices>;
      get(name: "{1becaf09-0b9b-49f1-80de-c827f0acf7bf}"): Xrm.PageTab<Tabs._1becaf090b9b49f180dec827f0acf7bf>;
      get(name: "{9c1adb13-c3d8-de11-a899-00155d289c61}"): Xrm.PageTab<Tabs._9c1adb13c3d8de11a89900155d289c61>;
      get(name: "{b49ba11c-c3d8-de11-a899-00155d289c61}"): Xrm.PageTab<Tabs.b49ba11cc3d8de11a89900155d289c61>;
      get(name: "{c0330026-8257-4219-8bc2-998017d1b6f7}"): Xrm.PageTab<Tabs.c0330026825742198bc2998017d1b6f7>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "msdyusd_allowmultiplepages"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyusd_apiversion"): Xrm.OptionSetAttribute<msdyusd_uii_hostedapplication_msdyusd_apiversion>;
    getAttribute(attributeName: "msdyusd_cifurl"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyusd_crmwindowhosttype"): Xrm.OptionSetAttribute<msdyusd_uii_hostedapplication_msdyusd_crmwindowhosttype>;
    getAttribute(attributeName: "msdyusd_customparameters"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyusd_dashboardname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyusd_displayname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyusd_hostingtype"): Xrm.OptionSetAttribute<msdyusd_uii_hostedapplication_msdyusd_hostingtype>;
    getAttribute(attributeName: "msdyusd_maximumbrowsers"): Xrm.NumberAttribute;
    getAttribute(attributeName: "msdyusd_paneltype"): Xrm.OptionSetAttribute<msdyusd_uii_hostedapplication_msdyusd_paneltype>;
    getAttribute(attributeName: "msdyusd_prefetchdata"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyusd_savedurl"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyusd_scanfordataparameters"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "msdyusd_trusteddomain"): Xrm.Attribute<string>;
    getAttribute(attributeName: "msdyusd_xaml"): Xrm.Attribute<string>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "statecode"): Xrm.OptionSetAttribute<uii_hostedapplication_statecode>;
    getAttribute(attributeName: "uii_adaptermode"): Xrm.OptionSetAttribute<uii_hostedapplication_uii_adaptermode>;
    getAttribute(attributeName: "uii_adaptertype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_adapteruri"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_applicationhostingmode"): Xrm.OptionSetAttribute<uii_hostedapplication_uii_applicationhostingmode>;
    getAttribute(attributeName: "uii_assemblytype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_assemblyuri"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_automationxml"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_displaygroup"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_extensionsxml"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_externalapparguments"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_externalappuri"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_externalappworkingdirectory"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_findwindowclass"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_hostedapplicationtype"): Xrm.OptionSetAttribute<uii_hostedapplication_uii_hostedapplicationtype>;
    getAttribute(attributeName: "uii_icafilename"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_isappdynamic"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isattachinputthread"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isdependentonworkflow"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isglobalapplication"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_islimittoprocess"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isnomessagepump"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isrestoreifminimized"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isretainframeandcaption"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isretainontaskbar"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isretainsystemmenu"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isshowintoolbardropdown"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isshowmenu"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_isusenewbrowserprocess"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_iswebappusetoolbar"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_mainwindowacquisitiontimeout"): Xrm.NumberAttribute;
    getAttribute(attributeName: "uii_managehosting"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_managepopups"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_minimumsizex"): Xrm.NumberAttribute;
    getAttribute(attributeName: "uii_minimumsizey"): Xrm.NumberAttribute;
    getAttribute(attributeName: "uii_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_optimalsizex"): Xrm.NumberAttribute;
    getAttribute(attributeName: "uii_optimalsizey"): Xrm.NumberAttribute;
    getAttribute(attributeName: "uii_processacquisitionfilename"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_remote_processacquisitionattempts"): Xrm.NumberAttribute;
    getAttribute(attributeName: "uii_remote_processacquisitiondelay"): Xrm.NumberAttribute;
    getAttribute(attributeName: "uii_removesizingcontrols"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_sortorder"): Xrm.NumberAttribute;
    getAttribute(attributeName: "uii_toplevelwindowcaption"): Xrm.Attribute<string>;
    getAttribute(attributeName: "uii_toplevelwindowmode"): Xrm.OptionSetAttribute<uii_hostedapplication_uii_toplevelwindowmode>;
    getAttribute(attributeName: "uii_usercanclose"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "uii_webappurl"): Xrm.Attribute<string>;
    getAttribute(attributeName: string): undefined;
    getAttribute(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Attribute<any>>): Xrm.Attribute<any>[];
    getControl(controlName: "Languages"): Xrm.SubGridControl<"msdyusd_languagemodule">;
    getControl(controlName: "footer_statecode"): Xrm.OptionSetControl<uii_hostedapplication_statecode>;
    getControl(controlName: "msdyusd_allowmultiplepages"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyusd_apiversion"): Xrm.OptionSetControl<msdyusd_uii_hostedapplication_msdyusd_apiversion>;
    getControl(controlName: "msdyusd_cifurl"): Xrm.StringControl;
    getControl(controlName: "msdyusd_crmwindowhosttype"): Xrm.OptionSetControl<msdyusd_uii_hostedapplication_msdyusd_crmwindowhosttype>;
    getControl(controlName: "msdyusd_customparameters"): Xrm.StringControl;
    getControl(controlName: "msdyusd_dashboardname"): Xrm.StringControl;
    getControl(controlName: "msdyusd_displayname"): Xrm.StringControl;
    getControl(controlName: "msdyusd_hostingtype"): Xrm.OptionSetControl<msdyusd_uii_hostedapplication_msdyusd_hostingtype>;
    getControl(controlName: "msdyusd_maximumbrowsers"): Xrm.NumberControl;
    getControl(controlName: "msdyusd_paneltype"): Xrm.OptionSetControl<msdyusd_uii_hostedapplication_msdyusd_paneltype>;
    getControl(controlName: "msdyusd_prefetchdata"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyusd_savedurl"): Xrm.StringControl;
    getControl(controlName: "msdyusd_scanfordataparameters"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "msdyusd_trusteddomain"): Xrm.StringControl;
    getControl(controlName: "msdyusd_xaml"): Xrm.StringControl;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "uii_adaptermode"): Xrm.OptionSetControl<uii_hostedapplication_uii_adaptermode>;
    getControl(controlName: "uii_adaptertype"): Xrm.StringControl;
    getControl(controlName: "uii_adapteruri"): Xrm.StringControl;
    getControl(controlName: "uii_applicationhostingmode"): Xrm.OptionSetControl<uii_hostedapplication_uii_applicationhostingmode>;
    getControl(controlName: "uii_assemblytype"): Xrm.StringControl;
    getControl(controlName: "uii_assemblyuri"): Xrm.StringControl;
    getControl(controlName: "uii_automationxml"): Xrm.StringControl;
    getControl(controlName: "uii_displaygroup"): Xrm.StringControl;
    getControl(controlName: "uii_extensionsxml"): Xrm.StringControl;
    getControl(controlName: "uii_externalapparguments"): Xrm.StringControl;
    getControl(controlName: "uii_externalappuri"): Xrm.StringControl;
    getControl(controlName: "uii_externalappworkingdirectory"): Xrm.StringControl;
    getControl(controlName: "uii_findwindowclass"): Xrm.StringControl;
    getControl(controlName: "uii_hostedapplicationtype"): Xrm.OptionSetControl<uii_hostedapplication_uii_hostedapplicationtype>;
    getControl(controlName: "uii_icafilename"): Xrm.StringControl;
    getControl(controlName: "uii_isappdynamic"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isattachinputthread"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isdependentonworkflow"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isglobalapplication"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_islimittoprocess"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isnomessagepump"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isrestoreifminimized"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isretainframeandcaption"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isretainontaskbar"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isretainsystemmenu"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isshowintoolbardropdown"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isshowmenu"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_isusenewbrowserprocess"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_iswebappusetoolbar"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_mainwindowacquisitiontimeout"): Xrm.NumberControl;
    getControl(controlName: "uii_managehosting"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_managepopups"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_minimumsizex"): Xrm.NumberControl;
    getControl(controlName: "uii_minimumsizey"): Xrm.NumberControl;
    getControl(controlName: "uii_name"): Xrm.StringControl;
    getControl(controlName: "uii_optimalsizex"): Xrm.NumberControl;
    getControl(controlName: "uii_optimalsizey"): Xrm.NumberControl;
    getControl(controlName: "uii_processacquisitionfilename"): Xrm.StringControl;
    getControl(controlName: "uii_remote_processacquisitionattempts"): Xrm.NumberControl;
    getControl(controlName: "uii_remote_processacquisitiondelay"): Xrm.NumberControl;
    getControl(controlName: "uii_removesizingcontrols"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_sortorder"): Xrm.NumberControl;
    getControl(controlName: "uii_toplevelwindowcaption"): Xrm.StringControl;
    getControl(controlName: "uii_toplevelwindowmode"): Xrm.OptionSetControl<uii_hostedapplication_uii_toplevelwindowmode>;
    getControl(controlName: "uii_usercanclose"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "uii_webappurl"): Xrm.StringControl;
    getControl(controlName: string): undefined;
    getControl(delegateFunction: Xrm.Collection.MatchingDelegate<Xrm.Control<any>>): Xrm.Control<any>[];
  }
}
